### PR TITLE
fix #2855 - comments > 2Mb

### LINKED ISSUE #2855: Crash report 4.1 - IllegalStateException accessing comment Cursor
[Accessing](https://github.com/wordpress-mobile/WordPress-Android/blob/4.1/WordPress/src/main/java/org/wordpress/android/datasets/CommentTable.java#L321) an OOB row? Weird because [moveToNext](https://github.com/wordpress-mobile/WordPress-Android/blob/4.1/WordPress/src/main/java/org/wordpress/android/datasets/CommentTable.java#L140) just returned true.

```
java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:299)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
       at java.util.concurrent.FutureTask.run(FutureTask.java:239)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:838)
Caused by: java.lang.IllegalStateException: Couldn't read row 3, col 6 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
       at android.database.CursorWindow.nativeGetString(CursorWindow.java)
       at android.database.CursorWindow.getString(CursorWindow.java:518)
       at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:62)
       at org.wordpress.android.datasets.CommentTable.getCommentFromCursor(CommentTable.java:321)
       at org.wordpress.android.datasets.CommentTable.getCommentsForBlog(CommentTable.java:140)
       at org.wordpress.android.ui.comments.CommentAdapter$LoadCommentsTask.doInBackground(CommentAdapter.java:340)
       at org.wordpress.android.ui.comments.CommentAdapter$LoadCommentsTask.doInBackground(CommentAdapter.java:327)
       at android.os.AsyncTask$2.call(AsyncTask.java:287)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:838)
```

### PR DESCRIPTION
**Pull request by maxme**
fix #2855 by deleting big comments and truncating new inserted comments.

New unit test to reproduce the issue.

```shell
git checkout a9f1b03
./gradlew :WordPress:cAT
```
 
You should get 2 failed tests with the same exception as in #2855

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/datasets/CommentTable.java [hunk 1]
```diff
@@ -95,7 +95,7 @@ public static void addComment(int localBlogId, final Comment comment) {
         values.put("comment_id",        comment.commentID);
         values.put("author_name",       comment.getAuthorName());
         values.put("author_url",        comment.getAuthorUrl());
-        values.put("comment",           comment.getCommentText());
+        values.put("comment",           SqlUtils.maxSQLiteText(comment.getCommentText()));
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/datasets/CommentTable.java]: Isn't a max size of 2MB per row? Seems that we're only considering one single column here.

Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/datasets/CommentTable.java]: Yes, it's a 2Mb limit per row, but other fields should be relatively small compared to `commentText` - and we have already a margin for error on the `maxSQLiteText` returned.

**Comment by daniloercoli** [comment]
:shipit:
