### PR TITLE
My Site Dashboard: Phase 2: Address PTR Crash

### LINKED ISSUE #15640: My Site Dashboard: Phase 2: Domain Registration Source refactor
This is a spin off from PR #15601. 

There is an issue with DomainRegistrationSource and the way it is fetching the data. The source uses continuation, but you can only resume a continuation one time and we are trying to resume continuation more than once. We end up with (1) a continuation cancel exception and (2) a illegalStateException (I believe this is the crash that @startuptester experienced) This type of logic worked perfectly fine for non-PTR situations, but once we added the refreshData support, the source falls on its face when switching sites.

In addition to the above issue, there is also some weirdness with distinctUntilChanged(). I'm still not 100% convinced we need to remove this and I'd like to address the issues with the DomainRegistrationSource first.

The above issue is manifested in PTR behavior as specified below.

### Expected behavior
On the My Site tab, expect that a PTR refreshes the view and removes the refreshing indicator from the view.

### Actual behavior
Sometimes the PTR refreshing indicator is still visible after refresh is complete.

### Steps to reproduce the behavior
When switching from free sites to non-free sites

- Login and Select a non-free site (choosing quick start or no quick start doesn't change issue)
- On My Site tab, swipe down to start the PTR
- Swipe down to start the PTR again
- Note the refresh indicator spins indefinitely
OR
- Login and Select a free site (choosing quick start or no quick start doesn't change issue)
- On My Site tab, swipe down to start the PTR
- Note the refresh indicator is removed when refresh is complete
- Using the site switcher, select a non-free site (try premium)
- On My Site tab, swipe down to start the PTR
- Swipe down to start the PTR again
- Note the refresh indicator spins indefinitely (Or you might periodically encounter an app crash)

##### Tested on [device], Android [version], WPAndroid [version]
Samsung S20

Thanks to @startuptester for identifying the bug!!

### PR DESCRIPTION
**Pull request by zwarm**
Fixes #15640 

This PR address the following issues with PTR in the My Site View
(1) Refactors `DomainRegistrationSource`:
- Use a mutableMap of  CancellableContinuation instead of a single continuation. 
- Added a check for duplicate requests for the same site id
- Remove/cancel continuations during OnPlansFetched
(2) Removes `distinctUntilChanged()` when the feature flag is on. Note: This _may_ be a temporary solution and as such, the fun was added to both `MySiteViewModel` and `SiteSourceManager`. A decision will be made shortly on whether this will remain, but for now it solves the issue of partial state updates not making it back to the viewModel and therefore prohibiting the refresh indicator from being removed.

@startuptester - if you have time, do your magic and see if this solves what you were seeing. Thank  you.

This PR goes round trip to the API level, so you will see valid Post cards.  
cc @osullivanchris 

**To test:**
Prerequisites
- Launch the app
- Navigate to My Site -> App Settings -> Debug Settings
- Ensure that the `MySiteDashboardPhase2FeatureConfig` is to set to on
- Restart the app if needed

#### Test 1 - Multiple PTR requests
-  Launch the app
- Navigate to the My Site tab
Repeat the following scenario multiple times
- Swipe down on the view to trigger the refresh
- Note: Refresh indicator is shown and is then removed from the view

#### Test 1 - Switching sites
-  Launch the app
- Navigate to the My Site tab
- Swipe down on the view to trigger the refresh
- Note: Refresh indicator is shown and is then removed from the view
Repeat the following for each type of  site switch ( non-free site to free site, free site to non-free site, non-free site to non-free site, free site to free site )
- Using the site switcher, select a different site 
- Swipe down on the My Site tab view to trigger the refresh 
- Note: Refresh indicator is shown and is then removed from the view

## Regression Notes
1. Potential unintended areas of impact
My site view shows indefinite progress indicator

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual and unit testing

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [X] I have completed the Regression Notes.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteSourceManager.kt [hunk 1]
```diff
@@ -93,6 +93,13 @@ class MySiteSourceManager @Inject constructor(
         quickStartCardSource.refresh()
     }
 
+    private fun <X> LiveData<X>.addDistinctUntilChangedIfNeeded(): LiveData<X> =
```
Comment (ParaskP7) [inline WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteSourceManager.kt]: 1. Suggestion (💡): What about moving this extension outside on this class, but still part of this file, then make it public and share that with with `MySiteViewModel` in order to remove the duplication and as such make it easy to update in the future, or else to not forget to update one if the other is updated. Wdyt?
2. Question (❓): Why do you need the `Transformations.distinctUntilChanged(this)`, wouldn't using the `distinctUntilChanged()` extension directly work at it used to work before?
3. Suggestion (💡): Also as part of the above suggestion, if I may, I want to suggest the following rewrite:

`MySiteSourceManager.kt`
```
fun <X> LiveData<X>.addDistinctUntilChangedIfNeeded(isNeeded: Boolean): LiveData<X> {
    return if (isNeeded) {
        distinctUntilChanged()
    } else {
        this
    }
}

    fun build(coroutineScope: CoroutineScope, siteLocalId: Int?): List<LiveData<out PartialState>> {
        return if (siteLocalId != null) {
            mySiteSources.map { source ->
                source.build(coroutineScope, siteLocalId)
                        .addDistinctUntilChangedIfNeeded(!mySiteDashboardPhase2FeatureConfig.isEnabled())
            }
        } else {
            mySiteSources.filterIsInstance(SiteIndependentSource::class.java).map { source ->
                source.build(coroutineScope)
                        .addDistinctUntilChangedIfNeeded(!mySiteDashboardPhase2FeatureConfig.isEnabled())
            }
        }
    }
```

`MySiteViewModel.kt`
```
    val state: LiveData<MySiteUiState> =
            selectedSiteRepository.siteSelected.switchMap { siteLocalId ->
                val result = MediatorLiveData<SiteIdToState>()
                for (newSource in mySiteSourceManager.build(viewModelScope, siteLocalId)) {
                    result.addSource(newSource) { partialState ->
                        if (partialState != null) {
                            result.value = (result.value ?: SiteIdToState(siteLocalId)).update(partialState)
                        }
                    }
                }
                // We want to filter out the empty state where we have a site ID but site object is missing.
                // Without this check there is an emission of a NoSites state even if we have the site
                result.filter { it.siteId == null || it.state.site != null }.map { it.state }
            }.addDistinctUntilChangedIfNeeded(!mySiteDashboardPhase2FeatureConfig.isEnabled())
```

File: WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt [hunk 2]
```diff
@@ -74,25 +75,32 @@ class DomainRegistrationSource @Inject constructor(
...
-            try {
-                val event = suspendCancellableCoroutine<OnPlansFetched> { cancellableContinuation ->
-                    continuation = cancellableContinuation
-                    fetchPlans(selectedSite)
-                }
-                continuation = null
-                if (event.isError) {
-                    val message = "An error occurred while fetching plans : " + event.error.message
-                    appLogWrapper.e(DOMAIN_REGISTRATION, message)
+        if (continuations[siteLocalId] == null) {
```
Comment (ParaskP7) [inline WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt:85]: 1. Praise (❤️): Great work here!
2. Question (❓): Are we sure that cancelling a continuation is not needed at all anymore?
3. Suggestion (💡): What if the `try/catch` gets extracted into its own `fetchPlans(...)` suspend function to make this `continuations` solution a little bit more visible? For example:
```
        if (continuations[siteLocalId] == null) {
            coroutineScope.launch(bgDispatcher) { fetchPlans(siteLocalId, selectedSite) }
        } else {
            appLogWrapper.d(DOMAIN_REGISTRATION, "A request is already running for $siteLocalId")
        }
```

File: WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt [hunk 3]
```diff
@@ -74,25 +75,32 @@ class DomainRegistrationSource @Inject constructor(
...
+                    when {
+                        event.isError -> {
+                            val message = "An error occurred while fetching plans : " + event.error.message
+                            appLogWrapper.e(DOMAIN_REGISTRATION, message)
+                            postState(DomainCreditAvailable(false))
+                        }
+                        siteLocalId == event.site.id -> {
+                            postState(DomainCreditAvailable(isDomainCreditAvailable(event.plans)))
+                        }
+                        else -> {
```
Comment (ParaskP7) [inline WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt]: Minor (🔍): Next time, please consider adding this extra logic as a part of a separate commit. Else, it can be easily missed.
Suggestion (💡): Consider adding a test for this scenario as well.

File: WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt [hunk 4]
```diff
@@ -34,9 +34,10 @@ class DomainRegistrationSource @Inject constructor(
     private val appLogWrapper: AppLogWrapper,
     private val siteUtils: SiteUtilsWrapper
 ) : MySiteRefreshSource<DomainCreditAvailable> {
-    private var continuation: CancellableContinuation<OnPlansFetched>? = null
     override val refresh: MutableLiveData<Boolean> = MutableLiveData<Boolean>(false)
 
+    private val continuations: MutableMap<Int, CancellableContinuation<OnPlansFetched>?> = mutableMapOf()
```
Comment (ParaskP7) [inline WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt]: 1. Suggestion (💡): Consider the following more compact field definition alternative: `private val continuations = mutableMapOf<Int, CancellableContinuation<OnPlansFetched>?>()`
2. Suggestion (💡): The same applies for the `refresh` field above: `override val refresh = MutableLiveData(false)` PS: And if you like this more compact alternative, consider doing the same on all sources.

File: WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt [hunk 5]
```diff
@@ -74,25 +75,32 @@ class DomainRegistrationSource @Inject constructor(
...
-                } else if (siteLocalId == event.site.id) {
-                    postState(DomainCreditAvailable(isDomainCreditAvailable(event.plans)))
                 }
-            } catch (e: CancellationException) {
-                postState(DomainCreditAvailable(false))
             }
+        } else {
+            appLogWrapper.d(DOMAIN_REGISTRATION, "A request is already running for $siteLocalId")
         }
     }
```
Comment (ParaskP7) [inline WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt:91]: Suggestion (💡): Consider moving the `init { ... }` block and its accompanying `clear()` function to the top (below the fields) so that to increase visibility of the `dispatcher` logic for this source.

PS: If you like that idea, I suggestion doing the same for:
- `ScanAndBackupSource` and its `clear()` function.
- `SelectedSiteSource` and its `init { ... }` block and `clear()` function.

**Review by osullivanchris — APPROVED** [review]
Hey this is looking good @zwarm the refresh behaviour displays as expected.

I'm seeing some flickering on the draft posts, and the card is also not interactive or possible to scroll past. But I reckon that's not related to what you're doing here.

**Review by ParaskP7 — APPROVED** [review]
👋 @zwarm !

I have reviewed and tested this PR as per the instructions, everything works as expected, awesome job! 🌟 🌟 🌟 

-----

I have left a couple of questions (❓), one minor (🔍) comment and a few suggestions (💡) for you to consider. I am going to approve this PR anyway, since none is blocking. I am **NOT** going to merge this PR yet to give you some time to apply any of my suggestions. However, feel free to ignore them and merge the PR yourself.

-----

`EXTRAS`
1. Praise (❤️): Once more, great work, I couldn't for the life of me reproduce the crash or make the pull-to-refresh hang on indefinitely!
2. Suggestions (💡): Most of the suggestions I made in this PR are just nice to have and don't affect the outcome. I can apply some of them on my subsequent PRs, so don't feel the need to do them all, or any, maybe the `addDistinctUntilChangedIfNeeded(...)` if a good one. 🤔

File: WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteSourceManager.kt (hunk 1 above)
Comment (zwarm) [reply WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteSourceManager.kt]: @ParaskP7 - I agree with everything above, and that's why I left the note in the description. Was waiting until after our discussion today to decide if this approach was to be left in place. If we decide to keep it, I will adjust before merging. 👍

File: WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt (hunk 3 above)
Comment (zwarm) [reply WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt]: Good idea. Yeah, until I moved it into the `when` this scenario would have been completed missed.

File: WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt (hunk 5 above)
Comment (zwarm) [reply WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt:91]: You are correct, I could go back and move the logic around, but I assumed the writer followed their own pattern  when it was written ... chicken and egg here. Will someone come after us and prefer things to be moved around to what they think is better organization? 😜  

With that said, I'll be move the logic within this class, but keep the other two sources out of this PR; they are unrelated to the context. Thanks.

File: WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt (hunk 4 above)
Comment (zwarm) [reply WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt]: Sure, I can use the compact definition for this source. Not updating other sources in this PR, they are not related to the context. Thanks.

Comment (zwarm) [reply WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt]: In 492c78d

File: WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt (hunk 5 above)
Comment (zwarm) [reply WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt:91]: In 479221c

File: WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteSourceManager.kt (hunk 1 above)
Comment (ParaskP7) [reply WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteSourceManager.kt]: 👋 @zwarm !

I say, let's keep it, since it doesn't affect `develop` and keep testing it for a few days to figure out if we can work with it, or find any issues, that is in addition to the dimming that happens. Then, we can try and figure out if we can fix the dimming as well and another solution or an update to this current solution. Wdyt?

File: WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt (hunk 5 above)
Comment (ParaskP7) [reply WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt:91]: 👋 @zwarm and thanks!

As far as the `chicken and egg` situation, and having other moved things around, especially in relation to `init { ... }` block I know we are doing the right thing as this need to be on top. The `clear()` function is debatable, I agree. I would just keep it close to the `init { ... }` block since the are grouped together already anyway.

File: WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt (hunk 2 above)
Comment (zwarm) [reply WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt:85]: > Question (❓): Are we sure that cancelling a continuation is not needed at all anymore?

Not directly, but please elaborate if you feel there is a situation I could have missed. 

> Suggestion (💡): What if the try/catch gets extracted into its own fetchPlans(...) suspend function to make this continuations solution a little bit more visible?

Excellent idea in a839061

File: WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt (hunk 3 above)
Comment (zwarm) [reply WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt]: 🤔  That scenario is already covered by `when fetched site is different from currently selected site, don't emit value`, but I think I'm going to review all drs tests. I'm not 100% sure they do exactly what they say - even though they all pass as written.

File: WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteSourceManager.kt (hunk 1 above)
Comment (zwarm) [reply WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteSourceManager.kt]: I added the `Do not merge` until after our discussion

Comment (zwarm) [reply WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteSourceManager.kt]: Committed to the functionality and addressed my original concerns by creating a single extension function. Incorporated @ParaskP7 idea of passing the featureFlag value to the extension directly. 👍  In 1ed958f. Thus I am removing the Do not merge label.

File: WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt (hunk 2 above)
Comment (ParaskP7) [reply WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt:85]: 👋 @zwarm !

> Not directly, but please elaborate if you feel there is a situation I could have missed.

Yeap, I am not sure as well, just making sure we are not missing something... 😅

File: WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt (hunk 3 above)
Comment (ParaskP7) [reply WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt]: Yeap, they do pass, but when a test is passing with or without some main code, then this is a flag that something is not tested. 🤔

File: WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteSourceManager.kt (hunk 1 above)
Comment (ParaskP7) [reply WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteSourceManager.kt]: Great, as discussed, let's revisit that but for now go with it, thank you @zwarm ! 🚀

**Comment by zwarm** [comment]
> Question (❓): Why did you do this update as well @zwarm ? Wouldn't this cause the pull-to-refresh to dismiss even if this is not what we want do to another continuation running in parallel?

As discussed, the try/catch can probably be removed, but it's there for completeness. If we capture an exception, we want make sure we flip the refresh flag off so the refresh indicator doesn't continue indefinitely. Thanks for calling it out. I'll be rewriting the DRS tests to validate and will be pushing as a separate PR. Thanks!

File: WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt (hunk 3 above)
Comment (zwarm) [reply WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt]: Agree 100% - I'll be reworking all the tests in a separate PR. I could add them to this PR if you want instead. I don't mind either wwy.

**Comment by ParaskP7** [comment]
👋 @osullivanchris !

> I'm seeing some flickering on the draft posts

Yes, this flickering is due to how the screen currently works, in respect to refreshing the data. We are going to try and find a better way (if possible) and reduce or get rid of the flickering altogether. 🤞 Working with legacy code is always such a fun exercise!

> and the card is also not interactive

Yes, you are right and we are going to handle this as part of this todo ` Navigate to Edit Post activity on post item click` task here: #15200

> or possible to scroll past.

Yes, you are right and we are going to handle this as part of this todo ` Improve scrolling experience (inner recycler view)` task here: #15625

> But I reckon that's not related to what you're doing here.

Yes, you are right, all the above are updates that we will be doing afterwards, and before shipping this to production, possibly next week. 🤞

**Comment by ParaskP7** [comment]
👋 @zwarm !

Still a 🟢 light from my side and thanks so much for adding all those improvement. Let's wait for Meaghan to test this PR as well and merge this right after! 🥳 

PS: 👋 @startuptester you are probably going to ask the same questions as Chris did, so please check my response to some of those in [this comment](https://github.com/wordpress-mobile/WordPress-Android/pull/15645#issuecomment-985643166) of mine right above.

**Review by startuptester — APPROVED** [review]
Tested all of the listed scenarios with multiple sites on S20 5G
The issues I encountered were the same ones other reviewers mentioned. 

Thanks!
