### PR TITLE
Only offer Like as an action in comment notification if note can be liked

### LINKED ISSUE #4642: Notifications: "Like" should not be an option for comments on Jetpack sites
### Expected behavior

Jetpack does not currently support Comment Likes, so it doesn't make sense for "Like" to be an action on comment notifications for Jetpack sites.

### Actual behavior

In comment notifications (in the notifications tab and push notifications) there is an option to "Like" a comment on a Jetpack site.

Push notification:

Notifications tab:

In contrast, the Comments section for the same Jetpack site does not have the "Like" option:

### Steps to reproduce the behavior

1. On a Jetpack site, make sure the site is set to approve incoming comments
2. From another account, make a comment on the site to trigger a notification
3. Check the notification and confirm it shows the "Like" action

##### Reported by a beta tester [here](https://make.wordpress.org/mobile/2016/10/04/call-for-testing-wordpress-for-android-6-0/#comment-19198)

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #4642 

With the enhancements we made in #4590 we could most probably have the Note payload and look into it to see if the Note is "likeable" by this user, and so we can safely decide whether we need to offer/hide the `Like` button on the Notification layout itself.
If by any chance we can't figure this out by the time we need to draw the notification layout, this PR makes a safe bet by only offering the `Reply` action (which is really the only thing we can know is doable for a Comment at this point).

To test:
1. On a Jetpack site, make sure the site is set to approve incoming comments
2. From another account, make a comment on the site to trigger a notification
3. Check the notification and confirm it doesn't show the "Like" action

Also, repeat the steps 2 and 3 on a wp.com site to get to see the "like" or "approve" actions

### CODE REVIEW

**Comment by daniloercoli** [comment]
Did a quick test and worked fine.

**Comment by mzorz** [comment]
Please check also PR #4656

File: WordPress/src/main/java/org/wordpress/android/WordPressDB.java [hunk 1]
```diff
@@ -907,11 +907,29 @@ public Blog instantiateBlogByLocalId(int localId) {
...
+
+    public int getLocalTableBlogIdForJetpackOrWpComRemoteSiteId(int remoteBlogId) {
+        //first try checking if a jetpack site is configured on this device site list with that remote id
+        // workaround: There are 2 entries in the DB for each Jetpack blog linked with
+        // the current wpcom account. We need to load the correct localID here, otherwise options are
+        // blank
+        int localId = getLocalTableBlogIdForJetpackRemoteID(remoteBlogId, null);
+
+        if (localId == 0) {
+            localId = getLocalTableBlogIdForRemoteBlogId(remoteBlogId);
```
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/WordPressDB.java]: You're right Danilo! I think I coded this solution trying to translate the name of the issue in a direct way. For reference here's the original issue name:

> Notifications: "Like" should not be an option for comments on Jetpack sites

So, what this code does is exactly that: only allow the "Like" option if the post is likeable, *and* this is not a Jetpack site.

That said, I'm following your suggestion and extend the solution for "Like" to be only an option for wp.com sites 👍

**Comment by daniloercoli** [comment]
I think this is ready to be merged, unless @tonyr59h has a different opinion.

**Comment by tonyr59h** [comment]
> I think this is ready to be merged

👍  :shipit:
