### PR TITLE
Fix #2458 - NPE in HtmlToSpannedConverter.startImg

### LINKED ISSUE #2458: Crash report 3.9-rc-1: NPE in HtmlToSpannedConverter.startImg
Probably a side effect introduced by the new media picker:

```
java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:278)
       at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
       at java.util.concurrent.FutureTask.run(FutureTask.java:137)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
       at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.NullPointerException
       at org.wordpress.android.util.HtmlToSpannedConverter.startImg(WPHtml.java:810)
       at org.wordpress.android.util.HtmlToSpannedConverter.handleStartTag(WPHtml.java:652)
       at org.wordpress.android.util.HtmlToSpannedConverter.startElement(WPHtml.java:992)
       at org.ccil.cowan.tagsoup.Parser.push(Parser.java:794)
       at org.ccil.cowan.tagsoup.Parser.rectify(Parser.java:1061)
       at org.ccil.cowan.tagsoup.Parser.stage(Parser.java:1026)
       at org.ccil.cowan.tagsoup.HTMLScanner.scan(HTMLScanner.java:573)
       at org.ccil.cowan.tagsoup.Parser.parse(Parser.java:449)
       at org.wordpress.android.util.HtmlToSpannedConverter.convert(WPHtml.java:552)
       at org.wordpress.android.util.WPHtml.fromHtml(WPHtml.java:159)
       at org.wordpress.android.util.WPHtml.fromHtml(WPHtml.java:122)
       at org.wordpress.android.ui.posts.EditPostPreviewFragment$LoadPostPreviewTask.doInBackground(EditPostPreviewFragment.java:78)
       at org.wordpress.android.ui.posts.EditPostPreviewFragment$LoadPostPreviewTask.doInBackground(EditPostPreviewFragment.java:62)
       at android.os.AsyncTask$2.call(AsyncTask.java:264)
       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
       at java.util.concurrent.FutureTask.run(FutureTask.java:137)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
       at java.lang.Thread.run(Thread.java:856)
```

### PR DESCRIPTION
**Pull request by tonyr59h**
Addresses #2458

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPreviewFragment.java [hunk 1]
```diff
@@ -21,6 +21,7 @@
     private EditPostActivity mActivity;
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPreviewFragment.java]: A future ToDo: get rid of `mActivity` and rely on `getActivity()` instead.

**Comment by nbradbury** [comment]
@tonyr59h The original issue has the 3.9 milestone but this is branched from `develop`. Should it be branched from `release/3.9` instead?

**Comment by maxme** [comment]
> Should it be branched from release/3.9 instead?

Yes, or cherry pick commits in `release/3.9` when it's merged (or ping me ;)).

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPreviewFragment.java [hunk 2]
```diff
@@ -53,14 +54,25 @@ public void onResume() {
...
+        super.onPause();
+
+        if (mLoadTask != null) {
+            mLoadTask.cancel(true);
+            mLoadTask = null;
+        }
     }
 
+    public void loadPost() {
+        if (mLoadTask == null) {
```
Comment (tonyr59h) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPreviewFragment.java]: If there's a load in progress I didn't think it was appropriate to send off another request. When the previous load completes it will set mLoadTask to null and allow another load to take place.

**Comment by tonyr59h** [comment]
> Should it be branched from release/3.9 instead?

Good catch! I'll cherry pick into 3.9 after the merge.

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPreviewFragment.java (hunk 1 above)
Comment (tonyr59h) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPreviewFragment.java]: Should I create an issue for this TODO? Otherwise I don't have high hopes of it being settled.

**Comment by nbradbury** [comment]
@tonyr59h I'll merge into develop :shipit: Ready for you to cherry pick.
