### PR TITLE
Showing better quality for featured image in Post Settings

### LINKED ISSUE #9020: Posts featured image thumbnail doesnt look good
### Expected behavior
The thumbnail view for featured image shouldn't look pixelated in the Post Settings screen.

### Actual behavior
The thumbnail view for featured image after first upload doesn’t look great for featured images on the Settings screen.

screen shot 2019-01-18 at 17 09 54

### Steps to reproduce the behavior
1. start a draft
2. tap on Post settings from the overflow menu
3. set a featured image
4. observe it loads pixelated

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #9020 

The title has it - I only checked what we were using in the Posts list as featured images look good there, and identified and reused the code from `ReaderUtils`.

#### Before
screen shot 2019-01-18 at 18 04 11

#### After
screen shot 2019-01-18 at 18 05 44

To test:
1. start a new draft
2. set a featured image
3. observe the featured image looks good :)

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java [hunk 1]
```diff
@@ -866,14 +866,11 @@ private void updateFeaturedImageView() {
         // Get max width for photon thumbnail
         int width = DisplayUtils.getDisplayPixelWidth(getActivity());
         int height = DisplayUtils.getDisplayPixelHeight(getActivity());
-        int size = Math.max(width, height);
 
         String mediaUri = StringUtils.notNullStr(media.getThumbnailUrl());
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java]: I think the real problem is that we're using `getThumbnailUrl()` for the image URL. Should this be using one of the larger image URLs instead?

Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java]: Well, that seemed ok but apparently `MediaModel` at that stage holds null stuff for all other sizes, look:

screen shot 2019-01-24 at 12 29 51

And this is how it looks like, ofc:

screen shot 2019-01-24 at 12 31 02


I tested this with pics on the device, stock photos, etc.
