### PR TITLE
Zendesk: Fix ticket language id for "he", "id", "yi".

### LINKED ISSUE #10742: Localization: tickets from Indonesian users being assigned deprecated language code `in`
### Expected behavior
The correct ISO 639-1 language code for Indonesian is `id`. Tickets from users with Indonesian set as their app language should show `id` in the `WP Mobile App Language` field in Zendesk.

### Actual behavior
Tickets from Indonesian-speaking WordPress for Android users are showing up in Zendesk with their `WP Mobile App Language` field incorrectly set to `in` (many thanks to @erricgunawan for confirming this). 

Therefore, `in` shows up as a language code in Zendesk reporting as well.

## Steps to reproduce
1) Run the following advanced search in ZD: `custom_field_360008583691:in form:"Mobile Support Form" group:wordpress.com order_by:created sort:asc`
2) Open any ticket and look at the `WP Mobile App Language` field on the sidebar
3) The field will be populated with `in` and not `id`, as it should be

The `WP Mobile App Language` field `(360008583691)`, along with some others, was added in #8161.

I also found this reference in this repo's source code about Java defaulting to the deprecated language code for Indonesian, so just linking it here too, in case it helps - https://github.com/wordpress-mobile/WordPress-Android/blob/50f98a16880a535af82c35f7a81c3c65e592fa9a/libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/LanguageUtils.java#L55-L58

Please let me know if you need any other information from me. Thank you for having a look!

### PR DESCRIPTION
**Pull request by hafizrahman**
Fixes #10742

To test:

Ideally this should be tested by filling the actual contact form using the app while set to use Indonesian language, then see if it gets tagged properly with "id" instead of "in" inside Zendesk. However, I haven't figured out how to set up the Zendesk auth setting properly to allow actual contact submission in my emulator, so I am not able to test it that way so far. Still trying to find more info about it.

I can confirm thru logging that the `LanguageUtils.getPatchedCurrentDeviceLanguage(context))`  function call will then output `id` properly instead of `in`, though. 

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/support/ZendeskHelper.kt [hunk 1]
```diff
@@ -21,6 +21,7 @@ import org.wordpress.android.util.currentLocale
 import org.wordpress.android.util.AppLog
 import org.wordpress.android.util.AppLog.T
 import org.wordpress.android.util.DeviceUtils
+import org.wordpress.android.util.LanguageUtils
```
Comment (shiki) [inline WordPress/src/main/java/org/wordpress/android/support/ZendeskHelper.kt]: It looks like the lint failed because of the unused `import java.util.Locale`. 

Please see [Coding Style](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/docs/coding-style.md) for more info on how to check and fix this locally.

**Comment by hafizrahman** [comment]
Based on some tests, it seems like this PR will then make Indonesian tickets be flagged either with "id" or "id_ID" depending on the device(?).

@erricgunawan @mahangu Can I know how the language custom field is used to filter out the tickets? If the common usage for it is by using the search field, then something like `custom_field_360008583691:id form:"Mobile Support Form" group:wordpress.com order_by:created sort:desc` will catch tickets with both the `id` or `id_ID` flag anyway, and I suppose this will then be a good enough temporary fix.

**Comment by jkmassel** [comment]
Howdy folks! I'm freezing `13.7` today, so this is being bumped to `13.8`. If you'd like it to go out as part of `13.7`, please target `release/13.7` for this PR, and DM me once it's merged – I'll be happy to cut a new beta release!

**Comment by shiki** [comment]
@hafizrahman I think we should just merge this as this fixes the issue. It looks like the second `_ID` is the country. This is standard as described [here](https://www.w3.org/TR/html401/struct/dirlang.html). It's also expected in Java's [Locale](https://docs.oracle.com/javase/7/docs/api/java/util/Locale.html). 

I also looked at the other Zendesk issues and they use similar formats like `vi_VI` for Vietnamese and `en_US` for English. It would be better if the app produces a standard format. 

If you can fix the lint issues, we can merge this. 🙂

File: WordPress/src/main/java/org/wordpress/android/support/ZendeskHelper.kt (hunk 1 above)
Comment (hafizrahman) [reply WordPress/src/main/java/org/wordpress/android/support/ZendeskHelper.kt]: Fixed, thanks for the tips!
