### PR TITLE
Fixed crash when trying to reupload nonexistent media.

### LINKED ISSUE #10609: NullPointerException: Attempt to invoke virtual method 'void org.wordpress.android.fluxc.model.MediaModel.setUploadStat...
Sentry Issue: [WORDPRESS-ANDROID-5RA](https://sentry.io/share/issue/b1ebf02e5bab4b3da5d77b2757a995a8/)

```
NullPointerException: Attempt to invoke virtual method 'void org.wordpress.android.fluxc.model.MediaModel.setUploadState(org.wordpress.android.fluxc.model.MediaModel$MediaUploadState)' on a null object reference
    at org.wordpress.android.ui.posts.EditPostActivity.onMediaRetryAllClicked(EditPostActivity.java:3534)
    at org.wordpress.android.editor.GutenbergEditorFragment$10.onClick(GutenbergEditorFragment.java:456)
...
(2 additional frame(s) were not displayed)

Attempt to invoke virtual method 'void org.wordpress.android.fluxc.model.MediaModel.setUploadState(org.wordpress.android.fluxc.model.MediaModel$MediaUploadState)' on a null object reference
```

### PR DESCRIPTION
**Pull request by khaykov**
Fixes #10609 

When removing an image that failed to upload, we were not removing it from the failed media list, which we use to reupload all media.

To test:
- Turn on airplane mode.
- Start a new post with Block editor.
- Add an image block and add an image from the device.
- Add another image block and add another image from the device.
- Tap on the last image and remove it.
- Tap on the first image and select "RETRY ALL" from the dialog.
- Notice that the app is not crashing.

PR submission checklist:

- [x] I have considered adding unit tests where possible.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jkmassel** [comment]
Howdy folks! I'm freezing `13.7` today, so this is being bumped to `13.8`. If you'd like it to go out as part of `13.7`, please target `release/13.7` for this PR, and DM me once it's merged – I'll be happy to cut a new beta release!

File: libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/GutenbergEditorFragment.java [hunk 1]
```diff
@@ -509,6 +509,7 @@ public void onClick(DialogInterface dialog, int id) {
             public void onClick(DialogInterface dialog, int id) {
                 dialog.dismiss();
                 mEditorFragmentListener.onMediaDeleted(String.valueOf(mediaId));
+                mFailedMediaIds.remove(String.valueOf(mediaId));
```
Comment (mzorz) [inline libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/GutenbergEditorFragment.java]: Note (unrelated) for clarity: while testing this PR step by step, I noticed we should also be doing this when the user taps on the trash bin icon to delete the block (as opposed to "removing" the image from the block, without removing the actual empty image block). 
Given that action isn't related to what this PR specifically fixes, going to check and open a new issue separately if merits.

Comment (mzorz) [reply libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/GutenbergEditorFragment.java]: Tracked this in https://github.com/wordpress-mobile/gutenberg-mobile/issues/1595
