### PR TITLE
Issue/2306 reader feed preview

### LINKED ISSUE #2306: Use new feed endpoint for Reader blog preview
Use new `/read/feed/{feedId}/posts` to get posts in a feed when showing blog preview (currently previewing a feed fails to show its posts).

### LINKED ISSUE #2316: Drop mshot and follower count from reader blog preview
For consistency with the iOS app, drop the mshot and follower count, and show the blavatar.

### PR DESCRIPTION
**Pull request by nbradbury**
Fix #2306 - This started out as a relatively small PR intended to support two new feed-related endpoints (in order fix  problems following & unfollowing feeds), but it ended up turning into something much bigger.

Here's an overview:
* Following & unfollowing a feed now works
* Posts in a feed now appear in the "blog preview"
* Tapping an avatar on a feed post now shows the preview (previously tapping did nothing)
* Removed the follow buttons from the blog lists in the "Tags & Blogs" activity
* A ton of cleanup around the now working feed-related changes

**Update:** I went ahead and included fix #2316 in this PR since it deals with the same area of the reader.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/models/ReaderBlog.java [hunk 1]
```diff
@@ -54,15 +56,22 @@ public static ReaderBlog fromJson(JSONObject json) {
...
+            blog.setFeedUrl(JSONUtil.getString(json, "feed_URL"));
             blog.isJetpack = JSONUtil.getBool(json, "jetpack");
             blog.isPrivate = JSONUtil.getBool(json, "is_private");
             blog.isFollowing = JSONUtil.getBool(json, "is_following");
             blog.numSubscribers = json.optInt("subscribers_count");
         }
 
+        // blogId will be empty for feeds, so set it to the feedId (consistent with /read/ endpoints)
+        if (blog.blogId == 0 && blog.feedId != 0) {
+            blog.blogId = blog.feedId;
```
Comment (blowery) [inline WordPress/src/main/java/org/wordpress/android/models/ReaderBlog.java]: I'm not sure how this is used later, but be very careful that these IDs are not used in the wrong context. Feed ID and Blog ID can and do overlap.

Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/models/ReaderBlog.java]: I think I was pretty careful about that, but it is confusing. The problem for me was this endpoint returns 0 as the blogId for a feed, whereas the read/xxxx endpoints set the blogId to be the same as the feedId. I needed these to be consistent.

Comment (bluefuton) [inline WordPress/src/main/java/org/wordpress/android/models/ReaderBlog.java]: I'm just working on some changes that would set the correct blog_id in the new `/read/following/$site/posts` endpoint wherever we know it, for example in feeds originating from Jetpack sites...so in the future, blogId may not _always_ be 0 for feeds.

Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/models/ReaderBlog.java]: Thanks for the heads up, @bluefuton. That shouldn't be a problem.

**Comment by daniloercoli** [comment]
I found an issue where tapping the "Open in browser" icon doesn't work for some articles in a feed. 
("View original" link works fine on the web version of the Reader).

See video below:

https://cloudup.com/cHwqG11ypsQ

**Comment by daniloercoli** [comment]
Found an issue where adding a feed to the Reader ends with a success, but articles are not in the list. Going back to "Blogs I follow" list doesn't show the newly added feed.
https://cloudup.com/c7V6uORAjSY

Odd thing, I receive emails that I've added a blog to the reader, but the emails points to a wpcom blog :|
screen shot 2015-02-12 at 12 42 26

Video is password protected. Sent the password to you pvt.

**Comment by nbradbury** [comment]
@daniloercoli I've filed a [separate issue](https://github.com/wordpress-mobile/WordPress-Android/issues/2319) for the browser bug since it's unrelated to this PR. I'm still looking into that second bug.

**Comment by nbradbury** [comment]
I believe I figured out the cause of the second bug. When you follow/unfollow a feed from that preview activity, I was incorrectly treating it as a blog instead of feed, resulting in you following the blog whose blog_ID matched the feed_ID of the feed you were viewing (which is why you got that email about Bali's blog). I fixed the problem in that [last commit](https://github.com/wordpress-mobile/WordPress-Android/commit/6877a8cc48bd9a1c93291ac1373afbc3358d2752).

File: WordPress/src/main/java/org/wordpress/android/datasets/ReaderBlogTable.java [hunk 2]
```diff
@@ -90,10 +92,36 @@ public static ReaderBlog getBlogInfo(long blogId, String blogUrl) {
...
-        return SqlUtils.stringForQuery(
-                ReaderDatabase.getReadableDb(), "SELECT blog_url FROM tbl_blog_info WHERE blog_id=?", args);
+    public static long getBlogIdFromUrl(String url) {
+        if (TextUtils.isEmpty(url)) {
+            return 0;
+        }
+        String normUrl = UrlUtils.normalizeUrl(url);
+        String[] args = {normUrl, normUrl};
+        return SqlUtils.longForQuery(ReaderDatabase.getReadableDb(),
+                "SELECT blog_id FROM tbl_blog_info WHERE feed_url=? OR blog_url=?",
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/datasets/ReaderBlogTable.java]: Wonder why we need to check the `feed_url` URL here.  Same consideration on line 113, where there is a check for `blog_url` instead.

Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/datasets/ReaderBlogTable.java]: I added that just in case we could get the ID from the other URL column, but now that you point it out it does seem confusing. I'll update this to only check the appropriate URL column.

**Comment by daniloercoli** [comment]
:shipit:
