### PR TITLE
Hide get started bar with javascript.

### LINKED ISSUE #8233: Hide the "Get started" message after creating a site
### Expected behavior
After creating a site, the user sees the site preview without a "Create your website at WordPress.com" message.

### Actual behavior
After a user creates a site, they see a site preview with a message "Create your website at WordPress.com" and a button "Get started" on top of the screen. After clicking the button, the screen shows a toast “Links are disabled on the preview screen”. 

screenshot_20180824-092616

### Steps to reproduce the behavior
* Create an account
* Go through the site creation flow
* Finish the process
* The Site preview opens.
* The message is visible on top of the screen above the site preview

### PR DESCRIPTION
**Pull request by khaykov**
Fixes #8233 

Hide "Get started" bar using javascript. At least until we implement a proper server-side solution.
This PR uses same approach as [iOS](https://github.com/wordpress-mobile/WordPress-iOS/pull/10040).

[Image from Gyazo](https://gyazo.com/e3d454b40d3f683d6151560dbb8a5198)

To test:

1. Create an account
2. Go through the site creation flow
3. Finish the process
4. The Site preview opens.
5. Make sure the "Get started" bar is not visible at the top of the preview screen.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SiteCreationCreatingFragment.java [hunk 1]
```diff
@@ -228,11 +230,23 @@ private PreviewWebViewClient loadWebview() {
...
 
+    // Hacky solution to https://github.com/wordpress-mobile/WordPress-Android/issues/8233
+    // Ideally we would hide "get started" bar on server side
+    @SuppressLint("SetJavaScriptEnabled")
+    private static void hideGetStartedBar(@NonNull WebView webView) {
+        webView.getSettings().setJavaScriptEnabled(true);
+        String javascript = "document.querySelector('html').style.cssText += '; margin-top: 0 !important;';\n"
+                            + "document.getElementById('wpadminbar').style.display = 'none';\n";
+
+        webView.evaluateJavascript(javascript, null);
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SiteCreationCreatingFragment.java]: Do you think we should disable JS after the changes are made to the doc? 
(Just for a security reason).

Comment (khaykov) [reply WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SiteCreationCreatingFragment.java]: Good call!

**Comment by daniloercoli** [comment]
Looks good! :shipit:
