### PR TITLE
Long title problem on stats cards #16887

### LINKED ISSUE #16887: [android] Long title problem on stats cards
### Expected behavior
The title of the stats cards below should fit in the card.
- Views & Visitors
- Total Likes
- Total Comments
- Total Followers
- Latest Post Summary

### Actual behavior
There is VIEW MORE button on these cards on the main stats screen. There isn't any button on the detail screen but there is still an empty room for the button on the detail screen.

### Steps to reproduce the behavior
1. Launch Jetpack app. 
2. Navigate to stats screen by using quick links or menu.
3. If the cards (mentioned above) are not present, go to the stats management (either through ⚙️ menu at the top right hand corner or Add new stats card at the bottom) and add cards and save, then return to Insights.
4. Check the title in detail screens.
5. Repeat 1-4 for different languages. We know German has a problem with long titles currently.

### PR DESCRIPTION
**Pull request by gitstart**
Fixes #16887 

Title:
[Bug] Long title problem on stats cards

Solution:
Removed the view more button to increase the Title visibility on the stats card.
Added extension function TextView.setTextOrHide(item: BlockListItem.TitleWithMore)

To test:
1. Launch Jetpack app.
2. Navigate to stats screen by using quick links or menu.
3. If the cards (mentioned above) are not present, go to the stats management (either through ⚙️ menu at the top right hand corner or Add new stats card at the bottom) and add cards and save, then return to Insights.
4. Check the title in detail screens.
Repeat 1-4 for different languages. We know German has a problem with long titles currently.

## Regression Notes
1. Potential unintended areas of impact: NONE

2. What I did to test those areas of impact (or what existing automated tests I relied on): Tested Visually

3. What automated tests I added (or what prevented me from doing so): None

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

How to test: https://www.loom.com/share/b523eb404409491e90ced4c843f776d8

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BlockListItemViewHolder.kt [hunk 1]
```diff
@@ -42,6 +43,15 @@ open class BlockListItemViewHolder(
...
 
+    protected fun TextView.setTextOrHide(item: BlockListItem.TitleWithMore) {
+        this.visibility = View.VISIBLE
+        if(item.navigationAction == null){
+            this.ellipsize = null
+            this.maxLines = Int.MAX_VALUE
+        }
+        this.setTextOrHide(item.textResource,item.text)
+    }
+
```
Comment (irfano) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BlockListItemViewHolder.kt]: - Nice! It's good to remove ellipsize end making the text view multiline. 👍🏻 
- I think the function name could be better. This function doesn't only set or hide the text view. It has a specific logic inside.
- Also, this function has a parameter of  `BlockListItem.TitleWithMore` type, so it'll be used only in `TitleWithMore`. We can move this function to `TitleWithMore`. I don't think we can benefit from having this function in `BlockListItemViewHolder`.

**Review by irfano — CHANGES_REQUESTED** [review]
Thanks for handling this, @gitstart.
I reviewed your changes, and it looks very good. I saw that the long title is multiline now. I'd like to see your update of a screenshot in the PR description.

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BlockListItemViewHolder.kt (hunk 1 above)
Comment (gitstart) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BlockListItemViewHolder.kt]: Thank you for reviewing the PR 🙌. 
Will do the changes as requested and push it. 
@irfano

**Comment by gitstart** [comment]
@irfano 
Requested changes added. 🙌
Please take a look.

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/TitleWithMoreViewHolder.kt [hunk 2]
```diff
@@ -17,12 +17,21 @@ class TitleWithMoreViewHolder(parent: ViewGroup) : BlockListItemViewHolder(
     private val viewMore = itemView.findViewById<MaterialButton>(id.view_more_button)
 
     fun bind(item: TitleWithMore) {
-        title.setTextOrHide(item)
+        title.multiLineText(item)
```
Comment (irfano) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/TitleWithMoreViewHolder.kt]: I would suggest moving `setTextOrHide()` call from `TextView.multiLineText` to `bind()` and call them separately. Because it's better to have only one responsibility for each functions. What do you think about this ⬇️?
```
fun bind(item: TitleWithMore) {
       title.setLineCount(item) // same as multiLineText()
       title.setTextOrHide(item) // moved from multiLineText() to here
       ...
```

Comment (gitstart) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/TitleWithMoreViewHolder.kt]: Thank you @irfano for reviewing the PR.
After inspection, I think your suggestion is legit. 
Will do the suggested changes.

**Comment by gitstart** [comment]
Hello @irfano,
Requested changes pushed. Please take a look.
Thank you! 🙌

**Review by irfano — APPROVED** [review]
The fix works great! All CI tests passed. LGTM! 👍🏻

**Comment by AliSoftware** [comment]
🎉  This PR now made it to the `20.9-rc-1` beta.
We will now start the beta-testing phase for version `20.9` (which lasts two weeks) before rolling that version `20.9` out to end users.

Watch https://make.wordpress.org/mobile/ for the upcoming Call for Testing for WPAndroid 20.9 and to learn how to help with the beta test of this version (including your changes from this PR)!
