### PR TITLE
Hide saving dialog on saving finished before preview

### LINKED ISSUE #13320: Cannot exit from previewing changes to a post or page and still continue using the app
Steps to reproduce:

1. Go to My Site > Blog Posts > +.
1. Add a title and some content.
1. Tap the ellipsis menu (top right) > Preview.
1. Tap the arrow at top left to go back.

And:

1. Go to My Site > Blog Posts and open any pre-existing post or page.
1. Make any change to the post.
1. Tap the ellipsis menu (top right) > Preview.
1. Tap the arrow at top left to go back.

**Result:** the app becomes stuck showing a "Saving…" dialog if you try to preview changes to a post before saving and you cannot use the app again until you force close and re-open it. ([2m38s](https://cloudup.com/cob2tEd0EGU))

Screenshot_20201106-115928

<sup>Tested with WPAndroid 16.1-rc-1 on Pixel 3 Android 11 tested on a WordPress.com Simple site madefortesting110620.wordpress.com logged in as user110620.</sup>

### PR DESCRIPTION
**Pull request by planarvoid**
Fixes #13320

Copy changes from https://github.com/wordpress-mobile/WordPress-Android/pull/13331 to a hotfix

To test:

1. Go to My Site > Blog Posts and open any pre-existing post or page.
2. Make any change to the post.
3. Tap the ellipsis menu (top right) > Preview
4. Notice the saving dialog pops up for a short time
5. Notice the preview is opened
6. Tap the arrow at top left to go back.
7. Notice the dialog is hidden

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java [hunk 1]
```diff
@@ -3270,6 +3270,7 @@ private boolean isRemoteAutoSaveError() {
     private PostModel handleRemoteAutoSave(boolean isError, PostModel post) {
         // We are in the process of remote previewing a post from the editor
         if (!isError && isUploadingPostForPreview()) {
+            mViewModel.hideSavingDialog();
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: I'm wondering - don't we need to hide the dialog even when the remote-autosave fails? Or is that handled in a different code path?

Comment (planarvoid) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: I've moved the hideSavingDialog out of the if condition. I don't think all the paths are covered. I'll ping the people responsible for this logic

**Review by malinajirka — APPROVED** [review]
LGTM, thanks!
