### PR TITLE
Users that lack 'publish' capability can't post with the app

### LINKED ISSUE #6011: User who can only "Submit for review" is not able to submit from app
### Expected behavior

If a user has account set up to only "submit for review" and they use the app to create a new post, I would expect the submit button in the app to either say submit but actually only submit for review, or say submit for review and submit for review.

### Actual behavior
The submit button does not function: it appears to work, no errors are explicitly given, but the blog does not get sent to the site at all

### Steps to reproduce the behavior
1) set up user on a self-hosted site who has had "publish_posts" function restricted by plugin. - check the "submit for review" button is showing in the UI
2) link up app
3) Try to "publish" a blog

 ##### Tested on [device], Android [version]

Android Nougat, Self-hosted wordpress.

### PR DESCRIPTION
**Pull request by daniloercoli**
Fixes #6011 by checking the status of the post before sending it to the blog.

We should probably improve this by disabling/enabling items in the post status spinner in a future.

**Test**
- Add a user as Contributor to a blog, and publish with the app. The new post should end up on the blog with the "pending" status.
- Try to modify the status to something != draft or pending. The app should switch it back to pending.

cc @tonyr59h who worked on this https://github.com/wordpress-mobile/WordPress-Android/pull/5430

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java [hunk 1]
```diff
@@ -1032,6 +1032,12 @@ public boolean isNewPost() {
         @Override
         protected Void doInBackground(Void... params) {
 
+            if (!mSite.getHasCapabilityPublishPosts()) {
+               if (PostStatus.fromPost(mPost) != PostStatus.DRAFT && PostStatus.fromPost(mPost) != PostStatus.PENDING) {
```
Comment (tonyr59h) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: We could save a `fromPost` call here by saving the result, but that's a pretty nitpicky change.

**Comment by tonyr59h** [comment]
Since there's nothing but that small nitpick I'm going to go ahead and :shipit:
