### PR TITLE
Fixes: User not guided to Proper tab on Navigation 

### LINKED ISSUE #16288: Quick Start for Existing Users V2  - User is not guided to the proper tab to see the current focus point.
Parent #16347 

### Expected behavior
I would expect to se a focus point on the tab I need to go to complete the current Quick Start task.

### Actual behavior
There is no indication, for certain tasks, that the user needs to switch tabs to see the focus point and complete the task.

In a few tasks, if the user change tabs during the completion of the tasks (it could be either intentionally or accidentally) we are not indicating that the current focus point is in the other tab as we do for some of the tasks like `Customize your site > Visit your site`.

The issue will only happen when a tab different from the Initial Screen is selected before the user clicking `GO` to start the affected tasks. The issue is not reproducible when selecting a specific task from the list, since Quick Start card will only appear in the selected Initial Screen.

Impacted tasks identified so far: 
* `Customize your site > Edit your homepage`
* `Customize your site > Review site pages`
* `Grow your audience > Check your stats`

Expected behavior (reference task): `Customize your site > Visit your site`

### Steps to reproduce the behavior
Initial Screen: `Site Menu`
1. Complete `Customize your site > Check your site title`.
2. Tap `GO` to start the next task.
3. Complete `Customize your site > Choose a unique site icon`.
4. Tap `HOME` tab.
5. Tap `GO` to start the next task.
6. ❌  Notice that no focus point is displayed.
7. Tap `SITE MENU` tab.
8. Notice that the focus point is displayed over `Pages` quick link.

Initial Screen: `HOME`
1. Complete `Customize your site > Check your site title`.
2. Tap `GO` to start the next task.
3. Complete `Customize your site > Choose a unique site icon`.
4. Tap `SITE MENU` tab.
5. Tap `GO` to start the next task.
6. ❌  Notice that no focus point is displayed.
7. Tap `HOME` tab.
8. Notice that the focus point is displayed over `Pages` quick link ribbon card.

### PR DESCRIPTION
**Pull request by AjeshRPai**
Fixes #16288 

This PR fixes the issue where there is no indication, for certain tasks, that the user needs to switch tabs to see the focus point and complete the task. 

This PR introduces a quick start focus point on the Tab header and Snackbar notice with the message to the User to switch to the Tab which holds the Quick start focus point for the Task. 

In a few tasks, if the user changes tabs during the completion of the tasks (it could be either intentionally or accidentally) we are not indicating that the current focus point is in the other tab. The issue will only happen when a tab different from the Initial Screen is selected before the user clicks GO to start the affected tasks. 

The below video capture shows the UI behaviour after the fix. The tab in which the Quickstart focus point is shown is switched and the GO button is clicked. A quick start focus point on SIte Menu tab/ Home tab to indicate the user to switch to the tab. 

https://user-images.githubusercontent.com/17463767/166743251-77c2058a-63c2-4a29-aa0a-e95cc4162b65.mp4

To test:
Steps to reproduce the behavior
Initial Screen: Site Menu
- Complete Customize your site > Check your site title.
- Tap GO to start the next task.
- Complete Customize your site > Choose a unique site icon.
- Tap the HOME tab.
- Tap GO to start the next task.
- Notice that focus point is displayed.
- Tap SITE MENU tab.
- Notice that the focus point is displayed over Pages quick link.

Initial Screen: HOME
- Complete Customize your site > Check your site title.
- Tap GO to start the next task.
- Complete Customize your site > Choose a unique site icon.
- Tap the SITE MENU tab.
- Tap GO to start the next task.
- Notice that the focus point is displayed.
- Tap the HOME tab.
- Notice that the focus point is displayed over the Pages quick link ribbon card.

Merging Instructions:
The issue was introduced as part of the changes for the 19.8 release. It'd be good if we can target frozen branch 19.8.
/cc @AliSoftware

## Regression Notes
1. Potential unintended areas of impact
Quick start focus point not being shown properly 

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual tests and Unit tests 

3. What automated tests I added (or what prevented me from doing so)
Unit tests

PR submission checklist:
- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quickstart/QuickStartRepository.kt [hunk 1]
```diff
@@ -92,7 +92,8 @@ class QuickStartRepository
     val onQuickStartTabStep = _onQuickStartTabStep as LiveData<QuickStartTabStep?>
     val activeTask = _activeTask as LiveData<QuickStartTask?>
     val isQuickStartNoticeShown = _isQuickStartNoticeShown
-    var quickStartTaskOrigin = if (isMySiteTabsEnabled) MySiteTabType.DASHBOARD else MySiteTabType.ALL
+    var currentTab = if (isMySiteTabsEnabled) DASHBOARD else MySiteTabType.ALL
```
Comment (zwarm) [inline WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quickstart/QuickStartRepository.kt]: Nitpick: Can we use the full qualifier for `MySiteTabType.DASHBOARD` here and below + for the places where using `SITE_MENU`. 🙏

**Review by zwarm — APPROVED** [review]
Hi @AjeshRPai - all seems to work as expected. I left a couple of nitpicks, but otherwise all is good. I like what you did with the currentTab instead of origin.I'm going to approve, but not merge so you can decide if you want to make the changes I suggested.

I tested starting on either tab and the focus point appears. Great catch by @tiagomar - and if you have time, we would love a second set of eyes on the fix.

Thanks!

**Comment by tiagomar** [comment]
The fix looks good to me. Nice job @AjeshRPai! Thanks for the ping @zwarm! =)

File: WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quickstart/QuickStartRepository.kt (hunk 1 above)
Comment (AjeshRPai) [reply WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quickstart/QuickStartRepository.kt]: @zwarm I have added the full qualifier in the commit [b946654](https://github.com/wordpress-mobile/WordPress-Android/pull/16462/commits/b946654ea6a2501dd95eadf8c443229633fdde84).

I intentionally kept `SITE_MENU` instead of `MySiteTabType.SITE_MENU` because there were many usages of the enum `MySiteTabType.SITE_MENU` and `MySiteTabType.DASHBOARD`, So I felt that this should make it more readable. 

I would like to know your thoughts on when or if we should import the ENUM constants or always use the full qualifier?.

Comment (zwarm) [reply WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quickstart/QuickStartRepository.kt]: > I would like to know your thoughts on when or if we should import the ENUM constants or always use the full qualifier?.

My thoughts run like this: if we are using the full qualifier then we should use it in every case; otherwise reading it I wonder "Is this a different ENUM constant or does it refer to the same as previous". Which is why it was a nitpick. :)

Thanks.

**Comment by AliSoftware** [comment]
Will a new beta be required for this as soon as it lands, or can it wait a bit for later (in case we have another fix) to avoid doing too many betas close to one another (especially since a rc-2 already went out less than 24h ago)?

**Comment by ashiagr** [comment]
👋 @AliSoftware, it's not super critical, we can wait for a new beta to include any other fix. Thanks!

**Comment by AjeshRPai** [comment]
@AliSoftware  👋🏼  Just a gentle reminder about this PR for `release/19.8` and checking for any updates on when this would land on the `trunk` branch?. 🤔 .

**Comment by AliSoftware** [comment]
Hey @AjeshRPai , thanks for the ping! Yes I plan to do a beta today actually, which will thus include this as well.

To be honest I hoped I'd be able to do a beta yesterday, but some blockers came up with App Center and all. And now I'm just waiting on a [Gutenberg betafix](https://github.com/wordpress-mobile/WordPress-Android/pull/16515) that should also land soon before I trigger the beta in a couple of hours.

Once the beta is done I'll merge the `release/19.8` branch into `trunk`, which will make this PR land there too (I should have merged `release/19.8` to `trunk` earlier tbh, even if no new beta was made since, sorry)

**Comment by AliSoftware** [comment]
For the record, this PR was (finally!) included in the `19.8-rc-3` beta. Sorry for the delay in landing it!
