### PR TITLE
Fix custom app language selection issues across various android versions

### LINKED ISSUE #7267: App language is restored back to default when the app is killed
### Expected behavior
When a user selects a language in the app settings, the language is preserved even when the app is killed.

### Actual behavior
When a user selects a language in the app settings and the app is killed, the app is again in the default language.

### Steps to reproduce the behavior
1. Change language in the settings to Hebrew.
2. Force close/kill the app.
3. Start the app - the app is in the default language.

##### Tested on [device], Android [version]
Emulator - Api 27

Might be related to #7265.

### PR DESCRIPTION
**Pull request by AmandaRiu**
Fixes #7267, #7265 

Updating the language of the App in real time is handled differently across different versions of Android. This PR centralizes language updates to a few new classes:
- BaseActivity
- BaseListActivity
- LocaleManager

Any Activity that should be sensitive to Locale changes should extend either `BaseActivity` or `BaseListActivity`.  

`LocaleManager` contains a set of helper methods/utilities for properly persisting, fetching and applying locale settings appropriate to the active android version. 

`AppSettingsFragment` now calls `System.exit(0)` to force an instance restart of the app so the language of the app is updated instantly, _and_ to give a consistent experience across all versions of Android. 

Once localization was updated to be carried with the active context, I ran into an issue where devices running API 24 & 25 would suddenly crash with a fatal "division by zero" exception while attempting to parse and format a string containing locale-specific grouping separators. For example, the following string: `%,d people like this` would cause a fatal crash while attempting to format it using `String.format(baseString, val)`. Turns out this is a [known Java bug for Android 7.x]("https://bugs.openjdk.java.net/browse/JDK-8167567"). 

The only way around this bug is to pass in the locale to String.format(), *BUT*, Locale.getDefault() will not work when the `language` property of the Locale object contains any regional information. Specifically, it will only work if `language=en` and will not work if `language=en_US`.  Created `LocaleManager.getSafeLocale(context)` to obtain a properly formatted locale object for the workaround and updated any places where this may be a problem by searching for `%,d` in `strings.xml`.

Fix tested on emulators running the following versions: 17, 19, 22, 23, 24, 25, 26, 27

# Screenshots
## API 19
1_screenshot_1520393588 1_screenshot_1520393437

## API 26
1_screenshot_1520394446 1_screenshot_1520394454 1_screenshot_1520394451 1_screenshot_1520394458 1_screenshot_1520394465

# To test:
1. Change language to Hebrew in App Settings. 
2. On devices running 17+, verify RTL layout change.
3. Verify the language is updated througout the app. Pay special attention to: 
		- Labels are updated in the filter bar of the notification tab.
		- Tag options dropdown are updated in the Reader.  
4. Change device orientation. 
5. Verify the language change persists.
6. Kill app and reopen. 
7. Verify the language change persists. 
8. Change the language back to English.
9. repeat steps 2 - 4.

### CODE REVIEW

**Comment by oguzkocer** [comment]
We have been discussing this issue on Slack and I'll just list the alternative solutions we can go about it in the order of my own preference:

1. Drop the language option all together. @nbradbury reminded us that we didn't do that before because we are supporting some languages that doesn't exist in the Android. I'd check the usage rate of these languages and consider if it's worth having the feature.
2. Drop the support for changing language for api levels that don't support it without all this workaround. At least in the latest couple versions it's working as expected. Again we need to check the usage rates, maybe these "extra" languages are only used by recent apis (pretty unlikely but worth a check).
3. Instead of introducing a base activity, I'd add it to each activity. I am almost 50-50 between this and the 4th option, but I really don't like base classes especially for something like activities. I feel like it's more likely for that base activity to become a mess than for us to forget about including the `attachBaseContext` in each activity. I believe this could easily be solved with the linter and there might even be an option to change the new activity template to have it by default. For me it's not too much different than passing the `site` object everywhere.
4. Keep this solution
5. Side note for 3 and 4, I am really worried about killing the process. Is there anything else we can do? Even if it's just showing a dialog to the user that they need to restart the app seems better to me.

I am going to defer this issue to @maxme since he probably knows about this issue more than any of us.

/cc @mzorz

**Comment by AmandaRiu** [comment]
While reviewing the code changes in this PR with @oguzkocer, it was decided that using `System.exit(0)` may be dangerous since it would kill the app instantly and this may cause issues with uploads, notifications, and FluxC jobs. That ended up being a really good call because once I figured out how to remove that and get everything working, the new fix ended up being cleaner and less "hackish" feeling. Much better. Peer reviews FTW! 🎉 

## The How
- Even though the new `context.createConfigurationContext(...)` method was added in API 17, it doesn't fully replace the old way of changing things until Lollipop. If you update one and not the other you either don't see the language update at all, or RTL definitions are not applied. This method now covers those scenarios:
```
private static Context updateResources(Context context, String language) {
    Locale locale = new Locale(language);
    Locale.setDefault(locale);

    Resources res = context.getResources();
    Configuration config = new Configuration(res.getConfiguration());

    // NOTE: Earlier versions of Android require both of these to be set, otherwise
    // RTL may not be implemented properly.
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
        config.setLocale(locale);
        context = context.createConfigurationContext(config);
    }
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.N_MR1) {
        config.locale = locale;
        res.updateConfiguration(config, res.getDisplayMetrics());
    }
    return context;
}
```
- **WordPressUtils -> LanguageUtils.getCurrentDeviceLanguage(...)** is fetching the locale using this logic:
```
public static Locale getCurrentDeviceLanguage(Context context) {
    // better use getConfiguration as it has the latest locale configuration change.
    // Otherwise Locale.getDefault().getLanguage() gets
    // the config upon application launch.
    Locale deviceLocale = context != null ? context.getResources().getConfiguration().locale : Locale.getDefault();
    return deviceLocale;
}
```
For Android 25 and above, this no longer works since the locale is updated differently. Looking at the code comment, the developer was worried that Locale.getDefault() would return an outdated locale, but this was only because the default locale was not being updated when the app language was changed (`Locale.setDefault(locale)`). This has been added so `Locale.getDefault()` will always return the current locale settings no matter the version of Android. So this method should be changed to:
```
public static Locale getCurrentDeviceLanguage(Context context) {
    return Locale.getDefault();
}
```
Technically we no longer need the `context` argument, but since this is a library used by many, maybe leave it and mark it as deprecated. Then have it point to a new method that does not have the `context` argument? 

> **_I haven't added this code change yet because I'm _really_ new to this repo and would like to get some direction before changing it._**

Until it is changed, however, the tag options drop down on the Notification view (and likely other places) will not reflect the app language change until the app is restarted for devices  running API 25 and above.

## Other Changes Included
@oguzkocer requested that I remove `BaseActivity` and `BaseListActivity` because base classes have the potential for abuse and often turn into a nightmare. I understand and respect this position, _BUT_ I must express that I have been brainwashed by the DRY principle so thoroughly that updating 54 classes with these exact 4 lines of code was just soul shattering 💔 
```
@Override
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(LocaleManager.setLocale(newBase));
    }
```
Ok, maybe I _am_ being a _tad bit_ dramatic. In any event, I committed all those changes separately from the main fix just in case someone decides they liked it better the other way 😉 

## Now for some noteworthy funkiness
**code word: Language Toggling**
On Android API 17 & 19, swapping between the same two languages more than once will still work for 95% of the UI, but the filter bar in the Notifications tab will stop updating. I believe this is because the buttons in that bar have static labels with assigned string resources, but I'm not 100% sure why it would work when switching from language A to language B, but not update when switching back to language A. The only thing I can think of is maybe the OS doesn't see it as a language change because it has it cached somewhere. If you go and switch to language C, it will update again just fine. I thought about how I could fix this by maybe creating an event to pass over the EventBus that would force those labels to be redrawn using the current locale, but that seemed like a lot of extra complexity to solve an issue that only happens on really old versions of android and only if the users follows that exact pattern.  

## Emulator Test Results by API
- 16 : 💯   - RTL does not work - functionality not added until 17
- 17, 19 : 👌 - language toggling
- 22, 23, 24 : 💯 
- 25, 26, 27 : 💯 - requires the recommended WordPressUtils fix
- P : 👌 - RTL changes not applied until app restart. Not sure what changed.

**Comment by hypest** [comment]
> Instead of introducing a base activity, I'd add it to each activity... I believe this could easily be solved with the linter

Regardless on which route we'll take on this particular PR, I would like us to explore that ^ idea. I'd love having the linter help us do the right thing while coding and implementing conventions this way sounds awesome!

**Comment by daniloercoli** [comment]
My preference here is to go with option 1. `Drop the language option all together.`.

I suggest to check usage in Tracks (if this is possibile) and if we don't want to kill the feature because it's still used by some of our users, we can just show a dialog that explains to restart the app to apply the changes (if this makes sense). Or limit the feature and patches to latest Android versions. Also mark this feature deprecated and remove it in one year or so.

**Comment by oguzkocer** [comment]
@AmandaRiu I think there was a slight miscommunication because what I was trying to say was I **personally** prefer not to add a base activity, however I am not completely against the idea. As we also discussed on Slack yesterday, I am actually OK with it if all we use it for will be the language issue. I am just worried that once that base activity is there we'll start adding more stuff which will complicate our lives in the long run.

**Comment by maxme** [comment]
I agree that having a `BaseActivity` is not a good idea, and we actually had one a long time ago that was causing problems

I agree that having the same method repeated in all class descending Activity is not a good idea either and very prone to error (unless we had a lint rule, but that kills me a little to add this kind of rules).

I disagree on the removal of the language selector. It's the only way to switch the app to certain languages (because some languages are not supported by in the core settings of Android). We'll also have to drop the work of our translators (we have very active translators for languages that are used by very few users). This would send a bad signal to our users and translators, and this only for avoiding a minor issue.

I think we can live with #7265 (and we could comment on it and mark it with the `won't fix` label, add a toast in the app to explain that, due to some Android limitation, users have to restart the app, etc.). Android < 5.0 represents less than 9% of our users and will decrease even more over time (we might kill support for it soon).

**Comment by maxme** [comment]
BTW, I misread the whole convo

> Drop the support for changing language for api levels that don't support it without all this workaround.

Yes that's an option too, for API levels < 21.

File: WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderSiteHeaderView.java [hunk 1]
```diff
@@ -131,13 +130,15 @@ private void showBlogInfo(ReaderBlog blogInfo) {
...
+            txtFollowCount.setText(String.format(
+                            LocaleManager.getSafeLocale(getContext()),
+                            getContext().getString(R.string.reader_label_follow_count),
+                            blogInfo.numSubscribers));
         } catch (ArithmeticException exception) {
-            // See https://github.com/wordpress-mobile/WordPress-Android/issues/5568
-            // In case of a "ArithmeticException: divide by zero", force the use of "US" locale to format the string.
-            txtFollowCount.setText(String.format(Locale.US, getContext().getString(R.string.reader_label_follow_count),
-                                                 blogInfo.numSubscribers));
+            txtFollowCount.setText(String.format(
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderSiteHeaderView.java]: It looks like our try and catch are the same now. Maybe we don't need the try and catch anymore, but if we do, shouldn't they be different statements?

File: WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderSiteHeaderView.java [hunk 2]
```diff
@@ -131,13 +130,15 @@ private void showBlogInfo(ReaderBlog blogInfo) {
...
 
         try {
-            txtFollowCount.setText(
-                    String.format(getContext().getString(R.string.reader_label_follow_count), blogInfo.numSubscribers));
+            txtFollowCount.setText(String.format(
+                            LocaleManager.getSafeLocale(getContext()),
+                            getContext().getString(R.string.reader_label_follow_count),
+                            blogInfo.numSubscribers));
         } catch (ArithmeticException exception) {
-            // See https://github.com/wordpress-mobile/WordPress-Android/issues/5568
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderSiteHeaderView.java]: If we do need this try/catch I assume we still need to deal with this bug in which case I think we should keep the comment here.

File: WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java [hunk 3]
```diff
@@ -0,0 +1,151 @@
...
+        }
+        return updateResources(context, language);
+    }
+
+    /**
+     * Compare the language for the current context with another language.
+     * @param language The language to compare
+     * @return True if the languages are the same, else false
+     */
+    public static boolean isDifferentLanguage(String language) {
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java]: It might just be me, but I think it'd be better if we had a `isSameLanguage` method instead of `isDifferentLanguage` to avoid the double negative like the one in `AppSettingsFragment`:

```
if (!LocaleManager.isDifferentLanguage(languageCode)) {
    return;
}
```

What do you think?

File: WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java [hunk 4]
```diff
@@ -280,35 +277,17 @@ private void changeLanguage(String languageCode) {
...
-        Locale newLocale = WPPrefUtils.languageLocale(languageCode);
-
-        if (currentLocale.toString().equals(newLocale.getDisplayLanguage())) {
+        if (!LocaleManager.isDifferentLanguage(languageCode)) {
             return;
         }
 
-        if (Locale.getDefault().toString().equals(newLocale.toString())) {
-            // remove custom locale key when original device locale is selected
-            mSettings.edit().remove(LANGUAGE_PREF_KEY).apply();
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java]: I don't think we need this `mSettings` property anymore after these changes. Should we remove that as well?

File: WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java [hunk 5]
```diff
@@ -0,0 +1,151 @@
...
+    /**
+     * Change the active locale to the language provided. Save the updated language
+     * settings to sharedPreferences.
+     * @param context The current context
+     * @param language The 2-letter language code (example "en") to switch to
+     */
+    public static Context setNewLocale(Context context, String language) {
+        Locale newLocale = WPPrefUtils.languageLocale(language);
+
+        if (Locale.getDefault().toString().equals(newLocale.toString())) {
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java]: I think we can use the helper method `isDifferentLanguage` here.

File: WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java [hunk 6]
```diff
@@ -0,0 +1,151 @@
...
+        return updateResources(context, language);
+    }
+
+    /**
+     * Compare the language for the current context with another language.
+     * @param language The language to compare
+     * @return True if the languages are the same, else false
+     */
+    public static boolean isDifferentLanguage(String language) {
+        Locale newLocale = WPPrefUtils.languageLocale(language);
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java]: I know this shouldn't really be a problem (at least not right now), but I am wondering if it's worth to check the emptiness of `language` ourselves instead of letting `WPPrefUtils.languageLocale()` to return the default language to us. Alternatively, it might be even better to just mark the `language` as `@NonNull` so the activity/fragment that's calling this method has to deal with the issue.

To clarify, let's say the current locale is `Turkish` and we somehow passed an empty string to this method, it'll return true since `Turkish` is not the default locale. By handling this case in the method we can return `false` and that'd be good enough. But if we were to change the method to `isSameLocale`, returning `false` in that case is not what we want. So, I feel the `@NonNull` approach is the better one, assuming that it's even worth to do anything here since it will pretty much only prevent developer errors.

File: WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderSiteHeaderView.java (hunk 2 above)
Comment (AmandaRiu) [reply WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderSiteHeaderView.java]: oh yeah good catch. The bug is still relevant, but now it's being properly handled by my `getSafeLocale(...)` method so I can remove this catch altogether.

File: WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java (hunk 6 above)
Comment (AmandaRiu) [reply WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java]: The default locale is the current locale unless the user is in the process of manually changing the language in which case the language string would not be empty and if it were then we wouldn't want to make a change so we would want it to return the default locale. When a new language is requested a locale object is created from that language and then set as the default locale. When the app is closed and restarts, one of the first few things it does during application startup is to check for the presence of a language override, and if it exists, the default locale is set from it immediately.

Also the `@NonNull` would only check for a null object and not an empty string so it wouldn't gain us anything. 🤔 

Oh, but I did move all the language-related methods out of WPPrefUtils since they were all just helper methods for localization and not really relevant to preferences. It's also nice to keep all those methods in one place so developers can find them in the future.

File: WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java (hunk 3 above)
Comment (AmandaRiu) [reply WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java]: Love it...I'll get it updated 💯

File: WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java [hunk 7]
```diff
@@ -0,0 +1,151 @@
...
+import java.util.Locale;
+
+import javax.annotation.Nullable;
+
+/**
+ * Helper class for working with localized strings. Ensures updates to the users
+ * selected language is properly saved and resources appropriately updated for the
+ * android version.
+ */
+public abstract class LocaleManager {
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java]: I forgot to mention this during my review. I am curious about why this class is marked as `abstract`, is there a benefit that I am missing about it? All `abstract` tells me is that we might have a different implementation, something like `WordPressLocaleManager` but we want to be able to pass the `LocaleManager` around instead which I don't think is the case here. I'd love to learn if there are other benefits I didn't know about.

File: WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java (hunk 6 above)
Comment (oguzkocer) [reply WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java]: > The default locale is the current locale unless the user is in the process of manually changing the language in which case the language string would not be empty

That sounds good to me, it was just a thought, because some check outside the control of `isDifferentLanguage` was happening in the `WPPrefUtils.languageLocale` which is always a worrisome thing for me. In this specific case, there is no harm and we don't have to do anything here. Thanks for indulging my question.

> Also the @NonNull would only check for a null object and not an empty string so it wouldn't gain us anything.

It doesn't fully fix it, but it covers half the case. Having said that, I was not really sure about if it's good enough either. I think the move to the `LocaleManager` will help with my concern 👍

File: WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java (hunk 4 above)
Comment (AmandaRiu) [reply WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java]: 👍 Removed

File: WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java (hunk 5 above)
Comment (AmandaRiu) [reply WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java]: Agreed :)

File: WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java (hunk 7 above)
Comment (AmandaRiu) [reply WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java]: It prevents people from instantiating an instance of this class since it's a utility class. I can remove it if you think it's misleading...I think it's one of those things where some developers do it and some do not.

**Comment by AmandaRiu** [comment]
@oguzkocer Implemented suggestions. I also went in and made the suggested changes to WordPressUtils.languageUtils() as explained here:


**WordPressUtils -> LanguageUtils.getCurrentDeviceLanguage(...)** is fetching the locale using this logic:
```
public static Locale getCurrentDeviceLanguage(Context context) {
    // better use getConfiguration as it has the latest locale configuration change.
    // Otherwise Locale.getDefault().getLanguage() gets
    // the config upon application launch.
    Locale deviceLocale = context != null ? context.getResources().getConfiguration().locale : Locale.getDefault();
    return deviceLocale;
}
```

For Android 25 and above, this no longer works since the locale is updated differently. Looking at the code comment, the developer was worried that Locale.getDefault() would return an outdated locale, but this was only because the default locale was not being updated when the app language was changed (Locale.setDefault(locale)). This has been added so Locale.getDefault() will always return the current locale settings no matter the version of Android. So this method should be changed to:

```
public static Locale getCurrentDeviceLanguage(Context context) {
    return Locale.getDefault();
}
```

File: WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java (hunk 7 above)
Comment (oguzkocer) [reply WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java]: Even if we create an instance, we won't be able to do anything with it, but that's a good point. Just for consistency, I think it might still be better not to make it `abstract` as other such classes don't follow that pattern.

P.S: I actually don't know which one I'd prefer if I was working solo in a project 🤔

Comment (AmandaRiu) [reply WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java]: Ok, will do :)

Comment (AmandaRiu) [reply WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java]: Done

File: libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/LanguageUtils.java [hunk 8]
```diff
@@ -1,24 +1,43 @@
...
 
 import android.content.Context;
+import android.support.annotation.Nullable;
 
 import java.util.Locale;
 
 /**
  * Methods for dealing with i18n messages
  */
 public class LanguageUtils {
```
Comment (oguzkocer) [inline libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/LanguageUtils.java]: I was trying to understand the deprecated methods in this class, but I feel like we should drop this all together if we are not going to use it. What do you think?

P.S: I don't think it has to happen in this PR, I'd actually prefer a separate one for this.

File: WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java [hunk 9]
```diff
@@ -0,0 +1,279 @@
...
+    /**
+     * Change the active locale to the language provided. Save the updated language
+     * settings to sharedPreferences.
+     * @param context The current context
+     * @param language The 2-letter language code (example "en") to switch to
+     */
+    public static Context setNewLocale(Context context, String language) {
+        Locale newLocale = languageLocale(language);
+
+        if (Locale.getDefault().toString().equals(newLocale.toString())) {
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java]: I think this change was missed https://github.com/wordpress-mobile/WordPress-Android/pull/7413#discussion_r173547994

File: libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/LanguageUtils.java [hunk 10]
```diff
@@ -1,24 +1,43 @@
...
+     * setting the active locale, the developer should set it in {@link Locale#setDefault(Locale)}.
+     */
+    @SuppressWarnings("DeprecatedIsStillUsed")
+    @Deprecated
+    public static Locale getCurrentDeviceLanguage(@Nullable Context context) {
+        return getCurrentDeviceLanguage();
+    }
+
+    @SuppressWarnings("WeakerAccess")
+    public static Locale getCurrentDeviceLanguage() {
```
[the remark this answers is not in the document]
Comment (oguzkocer) [reply libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/LanguageUtils.java]: Well, I guess we don't know if this class is used at all outside of WPAndroid. Let's skip this change for now.

File: WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java [hunk 11]
```diff
@@ -0,0 +1,279 @@
...
+            languageMap.put(languageCodes[i], languageIds[i]);
+        }
+
+        return languageMap;
+    }
+
+    /**
+     * Generates display strings for given language codes. Used as entries in language preference.
+     */
+    @android.support.annotation.Nullable
```
[the remark this answers is not in the document]
Comment (AmandaRiu) [reply WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java]: ✔️
