### PR TITLE
Fix #2445 - NPE in MediaBrowserActivity

### LINKED ISSUE #2445: Crash report 3.9-rc-1: NPE in MediaBrowserActivity
```
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in org.wordpress.android.ui.media.MediaBrowserActivity$1@424ab198
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:778)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5086)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.NullPointerException
       at org.wordpress.android.ui.media.MediaBrowserActivity$1.onReceive(MediaBrowserActivity.java:80)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:768)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5086)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

### LINKED ISSUE #2458: Crash report 3.9-rc-1: NPE in HtmlToSpannedConverter.startImg
Probably a side effect introduced by the new media picker:

```
java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:278)
       at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
       at java.util.concurrent.FutureTask.run(FutureTask.java:137)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
       at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.NullPointerException
       at org.wordpress.android.util.HtmlToSpannedConverter.startImg(WPHtml.java:810)
       at org.wordpress.android.util.HtmlToSpannedConverter.handleStartTag(WPHtml.java:652)
       at org.wordpress.android.util.HtmlToSpannedConverter.startElement(WPHtml.java:992)
       at org.ccil.cowan.tagsoup.Parser.push(Parser.java:794)
       at org.ccil.cowan.tagsoup.Parser.rectify(Parser.java:1061)
       at org.ccil.cowan.tagsoup.Parser.stage(Parser.java:1026)
       at org.ccil.cowan.tagsoup.HTMLScanner.scan(HTMLScanner.java:573)
       at org.ccil.cowan.tagsoup.Parser.parse(Parser.java:449)
       at org.wordpress.android.util.HtmlToSpannedConverter.convert(WPHtml.java:552)
       at org.wordpress.android.util.WPHtml.fromHtml(WPHtml.java:159)
       at org.wordpress.android.util.WPHtml.fromHtml(WPHtml.java:122)
       at org.wordpress.android.ui.posts.EditPostPreviewFragment$LoadPostPreviewTask.doInBackground(EditPostPreviewFragment.java:78)
       at org.wordpress.android.ui.posts.EditPostPreviewFragment$LoadPostPreviewTask.doInBackground(EditPostPreviewFragment.java:62)
       at android.os.AsyncTask$2.call(AsyncTask.java:264)
       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
       at java.util.concurrent.FutureTask.run(FutureTask.java:137)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
       at java.lang.Thread.run(Thread.java:856)
```

### PR DESCRIPTION
**Pull request by tonyr59h**
Addresses #2445

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java [hunk 1]
```diff
@@ -74,18 +75,20 @@
...
-            String action = intent.getAction();
-            if (ConnectivityManager.CONNECTIVITY_ACTION.equals(action)) {
+            if (ConnectivityManager.CONNECTIVITY_ACTION.equals(intent.getAction())) {
                 // Coming from zero connection. Continue what's pending for delete
-                String blogId = String.valueOf(WordPress.getCurrentBlog().getLocalTableBlogId());
-                if (WordPress.wpDB.getMediaDeleteQueueItems(blogId).getCount() > 0) {
-                    startMediaDeleteService();
+                Blog currentBlog = WordPress.getCurrentBlog();
+
+                if (currentBlog != null) {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java]: This NPE fix looks good. Note, though, that you could skip it entirely by using `WordPress.getCurrentLocalTableBlogId()`. And if you don't mind one more suggestion, I recommend using a more optimal way to detect whether there are pending deletes (since this receiver may fire quite frequently). Ex:

```
private BroadcastReceiver mReceiver = new BroadcastReceiver() {
    @Override
    public void onReceive(Context context, Intent intent) {
        if (ConnectivityManager.CONNECTIVITY_ACTION.equals(intent.getAction())) {
            int blogId = WordPress.getCurrentLocalTableBlogId();
            if (blogId != -1 && WordPress.wpDB.hasMediaDeleteQueueItems(blogId)) {
                startMediaDeleteService();
            }
        }
    }
};
```

Where `WordPress.wpDB.hasMediaDeleteQueueItems` is:

```
public boolean hasMediaDeleteQueueItems(int blogId) {
    return SqlUtils.boolForQuery(db,
            "SELECT 1 FROM " + MEDIA_TABLE + " WHERE uploadState=? AND blogId=?",
            new String[]{"delete", Integer.toString(blogId)});
}
```

**Comment by maxme** [comment]
Please merge this (or cherry pick commits) in `release/3.9`.

File: WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java (hunk 1 above)
Comment (tonyr59h) [inline WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java]: > And if you don't mind one more suggestion

Keep 'em coming ;)

**Comment by nbradbury** [comment]
@tonyr59h This looks good :shipit: I'll merge into develop and you can cherry pick in `release/3.9`.
