### PR TITLE
Select tab on button tap

### LINKED ISSUE #11849: Reader Master Issue: Enable horizontal swipe gesture in the Reader
Goal of this issue is to enable swipe gesture on the Reader and prepare the ground for the Reader Improvements project. We plan to refactor/rewrite one tab (following, discover, ..) at a time so we can release the changes continuously.
The plan for this PR is to introduce a new parent fragment with a tablayout - each tab would be an instance of ReaderPostListFragment. We'll need to do several changes in order to support having multiple instances of the ReaderPostListFragment at the same time. The current implementation uses a single instance of the ReaderPostListFragment and only changes filtering criteria when a different tab is selected.

Note: We started tracking the related PRs and issues in this ticket. However, as the number of issues increased we decided to start creating real issues and adding them to the "Reader Improvements" board. So the list below is not complete.

Created PRs
- https://github.com/wordpress-mobile/WordPress-Android/pull/11840 - Introduce Tablayout in parent fragment
- https://github.com/wordpress-mobile/WordPress-Android/pull/11848 - Remove unnecessary code from ReaderPostListFragment
- https://github.com/wordpress-mobile/WordPress-Android/pull/11867 - Move NewsCard to ReaderFragment
- https://github.com/wordpress-mobile/WordPress-Android/pull/11881 - Bug fixes
- https://github.com/wordpress-mobile/WordPress-Android/pull/11890 - Move SubFilter component into it's own VM
 - https://github.com/wordpress-mobile/WordPress-Android/pull/11890 - Restore lastly selected tab
- https://github.com/wordpress-mobile/WordPress-Android/pull/11902#pullrequestreview-410802534 - Fix "discover" button on the empty screen

Remaining issues
- [x] SubFilter component on the following tab doesn't show any data (the issue is that ReaderPostListViewModel is tied to ReaderPostListFragment's scope but the component is looking for it in WPMainActivity) (fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11872)
- [x] Move "NewsCard" to the ReaderFragment - currently it's shown on all the tabs (fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11867)
- [x] Verify a correct tag is loaded in the subfilter component when you add a new tag in the tag settings(fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11872)
- [x] Move TabLayout into the ReaderFragment (fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11840)
- [x] Move Toolbar into the ReaderFragment (fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11899)
- [x] Revert b558f2a388932508dcb966c20578cf2772be21b2 this commit and come up with a proper fix. (Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11881)
- [x] If I keep switching tabs long enough the app sometime shows "discover" content on all the tabs (it keeps happening quite often on self-hosted site) (fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11890)
- [x] Store and reopen lastly selected tab after app restart (fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11890)
- [x] Verify dark mode - especially subfilter component (fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11899)
---------------------------------------
- [-] The tabs names are different from before (not sure if it is intended), I get the below instead of the Following, Discover, Likes, Saved names (check what field we use for the tab names - also check if translations work, because I had troubles with translations when using a different field for the names) (created issue - https://github.com/wordpress-mobile/WordPress-Android/issues/11905)
- [-] "Time spent in reader" tracking is broken now, since we have multiple instances of the fragment. It should be moved to the ReaderFragment. (created issue - https://github.com/wordpress-mobile/WordPress-Android/issues/11906)
- [-] Saved posts empty screen - "discover" button doesn't work (created issue - https://github.com/wordpress-mobile/WordPress-Android/issues/11900)
- [-] When the user restarts the app and half-swipes in the reader the next fragment isn't pre-loaded (created issue - https://github.com/wordpress-mobile/WordPress-Android/issues/11907)
- [-] Move the Search into the ReaderFragment (Created ticket https://github.com/wordpress-mobile/WordPress-Android/issues/11908)
- [-] Initial/default tab should be discover (created ticket - https://github.com/wordpress-mobile/WordPress-Android/issues/11909)
- [-] When you sign up with a new user and you have no sites the empty states and the content can overlap like this below (they are drawn on top of each other) - HIGH PRIORITY! (created issue - https://github.com/wordpress-mobile/WordPress-Android/issues/11910)
- [-] Verify deeplinks and regular `startActivity` navigation works as expected (created notes on the ReaderImprovements board)
- [-] Verify re-blog feature works as expected(created notes on the ReaderImprovements board)

### PR DESCRIPTION
**Pull request by zwarm**
Fixes #11849 

This PR is part 5.5 of a larger PR that moves the tab layout to a parent.

The approach here was to pass the `ReaderViewModel` to the `ReaderPostListViewModel` and when an empty view button is clicked, send the request back to the observer (`ReaderFragment`) who will then change the selected index of view_pager. This way the normal viewpager handler will take over as if the tab itself was tapped. Note that we do save change the selectedTag value before posting the button tap to the viewmodel.

This may or may not be the best approach, but without knowing what else will change, I felt it was the safest option at the moment. We can revisit the further we get with the tab layout transformation.

Merge Instructions
1. Review this PR
2. Make sure #11890 is merged
3. Change the target branch to master-feature-branch/move-reader-tablayout-to-parent
4. Remove the "Not Ready for merge" label
5. Merge this PR

To test:
1. Log in as a user who is not following any sites
2. Select "Following" tab in the Reader
3. Tap on the Discover button from within the empty slate
4. Notice the "Discover" tab is selected

1. Log in as a user who has not saved any sites
2. Select "Saved" tab in the Reader
3. Tap on the Following button from within the empty slate
4. Notice the "Following" tab is selected
PR submission checklist:

- [ ] I have considered adding unit tests where possible.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderViewModel.kt [hunk 1]
```diff
@@ -44,6 +44,9 @@ class ReaderViewModel @Inject constructor(
     private val _selectTab = MutableLiveData<Event<TabPosition>>()
     val selectTab: LiveData<Event<TabPosition>> = _selectTab
 
+    private val _forceTabSelection = MutableLiveData<Event<ReaderTag>>()
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderViewModel.kt:47]: What if we reused the existing `_selectTab = MutableLiveData<Event<TabPosition>>()` ? The nice thing would be that we'd move the responsibility of mapping `tab -> position` from the view into the VM. Wdyt?

File: WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderViewModel.kt [hunk 2]
```diff
@@ -99,8 +102,14 @@ class ReaderViewModel @Inject constructor(
         return now - lastUpdated > UPDATE_TAGS_THRESHOLD
     }
 
+    fun emptyStateTabChange(tag: ReaderTag) {
+        onTagChanged(tag)
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderViewModel.kt:106]: Do we need to manually call `onTagChanged`? I'd expect when the tab is changed it'll invoke the `onPageChangeCallback` and the tag gets eventually changed. I haven't tested it, so I might be wrong. Let me know what you think ;).

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java [hunk 3]
```diff
@@ -412,6 +414,8 @@ public void onCreate(Bundle savedInstanceState) {
                                        .get(ReaderPostListViewModel.class);
         mNewsCardViewModel = ViewModelProviders.of(requireActivity(), mViewModelFactory)
                                                .get(NewsCardViewModel.class);
+        mReaderViewModel = ViewModelProviders.of(getParentFragment(), mViewModelFactory)
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java:417]: The ReaderPostListFragment is used even on different screens than just the Reader entry point - eg. Open Reader -> Click on a blog title of one of the posts in the discovery tab -> notice ReaderPostListActivity + ReaderPostListFragment gets created. 
I believe the `getParentFragment` might return null as there isn't any parent fragment in this scenario. Even if the parent fragment existed it wouldn't be `ReaderFragment` and ReaderViewModel wouldn't exist so this would create a duplicate of `ReaderViewModel` which would never be used.
One solution is to wrap this into `mIsTopLevel` - it's a flag indicating we are in the top level (Reader entry point) screen. We can discuss other possible solution on a call/slack.

Wdyt?

File: WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderViewModel.kt (hunk 1 above)
Comment (zwarm) [reply WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderViewModel.kt:47]: > What if we reused the existing _selectTab = MutableLiveData<Event<TabPosition>>() ?
I had considered that, but decided against it until the majority of the refactor work was complete. I could just as easily look up the `ReaderViewModel` state in the `ReaderPostListViewModel` to grab the tag tab index.

File: WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderViewModel.kt (hunk 2 above)
Comment (zwarm) [reply WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderViewModel.kt:106]: > Do we need to manually call onTagChanged?

Nope, the callback will take care of it. Going to remove it.

File: WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderViewModel.kt (hunk 1 above)
Comment (zwarm) [reply WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderViewModel.kt:47]: > P.S. I'd consider writing a simple unit test for the changes made in ReaderViewModel. Wdyt?

Agreed, just wanted to put out a PR with where I was before continuing. :)

Comment (zwarm) [reply WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderViewModel.kt:47]: > The other possible approach I was considering would be to use Android navigation 

The main reason I didn't go in this direction was that I wanted the animation to remain the same as if the tab was tapped directly. Just feels smoother. I can go either direction if you want it to change.

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java (hunk 3 above)
Comment (zwarm) [reply WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java:417]: > We can discuss other possible solution on a call/slack.

That would be good because I lack the 'reader' background and your insight is greatly appreciated.

File: WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderViewModel.kt (hunk 1 above)
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderViewModel.kt:47]: >The main reason I didn't go in this direction was that I wanted the animation to remain the same as if the tab was tapped directly. Just feels smoother. I can go either direction if you want it to change.

I'm not sure what you mean. You can play the animation the same way you are playing it now. The only difference would be from where you receive the information that you should change the tab. Can you please elaborate. Thanks!

>I had considered that, but decided against it until the majority of the refactor work was complete. 

I'm just curious what your thoughts on this were. I might be missing something but it seems to me we are creating a duplicate and the only difference is that one LiveData accept ReaderTab and the other position. Right?

>I could just as easily look up the ReaderViewModel state in the ReaderPostListViewModel to grab the tag tab index.

We could also find it within `fun emptyStateTabChange(tag: ReaderTag)` right? So the ReaderViewModel would do derive the position from its internal state, wdyt?

Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderViewModel.kt:47]: We've discussed all these points during the call, so I'm resolving this discussion ;).

**Comment by zwarm** [comment]
> I'd consider writing a simple unit test for the changes made in ReaderViewModel. 

Added unit test in commit 13a422d
