### PR TITLE
fix #2927: Replace the HttpURLConnection call by a synchronized Volley call.

### LINKED ISSUE #2927: Can't Choose to Trush Self Signed SSL
I've had a few reports and have now tested on a couple of test sites.
When you input your credentials it asks if you want to see details, and either accept or not accept the certificate.
Details shows a blank screen and choosing Yes to accept just brings back the same message again.
This is an example line from the app logs:
SSLHandshakeException failed. Erroneous SSL certificate detected.

### PR DESCRIPTION
**Pull request by maxme**
Replace the HttpURLConnection call by a synchronized Volley call.

IMO, the replaement is not as clean as the previous use of HttpURLConnection, but it uses the exact same Http Stack than other logins network calls. That Http Stack uses the underlying TrustUserSSLCertsSocketFactory that allows us to save the state of the latest SSL failure (via setLastFailureChain).

### CODE REVIEW

**Comment by maxme** [comment]
fix #2927

**Comment by daniloercoli** [comment]
I tested the app on our of test sites: 
- If I click "Details" the app takes me to the details screen for the certificate but details are blank.
- When I click "OK" I see the following message in the log

> Add the following certificate to our Certificate Manager: null

And there is the loop...

Is the site misconfigured or we have other issues in the app?

**Comment by daniloercoli** [comment]
Missed the site:
dh.wpmt.co (self-signed & forced ssl)

**Comment by maxme** [comment]
> I tested the app on our of test sites:
> 
> If I click "Details" the app takes me to the details screen for the certificate but details are blank.
> When I click "OK" I see the following message in the log
> Add the following certificate to our Certificate Manager: null
> And there is the loop...

That's weird, this is the behavior I had before the patch on the same site, but with the patch, when I tap `Yes` on the SSL dialog, it works.

File: WordPress/src/main/java/org/xmlrpc/android/ApiHelper.java [hunk 1]
```diff
@@ -1086,21 +1099,41 @@ public static String getXMLRPCUrl(String urlString) throws SSLHandshakeException
...
+                    return null;
+                }
+                // Follow redirect
+                RedirectError re = (RedirectError) e.getCause();
+                if (re.networkResponse != null && re.networkResponse.headers != null
+                        && re.networkResponse.headers.containsKey("Location")) {
+                    String newURL = re.networkResponse.headers.get("Location");
+                    AppLog.i(T.API, "Follow redirect from " + stringUrl + " to " + newURL);
+                    // Abort redirect if old URL was HTTPS and not the new one
+                    if (URLUtil.isHttpsUrl(stringUrl) && !URLUtil.isHttpsUrl(newURL)) {
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/xmlrpc/android/ApiHelper.java]: The value of the Location header could be an absolute or a relative URL. This code seems to work fine on absolute URL redirect only.
See https://blackberry.trac.wordpress.org/browser/trunk/src/com/wordpress/xmlrpc/HTTPPostConn.java#L82

**Comment by daniloercoli** [comment]
:shipit:
