### PR TITLE
Aztec - fix for long titles that are not properly rendered

### LINKED ISSUE #6944: Long post titles are not properly show in Aztec Editors
### Expected behavior
The title field should expand vertically, and take 2 or 3 lines, when the title is long and could not be displayed in one row.

device-2017-12-05-152851

Note that setting the input types to `                 android:inputType="textCapSentences|textMultiLine"` doesn't fix the issue, since WP doesn't have multi lines title concept. We should just make the title field expand vertically if the content doesn't fit. At least do this for at least 3 lines of rows.

 If you hit `Enter` when on the title field, on the web, it does simply add a new space.

### Actual behavior
The title field is one line field, and it scrolls horizontally.

### Steps to reproduce the behavior
Just open a new post with a long title in it.

### PR DESCRIPTION
**Pull request by daniloercoli**
Fixes #6944 by making sure the title field can be expand on multiple lines, and making sure it doesn't accept "New line" characters in it. When a new line is detected a space character is inserted instead.

To test:
Open the editor and try to write a long title, it must expand on more lines. If you try to insert enter it does insert a space.

cc @mzorz - This PR uses input filter ;)

### CODE REVIEW

File: libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java [hunk 1]
```diff
@@ -276,6 +281,35 @@ public void setAztecVideoLoader(Html.VideoThumbnailGetter videoLoader) {
         this.aztecVideoLoader = videoLoader;
     }
 
+    private InputFilter replaceEnterKeyWithSpaceInputFilter = new InputFilter() {
+        @Override
+        public CharSequence filter(CharSequence source, int start, int end,
+                                   Spanned dest, int dstart, int dend) {
+            //  You sometimes get a SpannableStringBuilder, sometimes a plain String in the source parameter
+            if (source instanceof SpannableStringBuilder) {
```
Comment (maxme) [inline libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java]: I've read the comment, but I wonder if we're adding spans to the title and that's why we sometimes have a plain string or a spannable. I don't think any span is needed for the title so maybe that exhibits an underlying issue.

I also wonder if we should use a simple EditText for the title as we don't need Aztec features there, cc @0nko maybe I'm missing something.

**Comment by maxme** [comment]
This looks a bit weird with the "?" button, but we're probably going to drop the button anyway.

File: libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java (hunk 1 above)
Comment (daniloercoli) [reply libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java]: The Android doc says it could be a SpannableStringBuilder or a simple string, so i've added both cases to be sure. 

If we decide to drop Aztec in favour of EditText, the code that replaces `Enter` with `Space` is also required, since we will have the same issue on longer titles. This PR should not change much, I guess at all.

Comment (maxme) [reply libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java]: Yep I read the doc, but we get a `SpannableStringBuilder` because there is a span in that source string. I don't think there should be one in there, that's why I'm a bit worried.

Comment (daniloercoli) [reply libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java]: I've replaced AztecText with EditText and once `Enter key` is entered in the title we get `SpannableStringBuilder`. I guess it's the Android FW that adds it.

Comment (maxme) [reply libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java]: Argh, ok that's weird.

**Comment by maxme** [comment]
Looks good - :shipit:

File: libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java (hunk 1 above)
Comment (0nko) [reply libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java]: Good call on changing it to EditText 👍
