### PR TITLE
Fix possible NPE in PublicizeUpdateService

### LINKED ISSUE #6148: Crash report 7.7-rc-2: NPE in PublicizeUpdateService.onHandleIntent
```
Fatal Exception: java.lang.NullPointerException
       at org.wordpress.android.ui.publicize.services.PublicizeUpdateService.onHandleIntent(PublicizeUpdateService.java:69)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:60)
```

### PR DESCRIPTION
**Pull request by oguzkocer**
Fixes #6148. This is an interesting crash as in I don't think it's supposed to happen. I opted to add a null check in `PublicizeListActivity` instead of doing just before the `site.getSiteId()` call in `PublicizeUpdateService`. This is a pattern we use in a lot of places and I thought it'd be better to just bail out from the activity if somehow the site is `null`. Also, the code seems to be changed since the crash happened, so I wasn't completely sure if it still is a valid crash.

To test:
* Go to sharing in blog settings and make sure it doesn't crash. I don't think there is anything else to test here.

/cc @nbradbury

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeListActivity.java [hunk 1]
```diff
@@ -59,6 +58,10 @@ public void onCreate(Bundle savedInstanceState) {
             mSite = (SiteModel) getIntent().getSerializableExtra(WordPress.SITE);
             PublicizeTable.createTables(WordPress.wpDB.getDatabase());
             showListFragment();
+            if (mSite == null) {
+                ToastUtils.showToast(this, R.string.blog_not_found, ToastUtils.Duration.SHORT);
+                finish();
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeListActivity.java]: There needs to be a `return` statement after this `finish()`.

Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeListActivity.java]: :facepalm:

I force pushed the change to avoid the extra commit.

**Comment by nbradbury** [comment]
:shipit:
