### PR TITLE
Fix pages in offline mode

### LINKED ISSUE #8521: Pages screen: incorrect handling of offline
### Expected behavior
The app should communicate what's the result of an action, if it could or could not handle it as per the user's request.

### Actual behavior
When offline, trying to trash / move to draft a Page makes it disappear and re-appear quickly, without any other indication that the app could not perform the requested action.
Furthermore, if you then decide to leave the screen (go back to Main screen), a snackbar appears saying "Draft saved to device" which doesn't look related to what the action was.

snackbar

### Steps to reproduce the behavior
1. turn airplane mode ON
2. go again to the Pages screen
3. now you'll see the overflow menu icon showing for the items in the list
4. try to move to draft, or move to trash. You'll see the item briefly disappears but then reappears. No error is displayed.
5. go back to main screen. Observe a "draft saved on device" snackbar appears.

### PR DESCRIPTION
**Pull request by 0nko**
Fixes #8521.

image

### To test:

1. Turn airplane mode ON
2. Go to the Pages screen
3. Now you'll see the overflow menu icon showing for the items in the list
4. Try to move to draft, or move to trash
5. Notice a snackbar message pops up, informing that the device is offline
6. Try to refresh the pages
7. Again, notice a snackbar message pops up, informing that the device is offline

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt [hunk 1]
```diff
@@ -351,8 +384,10 @@ class PagesViewModel
     }
 
     private fun publishPageNow(remoteId: Long) {
-        pageMap[remoteId]?.date = Date()
-        changePageStatus(remoteId, PageStatus.PUBLISHED)
+        performIfNetworkAvailable {
+            pageMap[remoteId]?.date = Date()
+            changePageStatus(remoteId, PageStatus.PUBLISHED)
+        }
```
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt]: what id there's no network available but only right at this moment, should we return something, or tell something to the user?

Comment (0nko) [reply WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt]: `performIfNetworkAvailable` is a function. It [prints a message](https://github.com/wordpress-mobile/WordPress-Android/pull/8936/files/909ed4e14ad3188f7eeea9463f037f82288868da#diff-2b7e7932d5393c1ad246d3584ccf8cecR359) if the network's down.

Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt]: Yes saw that later so I resolved to continue and merge, then forgot to make the clarification here. Thanks!
