### PR TITLE
7.3 - Fix pictures orientation issues

### LINKED ISSUE #5737: Orientation isn't correct when uploading photos sometimes
> In Aztec, the vertical photo did appear in the media selector sideways, but when I added it to the post it showed up immediately with a vertical orientation. In Visual, the vertical photo appeared vertical in the media selector; when I added it to the post it showed up sideways while it uploaded, but after the upload finished it appeared in the post with a vertical orientation.

A report from @rachelmcr 

Version 7.1, Samsung devices SM-G920F & SM-G903F

@nbradbury/@aforcier any ideas? Which part of the app is likely responsible: the editor or the media picker?

### PR DESCRIPTION
**Pull request by daniloercoli**
Fixes #5737 by rotating the picture according to the picture EXIF metadata field named `Orientation	` 
Rotation of the picture is not necessary if the `optimize picture` feature is set to ON, since it already rotates the picture.

Things we need to fix soon:
- This is just a quick fix for 7.3,i'm going to investigate a better way to fix the issue, since the current implementation uses an additional file in `cache` folder. It also erases EXIF metadata.
- `MediaBrowserActivity` should call the same function before adding a media from device library.
- Not strictly related to this PR, but we we need to provide a way of cleaning the `cache` folder.

### CODE REVIEW

File: libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/ImageUtils.java [hunk 1]
```diff
@@ -719,4 +719,92 @@ public static int getMaximumThumbnailWidthForEditor(Context context) {
...
+        // Do not rotate portrait pictures
+        if (orientation == 0) {
+            return  null;
+        }
+
+        File resizedImageFile;
+        FileOutputStream out;
+
+        try {
+            resizedImageFile = File.createTempFile("wp-image-", "." + fileExtension);
```
Comment (maxme) [inline libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/ImageUtils.java]: We should reuse the same file name - note: I'm ok to merge this for 7.3 and open another issue.

**Comment by maxme** [comment]
Confirmed, this fix the issue, but we should implement a proper solution for a future version. @daniloercoli can you open a new issue?

:shipit:

**Comment by daniloercoli** [comment]
Created! https://github.com/wordpress-mobile/WordPress-Android/issues/5855
