### PR TITLE
Making sanitizeMediaUploadStateForSite run on first run

### LINKED ISSUE #6794: Async media: force stop leaves inconsistent state
### Expected behavior
If the app is stopped while an upload is happening, it should recover gracefully next time it's opened.

### Actual behavior
A post that was uploading in the middle of the app being stopped shows as "normal" in the Posts list, but entering the editor shows the cancelled media.

### Steps to reproduce the behavior
- start a draft with multiple media
- force stop the app
- start the app again
- see the post is not marked failed
- edit it
- see all media is marked failed
- exit the editor
- see the post list still doesn’t show the Post as failed

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #6794 

The code to sanitize the state was already there, but when you run the app for the first time the code for  the lifecycle listener `appComesFromBackground` is not executed. If OTOH you open the app, send it to the background, and then bring it to the foreground again, the code would be executed, thus showing the right information in the Posts list screen.

With this PR, having the app be force-stopped and then launched again will make the errors visible right away on the first run.

To test:
1. open the app and start a new draft
2. include some media in it
3. exit the editor
4. while uploads are still happening, go to Settings->Apps->WordPress-> tap FORCE STOP and answer "OK"  to the confirm dialog.
5. launch the app again
6. go to the Posts list screen
7. observe the Post that was uploading shows an error in the Posts list.

cc @daniloercoli

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/WordPress.java [hunk 1]
```diff
@@ -286,6 +289,14 @@ public void onLog(T tag, LogLevel logLevel, String message) {
         mCredentialsClient.connect();
     }
 
+    private void sanitizeMediaUploadStateForSite() {
+        int siteLocalId = AppPrefs.getSelectedSite();
+        SiteModel selectedSite = mSiteStore.getSiteByLocalId(siteLocalId);
+        if (selectedSite != null) {
+            UploadService.sanitizeMediaUploadStateForSite(mMediaStore, mDispatcher, selectedSite);
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/WordPress.java]: I think performance is important since this is being called at startup and resume. Can this routine run in the background?

Also, we can exit [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java#L379) if both `uploadingMedia` and `queuedMedia` are empty (which will most likely be the case).

Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/WordPress.java]: background running addressed  in 933d71b
addressed the empty arrays case in 9f69224

**Comment by nbradbury** [comment]
:shipit:
