### PR TITLE
Issue/3263 reader janky subs viewpager

### LINKED ISSUE #3263: Reader: UI momentarily frozen on Followed Sites
Nexus 4, OS 5.1.1

To reproduce:
Switch to the Reader tab
Tap the gear icon to view the menu. 
Swipe twice right until you are viewing Sites You May Like
Swipe once left to view Followed Sites
The screen is now briefly frozen

Happens when logged in to WPcom and when not.

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #3263 - jank was due to the first fragment being destroyed when you swipe to the last tab, forcing it to be recreated when you swipe back again (similarly for the last fragment when you swipe to the first tab).

Resolved by using `setOffscreenPageLimit` on the activity's ViewPager to keep the fragments in memory.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderBlogFragment.java [hunk 1]
```diff
@@ -119,7 +119,7 @@ public void onResume() {
     }
 
     void refresh() {
-        if (hasBlogAdapter()) {
+        if (hasBlogAdapter()) {AppLog.d(AppLog.T.READER, "reader subs > refreshing blog fragment " + getBlogType().name());
```
Comment (tonyr59h) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderBlogFragment.java]: nitpick; newline

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderSubsActivity.java [hunk 2]
```diff
@@ -82,6 +85,7 @@ protected void onCreate(Bundle savedInstanceState) {
         restoreState(savedInstanceState);
 
         mViewPager = (WPViewPager) findViewById(R.id.viewpager);
+        mViewPager.setOffscreenPageLimit(NUM_TABS - 1);
```
Comment (tonyr59h) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderSubsActivity.java]: If the tabs are subject to change it might be safer to use `setOffscreenPageLimit(mPagerAdapter.getCount());` after setting the adapter.

Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderSubsActivity.java]: Sorry, I don't grok that. Could you explain further?

Comment (tonyr59h) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderSubsActivity.java]: If the tab count ever changes we won't have to worry about updating `NUM_TABS`, just one less chance for human error.

Comment (tonyr59h) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderSubsActivity.java]: But it's really a minor thing, I'm happy to close :smiley:

**Comment by tonyr59h** [comment]
:shipit:

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderSubsActivity.java (hunk 2 above)
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderSubsActivity.java]: Ah, okay I see where you're coming from with avoiding `NUM_TABS`. But looking at the ViewPager source code, it's better to call `setOffscreenPageLimit` before the adapter is assigned if you know the number of pages. Setting the offscreen page limit calls the ViewPager's [populate](http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/4.0.1_r1/android/support/v4/view/ViewPager.java#607) method, which does a lot of extra work when the adapter has been assigned,

Comment (tonyr59h) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderSubsActivity.java]: Good to know!
