### PR TITLE
Use site's title for domain suggestions primer

### LINKED ISSUE #7344: Site Creation: use site title for domain suggestions primer
### Expected behavior
Domain suggestions for site-creation should use the user-provided site title as a primer.

### Actual behavior
User's username is used as a primer.

### Steps to reproduce the behavior
1. Add a new wpcom site via the Site Picker
2. Follow the wizard steps and input a site title as normal
3. Notice that the domain suggestions that follow are based on your username instead of the site title.

##### Tested on [device], Android [version]
Nexus 5X, Android 7.1.2

### PR DESCRIPTION
**Pull request by hypest**
Fixes #7344 

To test:
* Follow the steps in the ticket and notice that the suggestions offered are now based on the site title

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/SiteCreationActivity.java [hunk 1]
```diff
@@ -183,7 +183,7 @@ public void withSiteDetails(String siteTitle, String siteTagline) {
         mSiteTitle = siteTitle;
         mSiteTagline = siteTagline;
 
-        SiteCreationDomainFragment fragment = SiteCreationDomainFragment.newInstance(mUsername);
```
Comment (theck13) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/SiteCreationActivity.java]: Now that `mUsername` is no longer used here, we can remove it from the class completely as well as the `ARG_USERNAME` constant since they are only being used to assign the `mUsername` value [here](https://github.com/wordpress-mobile/WordPress-Android/blob/583ac592887704b88585ebf1095d933cccf9764c/WordPress/src/main/java/org/wordpress/android/ui/accounts/SiteCreationActivity.java#L50), but never accessed.

I know it's not part of these changes, but the `mSiteDomain` variable falls into the same category; it's assigned, but never accessed and can be removed.

**Comment by hypest** [comment]
> Can we remove it there as well or is it used elsewhere?

Yes, we can remove those, good catch! Gone with 6105996.

Ready for another pass @theck13 , thanks!
