### PR TITLE
[Gutenberg] Add new block type badge to block inserter list

### LINKED ISSUE #30627: Add the "New" Block Badge
## What problem does this address?
The mobile editor is a powerful tool for creating content, but many users fail to understand the extent of what they can do with it. 

## What is your proposed solution?
We will display a "new" badge on blocks that were recently added to the editor to help users discover different blocks. 

Mobile new block badge

### PR DESCRIPTION
**Pull request by dcalhoun**
* **Gutenberg:** https://github.com/WordPress/gutenberg/pull/33119
* **Gutenberg Mobile:** https://github.com/wordpress-mobile/gutenberg-mobile/pull/3720
* **WPiOS:** https://github.com/wordpress-mobile/WordPress-iOS/pull/16857
* **WPAndroid:** Self

Fixes WordPress/gutenberg#30627. Add badge to showcase new block types. 

To test: See https://github.com/WordPress/gutenberg/pull/33119. 

## Regression Notes
1. Potential unintended areas of impact
  Modifications to the Gutenberg view and settings could cause disruption initializing the editor. 
2. What I did to test those areas of impact (or what existing automated tests I relied on)
  Verified the editor loaded without issue and successfully modified/saved post content. 
3. What automated tests I added (or what prevented me from doing so)
  None, as this feature is experimental at this time and any tests would be implemented in the Gutenberg editor repo.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java [hunk 1]
```diff
@@ -125,6 +130,7 @@
         SHOULD_AUTO_ENABLE_GUTENBERG_FOR_THE_NEW_POSTS_PHASE_2,
         GUTENBERG_OPT_IN_DIALOG_SHOWN,
         GUTENBERG_FOCAL_POINT_PICKER_TOOLTIP_SHOWN,
+        GUTENBERG_BLOCK_TYPE_IMPRESSIONS,
```
Comment (mchowning) [inline WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java]: Because this is a `DeleteablePrefKey` this will get reset if the user logs in and logs out. This is a bit of an edge case, but a user who regularly switches accounts would have the impressions reset each time they switched. I wonder if we would be better off making this an `UndeleteablePrefKey` so the preferences would persist even if they switched accounts.

Comment (dcalhoun) [reply WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java]: @mchowning good thought. Persisting the value throughout the life of the app install was my original intent. I agree that resetting this value when a user logs out would likely be unexpected. I will update the value to be an `UndeleteablePrefKey`.

Comment (dcalhoun) [reply WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java]: Addressed in https://github.com/wordpress-mobile/WordPress-Android/pull/15038/commits/03dee0565ec8325a0f515dd94be5a298f00badd9.

File: libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragmentAbstract.java [hunk 2]
```diff
@@ -219,6 +219,8 @@ public static MediaType getEditorMimeType(MediaFile mediaFile) {
         void onReplaceStoryEditedBlockActionSent();
         void onReplaceStoryEditedBlockActionReceived();
         boolean showPreview();
+        Map<String, Double> onRequestBlockTypeImpressions();
+        void onSetBlockTypeImpressions(Map<String, Double> impressions);
```
Comment (mchowning) [inline libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragmentAbstract.java:223]: Just FYI: Instead of redeclaring these methods, we could have this interface extend the `OnBlockTypeImpressionsEventListener` interface. Doing that would also allow us to just pass the `editorFragmentListener` as the implementation of the `OnBLockTypeImpressionsEventListener` interface directly instead of creating an anonymous implementation of the interface in `GutenbergEditorFragment::onCreateView`. I created a commit showing what this would look like [here](https://github.com/wordpress-mobile/WordPress-Android/commit/32265822f6a020e6b44f5c8fdbeb5267337e06eb).

I think this is a nice change, but no strong feelings. Definitely not a blocker, so only make this change if you like it better. 🙂

**Review by mchowning — APPROVED** [review]
Looks great! Nice work @dcalhoun ! 🎉

File: libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragmentAbstract.java (hunk 2 above)
Comment (dcalhoun) [reply libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragmentAbstract.java:223]: Interesting. Thank you for sharing this approach. In particular, thank you for sharing the example diff, as it was difficult for me to follow the written description. 

As a novice Android developer, I crafted the current implementation following the preexisting patterns in the code base for similar features. However, I see how leveraging extensions could make this less verbose. 

That said, I would prefer to forego the change at this time, as it appears it would require additional changes to the Gutenberg Mobile Java interface as well. I'd prefer to keep that stable now that it has been approved and I hope to merge later today.
