### PR TITLE
Fix #5372: Account for 'false' api_blogid in migration

### LINKED ISSUE #5372: Crash report 7.0-rc-1: NumberFormatException in WPLegacyMigrationUtils.java
```
Caused by java.lang.NumberFormatException: For input string: "false"
       at java.lang.Long.parseLong(Long.java:443)
       at java.lang.Long.valueOf(Long.java:542)
       at org.wordpress.android.util.WPLegacyMigrationUtils.getDraftsFromDeprecatedDB(WPLegacyMigrationUtils.java:255)
       at org.wordpress.android.util.WPLegacyMigrationUtils.migrateDraftsFromDeprecatedDB(WPLegacyMigrationUtils.java:80)
       at org.wordpress.android.WordPress.migrateDrafts(WordPress.java:357)
       at org.wordpress.android.WordPress.migrateSelfHostedSites(WordPress.java:351)
```

It seems the `api_blogid` field can be stored as `false`.

### PR DESCRIPTION
**Pull request by aforcier**
Fixes #5372. `api_blogid` can be `false` for self-hosted sites in some cases. This both causes a crash if there are drafts for those sites, and causes those sites not to be migrated at all.

To test:
1. Check out 0991171, run tests in `FluxCMigrationTest` 💥
2. Check out branch, run tests 👍

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/util/WPLegacyMigrationUtils.java [hunk 1]
```diff
@@ -158,9 +158,10 @@ public static boolean hasSelfHostedSiteToMigrate(Context context) {
             int numRows = c.getCount();
             c.moveToFirst();
             for (int i = 0; i < numRows; i++) {
-                // If the api_blogid field is set, that's probably a Jetpack site that is not connected to the main
-                // account, so we want to skip it.
-                if (!TextUtils.isEmpty(c.getString(5))) {
+                long apiBlogId = StringUtils.stringToLong(c.getString(5));
```
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/util/WPLegacyMigrationUtils.java]: Should we change the same test on line 134?

Comment (aforcier) [inline WordPress/src/main/java/org/wordpress/android/util/WPLegacyMigrationUtils.java]: 👍 done in fef621e.

**Comment by maxme** [comment]
:shipit:
