### PR TITLE
Issue/12915 permission label overlap

### LINKED ISSUE #12915: Overlapped labels when accessing new media picker without permissions active.
This was noted while working on the #12884 PR and is related to the new media picker

### Expected behavior
After a clean install, when opening the media picker for the first time we should get the following message that asks for permissions.

<p align="center">
  
</p>

### Actual behavior
After a clean install, when opening the media picker for the first time we get the following overlapped message that asks for permissions.

<p align="center">
  
</p>

### Steps to reproduce the behavior
- Activate the CONSOLIDATED_MEDIA_PICKER flag for wasabi
- Clean install the WasabiDebug flavor and create a new post
- Add a Image block and open the picker to add an image
- note you the the following image with overlapped labels

<p align="center">
  
</p>

### PR DESCRIPTION
**Pull request by develric**
Fixes #12915 

### To test

- Make a clean install, 
- Create a new post and add an Image Block
- Open the media picker to add an image from device
- Check you get the following image without overlapping labels
<p align="center">
  
</p>

- Press the `Allow` button and grant permission
- Note the empty view is briefly shown while background is loading images
- Note the images are loaded and empty view is hidden
- Use the search and type a string with some matched images. Note the matched images are shown
- Use the search and type a string with no matched images. Note the empty state image is shown

<p align="center">
  
</p> 

- Smoke test the picker

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/mediapicker/MediaPickerFragment.kt [hunk 1]
```diff
@@ -260,11 +260,16 @@ class MediaPickerFragment : Fragment() {
                         requestStoragePermission()
                     }
                 }
+
+                recycler.setEmptyView(null)
+                actionable_empty_view.visibility = View.GONE
```
Comment (planarvoid) [inline WordPress/src/main/java/org/wordpress/android/ui/mediapicker/MediaPickerFragment.kt]: I think the correct solution would be to move this logic to the `PhotoListViewModel`. We can introduce a new subclass of the `PhotoListUiModel` (we have `Data`, `Empty` and we can add `Hidden`). The `build` method can decide to set it to `Hidden` based on the same check used `if (softAskRequest != null && softAskRequest.show)`. This moves the decision out of the fragment. WDYT?

Comment (develric) [reply WordPress/src/main/java/org/wordpress/android/ui/mediapicker/MediaPickerFragment.kt]: I think you are right 👍 !

**Comment by develric** [comment]
Hey @planarvoid , thanks for the review. I made changes as per your feedback 👍 ! 

Re the 

```
fun `empty state is emitted when no items in picker`()
```

I needed to modify the flow behavior in the `setupViewModel` function. Not sure it is the best approach tbh so let me know wdyt 🙇

**Review by planarvoid — APPROVED** [review]
Looks good 👍 . I've tested the flow and it works well, thanks!
