### PR TITLE
Fix issue with snackbar being dismissed by invisible WPMainActivity

### LINKED ISSUE #9604: Post List - "Post published" Snackbar is dismissed immediately
### Expected behavior
When you publish a post a Snackbar with text "Post Published" + "View" action is shown for a couple of seconds.

### Actual behavior
When you publish a post a Snackbar with text "Post Published" + "View" action is shown, but disappears immediately.

post-published-snackbar-disappears-vv3

post-published-snackbar-disappears

### Steps to reproduce the behavior
1. My Site
2. Blog Posts
3. Edit a post
4. Change title
5. Publish
6. The Post List is displayed and a SnackBar "Publishing post" is shown
7. When the post is publish - "Post Published" SnackBar is shown for a fraction of a second

##### Tested on [device], Android [version]
Tested on commit 21454786c80d70c576d92557a5b66528c5297e54 - after we moved things from PostListViewModel to PostListMainViewModel
Nexus 5x, Android 8.1.0

cc @oguzkocer

### PR DESCRIPTION
**Pull request by malinajirka**
Fixes #9604

Fixes an issue with snackbar - sometimes WPMainActivity invoked Snackbar.show(..) even though the activity wasn't visible. This could have pretty nasty side-effect -> it may dismiss another Snackbar shown by other activity/fragment. More info [here](https://github.com/wordpress-mobile/WordPress-Android/issues/9604#issuecomment-482760389)

To test:
1. Go to Post List
2. Drafts
3. Publish a post
4. Wait until the upload completes
5. Make sure snackbar with "Post published" message and "View" action is shown
6. Go to Me section
7. Create and publish a post using "+New Post" button in the bottom navigation bar
8. Wait until the upload completes
9. Make sure snackbar with "Post published" message and "View" action is shown

Update release notes:

- We'll update the release notes when we merge master-post-filters branch into develop

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java [hunk 1]
```diff
@@ -1094,16 +1095,18 @@ public void initSelectedSite() {
...
-        if (site != null && event.post != null && event.post.getLocalSiteId() == site.getId()) {
-            UploadUtils.onPostUploadedSnackbarHandler(
-                    this,
-                    findViewById(R.id.coordinator),
-                    event.isError(),
-                    event.post,
-                    null,
-                    site,
-                    mDispatcher);
+        if (getLifecycle().getCurrentState().isAtLeast(STARTED)) {
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java]: We may want to add a comment for why we need to check for this, but it's fairly obvious so I am not sure. Feel free to make this addition if you'd like as a part of any other PR. Thanks!
