### PR TITLE
Follow system font size in Reader post detail

### LINKED ISSUE #4284: Reader content doesn't follow the system font size setting
### Expected behavior
Altering the system's font size setting should affect the Reader's content font size accordingly.

### Actual behavior
Reader's content font size doesn't change at all.

### Steps to reproduce the behavior

* Open any post in the Reader
* Switch to device's system settings and change the system font size
* Switch back to the app (should land on the Reader)
* Notice that the post font size hasn't changed in any way
* Notice that the tag name and comments/likes count texts _have_ changed

##### Tested on [device], Android [version]
Tested on a variety of tablet and phone devices.

### PR DESCRIPTION
**Pull request by hypest**
Fixes #4284 

To test:

* Open a post in the Reader
* Notice the font size for future comparison
* Switch to the Android System Settings and change the Font Size to something different than the current setting
* Switch back to the app
* Notice the font size change accordingly

Needs review: @nbradbury , wanna have a look? Thanks!

### CODE REVIEW

**Comment by hypest** [comment]
The issue doesn't seem to manifest on APIs above 19. I will focus this fix to the APIs that manifest the issue.

File: WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderWebView.java [hunk 1]
```diff
@@ -95,6 +95,10 @@ private void init() {
             this.setWebChromeClient(mReaderChromeClient);
             this.setWebViewClient(new ReaderWebViewClient(this));
             this.getSettings().setUserAgentString(WordPress.getUserAgent());
+            this.getSettings().setDefaultFontSize(
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderWebView.java]: Let's add a comment here explaining why this is being done. Otherwise a future dev may notice it's not doing anything on their device and think it should be deleted.

File: WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderWebView.java [hunk 2]
```diff
@@ -95,10 +95,15 @@ private void init() {
             this.setWebChromeClient(mReaderChromeClient);
             this.setWebViewClient(new ReaderWebViewClient(this));
             this.getSettings().setUserAgentString(WordPress.getUserAgent());
-            this.getSettings().setDefaultFontSize(
-                    (int) (this.getSettings().getDefaultFontSize() * getResources().getConfiguration().fontScale));
-            this.getSettings().setDefaultFixedFontSize(
-                    (int) (this.getSettings().getDefaultFixedFontSize() * getResources().getConfiguration().fontScale));
+
+            if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.KITKAT) {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderWebView.java]: Since the problem only occurs when the font scale isn't "normal," how about we further isolate this and only adjust the sizes when `fontScale != 1.0f`? Also, just in case my earlier comment was missed, this could really benefit from a comment explaining its purpose.

Comment (hypest) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderWebView.java]: Hey Nick, I've added a comment (good point!) and limited the font sizing for only when the scale is not too close to 1. (Notice that it's not a good practice to do `equals` checks with floats and that's why I did it with rounding to some significant digits).

Ready for another pass at this point. Thanks!

**Comment by nbradbury** [comment]
:shipit:
