### PR TITLE
Fixes Media Picker video selection Accessibility issue

### LINKED ISSUE #11077: Accessibility : WordPress Media Picker - Video Selection Issue
### Expected behavior
"Video Selected" should be shown when a video selection occurs.

### Actual behavior
"Image Selected" is shown. 

### Steps to reproduce the behavior
1. Create post while TalkBack is enabled.
2. Add video from WordPress Media Picker. 
3. Select the video and listen to the announcement. 

Tested on Google Pixel 4 XL, Android 10, WPAndroid `develop` ()

### PR DESCRIPTION
**Pull request by antonis**
Fixes #11077

# Description
This PR:
* [Announces the correct media type on selection](https://github.com/wordpress-mobile/WordPress-Android/pull/16426/commits/e04617da4ea802b37a8db4aa573613486a9d5131)
* [Fixes the default announcement while browsing media to avoid confusion by always announcing `image`](https://github.com/wordpress-mobile/WordPress-Android/pull/16426/commits/1bcef3a7a36851addcc711f8170794764034dbc7)

# To test:
1. Enable talkback
2. Open `Media`
3. Press the ➕ button at the top left and select `Choose from device`
4. Select a video or an image
5. **Verify** that the correct media type is announced

## Regression Notes
1. Potential unintended areas of impact
N/A

6. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

7. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridAdapter.java [hunk 1]
```diff
@@ -638,22 +638,27 @@ public void run() {
             mCallback.onAdapterSelectionCountChanged(mSelectedItems.size());
         }
 
-        PhotoPickerUtils.announceSelectedImageForAccessibility(holder.mImageView, selected);
+        PhotoPickerUtils.announceSelectedImageForAccessibility(holder.mImageView, isVideo, selected);
```
Comment (mkevins) [inline WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridAdapter.java]: Though not introduced in this PR, I wonder if we can rename this method to `announceSelectedItemForAccessibility`, or `announceSelectedMediaForAccessibility`, or something like that, since it could be video and not only images. Wdyt?

Comment (antonis) [reply WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridAdapter.java]: Great point @mkevins 👍 
Renamed with cfe595ddafbf0966b9b9164848c4cfeeff8812e7

Comment (mkevins) [reply WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridAdapter.java]: That was fast!

**Review by mkevins — APPROVED** [review]
These code changes look good, and this fixes the issue. Thanks Antonis!

I tested this on a Pixel 3a (physical device) and I also noted that this issue fixes a separate 
 as well issue:

That the "selected" / "unselected" announcements were backwards. Nice work Antonis!
