### PR TITLE
Accessibility : Bar Chart Improvements

### LINKED ISSUE #10987: Accessibility : Stats Graph Improvement
This graph was made accessible in a previous version of its implementation. More details #10285

## Expected behavior
Each bar in the graph should be accessible and when focused should be able to tell the user something. 

## Actual behavior
The whole view the graph resides in is announced. 

### Steps to reproduce the behavior
1. Go Stats within the app. 
2. Select either Day or Weeks and you will see the graph. 
3. Attempt to interact with the columns and you will see that's not possible. 

Tested on Google Pixel 4 XL, Android 10, WPAndroid `develop` ()

### PR DESCRIPTION
**Pull request by jd-alexander**
Fixes #10987

## Findings
The bar chart component wasn't accessible so this improvement seeks to make it easier for visually impaired users to navigate its contents. 

## Solution

`ExploreByTouchHelper` was utilized to make the bars within the chart selectable which would then trigger the announcement of a bar's content description. 

Before | After 
--------|-------
[Before Video ](https://drive.google.com/file/d/19dDnYoiueb1S5NTwNTH8POlAQvb65-vH/view?usp=sharing) |   [After Video    ](https://drive.google.com/file/d/19m6iZKmCrKoBehhI0k3YAVGDHlpxbloB/view?usp=sharing)

## Testing
1. Turn on TalkBack
2. Open Stats → Days
3. Slide finger over each bar to hear the content description. 
4. Open other tabs and the bar chart will update. 
5. Tap to make a bar highlighted and the stats will be updated as well. 

Days - Visitors | Days - Visitors (Bar Selected) 
--------|-------
        |   

Days - Views | Days - Views (Bar Selected) 
--------|-------
        | 

Days - Likes | Week - Views 
--------|-------
        |       

## Reviewing 
Only 1 reviewer is needed but anyone can review. 

## Submitter Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
- [x] If it's feasible, I have added unit tests.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/BarChartAccessibilityHelper.kt [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+    private val barChart: BarChart,
+    private val contentDescriptions: List<String>,
+    private val hasOverlappingEntries: Boolean
+) : ExploreByTouchHelper(barChart) {
+    interface BarChartAccessibilityEvent {
+        fun onHighlight(index: Int, hasOverlappingEntries: Boolean)
+    }
+
+    private val dataSet = barChart.data.dataSets.first()
+    var accessibilityEvent: BarChartAccessibilityEvent? = null
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/BarChartAccessibilityHelper.kt]: Does this field need to be `var` and nullable? Could we move it into the constructor and change it to `val`?

File: WordPress/src/main/res/values/strings.xml [hunk 2]
```diff
@@ -886,6 +885,8 @@
     <string name="stats_item_collapsed">Item collapsed</string>
     <string name="stats_posting_activity_graph">Graph of posting activity.</string>
     <string name="stats_list_item_description">%1$s: %2$s, %3$s: %4$s</string>
+    <string name="stats_bar_chart_accessibility_entry">%1$s, %2$d %3$s</string>
+    <string name="stats_bar_chart_accessibility_overlapping_entry">&#160; &amp; %1$d %2$s</string>
```
Comment (malinajirka) [inline WordPress/src/main/res/values/strings.xml]: I'm not familiar with the code, could you please help me understand what is an "overlapping entry"? Can I somehow test this behavior?

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsUtils.kt [hunk 3]
```diff
@@ -132,6 +134,36 @@ class StatsUtils
             number
         }
     }
+
+    fun getEntryContentDescriptions(
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsUtils.kt]: It seems this method is made for chart entries - we might want to consider renaming it so the intention/usage is more clear. Wdyt?

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BarChartViewHolder.kt [hunk 4]
```diff
@@ -42,6 +46,24 @@ class BarChartViewHolder(parent: ViewGroup) : BlockListItemViewHolder(
...
+                        chart,
+                        contentDescriptions = item.entryContentDescriptions,
+                        hasOverlappingEntries = item.overlappingEntries != null
+                )
+
+                accessibilityHelper.accessibilityEvent = object : BarChartAccessibilityEvent {
+                    override fun onHighlight(index: Int, hasOverlappingEntries: Boolean) {
+                        chart.highlightColumn(index, hasOverlappingEntries)
+                        val entry = chart.data.dataSets.first().getEntryForIndex(index)
+                        val value = entry?.data as? String
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BarChartViewHolder.kt]: Btw can't the caller pass us the value so we don't need to look it up and access the `chart.data.dataSet` from here?

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewMapper.kt [hunk 5]
```diff
@@ -196,13 +196,35 @@ class OverviewMapper
         if (shouldShowVisitors) {
             result.add(ChartLegend(R.string.stats_visitors))
         }
+
+        val entryType = when (selectedType) {
+            1 -> R.string.stats_visitors
```
[the remark this answers is not in the document]
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewMapper.kt]: Thanks! That sounds like a good idea! I did this here because the same approach was being used above to determine the `selectedType` so I thought doing this would make it easier to spot the relation.

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BarChartViewHolder.kt [hunk 6]
```diff
@@ -42,6 +46,24 @@ class BarChartViewHolder(parent: ViewGroup) : BlockListItemViewHolder(
         GlobalScope.launch(Dispatchers.Main) {
             delay(50)
             chart.draw(item, labelStart, labelEnd)
+            chart.post {
```
[the remark this answers is not in the document]
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BarChartViewHolder.kt]: I invoked post here because it would initiate the helper when the chart is drawn and that would allow all the virtual views that are needed by the accessibility framework to be created. I am going to check to see if I can use another way to accomplish this that doesn't involve mixing threads which could cause issues or side effects.

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BarChartViewHolder.kt [hunk 7]
```diff
@@ -42,6 +46,24 @@ class BarChartViewHolder(parent: ViewGroup) : BlockListItemViewHolder(
...
+                accessibilityHelper = BarChartAccessibilityHelper(
+                        chart,
+                        contentDescriptions = item.entryContentDescriptions,
+                        hasOverlappingEntries = item.overlappingEntries != null
+                )
+
+                accessibilityHelper.accessibilityEvent = object : BarChartAccessibilityEvent {
+                    override fun onHighlight(index: Int, hasOverlappingEntries: Boolean) {
+                        chart.highlightColumn(index, hasOverlappingEntries)
+                        val entry = chart.data.dataSets.first().getEntryForIndex(index)
```
[the remark this answers is not in the document]
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BarChartViewHolder.kt]: Yes, I should add a comment indeed. I called first here because the chart will always have at least one dataset that does the default rendering i.e the values that the chart is trying to represent. Based on my exploration, it seems three datasets can get applied: main bars being represented, overlapping bars, and highlights and since the main set of values are always added first it will always be the first dataset present. 

Eg. 
main values = Views
overlapping values = Visitors
highlights = selected bar(s) 

I didn't see a unique identifier I could identify each dataset which would make the solution more direct so I opted for this approach.

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BarChartViewHolder.kt [hunk 8]
```diff
@@ -42,6 +46,24 @@ class BarChartViewHolder(parent: ViewGroup) : BlockListItemViewHolder(
...
+                        val value = entry?.data as? String
+                        item.onBarSelected?.invoke(value)
```
[the remark this answers is not in the document]
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BarChartViewHolder.kt]: No we don't. Thanks 👏

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/BarChartAccessibilityHelper.kt (hunk 1 above)
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/BarChartAccessibilityHelper.kt]: Yes, this a good observation. Will do the refactor!

File: WordPress/src/main/res/values/strings.xml (hunk 2 above)
Comment (jd-alexander) [reply WordPress/src/main/res/values/strings.xml]: An overlapping entry is when two sets of stats are being represented on a single chart. So when you are able to see both "Views and Visitors" at the same time one of those values is overlapping the other. In this case, it would be the visitors that are overlapping entries. Let me know if this explanation helps!

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsUtils.kt (hunk 3 above)
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsUtils.kt]: Good observation! I will rename it!

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BarChartViewHolder.kt (hunk 4 above)
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BarChartViewHolder.kt]: Yes, I will move this to the constructor.

**Comment by jkmassel** [comment]
I'm moving this PR to 14.1 since we're code freezing today.

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewMapper.kt (hunk 5 above)
[the remark this answers is not in the document]
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewMapper.kt]: Yeah, I saw it and I understand your decision. However, I thought introducing an enum might still be worth it and would make the code clearer.

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BarChartViewHolder.kt (hunk 6 above)
[the remark this answers is not in the document]
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BarChartViewHolder.kt]: Thanks ;) - I'd just try the approach I suggested or anything else that comes from the top of your head -> if it doesn't work, don't worry about it.

[the remark this answers is not in the document]
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BarChartViewHolder.kt]: I tried the coroutines approach but it didn't work out well. My coroutine knowledge isn't as advanced so that could probably be the reason so, for now, I think it's okay to leave it once there are no obvious side effects in testing.

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BarChartViewHolder.kt (hunk 8 above)
[the remark this answers is not in the document]
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BarChartViewHolder.kt]: Resolved in 2b51423

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/BarChartAccessibilityHelper.kt (hunk 1 above)
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/BarChartAccessibilityHelper.kt]: resolved in 4c473f4

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsUtils.kt (hunk 3 above)
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsUtils.kt]: resolved in 9b5f428

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BarChartViewHolder.kt (hunk 4 above)
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BarChartViewHolder.kt]: Resolved in 8bab45d dfbab1b

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BarChartViewHolder.kt (hunk 6 above)
[the remark this answers is not in the document]
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BarChartViewHolder.kt]: 👍 Thanks for giving it a try! ;)

**Comment by malinajirka** [comment]
Thanks @jd-alexander! 
I've reviewed the changes and they look great overall. I've left one comment.

I've also looked into [the issue](https://github.com/wordpress-mobile/WordPress-Android/pull/11059#pullrequestreview-341778905) I'm experiencing on my hw device. It took me a while, but I believe I found the culprit. We sometimes "cut" some entries/columns depending on the width of the screen - [here](https://github.com/wordpress-mobile/WordPress-Android/blob/dfbab1bb6b9a75014f1071e320d42ea20a67b5c0/WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BarChartViewHolder.kt#L302). However, we don't adjust the list of contentDescriptions (`item.entryContentDescriptions`) accordingly. Therefore the indices between graph-columns and contentDescriptions are off by n (in my case off by 1).

I was able to reproduce the bug on an emulator - Pixel 3, API 28. I assume you'll be able to reproduce it as well. If you won't be able to reproduce it, we can look into it together.

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BarChartViewHolder.kt (hunk 4 above)
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BarChartViewHolder.kt]: Resolved df98ba8

**Comment by malinajirka** [comment]
I'm still experiencing the same offset issue as before even after the fix. Does the fix work for you?

I think the culprit is `take(..)`. `take` takes first n elements and [`cutEntries`](https://github.com/wordpress-mobile/WordPress-Android/blob/df98ba859acb4a36476f0f69a73158391c2b230f/WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BarChartViewHolder.kt#L305) takes last n elements.

It also feels a bit weird we cut the contentDescription in the helper even though the logic isn't related to it at all. We might want to consider passing only the relevant contentDescription to the helper (or write a comment with explanation at least). Wdyt?

**Comment by jd-alexander** [comment]
> I'm still experiencing the same offset issue as before even after the fix. Does the fix work for you?

> I think the culprit is take(..) - it takes first n elements and cutEntries takes last n elements.

> It also feels a bit weird we cut the contentDescription in the helper even though the logic isn't related to it at all. We might want to consider passing only the relevant contentDescription to the helper (or write a comment with an explanation at least). Wdyt?

Thanks for a productive pair programming session @malinajirka! The fixes we came up with for these issues were really good! I just reviewed the code again and I think all is well now so this can be merged!
