### PR TITLE
Fix UserAgent ANR (again)

### LINKED ISSUE #20147: JniAndroid$UncaughtExceptionException: Native stack trace:
Sentry Issue: [JETPACK-ANDROID-J3B](https://a8c.sentry.io/issues/4955991275/?referrer=github_integration)

```
Surface$OutOfResourcesException: None
    at android.view.SurfaceControl.nativeCreate(SurfaceControl.java)
    at android.view.SurfaceControl.<init>(SurfaceControl.java:1038)
    at android.view.SurfaceControl.<init>(SurfaceControl.java:86)
    at android.view.SurfaceControl$Builder.build(SurfaceControl.java:693)
    at android.view.View.startDragAndDrop(View.java:27229)
...
(8 additional frame(s) were not displayed)

JniAndroid$UncaughtExceptionException: Native stack trace:
#00 pc 0x0000000003cb82b7 /data/app/~~edjQkLFlZwvqNMeJWfgDKw==/com.google.android.trichromelibrary_616714333-9frhU_h0WwVrsnVaP0qSbg==/base.apk (offset 0x8dc000)
#01 pc 0x0000000002bb566f /data/app/~~edjQkLFlZwvqNMeJWfgDKw==/com.google.android.trichromelibrary_616714333-9frhU_h0WwVrsnVaP0qSbg==/base.apk (offset 0x8dc000)
#02 pc 0x0000000002bb4d57 /data/app/~~edjQkLFlZwvqNMeJWfgDKw==/com.google.android.trichromelibrary_616714333-9frhU_h0WwVrsnVaP0qSbg==/base.apk (offset 0x8dc000)
#03 pc 0x0000000007073447 /data/app/~~edjQkLFlZwvqNMeJWfgDKw==/com.google.android.trichromelibrary_616714333-9frhU_h0WwVrsnVaP0qSbg==/base.apk (offset 0x8dc000)
#04 pc 0x00000000054fdd1f /data/app/~~edjQkLFlZwvqNMeJWfgDKw==/com.google.android.trichromelibrary_616714333-9frhU_h0WwVrsnVaP0qSbg==/base.apk (offset 0x8dc000)
#05 pc 0x00000000053b8b63 /data/app/~~edjQkLFlZwvqNMeJWfgDKw==/com.google.android.trichromelibrary_616714333-9frhU_h0WwVrsnVaP0qSbg==/base.apk (offset 0x8dc000)
#06 pc 0x00000000053956f3 /data/app/~~edjQkLFlZwvqNMeJWfgDKw==/com.google.android.trichromelibrary_616714333-9frhU_h0WwVrsnVaP0qSbg==/base.apk (offset 0x8dc000)
#07 pc 0x0000000003984603 /data/app/~~edjQkLFlZwvqNMeJWfgDKw==/com.google.android.trichromelibrary_616714333-9frhU_h0WwVrsnVaP0qSbg==/base.apk (offset 0x8dc000)
#08 pc 0x0000000002bd169f /data/app/~~edjQkLFlZwvqNMeJWfgDKw==/com.google.android.trichromelibrary_616714333-9frhU_h0WwVrsnVaP0qSbg==/base.apk (offset 0x8dc000)
#09 pc 0x0000000002bd0f6b /data/app/~~edjQkLFlZwvqNMeJWfgDKw==/com.google.android.trichromelibrary_616714333-9frhU_h0WwVrsnVaP0qSbg==/base.apk (offset 0x8dc000)
#10 pc 0x0000000002bd121f /data/app/~~edjQkLFlZwvqNMeJWfgDKw==/com.google.android.trichromelibrary_616714333-9frhU_h0WwVrsnVaP0qSbg==/base.apk (offset 0x8dc000)
#11 pc 0x0000000002a7b41f /data/app/~~edjQkLFlZwvqNMeJWfgDKw==/com.google.android.trichromelibrary_616714333-9frhU_h0WwVrsnVaP0qSbg==/base.apk (offset 0x8dc000)
#12 pc 0x0000000002a7b2d7 /data/app/~~edjQkLFlZwvqNMeJWfgDKw==/com.google.android.trichromelibrary_616714333-9frhU_h0WwVrsnVaP0qSbg==/base.apk (offset 0x8dc000)
#13 pc 0x0000000002b6bc4f /data/app/~~edjQkLFlZwvqNMeJWfgDKw==/com.google.android.trichromelibrary_616714333-9frhU_h0WwVrsnVaP0qSbg==/base.apk (offset 0x8dc000)
#14 pc 0x0000000002b6696f /data/app/~~edjQkLFlZwvqNMeJWfgDKw==/com.google.android.trichromelibrary_616714333-9frhU_h0WwVrsnVaP0qSbg==/base.apk (offset 0x8dc000)
#15 pc 0x0000000003aa3bc3 /data/app/~~edjQkLFlZwvqNMeJWfgDKw==/com.google.android.trichromelibrary_616714333-9frhU_h0WwVrsnVaP0qSbg==/base.apk (offset 0x8dc000)
#16 pc 0x0000000003aa3b47 /data/app/~~edjQkLFlZwvqNMeJWfgDKw==/com.google.android.trichromelibrary_616714333-9frhU_h0WwVrsnVaP0qSbg==/base.apk (offset 0x8dc000)
#17 pc 0x000000000000b067 /system/lib64/libutils.so
#18 pc 0x000000000000ac6b /system/lib64/libutils.so
#19 pc 0x000000000007cb3f /system/lib64/libandroid_runtime.so

    at org.chromium.base.JniAndroid.handleException(chromium-TrichromeWebViewGoogle6432.aab-stable-616714333:11)
    at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
    at android.os.MessageQueue.next(MessageQueue.java:335)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:8131)
...
(3 additional frame(s) were not displayed)
```

### LINKED ISSUE #21679: ApplicationNotResponding: Background ANR
Sentry Issue: [JETPACK-ANDROID-1307](https://a8c.sentry.io/issues/6134221409/?referrer=github_integration)

```
ApplicationNotResponding: Background ANR
    at org.wordpress.android.fluxc.network.UserAgent.<init>(UserAgent.kt:17)
    at org.wordpress.android.modules.AppConfigModule.provideUserAgent(AppConfigModule.java:36)
    at org.wordpress.android.modules.AppConfigModule_ProvideUserAgentFactory.provideUserAgent(AppConfigModule_ProvideUserAgentFactory.java:51)
    at org.wordpress.android.DaggerWordPressRelease_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get0(DaggerWordPressRelease_HiltComponents_SingletonC.java:11957)
    at org.wordpress.android.DaggerWordPressRelease_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(DaggerWordPressRelease_HiltComponents_SingletonC.java:13317)
...
(50 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes https://github.com/wordpress-mobile/WordPress-Android/issues/21679
Fixes https://github.com/wordpress-mobile/WordPress-Android/issues/20147

This is another attempt to fix a long-standing ANR exception caused by reading `WebSettings.getDefaultUserAgent` on the main thread. [The previous attempt](https://github.com/wordpress-mobile/WordPress-Android/pull/21681) contains details on why we couldn't call `WebSettings.getDefaultUserAgent` on a separate thread.

Over in WCAndroid, @hichamboushaba came up with [this solution](https://github.com/woocommerce/woocommerce-android/pull/14431) which I'm borrowing from here.

The gist is rather than use `WebSettings.getDefaultUserAgent` for constructing the user agent for API calls, instead use the system property `http.agent`. [The WCAndroid PR](https://github.com/woocommerce/woocommerce-android/pull/14431) contains more information about the approach and other options explored. I recommend reading that PR thread before reviewing this.

Note that as with WCAndroid, this PR removes `UserAgent.toString()` because I found no usages of it. I asked Claude to find usages and it responded with this:

```
 Based on my thorough search, I haven't found any places where UserAgent.toString() is called
 either explicitly or implicitly. The codebase consistently uses:
  - userAgent.webViewUserAgent for web views and headers
  - userAgent.apiUserAgent for REST API clients
  - String parameters when passing user agent values to authentication methods

  The UserAgent object is never:
  - Concatenated with strings
  - Passed to methods expecting String parameters
  - Used in logging statements directly (always uses the getter methods)
  - Used in string templates or interpolation

  No calls to UserAgent.toString() found, either explicit or implicit.
```

@wzieba @ParaskP7  I've added you as reviewers since you had some prior interaction with this issue, either on WPAndroid or WCAndroid.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/media/MediaRestClient.java [hunk 1]
```diff
@@ -199,7 +199,7 @@ public void uploadMedia(@NonNull final SiteModel site, @Nullable final MediaMode
 
         Request request = new Request.Builder()
                 .addHeader(WPComGsonRequest.REST_AUTHORIZATION_HEADER, authHeader)
-                .addHeader("User-Agent", mUserAgent.toString())
+                .addHeader("User-Agent", mUserAgent.getWebViewUserAgent())
```
Comment (hichamboushaba) [inline libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/media/MediaRestClient.java]: @nbradbury not a full review, but just spotted few areas like this where we use the `webViewUserAgent` instead of `apiUserAgent`, all RestClients should use `apiUserAgent`.

File: libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/jetpackai/JetpackAITranscriptionRestClient.kt [hunk 2]
```diff
@@ -63,7 +63,7 @@ class JetpackAITranscriptionRestClient  @Inject constructor(
                 url(it)
             } ?: url(url)
             addHeader("Authorization", "Bearer ${jwtToken.value}")
-            addHeader("User-Agent",  userAgent.toString())
+            addHeader("User-Agent",  userAgent.webViewUserAgent)
```
Comment (dcalhoun) [inline libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/jetpackai/JetpackAITranscriptionRestClient.kt]:
```suggestion
            addHeader("User-Agent",  userAgent.apiUserAgent)
```

File: libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/media/MediaRestClient.java (hunk 1 above)
Comment (dcalhoun) [reply libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/media/MediaRestClient.java]:
```suggestion
                .addHeader("User-Agent", mUserAgent.getApiUserAgent())
```

File: libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/media/MediaXMLRPCClient.java [hunk 3]
```diff
@@ -192,7 +192,7 @@ public void uploadMedia(@NonNull final SiteModel site, @Nullable final MediaMode
         Builder builder = new Request.Builder()
                 .url(url)
                 .post(requestBody)
-                .addHeader("User-Agent", mUserAgent.toString())
+                .addHeader("User-Agent", mUserAgent.getWebViewUserAgent())
```
Comment (dcalhoun) [inline libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/media/MediaXMLRPCClient.java]:
```suggestion
                .addHeader("User-Agent", mUserAgent.getApiUserAgent())
```

File: WordPress/src/main/java/org/wordpress/android/ui/media/MediaSettingsActivity.java [hunk 4]
```diff
@@ -1041,7 +1041,7 @@ private void saveMediaToDevice() {
         }
         request.allowScanningByMediaScanner();
         request.setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE);
-        request.addRequestHeader("User-Agent", mUserAgent.toString());
+        request.addRequestHeader("User-Agent", mUserAgent.getWebViewUserAgent());
```
Comment (dcalhoun) [inline WordPress/src/main/java/org/wordpress/android/ui/media/MediaSettingsActivity.java]:
```suggestion
        request.addRequestHeader("User-Agent", mUserAgent.getApiUserAgent());
```

File: WordPress/src/main/java/org/wordpress/android/ui/utils/AuthenticationUtils.kt [hunk 5]
```diff
@@ -20,7 +20,7 @@ class AuthenticationUtils
     @Suppress("ImplicitDefaultLocale")
     fun getAuthHeaders(url: String): Map<String, String> {
         val headers = mutableMapOf<String, String>()
-        headers["User-Agent"] = userAgent.userAgent
+        headers["User-Agent"] = userAgent.webViewUserAgent
```
Comment (dcalhoun) [inline WordPress/src/main/java/org/wordpress/android/ui/utils/AuthenticationUtils.kt]: This appears to be used in several places. Most of them, if not all of them, appear unrelated to WebViews, strictly speaking. Should this use the API user agent instead or are the requests generic enough that they warrant the WebView user agent?

**Review by dcalhoun — COMMENTED** [review]
As noted in https://github.com/wordpress-mobile/WordPress-Android/pull/22174#discussion_r2307871222, it appears there are several WebView user agents that should instead be the API user agent. I left inline comments on those I spotted. 

From observing a handful of requests, it appears as though the changes are functioning as expected otherwise.

**Comment by nbradbury** [comment]
@hichamboushaba @dcalhoun Thanks for taking a look, you're right, there are a few places where I should've been using `apiUserAgent`. I think I was overly cautious in switching to that user agent since we know the `webUserAgent` worked, but I needn't have been since everything seems to work fine with the api agent. 

I've made the suggested changes, so @dcalhoun it's ready for another round.

**Review by dcalhoun — APPROVED** [review]
I navigated around various portions of the app to see if any requests failed. I did not encounter any issues. The user agents appear to be set as expected.

**Comment by dcalhoun** [comment]
> This pull request was deployed and Sentry observed the following issues:
> 
> * ‼️ [**ApplicationNotResponding: ANR for at least 5000 ms...**](https://a8c.sentry.io/issues/6861469934/?referrer=github-pr-bot) in `release`

The mentioned ANR occurred in 25.6, which does not include these changes. 26.2 is the first release with these changes.
