### PR TITLE
Fixes Twitter publicize connections

### LINKED ISSUE #8652: Publicize: Error Connecting To Social Media Profiles
### Expected behavior

I expected to be able to connect my WordPress.com site to my Twitter account or other social media accounts so that future blog posts are automatically shared.

### Actual behavior

After going through the steps to connect to my Twitter account, when I have connected more than one Twitter account in the past, a toast message comes up with an error and the site isn't connected.

Similar errors occur for other social media accounts I try to connect (LinkedIn, Facebook).

### Steps to reproduce the behavior

1. Navigate to My Site > Sharing.
2. Tap on "Twitter" and choose the option to "Connect".
3. Enter your username and password for Twitter.
4. Select your Twitter account in the Connecting Twitter modal.

If you don't see the Connecting Twitter modal, and your Twitter account is connected successfully, delete the connection and repeat the steps above using a second Twitter account. The second time, you will see the Connecting Twitter modal with both Twitter accounts.

Result: A toast message comes up with the error "An error occurred."

##### Reported in 1581544-z, WordPress for Android 11.1.1

### PR DESCRIPTION
**Pull request by oguzkocer**
Fixes #8652.

When we tried to add a new publicize connection with the `/sites/$site/publicize-connections/new` endpoint, it complained with the following error:

> This Publicize service does not support setting an external user ID.

This is easily reproducible by:

1. Create a few twitter connections from any client
2. Make a request to `v1.1/me/keyring-connections/`
3. Pick a Twitter connection from the results
4. Use the `ID` of it as `keyring_connection_ID` and  `external_ID` of it as `external_user_ID` and make a request to `/sites/$site/publicize-connections/new` for any of your sites. You can also use the `/me/publicize-connections/new` to create a connection for all of your sites
5. Notice the error `This Publicize service does not support setting an external user ID.`

I checked Calypso and they are not sending the `external_user_ID` at all for Twitter connections. (They also send the parameters as a json object but that doesn't seem to make a difference) I initially tried to remove the `external_user_ID` for all connection requests, but Facebook does expect it and since #8652 says the issue only affects Twitter, the most straightforward solution is to not send the `external_user_ID` parameter for it.

---

**To test:**
* Connect multiple Twitter accounts from `My Site` -> `Sharing` -> `Twitter`
* Try connecting to other services
* Try disconnecting/reconnecting the twitter accounts

In my test I was able to connect 2 different Twitter accounts without any issues and a Facebook account once I add a page to my test Facebook account. I don't have a handy test account for LinkedIn or Tumblr, but this PR shouldn't change anything about them. If anyone has it handy, it'd be good to test them just in case.

Finally, I found an issue with the Facebook connections which I'll create a new issue for.

---

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeActions.java [hunk 1]
```diff
@@ -161,7 +161,8 @@ public void onErrorResponse(VolleyError volleyError) {
 
         Map<String, String> params = new HashMap<>();
         params.put("keyring_connection_ID", Long.toString(keyringConnectionId));
-        if (!externalUserId.isEmpty()) {
+        // Sending the external id for Twitter connections result in an error
+        if (!externalUserId.isEmpty() && !serviceId.equals(PublicizeConstants.TWITTER_ID)) {
```
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeActions.java]: wdyt about using `TextUils.isEmpty(externalUserId)` and `PublicizeConstants.TWITTER_ID.equals(serviceId)` to avoid potential NPEs?

Comment (oguzkocer) [reply WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeActions.java]: Ha, I have been in Kotlin world for too long, good catch! I'll make the change later today.

Comment (oguzkocer) [reply WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeActions.java]: Addressed in dc812045357ea150161e555b59ff4a30bb0813f8.

**Comment by oguzkocer** [comment]
@mzorz I've addressed the possible NPE issue and merged `develop` into this branch to resolve the conflict for the release notes. This should be ready for a second round, thanks!

**Comment by mzorz** [comment]
Thanks for this @oguzkocer ! Will merge once CircleCI goes 💚
