### PR TITLE
Hide Giphy Picker

### LINKED ISSUE #10801: Post Settings: featured image option "Choose from Giphy" is not working
Steps to reproduce:

1. Open any post.
1. Go to More > Post Settings.
1. Tap the image icon (bottom left).
1. Tap the "Choose from Giphy" option. 

**Result:** nothing happens when you tap the "Choose from Giphy" option.

Screenshot_20191114-104813
<sup>Tested with WPAndroid 13.6-rc-3 on Pixel 3 Android 10.</sup>

**Note:** this was found while testing 13.6 beta but I also tested with 13.5 and verified it happens there as well.

### PR DESCRIPTION
**Pull request by shiki**
Fixes #10801 

Before | After 
--------|-------
image        |       image

This removes the Giphy option from Actec, Media Library, and Featured Image. The connections to the `GiphyPickerActivity` have been removed. The Giphy SDK dependency was also removed. 

The `GiphyPickerActivity` and its related classes were kept based on @frosty's advice. 

References:

- https://github.com/wordpress-mobile/WordPress-iOS/pull/12769
- p77Llu-cVm-p2

## Testing

Please test that:

1. You can't use Giphy in Aztec
2. You can't use Giphy in Media Library.
2. You can't use Giphy in Post Settings → Featured Image.

## Reviewing 

Only 1 reviewer is needed but anyone can review. 

## Submitter Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
- [x] If it's feasible, I have added unit tests.

### CODE REVIEW

**Comment by jkmassel** [comment]
Howdy folks! I'm freezing `13.7` today, so this is being bumped to `13.8`. If you'd like it to go out as part of `13.7`, please target `release/13.7` for this PR, and DM me once it's merged – I'll be happy to cut a new beta release!

File: WordPress/src/main/java/org/wordpress/android/viewmodel/giphy/GiphyPickerDataSource.kt [hunk 1]
```diff
@@ -14,7 +11,6 @@ import com.giphy.sdk.core.network.api.GPHApiClient
  * [searchQuery] is changed by the user.
  */
 class GiphyPickerDataSource(
```
Comment (planarvoid) [inline WordPress/src/main/java/org/wordpress/android/viewmodel/giphy/GiphyPickerDataSource.kt]: I'm wondering if this should be renamed to something like `GifPickerDataSource` so once we implement a solution with Tenor, it would be obvious to put it here. I guess it's not that important though.

Comment (shiki) [reply WordPress/src/main/java/org/wordpress/android/viewmodel/giphy/GiphyPickerDataSource.kt]: That's a good idea. We could probably do it when we switch to a different provider. Git has some quirkiness when files and folders are renamed. It always seemed harder for me to track the history of those. In this case, we probably want to make it easier to see the history of the files and be able to integrate the new provider a bit faster.

**Comment by shiki** [comment]
Thank you, @planarvoid!
