### PR TITLE
Fix #5265: FluxC media browser retries

### LINKED ISSUE #5265: FluxC - Media - Failed uploads in media browser stay UPLOADING
When a media upload fails in the media browser, the media item continues to display a spinner and `UPLOADING` message, and can't be deleted or retried.

### PR DESCRIPTION
**Pull request by aforcier**
Partially fixes #5265.

1. Persists the `FAILED` media upload state in the FluxC DB (otherwise it's not correctly identified and stays `UPLOADING` in the UI forever)
2. Displays a 'Retry' message for failed media
3. Uses the local `REMOVE_MEDIA` action when attempting to delete failed uploads (this used to attempt a network delete and resulted in an error message)
4. Fixes a crash when deleting failed media

To get 1-3 working, I had to reinstate the hacky behaviour (that already exists in `develop`) of [setting a placeholder remote media ID](https://github.com/wordpress-mobile/WordPress-Android/commit/0f800d30265d77a955661a955a891e0de2e050bb) when uploading local media. Part of the issue was that the remote media ID is used throughout the media picker (which is `0` for local media).

A full refactor using local media IDs (or even better the `MediaModel`s themselves) to identify media is the ideal fix. I'm opening a separate PR for that against this one, since it's a fairly invasive change and we might decide to roll out this dirtier but 'safer' fix in the meantime.

Note about 1: We should make all upload state changes in FluxC instead of managing them in WPAndroid - that will be another refactor.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridAdapter.java [hunk 1]
```diff
@@ -240,16 +240,15 @@ public void bindView(final View view, Context context, Cursor cursor) {
 
                 // add onclick to retry failed uploads
                 if (state.equalsIgnoreCase(MediaUploadState.FAILED.name())) {
-                    state = MediaUploadState.QUEUED.name();
                     holder.stateTextView.setVisibility(View.VISIBLE);
-                    holder.stateTextView.setText(state);
+                    holder.stateTextView.setText(context.getString(R.string.retry));
```
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridAdapter.java]: 👍

Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridAdapter.java]: We should do the same thing above `holder.stateTextView.setText(state);` - I'll fill a new issue

Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridAdapter.java]: https://github.com/wordpress-mobile/WordPress-Android/issues/5271

**Comment by maxme** [comment]
:shipit:
