### PR TITLE
Fix #6316: missing isAdded could lead to a crash

### LINKED ISSUE #6316: Crash report 7.7: ISE in MeFragment.onActivityResult
```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {org.wordpress.android/org.wordpress.android.ui.main.WPMainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1200, result=-1, data=Intent { (has extras) }} to activity {org.wordpress.android/org.wordpress.android.ui.main.WPMainActivity}: java.lang.IllegalStateException: Fragment MeFragment{293d05f} not attached to Activity
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3314)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3345)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2659)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5729)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
Caused by java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1200, result=-1, data=Intent { (has extras) }} to activity {org.wordpress.android/org.wordpress.android.ui.main.WPMainActivity}: java.lang.IllegalStateException: Fragment MeFragment{293d05f} not attached to Activity
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3930)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3296)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3345)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2659)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5729)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
Caused by java.lang.IllegalStateException: Fragment MeFragment{293d05f} not attached to Activity
       at android.app.Fragment.getResources(Fragment.java:816)
       at android.app.Fragment.getString(Fragment.java:838)
       at org.wordpress.android.ui.main.MeFragment.onActivityResult(MeFragment.java:451)
       at org.wordpress.android.ui.main.WPMainActivity.onActivityResult(WPMainActivity.java:588)
       at android.app.Activity.dispatchActivityResult(Activity.java:6461)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3926)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3296)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3345)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2659)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5729)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

### PR DESCRIPTION
**Pull request by maxme**
Fix #6316: missing isAdded could lead to a crash

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.java [hunk 1]
```diff
@@ -462,10 +470,8 @@ public void onActivityResult(int requestCode, int resultCode, Intent data) {
                 if (resultCode == Activity.RESULT_OK) {
                     fetchMedia(UCrop.getOutput(data));
                 } else if (resultCode == UCrop.RESULT_ERROR) {
-                    Toast.makeText(getActivity(), getString(R.string.error_cropping_image), Toast.LENGTH_SHORT).show();
-
-                    final Throwable cropError = UCrop.getError(data);
-                    AppLog.e(AppLog.T.MAIN, "Image cropping failed!", cropError);
+                    AppLog.e(AppLog.T.MAIN, "Image cropping failed!", UCrop.getError(data));
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.java]: AS is complaining that `UCrop.getError(data)` can be `null`, but I don't see a good way around that.
