### PR TITLE
fix #2479: fix a NPE in PostUploadService.onCancelled

### LINKED ISSUE #2479: Crash report 3.8.1: NPE in PostUploadService$UploadPostTask.onCancelled
```
java.lang.NullPointerException
       at org.wordpress.android.ui.posts.PostUploadService$UploadPostTask.onCancelled(PostUploadService.java:187)
       at org.wordpress.android.ui.posts.PostUploadService$UploadPostTask.onCancelled(PostUploadService.java:151)
       at android.os.AsyncTask.finish(AsyncTask.java:600)
       at android.os.AsyncTask.access$600(AsyncTask.java:156)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4424)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:558)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

### PR DESCRIPTION
**Pull request by maxme**
fix #2479: fix a NPE in PostUploadService.onCancelled

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostUploadService.java [hunk 1]
```diff
@@ -183,9 +183,14 @@ protected void onPostExecute(Boolean postUploadedSuccessfully) {
         @Override
         protected void onCancelled(Boolean aBoolean) {
             super.onCancelled(aBoolean);
-            mPostUploadNotifier.updateNotificationWithError(mErrorMessage, mIsMediaError, mPost.isPage(),
-                    mErrorUnavailableVideoPress);
-            WordPress.postUploadFailed(mPost.getLocalTableBlogId());
+            // mPostUploadNotifier and mPost can be null if onCancelled is called before doInBackground
+            if (mPostUploadNotifier != null) {
+                mPostUploadNotifier.updateNotificationWithError(mErrorMessage, mIsMediaError, mPost.isPage(),
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/PostUploadService.java]: Is it possible for `mPostUploadNotifier` to be non-null when `mPost` is null? If so, calling `mPost.isPage()` here might result in an NPE.

Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/PostUploadService.java]: Probably not: https://github.com/wordpress-mobile/WordPress-Android/blob/issue/2479-npe-postuploadservice-oncancelled/WordPress/src/main/java/org/wordpress/android/ui/posts/PostUploadService.java#L199-L201

but I'll join both `if`s.

**Comment by nbradbury** [comment]
:shipit:
