### PR TITLE
Fixing Comments list issues

### LINKED ISSUE #1175: Better UX when bulk moderating comments
Moderating 10 comments means 10 network calls, on a slow network that can lead to an horrible user experience because that step is blocking the UI and there is no way to stop it (back button doesn't work).
We should either make the back button cancel the current action or remove the blocking loading dialog (background task but not trivial)

### LINKED ISSUE #3687: Comments list not retaining state on orientation change
Steps: 
1. Open Comments activity from MySites tab.
2. Long press on any comment.
3. Contextual action bar (CAB) appears at top of the screen.
4. Rotate device.
5. Selected comments and CAB are gone.

Issue with dialogs on this screen:
When CAB is visible try to delete/approve/unapprove some comments, and while progress dialog is displayed, rotate your device - progress dialog will stick, and won't be dismissed, the only way out of this is to kill an app.

When "Trash comments" confirmation dialog is visible rotate devices - the dialog will disappear (along with selected comments).

I discovered those issues while working on CommentActivity as part of #3551 . Fix is included in upcoming PR (will be submitted after #3663 is merged).

### LINKED ISSUE #3953: Reader: Comment count is not updated after replying
To reproduce: 

Go to the reader and tap to view comments on a post. 
Note the current number of comments on the post, shown both in the post card and in the comment list header. 
Use the "Reply" form at the bottom of the screen to add a new comment. 
Notice that the comment count has not updated in the comment list header. 
Tap back to return to the post list.  Notice that the post card shows the old comment count. 
Pull to refresh the post list. 
Now the comment count is updated. 

My expectation is we'd optimistically increment and refresh the comment count without needing to sync.

### LINKED ISSUE #4275: Multi-selection of comments persist during filter change.
### Steps to reproduce the behavior
Go to Comments.
Select multiple comments using long press.
Change filter.
Selected positions persist even though the comments at those positions might be different.

### Expected behavior
Selection should be based on comment id and not on index.

### LINKED ISSUE #4276: Comments are not removed from filtered list after their status changes
### Steps to reproduce the behavior
Go to Comments.
Select Pending or Approved filter.
Select multiple comments using long press.
Perform Approve/Disapprove action from Content Action Bar.
Comments will remain in current list even though their status will no longer match the filter.

### Expected behavior
Comments will disaster from filter list after their status no longer match the filter.

Everything works as it should if you moderate individual comments.

### LINKED ISSUE #4278: Deleted/Marked as spam Comment does not appear in filtered list after snack bar dissmised
### Steps to reproduce the behavior
Go to Comments.
Select All filter.
Open any comment.
Mark it as Spam or Trash it.
While “Undo” snack bar is visible, select Spam or Trashed filter (depending on what you did with the comment)
Wait till snack bar disappears.
Comments does not appear in list.

### Expected behavior
Comment should appear in filtered list after it’s status have been changed to match filter.

### LINKED ISSUE #4279: “Load more” at Comments list doesn’t work as expected
### Steps to reproduce the behavior
Go to Comments.
Scroll down to load more.
Notice that existing comments in the list are replaced with the older comments, that were supposed to go to the end of the list.

In addition, after this, “Load more” stops working at all.

### Expected behavior
Older comments should be added to the end of the list.

### PR DESCRIPTION
**Pull request by khaykov**
Originally this PR was intended to only solve #3687, but at the end I found couple of smaller but related issues, so they are bundled together.

Currently, this PR:
Fixes #1175 - Removes blocking progress dialog while performing batch moderation.
Fixes #3687 - CAB selection, moderation progress, etc. is retained on config change.
Fixes #4275 - Comment selection now resets after filter change.
Fixes #4276 - Filtered list is updated after moderation is finished - ex. if you approve comment from Pending list, it will disappear from the list after it's status changes to Approved.
Fixes #4278 - Like with previous issue, the comment will appear in filtered list after it's status have been changed to match the Filter (usually happens when moderation finishes after you switch filter).
Fixes #4279 - Making "load more" work as intended.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/comments/CommentAdapter.java [hunk 1]
```diff
@@ -277,27 +276,37 @@ CommentList getSelectedComments() {
             return comments;
         }
 
-        for (Integer position: mSelectedPositions) {
-            if (isPositionValid(position))
-                comments.add(mComments.get(position));
+        for (Long commentId : mSelectedCommentsId) {
+            if (isCommentIdValid(commentId))
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/comments/CommentAdapter.java]: This is the only place where `isCommentIdValid` is used, and that routine calls `indexOfCommentId` which is again called below. Given that, how about dropping `isCommentIdValid` and using this:
```
for (Long commentId : mSelectedCommentsId) {
    int index = indexOfCommentId(commentId);
    if (index > -1) {
        comments.add(mComments.get(index));
    }
}
```

File: WordPress/src/main/java/org/wordpress/android/ui/comments/CommentAdapter.java [hunk 2]
```diff
@@ -450,4 +463,25 @@ protected void onPostExecute(Boolean result) {
...
+
+
+    public CommentAdapterState getAdapterState() {
+        return new CommentAdapterState(mSelectedCommentsId, mModeratingCommentsIds);
+    }
+
+    public void setInitialState(CommentAdapterState adapterState) {
+        if (adapterState == null) return;
+
+        if (adapterState.hasSelectedComments()) {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/comments/CommentAdapter.java]: Do `mSelectedCommentsId` and `mModeratingCommentsIds` need to be cleared here before adding to them?

File: WordPress/src/main/java/org/wordpress/android/ui/comments/CommentAdapterState.java [hunk 3]
```diff
@@ -0,0 +1,69 @@
...
+
+import java.util.HashSet;
+
+/**
+ * Used to store state of {@link CommentAdapter}
+ */
+public class CommentAdapterState implements Parcelable {
+    public static final String KEY = "comments_adapter_state";
+
+    private HashSet<Long> mSelectedComments;
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/comments/CommentAdapterState.java]: These can both be `final`.

File: WordPress/src/main/java/org/wordpress/android/ui/comments/CommentEvents.java [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+
+        public CommentList getComments() {
+            return mComments;
+        }
+
+        public boolean isDeleted() {
+            return mIsDeleted;
+        }
+
+        public CommentStatus getNewStatus() {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/comments/CommentEvents.java]: This is unused.

File: WordPress/src/main/java/org/wordpress/android/ui/comments/CommentEvents.java [hunk 5]
```diff
@@ -0,0 +1,62 @@
+package org.wordpress.android.ui.comments;
+
+import org.wordpress.android.models.CommentList;
+import org.wordpress.android.models.CommentStatus;
+
+class CommentEvents {
+
+    public static class CommentsBatchModerationFinishedEvent {
+        private CommentList mComments;
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/comments/CommentEvents.java]: All three of these can be `final`.

File: WordPress/src/main/java/org/wordpress/android/ui/comments/CommentEvents.java [hunk 6]
```diff
@@ -0,0 +1,62 @@
...
+        }
+
+        public CommentStatus getNewStatus() {
+            return mNewStatus;
+        }
+
+    }
+
+    public static class CommentModerationFinishedEvent {
+        private boolean mIsSuccess;
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/comments/CommentEvents.java]: These can all be `final`, too.

File: WordPress/src/main/java/org/wordpress/android/ui/comments/CommentsListFragment.java [hunk 7]
```diff
@@ -739,4 +636,148 @@ public void onDestroyActionMode(ActionMode mode) {
...
+        EventBus.getDefault().register(this);
+    }
+
+    @Override
+    public void onStop() {
+        EventBus.getDefault().unregister(this);
+        super.onStop();
+    }
+
+    public void onEventMainThread(CommentEvents.CommentModerationFinishedEvent event) {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/comments/CommentsListFragment.java]: Although this isn't really necessary, I like to add `@SuppressWarnings("unused")` to all `onEvent` handlers to avoid the AS lint warning about it being unused.

File: WordPress/src/main/java/org/wordpress/android/ui/comments/CommentAdapter.java (hunk 2 above)
Comment (khaykov) [inline WordPress/src/main/java/org/wordpress/android/ui/comments/CommentAdapter.java]: Technically no, but you are right, it's definitely better to clear them, just in case - we never know when the `setInitialState` might be called.

**Comment by khaykov** [comment]
Thanks for the review, Nick! 🙇 

On the side note, I should probably run a code inspector to catch all the minor issues, before making a PR 😊

**Comment by nbradbury** [comment]
@khaykov This looks great, but unfortunately I just ran into a bug: when multiple comments are in the process of being moderated, you can still select a comment and enable CAB mode. That wasn't an issue before since doing that was blocked by the dialog.

I can file that as a separate issue if you'd like to see this one merged, though.

**Comment by khaykov** [comment]
@nbradbury Good catch! I made comments that are being moderated not selectable. You can still select (and moderate) other comments while doing separate batch moderation. 
I think this issue was there before - you can moderate single comment and still select it with long press.

**Comment by nbradbury** [comment]
Looks good! :shipit:
