### PR TITLE
Fix magic link login tracking

### LINKED ISSUE #4919: All sign in events are being tracked as magic link logins
We only want it to be true when the user actually logs in with magic links

### PR DESCRIPTION
**Pull request by kwonye**
Fixes #4919 

To test: Login with username/password and verify that [this line](https://github.com/wordpress-mobile/WordPress-Android/blob/hotfix/6.2.1/WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java#L400) is not hit

Login with magic link and verify that the line hits

### CODE REVIEW

**Comment by kwonye** [comment]
Also cherry-picking in b7c1f03 from the `6.3` branch as it can fix a few crashes we've been seeing on `6.2`

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInFragment.java [hunk 1]
```diff
@@ -133,7 +133,7 @@
 
     private OnMagicLinkRequestInteraction mListener;
     private String mToken = "";
-    private boolean mInhibitMagicLogin;
+    private boolean mShouldReturnToPreviousActivity;
```
Comment (hypest) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInFragment.java]: @kwonye , can you elaborate on the rename? I know the commit message reads "...as it previously implied that it was non-magic links..." but not sure it implied that. Thanks!

Let me share some background on the naming of mInhibitMagicLogin:
`mInhibitMagicLogin` being true means the code should _prevent_ the magic-links flow from happening. `mInhibitMagicLogin` being false means the code is free to engage in magic-links or not, based on other conditions.
So, it's not a state variable for whether magic-links is actually in-effect or not. Perhaps we can tweak its name a bit, like rename it to "mPreventMagicLinks" if that makes it easier to understand.

Then again, "mShouldReturnToPreviousActivity" to me sounds like it might interfere somehow with the normal way Android handles activities. For example, if this fragment (parent activity anyway) was started via a `startActivityForResult` then the system _will_ return to the calling activity when this one finishes but, the `mShouldReturnToPreviousActivity` name seems to imply it might not.

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInFragment.java [hunk 2]
```diff
@@ -148,7 +148,7 @@ public void onCreate(Bundle savedInstanceState) {
             mSelfHosted = savedInstanceState.getBoolean(KEY_IS_SELF_HOSTED);
         }
 
-        mInhibitMagicLogin = getActivity() != null
+        mShouldReturnToPreviousActivity = getActivity() != null
```
Comment (hypest) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInFragment.java]: If we go with the rename, let's add some comment here to explain for example why an email client being unavailable governs the return to the previous activity or not. Thanks!

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInFragment.java (hunk 1 above)
Comment (kwonye) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInFragment.java]: For someone new coming into the code base, `mInhibitMagicLogin` will not help them understand why we need that boolean set at all. Magic Links isn't the reason we set that boolean, it's because we need to make sure the stack isn't cleared so that we can go back to the previous activity.

Right now, whether or not the user uses magic links, it clears the stack. So the reader of the code will see this if the name includes magic links:
```
if (can't be magic link login) {
  sign in
  finish activity
} else { // can be magic link or username login
  sign in
  clear stack
  finish activity
}
```
Because this is the only place we're using the boolean as a switch, I think it's important that we focus on making it as clear as possible here.

**Comment by maxme** [comment]
Note: moved this to 6.3 (release is next Monday), please merge it in `release/6.3`

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInFragment.java (hunk 1 above)
Comment (hypest) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInFragment.java]: > For someone new coming into the code base, mInhibitMagicLogin will not help them understand why we need that boolean set at all.

Oh I see. If it's for the "why" then I think we should add some comments to help with that. Notice that `mShouldReturnToPreviousActivity` doesn't explain the "why" either, especially since for a new-comer the typical way to control "return to previous activity" is a combination of `setResult()` and `finish()`. The new-comer might ask: "how come mShouldReturnToPreviousActivity being true means bypassing the magic-links flow?"

Also notice that the `mShouldReturnToPreviousActivity` assignment includes a check for an email handler which makes even less sense than before and begs for a comment to explain "why" the existence or not of an email handler affects the return to the previous activity.

In the end, I still think that `mShouldReturnToPreviousActivity` is less clear than `mInhibitMagicLogin` but let's not block on this. I'd recommend adding a comment to explain the why for the flag and perhaps even rename the `EXTRA_INHIBIT_MAGIC_LOGIN` constant to match the flag. WDYT?

**Comment by maxme** [comment]
Note this was closed because I deleted the target branch (`release/6.3`), this was not my intention to close it.

**Comment by kwonye** [comment]
No worries, @maxme. My fault as I mistakenly thought `6.2` was the last release until the new year, hence the `6.2.1` hotfix target.

I'll be moving this to `6.4` as we can't correctly determine how many people successfully log in with magic links, which is something we want to track as soon as possible.

**Comment by kwonye** [comment]
@maxme Stefanos has agreed to let me have someone else review this as he's off for vacation. Do you mind reviewing this please? Thanks!

**Comment by maxme** [comment]
The use of `mIsMagicLinksEnabled` and `mInhibitMagicLogin` is very confusing, can we add some comments to explain when one or the other is used.

Also, I'm not sure how this solves the original issue, should we add a property in `SignInFragment.trackAnalyticsSignIn`?

**Comment by kwonye** [comment]
> The use of mIsMagicLinksEnabled and mInhibitMagicLogin is very confusing, can we add some comments to explain when one or the other is used.

Added a comment to mInhibitMagicLogin that describes what it's used for.

> Also, I'm not sure how this solves the original issue, should we add a property in SignInFragment.trackAnalyticsSignIn?

The way we track `magic_link_success` is in `WPMainActivity.checkMagicLinkSignIn()`. We were previously always returning `true` for that because of a bug. Now, we pass the correct boolean and only log that event if we actually did request a magic link.
