### PR TITLE
Fixing app log appbar icon color

### LINKED ISSUE #13067: AppBar: copy and share icons aren't visible on the "Application log" screen while in light mode
Steps to reproduce:

1. Go to My Site > Account (top right) > App Settings > Appearance and select "Light".
1. Go to My Site > Account (top right) > Help & Support > Application log.
1. Look for the copy and share icons near the top right.

**Result:** the copy and share icons are not visible on the "Application log" screen while in light mode.

application-log-screen-wpandroid-15 9-rc-1 copy-and-share-icons-not-showing-in-light-mode-wpandroid-15 9-rc-1

<sup>Tested with WPAndroid 15.9-rc-1 on Pixel 3 Android 11.</sup>

### PR DESCRIPTION
**Pull request by khaykov**
Fixes #13067

This PR fixes the color of Application Log Appbar icons by inflating the menu from xml instead of creating it in code.

[Image from Gyazo](https://gyazo.com/b028b2d51e6db9b428b3ad2f107aa3a3)

[Image from Gyazo](https://gyazo.com/b0cb655a5b500c2cc579bfe9a4fff35b)

To test:
- Navigate to Application log activity from Help scren.
- Make sure the appbar icons for Share and Copy To Clipboard are visible in both light and dark mores.
- Make sure the correct tooltip appears when you long-press menu icons.
- Make sure the menu button performs the correct action (opening share dialog and copying logs into the clipboard).

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/AppLogViewerActivity.java [hunk 1]
```diff
@@ -140,14 +141,8 @@ private void copyAppLogToClipboard() {
...
     public boolean onCreateOptionsMenu(Menu menu) {
         super.onCreateOptionsMenu(menu);
-        // Copy to clipboard button
-        MenuItem item = menu.add(Menu.NONE, ID_COPY_TO_CLIPBOARD, Menu.NONE, R.string.copy_text);
-        item.setShowAsAction(MenuItem.SHOW_AS_ACTION_IF_ROOM);
-        item.setIcon(R.drawable.ic_copy_white_24dp);
-        // Share button
-        item = menu.add(Menu.NONE, ID_SHARE, Menu.NONE, R.string.reader_btn_share);
-        item.setShowAsAction(MenuItem.SHOW_AS_ACTION_IF_ROOM);
-        item.setIcon(R.drawable.ic_share_white_24dp);
```
Comment (renanferrari) [inline WordPress/src/main/java/org/wordpress/android/ui/AppLogViewerActivity.java:150]: Since both the `ID_SHARE` and `ID_COPY_TO_CLIPBOARD` constants are not being used anymore, I think it's safe to remove them from this class?

**Review by renanferrari — COMMENTED** [review]
Thanks for the changes! I've tested in both light and dark modes and everything is working as expected. I left a comment below with a minor suggestion.

File: WordPress/src/main/java/org/wordpress/android/ui/AppLogViewerActivity.java (hunk 1 above)
Comment (khaykov) [reply WordPress/src/main/java/org/wordpress/android/ui/AppLogViewerActivity.java:150]: Good catch! Removed them 👍

**Comment by loremattei** [comment]
I'm moving this to 16.1 because 16.0 has been cut. Please, if you want this to make it to 16.0, feel free to ping me.

**Review by renanferrari — APPROVED** [review]
LGTM! :shipit:
