### PR TITLE
Fix wrong Y axis values in Swedish

### LINKED ISSUE #9308: Handle 0e00 decimal format in Start chart label
A user reported that they're seeing a number in this format `0e00` instead of just 0 - (https://android.forums.wordpress.org/topic/x-axis-of-stats-graph-showing-hex-numbers?
The `LargeValueFormatter` class in the MPAndroidChart library handles only `0E00` decimal format (coming from Java `DecimalFormat`) which is standard. We have to look into this and possible override the `LargeValueFormatter` in order to fix this issue.

### PR DESCRIPTION
**Pull request by planarvoid**
Fixes #9308 and #10071 
The value formatted by DecimalFormat is different in some languages (standard, US way is `520.0 520E00`, in Swedish it is `720.0 720×10^00`, we've seen cases of `520.0 520e00`). In the default `LargeValueFormatter` in the library we expect the first US format. In this PR I've created a new `LargeValueFormatter` in which I'm setting the default Locale to US so we always get the correct results. The `LargeValueFormatter` is mostly copy&paste of the same class in the MPAndroidChart library. 

To test:
* Change language to Swedish
* Go to Stats/DWMY
* Notice that the Y axis labels are now correct
* Check that nothing has changed in English

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/LargeValueFormatter.kt [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+import com.github.mikephil.charting.data.Entry
+import com.github.mikephil.charting.formatter.IAxisValueFormatter
+import com.github.mikephil.charting.formatter.IValueFormatter
+import com.github.mikephil.charting.utils.ViewPortHandler
+import java.text.DecimalFormat
+import java.text.DecimalFormatSymbols
+import java.util.Locale
+import kotlin.math.round
+
+class LargeValueFormatter : IValueFormatter, IAxisValueFormatter {
```
Comment (frosty) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/LargeValueFormatter.kt]: Should we add a comment saying where the original implementation of this comes from? And possibly one to explain why the format's locale is overridden?

**Review by frosty — APPROVED** [review]
Tested, and this resolved the issue for me. Same fix we used for iOS :)
