### PR TITLE
issue/15172-Mysite-url-cutoff

### LINKED ISSUE #15172: My Site: Site Info Block - Site URL is cutoff when system font is set to largest setting
### Expected behavior
The site URL should be fully visible in the site Info Block on the My Site view when the system font is set to the largest setting.

### Actual behavior
The site URL is cutoff in the site Info Block on the My Site view when the system font is set to the largest setting.

### Steps to reproduce the behavior
- Set system font to highest setting on device
- Open app
- Navigate to My Site
- Note the Site url is cutoff

###Screenshot###
Screen Shot 2021-08-12 at 8 35 34 AM

### PR DESCRIPTION
**Pull request by namanrana16**
Fixes #15172  

**Description:** When the font is set to maximum and your site title is more than 1 line, the URL of the site gets hidden. 
 This was because the Title and URL section was bound to the lower edge of the image.
I removed the restraint and made the widget accommodate for more than 2 lines as well.

**To test:** Set the font to the largest setting and open the app.

**Before:**
129197683-10e1ed47-2183-4a1a-a514-26a76698b902

**After:**
WhatsApp Image 2021-09-03 at 19 04 23

## Regression Notes
1. Potential unintended areas of impact
  None

2. What I did to test those areas of impact (or what existing automated tests I relied on)
  None

3. What automated tests I added (or what prevented me from doing so)
  None

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/widgets/MySiteTitleAndSubtitleLabelView.kt [hunk 1]
```diff
@@ -36,7 +36,7 @@ class MySiteTitleAndSubtitleLabelView @JvmOverloads constructor(
                 constraintSet.clone(this@MySiteTitleAndSubtitleLabelView)
                 constraintSet.connect(title.id, ConstraintSet.BOTTOM, guideline.id, ConstraintSet.TOP, 0)
                 constraintSet.applyTo(this@MySiteTitleAndSubtitleLabelView)
-            } else if (title.lineCount == 2 && (title.layoutParams as LayoutParams).bottomToTop == guideline.id) {
+            } else if (title.lineCount  >    1 && (title.layoutParams as LayoutParams).bottomToTop == guideline.id) {
```
Comment (ashiagr) [inline WordPress/src/main/java/org/wordpress/android/widgets/MySiteTitleAndSubtitleLabelView.kt]: Minor [fomatting issue:](https://buildkite.com/wordpress-mobile/wordpress-android/builds/1299#8b0b0c36-6d7c-4e28-be3a-0a9bb430a942/156-203) 

```suggestion
            } else if (title.lineCount > 1 && (title.layoutParams as LayoutParams).bottomToTop == guideline.id) {
```

**Review by ashiagr — COMMENTED** [review]
Thanks for fixing the issue @namanrana16!

I've verified the changes. It fixes the issue, good job 👍.  
Just left one comment regarding formatting. 

Once fixed, I'll merge the PR.

File: WordPress/src/main/java/org/wordpress/android/widgets/MySiteTitleAndSubtitleLabelView.kt (hunk 1 above)
Comment (namanrana16) [reply WordPress/src/main/java/org/wordpress/android/widgets/MySiteTitleAndSubtitleLabelView.kt]: @ashiagr  Thanks for the help. Resolved the formatting issue.

**Review by ashiagr — APPROVED** [review]
