### PR TITLE
Issue/8225 fix google sign up

### LINKED ISSUE #8225: Google sign-up doesn't work
### Expected behavior
When the user clicks on the "Sign-up with Google" button a dialog with list of Google accounts appears. When the user picks an account, the sign-up flow continues.

### Actual behavior
When the user clicks on the "Sign-up with Google" button a dialog with list of Google accounts appears. When the user picks an account, the dialog disappears, but nothing else happens.
sign-up

### Steps to reproduce the behavior
1. Open the app
2. Click on "Sign up for WordPress.com"
3. Click on "Sign up with Google"
4. Wait until a dialog with a list of google accounts is shown
5. Pick an account
6. Nothing happens

##### Tested on [device], Android [version]
Samsung Galaxy lite 2, Android 4.4

Works as expected on Pixel 2, Android 9

### PR DESCRIPTION
**Pull request by malinajirka**
Fixes #8225 #8223 

@planarvoid and I were working on this issue together, so I believe it'd be good for someone else to review this PR. 

Issues
- Infinite progress dialog that couldn't be cancelled
- No feedback after selecting an account
- generic error on deleted account
- 2FA broken when FluxC sends a verification SMS
- weird state after an unsuccessful sign up/in when all the options were broken

It'd be hard to list all the things that have been broken. Some of them were happening in rare scenarios. We have tried to cover all the use-cases and test them extensively. 
It's hard to connect the fixes with the issues, some of them fix more than one thing. Please feel free to ask if you have any doubts.

To test:
**Sign up screen**

State: New account (non 2fa)
1. Clear app data
1. Open the app
2. Click on "Sign up for WordPress.com"
3. Click on "Sign up with Google"
4. Wait until an account chooser appears
5. Select an account
6. Allow access to your Google account
7. Epilogue is shown
-------------
State: Existing WordPress account not connected to Google
1. Clear app data
1. Open the app
2. Click on "Sign up for WordPress.com"
3. Click on "Sign up with Google"
4. Wait until an account chooser appears
5. Select an account
6. Toast "Email already exists" is shown
7. Login with WordPress password is shown (if you created your account with a magic link, you need to add a password)
8. Enter your password
9. Epilogue is shown
-------------
State: Existing WordPress account connected to Google
1. Clear app data
1. Open the app
2. Click on "Sign up for WordPress.com"
3. Click on "Sign up with Google"
4. Wait until an account chooser appears
5. Select an account
6. Epilogue is shown

-------------

State: Existing WordPress account with 2fa not connected to Google 
1. Clear app data
1. Open the app
2. Click on "Sign up for WordPress.com"
3. Click on "Sign up with Google"
4. Wait until an account chooser appears
5. Select an account
6. Allow access to your Google account
7. Toast "Email already exists" is shown
8. Login with WordPress password is shown (if you created your account with a magic link, you need to add a password)
9. Enter your password
10. 2FA verification screen is shown
11. Enter the code from 2FA
12. Epilogue is shown
-------------
State: Existing WordPress account with 2fa connected to Google 
1. Clear app data
1. Open the app
2. Click on "Sign up for WordPress.com"
3. Click on "Sign up with Google"
4. Wait until an account chooser appears
5. Select an account
6. Toast "Email already exists" is shown
7. 2FA verification screen is shown
8. Enter the code from 2FA
9. Epilogue is shown

-------------------------------------------------
-------------------------------------------------

**Sign in screen**

State: Non existing account (non 2fa)
1. Clear app data
2. Open the app
3. Click on "Log in"
4. Click on "Login with Google"
5. Wait until an account chooser appears
6. Select an account
7. Dialog "The google account xyz@abc...." is shown
-------------
State: Existing WordPress account not connected to Google
1. Clear app data
2. Open the app
3. Click on "Log in"
4. Click on "Login with Google"
5. Wait until an account chooser appears
6. Select an account
7. Login with WordPress password is shown (if you created your account with a magic link, you need to add a password)
8. Enter your password
9. Epilogue is shown
-------------
State: Existing WordPress account connected to Google
1. Clear app data
2. Open the app
3. Click on "Log in"
4. Click on "Login with Google"
5. Wait until an account chooser appears
6. Select an account
7. Epilogue is shown
-------------

State: Existing WordPress account with 2fa not connected to Google 
1. Clear app data
2. Open the app
3. Click on "Log in"
4. Click on "Login with Google"
5. Wait until an account chooser appears
6. Select an account
7. Login with WordPress password is shown (if you created your account with a magic link, you need to add a password)
8. Enter your password
9. 2FA verification screen is shown
10. Enter the 2FA code
11. Epilogue is shown
-------------
State: Existing WordPress account with 2fa connected to Google 
2. Open the app
3. Click on "Log in"
4. Click on "Login with Google"
5. Wait until an account chooser appears
6. Select an account
7. 2FA verification screen is shown
8. Enter the 2FA code
9. Epilogue is shown

### CODE REVIEW

**Comment by theck13** [comment]
The test steps are the same as those from the original Google [login](https://github.com/wordpress-mobile/WordPress-Android/pull/6791) and [signup](https://github.com/wordpress-mobile/WordPress-Android/pull/6999) pull requests, which were tested and passed.  Can you be more specific about the rare scenarios so I can be sure to test the case(s) in question?

**Comment by planarvoid** [comment]
@theck13 for example 2fa:
- There are 2 usecases that might happen when you have an account with 2fa enabled and you try to login. In both usecases you receive the `OnSocialChanged`. In the usecase that passes the `requiresTwoStepAuth` is set to true, the app opens the verification screen, the user requests an SMS code and everything is ok. In the previously failing usecase the app requests the verification code by itself and returns an event in which `requiresTwoStepAuth` is false but the `notificationSent` field is filled with a text `sms`. The second usecase is valid in FluxC but it was not handled in WPAndroid. In `LoginGoogleFragment#onSocialChanged` it fell through to the last else and finished the flow. At the same time the user receives an SMS with the verification code (which is confusing because there is no verification screen). 
This broke 2fa for me in most attempts. What sometimes worked was going back and trying again. 

I'm sure @malinajirka has more usecases he can describe here.

**Comment by theck13** [comment]
Are there specific devices and/or Android version(s)?

**Comment by planarvoid** [comment]
The 2fa bug was happening to me on my Pixel 2 with Android Pie and on my emulator with Android 8. I know Jirka was testing the Google flow also on an old Samsung device.

**Comment by malinajirka** [comment]
I don't remember all the scenarios, but I'll try to list at least some of them. Not all are easily reproducible -> I just kept trying to signing in/up.

One of the infinite dialog cases 
1. Delete your WordPress account
2. Try the Google sign-up with the same email address
3. Generic error -> "There was some troubles connecting with the Google account" is shown
--------------
Broken flow - happening mostly on low cost devices with limited memory (Samsung Galaxy Lite 2 - Android 4.4).
1. Click on "Sign Up With Google"
2. Account chooser is shown
3. Select an account
4a. Sometimes an infinite dialog which can't be canceled is shown
4b. Sometimes the dialog disappears, but nothing else happens (I think the activity's onSaveInstanceState gets called -> the GoogleSignUp fragment is removed)
---------------------
Broken flow - weird state which I'm not sure how to reproduce, but happens from time to time (happened on both Pixel 2, Android 9  and Samsung Galaxy Lite 2, Android 4.4 phones)
1. Click on "Sign Up with Google"
2. Semi-transparent grey overlay is shown
3. Nothing else happens 
---------------------
Generic error message (2fa code can be generated just once per minute)
1. Login to a WordPress account with 2fa in a browser
2. Open the app
3. Click on "Log in" button
4. Click on "Log in with Google"
5. Generic error -> "There was some troubles connecting with the Google account" is shown

**Comment by theck13** [comment]
Are all four of those scenarios fixed with these changes?  It seems like the first set is due to some backend server confusion and it's not clear where that is fixed with these changes.  The second set sounds like I need to use and low-memory device with Android 4.4.  Where can I find how that is fixed with these changes?  The third set sounds inconsistent and due to another backend issue.  Which changes address that?  The fourth set seems to be the only one for certain to reproduce.  Were there changes to update the error message or was something else changed?

It's hard to follow what changes correspond to each issue.

I'm interested in specific steps for devices and/or Android versions because we tested this previously and they were verified as I mentioned.

File: libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/SignupGoogleFragment.java [hunk 1]
```diff
@@ -186,34 +224,49 @@ public void onSocialChanged(OnSocialChanged event) {
...
+            AppLog.d(T.MAIN, "GOOGLE SIGNUP: onSocialChanged - 2fa required");
             mAnalyticsListener.trackSignupSocialToLogin();
             mLoginListener.needs2faSocial(mGoogleEmail, event.userId, event.nonceAuthenticator, event.nonceBackup,
                     event.nonceSms);
-            // Kill connections with FluxC and this fragment since the flow is changing to login.
-            mDispatcher.unregister(this);
-            getActivity().getSupportFragmentManager().beginTransaction().remove(this).commit();
+            finishSignUp();
+        } else {
+            AppLog.d(T.MAIN, "GOOGLE SIGNUP: onSocialChanged - shouldn't happen - google sign in success");
```
Comment (malinajirka) [inline libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/SignupGoogleFragment.java]: Following flow is "fixed" with this else branch -> the user is redirected to "Login with WordPress password is shown" and when they try to log in a valid error message is shown (something like your account seems to be deleted, contact our support if you haven't deleted your account).
```
One of the infinite dialog cases
1. Delete your WordPress account
2. Try the Google sign-up with the same email address
3. Generic error -> "There was some troubles connecting with the Google account" is shown
```

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java [hunk 2]
```diff
@@ -158,14 +164,6 @@ protected void onCreate(Bundle savedInstanceState) {
 
     @Override
     public void onSaveInstanceState(Bundle outState) {
-        SignupGoogleFragment signupGoogleFragment;
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java]: Following flow is fixed here -> this change requires to change a lot of other code - > mainly the `finishSignupFlow` needs to be invoked in all scenarios when the flow is finished.
```
Broken flow - happening mostly on low cost devices with limited memory (Samsung Galaxy Lite 2 - Android 4.4).
Click on "Sign Up With Google"
Account chooser is shown
Select an account
4a. Sometimes an infinite dialog which can't be canceled is shown
4b. Sometimes the dialog disappears, but nothing else happens (I think the activity's onSaveInstanceState gets called -> the GoogleSignUp fragment is removed)
```

File: libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginGoogleFragment.java [hunk 3]
```diff
@@ -165,27 +181,38 @@ public void onSocialChanged(OnSocialChanged event) {
...
                 default:
-                    showErrorDialog(getString(R.string.login_error_generic));
+                    AppLog.d(T.MAIN, "GOOGLE SIGNIN: onSocialChanged - unknown error");
+                    showError(getString(R.string.login_error_generic));
                     break;
             }
-        // Response does not return error when two-factor authentication is required.
-        } else if (event.requiresTwoStepAuth) {
+            // Response does not return error when two-factor authentication is required.
+        } else if (event.requiresTwoStepAuth || "sms".equals(event.notificationSent)) {
```
Comment (malinajirka) [inline libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginGoogleFragment.java]: Following flow is fixed here and in the same `else` branch in the SignUpGoogleFragment.
```
Generic error message (2fa code can be generated just once per minute)

Login to a WordPress account with 2fa in a browser
Open the app
Click on "Log in" button
Click on "Log in with Google"
Generic error -> "There was some troubles connecting with the Google account" is shown
```

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java (hunk 2 above)
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java]: I think following flow got fixed as part of this change as well. It sometimes happens in the production version of the app but never happened in this branch. What might have also helped to fix this issue is, that we always disconnect the GoogleApiClient when the activityResult is returned.
```
Broken flow - weird state which I'm not sure how to reproduce, but happens from time to time (happened on both Pixel 2, Android 9 and Samsung Galaxy Lite 2, Android 4.4 phones)

Clic

1. k on "Sign Up with Google"
2. Semi-transparent grey overlay is shown
3. Nothing else happens
```

**Comment by malinajirka** [comment]
I agree you'll need a low cost device to test the second set. However, I've tested it extensively after the changes and afaik it works.

>It's hard to follow what changes correspond to each issue.

I've tried to add some in-code comments pointing to specific lines. However, I'd suggest to review and test the code without keeping focus on which line fixes which issue.

>I'm interested in specific steps for devices and/or Android versions because we tested this previously and they were verified as I mentioned.

Unfortunately, I don't have more info than what I provided in my previous comment. I agree it's not exactly specific, but both Vojta and I had troubles when we tried to sign-up in the production version of the app and I believe it works pretty well now. I think one of the reasons why it worked during the tests is that most people test it with same type of a phone. Maybe, it's also possible the Google Services got updated since the feature was tested - who knows.

**Comment by malinajirka** [comment]
Last thing I'd like to add. I definitely don't want to give an impression that I think this issue is someones fault (developer's, reviewer's, tester's or anyone's else). We've all experienced releasing a code which worked and was tested, but turned out to have some issues in the future. I'm looking forward to see if these changes will have any impact on percentage of successful sign up/in :-).

File: libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/SignupGoogleFragment.java [hunk 4]
```diff
@@ -186,34 +224,49 @@ public void onSocialChanged(OnSocialChanged event) {
...
+           handleUserExists();
```
Comment (theck13) [inline libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/SignupGoogleFragment.java]: The `handleUserExists();` statement is indented three spaces.  Let's make it four for consistency.

File: libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/SignupGoogleFragment.java [hunk 5]
```diff
@@ -186,34 +224,49 @@ public void onSocialChanged(OnSocialChanged event) {
...
+                    AppLog.d(T.MAIN, "GOOGLE SIGNUP: onSocialChanged - error - sms code throttled");
+                    showError(getString(R.string.login_error_sms_throttled));
                     break;
                 default:
-                    showErrorDialog(getString(R.string.login_error_generic));
+                    AppLog.d(T.MAIN, "GOOGLE SIGNUP: onSocialChanged - error - unknown");
+                    showError(getString(R.string.login_error_generic));
                     break;
             }
             // Response does not return error when two-factor authentication is required.
```
Comment (theck13) [inline libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/SignupGoogleFragment.java]: This comment was accidentally indented most likely due to autoformatting outside of these changes. Let's move it back to keep it inline with the `else if` branch it describes.

File: libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/SignupGoogleFragment.java [hunk 6]
```diff
@@ -186,34 +224,49 @@ public void onSocialChanged(OnSocialChanged event) {
...
-        } else if (event.requiresTwoStepAuth) {
+        } else if (event.requiresTwoStepAuth || "sms".equals(event.notificationSent)) {
```
Comment (theck13) [inline libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/SignupGoogleFragment.java]: Let's replace the hard-coded `"sms"` with a constant like `Login2FaFragment.TWO_FACTOR_TYPE_SMS`.

File: libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginGoogleFragment.java (hunk 3 above)
Comment (theck13) [inline libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginGoogleFragment.java]: Let's replace the hard-coded `"sms"` with a constant like `Login2FaFragment.TWO_FACTOR_TYPE_SMS`.

File: libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/SignupGoogleFragment.java (hunk 1 above)
Comment (theck13) [inline libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/SignupGoogleFragment.java]: For better differentiation between the two, we used Google *login* or *signup* rather than *signin*.  Let's update `sign in` to `signup` for consistency.

File: libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/SignupGoogleFragment.java [hunk 7]
```diff
@@ -186,34 +224,49 @@ public void onSocialChanged(OnSocialChanged event) {
             switch (event.error.type) {
                 // WordPress account exists with input email address, and two-factor authentication is required.
                 case TWO_STEP_ENABLED:
+                    AppLog.d(T.MAIN, "GOOGLE SIGNUP: onSocialChanged - error - two step authentication");
                     mAnalyticsListener.trackSignupSocialToLogin();
                     mLoginListener.showSignupToLoginMessage();
                     // Dispatch social login action to retrieve data required for two-factor authentication.
                     PushSocialPayload payload = new PushSocialPayload(mIdToken, SERVICE_TYPE_GOOGLE);
+                    AppLog.d(T.MAIN,
+                            "GOOGLE SIGNUP: onSocialChanged - error - two step authentication - dispatching "
```
Comment (theck13) [inline libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/SignupGoogleFragment.java]: The first part of the string can be on the previous line with the second part can be on the second since it makes the line longer than 120 characters.

File: libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/SignupGoogleFragment.java [hunk 8]
```diff
@@ -186,34 +224,49 @@ public void onSocialChanged(OnSocialChanged event) {
...
+        } else if (event.requiresTwoStepAuth || "sms".equals(event.notificationSent)) {
+            AppLog.d(T.MAIN, "GOOGLE SIGNUP: onSocialChanged - 2fa required");
             mAnalyticsListener.trackSignupSocialToLogin();
             mLoginListener.needs2faSocial(mGoogleEmail, event.userId, event.nonceAuthenticator, event.nonceBackup,
                     event.nonceSms);
-            // Kill connections with FluxC and this fragment since the flow is changing to login.
-            mDispatcher.unregister(this);
-            getActivity().getSupportFragmentManager().beginTransaction().remove(this).commit();
+            finishSignUp();
+        } else {
```
Comment (theck13) [inline libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/SignupGoogleFragment.java]: We shouldn't make the assumption all scenarios that aren't an error and not two-factor authentication are a deleted WordPress account.  It's possible that's not the case and we're directing them to login, which may be incorrect and confusing to the user.  If we can ensure it's a deleted account, we should catch that case, show an appropriate message, and track that event specifically.  If we can't, let's keep the generic error message and remove the `SignupGoogleFragment` to fix the indefinite dialog scenario.

Also, we're triggering the `trackSignupSocialAccountsNeedConnecting` statistic from the `handleUserExists` method, which should only be called when we're certain the user exists and their WordPress/Google accounts need to be connected.  That's not true if they deleted their account.

**Comment by aerych** [comment]
Thanks @malinajirka for wrangling this. :)

Can I ask a favor?  Authentication has quite a bit of complicated logic (as I'm sure you've seen by now) and we want to be very cautious about introducing a new regression in the course of fixing another.  Testing all the different flows is very time consuming and with the more things a single PR fixes the easier it becomes to start to miss things during testing.  Some of the glitches being fixed in this PR sound very tricky to reproduce, making the reviewer's job a bit harder.   

With that in mind, I'm wondering if there is a way to break this PR into two or more smaller more targeted PRs where testing could also be more focused and less likely to overlook anything?  What do you think?

I understand that some changes resolve multiple issues so not everything can be broken up, but any separation that makes the code more focused would be helpful.

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java [hunk 9]
```diff
@@ -76,7 +80,7 @@
 
 public class LoginActivity extends AppCompatActivity implements ConnectionCallbacks, OnConnectionFailedListener,
         Callback, LoginListener, GoogleListener, LoginPrologueListener, SignupSheetListener,
-        HasSupportFragmentInjector {
+        HasSupportFragmentInjector, BasicDialogPositiveClickInterface {
```
[the remark this answers is not in the document]
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java]: BasicDialogFragments verifies in the onAttach method that the parent activity implements the interface and throws an exception if it doesn't.

File: WordPress/src/main/res/values/strings.xml [hunk 10]
```diff
@@ -2066,6 +2066,7 @@
     <string name="login_error_button">Close</string>
     <string name="login_error_email_not_found">The Google account \'%s\' doesn\'t match any existing account on WordPress.com.</string>
     <string name="login_error_generic">There was some trouble connecting with the Google account.</string>
+    <string name="login_error_sms_throttled">Too many attempts on sending SMS verification code. Try again in a minute.</string>
```
[the remark this answers is not in the document]
Comment (malinajirka) [reply WordPress/src/main/res/values/strings.xml]: 👍

**Comment by malinajirka** [comment]
Thanks @aerych for your comment. I've considered breaking this PR into more smaller PRs, but I decided having everything in one PR makes more sense to me for the following reasons

- we'd have to test all the scenarios in each of these PRs since the components aren't atomic
- the changes are very connected and it's quite hard to break them into different PRs (we changed the logic how/when we remove the Login/SignUp fragments -> just this change makes us test everything)
- I can't test it anymore since I've reached a limit on my phone number so I can't create any more Google accounts
- It'd take me a lot of time and I wouldn't be able to make it in the Hack week time frame

File: libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/SignupGoogleFragment.java (hunk 8 above)
Comment (malinajirka) [reply libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/SignupGoogleFragment.java]: I don't think we are making ` the assumption all scenarios that aren't an error and not two-factor authentication are a deleted WordPress account`. We are making an assumption that all scenarios that aren't an error or not two-factor authentication are successful. I've renamed the `handleUserExists` to `loginViaSocialAccount` to make it more clear. Wdyt?

File: libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/GoogleFragment.java [hunk 11]
```diff
@@ -52,14 +58,22 @@
...
+        void onGoogleSignupError(String msg);
     }
 
     @Override
     public void onCreate(Bundle savedInstanceState) {
         super.onCreate(savedInstanceState);
-
-        // Restore state of error resolving.
-        mIsResolvingError = savedInstanceState != null && savedInstanceState.getBoolean(STATE_RESOLVING_ERROR, false);
+        mDispatcher.register(this);
```
[the remark this answers is not in the document]
Comment (malinajirka) [reply libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/GoogleFragment.java]: The dispatcher is unregistered in `onDestroy`, therefor it's registered in the `onCreate`. This is one of the changes I'm not 100% sure about.

File: libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/GoogleFragment.java [hunk 12]
```diff
@@ -183,16 +201,24 @@ protected void disconnectGoogleClient() {
...
-        AlertDialog dialog = new AlertDialog.Builder(new ContextThemeWrapper(getActivity(), R.style.LoginTheme))
-                .setMessage(message)
-                .setPositiveButton(R.string.login_error_button, null)
-                .create();
-        dialog.show();
+    protected void finishSignUp() {
+        /* This flag might get lost when the finishSignUp is called after the fragment's
+         onSaveInstanceState was called - however it's a very rare case, since the fragment is retained across
+         config changes.  */
+        mFinished = true;
```
[the remark this answers is not in the document]
Comment (malinajirka) [reply libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/GoogleFragment.java]: I think it handles following situation
1. Device is rotated
2. Event is received and as result `finishSignUp()/finishFlow()` is called
3. The mFinished is set to true
4. commitAllowingStateLoss is called, but since the configuration change is ongoing, the state is lost
5. New Activity is created
6. Retained GoogleFragments is attached
7. It removes itself, because mFinished is true

It doesn't solve the situation when the retained GoogleFragment is destroyed by the system and recreated, but it's such a rare case, that I believe it's ok to keep it as it is.

Wdyt?

[the remark this answers is not in the document]
Comment (malinajirka) [reply libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/GoogleFragment.java]: I've added a comment to the flag.

**Comment by malinajirka** [comment]
Thank you @theck13 !!! I've fixed most of the issues you've pointed out. I have left comments for those I haven't fixed. 

I believe it's ready for another round. Thank you!!

File: WordPress/src/main/res/values/strings.xml (hunk 10 above)
[the remark this answers is not in the document]
Comment (michelleweber) [reply WordPress/src/main/res/values/strings.xml]: Tweaks for 2 and 4:
- There's no WordPress.com account matching this Google account.
- We've made too many attempts to send an SMS verification code -- take a break, and request a new one in a minute.

On the "There was some trouble..." is there something we can tell them about what to do next? Wait a few minutes and try again?

[the remark this answers is not in the document]
Comment (malinajirka) [reply WordPress/src/main/res/values/strings.xml]: Thank you @michelleweber ! 
>On the "There was some trouble..." is there something we can tell them about what to do next? Wait a few minutes and try again?

Nope, it's an unexpected state and we don't know if there is something wrong with their account/our app/server.

**Comment by AmandaRiu** [comment]
Crash:

Android API 24 (7.0) Samsung Galaxy S6

**Steps:**
1. Opened WordPress app after fresh install
2. Click signup
3. Click to signup with google
4. Select google account - google chooser closes
5. Nothing happens

[Full Log](https://www.dropbox.com/s/kmc555buzvh6cgk/full_log.log?dl=0)

**Notable Log messages:**
```
2018-09-05 17:33:36.972 23077-23077/org.wordpress.android I/WordPress-STATS: 🔵 Tracked: signup_google_button_tapped
2018-09-05 17:33:36.992 23077-23077/org.wordpress.android D/dagger.android.support: An injector for org.wordpress.android.login.SignupGoogleFragment was found in org.wordpress.android.ui.accounts.LoginActivity
2018-09-05 17:33:37.234 23077-23077/org.wordpress.android D/WordPress-MAIN: GOOGLE SIGNUP: startFlow
2018-09-05 17:33:41.987 23077-23077/org.wordpress.android D/WordPress-MAIN: GOOGLE SIGNUP: sign up result returned - canceled
2018-09-05 17:33:41.987 23077-23077/org.wordpress.android W/WordPress-STATS: There is NO match for the event SIGNUP_SOCIAL_BUTTON_FAILUREstat
2018-09-05 17:33:41.987 23077-23077/org.wordpress.android E/WordPress-NUX: Google Signup Failed: result was CANCELED.
2018-09-05 17:33:41.988 23077-23077/org.wordpress.android D/WordPress-MAIN: GOOGLE SIGNUP/LOGIN: finishing signup/login
2018-09-05 17:33:42.038 23077-23077/org.wordpress.android D/WordPress-MAIN: GOOGLE SIGNUP/LOGIN: disconnecting google client
```

**Exception:**
```
2018-09-05 17:28:39.825 23077-23077/org.wordpress.android I/chromium: [INFO:aw_field_trial_creator.cc(52)] First-WebView-Experiment found, group=Control
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art: Rejecting re-init on previously-failed class java.lang.Class<ul>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/SafeBrowsingResponse;
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at xf com.android.webview.chromium.WebViewChromiumFactoryProvider.a(android.webkit.WebView, android.content.Context) (SourceFile:209)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void com.android.webview.chromium.WebViewChromium.init(java.util.Map, boolean) (SourceFile:63)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:636)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:572)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int) (WebView.java:555)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet) (WebView.java:542)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void android.webkit.WebView.<init>(android.content.Context) (WebView.java:532)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void org.wordpress.android.fluxc.network.UserAgent.<init>(android.content.Context, java.lang.String) (UserAgent.java:18)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at org.wordpress.android.fluxc.network.UserAgent org.wordpress.android.modules.AppConfigModule.provideUserAgent(android.content.Context) (AppConfigModule.java:22)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at org.wordpress.android.fluxc.network.UserAgent org.wordpress.android.modules.AppConfigModule_ProvideUserAgentFactory.get() (AppConfigModule_ProvideUserAgentFactory.java:30)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at java.lang.Object org.wordpress.android.modules.AppConfigModule_ProvideUserAgentFactory.get() (AppConfigModule_ProvideUserAgentFactory.java:10)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at org.wordpress.android.fluxc.network.rest.wpcom.account.AccountRestClient org.wordpress.android.fluxc.module.ReleaseNetworkModule_ProvideAccountRestClientFactory.get() (ReleaseNetworkModule_ProvideAccountRestClientFactory.java:68)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at java.lang.Object org.wordpress.android.fluxc.module.ReleaseNetworkModule_ProvideAccountRestClientFactory.get() (ReleaseNetworkModule_ProvideAccountRestClientFactory.java:15)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at java.lang.Object dagger.internal.DoubleCheck.get() (DoubleCheck.java:47)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at org.wordpress.android.fluxc.store.AccountStore org.wordpress.android.fluxc.store.AccountStore_Factory.get() (AccountStore_Factory.java:58)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at java.lang.Object org.wordpress.android.fluxc.store.AccountStore_Factory.get() (AccountStore_Factory.java:14)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at java.lang.Object dagger.internal.DoubleCheck.get() (DoubleCheck.java:47)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void org.wordpress.android.WordPress_MembersInjector.injectMembers(org.wordpress.android.WordPress) (WordPress_MembersInjector.java:100)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void org.wordpress.android.WordPress_MembersInjector.injectMembers(java.lang.Object) (WordPress_MembersInjector.java:17)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void org.wordpress.android.modules.DaggerAppComponentDebug.inject(org.wordpress.android.WordPress) (DaggerAppComponentDebug.java:2220)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void org.wordpress.android.WordPress.onCreate() (WordPress.java:225)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void org.wordpress.android.WordPressDebug.onCreate() (WordPressDebug.java:14)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1032)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5876)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void android.app.ActivityThread.-wrap3(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1699)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void android.os.Looper.loop() (Looper.java:154)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6682)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:1520)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:1410)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.SafeBrowsingResponse" on path: DexPathList[[zip file "/data/app/com.android.chrome-2/base.apk"],nativeLibraryDirectories=[/data/app/com.android.chrome-2/lib/arm64, /data/app/com.android.chrome-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at xf com.android.webview.chromium.WebViewChromiumFactoryProvider.a(android.webkit.WebView, android.content.Context) (SourceFile:209)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void com.android.webview.chromium.WebViewChromium.init(java.util.Map, boolean) (SourceFile:63)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:636)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:572)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int) (WebView.java:555)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet) (WebView.java:542)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void android.webkit.WebView.<init>(android.content.Context) (WebView.java:532)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void org.wordpress.android.fluxc.network.UserAgent.<init>(android.content.Context, java.lang.String) (UserAgent.java:18)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at org.wordpress.android.fluxc.network.UserAgent org.wordpress.android.modules.AppConfigModule.provideUserAgent(android.content.Context) (AppConfigModule.java:22)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at org.wordpress.android.fluxc.network.UserAgent org.wordpress.android.modules.AppConfigModule_ProvideUserAgentFactory.get() (AppConfigModule_ProvideUserAgentFactory.java:30)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at java.lang.Object org.wordpress.android.modules.AppConfigModule_ProvideUserAgentFactory.get() (AppConfigModule_ProvideUserAgentFactory.java:10)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at org.wordpress.android.fluxc.network.rest.wpcom.account.AccountRestClient org.wordpress.android.fluxc.module.ReleaseNetworkModule_ProvideAccountRestClientFactory.get() (ReleaseNetworkModule_ProvideAccountRestClientFactory.java:68)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at java.lang.Object org.wordpress.android.fluxc.module.ReleaseNetworkModule_ProvideAccountRestClientFactory.get() (ReleaseNetworkModule_ProvideAccountRestClientFactory.java:15)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at java.lang.Object dagger.internal.DoubleCheck.get() (DoubleCheck.java:47)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at org.wordpress.android.fluxc.store.AccountStore org.wordpress.android.fluxc.store.AccountStore_Factory.get() (AccountStore_Factory.java:58)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at java.lang.Object org.wordpress.android.fluxc.store.AccountStore_Factory.get() (AccountStore_Factory.java:14)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at java.lang.Object dagger.internal.DoubleCheck.get() (DoubleCheck.java:47)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void org.wordpress.android.WordPress_MembersInjector.injectMembers(org.wordpress.android.WordPress) (WordPress_MembersInjector.java:100)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void org.wordpress.android.WordPress_MembersInjector.injectMembers(java.lang.Object) (WordPress_MembersInjector.java:17)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void org.wordpress.android.modules.DaggerAppComponentDebug.inject(org.wordpress.android.WordPress) (DaggerAppComponentDebug.java:2220)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void org.wordpress.android.WordPress.onCreate() (WordPress.java:225)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void org.wordpress.android.WordPressDebug.onCreate() (WordPressDebug.java:14)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1032)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5876)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void android.app.ActivityThread.-wrap3(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1699)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void android.os.Looper.loop() (Looper.java:154)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6682)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:1520)
2018-09-05 17:28:39.877 23077-23077/org.wordpress.android I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:1410)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art: Rejecting re-init on previously-failed class java.lang.Class<xo>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/RenderProcessGoneDetail;
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at xf com.android.webview.chromium.WebViewChromiumFactoryProvider.a(android.webkit.WebView, android.content.Context) (SourceFile:209)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void com.android.webview.chromium.WebViewChromium.init(java.util.Map, boolean) (SourceFile:63)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:636)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:572)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int) (WebView.java:555)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet) (WebView.java:542)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void android.webkit.WebView.<init>(android.content.Context) (WebView.java:532)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void org.wordpress.android.fluxc.network.UserAgent.<init>(android.content.Context, java.lang.String) (UserAgent.java:18)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at org.wordpress.android.fluxc.network.UserAgent org.wordpress.android.modules.AppConfigModule.provideUserAgent(android.content.Context) (AppConfigModule.java:22)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at org.wordpress.android.fluxc.network.UserAgent org.wordpress.android.modules.AppConfigModule_ProvideUserAgentFactory.get() (AppConfigModule_ProvideUserAgentFactory.java:30)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at java.lang.Object org.wordpress.android.modules.AppConfigModule_ProvideUserAgentFactory.get() (AppConfigModule_ProvideUserAgentFactory.java:10)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at org.wordpress.android.fluxc.network.rest.wpcom.account.AccountRestClient org.wordpress.android.fluxc.module.ReleaseNetworkModule_ProvideAccountRestClientFactory.get() (ReleaseNetworkModule_ProvideAccountRestClientFactory.java:68)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at java.lang.Object org.wordpress.android.fluxc.module.ReleaseNetworkModule_ProvideAccountRestClientFactory.get() (ReleaseNetworkModule_ProvideAccountRestClientFactory.java:15)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at java.lang.Object dagger.internal.DoubleCheck.get() (DoubleCheck.java:47)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at org.wordpress.android.fluxc.store.AccountStore org.wordpress.android.fluxc.store.AccountStore_Factory.get() (AccountStore_Factory.java:58)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at java.lang.Object org.wordpress.android.fluxc.store.AccountStore_Factory.get() (AccountStore_Factory.java:14)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at java.lang.Object dagger.internal.DoubleCheck.get() (DoubleCheck.java:47)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void org.wordpress.android.WordPress_MembersInjector.injectMembers(org.wordpress.android.WordPress) (WordPress_MembersInjector.java:100)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void org.wordpress.android.WordPress_MembersInjector.injectMembers(java.lang.Object) (WordPress_MembersInjector.java:17)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void org.wordpress.android.modules.DaggerAppComponentDebug.inject(org.wordpress.android.WordPress) (DaggerAppComponentDebug.java:2220)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void org.wordpress.android.WordPress.onCreate() (WordPress.java:225)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void org.wordpress.android.WordPressDebug.onCreate() (WordPressDebug.java:14)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1032)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5876)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void android.app.ActivityThread.-wrap3(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1699)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void android.os.Looper.loop() (Looper.java:154)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6682)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:1520)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:1410)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.RenderProcessGoneDetail" on path: DexPathList[[zip file "/data/app/com.android.chrome-2/base.apk"],nativeLibraryDirectories=[/data/app/com.android.chrome-2/lib/arm64, /data/app/com.android.chrome-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at xf com.android.webview.chromium.WebViewChromiumFactoryProvider.a(android.webkit.WebView, android.content.Context) (SourceFile:209)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void com.android.webview.chromium.WebViewChromium.init(java.util.Map, boolean) (SourceFile:63)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:636)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:572)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int) (WebView.java:555)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet) (WebView.java:542)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void android.webkit.WebView.<init>(android.content.Context) (WebView.java:532)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void org.wordpress.android.fluxc.network.UserAgent.<init>(android.content.Context, java.lang.String) (UserAgent.java:18)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at org.wordpress.android.fluxc.network.UserAgent org.wordpress.android.modules.AppConfigModule.provideUserAgent(android.content.Context) (AppConfigModule.java:22)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at org.wordpress.android.fluxc.network.UserAgent org.wordpress.android.modules.AppConfigModule_ProvideUserAgentFactory.get() (AppConfigModule_ProvideUserAgentFactory.java:30)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at java.lang.Object org.wordpress.android.modules.AppConfigModule_ProvideUserAgentFactory.get() (AppConfigModule_ProvideUserAgentFactory.java:10)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at org.wordpress.android.fluxc.network.rest.wpcom.account.AccountRestClient org.wordpress.android.fluxc.module.ReleaseNetworkModule_ProvideAccountRestClientFactory.get() (ReleaseNetworkModule_ProvideAccountRestClientFactory.java:68)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at java.lang.Object org.wordpress.android.fluxc.module.ReleaseNetworkModule_ProvideAccountRestClientFactory.get() (ReleaseNetworkModule_ProvideAccountRestClientFactory.java:15)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at java.lang.Object dagger.internal.DoubleCheck.get() (DoubleCheck.java:47)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at org.wordpress.android.fluxc.store.AccountStore org.wordpress.android.fluxc.store.AccountStore_Factory.get() (AccountStore_Factory.java:58)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at java.lang.Object org.wordpress.android.fluxc.store.AccountStore_Factory.get() (AccountStore_Factory.java:14)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at java.lang.Object dagger.internal.DoubleCheck.get() (DoubleCheck.java:47)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void org.wordpress.android.WordPress_MembersInjector.injectMembers(org.wordpress.android.WordPress) (WordPress_MembersInjector.java:100)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void org.wordpress.android.WordPress_MembersInjector.injectMembers(java.lang.Object) (WordPress_MembersInjector.java:17)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void org.wordpress.android.modules.DaggerAppComponentDebug.inject(org.wordpress.android.WordPress) (DaggerAppComponentDebug.java:2220)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void org.wordpress.android.WordPress.onCreate() (WordPress.java:225)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void org.wordpress.android.WordPressDebug.onCreate() (WordPressDebug.java:14)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1032)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5876)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void android.app.ActivityThread.-wrap3(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1699)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void android.os.Looper.loop() (Looper.java:154)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6682)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:1520)
2018-09-05 17:28:39.882 23077-23077/org.wordpress.android I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:1410)
```

**Comment by malinajirka** [comment]
Thanks @AmandaRiu !!! 

I tested the app on Samsung Galaxy S6 Edge and it works as expected:(. The exception is there as well, so it most probably isn't related.

Are you aware of any settings on your phone which might "cause" the issue -> such as "Don't keep activities" in developer options is on or anything similar?

**Comment by rachelmcr** [comment]
I tested the following scenarios:

1. New Account
2. Old Account / Social Disconnected / Two-Factor Disabled
3. Old Account / Social Connected / Two-Factor Disabled
4. Old Account / Social Disconnected / Two-Factor Enabled
5. Old Account / Social Connected / Two-Factor Enabled
6. Jetpack Connect from Stats

Scenarios 1-5 worked exactly as expected. The last scenario connecting Jetpack did not work as expected. Here's what I expected:

0. Log in with only self-hosted site with Jetpack.
1. Go to _*Sites*_ tab.
2. Tap _*Stats*_ item.
3. Tap _*Set Up Jetpack*_ button.
4. Tap _*Don’t have an account? Sign up*_ button.
5. Tap _*Sign Up With Google*_ button.
6. Choose non-WordPress.com email address.
7. Tap _*Open Mail*_ button.
8. Open magic link email.
9. Tap _*Sign up to WordPress.com*_ button.
10. Tap _*Continue*_ button.
11. Tap _*Approve*_ button.

Here's what happened:

0. Log in with only self-hosted site with Jetpack.
1. Go to _*Sites*_ tab.
2. Tap _*Stats*_ item.
3. **Unexpected:** On the stats screen I saw an _*Install Jetpack*_ button even though Jetpack was already installed and activated. I tapped this button.
3. Jetpack connect webview automatically starts the connection.
4. Tap _*Don’t have an account? Sign up*_ button.
5. Tap _*Sign Up With Google*_ button.
6. Choose non-WordPress.com email address. (Note: There was no magic link process, but I was logged into this Google account on my device. I think that should be expected in this scenario but it deviates from the testing steps above.)
7. Tap _*Continue*_ button. (on Epilogue screen)
8. **Unexpected:** I was returned to the _*My Site*_ screen showing this error: "Check that the site URL entered is valid"
9. **Unexpected:** At this point I was logged in to my new WordPress.com account in the app, but when I tapped on the _*Stats*_ item again I still saw the _*Install Jetpack*_ button from earlier. I had to go through the Jetpack connect process again to finish connecting my new account.

I tested the same scenario in the latest 10.8 alpha (alpha-126) and the flow worked as expected there (without the magic link flow, but as mentioned I think that's expected), so this issue seems to be specific to this PR.

**Comment by AmandaRiu** [comment]
Turns out my errors were due to google services not being properly configured in my development environment. Once that issue was remedied, signup with google worked like a charm on my Samsung Galaxy s6!
