### PR TITLE
Fixes: NumberFormatExcpetion in BlockProcessor

### LINKED ISSUE #20494: NumberFormatException: s == null
Sentry Issue: [JETPACK-ANDROID-MBP](https://a8c.sentry.io/issues/5075695289/?referrer=github_integration)

```
NumberFormatException: s == null
    at java.lang.Integer.parseInt(Integer.java:577)
    at java.lang.Integer.parseInt(Integer.java:650)
    at org.wordpress.android.ui.posts.mediauploadcompletionprocessors.VideoBlockProcessor.processBlockJsonAttributes(VideoBlockProcessor.java:34)
    at org.wordpress.android.ui.posts.mediauploadcompletionprocessors.BlockProcessor.processBlock(BlockProcessor.java:98)
    at org.wordpress.android.ui.posts.mediauploadcompletionprocessors.MediaUploadCompletionProcessor.processBlock(MediaUploadCompletionProcessor.java:85)
...
(25 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by pantstamp**
Fixes #20494 

-----

This PR tries to prevent NumberFormatExpeption crashes that might occur in processBlockJsonAttributes() function of the classes that extend BlockProcessor. This crash might occur when why try to parse mRemoteId into an Integer. 

## To Test:

Just review the code as I was not able to replicate the crash. Please feel free to test otherwise if you find a way.

-----

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-Android/milestone/279">24.5</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by ravishanker — APPROVED** [review]
Thanks for taking care of this 👍 

I've also added @fluiddot since they're close to this part of the codebase.

**Comment by pantstamp** [comment]
> Thanks for taking care of this 👍
> 
> I've also added @fluiddot since they're close to this part of the codebase.

Thanks @ravishanker for reviewing this PR!

File: WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/BlockProcessor.java [hunk 1]
```diff
@@ -129,6 +131,14 @@ String processBlock(String block) {
         return processBlock(block, false);
     }
 
+     final void addIdPropertySafely(JsonObject jsonAttributes, String idName, String remoteId) {
```
Comment (fluiddot) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/BlockProcessor.java]: Nitpick: We could use this function in the future to set integer properties, so I wonder if we could name it more generically. E.g.
```suggestion
     final void addIntPropertySafely(JsonObject jsonAttributes, String propertyName, String value) {
```

**Review by fluiddot — APPROVED** [review]
LGTM 🎊 ! I couldn't manage to reproduce it either. Seems this might be triggered in an edge case, as it's unexpected that the remote ID is `null`, based on the error 🤔: `s == null` .

File: WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/BlockProcessor.java [hunk 2]
```diff
@@ -131,7 +131,7 @@ String processBlock(String block) {
         return processBlock(block, false);
     }
 
-     final void addIdPropertySafely(JsonObject jsonAttributes, String idName, String remoteId) {
+     final void addIntPropertySafely(JsonObject jsonAttributes, String propertyName, String value) {
         try {
             jsonAttributes.addProperty(idName, Integer.parseInt(remoteId));
```
Comment (fluiddot) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/BlockProcessor.java]: @pantstamp The changes I suggested in https://github.com/wordpress-mobile/WordPress-Android/pull/20495#discussion_r1530647905 weren't meant to be committed directly as it requires also updating this line with the function arguments (`propertyName` and `value`). Sorry because I didn't specify this clearly 😅 .
