### PR TITLE
fix: Address editor crashes from null listeners

### LINKED ISSUE #21656: NullPointerException: Parameter specified as non-null is null: method org.wordpress.gutenberg.GutenbergView.setContentC...
Sentry Issue: [JETPACK-ANDROID-15AY](https://a8c.sentry.io/issues/6258660117/?referrer=github_integration)

```
NullPointerException: Parameter specified as non-null is null: method org.wordpress.gutenberg.GutenbergView.setContentChangeListener, parameter listener
    at org.wordpress.android.editor.gutenberg.GutenbergKitEditorFragment.onCreateView(GutenbergKitEditorFragment.java:137)
...
(21 additional frame(s) were not displayed)
```

## Steps to Reproduce

1. Enable the experimental editor in _Me_ → _Experimental features_. 
2. Launch the editor. 
3. Rotate the device.

### PR DESCRIPTION
**Pull request by dcalhoun**
Setting the listeners within `instantiateItem` appears problematic as
this only runs for the initial launch, but not for other events that
destroy and recreate the fragment—e.g., screen rotation events.

To address this, GutenbergKit now follow the pattern of the Aztec and
GutenbergMobile editors, invoking the `initializeEditorFragment` method.
This method is described as "requesting dependency injection," which
feels like an odd statement. There is likely further opportunity to
refactor this architecture for simplicity.

Fixes #21656.

## To Test:

See: https://github.com/wordpress-mobile/WordPress-Android/issues/21656

## Regression Notes
1. Potential unintended areas of impact
    Regressions in the Aztec and Gutenberg Mobile editors.
2. What I did to test those areas of impact (or what existing automated tests I relied on)
    Manually tested.
3. What automated tests I added (or what prevented me from doing so)
    Deemed unnecessary for the experimental editor.

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

File: libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergKitEditorFragment.java [hunk 1]
```diff
@@ -125,6 +126,11 @@ public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle sa
             mSettings = (Map<String, Object>) getArguments().getSerializable(ARG_GUTENBERG_KIT_SETTINGS);
         }
 
+        // request dependency injection. Do this after setting min/max dimensions
+        if (getActivity() instanceof EditorFragmentActivity) {
+            ((EditorFragmentActivity) getActivity()).initializeEditorFragment();
+        }
+
```
Comment (dcalhoun) [inline libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergKitEditorFragment.java:133]: This pattern mirrors that found in the Aztec and Gutenberg Mobile editor implementations. 

https://github.com/wordpress-mobile/WordPress-Android/blob/25ac30b8d55169d36b5b936df6f9e6870b551b47/libs/editor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java#L258-L261

https://github.com/wordpress-mobile/WordPress-Android/blob/25ac30b8d55169d36b5b936df6f9e6870b551b47/libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergEditorFragment.java#L568-L571

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-Android/milestone/302">25.6.1</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR contains changes to <code>RELEASE-NOTES.txt</code>.<br />
Note that these changes won't affect the final version of the release notes as this version is in code freeze.<br />
Please, get in touch with a release manager if you want to update the final release notes.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by nbradbury — APPROVED** [review]
Feel free to merge when ready :shipit:
