### PR TITLE
Fix null site while updating post formats

### LINKED ISSUE #8814: NullPointerException related to PostFormats
**Relevant stack trace:**

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int org.wordpress.android.fluxc.model.SiteModel.getId()' on a null object reference
       at org.wordpress.android.fluxc.persistence.SiteSqlUtils.getPostFormats(SiteSqlUtils.java:242)
       at org.wordpress.android.fluxc.store.SiteStore.getPostFormats(SiteStore.java:1128)
       at org.wordpress.android.ui.posts.EditPostSettingsFragment.updatePostFormatKeysAndNames(EditPostSettingsFragment.java:791)
       at org.wordpress.android.ui.posts.EditPostSettingsFragment.onPostFormatsChanged(EditPostSettingsFragment.java:922)
       at java.lang.reflect.Method.invoke(Method.java)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
       at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:416)
       at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:397)
       at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:370)
       at org.greenrobot.eventbus.EventBus.post(EventBus.java:251)
       at org.wordpress.android.fluxc.Dispatcher.emitChange(Dispatcher.java:41)
       at org.wordpress.android.fluxc.store.Store.emitChange(Store.java:32)
       at org.wordpress.android.fluxc.store.SiteStore.updatePostFormats(SiteStore.java:1475)
       at org.wordpress.android.fluxc.store.SiteStore.onAction(SiteStore.java:1208)
       at java.lang.reflect.Method.invoke(Method.java)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
       at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

Reference: 5995a7f0be077a4dcc36b687-fabric

### PR DESCRIPTION
**Pull request by hypest**
Fixes #8814 

Can't reproduce the issue but, judging from the code and especially the fact that there's already null checks for both the Activity and the Site ref at the start of the updatePostFormatKeysAndNames() method, this seems like a case of timing: the Activity is lost in the time between the null check and the second `getSite()` call. The method is only trying to update some Fragment-local data so, holding on the Site ref to use it seems safe enough.

To test:

No steps available unfortunately, haven't been able to reproduce the crash.

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java [hunk 1]
```diff
@@ -778,7 +778,8 @@ private int getCurrentPostStatusIndex() {
     // Post Format Helpers
 
     private void updatePostFormatKeysAndNames() {
-        if (getActivity() == null || getSite() == null) {
+        final SiteModel site = getSite();
+        if (!isAdded() || site == null) {
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java]: I don't think we really care whether the fragment is currently added since we are not doing any view manipulation. Just a site `null` check seems enough to me since `getSite()` will check for the activity being `null`.

```suggestion
        if (site == null) {
```

Comment (hypest) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java]: True, there are no View manipulations in the method. I'd be willing to keep the `isAdded()` check only as an small optimization since the method does update some Fragment-local state, which is unneeded to do if the Fragment is not added. Hardy strong feelings on this one though.

I kept the relevant change as a separate commit anyway and happy to revert it if you still feel like removing the check. Let me know 👍

Comment (oguzkocer) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java]: Actually, I think we want to make sure we handle this at all times, since it's from a callback and we need that information. It's hardly ideal, but we didn't have `ViewModel`s when we wrote all this, so we have to live with it for now.

Comment (hypest) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java]: Good point, will leave it as is with the `isAdded()`.

Comment (oguzkocer) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java]: Umm.. I think my comment was not clear, I think we need to handle it even if the fragment is not added at the time of the callback. Sorry for the confusion.

Comment (hypest) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java]: Oh, I see :), no prob. Lemme give it a look and remove the isAdded check. Will probably also add some comment about it.

Comment (hypest) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java]: Hmm, there's a `getResources()` call in line 787 that I think will throw if the fragment is not added.

Comment (oguzkocer) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java]: Ha, I missed that in the review, good point. I guess that's why we had the `getActivity()` check before. I don't think it'd throw if it's not added though, it'd throw if the `host` is null, so I feel `getActivity()` check is still better.

A little bit of context into my thinking. I have been recently thinking about the `isAdded` checks  we have all around the app and I feel like they are just masking problems. Ideally a fragment would stop receiving callbacks once it's paused (or stopped) and the `isAdded` checks wouldn't be there for anything. We can't really fix the root cause of these `isAdded` checks for every fragment right now, but I am reluctant to use it when it's not absolutely necessary. Even a little bit of improvement is good in my opinion.

In this case, if all we need is the `resources` I think we should stick to the activity check. Having said all this and the previous comments, I don't feel too strongly about any of this for an old fragment. I am OK to go with whatever you decide at this point, just thought I'd provide all the context necessary for you to make a decision :)

Comment (hypest) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java]: Thanks for elaborating in your thinking Oguz. And I totally agree with the feeling about `isAdded()`. It's been long time now that we have sprinkled the app with it and had started to feel like snake oil :(

So, here's the thing: this originating issue points to some timing issue (which still feels weird to happen as often as it does to be honest, but anyway) so, just reinstating the `getActivity()` check doesn't feel like a safest route.

Here's what I'm thinking to do at this point:
1. Extract the initialization of the `mPostFormatKeys` and `mPostFormatNames` to an earlier point in Fragment's lifecycle and use it as cache, plus
2. only leave the `site` null check in the method

How does that sound?

Comment (oguzkocer) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java]: > Extract the initialization of the `mPostFormatKeys` and `mPostFormatNames` to an earlier point in Fragment's lifecycle and use it as cache, plus

Can we do this? If I am not mistaken, it's called in two places, one in `onActivityCreated()` the other in `onPostFormatsChanged()`. The `onActivityCreated` is one of the first places we could do it and `onPostFormatsChanged` is a FluxC callback. Maybe I am missing something, or didn't fully understand your suggestion?

> So, here's the thing: this originating issue points to some timing issue (which still feels weird to happen as often as it does to be honest, but anyway) so, just reinstating the getActivity() check doesn't feel like a safest route.

I think the issue was just that we were using `getSite` and by caching it with `final` at the beginning of the method was the necessary fix for this issue. I might be wrong though :)

Comment (hypest) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java]: Pushed d0dc7292f1 that has what I had in mind. The caching of the lists happens in `onCreate()`, quite early that is, and then using it to initialize mPostFormatKeys and mPostFormatNames.

It starts to feel like over-engineering at this point, but maybe not too much. WDYT?

Comment (oguzkocer) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java]: That works for me @hypest, just tested it as well and once that extra empty line in `Line 156` is removed, I think we can merge this in 👍

Comment (hypest) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java]: Done with 35c5ba9.
