### PR TITLE
IllegalArgumentException crash in SiteSettingsFragment  

### LINKED ISSUE #4124: Crash report 5.3: IllegalArgumentException: View not attached to window manager
```
Fatal Exception: java.lang.IllegalArgumentException: View not attached to window manager
       at android.view.WindowManagerImpl.findViewLocked(WindowManagerImpl.java:672)
       at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:368)
       at android.view.WindowManagerImpl$CompatModeWrapper.removeView(WindowManagerImpl.java:160)
       at android.app.Dialog.dismissDialog(Dialog.java:319)
       at android.app.Dialog.dismiss(Dialog.java:302)
       at org.wordpress.android.ui.prefs.SiteSettingsFragment$5.onErrorResponse(SiteSettingsFragment.java:759)
       at com.android.volley.Request.deliverError(Request.java:590)
       at com.wordpress.rest.RestRequest.deliverError(RestRequest.java:86)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:101)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4950)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1004)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:771)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

### PR DESCRIPTION
**Pull request by daniloercoli**
Fixes #4124

To test:
- Go to site settings and Tap delete site.
- (Better to use a proxy and throttle the REST request).
- Tap home button and move the app in background.
- Wait....

Also fixes another issue where the app crashes if sent in BG while retrieving purchases of a site. The callback in this other case was trying to push a new dialog fragment into the stack, but the parent/target fragment was already paused.

@maxme

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFragment.java [hunk 1]
```diff
@@ -740,6 +748,16 @@ public void onClick(DialogInterface dialog, int which) {
                 AnalyticsTracker.Stat.SITE_SETTINGS_EXPORT_SITE_ACCESSED);
     }
 
+    private void dismissProgressDialog(ProgressDialog progressDialog) {
```
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFragment.java]: I don't like this solution much, but I don't see any better. We could  use a EventBus to make fragment transaction when the activity is not paused.

**Comment by maxme** [comment]
:shipit:
