### PR TITLE
Fixes: site monitor prevent webview reload

### LINKED ISSUE #20067: Site Monitor: Prevent webview reload
Prevent the webview from reloading when navigating between tabs

### PR DESCRIPTION
**Pull request by AjeshRPai**
## Fixes 
#20067 

## Description
This PR fixes the issue of reloading of the webviews in site monitoring activity when the tabs are selected again.

[Screen_recording_20240131_151636.webm](https://github.com/wordpress-mobile/WordPress-Android/assets/17463767/7b014247-4a46-41c7-b5de-d856f718e494)  

## Pending issues 
- [Fixed] On Loading of the Webview first time - there is a glitch happening (not sure if its because of the emulator or something else)

#### Prerequisite
<details><summary>◐ Toggle the <code>site_monitoring</code> flag</summary>

1. Go to `Me` → `App Settings` → `Debug settings` → `Remote Feature Flags`
2. Tap on the item corresponding to the flag - site_monitoring
3. Tap `RESTART THE APP` button

</details>

###  Site monitor webviews are not re-loaded when selected again 
1. Go to More → Site Monitoring 
2. ✅ Verify that the logs include tracking` 🔵 Tracked: site_monitoring_screen_shown`
3. ✅  Verify that for each tab - Metrics, PHP logs and Web Server logs, the webview loads from the network first time
4. ✅ Verify that on changing tab, the logs include tracking - `🔵 Tracked: site_monitoring_tab_shown, Properties: {"tab":"php_logs"}
5. ✅ Verify that when the tabs are selected again, the webviews are not reloaded
`

## Regression Notes

1. Potential unintended areas of impact
- Site monitor webview screens are loaded on selecting tabs after the first time
- Site monitor screens are not loaded in the first time 

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing 

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:
- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
- [x] Portrait and landscape orientations.
- [x] Light and dark modes.
- [x] Fonts: Larger, smaller and bold text.
- [x] High contrast.
- [x] Talkback.
- [x] Languages with large words or with letters/accents not frequently used in English.
- [x] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [x] Large and small screen sizes. (Tablet and smaller phones)
- [x] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WordPress/src/main/java/org/wordpress/android/ui/sitemonitor/SiteMonitorParentViewModel.kt [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+
+    fun start(site: SiteModel) {
+        this.site = site
+        trackActivityLaunched()
+        metricsViewModel.start(SiteMonitorType.METRICS, SiteMonitorTabItem.Metrics.urlTemplate, site)
+        phpLogViewModel.start(SiteMonitorType.PHP_LOGS, SiteMonitorTabItem.PHPLogs.urlTemplate, site)
+        webServerViewModel.start(SiteMonitorType.WEB_SERVER_LOGS, SiteMonitorTabItem.WebServerLogs.urlTemplate, site)
+    }
+
+    fun getUiState(siteMonitorType: SiteMonitorType): MutableState<SiteMonitorUiState> {
```
Comment (pantstamp) [inline WordPress/src/main/java/org/wordpress/android/ui/sitemonitor/SiteMonitorParentViewModel.kt]: Would it be better to return here State instead of MutableState? I guess the consume is not going to modify the received state. WDYT @AjeshRPai ?

Comment (AjeshRPai) [reply WordPress/src/main/java/org/wordpress/android/ui/sitemonitor/SiteMonitorParentViewModel.kt]: Nice catch @pantstamp, You are right. Its better to return state here. Done in [f6633cf](https://github.com/wordpress-mobile/WordPress-Android/pull/20077/commits/f6633cf9d849a39afd0328dadcb88138504cae3b)

File: WordPress/src/main/java/org/wordpress/android/ui/sitemonitor/SiteMonitorTabViewModel.kt [hunk 2]
```diff
@@ -1,34 +1,35 @@
...
+    private lateinit var scope: CoroutineScope
+
     private lateinit var site: SiteModel
     private lateinit var siteMonitorType: SiteMonitorType
     private lateinit var urlTemplate: String
 
-    private val _uiState = MutableStateFlow<SiteMonitorUiState>(SiteMonitorUiState.Preparing)
-    val uiState: StateFlow<SiteMonitorUiState> = _uiState
+    private val _uiState = mutableStateOf<SiteMonitorUiState>(SiteMonitorUiState.Preparing)
+    val uiState = _uiState
```
Comment (pantstamp) [inline WordPress/src/main/java/org/wordpress/android/ui/sitemonitor/SiteMonitorTabViewModel.kt]: Is there a reason why we do not return here state instead of mutable state like this? 
`val uiState: State<SiteMonitorUiState> = _uiState`

**Comment by pantstamp** [comment]
Great work @AjeshRPai ! I really like the fact that you got rid of the fragment. I will take a look at the glitch to see what I can find.

**Comment by pantstamp** [comment]
@AjeshRPai the first time that we launch the site monitoring screen, I can see the `Tracked: site_monitoring_screen_shown` but not the `Tracked: site_monitoring_tab_shown, Properties: {"tab":"metrics"}` even though the metrics tab is shown. 

Is this what we want? I think that we should track this event even the first time.

**Review by zwarm — APPROVED** [review]
@AjeshRPai - Thanks for finding a solution to the reload issue. 👏 
With the exception of the few comment @pantstamp left, I am ready to give this a 👍 . In addition, I added a fix for the glitch. Please let me know what you think.

**Comment by zwarm** [comment]
> @AjeshRPai the first time that we launch the site monitoring screen, I can see the `Tracked: site_monitoring_screen_shown` but not the `Tracked: site_monitoring_tab_shown, Properties: {"tab":"metrics"}` even though the metrics tab is shown.
> 
> Is this what we want? I think that we should track this event even the first time.

@AjeshRPai @pantstamp - 🤔 We already capture `Tracked: more_menu_item_tapped, Properties: {"item":"site_monitoring"}`, so let's make stick with including "tab" property whenever we track `site_monitoring_tab_shown`

**Review by pantstamp — APPROVED** [review]

File: WordPress/src/main/java/org/wordpress/android/ui/sitemonitor/SiteMonitorTabViewModel.kt (hunk 2 above)
Comment (AjeshRPai) [reply WordPress/src/main/java/org/wordpress/android/ui/sitemonitor/SiteMonitorTabViewModel.kt]: You are right @pantstamp , I have updated the variable type as suggested in this commit [fb3c6b9](https://github.com/wordpress-mobile/WordPress-Android/pull/20077/commits/fb3c6b9815cda5d18f97a1a9227042a936dc91c4)
