### PR TITLE
Removed the `contentResolver.getMimeType - isSupportedMimeType() `  check for populating the picker

### LINKED ISSUE #12996: Delay in displaying images from the phone
### Expected behavior
The images from the phone should be displayed immediately

### Actual behavior
We need to wait for a few seconds for the images from the phone to get listed on the screen

### Steps to reproduce the behaviour
1. In the post/page editor, add an image block
2. Choose option add image > choose from device.
3. You will need to wait for a few seconds(~10 seconds) to get the images from the phone listed on the screen.

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #12996 

After discussion and attempting an alternative solution in #13034, this PR effectively unmakes the change introduced in https://github.com/wordpress-mobile/WordPress-Android/pull/12824 with which we wanted to offer users only those media item types that were supported on their WP sites.

To test:
1. create a GB post, add an image block
2. tap on Add Image
3. on the bottom sheet, choose "Choose from device"
4. observe the picker shows up and loads image thumbnails without issues

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/mediapicker/DeviceListBuilder.kt [hunk 1]
```diff
@@ -108,9 +107,7 @@ class DeviceListBuilder
                         getMimeType(uri),
                         dateModified
                 )
-                if (MediaUtils.isSupportedMimeType(context.contentResolver.getType(uri))) {
-                    result.add(item)
-                }
+                result.add(item)
```
Comment (planarvoid) [inline WordPress/src/main/java/org/wordpress/android/ui/mediapicker/DeviceListBuilder.kt:110]: I'm not sure why we haven't done that before but we're already calling the `getMimeType(uri)` 3 lines above this code so we could be using the mime type loaded there. However, we can do that in another PR. I think the `MediaUtils.isSupportedMimeType` is quite inefficient. We can figure out something better. 

edit: I missed that this is the updated picker, not the one that's currently released :-)

**Review by planarvoid — APPROVED** [review]
Looks good, thanks for the quick fix!

**Review by develric — APPROVED** [review]
Jumping in to confirm I tested this one with my scenario (OnePlus 7T with 8000+ media on device) and works as expected (no delay when opening picker). Thanks for the quick fix @mzorz and also for exploring the solution in #13034 🙇

File: WordPress/src/main/java/org/wordpress/android/ui/mediapicker/DeviceListBuilder.kt (hunk 1 above)
Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/mediapicker/DeviceListBuilder.kt:110]: > I'm not sure why we haven't done that before but we're already calling the getMimeType(uri) 3 lines above this code so we could be using the mime type loaded there. However, we can do that in another PR. I think the MediaUtils.isSupportedMimeType is quite inefficient. We can figure out something better.

Agreed it is inefficient and as such, contributing to time consumption while building a list seems like something we don't want. 

A proposed solution is to only check in the entry points once the item has been selected, as described here https://github.com/wordpress-mobile/WordPress-Android/issues/13036

I'd say this is something to take into account and we should probably remove the `context.contentResolver.getType(uri)` call from this class altogether as well - other solutions (for example involving pre-fetching) might apply but seem potentially beyond the effort for an issue we haven't heard many times from users anyway. Let me know your thoughts @planarvoid 👍

Comment (planarvoid) [reply WordPress/src/main/java/org/wordpress/android/ui/mediapicker/DeviceListBuilder.kt:110]: I was thinking about implementing pagination to solve this issue in the new media picker. I don't think it's very efficient to load all the images from the device anyway. I can imagine some users having tens of thousands of items and that could definitely cause other issues.

Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/mediapicker/DeviceListBuilder.kt:110]: Ah definitely a great idea! That passed over my head.
I was leaning on checking in the entry points given we may also need to filter out things per entry point / consumer of the picker to have a more granular control over the broad "supported by WP site" or the "give me video" or "give me images" sort of flags (although can't think of a good enough use case right now anyway, and if such a need appears it would still make more sense to filter in the picker right away)
Looking forward to seeing the new picker 💯
