### PR TITLE
[Reader] Fix "Your Tags" feed scrolling to top on screen orientation change

### LINKED ISSUE #20834: Tags feed position resetting to top on screen rotation.
Noticed during a PR review [here](https://github.com/wordpress-mobile/WordPress-Android/pull/20791#pullrequestreview-2049848297)

### Expected behavior
When on the Tags feed screen, if I scroll deep into the feed, I'd like the feed position to be kept on screen rotation.

### Actual behavior
When on the Tags feed screen, if I scroll deep into the feed, and I do a screen rotation, the feed position is reset to the top.

### Steps to reproduce the behavior
- Go to the tags feed (and be sure to have enough tags followed to be able to scroll into the feed)
- Scroll down into the feed
- Rotate the screen 
- Notice the position of the feed is reset to the top

### PR DESCRIPTION
**Pull request by RenanLukas**
Fixes #20834

This PR fixes two bugs:

1 - "Your Tags" feed was scrolling to top when screen orientation changed.
2 - "Your Tags" feed app bar was not collapsing on scroll (fixed by @thomashorta).

-----

### Setup
1 - Install JP and log in.
2 - Open Reader.
3 - Make sure you're subscribed to a few tags.

### Scrolling to top on screen orientation change
4 - Scroll to any item in the "Your Tags" feed.
5 - 🔍 Rotate the screen: the scroll should be at the position of the first visible item instead of scrolling to top.
6 - 🔍 Rotate the screen again: the scroll should be at the position of the first visible item instead of scrolling to top.

### App bar not collapsing on scroll
7 - 🔍 Scroll down in "Your Tags" feed: the app bar should be hidden.
8 - 🔍  Scroll up in "Your Tags" feed: the app bar that was previously hidden should be visible again.

-----

## Regression Notes

1. Potential unintended areas of impact

    - None

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - Manual testing
    
3. What automated tests I added (or what prevented me from doing so)

    - UI only

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [x] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WordPress/src/main/java/org/wordpress/android/ui/reader/views/compose/tagsfeed/ReaderTagsFeed.kt [hunk 1]
```diff
@@ -98,15 +101,17 @@ private fun Loaded(uiState: UiState.Loaded) {
             uiState.onRefresh()
         }
     )
-
     Box(
         modifier = Modifier
             .fillMaxSize()
             .pullRefresh(state = pullRefreshState),
     ) {
+        val listState = rememberLazyListState()
```
Comment (thomashorta) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/views/compose/tagsfeed/ReaderTagsFeed.kt]: 💡  Since we're not using the state for anything, I believe we can keep using the default parameter in `LazyColumn` instead of explicitly defining the state.

**Review by thomashorta — APPROVED** [review]
Overall looks good and it's working as expected. Thanks for the fixes!

I left a small suggestion, feel free to merge with or without resolving it.

File: WordPress/src/main/java/org/wordpress/android/ui/reader/views/compose/tagsfeed/ReaderTagsFeed.kt (hunk 1 above)
Comment (RenanLukas) [reply WordPress/src/main/java/org/wordpress/android/ui/reader/views/compose/tagsfeed/ReaderTagsFeed.kt]: Fixed, thanks!
