### PR TITLE
Fix NPE in onActivityResult in MediaBrowserActivity

### LINKED ISSUE #5328: Media browser: NPE trying to add a picture then cancelling
### Expected behavior
When trying to add a picture to the Media Library, it should be added, or if the action is cancelled, the user should be returned to the media browser screen.

### Actual behavior
When returning to the media browser screen without picking any picture to include in the media library, the app crashes.

```03-03 10:08:59.622 25817-25817/org.wordpress.android.beta E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: org.wordpress.android.beta, PID: 25817
                                                                            java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2000, result=0, data=null} to activity {org.wordpress.android.beta/org.wordpress.android.ui.media.MediaBrowserActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.content.Intent.getData()' on a null object reference
                                                                                at android.app.ActivityThread.deliverResults(ActivityThread.java:4089)
                                                                                at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132)
                                                                                at android.app.ActivityThread.-wrap20(ActivityThread.java)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                             Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.content.Intent.getData()' on a null object reference
                                                                                at org.wordpress.android.ui.media.MediaBrowserActivity.onActivityResult(MediaBrowserActivity.java:285)
                                                                                at android.app.Activity.dispatchActivityResult(Activity.java:6932)
                                                                                at android.app.ActivityThread.deliverResults(ActivityThread.java:4085)
                                                                                at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132) 
                                                                                at android.app.ActivityThread.-wrap20(ActivityThread.java) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:154) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
03-03 10:08:59.626 1035-4599/? W/ActivityManager:   Force finishing activity org.wordpress.android.beta/org.wordpress.android.ui.media.MediaBrowserActivity
```

### Steps to reproduce the behavior
1. Open the Media browser by going to the first tab -> Media
2. Hit the `+` button on the top-right corner, and choose "select from gallery"
3. the native picker is presented
4. Hit the device back button
5. Crash happens

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #5328 

To test:
1. Open the Media browser by going to the first tab -> Media
2. Hit the + button on the top-right corner, and choose "select from gallery"
3. the native picker is presented
4. Hit the device back button
5. instead of crashing, the media browser activity should be shown.

cc @aforcier

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java [hunk 1]
```diff
@@ -282,9 +282,13 @@ public void onActivityResult(int requestCode, int resultCode, Intent data) {
         switch (requestCode) {
             case RequestCodes.PICTURE_LIBRARY:
             case RequestCodes.VIDEO_LIBRARY:
-                Uri imageUri = data.getData();
-                String mimeType = getContentResolver().getType(imageUri);
-                fetchMedia(imageUri, mimeType);
+                if (resultCode == Activity.RESULT_OK) {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java]: This is perhaps picky, but we can simplify this to `if (resultCode == Activity.RESULT_OK && data != null)`.

Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java]: addressed in this commit fba3de1

File: WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java [hunk 2]
```diff
@@ -282,17 +282,17 @@ public void onActivityResult(int requestCode, int resultCode, Intent data) {
...
+                }
                 break;
             case RequestCodes.TAKE_PHOTO:
-                if (resultCode == Activity.RESULT_OK) {
-                    if (data != null) {
-                        Uri uri = Uri.parse(mMediaCapturePath);
-                        mMediaCapturePath = null;
-                        queueFileForUpload(uri, getContentResolver().getType(uri));
-                    }
+                if (resultCode == Activity.RESULT_OK && data != null) {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java]: I didn't notice this before, but is the check for `data != null` necessary here since `data` is unused?

Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java]: doh, addressed in 7b77738

**Comment by nbradbury** [comment]
:shipit:

File: WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java [hunk 3]
```diff
@@ -282,17 +282,17 @@ public void onActivityResult(int requestCode, int resultCode, Intent data) {
         switch (requestCode) {
             case RequestCodes.PICTURE_LIBRARY:
             case RequestCodes.VIDEO_LIBRARY:
-                Uri imageUri = data.getData();
-                String mimeType = getContentResolver().getType(imageUri);
-                fetchMedia(imageUri, mimeType);
+                if (resultCode == Activity.RESULT_OK && data != null) {
```
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java]: 👍

File: WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java [hunk 4]
```diff
@@ -282,17 +282,17 @@ public void onActivityResult(int requestCode, int resultCode, Intent data) {
...
+                    Uri imageUri = data.getData();
+                    String mimeType = getContentResolver().getType(imageUri);
+                    fetchMedia(imageUri, mimeType);
+                }
                 break;
             case RequestCodes.TAKE_PHOTO:
                 if (resultCode == Activity.RESULT_OK) {
```
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java]: Should we add `&& data != null` here as well?
