### PR TITLE
issue/6315-publicize-fragment-npe-no-site

### LINKED ISSUE #6315: Crash report 7.7-rc-1: NPE in PublicizeListFragment.onResume
```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {org.wordpress.android/org.wordpress.android.ui.publicize.PublicizeListActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2676)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2704)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2150)
       at android.app.ActivityThread.access$600(ActivityThread.java:130)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4847)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:535)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException
       at org.wordpress.android.ui.publicize.PublicizeListFragment.getAdapter(PublicizeListFragment.java:140)
       at org.wordpress.android.ui.publicize.PublicizeListFragment.onResume(PublicizeListFragment.java:70)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:886)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1047)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1029)
       at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:1824)
       at android.app.Activity.performResume(Activity.java:5271)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2666)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2704)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2150)
       at android.app.ActivityThread.access$600(ActivityThread.java:130)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4847)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:535)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #6315 - fixes the crash that was caused by a null site, also cleans up how arguments are handled.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeListFragment.java [hunk 1]
```diff
@@ -45,21 +45,16 @@ public static PublicizeListFragment newInstance(@NonNull SiteModel site) {
     }
 
     @Override
-    public void setArguments(Bundle args) {
```
Comment (tonyr59h) [inline WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeListFragment.java]: 👍

**Comment by tonyr59h** [comment]
:shipit:
