### PR TITLE
NPE sharing media to WP Media Library

### LINKED ISSUE #5666: Crash report on 7.0: NPE in MediaBrowserActivity.uploadList
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.media.MediaBrowserActivity}: java.lang.NullPointerException: url
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by java.lang.NullPointerException: url
       at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:60)
       at android.content.ContentResolver.getType(ContentResolver.java:329)
       at org.wordpress.android.ui.media.MediaBrowserActivity.uploadList(MediaBrowserActivity.java:665)
       at org.wordpress.android.ui.media.MediaBrowserActivity.handleSharedMedia(MediaBrowserActivity.java:867)
       at org.wordpress.android.ui.media.MediaBrowserActivity.onCreate(MediaBrowserActivity.java:173)
       at android.app.Activity.performCreate(Activity.java:6245)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

### PR DESCRIPTION
**Pull request by daniloercoli**
Fixes #5666 by checking that both the list, and the items into it, are not null before adding (retrieving) them.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java [hunk 1]
```diff
@@ -544,8 +544,13 @@ public void deleteMedia(final ArrayList<Integer> ids) {
     }
 
     private void uploadList(List<Uri> uriList) {
+        if (uriList == null || uriList.size() == 0) {
```
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java]: nit: I think the `uriList.size() == 0`  check here is not important as it will be checked by the `for` statement below.

**Comment by mzorz** [comment]
:shipit:
