### PR TITLE
Fix RTL tab swipe direction in notifications

### LINKED ISSUE #17530: Notifications: Tab swipe direction incorrect when set to an RTL langauge
### Expected behavior
I expected the swipe gesture to change screens in Notifications _in the same direction_ as in Reader and in Stats.

### Actual behavior
When the device language is set to Arabic or Hebrew, the Notifications screen swipes tabs in the opposite direction from Reader and Stats.
In Reader, if I start at the first tab (furthest right), I use a left-to-right swipe to move to the second tab. In Notifications, if I start at the first tab (furthest right), a left-to-right swipe does not move me to the second tab.

Reader is the correct experience. The tabs are in order and swiping left-to-right takes you to the next tab - the one to the left. 
In Notifications, swiping left-to-right takes you to the previous tab - the one that should be to the right.

### Steps to reproduce the behavior
1. In device settings, change langauge to Arabic
2. In the Jetpack app, head to Reader. Swipe between tabs. Note the order of the tabs and the progression of the green line highlighting each tab. Note which direction your finger travels across the screen for the swipe gesture (left to right).
3. Now, head to notifications. Swipe between tabs and note your gesture direction, order of tabs, and green line progression. 

Compare Reader:

https://user-images.githubusercontent.com/15107387/203799983-157bd595-5ca3-420b-bf1a-fc7f6e81cdbb.mp4

To Notifications:

https://user-images.githubusercontent.com/15107387/203801713-20d7e876-e41d-47cd-bbc6-f4e84d9a3f78.mp4

### PR DESCRIPTION
**Pull request by mkevins**
Fixes #17530

### Description

Notifications is currently using `WPViewPager` (extends `ViewPager`) which does not support RTL. This PR migrates the implementation to use `ViewPager2`, supporting RTL.

To test:

Follow [the steps in the issue](https://github.com/wordpress-mobile/WordPress-Android/issues/17530#issue-1463389504), and expect that the swipe direction for RTL locales works as expected.

## Regression Notes
1. Potential unintended areas of impact
Notifications tabs

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

3. What automated tests I added (or what prevented me from doing so)
Coverage would require e2e tests for this UI which is currently not established.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragment.kt [hunk 1]
```diff
@@ -93,25 +93,23 @@ class NotificationsListFragment : Fragment(R.layout.notifications_list_fragment)
...
-                    when (tab.position) {
-                        TAB_POSITION_ALL -> properties[NOTIFICATIONS_SELECTED_FILTER] = FILTER_ALL.toString()
-                        TAB_POSITION_COMMENT -> properties[NOTIFICATIONS_SELECTED_FILTER] = FILTER_COMMENT.toString()
-                        TAB_POSITION_FOLLOW -> properties[NOTIFICATIONS_SELECTED_FILTER] = FILTER_FOLLOW.toString()
-                        TAB_POSITION_LIKE -> properties[NOTIFICATIONS_SELECTED_FILTER] = FILTER_LIKE.toString()
-                        TAB_POSITION_UNREAD -> properties[NOTIFICATIONS_SELECTED_FILTER] = FILTER_UNREAD.toString()
-                        else -> properties[NOTIFICATIONS_SELECTED_FILTER] = FILTER_ALL.toString()
-                    }
-                    AnalyticsTracker.track(NOTIFICATION_TAPPED_SEGMENTED_CONTROL, properties)
+                    val tabPosition = TabPosition.values().getOrNull(tab.position) ?: All
```
Comment (ravishanker) [inline WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragment.kt:96]: Awesome ❤️

**Review by ravishanker — APPROVED** [review]
Nice work 👍 

I happened to do this upgrade to ViewPager2 for Stats a while ago.

**Comment by mkevins** [comment]
Thank you Ravi for reviewing and testing!
