### PR TITLE
Saving remote Post id in EditPostActivity state

### LINKED ISSUE #6808: Crash NPE: When editor activity is recreated after being killed in background
Happens with both Visual and Aztec editors.

Steps to reproduce:

1. Turn "Don't keep activities" on.
2. Open any draft or published post (new post does not cause this crash).
3. While at the editor screen press Home button to minimize the app.
4. Return to the app, notice crash.

```
FATAL EXCEPTION: main
   Process: org.wordpress.android, PID: 20465
   java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.posts.EditPostActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.wordpress.android.fluxc.model.PostModel.getPostFormat()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6077)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.wordpress.android.fluxc.model.PostModel.getPostFormat()' on a null object reference
       at org.wordpress.android.ui.posts.EditPostSettingsFragment.fetchSiteSettingsAndUpdateDefaultPostFormatIfNecessary(EditPostSettingsFragment.java:168)
       at org.wordpress.android.ui.posts.EditPostSettingsFragment.onActivityCreated(EditPostSettingsFragment.java:154)
       at android.app.Fragment.performActivityCreated(Fragment.java:2361)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1014)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
       at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2039)
       at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:176)
       at android.app.Activity.performCreateCommon(Activity.java:6658)
       at android.app.Activity.performCreate(Activity.java:6666)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
```

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #6808 

Before merging, we need to merge the FluxC branch https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/600 and update the FluxC hash here first.

To test:
These steps have worked consistently for me, and are easier for reproduction:

Using the `release/8.5` branch:
0. set developer options to `Don’t keep activities`
1. go to posts list
2. pull down to refresh
3. while its refreshing, tap on a post
4. while in the editor and once the refresh has finished (check logs or wait a few seconds), tap HOME to kill the a activity
5. go back to the app
6. observe the crash

Switch to this branch `issue/6808-use-remote-post-id-if-available` and repeat steps 1-5 above, observe the app doesn't crash anymore.

### CODE REVIEW

**Comment by mzorz** [comment]
Just added a change in df54b2a, to only save the  `remotePostId` for configuration changes if the post is not a local draft. For all other cases we should be good to rely on the post's `localId`

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java [hunk 1]
```diff
@@ -319,14 +320,19 @@ protected void onCreate(Bundle savedInstanceState) {
...
             mDroppedMediaUris = savedInstanceState.getParcelable(STATE_KEY_DROPPED_MEDIA_URIS);
             mIsNewPost = savedInstanceState.getBoolean(STATE_KEY_IS_NEW_POST, false);
 
-            if (savedInstanceState.containsKey(STATE_KEY_POST_LOCAL_ID)) {
-                initializePostObjects(savedInstanceState.getInt(STATE_KEY_POST_LOCAL_ID));
+            // if we have a remote id saved, let's first try with that, as the local Id might have changed
+            // after FETCH_POSTS
+            if (savedInstanceState.containsKey(STATE_KEY_POST_REMOTE_ID)) {
+                initializePostObjectsWithRemoteId(savedInstanceState.getLong(STATE_KEY_POST_REMOTE_ID));
+            }
```
Comment (hypest) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: Super minor but, let's have the `else` on the same line as its preceding `}` as per [the styleguide](https://source.android.com/source/code-style#use-standard-brace-style). Thanks!

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java [hunk 2]
```diff
@@ -404,18 +410,29 @@ public void run() {
...
-            mPost = UploadService.updatePostWithCurrentlyCompletedUploads(mPost);
-            mMediaMarkedUploadingOnStartIds =
-                    AztecEditorFragment.getMediaMarkedUploadingInPostContent(this, mPost.getContent());
-            Collections.sort(mMediaMarkedUploadingOnStartIds);
-            mIsPage = mPost.isPage();
+            initializePostObject();
+        }
+    }
+
+    private void initializePostObjectsWithRemoteId(long remotePostId) {
```
Comment (hypest) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: It seems we could get away with just adding a flag parameter (say, `isRemoteId`) to the original `initializePostObjects` to decide where which PostStore's method to use for loading. The separate functions seem to have only 1 line different between them.

Of course there's merit in separating into two functions to make their names more descriptive, but these methods are called by so few callers that I'm not sure it worths it. WDYT?

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java (hunk 1 above)
Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: oops sorry for that -  4bd7ecb

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java (hunk 2 above)
Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: I see your point - made changes in afe2ebc to have only the `initializePostObjects` not decide where to obtain the mPost from, but letting one-liners elsewhere to decide whether to use the remote or the local id depending on their context 👍

**Comment by aforcier** [comment]
Tested it out for myself as well, fix works :+1:. :shipit:
