### PR TITLE
NotificationHelper Refactor to make it be created upon app init.

### LINKED ISSUE #4895: Notifications are not rebuilt anymore when debugger is detached
### Expected behavior
Always handle quick actions show/hide when WPPin enabled (they should not be shown on the lock screen, and be shown again when the device is unlocked)

### Actual behavior
When debugger is detached (wondering if this might happen in other, real world situations), notifications are not being re-built anymore, so setting a  WPPin and locking/unlocking the device doesn't make any difference - notifications remain with or without quick actions, depending on the state things were when the debugger was detached.
Things start working again when a new notification is received (thus triggering the initialization of a new NotificationHelper)

### Steps to reproduce the behavior
I think this only happens to me... But managed to reproduce by setting up a debugging session then unplugging the USB cable when on a breakpoint.

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #4895 

Found a weird bug, that only happened to me when debugging (?), but there's a potential for this to happen elsewhere (*): from time to time when I’m step-by-step debugging how we build a notification,  I lose connection to the debugger, but the notification remains there in the dashboard. I can re-launch the debugger and attach to the process but for some reason some vars are not initialised: specifically a NotificationHelper would not be constructed until a new notification was received, so when you re-started the app (lose debugger then launch again),  any remaining notification would show the quick actions and would never be re-built even when you had WPPin enabled. You’d have to wait until a new notification is received, then a notification helper static object is created, and from there on it would all work as expected.

This PR fixes this potential problem (*) by making NotificationHelper be initialised right at declaration of the GCMMessageService class, thus ensuring that if we have a GCMMessageService running we also always have a NotificationsHelper that can deal with anything notification-related (not only processing a received message but also re-building existing notifications when locking/unlocking the screen, etc).

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/push/GCMMessageService.java [hunk 1]
```diff
@@ -59,7 +59,7 @@
 
 public class GCMMessageService extends GcmListenerService {
     private static final ArrayMap<Integer, Bundle> sActiveNotificationsMap = new ArrayMap<>();
-    private static NotificationHelper sNotificationHelpers;
+    private static NotificationHelper sNotificationHelpers = new NotificationHelper();
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/push/GCMMessageService.java]: This can be `final`, and we can drop any null checks for `sNotificationHelpers` in this class.

Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/push/GCMMessageService.java]: thank you @nbradbury ! addressed here b57a32f

**Comment by nbradbury** [comment]
@mzorz Looks good, but it now has conflicts due to that previous notifications PR that I just merged. Once the conflicts are resolved I'll merge this one.

**Comment by mzorz** [comment]
Re: #4892, I need to apologize and go back on my own steps - my tests were done with `timestampFromIso8601` instead of `timestampFromIso8601Millis`, that’s why I was getting a bad date format.
Did test again with the correct method in `DateTimeUtils` and it works. So now getting this reflected in code in c2ebc47 @nbradbury. 
I realised this while re-testing it after solving merge conflicts. Sorry! Can you check it once more please? thanks in advance 🙇

**Comment by nbradbury** [comment]
Looks great! :shipit:

**Comment by mzorz** [comment]
Thank you very much @nbradbury ! Thanks for suggesting the change in the first place as well - I'll look closer next time 🙇 tyty
