### PR TITLE
Issue/5786 runtime ex

### LINKED ISSUE #5786: Crash report 7.2: java.lang.RuntimeException: PARAGRAPH span must end at paragraph boundary
```
Fatal Exception: java.lang.RuntimeException: PARAGRAPH span must end at paragraph boundary
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:693)
       at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:102)
       at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:50)
       at org.wordpress.android.ui.posts.EditPostActivity.updatePostContent(EditPostActivity.java:1610)
       at org.wordpress.android.ui.posts.EditPostActivity.updatePostObject(EditPostActivity.java:1031)
       at org.wordpress.android.ui.posts.EditPostActivity.access$900(EditPostActivity.java:148)
       at org.wordpress.android.ui.posts.EditPostActivity$3$1.run(EditPostActivity.java:418)
       at java.lang.Thread.run(Thread.java:761)
```

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #5786

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java [hunk 1]
```diff
@@ -1612,6 +1612,9 @@ public void updatePostContent(boolean isAutoSave) throws IllegalEditorStateExcep
                 // A core android bug might cause an out of bounds exception, if so we'll just use the current editable
                 // See https://code.google.com/p/android/issues/detail?id=5164
                 postContent = new SpannableStringBuilder(StringUtils.notNullStr((String) mEditorFragment.getContent()));
+            } catch (RuntimeException e) {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: The catch for `IndexOutOfBoundsException` is now redundant, since that is a `RuntimeException`.

Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: thank you! addressed in 999d5d4

**Comment by nbradbury** [comment]
:shipit:
