### PR TITLE
Fix issues related to the Like state in notifications tab

### LINKED ISSUE #20211: 🤖 Changes in the like status are not reflected in the list
Changes in the like status from the detail screen are not reflected in the list view till you refresh

https://github.com/wordpress-mobile/WordPress-Android/assets/304044/806ed1f4-ac3f-4c6e-bb22-13525f72afb3

### PR DESCRIPTION
**Pull request by jarvislin**
Fixes #20211, #20210
And https://github.com/wordpress-mobile/WordPress-Android/pull/20223#pullrequestreview-1894675368

-----

The original implementation didn't sync the Like state in every tab. This PR contains:
1. Sync the Like state by using events.
2. Correct the lifecycle of fetching remote data

## To Test:
#20211

1. Sign in the JP app and switch to the notification tab.
2. Click the notification item
3. Click Like in the detail view
4. Back to the notification tab.
5. The Like state should be correct.

#20210
1. Click the system notification.
2. Click the Back button
3. It should display the notification tab correctly

Known issue:
The like state cannot sync correctly when we click Like and switch tab quickly. 
I don't have a solid solution at the moment. It requires a huge refactor for our local database.

-----

## Regression Notes

1. Potential unintended areas of impact

    - Notifications tab

7. What I did to test those areas of impact (or what existing automated tests I relied on)

    - Manuel

8. What automated tests I added (or what prevented me from doing so)

    - Update some unit tests in the NotificationListViewModel

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist:

- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          10 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>EnabledActions</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>NoteTimeGroup</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>Notification</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>PostNotification</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>Like</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>NoteType</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>LinearLayoutManagerWrapper</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>InlineActionEvent</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>SharePostButtonTapped</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>Filter</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><code>strings.xml</code> files should only be updated on release branches, when the translations are downloaded by our automation.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WordPress/src/main/java/org/wordpress/android/ui/notifications/adapters/NotesAdapter.kt [hunk 1]
```diff
@@ -46,13 +47,20 @@ class NotesAdapter(context: Context, private val inlineActionEvents: MutableShar
...
+                filteredNotes[oldItemPosition].id == newNotes[newItemPosition].id
+
+            override fun areContentsTheSame(oldItemPosition: Int, newItemPosition: Int): Boolean =
+                filteredNotes[oldItemPosition].json.toString() == newNotes[newItemPosition].json.toString()
+        })
         filteredNotes.clear()
         filteredNotes.addAll(newNotes)
         withContext(Dispatchers.Main) {
-            notifyItemRangeRemoved(0, currentSize)
-            notifyItemRangeInserted(0, newNotes.size)
```
Comment (jarvislin) [inline WordPress/src/main/java/org/wordpress/android/ui/notifications/adapters/NotesAdapter.kt:55]: Replace these lines with DiffUtil because it causes the list blinking when we refresh the list

File: WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationEvents.java [hunk 2]
```diff
@@ -62,4 +62,14 @@ public NotificationsRefreshError(VolleyError error) {
 
         public NotificationsRefreshError() {}
     }
+
+    public static class OnNoteCommentLikeChanged {
+        public final Note note;
```
Comment (mkevins) [inline WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationEvents.java:69]: NP: missing null annotation

**Review by antonis — APPROVED** [review]
Awesome work @jarvislin ⭐ 
I verified that all three issues Fixes https://github.com/wordpress-mobile/WordPress-Android/issues/20211, https://github.com/wordpress-mobile/WordPress-Android/issues/20210, https://github.com/wordpress-mobile/WordPress-Android/pull/20223#pullrequestreview-1894675368 are fixed by testing on a Pixel 5 (Android 14). The code changes also look good 🎉 

ps. I noticed a minor UI issue https://github.com/wordpress-mobile/WordPress-Android/issues/20248 but I think it can be handled on a separate PR with low priority.
