### PR TITLE
Fix #2949 - Verify comment exists before accessing it

### LINKED ISSUE #2949: Crash report 4.2 - NPE CommentDetailFragment
Need to make sure [mComment](https://github.com/wordpress-mobile/WordPress-Android/blob/4.2/WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailFragment.java#L269) isn't null.

```
java.lang.NullPointerException
       at org.wordpress.android.ui.comments.CommentDetailFragment$3.onClick(CommentDetailFragment.java:269)
       at android.view.View.performClick(View.java:4654)
       at android.view.View$PerformClick.run(View.java:19438)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5487)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

### PR DESCRIPTION
**Pull request by tonyr59h**
Addresses #2949

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailFragment.java [hunk 1]
```diff
@@ -259,6 +259,8 @@ public boolean onEditorAction(TextView v, int actionId, KeyEvent event) {
         mImgSubmitReply.setOnClickListener(new View.OnClickListener() {
             @Override
             public void onClick(View v) {
+                if (!hasComment()) return;
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailFragment.java]: The `hasComment()` check probably belongs in `submitReply()` rather than here.

**Comment by nbradbury** [comment]
:shipit:
