### PR TITLE
Issue/6279 post list missing featured image

### LINKED ISSUE #6279: Media: featured image is sometimes not shown in Posts list
Sometimes the Featured image is not shown on posts after having created a post with one or more images, waiting for everything to upload, and then coming back to the Posts list, when using the Visual Editor in particular. Couldn’t figure out a way to reproduce consistently / check if it happens with Aztec as well.

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #6279 - the problem was due to choosing a featured image from the post content when the image is still uploading. This resulted in choosing a local file (ex: `/storage/emulated/0/Download/IMG_q5m29m.jpg`) as a featured image, and the post adapter didn't support displaying device images.

This PR corrects this by supporting device images, and also fixes a few problems in the existing featured image code.

**Note:** As part of this PR, I added [this routine](https://github.com/wordpress-mobile/WordPress-Android/blob/d5d7ae968dc260d6421bf42a45f25ba8c8dd0f55/WordPress/src/main/java/org/wordpress/android/ui/posts/adapters/PostsListAdapter.java#L328) to load resized bitmaps more efficiently than similar routines in [ImageUtils](https://github.com/wordpress-mobile/WordPress-Utils-Android/blob/develop/WordPressUtils/src/main/java/org/wordpress/android/util/ImageUtils.java#L598). At some point we'll want to move that routine to `ImageUtils`, but for now I'd like to keep it inside `PostListAdapter`.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/adapters/PostsListAdapter.java [hunk 1]
```diff
@@ -309,6 +305,46 @@ public void onClick(View v) {
...
+    private void showFeaturedImage(int postId, WPNetworkImageView imgFeatured) {
+        String imageUrl = mFeaturedImageUrls.get(postId);
+        if (imageUrl == null) {
+            imgFeatured.setVisibility(View.GONE);
+        } else if (imageUrl.startsWith("http")) {
+            String photonUrl =  ReaderUtils.getResizedImageUrl(imageUrl, mPhotonWidth, mPhotonHeight, mSite.isPrivate());
+            imgFeatured.setVisibility(View.VISIBLE);
+            imgFeatured.setImageUrl(photonUrl, WPNetworkImageView.ImageType.PHOTO);
+        } else {
+            Bitmap bmp = fastResizeBitmap(imageUrl, mPhotonWidth);
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/adapters/PostsListAdapter.java]: Any reason to not use `Bitmap bmp = ImageUtils.getWPImageSpanThumbnailFromFilePath(context, imageUrl, mPhotonWidth);`  that is well tested and used in the app?

The actual implementation doesn't take in consideration orientation of the pictures, resulting in pictures turned 90° on some devices, and doesn't show the "poster" picture for videos.

File: WordPress/src/main/java/org/wordpress/android/ui/posts/adapters/PostsListAdapter.java [hunk 2]
```diff
@@ -309,6 +305,46 @@ public void onClick(View v) {
         });
     }
 
+    private void showFeaturedImage(int postId, WPNetworkImageView imgFeatured) {
+        String imageUrl = mFeaturedImageUrls.get(postId);
+        if (imageUrl == null) {
+            imgFeatured.setVisibility(View.GONE);
+        } else if (imageUrl.startsWith("http")) {
+            String photonUrl =  ReaderUtils.getResizedImageUrl(imageUrl, mPhotonWidth, mPhotonHeight, mSite.isPrivate());
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/adapters/PostsListAdapter.java]: Instead of `mSite.isPrivate()` should we use `SiteUtils.isPhotonCapable(mSite)`?
Otherwise self hosted sites can get redirected to Photon.

**Comment by nbradbury** [comment]
@daniloercoli You're right, I should've stuck with the existing image resize. My concern was that since the resizing occurs on the main thread I wanted it to be as fast as possible, and our existing code could be faster. But that's something we should address separately rather than in this PR.

I've updated this PR in 6541dd6 to use the existing method and also switched to using `isPhotonCapable`, as you suggested.

File: WordPress/src/main/java/org/wordpress/android/ui/posts/adapters/PostsListAdapter.java [hunk 3]
```diff
@@ -729,34 +751,23 @@ protected Boolean doInBackground(Void... nada) {
...
+                        // If the media isn't found it means the featured image info hasn't been added to
+                        // the local media library yet, so add to the list of media IDs to request info for
                         mediaIdsToUpdate.add(post.getFeaturedImageId());
                     }
-                } else if (StringUtils.isNotEmpty(post.getContent())) {
-                    ReaderImageScanner scanner = new ReaderImageScanner(post.getContent(), mSite.isPrivate());
-                    imageUrl = scanner.getLargestImage();
                 } else {
-                    imageUrl = null;
+                    imageUrl = new ReaderImageScanner(post.getContent(), mSite.isPrivate()).getLargestImage();
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/adapters/PostsListAdapter.java]: Sorry, I missed this in the first pass. Should we use `SiteUtils.isPhotonCapable(mSite)` here?

Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/adapters/PostsListAdapter.java]: Fixed in 50f8a8c

**Comment by daniloercoli** [comment]
:shipit:
