### PR TITLE
Handling deleting uploading media in Aztec - take nbr 2

### LINKED ISSUE #6456: Async media: upload not cancelled when media deleted in Aztec
### Expected behavior
When you're uploading a media item (video or image) in the Editor, and you delete it, the upload should be cancelled.

### Actual behavior
The upload continues and there's no way for you to cancel it.

### Steps to reproduce the behavior
1. start a new draft on Aztec
2. insert media item
3. delete the item
4. observe the "uploading media" notification is still going on, and if you exit the editor the posts list will show the progress bar as well

### PR DESCRIPTION
**Pull request by mzorz**
Superseedes #6513 
This PR is better than #6513 in that it approaches triggering and actions in the same way as `onMediaUploadCancelClicked` by having [both call `cancelMediaUpload`](https://github.com/wordpress-mobile/WordPress-Android/blob/issue/6456-upload-cancel-on-media-deleted-aztec-take-2/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L2317-L2333) 

Thanks @aforcier for bringing my attention to this - tested both the old and the new branch and they behave pretty much the same, while this solution is much simpler and adds less code (and less likely to introduce new bugs)

All the relevant comments from the former PR have bee taken into account and/or cherry-picked in this PR as well @nbradbury 

=========================
Fixes #6456 

This PR takes care of 2 situations:
- when a user deletes one or more media items within Aztec, [now Aztec triggers an event](https://github.com/wordpress-mobile/AztecEditor-Android/pull/461) through the `OnMediaDeletedListener` interface that is being listened to by `AztecEditorFragment` within WPAndroid. This in turn calls the host of such fragment, `EditPostActivity`, which takes care of notifying the `UploadService` of such a thing, which in turn takes care of cancelling the upload as it's not needed anymore.

- this comes with one other situation that can come up from this, and it's the user can go back and `undo` this on Aztec, so you end up having the same media item again, but now the upload for such an item has been stopped (and wiped out from the UploadService altogether). The `EditorFragmentListener` now has a new method, `onUndoMediaCheck()`, where the implementation checks for those media items that are in the new Post content (_undoed_ content) marked with the `UPLOADING` class attribute but are not there in the `UploadService`. These are marked as `FAILED` so they can be retried by the user.

To test:
1. start a new draft
2. insert a media item - preferrably something big so you're able to test an in-progress upload cancelation.
3. while the media item is being uploaded, place the cursor to its right (or after it), and hit backspace to delete it
4. observe the upload is stopped
5. tap on the UNDO button
6. observe the media item appears again, now with the "failed"  overlay
7. Tap on it to start the upload again, as normal

Test this also with variants such as: exiting the editor in the middle of an upload (so the upoading notification is triggered) and coming back in again, or inserting several media items mixed with text, selecting them all and deleting it, check how the Posts list behaves, etc.
Maybe even test we haven't broken anything in the Visual Editor as well (as this should only work with Aztec)

cc @nbradbury

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java [hunk 1]
```diff
@@ -2328,6 +2325,53 @@ public void onMediaUploadCancelClicked(String localMediaId) {
...
+        List <MediaModel> currentlyUploadingMedia = UploadService.getAllInProgressOrQueuedMediaItemsForPost(mPost);
+        List<String> mediaMarkedUploading  =
+                AztecEditorFragment.getMediaMarkedUploadingInPostContent(EditPostActivity.this, undoedContent);
+
+        // go through the list of items marked UPLOADING within the Post content, and look in the UploadService
+        // to see whether they're really being uploaded or not. If an item is not really being uploaded, mark that item failed
+        for (String mediaId : mediaMarkedUploading) {
+            boolean found = false;
+            for (MediaModel media : currentlyUploadingMedia) {
+                if (Integer.valueOf(mediaId) == media.getId()) {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: Let's use `StringUtils.stringToInt` here.

Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: addressed in d60ebd2

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java [hunk 2]
```diff
@@ -2328,6 +2325,53 @@ public void onMediaUploadCancelClicked(String localMediaId) {
...
+            boolean found = false;
+            for (MediaModel media : currentlyUploadingMedia) {
+                if (StringUtils.stringToInt(mediaId) == media.getId()) {
+                    found = true;
+                    break;
+                }
+            }
+
+            if (!found) {
+                // 2- Run through loop and set each media to failed
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: This comment seems confusing, perhaps it was written for an earlier version of this code?

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java [hunk 3]
```diff
@@ -403,6 +403,10 @@ public static boolean hasMediaErrorForPost(PostModel post) {
         return error != null && error.mediaError != null;
     }
 
+    public static List<MediaModel> getAllInProgressOrQueuedMediaItemsForPost(PostModel post){
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java]: This method could be renamed to better match `MediaUploadHandler.getPendingOrInProgressMediaUploadsForPost()`. It's a bit confusing to refer to the media as "in progress or queued" in one place and "pending or in progress" in another.

File: libs/editor/WordPressEditor/build.gradle [hunk 4]
```diff
@@ -51,8 +51,10 @@ dependencies {
     compile 'com.android.support:design:25.3.1'
     compile 'org.apache.commons:commons-lang3:3.5'
     compile 'org.wordpress:utils:1.16.0'
-    compile ('com.github.wordpress-mobile.WordPress-Aztec-Android:aztec:ce388e4c55e345bb10156329486edd378eb223bb')
-    compile ('com.github.wordpress-mobile.WordPress-Aztec-Android:wordpress-comments:ce388e4c55e345bb10156329486edd378eb223bb')
+//    compile ('com.github.wordpress-mobile.WordPress-Aztec-Android:aztec:ce388e4c55e345bb10156329486edd378eb223bb')
```
Comment (nbradbury) [inline libs/editor/WordPressEditor/build.gradle]: Should these commented lines be removed?

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java [hunk 5]
```diff
@@ -2328,6 +2325,53 @@ public void onMediaUploadCancelClicked(String localMediaId) {
...
+    private void cancelMediaUpload(int localMediaId, boolean delete) {
+        MediaModel mediaModel = mMediaStore.getMediaWithLocalId(Integer.valueOf(localMediaId));
+        if (mediaModel != null) {
+            CancelMediaPayload payload = new CancelMediaPayload(mSite, mediaModel, delete);
+            mDispatcher.dispatch(MediaActionBuilder.newCancelMediaUploadAction(payload));
+        }
+    }
+
+    @Override
+    public void onUndoMediaCheck(final String undoedContent) {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: What do you think about simplifying this by making Aztec do the work? It seems out of place to have WPAndroid scan the undone content for media. My thought is that `AztecEditorFragment` could have a `onMediaUndeleted()` event which works the same as `onMediaDeleted()` - it simply passes the ID of the deleted media.

Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: I get your point, but the thing is Aztec doesn't know how to make diffs, it just saves the whole string each time an action is triggered, replacing the editor's content with what was there before / after. The diff in this PR is done by inferring that in an older content (`undoedContent`) all we need to be interested in are the media items marked with the `UPLOAD` class, and that is not known to Aztec itself but rather something that belongs to AztecEditorFragmnet / WPAndroid app.
I think it would make things a bit more complicated if we gave Aztec this kind of capability to interpret its content any further than this.

File: libs/editor/WordPressEditor/build.gradle (hunk 4 above)
Comment (mzorz) [inline libs/editor/WordPressEditor/build.gradle]: oops - sorry for that, addressed in 01e7f31

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java (hunk 2 above)
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: oops good catch addressed in 4703a4d

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java (hunk 3 above)
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java]: good call - renamed in af6c7e7

**Comment by nbradbury** [comment]
Looks good, nice work! :shipit:
