### PR TITLE
Date formatting crash

### LINKED ISSUE #8886: Crash in StatsDateFormatter.kt: Unparseable date: ""
This was introduced in 11.5-rc-1 and has already been reported in Fabric >500 times.

I don't have clear steps but it seems to be caused by `StatsDateFormatter.kt` attempting to parse an empty date: `Unparseable date: ""`

Here is the stacktrace:

```
Fatal Exception: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

Caused by java.text.ParseException: Unparseable date: ""
       at java.text.DateFormat.parse(DateFormat.java:358)
       at org.wordpress.android.ui.stats.refresh.utils.StatsDateFormatter.parseStatsDate(StatsDateFormatter.kt:117)
       at org.wordpress.android.ui.stats.refresh.lists.sections.granular.usecases.OverviewUseCase.buildStatefulUiModel(OverviewUseCase.kt:81)
       at org.wordpress.android.ui.stats.refresh.lists.sections.granular.usecases.OverviewUseCase.buildStatefulUiModel(OverviewUseCase.kt:25)
       at org.wordpress.android.ui.stats.refresh.lists.sections.BaseStatsUseCase$StatefulUseCase.buildUiModel(BaseStatsUseCase.kt:165)
       at org.wordpress.android.ui.stats.refresh.lists.sections.BaseStatsUseCase$liveData$1.invoke(BaseStatsUseCase.kt:33)
       at org.wordpress.android.ui.stats.refresh.lists.sections.BaseStatsUseCase$liveData$1.invoke(BaseStatsUseCase.kt:22)
       at org.wordpress.android.util.LiveDataUtilsKt$merge$3.invoke(LiveDataUtils.kt:76)
       at org.wordpress.android.util.LiveDataUtilsKt$merge$3.invoke(LiveDataUtils.kt)
       at org.wordpress.android.util.LiveDataUtilsKt$map$1.apply(LiveDataUtils.kt:132)
       at android.arch.lifecycle.Transformations$1.onChanged(Transformations.java:70)
       at android.arch.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:152)
       at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
       at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:126)
       at android.arch.lifecycle.LiveData.setValue(LiveData.java:282)
       at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
       at org.wordpress.android.util.LiveDataUtilsKt$merge$1.onChanged(LiveDataUtils.kt:71)
       at android.arch.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:152)
       at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
       at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:121)
       at android.arch.lifecycle.LiveData.access$400(LiveData.java:59)
       at android.arch.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:416)
       at android.arch.lifecycle.LiveData.observeForever(LiveData.java:207)
       at android.arch.lifecycle.MediatorLiveData$Source.plug(MediatorLiveData.java:141)
       at android.arch.lifecycle.MediatorLiveData.onActive(MediatorLiveData.java:118)
       at android.arch.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:410)
       at android.arch.lifecycle.LiveData.observeForever(LiveData.java:207)
       at android.arch.lifecycle.MediatorLiveData$Source.plug(MediatorLiveData.java:141)
       at android.arch.lifecycle.MediatorLiveData.onActive(MediatorLiveData.java:118)
       at android.arch.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:410)
       at android.arch.lifecycle.LiveData.observeForever(LiveData.java:207)
       at android.arch.lifecycle.MediatorLiveData$Source.plug(MediatorLiveData.java:141)
       at android.arch.lifecycle.MediatorLiveData.onActive(MediatorLiveData.java:118)
       at android.arch.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:410)
       at android.arch.lifecycle.LiveData.observeForever(LiveData.java:207)
       at android.arch.lifecycle.MediatorLiveData$Source.plug(MediatorLiveData.java:141)
       at android.arch.lifecycle.MediatorLiveData.onActive(MediatorLiveData.java:118)
       at android.arch.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:410)
       at android.arch.lifecycle.LiveData.observeForever(LiveData.java:207)
       at android.arch.lifecycle.MediatorLiveData$Source.plug(MediatorLiveData.java:141)
       at android.arch.lifecycle.MediatorLiveData.onActive(MediatorLiveData.java:118)
       at android.arch.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:410)
       at android.arch.lifecycle.LiveData.observeForever(LiveData.java:207)
       at android.arch.lifecycle.MediatorLiveData$Source.plug(MediatorLiveData.java:141)
       at android.arch.lifecycle.MediatorLiveData.onActive(MediatorLiveData.java:118)
       at android.arch.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:410)
       at android.arch.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:368)
       at android.arch.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
       at android.arch.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:292)
       at android.arch.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:332)
       at android.arch.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:137)
       at android.arch.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:123)
       at android.support.v4.app.Fragment.performStart(Fragment.java:2380)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1467)
       at android.support.v4.app.FragmentManagerImpl.performPendingDeferredStart(FragmentManager.java:1232)
       at android.support.v4.app.FragmentManagerImpl.startPendingDeferredFragments(FragmentManager.java:1855)
       at android.support.v4.app.FragmentManagerImpl.doPendingDeferredStart(FragmentManager.java:2697)
       at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2221)
       at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
       at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
       at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:663)
       at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:625)
       at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:606)
       at android.support.design.widget.TabLayout$ViewPagerOnTabSelectedListener.onTabSelected(TabLayout.java:2170)
       at android.support.design.widget.TabLayout.dispatchTabSelected(TabLayout.java:1165)
       at android.support.design.widget.TabLayout.selectTab(TabLayout.java:1158)
       at android.support.design.widget.TabLayout.selectTab(TabLayout.java:1128)
       at android.support.design.widget.TabLayout$Tab.select(TabLayout.java:1427)
       at android.support.design.widget.TabLayout$TabView.performClick(TabLayout.java:1537)
       at android.view.View$PerformClick.run(View.java:22693)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6269)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

Reference: 5c230708f8b88c296335ea8a-fabric

cc @jkmassel

### PR DESCRIPTION
**Pull request by 0nko**
Fixes #8886.

This bug is caused by an inconsistent API behavior that is hard to reproduce (random empty parameter response). This PR references a FluxC build that treats empty data as an error and makes sure the empty data is never parsed.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewUseCase.kt [hunk 1]
```diff
@@ -75,33 +77,38 @@ constructor(
...
+                            statsGranularity,
+                            this::onBarSelected,
+                            uiState.selectedPosition,
+                            selectedDate
+                    )
+            )
+            items.add(overviewMapper.buildColumns(selectedItem, this::onColumnSelected, uiState.selectedPosition))
+        }
+        else {
+            AppLog.e(T.STATS, "There is no data to be shown in the overview block")
```
Comment (planarvoid) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewUseCase.kt]: I know this shouldn't happen anymore (because FluxC will emit an error and we'll never get invalid data) but I think we should be showing some kind of Error block in this case (or crash). If we don't, the whole page will miss the overview block and the other blocks will be loading indefinitely (because there is no selected date). We can also extend the selected date provider to emit something like "Invalid date" which would stop loading of the other blocks but I think that's totally out of scope for this PR.

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/viewholders/ErrorViewHolder.kt [hunk 2]
```diff
@@ -3,13 +3,19 @@ package org.wordpress.android.ui.stats.refresh.lists.viewholders
...
-import org.wordpress.android.R.layout
 import org.wordpress.android.ui.stats.refresh.lists.Error
 
-class ErrorViewHolder(parent: ViewGroup) : BaseStatsViewHolder<Error>(parent, layout.stats_error_view) {
+class ErrorViewHolder(val parent: ViewGroup) : BaseStatsViewHolder<Error>(parent, R.layout.stats_error_view) {
     private val title: TextView = itemView.findViewById(R.id.error_message)
     override fun bind(item: Error) {
         super.bind(item)
-        title.text = item.errorMessage
+        if (item.errorMessage.isNotBlank()) {
```
Comment (planarvoid) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/viewholders/ErrorViewHolder.kt]: Good change. Out of scope: I think this error view holder still needs some polishing (maybe we should add a refresh button to the block 🤷‍♂️ ).

**Review by planarvoid — APPROVED** [review]
Consider my suggestions (but I'm fine with merging this PR as it is)

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/viewholders/ErrorViewHolder.kt (hunk 2 above)
Comment (0nko) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/viewholders/ErrorViewHolder.kt]: I agree. This is just a minimum that should be there so that we don't show empty cards (when a device is offline, for example). We should overhaul the error management in a separate task/PR that will also detect offline mode and displays a single error message.

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewUseCase.kt (hunk 1 above)
Comment (0nko) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewUseCase.kt]: Good idea. Let's tackle this separately.
