### PR TITLE
Fix NPE uploading local media

### LINKED ISSUE #8210: NPE while uploading media
User reports a crash while media are uploading. The log looks like that reported in #6866, except in that situation the problem was caused by uploading from a third party source. In this situation, the user is uploading directly from the device.

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int org.wordpress.android.fluxc.model.MediaModel.getId()' on a null object reference
       at org.wordpress.android.fluxc.store.UploadStore.handleUpdateMedia(UploadStore.java:337)
       at org.wordpress.android.fluxc.store.UploadStore.onMediaAction(UploadStore.java:131)
       at org.wordpress.android.fluxc.store.UploadStore.onAction(UploadStore.java:98)
       at java.lang.reflect.Method.invoke(Method.java)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
       at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

5a07c4e861b02d480d3e5876-fabric
1338678-zendesk

### PR DESCRIPTION
**Pull request by daniloercoli**
Fixes #8210 by adding a check to `PhotoPickerActivity` that does ensure `MediaModel` is not null before dispatching a new `newUpdateMediaAction` action.

The NPE happens internal to FluxC, but is wp-android that does trigger an event with a null payload. I will probably add some more checks to FluxC to avoid the crashing in a separate PR.

This PR also adds few other checks to be sure MediaModel returned by `FluxcUtils` is not null (EX: when the file is not readable for some reason).

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java [hunk 1]
```diff
@@ -661,6 +661,10 @@ private void startSiteIconUpload(final String filePath) {
         SiteModel site = getSelectedSite();
         if (site != null) {
             MediaModel media = buildMediaModel(file, site);
+            if (media == null) {
+                ToastUtils.showToast(getActivity(), R.string.file_not_found, ToastUtils.Duration.SHORT);
+                return;
```
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java]: I think we didn't catch the exception / close the code flow before because we were hoping to find more information in the crash report. What do you think about also adding some logging we can report back to Crashlytics so we can understand why this situation happens?

Comment (daniloercoli) [reply WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java]: This could happen when `FluxCUtils.mediaModelFromLocalUri` returns `null`.
(Actually  we're not seeing problems in `MySiteFragment`, and added the code to be safe).

It return null when `String path = MediaUtils.getRealPathFromURI(context, uri);`  cannot complete for some reasons. I can add a log there, but don't think it would be of any help.

Comment (daniloercoli) [reply WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java]: The real fix of this NPE is done in f539301f797df318d537f5ddafc3ce6b53618267.
Since the code that builds the media model in `PhotoPickerActivity` expects the file to be accessible/there, but for some reason it is not, and then it dispatches an action with empty payload.

Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java]: > The real fix of this NPE is done in f539301.

Sure, I only commented on this other file/line but meant to make a general comment for every place where this PR shows a toast and end the flow. 👍

Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java]: > It returns null when `String path = MediaUtils.getRealPathFromURI(context, uri);` cannot complete for some reasons. I can add a log there, but don't think it would be of any help.

My fear here is that if they can't open a file once, they probably won't be able to ever open such a file  (that is, they will keep getting the toast each time they try). That will be silent for us, and we won't be able to help them as we don't know something happened. What if we add some sort of tracking?  Maybe not logging, but using tracks so we know if something grows? (I just wouldn't want it to go unnoticed for long time and hit the app ratings if anything happens and we can't see it) wdyt?

Comment (daniloercoli) [reply WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java]: Yeah, good call. Added the logging in 5c6255b
