### PR TITLE
Attempt to use featured media if featured image is not set

### LINKED ISSUE #7404: Reader: missing image in stream when image has no WP class name attributes
### Expected behavior
I'd expect to see images in the Reader stream, especially for photo blogs.

### Actual behavior
Missing the image.

Here's the source code for this particular blog post.

```
<div>

<img style="max-width: 600px;" src="https://b19y.files.wordpress.com/2017/12/977d8-25017105_138648596841514_72137175486955520_n.jpg" />
<div>Lap dog
#goldendoodle</div>
</div>
```

Note it's missing the WP class names. Ben L posted it "via the ifttt applet".

### Steps to reproduce the behavior
Web, front-end: https://b19y.blog/2017/12/23/2483/

screen shot 2017-12-29 at 11 35 41

WP.com Reader (Calypso web): https://wordpress.com/read/feeds/58928981

screen shot 2017-12-29 at 11 35 33

WP Android app version 9.5

screenshot_1520358757

### PR DESCRIPTION
**Pull request by 0nko**
Fixes #7404.

Before:

After:
screenshot_1520364541

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/models/ReaderPost.java [hunk 1]
```diff
@@ -172,11 +172,20 @@ public static ReaderPost fromJson(JSONObject json) {
...
-        // we can find a suitable image from the content
-        if (!post.hasFeaturedImage() && post.hasImages()) {
-            post.mFeaturedImage = new ReaderImageScanner(post.mText, post.isPrivate)
-                    .getLargestImage(ReaderConstants.MIN_FEATURED_IMAGE_WIDTH);
+        if (!post.hasFeaturedImage()) {
+            // if there's no featured image, check if featured media has been set to an image
+            if (json.has("featured_media")) {
+                JSONObject jsonMedia = json.optJSONObject("featured_media");
+                String type = JSONUtils.getString(jsonMedia, "type");
+                if (type.equals("image")) {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/models/ReaderPost.java]: If `type` is not an image then the image scan won't run and no featured image will be assigned. How about this instead:

```
// if there's no featured image, check if featured media has been set to an image
if (!post.hasFeaturedImage() && json.has("featured_media")) {
    JSONObject jsonMedia = json.optJSONObject("featured_media");
    String type = JSONUtils.getString(jsonMedia, "type");
    if (type.equals("image")) {
        post.mFeaturedImage = JSONUtils.getString(jsonMedia, "uri");
    }
}
// if the post doesn't have a featured media but it contains an IMG tag, check whether
// we can find a suitable image from the content
if (!post.hasFeaturedImage() && post.hasImages()) {
        post.mFeaturedImage = new ReaderImageScanner(post.mText, post.isPrivate)
                .getLargestImage(ReaderConstants.MIN_FEATURED_IMAGE_WIDTH);
}
```

Comment (0nko) [reply WordPress/src/main/java/org/wordpress/android/models/ReaderPost.java]: Makes sense, thanks.

**Comment by nbradbury** [comment]
Looks good! :shipit:
