### PR TITLE
Navigate not logged in user to launch screen from Notification Settings

### LINKED ISSUE #16070: Notification settings screen misbehave for not logged in user
### Expected behavior
If not logged in user taps "Additional settings in the app" button from "App info" menu, the Notification Settings screen shouldn't open. Because that screen is related to the account.

### Actual behavior

- **Logged out user**: If the user logs out and opens notification settings from App info menu, the last user's site information and notification settings are shown.

https://user-images.githubusercontent.com/2471769/157758498-a9210149-5d68-4829-9eb0-2a818065c7fd.mp4

- **Fresh install:** If a new user opens notification settings from App info menu, the notification settings screen opens with a loading indicator never ends.

https://user-images.githubusercontent.com/2471769/157474373-d80bd7e9-89a5-4e8d-ae09-fd14246611fd.mp4

### Steps to reproduce the behavior
**Logged out user**
1. Log in to the app.
2. Log out from the app.
3. Close the app or send it to the background.
4. Hold WordPress app icon from the app list. Tap i (info) button. Tap "Notifications". Tap "Additional Settings in the app." _(This navigation and button names can be different depending on your device.)_
5. Notification Settings screen will open but the last user's data will be shown.

**Fresh install**
1. Do a fresh install or clear storage of WordPress app from the App info > Storage & cache.
2. Hold WordPress app icon from the app list. Tap i (info) button. Tap "Notifications". Tap "Additional Settings in the app." _(This navigation and button names can be different depending on your device.)_
3. Notification Settings screen will open and you'll see a loading indicator never ends.

##### Tested on Emulator Pixel 4 API 32, Android 12, WPAndroid alpha-347

### PR DESCRIPTION
**Pull request by irfano**
Fixes #16070 

Not logged-in users can open the notification settings screen from App info menu without starting the WordPress app. But this Notification Settings screen is related to the user account, so the screen shouldn't be shown to not logged in user.
This PR navigates not logged-in users from Notification Settings to the launch screen.

Extra neatness could be keeping the user's intent after logging in and navigating them to Notification Settings screen. But it could cause extra problems for some cases. Some other applications (I checked Instagram) are just navigating users to the launch screen as I did in this PR.

**Before:**

https://user-images.githubusercontent.com/2471769/157774046-71634fc3-45be-4fb1-bc35-4e1da31c5dbb.mp4

**After:**

https://user-images.githubusercontent.com/2471769/157774185-d452cfd7-6e99-4d1a-902d-3e0a9e0108ca.mp4

To test:
**Logged out user case**
- Log in to the app.
- Log out from the app.
- Close the app or send it to the background.
- Hold WordPress app icon from the app list. Tap i (info) button. Tap "Notifications". Tap "Additional Settings in the app." (This navigation and button names can be different depending on your device.)
- Launch screen should open.

**Fresh install case**
- Do a fresh install or clear storage of WordPress app from the App info > Storage & cache.
- Hold WordPress app icon from the app list. Tap i (info) button. Tap "Notifications". Tap "Additional Settings in the app." (This navigation and button names can be different depending on your device.)
- Launch screen should open.

## Regression Notes
1. Potential unintended areas of impact
Notification Settings screen should work correctly for all kinds of accounts.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Tested manually for different cases explained in testing instructions.

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/prefs/notifications/NotificationsSettingsFragment.java [hunk 1]
```diff
@@ -184,6 +185,17 @@ private void removeFollowedBlogsPreferenceForIfDisabled() {
...
 
+        boolean isLoggedIn = mAccountStore.hasAccessToken();
+        if (!isLoggedIn) {
+            // Not logged in users can start Notification Settings from App info > Notifications menu.
+            // If there isn't a logged in user, just show the entry screen.
+            Intent intent = new Intent(getContext(), WPLaunchActivity.class);
+            intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK | Intent.FLAG_ACTIVITY_NEW_TASK);
+            startActivity(intent);
+            getActivity().finish();
+            return;
```
Comment (ravishanker) [inline WordPress/src/main/java/org/wordpress/android/ui/prefs/notifications/NotificationsSettingsFragment.java:196]: What does this **return** do here!

Comment (irfano) [reply WordPress/src/main/java/org/wordpress/android/ui/prefs/notifications/NotificationsSettingsFragment.java:196]: I don't want to continue after closing the screen with `finish()`. Next lines (like  `loadNotificationsAndUpdateUI()`) works, if I don't add `return`.

**Review by ravishanker — APPROVED** [review]
Thanks for taking care of this.  LGTM 👍
