### PR TITLE
Unified Login & Sign-Up: Fix theming-related issues

### LINKED ISSUE #12376: Unified Login & Sign-Up: Username changer toolbar is not correctly styled
### Expected behavior
The username changer toolbar should either be white with black icons or blue with white icons.

### Actual behavior
The toolbar is white with white icons (making them invisible).

### Steps to reproduce the behavior
1. Create a new account from the app.
2. On the Epilogue screen, tap on the username field.
3. Notice the Username changer screen.
4. Notice how the toolbar is not correctly styled.

| Before | Now |
|---|---|
|before|now|

Note: these steps were originally provided by @develric in pbMoDN-ET-p2#comment-1213

### LINKED ISSUE #12417: Unified Login & Sign-Up: App crashes after selecting an avatar on Signup Epilogue screen
### Expected behavior
After selecting an image to use as an avatar on the Signup Epilogue screen, I expect to be able to crop it.

### Actual behavior
The app crashes as soon as I select the avatar image.

### Steps to reproduce the behavior
1. Go through the signup flow with email and magic link until you reach the epilogue.
2. Tap the Gravatar icon at the top of the epilogue screen.
3. Grant the app permission to access your photos.
4. On the “Choose photo” screen, select a photo.
5. At the top of the screen where it says “Use this photo” tap the check icon.

Note: these steps were originally provided by @rachelmcr in pbMoDN-ET-p2#comment-1305

##### Tested on moto e5 play, Android 8.1.0

### LINKED ISSUE #12420: Unified Login & Sign-Up: Text labels are incorrectly tinted on older API levels
### Expected behavior
I expect the text labels to be shown with their correct colors on every API level.

### Actual behavior
The text labels are tinted incorrectly on older API levels.

### Steps to reproduce the behavior
Run the app with on a device with Android 5 (API 21) and notice how the text labels have a red color:

### LINKED ISSUE #12421: Unified Login & Sign-Up: Toolbar is display incorrecty on older API levels
### Steps to reproduce the behavior
1. Tap "Enter your site address".
2. Enter a site email address.
3. Select the site email address.
4. Notice how the action mode toolbar is displayed on top of the regular toolbar, instead of over it:

### PR DESCRIPTION
**Pull request by renanferrari**
This PR fixes various theming and styling-related issues and crashes. Most of the changes are small and depend on each other a little bit, so I decided to group them into a single PR.

To test, I suggest taking a look at each commit separately and try to reproduce each issue that it fixes to verify that it doesn't happen anymore:

- [1e9c105](https://github.com/wordpress-mobile/WordPress-Android/commit/1e9c1053640f5f37194826761964b43c2f93df26) → fixes #12417 and #12418
- [bd9706c](https://github.com/wordpress-mobile/WordPress-Android/commit/bd9706cab7370b1bc16f67bdd87440d8f194d04f) → complements the changes above, by fixing the UCrop activity layout
- [81b74ba](https://github.com/wordpress-mobile/WordPress-Android/commit/81b74ba54e218d65d8f7f0495f6350c446269068) → fixes #12376
- [8bee093](https://github.com/wordpress-mobile/WordPress-Android/commit/8bee093f1df7379977fee351b57be206e0349399) → fixes #12420
- [57ed8c7](https://github.com/wordpress-mobile/WordPress-Android/commit/57ed8c77d101bd3104b22fdc1106357fcc9032ed) → fixes #12421

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by oguzkocer** [comment]
We no longer need to set the milestone for PRs that don't target `develop` or `release` branches. Milestones should be set to whichever version of the app the feature will be released in, so the milestones for PRs against feature branches are unlikely to be correct. We just need to make sure the PR from the feature branch to `develop` has the milestone which Peril checks will ensure. So, I am removing the milestone for this PR.

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SignupEpilogueFragment.java [hunk 1]
```diff
@@ -703,26 +705,20 @@ protected void showErrorDialogWithCloseButton(String message) {
...
-            ));
-            options.setAllowedGestures(UCropActivity.SCALE, UCropActivity.NONE, UCropActivity.NONE);
-            options.setHideBottomControls(true);
-
-            UCrop.of(uri, Uri.fromFile(new File(context.getCacheDir(), "cropped.jpg")))
-                 .withAspectRatio(1, 1)
-                 .withOptions(options)
-                 .start(getActivity(), this);
-        }
+        final Context context = new ContextThemeWrapper(getActivity(), R.style.WordPress_NoActionBar);
```
Comment (planarvoid) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SignupEpilogueFragment.java:708]: We're removing the getActivity() != null check. Is it possible it might cause a problem?

Comment (renanferrari) [reply WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SignupEpilogueFragment.java]: Good catch! `ContextThemeWrapper` will be non-null even if the base `context` is, which could cause problems indeed. 

I've made some changes to check if the base `context` is null before wrapping it with the `ContextThemeWrapper`.

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginFlowThemeHelper.kt [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+
+object LoginFlowThemeHelper {
+    /**
+     * This function should be used by activities that use the LoginFlow theme.
+     * These activities often use components that refer to custom theme attributes defined by the WordPress theme,
+     * but that are missing from the LoginFlow theme. Some examples: wpColorText, wpColorError, wpColorSuccess, etc.
+     * Instead of extending the LoginTheme only to include these attributes and having to maintain them in multiple
+     * places, we use this function to "inject" them directly.
+     */
+    @JvmStatic fun injectMissingCustomAttributes(theme: Resources.Theme) {
```
Comment (khaykov) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginFlowThemeHelper.kt:14]: Glad this worked!

Comment (renanferrari) [reply WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginFlowThemeHelper.kt:14]: It did! Thanks again for the help on this, btw 🙇‍♂️
