### PR TITLE
Layouts picker scroll position

### LINKED ISSUE #14364: Horizontal scroll position after orientation change in layout picker and site creation design picker
### Expected behavior
Horizontal scroll position of thumbnails is preserved after screen rotation.

### Actual behavior
Horizontal scroll position of thumbnails is not preserved on configuration change, even if you select a theme. It is expected to see the theme even after screen rotation.
Vertical Scroll position is not preserved in the most accurate way after configuration change either.

### Steps to reproduce the behavior
1. Open the page layout picker or the site design picker
2. Scroll horizontally on a category
3. Rotate the device
4. Notice that after rotation the visible themes change

### PR DESCRIPTION
**Pull request by ravishanker**
Fixes layout picker scroll position issue

Fixes #14364 

To test:

- scroll vertically to the bottom of this screen, 
- then scroll horizontally to the end of the Home pages list, then select the last layout, like the Raise Your Helping Hand
- and either scroll up to the top and back down to the bottom to see that the horizontal scroll position was reset to the left.

## Regression Notes
1. Potential unintended areas of impact
None

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by antonis — COMMENTED** [review]
Hey @ravishanker 👋 
Thank you for working on this 🙇 
The code changes are in the right direction but I managed to reproduce the [issue](https://github.com/wordpress-mobile/WordPress-Android/issues/14364) with the following steps:
1. Open the page layout picker or the site design picker
2. Scroll horizontally on a category
3. Rotate the device
4. Rotate back to the initial orientation
5. Notice that the visible themes changed 

https://user-images.githubusercontent.com/304044/131681234-6431a525-93c9-40e7-8b8d-f3808a1a7c03.mp4

_Tested on a Pixel 2 XL (Android 11)_

**Comment by ravishanker** [comment]
> Hey @ravishanker 👋
> Thank you for working on this 🙇
> The code changes are in the right direction but I managed to reproduce the [issue](https://github.com/wordpress-mobile/WordPress-Android/issues/14364) with the following steps:
> 
>     1. Open the page layout picker or the site design picker
> 
>     2. Scroll horizontally on a category
> 
>     3. Rotate the device
> 
>     4. Rotate back to the initial orientation
> 
>     5. Notice that the visible themes changed
> 
> 
> device-2021-09-01-163453.mp4
> 
> _Tested on a Pixel 2 XL (Android 11)_

Hi @antonis Thanks for the review.  I probably celebrated too soon!  I didn't try rotate back.  It is quite tricky given that recyclerview inside a viewholder.  Will take another pass at it.

**Comment by ravishanker** [comment]
> > Hey @ravishanker 👋
> > Thank you for working on this 🙇
> > The code changes are in the right direction but I managed to reproduce the [issue](https://github.com/wordpress-mobile/WordPress-Android/issues/14364) with the following steps:
> > ```
> > 1. Open the page layout picker or the site design picker
> > 
> > 2. Scroll horizontally on a category
> > 
> > 3. Rotate the device
> > 
> > 4. Rotate back to the initial orientation
> > 
> > 5. Notice that the visible themes changed
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > device-2021-09-01-163453.mp4
> > _Tested on a Pixel 2 XL (Android 11)_
> 
> Hi @antonis Thanks for the review. I probably celebrated too soon! I didn't try rotate back. It is quite tricky given that recyclerview inside a viewholder. Will take another pass at it.

Hi @antonis I've fixed the issue.  Please take another look at your convenience.  Thanks

File: WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutsItemViewHolder.kt [hunk 1]
```diff
@@ -1,24 +1,29 @@
...
+import androidx.recyclerview.widget.RecyclerView.OnScrollListener
 import org.wordpress.android.R
 
 /**
  * Modal Layout Picker layouts view holder
  */
 class LayoutsItemViewHolder(
     parent: ViewGroup,
-    private val prefetchItemCount: Int = 4
+    private val prefetchItemCount: Int = 4,
```
Comment (antonis) [inline WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutsItemViewHolder.kt:18]: I think we can remove the `,` at the end of the line

File: WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutPickerViewModel.kt [hunk 2]
```diff
@@ -65,6 +65,8 @@ abstract class LayoutPickerViewModel(
 
     abstract val useCachedData: Boolean
 
+    open var nestedScrollStates: Bundle = Bundle()
```
Comment (antonis) [inline WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutPickerViewModel.kt]: I think we can omit the `open` keyword

Comment (antonis) [reply WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutPickerViewModel.kt]: Having the `nestedScrollStates` in the ViewModel has the minor side effect that it persists the horizontal scroll positions when the layout chooser closes and reopens. I think it might work better if we instead moved the `nestedScrollStates` in the [LayoutPickerUiState](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutPickerUiState.kt) or in the `HomePagePickerFragment` and `ModalLayoutPickerFragment`. I haven't tried that though thus consider this just a suggestion.

**Review by antonis — APPROVED** [review]
Hey @ravishanker 👋 
Great work resolving this 👍 
I tested the app on a Pixel 5 with Android 12 and everything works as expected. The code also LGTM 🎉 
I've left only a few minor comments/suggestions 🙇

File: WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutsItemViewHolder.kt (hunk 1 above)
Comment (ravishanker) [reply WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutsItemViewHolder.kt:18]: removed, thanks

File: WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutPickerViewModel.kt (hunk 2 above)
Comment (ravishanker) [reply WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutPickerViewModel.kt]: removed open keyword
Looked into your suggestion for moving scrollState into some UiState, it is not available for access as it is nested through viewholders and recyclerviews.  It would have been easier if they were all just recyclerviews without nesting inside viewholders I guess.
