### PR TITLE
Site Title overlap on Tablets #16817

### LINKED ISSUE #16817: Site Title overlap on Tablets
### Expected behavior

The title should not overlap the Navigation Tabs (Home, Menu)

### Actual behavior

Sites which have long titles have them overlap the Home and Menu Tabs

### Steps to reproduce the behavior

- Log into the app on a Tablet Device
- Make sure you have more than 1 site connected and you have one with a long title

##### Tested on a Samsung Galaxy Tab A, Android 7.1.1, WPAndroid 20.0

Screenshot_20220624-141346

In #5305230-zen, the user was using a Lenovo TB-X104F, with Android version 8.1

### PR DESCRIPTION
**Pull request by gitstart**
Fixes #16817
Site Title overlap on Tablets

Solution
In `MySiteFragment.kt` in the `MySiteFragmentBinding.updateCollapsibleToolbar` function for a tablet all the values ie `appBarLayout.totalScrollRange and (verticalOffset)` are zero. Therefore the `updateCollapsibleToolbar` always shows the title on the `collapsingToolbar` and hides the  `siteInfoCard`. The solution was to check if the device `appBarLayout.totalScrollRange` is `0` and if it is, call `updateCollapsibleToolbar` with a value of one and set the percentage to 100.

To test:

- Log into the app on a Tablet Device
- Make sure you have more than 1 site connected and you have one with a long title

## Regression Notes
1. Potential unintended areas of impact
None

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Visual testing of the UI changes

3. What automated tests I added (or what prevented me from doing so)
No need to add any more tests

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Before UI
**Bug** [Loom Video](https://www.loom.com/share/c5071b2ca8a345208a9033c22562155b)

175532359-fbd82d89-00f8-4398-a4a0-864918d11b31

After Fix UI 
image

**On Scroll Up**

image

Loom video [here](https://www.loom.com/share/cb24417151054033862730238fb80f58)

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteFragment.kt [hunk 1]
```diff
@@ -105,9 +105,14 @@ class MySiteFragment : Fragment(R.layout.my_site_fragment),
             val maxOffset = appBarLayout.totalScrollRange
             val currentOffset = maxOffset + verticalOffset
 
-            updateCollapsibleToolbar(currentOffset)
+            val percentage = if (maxOffset == 0) {
+                updateCollapsibleToolbar(1)
+                resources.getInteger(R.integer.one_hundred)
+            } else {
+                updateCollapsibleToolbar(currentOffset)
+                ((currentOffset.toFloat() / maxOffset.toFloat()) * 100).toInt()
```
Comment (AjeshRPai) [inline WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteFragment.kt]: ❓ Would it be better if we add a static variable with the value `100` and use that instead of an integer value in `integers.xml`? Something like this 
```
   val percentage = if (maxOffset == 0) {
                updateCollapsibleToolbar(1)
                MAX_PERCENT
            } else {
                updateCollapsibleToolbar(currentOffset)
                ((currentOffset.toFloat() / maxOffset.toFloat()) * MAX_PERCENT).toInt()
            }
```

**Review by AjeshRPai — APPROVED** [review]
I have tested the changes, and everything looks good to me. However, I have left a suggestion for you to address. As that is non-blocking, I am approving the PR but not merging it so that you can make changes if you feel those are necessary.

File: WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteFragment.kt (hunk 1 above)
Comment (gitstart) [reply WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteFragment.kt]: Thank you for reviewing & approving the PR 🙌,
Yeah we can use static value.. Will do the changes and push the updated code.

**Comment by gitstart** [comment]
@AjeshRPai 
Requested changes pushed.

**Comment by AjeshRPai** [comment]
@gitstart Thanks for making the requested changes. 👍🏼 . Can u also update your branch with `trunk`? . Right now I can see some changes which are not part of this PR.

File: WordPress/src/main/res/values/integers.xml [hunk 2]
```diff
@@ -42,5 +42,5 @@
 
     <!--Site Creation-->
     <integer name="site_creation_snackbar_duration">5000</integer>
-
+
```
Comment (AjeshRPai) [inline WordPress/src/main/res/values/integers.xml]: @gitstart ❓ Can we remove this blank space?

Comment (gitstart) [reply WordPress/src/main/res/values/integers.xml]: @AjeshRPai 
Removed blank space.

Comment (AjeshRPai) [reply WordPress/src/main/res/values/integers.xml]: @gitstart Can you revert the changes in this file, so it's identical to the `trunk`? It's still showing up on the files changed tab on PR. I believe there was an empty space after the closing tab as per formatting, which got removed on this PR. Sorry for nitpicking this.

Comment (gitstart) [reply WordPress/src/main/res/values/integers.xml]: No problem @AjeshRPai. Reverted to exact `trunk` version. 
Please have a look now. Thank you!

Comment (AjeshRPai) [reply WordPress/src/main/res/values/integers.xml]: Thanks, @gitstart. All looks good 👍🏼 . I am triggering the CI for this Branch. Once it succeeds. I will merge it. Once again, thanks for working on this issue.
