### PR TITLE
Fix 11835: Input validation for post password dialog

### LINKED ISSUE #11835: Post Password Dialog : Input validation required
### Expected behavior
That the password dialog should have input validation and empty spaces and such forth shouldn't allow it to be submitted. 

### Actual behavior
It has no input validation so you are able to set empty spaces as a password. 

<kbd></kbd>

### Steps to reproduce the behavior
1. Create a new post.
2. Go to Post Settings.
3. Click on the field and add an empty password.
4. Once you press okay you will see the empty password below the Password title.

Link to video https://drive.google.com/open?id=1A3lTcgO9MQAFmVa7heDq2XztIlO9hmMa

Tested on Google Pixel 4 XL, Android 10, WPAndroid `develop` ()

### PR DESCRIPTION
**Pull request by adityabhaskar**
Fixes #11835 

## Issue

Users can set a 'blank' post password consisting entirely of spaces. There is no input validation of password submitted by users.

## Solution

Check provided password if it is blank, i.e. is empty or consists of spaces only.

1. Do nothing if the new password is blank, and the post does not already have a password.
2. Remove post password if the new password is blank, and the post has a password.
3. Set password, without trimming spaces, if it is not blank.

## To test

1. Create a new post.
2. Open Post Settings from overflow menu

### Test 1:
1. Set a post password consisting of only spaces.
2. Check that no password has been set.

### Test 2:
1. Set a post password consisting of only non-space characters.
2. Check that new password has been saved.

### Test 3:
1. With a non-space password set, set a new password consisting of only spaces
2. Check that password has been removed.

### Test 4:
1. Set a post password non-space characters, with leading/trailing spaces.
2. Check that new password is saved including leading/trailing spaces.

PR submission checklist:

- [ ] I have considered adding unit tests where possible.
- [ ] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java [hunk 1]
```diff
@@ -744,17 +744,28 @@ private void updateSlug(String slug) {
...
-                }
-                return null;
-            });
-        }
+        if (editPostRepository == null) return;
+
+        String trimmedPassword = password.trim();
+        Boolean isNewPasswordBlank = trimmedPassword.isEmpty();
+        String previousPassword = editPostRepository.getPassword();
+        Boolean isPreviousPasswordBlank = previousPassword.isEmpty() || previousPassword.trim().isEmpty();
```
Comment (jd-alexander) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java:752]: Hi @adityabhaskar would this give the same result hence making the `isEmpty()` redundant? Let me know your thoughts. Thanks 👍 

```suggestion
        Boolean isPreviousPasswordBlank = previousPassword.trim().isEmpty();
```

Comment (adityabhaskar) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java:752]: I was just unnecessarily micro optimising—no need to trim if length is already zero :)

Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java]: Awesome! Thanks much @adityabhaskar 🙏
