### PR TITLE
Guard for null Activity in a Gravatar showToast

### LINKED ISSUE #8590: Crash in ToastUtils showToast
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getString(int)' on a null object reference
       at org.wordpress.android.util.ToastUtils.showToast(ToastUtils.java:25)
       at org.wordpress.android.ui.main.MeFragment$8.onLoadFailed(MeFragment.java:331)
       at org.wordpress.android.util.image.ImageManager$attachRequestListener$1.onLoadFailed(ImageManager.kt:277)
       at com.bumptech.glide.request.SingleRequest.onLoadFailed(SingleRequest.java:613)
       at com.bumptech.glide.request.SingleRequest.onLoadFailed(SingleRequest.java:593)
       at com.bumptech.glide.load.engine.EngineJob.handleExceptionOnMainThread(EngineJob.java:293)
       at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:327)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
``` 

5ae5c2ea638393737aa7e57e-fabric

### PR DESCRIPTION
**Pull request by hypest**
Fixes #8590 

Couldn't replicate the issue so, just guarding for the null Activity case.

While at it, logging the exception reported by the Image Loader.

To test:
No test steps available. You might want to try the info found in the original ticket and the comments there ([this one in particular](https://github.com/wordpress-mobile/WordPress-Android/issues/8590#issuecomment-451442787)).

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.java [hunk 1]
```diff
@@ -328,8 +329,18 @@ private void loadAvatar(final String avatarUrl, String injectFilePath) {
...
-                                    ToastUtils.Duration.SHORT);
+                            final String appLogMessage = "onLoadFailed while loading Gravatar image!";
+                            if (e == null) {
+                                AppLog.e(T.MAIN, appLogMessage + " e == null");
+                            } else {
+                                AppLog.e(T.MAIN, appLogMessage, e);
+                            }
+
+                            // For some reason, the Activity can be null so, guard for it. See #8590.
+                            if (getActivity() != null) {
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.java]: Maybe the activity can be null if the user already logged out? In that case `WPMainActivity` is gone when the network response returns to the fragment.

Wondering why we're not checking if the fragment is attached or not here, and `onResourceReady`.

Comment (hypest) [reply WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.java]: > Maybe the activity can be null if the user already logged out?

Could be, yeah. Do you perhaps have something in mind to handle that case differently?

> Wondering why we're not checking if the fragment is attached or not here, and `onResourceReady`.

Oh, you think it could make a difference for `onLoadFailed()`? I guess we'd still want the exception to be logged and then guard the Toast with the `isAdded()`. I can go ahead and do the chance if you prefer that.

Regarding `onResourceReady()`, it doesn't seem to need access to the Activity so, not sure it needs to be guarded. Do you see a need there @daniloercoli?

**Comment by daniloercoli** [comment]
LGTM!

File: WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.java (hunk 1 above)
Comment (daniloercoli) [reply WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.java]: > Could be, yeah. Do you perhaps have something in mind to handle that case differently?

Checking for `null` activity is ok, since we're already removing pending network requests on logout. Maybe this particular request was already running on logout and the clear method didn't stop it. Anyway, your code is good to go.

Re-checked the code, and it seems we don't need to add those `isAdded` guards I mentioned in the comment above.
