### PR TITLE
Remove Reblog button for Jetpack sites

### LINKED ISSUE #7162: Reblog button option should not appear for Jetpack (or AT) sites.
### Expected behavior
When going to the Sharing menu in the Android app when managing a Jetpack site, the Reblog option should not appear: it is not available outside of WordPress.com. `p4a5px-280-p2`

### Actual behavior
The button is there.

### Steps to reproduce the behavior
Go to the Sharing menu for a Jetpack site.

### PR DESCRIPTION
**Pull request by planarvoid**
Fixes #7162 
Hides "Show Reblog button" settings if the site is jetpack connected. Changes the header text from "Reblog & Like" to just like
I removed an unused settings fragment and it's XML file. Any objections? Did I miss something? 

To test:
* Log in with self-hosted Jetpack site
* Go to Site/Configuration - Sharing/Sharing buttons - Manage
* "Show Reblog Button" setting is gone
* The category containing the "Show Like Button" setting is titled "Like"

screenshot_1519136340

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeButtonPrefsFragment.java [hunk 1]
```diff
@@ -116,6 +116,11 @@ public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container,
         mPrefAllowCommentLikes = (WPPrefView) view.findViewById(R.id.pref_allow_comment_likes);
         mPrefTwitterName = (WPPrefView) view.findViewById(R.id.pref_twitter_name);
 
+        if (!mSite.isWPCom() && mSite.isJetpackConnected()) {
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeButtonPrefsFragment.java]: Just a quick note: we prefer to use `mSite.isUsingWpComRestApi()` instead of `mSite.isJetpackConnected()` because a site could be Jetpack connected but still using the xml-rpc api. For this feature it doesn't make a difference since we don't show the "Sharing" button to xml-rpc users. Here is a test which shows this case: https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/develop/example/src/androidTest/java/org/wordpress/android/fluxc/release/ReleaseStack_SiteTestJetpack.java#L146
