### PR TITLE
Move GoogleApiClient.Builder to onStart/Stop methods

### LINKED ISSUE #10357: Crash when trying to create a WordPress account
### Expected behavior
No crash

### Actual behavior
    java.lang.IllegalStateException: Already managing a GoogleApiClient with id 1001
        at com.google.android.gms.common.internal.Preconditions.checkState(Unknown Source)
        at com.google.android.gms.common.api.internal.zzi.zza(Unknown Source)
        at com.google.android.gms.common.api.GoogleApiClient$Builder.build(Unknown Source)
        at org.wordpress.android.login.SignupEmailFragment.onCreate(SignupEmailFragment.java:153)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2414)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
        at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1195)
        at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1078)
        at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:117)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2408)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

##### Tested on [device], Android [version], WPAndroid [version]
API level 22

### PR DESCRIPTION
**Pull request by planarvoid**
Fixes #10357

I think (and I might be wrong) that there are 2 possible issues. One is that sometimes `onDestroy` and `onDetach` are not called. The other one is that in the `SignupEmailFragment` we were checking whether the client is connected before we called `stopAutoManage` and I don't think that's always the case (I was able to make that crash after moving the logic to `onStart` and `onStop`). 

This PR is not really based on evidence so I might be very wrong :-).

To test:
* Test Login and Signup
* Try to move the app to the background in the middle of the process and come back

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/SignupEmailFragment.java [hunk 1]
```diff
@@ -143,16 +143,24 @@ public void onAttach(Context context) {
...
                 .enableAutoManage(getActivity(), GOOGLE_API_CLIENT_ID, SignupEmailFragment.this)
                 .addApi(Auth.CREDENTIALS_API)
                 .build();
     }
 
+    @Override
+    public void onStop() {
+        super.onStop();
+        mGoogleApiClient.stopAutoManage(getActivity());
+        if (mGoogleApiClient != null && mGoogleApiClient.isConnected()) {
```
Comment (develric) [inline libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/SignupEmailFragment.java]: Maybe we can move the null check on `mGoogleApiClient` a level above so to protect also the access to `stopAutoManage`. wdyt?

File: libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailFragment.java [hunk 2]
```diff
@@ -280,14 +280,27 @@ public void onCreate(Bundle savedInstanceState) {
...
                 .enableAutoManage(getActivity(), GOOGLE_API_CLIENT_ID, LoginEmailFragment.this)
                 .addApi(Auth.CREDENTIALS_API)
                 .build();
     }
 
+    @Override
+    public void onStop() {
+        super.onStop();
+        mGoogleApiClient.stopAutoManage(getActivity());
+        if (mGoogleApiClient != null && mGoogleApiClient.isConnected()) {
```
Comment (develric) [inline libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailFragment.java]: Same comment as [here](https://github.com/wordpress-mobile/WordPress-Android/pull/10523/files#r329371454). Maybe I would also consider to add same null check logic here for consistency. Let me know what you think 😊.

File: libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/SignupEmailFragment.java (hunk 1 above)
Comment (planarvoid) [reply libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/SignupEmailFragment.java]: you're right. I've originally had the full check there but it was crashing. In this case we should split the check.
