### PR TITLE
Issue/7518 - Media Library Empty State Message Shows Incorrect Category

### LINKED ISSUE #7518: Media Library Empty State Message Shows Incorrect Category
### Expected
The empty state message shown on the media library screen shows the currently selected tab value when there are no search results.  In other words, if the Images tab is selected and searching returns no results, the empty state message is "You don't have any images." if any other tab was previously selected.

### Observed
The empty state message shown on the media library screen shows the previously selected tab value when there are no search results.  In other words, if the Images tab is selected and searching returns no results, the empty state message is "You don't have any documents." if the documents tab was previously selected.

### Reproduced
1. Go to ***Sites*** tab.
2. Tap ***Media*** item from ***Publish*** section.
3. Select tab with no items (e.g. ***Documents***).
4. Select tab with some items (i.e. ***Images***).
5. Tap ***Search*** action.
6. Enter characters until empty state is shown.
7. Notice ***You don't have any documents.*** message.

##### Tested
Google Pixel 2 on Android 8.1.0 with WordPress alpha-103

### PR DESCRIPTION
**Pull request by jorgecasariego**
Fixes #7518 Media Library Empty State Message Shows Incorrect Category

To test:

1. Go to **Sites** tab.
2. Tap **Media** item from Publish section.
3. Select tab with no items (e.g. **Documents**).
4. Select tab with some items (i.e. **Images**).
5. Tap **Search** action.
6. Enter characters until empty state is shown.
6. Notice the empty state message shown on the media library screen shows the currently selected tab value (e.g. "You don't have any images)

cc @theck13

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridFragment.java [hunk 1]
```diff
@@ -525,6 +525,10 @@ public void search(String searchTerm) {
         mSearchTerm = searchTerm;
         List<MediaModel> mediaList = getFilteredMedia();
         mGridAdapter.setMediaList(mediaList);
+
+        if(isEmpty()){
```
Comment (theck13) [inline WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridFragment.java]: To keep the code style consistent, we should change `if(isEmpty()){` to `if (isEmpty()) {`.

Comment (jorgecasariego) [reply WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridFragment.java]: Sorry about this. I didn't check before push to GitHub 😬

**Comment by jorgecasariego** [comment]
Thanks again @theck13 😃
