### PR TITLE
Issue/10189 Clears old data from previous visits to wizard steps

### LINKED ISSUE #10189: siteCreationState data payloud out of synch with UI when moving backwards then skipping forwards through site creation wizard
### Expected behavior
During new site creation, moving backwards in the wizard should not create a deviation between the "siteCreationState" used to create your site, and what the UI input forms show to the user. 

### Actual behavior
If you move backwards in the site creation wizard, you will clear the user input forms for vertical, site title, and tagline. If you skip through them on your next pass through, however, leaving them in this empty form, and then search for a domain and create a site, the vertical, site title, and tagline previously entered will come back because they stayed preserved in the siteCreationState.  

### Feeback welcome!, see my suggestion below:
Not objectively obvious whether we want these fields to clear when the user moves backwards, but if we do, then we should clear the "siteCreationState" so users next pass through doesn't save unexpected state, not visible to the user if they skip. In my opinion, we should not clear the UI when the user moves backwards through the wizard, we should just display the previously saved "siteCreationState" which we are already retaining anyway.

### Steps to reproduce the behavior

1. My Site
2. Switch Site
3. Click on plus sign icon in the top right corner
4. Select "Create WordPress.com site"
5. Choose a site type
6. Enter some custom vertical type, click next
7. Enter site title and tagline, click next
8. On the choose a domain screen, hit the back arrow
9. On the title/tagline screen, hit the back arrow
10. On the vertical screen, hit the back arrow
11. Choose a site type
12. Press skip for site vertical
13. Press skip for title/tagline
14. Search a domain, select, and press create (before you search you will see the previously entered title even though you skipped title input this time)
15. Verify that the previously entered vertical, title, and tagline have returned even though they were skipped on second pass through the wizard. 

*Note in test build I wasn't able to create a site (OAuth settings?), but I was able to verify the issue with Play Store build, and with test build I was able to verify unexpected "siteCreationState" using the debugger.

### PR DESCRIPTION
**Pull request by cameronvoell**
Fixes #10189

### To test:
Steps to reproduce the behavior

1. My Site
2. Switch Site
3. Click on plus sign icon in the top right corner
4. Select "Create WordPress.com site"
5. Choose a site type
6. Enter some custom vertical type, click next
7. Enter site title and tagline, click next
8. On the choose a domain screen, hit the back arrow
9. On the title/tagline screen, hit the back arrow
10. On the vertical screen, hit the back arrow
11. Choose a site type
12. Press skip for site vertical
13. Press skip for title/tagline
14. Search a domain, select, and press create (before you search you can verify you do not see the previously entered title)
15. Verify that the previously entered verticalId, title, and tagline are gone because you skipped on your second pass through the wizard.

*Note if you can not create sites in test build like me, you may need to verify through the debugger (and through the lack of old title searches appearing like they were before the fix)

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by cameronvoell** [comment]
Just want to mention, I cleared segmentId on the segment step and domain on the domain step even though it is currently impossible to reproduce the issue on those steps. I coded defensively here in case restrictions on requiring those fields are lifted in the future. Let me know if that was overzealous and it is preferred that we only clear title, tagline, and verticalId for now.

**Comment by cameronvoell** [comment]
looking at failed tests now

**Comment by cameronvoell** [comment]
Ready for review (can't change labels :-P, but I can comment!)

**Comment by shiki** [comment]
Thank you, @cameronvoell! 

@malinajirka it looks like you are the most knowledgeable on Site Creation. Would you be able to review this? 🙂

File: WordPress/src/test/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVMTest.kt [hunk 1]
```diff
@@ -249,6 +255,19 @@ class SiteCreationMainVMTest {
         verify(wizardManager).setCurrentStepIndex(index)
     }
 
+    @Test
+    fun oldSiteCreationDataClearedWhenReturningToPreviousStep() {
+        // See issue #10189 - unintended data retained if user goes backwards in wizard
+        whenever(wizardManager.showNextStep()).then {
```
Comment (malinajirka) [inline WordPress/src/test/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVMTest.kt]: I believe the `whenever` is not needed here. Imho it makes the test a bit more difficult to understand. Wdyt?

**Comment by malinajirka** [comment]
Thanks @cameronvoell ! It looks and works great - good job. I've left two nitpicking comments!

File: WordPress/src/test/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVMTest.kt (hunk 1 above)
Comment (cameronvoell) [reply WordPress/src/test/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVMTest.kt]: Yeah, I think we can get away with taking that out here, since it is documented in previous tests that we need showNextStep() to not default to SEGMENT when we test setting segmentID, but it is okay for testing other values.

`@Test
    fun siteCreationStateUpdatedWithSelectedSegment() {
        whenever(wizardManager.showNextStep()).then {
            wizardManagerNavigatorLiveData.value = SiteCreationStep.VERTICALS
            Unit
        }
        viewModel.onSegmentSelected(SEGMENT_ID)
        assertThat(currentWizardState(viewModel).segmentId).isEqualTo(SEGMENT_ID)
    }
`

   ` @Test
    fun siteCreationStateUpdatedWithSelectedVertical() {
        viewModel.onVerticalsScreenFinished(VERTICAL_ID)
        assertThat(currentWizardState(viewModel).verticalId).isEqualTo(VERTICAL_ID)
    }
`

I'll remove that whenever so the test is easier to read.

File: WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVM.kt [hunk 2]
```diff
@@ -114,6 +119,21 @@ class SiteCreationMainVM @Inject constructor(
         }
     }
 
+    private fun clearOldSiteCreationState(wizardStep: SiteCreationStep) {
+        when (wizardStep) {
```
[the remark this answers is not in the document]
Comment (cameronvoell) [reply WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVM.kt]: updated

**Comment by cameronvoell** [comment]
Did a git rebase for the better commit ordering, but forgot it would make the PR so hard to read. let me know if you want me to fix.
