### PR TITLE
fix #3966 catch runtime exception sadness

### LINKED ISSUE #3966: Crash report 5.2: PostUploadNotifier.updateNotificationIcon
Only happens on Android 6.0 - looks like a concurrency issue.

```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:309)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.RuntimeException: bad array lengths
       at android.os.Parcel.readIntArray(Parcel.java:926)
       at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:777)
       at android.app.NotificationManager.notify(NotificationManager.java:272)
       at android.app.NotificationManager.notify(NotificationManager.java:211)
       at org.wordpress.android.ui.posts.services.PostUploadService$PostUploadNotifier.updateNotificationIcon(PostUploadService.java:893)
       at org.wordpress.android.ui.posts.services.PostUploadService$UploadPostTask.processPostMedia(PostUploadService.java:492)
       at org.wordpress.android.ui.posts.services.PostUploadService$UploadPostTask.doInBackground(PostUploadService.java:235)
       at org.wordpress.android.ui.posts.services.PostUploadService$UploadPostTask.doInBackground(PostUploadService.java:166)
       at android.os.AsyncTask$2.call(AsyncTask.java:295)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

### PR DESCRIPTION
**Pull request by maxme**
fix #3966 catch runtime exception sadness

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/services/PostUploadService.java [hunk 1]
```diff
@@ -855,44 +852,35 @@ private File createTempUploadFile(String fileExtension) throws IOException {
...
         private float mItemProgressSize;
 
-        public PostUploadNotifier(Post post) {
+        public PostUploadNotifier(Post post, String title, String message) {
             // add the uploader to the notification bar
             mNotificationManager = (NotificationManager) SystemServiceFactory.get(mContext,
                     Context.NOTIFICATION_SERVICE);
-
-            mNotificationBuilder = new NotificationCompat.Builder(getApplicationContext());
+            new Notification.Builder(getApplicationContext());
```
Comment (hypest) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/services/PostUploadService.java]: Leftover code?

File: WordPress/src/main/java/org/wordpress/android/ui/posts/services/PostUploadService.java [hunk 2]
```diff
@@ -1006,13 +994,16 @@ public void updateNotificationProgress(float progress) {
             }
 
             mNotificationBuilder.setProgress(100, (int)Math.ceil(currentChunkProgress), false);
+            notifyManager(mNotificationId, mNotificationBuilder.build());
+        }
 
+        private void notifyManager(int id, Notification notification) {
```
Comment (hypest) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/services/PostUploadService.java]: Nitpicking but, for readability purposes, would you consider renaming this to something like "doNotify()" to better reflect its functionality? Cheers!

**Comment by hypest** [comment]
LGTM! Thanks for considering `synchronized` as well!
