### PR TITLE
Issue/3940 reader tag titles

### LINKED ISSUE #3940: Reader: Issue with primary tags under the News & Current Events topic
To reproduce: 
- While signed in with just a self-hosted account browse to the reader and selected the `News & Current Events` topic. 
- Notice the post cards show a primary tag of `#News/ Current Events`.  The slash seems odd, maybe something misformatted? 
- Tap to preview the primary tag. 
- The tag preview shows "No posts with this tag."

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #3940 

The problem Eric uncovered was actually quite deep and touched a lot of areas of the reader. 

In a nutshell, the app wasn't differentiating between a tag's "title" (the title to display for the tag) and the tag's "name" (the name to use when updating the tag via the endpoint).

For example, the tag titled "News & Current Events" is named "news-current-events," but the Android app didn't store both the name & title, causing numerous problems in addition to the one mentioned in the original issue.

@aerych Any chance you'd be able to review this one, or at least verify that the code is working correctly?

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/reader/services/ReaderUpdateService.java [hunk 1]
```diff
@@ -200,9 +200,15 @@ private static ReaderTagList parseTags(JSONObject jsonObject, String name, Reade
             String internalName = it.next();
             JSONObject jsonTopic = jsonTopics.optJSONObject(internalName);
             if (jsonTopic != null) {
-                String tagName = JSONUtils.getStringDecoded(jsonTopic, "title");
+                String tagTitle = JSONUtils.getStringDecoded(jsonTopic, "title");
+                String tagName;
+                if (jsonTopic.has("display_name")) {
```
Comment (aerych) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/services/ReaderUpdateService.java]: Maybe use `slug` vs `display_name`? It might help clarify the distinction between the tags name and the tags title.  `display_name` is rather unfortunate as a dictionary key. At a glance you'd think its what would be presented to the user on screen.

File: WordPress/src/main/java/org/wordpress/android/models/ReaderTag.java [hunk 2]
```diff
@@ -9,50 +9,61 @@
...
-    public String getCapitalizedTagName() {
-        if (tagName == null || tagName.length() == 0) {
+
+    /*
+     * when displaying a tag name, we want to use the title when available since it's often
+     * more user-friendly
+     */
+    public String getTagNameForDisplay() {
+        if (!TextUtils.isEmpty(tagTitle)) {
+            return tagTitle;
```
Comment (aerych) [inline WordPress/src/main/java/org/wordpress/android/models/ReaderTag.java]: Sadly, the string returned `title` isn't capitalized half the time. :(

File: WordPress/src/main/java/org/wordpress/android/ui/reader/services/ReaderUpdateService.java [hunk 3]
```diff
@@ -200,9 +200,15 @@ private static ReaderTagList parseTags(JSONObject jsonObject, String name, Reade
...
+                    tagName = JSONUtils.getStringDecoded(jsonTopic, "display_name");
+                } else {
+                    tagName = tagTitle;
+                }
                 String endpoint = JSONUtils.getString(jsonTopic, "URL");
-                topics.add(new ReaderTag(tagName, endpoint, topicType));
+                topics.add(new ReaderTag(tagName, tagTitle, endpoint, topicType));
```
Comment (aerych) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/services/ReaderUpdateService.java]: Maybe check to ensure the `tagTitle` is capitalized the way we like, then store the capitalized title.

**Comment by aerych** [comment]
Hiya @nbradbury :) 
I left a couple of notes, one issue with capitalization and a small suggestion. 
When I was testing, apart from the issue with capitalization in the tag list I also noticed that post cards are showing the tag's name (slug) not the tag's title.  Maybe we're not storing both the slug and title for the post's tag?
screen shot 2016-04-18 at 9 13 47 pm
screen shot 2016-04-18 at 9 26 45 pm

**Comment by aerych** [comment]
Follow up:  Soooo I guess I missed that we *do* want to use the [display_name vs title when displaying tags](https://github.com/Automattic/wp-calypso/pull/2775).  So disregard my note about the tag's appearance on the cards and list header. :)

**Comment by nbradbury** [comment]
@aerych I believe this is ready for another round. I've left tag capitalization and the use of `tag_display` alone, instead moving that to [another issue](https://github.com/wordpress-mobile/WordPress-Android/issues/3985).

File: WordPress/src/main/java/org/wordpress/android/models/ReaderPost.java [hunk 4]
```diff
@@ -273,7 +273,7 @@ private static void assignTagsFromJson(ReaderPost post, JSONObject jsonTags) {
             int postCount = jsonThisTag.optInt("post_count");
             if (postCount > popularCount) {
                 nextMostPopularTag = mostPopularTag;
-                mostPopularTag = JSONUtils.getStringDecoded(jsonThisTag, "name");
+                mostPopularTag = JSONUtils.getStringDecoded(jsonThisTag, "display_name");
```
Comment (aerych) [inline WordPress/src/main/java/org/wordpress/android/models/ReaderPost.java]: Wondering if this should be also be `slug`.  It looks like in places like `getTagForDisplay` the string passed will be the slug for the current tag.

**Comment by aerych** [comment]
@nbradbury took this for a spin and everything was working great, including tags from doublebyte chars (yay Kanji).  I had one concern where we might be comparing the value of `slug` to `display_name`.  I didn't see any other places that might be happening but another set of Android eyes would probably be a good idea.  
Once the concern with the comparison is addressed (patched if needed or determined to be benign) then its a :shipit: from me.

File: WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java [hunk 5]
```diff
@@ -439,7 +439,7 @@ public static String getOldestPubDateInFeed(long feedId) {
     public static void removeGapMarkerForTag(final ReaderTag tag) {
         if (tag == null) return;
 
-        String[] args = {tag.getTagName(), Integer.toString(tag.tagType.toInt())};
+        String[] args = {tag.getTagSlug(), Integer.toString(tag.tagType.toInt())};
         String sql = "UPDATE tbl_post_tags SET has_gap_marker=0 WHERE has_gap_marker!=0 AND tag_name=? AND tag_type=?";
```
Comment (roundhill) [inline WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java]: Should it be `tag_slug=?` here now instead of `tag_name`?

Comment (roundhill) [inline WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java]: Oh nevermind, I see now that tag_name hasn't changed in `tbl_post_tags`.

File: WordPress/src/main/java/org/wordpress/android/datasets/ReaderTagTable.java [hunk 6]
```diff
@@ -114,53 +117,54 @@ public static boolean tagExists(ReaderTag tag) {
...
 
-    public static boolean isFollowedTagName(String tagName) {
-        return tagExistsOfType(tagName, ReaderTagType.FOLLOWED);
+    public static boolean isFollowedTagName(String tagSlug) {
+        return tagExistsOfType(tagSlug, ReaderTagType.FOLLOWED);
     }
 
-    public static boolean isDefaultTagName(String tagName) {
-        return tagExistsOfType(tagName, ReaderTagType.DEFAULT);
+    public static boolean isDefaultTagName(String tagSlug) {
```
Comment (roundhill) [inline WordPress/src/main/java/org/wordpress/android/datasets/ReaderTagTable.java]: AS is claiming that this method is unused.

**Comment by roundhill** [comment]
Looks good :shipit:
