### PR TITLE
Temporarily disable option to connect a Facebook account to Publicize

### LINKED ISSUE #15456: Fix authentication bug when sharing to Facebook
### Expected behavior

When sharing to Facebook, users expect a seamless experience authenticating their Facebook account, even if they don't have the Facebook app installed on their device.

### Actual behavior

Users attempting to share to Facebook (My Site → Sharing → Facebook) see what looks like a cryptic technical message or error when trying to authenticate via their Facebook account. After tapping Connect, a Facebook login page is shown briefly before users are redirected to a screen which explains how Facebook login is not permitted in embedded web views. It asks the user to download the Facebook app to continue.

The glitchy UX (Facebook login page shown briefly) plus the technical message ("login is not permitted in embedded web views") feels like a hurdle for most users, even if instructions to resolve the issue (by downloading the Facebook app) are included in the message.

Update: Installing the Facebook app does not allow users to authenticate and share to Facebook, see https://github.com/wordpress-mobile/WordPress-Android/issues/15456#issuecomment-973662924.

As @thehenrybyrd suggested offline, a better user experience might involve re-directing users to the device's web browser to login (and have it redirect to the app) if that is possible. It might be worth investigating what options we have for users such as this who don't have the Facebook app installed on their device. 

### Steps to reproduce the behavior

**Prerequiste**: Make sure the device does not have the Facebook app installed.

1. Go to the My Site tab
2. Tap Sharing
3. Tap Facebook
4. Tap Connect
5. Notice that the Facebook login screen is shown briefly
6. Notice after a second or two that are "Log in Disabled" screen is shown with an explanation of the issue and instructions to download the Facebook app
7. Install the Facebook app and try to share to Facebook again
8. Notice the warning from Step 6 is still shown (see https://github.com/wordpress-mobile/WordPress-Android/issues/15456#issuecomment-973662924)

### PR DESCRIPTION
**Pull request by renanferrari**
Fixes #15456

This PR temporarily disables the ability for a user to connect a Facebook account to the Publicize feature through the app. Viewing and disconnecting a Facebook account will still be possible, but connecting will only be available through the web. (internal ref for additional context: pbArwn-3uU-p2)

Note that this is not really a fix for #15456 just yet, but more of a way to temporarily suppress the main error there until we figure out a better solution.

The main change introduced here is that if the user selects the Facebook option on the Sharing screen and then taps the "Connect" button, they will now see a dialog instead of continuing to the usual connection flow. The dialog explains this action is currently unavailable and suggests continuing through the web, as shown in the video below:

https://user-images.githubusercontent.com/830056/150023135-022a021f-48a1-425e-8b90-43d9d16fd9fc.mp4

I also considered hiding or disabling either the Facebook option entirely or just the "Connect" button, but those alternatives didn't seem as clear and flexible as the dialog. As for the dialog itself, I also considered a shorter message like `Sorry, connecting a Facebook account is currently only available through the web version of WordPress.` as well as a different label button like `Continue on the web`. 

I'm adding both the `Needs Copy Review` and `Need Design Review` tags so that we can carefully consider all the appropriate alternatives before we merge this. 

### To test

1. Open the app and select a WP.com or Jetpack site.
1. On the My Site screen, scroll down to the Configuration section.
1. Tap "Sharing".
1. Tap "Facebook".
1. Tap "Connect".
1. Make sure you see the new dialog.
1. Tap "Go to web".
1. Make sure an external browser is opened with the following address: `https://https://wordpress.com/marketing/connections/{currentSiteUrl}`.

## Regression Notes
1. Potential unintended areas of impact
Other Publicize connections.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing.

3. What automated tests I added (or what prevented me from doing so)
None. A bigger refactor was out of scope at this moment. 

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeListActivity.java [hunk 1]
```diff
@@ -249,6 +259,30 @@ public void onRequestDisconnect(PublicizeConnection publicizeConnection) {
         confirmDisconnect(publicizeConnection);
     }
 
+    private boolean isFacebook(PublicizeService service) {
+        return service.getId().equals(PublicizeConstants.FACEBOOK_ID);
+    }
+
+    private String getConnectionsUrl(SiteModel site) {
+        return "https://wordpress.com/marketing/connections/" + SiteUtils.getHomeURLOrHostName(site);
```
Comment (ravishanker) [inline WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeListActivity.java]: Should this URL go into constants?  Is it because it is a temporary fix!

**Review by ravishanker — APPROVED** [review]
Works well as a workaround and avoids error message.  Nice work  👍

Please merge it after design and copy reviews.

File: WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeListActivity.java (hunk 1 above)
Comment (renanferrari) [reply WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeListActivity.java]: Good catch! It wasn't intentional, I guess I was just being lazy 😅

Fixed in a96f815c255a2d8f9ba1c05569df0820f467686d.

**Comment by mattmiklic** [comment]
I think overall the UX seems fine as a temporary solution to the problem. The text of the modal dialog is quite verbose though, so I'd recommend something a bit shorter. If someone from the Editorial team has time to make an edit that might be the best solution, but if not, we could try something like:

> You can connect your Facebook account on the WordPress.com website. When you're done, return to the WordPress app to change your Sharing settings.

The "Cancel" and "Go to web" labels can remain the same.

**Comment by renanferrari** [comment]
Thank you, @mattmiklic! Adopted your suggestion in e80e801c4a0deda65806f45c6d567caa2f887a73.
