### PR TITLE
WPWebChromeClient with File Chooser support for form upload input type

### LINKED ISSUE #14967: Custom Forms: Select File upload button doesn't initiate in Preview
When using custom form plugins like CF7, you have the ability to add file/attachment upload fields. However, when you preview the page, tapping the file upload field doesn't do anything.

All the other tested fields (text, email, textarea, etc) works.

### Expected behavior
To have a functional form when I tap Preview, even if the block is not supported in the editor, like we see in the iOS app:

### Actual behavior
* When tapping the file field in Preview mode, nothing happens.
* The file field works without issues when you visit the page from a browser

### Steps to reproduce the behavior
1. Install a custom plugin like CF7: https://wordpress.org/plugins/contact-form-7/
2. Edit the default form and make sure you add a [file upload field](https://contactform7.com/file-uploading-and-attachment/)
3. Add the CF7 block to a post or page
4. Tap the 3-dots, then "Preview"

##### User report: 4101931-zen

### PR DESCRIPTION
**Pull request by jd-alexander**
Fixes #14967

## Findings
The `WPWebChromeClient` does not currently override the `onShowFileChooser` method that allows for files to be uploaded when the file upload input type is utilized. 

Therefore the `WPWebChromeClient` was extended as `WPWebChromeClientWithFileChooser` within the main app, since the integration with `MediaUtils` from FluxC would be seamless. 

## Solution
 - The `WPWebChromeClient` implements the`onShowFileChooser` so that it now integrates with the `WPWebViewActivity ` to provide a file picking experience for any intents that utilize the `WebView` functionality. 
 
- I utilized the depreciated startForActivityResult because its usage was already present within the class. 

- I did not integrate with the MediaPicker Launcher because how the form chooser intent operates is different from how the API is structured therefore the effort to integrate with it did not seem worth it at the moment. The File Chooser supports other input modes such as Camera or Video Capture. Currently, this solution does not support this as it may be better to wait until [WordPress MediaPicker Android](https://github.com/wordpress-mobile/WordPress-MediaPicker-Android)  is finalized so that a possible integration could be done. This solution will be shared there as a means of inquiring if there may be the possibility that the picker would prepare the API or clients for the use cases of the Webview's Form Chooser.  

- After completing the implementation, I thought about moving the logic into `WPWebChromeClient` inside the WordPress Utils class. I didn't get to that because I was trying to look at other groundskeeping issues. However, it seems like it would be worth the effort, I move it. However, there would need to be several changes to how the class is written to facilitate components that aren't accessible from the Utils library. 

### Forms Plugin
Create a form utilzing corresponding MIME types of any of the file types in each category to verify that the File Picker is filtering MIME types appropriately. The functionality verification should also cover single vs multiple selection.

You can utilize https://file-examples.com/ to grab sample files that match the associated MIME types.

### Create Form From Scratch
1.  Install a custom plugin like CF7: [https://wordpress.org/plugins/contact-form-7/](https://wordpress.org/plugins/contact-form-7/)
2.  Edit the default form and make sure you add a [file upload field](https://contactform7.com/file-uploading-and-attachment/)
3.  Add the CF7 block to a post or page in Calypso.
4.  Tap the 3-dots, then "Preview" in the app. 
5.  Press Choose File on the file upload field.
6.  **Expect** that you are able to select the file using the System Picker.
7. **Optional** : Send the completed form to the server.

https://user-images.githubusercontent.com/1509205/141753102-ffb0375f-f98c-4a8e-b112-0458d6560a50.mov

### Import Prexisting Form 

1.  Install Caldera Forms: [https://wordpress.org/plugins/caldera-forms/](https://wordpress.org/plugins/caldera-forms/)
2. Import the [attached form](https://gist.github.com/jd-alexander/17e6d9ca323f133ad78b7dc10314e695).
3.  Add the Caldera Form block to a post or page in Calypso.
4.  Tap the 3-dots, then "Preview" in the app. 
5.  Press Choose File on the file upload fields within the form.
6.  **Expect** that you are able to select file (s) using the System Picker.
7. **Optional** : Send the completed form to the server.

N.B some MIME types aren't filtered as expected because the accepted types implementation in Caldera Forms does not function as expected.

https://user-images.githubusercontent.com/1509205/142083390-34b18505-3d79-497d-af21-92f3f208562d.mov

## Regression Notes

1. Potential unintended areas of impact

I don't see any potential unintended areas of impact with the changes introduced. The functionality of 
`WPWebChromeClient` was extended in a manner that doesn't interfere with any of it's existing behavior.

2. What I did to test those areas of impact (or what existing automated tests I relied on)

To test I utilized two form building plugins that would be capable of creating the `input type` fields within a form that facilitate file uploads. To satisfy MIME type requirements, I carried out tests that combined different MIME types and selection params - single or multiselect. 

3. What automated tests I added (or what prevented me from doing so)

I didn't add any automated tests for this flow since we aren't currently currently testing `WPWebChromeClient`.

## Reviewing 
Only 1 reviewer is needed but anyone can review. 

## Submitter Checklist

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jd-alexander** [comment]
I just noticed that when I submit forms I am not getting the file upload even though it is attached. I don't think this should be an issue with the implementation but I will need to test again to make sure it has nothing to do with the code. If anyone wants to do a first pass, I have no problem with that 🙇🏾

**Comment by jd-alexander** [comment]
So the implementation here is fine. I was able to successfully submit an attachment that reached my email. The issue is with the Contact Form 7 and Caldera Form plugins. They have extra configurations for file attachments. 

eg, in Contact Form 7, you need to supply the field name in the Mail settings. 

plugin

For more details on this, you can visit this [tutorial](https://www.freakyjolly.com/resolved-contactform7-file-attachment-not-recieved-in-email/).

File: WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java [hunk 1]
```diff
@@ -957,4 +960,16 @@ public void onCookieProgressDialogCancelled() {
...
+
+    @Override
+    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
+        super.onActivityResult(requestCode, resultCode, data);
+        if (mWPWebChromeClientWithFileChooser != null) {
+            mWPWebChromeClientWithFileChooser.onActivityResult(requestCode, resultCode, data);
+        }
+    }
+
+    @Override public void startActivityForFileChooserResult(Intent intent, int requestCode) {
```
Comment (khaykov) [inline WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java]: This `@Override` also should probably go one line up :)

File: WordPress/src/main/java/org/wordpress/android/ui/WPWebChromeClientWithFileChooser.java [hunk 2]
```diff
@@ -0,0 +1,119 @@
...
+    private final OnShowFileChooserListener mOnShowFileChooserListener;
+
+    public WPWebChromeClientWithFileChooser(Activity activity, View view, int defaultPoster,
+                                            ProgressBar progressBar,
+                                            OnShowFileChooserListener onShowFileChooserListener) {
+        super(activity, view, defaultPoster, progressBar);
+        this.mOnShowFileChooserListener = onShowFileChooserListener;
+    }
+
+    @Override public boolean onShowFileChooser(WebView webView, ValueCallback<Uri[]> filePathCallback,
```
Comment (khaykov) [inline WordPress/src/main/java/org/wordpress/android/ui/WPWebChromeClientWithFileChooser.java]: Looks like `@Override` crept down here :)

File: WordPress/src/main/java/org/wordpress/android/ui/WPWebChromeClientWithFileChooser.java [hunk 3]
```diff
@@ -0,0 +1,119 @@
...
+        Intent intent = fileChooserParams.createIntent();
+        intent.putExtra(Intent.EXTRA_ALLOW_MULTIPLE, canMultiselect);
+
+        String[] acceptableMimeTypes = fileChooserParams.getAcceptTypes();
+        int acceptableMimeTypesLength = acceptableMimeTypes.length;
+
+        // Sets an explicit MIME data type that states that all MIME types are supported.
+        intent.setType("*/*");
+        // Creates values for Intent.EXTRA_MIME_TYPES with the MIME types that are currently acceptable.
+        String[] resolvedMimeTypes = new String[acceptableMimeTypes.length];
```
Comment (khaykov) [inline WordPress/src/main/java/org/wordpress/android/ui/WPWebChromeClientWithFileChooser.java]: I think we can use `acceptableMimeTypesLength` instead of `acceptableMimeTypes.length` here.

File: WordPress/src/main/java/org/wordpress/android/ui/WPWebChromeClientWithFileChooser.java [hunk 4]
```diff
@@ -0,0 +1,119 @@
...
+            String acceptableMimeType = acceptableMimeTypes[index];
+
+            /**
+             * The fileChooserParams.getAcceptTypes() API states that the it returns an array of acceptable MIME
+             * types. The returned MIME type could be partial such as audio/* . Currently, there are plugins that
+             * return extensions when the form input type is utilized instead of
+             *  MIME types. The logic below is to accommodate the use cases by utilizing the extension to resolve
+             *  the appropriate Mime type with MediaUtils.getMimeTypeForExtension().
+             */
+            if (acceptableMimeType.contains(".")) {
```
Comment (khaykov) [inline WordPress/src/main/java/org/wordpress/android/ui/WPWebChromeClientWithFileChooser.java]: If I understand this correctly, we check for dot here to detect mime type that is just an extension, eg. `.png`. Looks like regular mime-types can also have dots in them (eg. `application/vnd.ms-excel`), so maybe it makes sense to check if the `/` is absent (eg. `acceptableMimeType.contains(".") && !acceptableMimeType.contains("/")`)

**Review by khaykov — COMMENTED** [review]
Thanks for the investigation and a fix, @jd-alexander ! I confirmed that the file picker works, and the file is correctly uploaded using CF7. All the issues I had were related to the plugin, and not the implementation itself.

I also left a couple of minor comments in the code :)

**Comment by jd-alexander** [comment]
Thanks for the feedback @khaykov I am going to implement the changes and then do a final run thorough and then re-request a review from you 🙇🏾

File: WordPress/src/main/java/org/wordpress/android/ui/WPWebChromeClientWithFileChooser.java (hunk 4 above)
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/WPWebChromeClientWithFileChooser.java]: Good find! 152424e

File: WordPress/src/main/java/org/wordpress/android/ui/WPWebChromeClientWithFileChooser.java (hunk 3 above)
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/WPWebChromeClientWithFileChooser.java]: Makes sense 43a5c51

File: WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java (hunk 1 above)
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java]: Resolved here b0b011e

File: WordPress/src/main/java/org/wordpress/android/ui/WPWebChromeClientWithFileChooser.java (hunk 2 above)
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/WPWebChromeClientWithFileChooser.java]: Resolved here b0b011e

**Review by khaykov — APPROVED** [review]
Thanks for the changes, @jd-alexander ! Looks good to me 👍
