### PR TITLE
Fix crash in ReaderActivityLauncher

### LINKED ISSUE #20847: NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a...
Sentry Issue: [JETPACK-ANDROID-MRK](https://a8c.sentry.io/issues/5088946510/?referrer=github_integration)

```
NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
    at org.wordpress.android.ui.reader.ReaderActivityLauncher.buildShowReaderCommentsIntent(ReaderActivityLauncher.java:274)
    Intent intent = new Intent(
    at org.wordpress.android.ui.reader.ReaderActivityLauncher.showReaderComments(ReaderActivityLauncher.java:237)
    Intent intent = buildShowReaderCommentsIntent(
    at org.wordpress.android.ui.reader.ReaderActivityLauncher.showReaderComments(ReaderActivityLauncher.java:214)
    showReaderComments(
    at org.wordpress.android.ui.notifications.NotificationsListFragmentPage$handleNoteClick$1.invoke(NotificationsListFragmentPage.kt:228)
    ReaderActivityLauncher.showReaderComments(
    at org.wordpress.android.ui.notifications.NotificationsListFragmentPage$handleNoteClick$1.invoke(NotificationsListFragmentPage.kt:225)
    viewModel.openNote(
...
(17 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by aditi-bhatia**
Fixes #20847

This PR addresses a crash related to `context` being null when calling `buildShowReaderCommentsIntent()`. 

-----

## To Test:

I haven't been able to reproduce this crash, so code check + smoke test comments on the Reader.

-----

## Regression Notes

1. Potential unintended areas of impact

    - None

3. What I did to test those areas of impact (or what existing automated tests I relied on)

    - None

4. What automated tests I added (or what prevented me from doing so)

    - None
-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [ ] ~WordPress.com sites and self-hosted Jetpack sites.~
- [ ] ~Portrait and landscape orientations.~
- [ ] ~Light and dark modes.~
- [ ] ~Fonts: Larger, smaller and bold text.~
- [ ] ~High contrast.~
- [ ] ~Talkback.~
- [ ] ~Languages with large words or with letters/accents not frequently used in English.~
- [ ] ~Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)~
- [ ] ~Large and small screen sizes. (Tablet and smaller phones)~
- [ ] ~Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)~

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by irfano — COMMENTED** [review]
@aditi-bhatia, would you like to fix this using `NonNull` annotations? There are already warnings for parameters that don't have `NonNull` or `Nullable` annotations in the Java classes. When you add the `NonNull` annotation, other places that call these functions will show errors, and it also prevents calling this function with nullable parameters in the future. 

For more info: There is an internal project (paaHJt-5fa-p2) for nullability annotations that we can assist with.

image

**Comment by aditi-bhatia** [comment]
Hi @irfano, thanks for the suggestion, the lack of annotations in the codebase was also something that I was concerned about. I spent some time looking into adding `NotNull` annotations here today and just wanted to double check this part: 

> When you add the NonNull annotation, [...] prevents calling this function with nullable parameters in the future.

From what I understand, `NotNull` only provides a warning if you pass a `nullable` parameter (which is good for code quality / ease of understanding), but doesn't actually prevent `null` from being passed. For example in the code below, even though `context` is annotated `NotNull`, a warning is displayed on `line 200` but the code still runs and throws a NPE:


Screenshot 2024-05-21 at 10 16 26 PM



So from what I understand, adding `NotNull` annotations will be good for code hygiene but null checks are still required at some point to prevent an NPE, so I think it would be best to add both. What do you think? Let me know if I missed something 👍

**Comment by irfano** [comment]
I made the same change as you (added `NonNull` to lines 196 and 200), and but I received an error in `NotificationsDetailListFragment.kt` couldn't build. I'm not sure why you didn't get the same error. Probably java files show a warning while Kotlin files show errors.

<image src="https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/8348fca3-e968-4d31-b4fa-2069ffe513e8" width=600>

> but null checks are still required at some point to prevent an NPE

Yes! `NonNull` annotations don't provide fixes, but they help us find the deepest code where nulls are coming from. Eventually, we will need null checks to those places.

**Comment by aditi-bhatia** [comment]
Hi @irfano, thank you for the input 👍 I've added NonNull annotations as well as null checks in the calling functions if you'd like to take another look.

File: WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsDetailListFragment.kt [hunk 1]
```diff
@@ -255,11 +256,14 @@ class NotificationsDetailListFragment : ListFragment(), NotificationFragment {
...
-                    COMMENT_NOTIFICATION.sourceDescription
-                )
+                val maybeActivity: FragmentActivity? = activity
+                maybeActivity?.let { fragmentActivity ->
+                    ReaderActivityLauncher.showReaderComments(
+                        fragmentActivity, note.siteId.toLong(), note.postId.toLong(),
+                        note.commentId,
+                        COMMENT_NOTIFICATION.sourceDescription
+                    )
+                }
```
Comment (irfano) [inline WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsDetailListFragment.kt]:
```suggestion
                context?.let { nonNullContext ->
                    ReaderActivityLauncher.showReaderComments(
                        nonNullContext, note.siteId.toLong(), note.postId.toLong(),
                        note.commentId,
                        COMMENT_NOTIFICATION.sourceDescription
                    )
                }
```

np: Wouldn't this be simpler?

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt [hunk 2]
```diff
@@ -1580,11 +1581,14 @@ class ReaderPostDetailFragment : ViewPagerFragment(),
...
-                    DIRECT_OPERATION.sourceDescription
-                )
+                val maybeActivity: FragmentActivity? = activity
+                maybeActivity?.let { fragmentActivity ->
+                    ReaderActivityLauncher.showReaderComments(
+                        fragmentActivity, it.blogId, it.postId,
+                        directOperation, commentId.toLong(), viewModel.interceptedUri,
+                        DIRECT_OPERATION.sourceDescription
+                    )
+                }
```
Comment (irfano) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt]: np: I will make the same comment here? Just checking `context?.let {` looks simpler to me, as you also did in the `ReaderDiscoverFragment`.

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderActivityLauncher.java [hunk 3]
```diff
@@ -255,8 +255,11 @@ public static void showReaderCommentsForResult(
         showReaderCommentsForResult(fragment, blogId, postId, null, 0, null, source);
     }
 
-    public static void showReaderCommentsForResult(Fragment fragment, long blogId, long postId, DirectOperation
+    public static void showReaderCommentsForResult(@NonNull Fragment fragment, long blogId, long postId, DirectOperation
```
Comment (irfano) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderActivityLauncher.java:258]: Line 249 is calling this `showReaderCommentsForResult()` function with nullable fragment. We should also add `NonNull` annotation there.

**Review by irfano — CHANGES_REQUESTED** [review]

**Review by irfano — APPROVED** [review]
I left two nitpicking comments and one for minor request to add the `NonNull` annotation. It was like a puzzle to find all possible instances of null parameters. 😅 Thanks for your effort! I'm approving, and you can merge after considering my comments.

File: WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsDetailListFragment.kt (hunk 1 above)
Comment (aditi-bhatia) [reply WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsDetailListFragment.kt]: Thanks for the suggestion, I agree that naming is better so I've updated it 👍

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt (hunk 2 above)
Comment (aditi-bhatia) [reply WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt]: Thanks, updated 👍

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderActivityLauncher.java (hunk 3 above)
Comment (aditi-bhatia) [reply WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderActivityLauncher.java:258]: 🤦 Somehow that got removed, re-added it - thanks for the catch!

**Comment by aditi-bhatia** [comment]
Thanks for the review @irfano! I addressed the comments you made above and will go ahead and merge.
