### PR TITLE
[Reader] Fix tag posts list paging 

### LINKED ISSUE #19879: [Reader] Tag posts list not fetching new pages
### Expected behavior
When we scroll the posts list of a tag, we should continue to fetch the next pages.

### Actual behavior
When we scroll the posts list of a tag, paging stops working at some point even when there are still posts that match the filter.

### Steps to reproduce the behavior
- Install JP and sign-in
- Open "Reader"
- Select a tag
- Start scrolling: it will stop loading new posts at some point, even though there are many more (compare with web)

Another way to test is opening the tag posts list from blogging prompts card:
- Install JP and sign-in
- Open "My Site"
- Tap on "View all responses" in blogging prompts card
- Start scrolling: it will stop loading new posts at some point, even though there are many more (compare with web)

### PR DESCRIPTION
**Pull request by RenanLukas**
Fixes #19879 

We were sorting the tag related blog posts comparing `date_published` as a string instead of a date. This was causing paging not to work properly.

I've replaced `...ORDER BY date_published...` with `...ORDER BY datetime(date_published)...` in our query so the posts are sorted as dates correctly.

### Before
```
SELECT <columns> FROM tbl_posts WHERE tag_name=? AND tag_type=? ORDER BY date_published DESC
```

https://github.com/wordpress-mobile/WordPress-Android/assets/14964993/a007afc1-801d-4f21-87ab-e74a9f6130ce

### After
```
SELECT <columns> FROM tbl_posts WHERE tag_name=? AND tag_type=? ORDER BY datetime(date_published) DESC
```

https://github.com/wordpress-mobile/WordPress-Android/assets/14964993/ec7a0768-f2ad-4768-8b87-1418e9775972

-----

## To Test:
Please test this change with different SQLite versions. Also compare the results with web to make sure now we're displaying the same results using the same order.

- Install JP and sign-in
- Open "Reader"
- Select a tag
- Start scrolling: it will stop loading new posts at some point, even though there are many more (compare with web)

Another way to test is opening the tag posts list from blogging prompts card:
- Install JP and sign-in
- Open "My Site"
- Tap on "View all responses" in blogging prompts card
- Start scrolling: it will stop loading new posts at some point, even though there are many more (compare with web)

-----

## Regression Notes

1. Potential unintended areas of impact

    - SQLite function `datetime(...)` might not available in every version?

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - Manual testing

3. What automated tests I added (or what prevented me from doing so)

    --

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## UI Changes Testing Checklist:

- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by RenanLukas** [comment]
There are other places where we might also be comparing the strings instead of dates ([example](https://github.com/wordpress-mobile/WordPress-Android/pull/19881/files#diff-6698962ec7d529d03ed4128791bac7a7a2279f17bbe052d31bd8542a6a59875aR776)). Might be worth to investigate them when we can.

**Comment by RenanLukas** [comment]
This might solve the inserted items animation issue that made us [revert the updated fetched tag posts limit](https://github.com/wordpress-mobile/WordPress-Android/pull/19628). I'm submitting a PR with that change again since the performance gain was meaningful.

You might still see items being moved only the first time it loads if you already had posts for that tag in the local database.

File: WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java [hunk 1]
```diff
@@ -751,7 +751,7 @@ private static String getSortColumnForTag(ReaderTag tag) {
         } else if (tag.isTagTopic() || tag.isBookmarked()) {
             return "date_tagged";
         } else {
-            return "date_published";
+            return "datetime(date_published)";
```
Comment (thomashorta) [inline WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java:754]: ❤️ So it seems like the issue is that we store this date as a string but it has format like "2024-01-08T14:42:19+00:00", and not all posts have the same timezone, causing the order to be inconsistent since the backend actually treats the field as a date. This is a really nice catch, thanks!

💡  Also, since this is the issue, I think it makes sense to add `datetime` around the other date-related cases above (lines 746, 748, and 752), since they would suffer the same problem.

💡 Do you think it also makes sense to use the `datetime` function on other queries in this file that use a date as `order` clause? ([here](https://github.com/wordpress-mobile/WordPress-Android/blob/abc64da44acaa7df5b4f02fa69815d7f93e6bc9e/WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java#L661), [here](https://github.com/wordpress-mobile/WordPress-Android/blob/abc64da44acaa7df5b4f02fa69815d7f93e6bc9e/WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java#L668), [here](https://github.com/wordpress-mobile/WordPress-Android/blob/abc64da44acaa7df5b4f02fa69815d7f93e6bc9e/WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java#L985), [here](https://github.com/wordpress-mobile/WordPress-Android/blob/abc64da44acaa7df5b4f02fa69815d7f93e6bc9e/WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java#L1023), and [here](https://github.com/wordpress-mobile/WordPress-Android/blob/abc64da44acaa7df5b4f02fa69815d7f93e6bc9e/WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java#L1100))

**Review by thomashorta — APPROVED** [review]
Thanks for this PR, this issue has been happening to several tags and feeds and it looks like you found one of the main root causes! 🙇🏼 

I added a few suggestions regarding other date fields and other queries using sorting by date, maybe we want to fix them too.

Just a note: it's not possible to test this specific fix with the "View all responses" from Blogging Prompts after syncing this branch with `trunk`, since `trunk` already had a fix for the prompts order issue (https://github.com/wordpress-mobile/WordPress-Android/pull/19730) that solved it by making the `getSortColumnForTag` function use the `date_tagged` column (which seems to be normalized in terms of timezone).

File: WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java (hunk 1 above)
Comment (RenanLukas) [reply WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java:754]: Thanks for the review, @thomashorta !

> 💡 Also, since this is the issue, I think it makes sense to add datetime around the other date-related cases above (lines 746, 748, and 752), since they would suffer the same problem.

>💡 Do you think it also makes sense to use the datetime function on other queries in this file that use a date as order clause? ([here](https://github.com/wordpress-mobile/WordPress-Android/blob/abc64da44acaa7df5b4f02fa69815d7f93e6bc9e/WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java#L661), [here](https://github.com/wordpress-mobile/WordPress-Android/blob/abc64da44acaa7df5b4f02fa69815d7f93e6bc9e/WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java#L668), [here](https://github.com/wordpress-mobile/WordPress-Android/blob/abc64da44acaa7df5b4f02fa69815d7f93e6bc9e/WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java#L985), [here](https://github.com/wordpress-mobile/WordPress-Android/blob/abc64da44acaa7df5b4f02fa69815d7f93e6bc9e/WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java#L1023), and [here](https://github.com/wordpress-mobile/WordPress-Android/blob/abc64da44acaa7df5b4f02fa69815d7f93e6bc9e/WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java#L1100))

I agree 100%, but this also means we'd have to test every single scenario that relies on the logic you've mentioned in this same PR, right? Since this already solves the original tag post list issue, does it make sense to create a separate issue for the other places where we can thoroughly investigate and test the new changes?

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java (hunk 1 above)
Comment (thomashorta) [reply WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java:754]: That makes sense, let's make the `datetime` change for the other places in a different PR then.

Comment (RenanLukas) [reply WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java:754]: [Issue created](https://github.com/wordpress-mobile/WordPress-Android/issues/19897).
