### PR TITLE
Fix unauthenticated post view for custom domains

### LINKED ISSUE #5326: Posts: Unauthenticated webview when viewing a post from the posts list
### Expected behavior

I expect to get an authenticated webview when I select "View" on a published or draft post in the posts list.

### Actual behavior

The webview is not authenticated, so viewing a published post bumps the stats and viewing a draft leads to a 404 error.

h/t Davor for reporting this issue in the alpha version.

cc @maxme — possibly due to FluxC changes?

### Steps to reproduce the behavior

1. Open the Blog Posts section for a site.
2. Find a draft (marked "Draft" - not a local draft) in the posts list.
3. Tap "View" on the post's card. Result: 404 error.
4. Find a published post in the posts list.
5. Tap "View" on the post's card. Result: The post loads but with a logged-out view, so the view is counted in the site's stats.

##### Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-38

### PR DESCRIPTION
**Pull request by oguzkocer**
Fixes #5326. This PR updates the Fluxc hash and adds a workaround for custom domains by replacing their url with the unmapped url so we can properly authenticate them in the webview. This is somewhat a hack, but a simple one and we have not yet been able to fix it in server side. /cc @astralbodies 

To test:
* Go into the post list for a site with custom domain
* Try to view a post before the change. You should see a login page. After the change the site should load properly and you should be authenticated.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java [hunk 1]
```diff
@@ -205,6 +205,8 @@ public static void browsePostOrPage(Context context, SiteModel site, PostModel p
 
         // always add the preview parameter to avoid bumping stats when viewing posts
         String url = UrlUtils.appendUrlParameter(post.getLink(), "preview", "true");
+        // Custom domains are not properly authenticated due to a server side(?) issue, so this gets around that
+        url = url.replace(site.getUrl(), site.getUnmappedUrl());
```
Comment (aforcier) [inline WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java]: The unmapped URL can be `null` here (for example, for self hosted sites), and will cause a crash. We should probably also skip this if `getUnmappedUrl()` returns the empty string.

Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java]: This was a stupid mistake by me. This code should only run for .com sites and the `null` case should be handled. Fix incoming!

Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java]: Fixed in 3e68f0b4f76017d394f3022be2a6c652c2c99f96

**Comment by aforcier** [comment]
Looks good and works well @oguzkocer!

This fix is probably needed elsewhere in the app in some places calling `WPWebViewActivity.openUrlByUsingGlobalWPCOMCredentials()`. For example, it looks like the issue [is known here](https://github.com/wordpress-mobile/WordPress-Android/blob/cb401debe9e4aaa7be04f80e014c2babcc1516dc/WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderActivityLauncher.java#L272-L274), and should be fixable by using the unmapped URL.

I think that should be done in a separate PR - I'll open a new issue for this.

**Comment by aforcier** [comment]
Opened https://github.com/wordpress-mobile/WordPress-Android/issues/5734.

**Comment by aforcier** [comment]
:shipit:

**Comment by oguzkocer** [comment]
Thanks @aforcier!

> I think that should be done in a separate PR - I'll open a new issue for this.

Feel free to assign that to me and I'll fix it tomorrow!

**Comment by RichardHoOoOo** [comment]
May I ask several questions about this PR?
1. What the difference is between "**_unmapped url_**" and "**_url"_**? What is the return value of **_site.getUrl()_** and what is the return value of **_site.getUnmappedUrl()_**? Can anyone show me an example?
2. Why replacing url with unmapped one can authenticate webview?

**Comment by oguzkocer** [comment]
Hey @RichardHoOoOo!

1. In WordPress.com, users can have a custom domain for their sites, so for example if their WordPress. com site is `example.wordpress.com`, they can map my custom domain `example.blog`, `example.com` etc to their site. `site.getUnmappedUrl()` will return the `example.wordpress.com` url in this case, whereas the `site.getUrl()` will return the `example.com` url.
2. Custom domains normally shouldn't make a difference for the authentication, however we think a server side issue is causing one, so this is pretty much a workaround. When an authentication happens, we do so with a cookie and it looks like that cookie doesn't work with custom domains (at least in some cases). Since we know our authentication code works for any site with `*.wordpress.com` url, we are just using the unmapped url to bypass possible issues.

Hope that makes sense!

**Comment by RichardHoOoOo** [comment]
Thanks @oguzkocer !

Thank you so much for your answer, it totally make sense.
However, it seems that this workaround compromises security for functionality, as mentioned in your first comment "**_This is somewhat a hack_**". 
So could I trouble you to give me further explanation on why this can become a hack and why not fix this issue on the server side to balance security and functionality.
 
Thanks in advance!
Richard

**Comment by oguzkocer** [comment]
@RichardHoOoOo It has no implications on security, it's just a simple url swap. The reason I said "This is somewhat a hack" is that both urls point to the same site and ideally, we shouldn't need to do this. We'll look into this on the server side, but unfortunately it's not a priority. Since this is a harmless change, we didn't want our users to wait for a possible fix on the server side.

**Comment by RichardHoOoOo** [comment]
@oguzkocer Thank you for your reply!
May I ask another question? Custom domains cannot authenticate Webview, but can they authenticate other browsers like Chrome? If it can authenticate other browsers, this maybe a problem caused by Webview itself. If it cannot, it is a server side problem. 
I ask this question because I want to figure out whether this issue is webview related or not.
Thanks!

**Comment by oguzkocer** [comment]
@RichardHoOoOo This is not a browser or a webview issue, it's only related to how we handle the authentication on the server side.
