### PR TITLE
Fix #4724: update the textview unique id when comment is updated

### LINKED ISSUE #4724: Notifications: comment reply text persists to new comments (field should be empty)
#### Expected behavior

After commenting on a post from Notifications, then opening up a new comment, the comment reply field should be empty.
#### Actual behavior

The previous comment I made persists in all comment fields, even other posts or blogs.
#### Steps to reproduce the behavior
1. Open Android app
2. Click Notifications menu item
3. Click on a comment on on of your posts
4. Type a reply and click SEND action
5. Comment is added
6. Now, navigate to another comment, and see your reply text from step 4 is pre-filled in the form — instead of an empty form field
#### Tested on [device], Android [version]

Nexus 6P, Android version 7.0, WordPress Android app version alpha-25

Reference: https://make.wordpress.org/mobile/2016/10/27/call-for-testing-wordpress-for-android-6-1/

### PR DESCRIPTION
**Pull request by maxme**
Fix #4724: update the textview unique id when comment is updated

Before the fix, comment was null during `onCreateView` when CommentDetailFragment was created in Notifications.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailFragment.java [hunk 1]
```diff
@@ -364,11 +369,16 @@ private void setComment(int localBlogId, final Comment comment) {
...
             mRemoteBlogId = WordPress.wpDB.getRemoteBlogIdForLocalTableBlogId(mLocalBlogId);
+        }
 
-        if (isAdded())
+        if (isAdded()) {
             showComment();
+        }
+
+        // Reset the reply unique id since mComment just changed.
+        setReplyUniqueId();
```
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailFragment.java]: Yes, you're right! Fixed in fa7699e, I also fixed a `format(` locale problem I just noticed.

Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailFragment.java]: And fixed the same kind of String.format/locale problem in `ReaderCommentListActivity` - 85ab7ed

**Comment by nbradbury** [comment]
Looks good! :shipit:
