### PR TITLE
issue/7127 - do not call getActivity when fragment is not added.

### LINKED ISSUE #7127: Crash report 8.1-9.0.1 - NPE in EditorFragment
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
       at org.wordpress.android.editor.EditorFragment$6.run(EditorFragment.java:638)
       at java.lang.Thread.run(Thread.java:833)
```

### PR DESCRIPTION
**Pull request by khaykov**
Fixes #7127 

`IllegalEditorStateException` will be thrown when fragment `isAdded()` check fails in `getTitle()` or `getContent()`. Trying to call ` getActivity()` when fragment is not added leads to NPE.

### CODE REVIEW

File: libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragment.java [hunk 1]
```diff
@@ -635,14 +635,14 @@ public void run() {
                         getContent();
                     } catch (IllegalEditorStateException e) {
                         AppLog.e(T.EDITOR, "toggleHtmlMode: unable to get title or content");
-                        getActivity().runOnUiThread(new Runnable() {
-                            @Override
-                            public void run() {
-                                toggleButton.setChecked(false);
```
Comment (hypest) [inline libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragment.java]: Hey @khaykov , can you share some background on removing the toggling back to `false` here? In particular, is the removal on purpose?

Comment (khaykov) [reply libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragment.java]: Sure. In my understanding, at the time this code is executed fragment is already detached from activity and does not have UI (onDestroyView() was called). If and when fragment will be recreated it will be in the default state with the button unchecked.

Comment (hypest) [reply libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragment.java]: Ah, I see, makes sense, thanks!

Going a step further, `IllegalEditorStateException` has a pretty general name, implying that there might be various reasons the Editor might be in an illegal state. But at the moment, it is only thrown when the fragment is not added. I think this is rather confusing (hence my original question :) ) so, what do you think about renaming the exception class to smth like `FragmentNotAdded` perhaps?

Comment (khaykov) [reply libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragment.java]: This is a good idea :) Renamed to something more descriptive.

**Comment by hypest** [comment]
LGTM!
