### PR TITLE
Blaze: Fix view not scrolling for large font size/displays

### LINKED ISSUE #18048: [Blaze] 'Blaze a post now' button on Blaze intro overlay is not visible for big font sizes
### Expected behavior
'Blaze a post now' button on Blaze intro overlay should be always visible.

### Actual behavior
'Blaze a post now' button on Blaze intro overlay is not visible and can't be brought into view for big font sizes.

### Steps to reproduce the behavior
0. Make sure that Blaze is enabled via the debug menu
1. Selecta site that has Blaze enabled.
2. Notice that the Blaze Card is displayed.
3. Tap the Blaze Card.

### PR DESCRIPTION
**Pull request by zwarm**
Fixes #18048 

This PR fixes an issue in the Blaze overlay. The view prohibited the user from accessing the action button when using a larger font/display sizes.

- Added a scrollable box the around `BlazeOverlayContent`
- Changed `Subtitles` from a `LazyColumn` to `Column`
Note: Apologies for the "reformat code" - <shakes fist> at Android Studio.

I'm still learning Compose, so if there is a better way to do this please lmk!

**To test:**
- Install and launch the app
- Login with a wp.com account that has blaze access 
- Navigate to posts or pages list
- Choose a post/page and tap the More menu 
- From the more menu, tap "Promote with Blaze"
- ✅ Verify the overlay page is shown
- Navigate to the Device settings
- And set the display size and text to their highest settings
- Repeat the above steps
- ✅ Verify the overlay page is shown and the content is scrollable. Ensure you can see the action button

## Regression Notes
1. Potential unintended areas of impact
The blaze overlay doesn't scroll properly

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:
- [X] I have completed the Regression Notes.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/blaze/ui/blazeoverlay/BlazeOverlayFragment.kt [hunk 1]
```diff
@@ -320,16 +336,14 @@ class BlazeOverlayFragment : Fragment() {
 
     @Composable
     fun Subtitles(list: List<Int>, modifier: Modifier = Modifier) {
-        LazyColumn(
+        Column(
```
Comment (thomashorta) [inline WordPress/src/main/java/org/wordpress/android/ui/blaze/ui/blazeoverlay/BlazeOverlayFragment.kt:325]: Nice! This makes total sense to me, as this is a short list that should be always visible on the screen, and not scrollable itself. `LazyColumn` is more suited for long lists that need lazy loading / recycling as it's the equivalent of a `RecyclerView` in Compose.

File: WordPress/src/main/java/org/wordpress/android/ui/blaze/ui/blazeoverlay/BlazeOverlayFragment.kt [hunk 2]
```diff
@@ -205,6 +205,18 @@ class BlazeOverlayFragment : Fragment() {
...
+    fun ScrollableBox(uiModel: BlazeUIModel?,
+                      isDarkTheme: Boolean) {
+        Box(Modifier.fillMaxSize()) {
+            LazyColumn(Modifier.fillMaxSize()) {
+                items(1) {
+                    BlazeOverlayContent(uiModel, isDarkTheme)
+                }
+            }
+        }
+    }
```
Comment (thomashorta) [inline WordPress/src/main/java/org/wordpress/android/ui/blaze/ui/blazeoverlay/BlazeOverlayFragment.kt]: This is not needed, to add scrolling behavior to an element, you can simply make it `fillMaxSize` and add the `verticalScroll` modifier to it. See an example [here](https://github.com/wordpress-mobile/WordPress-Android/blob/20573080b5f7ed3873b83c73dab9cd669efde653/WordPress/src/main/java/org/wordpress/android/ui/jpfullplugininstall/install/compose/state/BaseState.kt#L61-L64).

Basically, all you need to do is to add those modifiers to the "root" `Column` inside of `BlazeOverlayContent` on line 147. So it will look like this:
```kotlin
Column(
    horizontalAlignment = Alignment.CenterHorizontally,
    modifier = Modifier
        .fillMaxSize()
        .verticalScroll(rememberScrollState())
        .padding(Margin.ExtraLarge.value)
) {
```

You will notice that I changed the padding to be applied at all sides now (instead of just `top`, `start`, and `end`). That's because if the content ever fills the entire screen and needs scrolling there will still be a bit of padding below the CTA button.

---

Side note: `LazyColumn` is the Compose-equivalent of `RecyclerView`, so it's better to be used only when there's a high number of items, so only what is visible is actually processed. [Extra resources about it](https://foso.github.io/Jetpack-Compose-Playground/foundation/lazycolumn/).

**Review by thomashorta — CHANGES_REQUESTED** [review]
Nice PR! Welcome to the Compose world! 😆 

I added a change request as there's a much easier and better (performance-wise) way of achieving scrolling on that screen. Let me know in case of any questions!

File: WordPress/src/main/java/org/wordpress/android/ui/blaze/ui/blazeoverlay/BlazeOverlayFragment.kt (hunk 2 above)
Comment (zwarm) [reply WordPress/src/main/java/org/wordpress/android/ui/blaze/ui/blazeoverlay/BlazeOverlayFragment.kt]: ❤️ @thomashorta 
Funny, I did start out with the following on the column ... but then I also added another LazyColumn
`modifier = Modifier
        .fillMaxSize()
        .verticalScroll(rememberScrollState())`

And that I ran into a bunch of `IllegalStateException`s. I should have realized that after I removed the `LazyColumn` for the bulleted list that it would have been fine. Thank you.

> You will notice that I changed the padding to be applied at all sides now (instead of just top, start, and end). That's because if the content ever fills the entire screen and needs scrolling there will still be a bit of padding below the CTA button.

Excellent 🙇 I was unsure if I needed to add something to preserve the space.

> Side note: LazyColumn is the Compose-equivalent of RecyclerView, so it's better to be used only when there's a high number of items, so only what is visible is actually processed.

That's what I thought too. What really threw my off was that everything was inside a single column, but the list scrolled itself, which is not what we wanted in this case. If we had treated each element as a separate row, then just using a lazyColumn would have been okay. (If I think in terms of a recyclerview).

I'll make the suggested changes now. :)

Comment (zwarm) [reply WordPress/src/main/java/org/wordpress/android/ui/blaze/ui/blazeoverlay/BlazeOverlayFragment.kt]: @thomashorta Requested changes in commit [f2da160](https://github.com/wordpress-mobile/WordPress-Android/pull/18083/commits/f2da1606237ce75a494de7ea4e7c972ebe1794a4)

Thanks again for the assistance and the :TIL opportunities. :)

**Review by thomashorta — APPROVED** [review]
Everything looks good to me! :shipit:

**Comment by AjeshRPai** [comment]
@zwarm , 

I have tested the changes, look good to me. Thanks for fixing this issue. 🙌🏼 . Approving and merging this PR. 

Thanks, @thomashorta for clarifying about the `LazyColumn`, `Column` and `rememberScrollState`.  TIL. 👏🏼 🙌🏼

**Review by AjeshRPai — APPROVED** [review]
