### PR TITLE
7.5 - Fix SecurityException in Me Fragment

### LINKED ISSUE #5818: Crash report 7.2.1: SecurityException: Permission Denial: com.google.android.apps.photos.contentprovider.MediaContentProvider
http://crashes.to/s/b4e0c187f19

```
Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:300)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.SecurityException: Permission Denial: reading com.google.android.apps.photos.contentprovider.MediaContentProvider uri content://com.google.android.apps.photos.contentprovider/0/1/mediakey%3A%2Flocal%253A7c1d3c4c-bfed-445c-a330-05ccafc1ca8f/ORIGINAL/NONE/1120761078 from pid=18359, uid=10262 requires the provider be exported, or grantUriPermission()
       at android.os.Parcel.readException(Parcel.java:1547)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)
       at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:148)
       at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:689)
       at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1080)
       at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:921)
       at android.content.ContentResolver.openInputStream(ContentResolver.java:646)
       at com.yalantis.ucrop.task.BitmapLoadTask.copyFile(BitmapLoadTask.java:198)
       at com.yalantis.ucrop.task.BitmapLoadTask.processInputUri(BitmapLoadTask.java:176)
       at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:90)
       at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:41)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

### PR DESCRIPTION
**Pull request by daniloercoli**
`Me` Fragment: Fix a `SecurityException` by downloading the "external" picture immediately, if it's not available in the media store, before starting manipulating it with UCrop.

Fixes #5818 (I hope this is the final fix for this issue).

To test:
- Open the `Me` Fragment
- Tap on the picture
- Select Gallery
- Get a picture from an external store (Google Drive)
- Make sure the picture is correctly accessed by UCrop

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.java [hunk 1]
```diff
@@ -497,7 +494,18 @@ public void onActivityResult(int requestCode, int resultCode, Intent data) {
                                     : AnalyticsTracker.Stat.ME_GRAVATAR_GALLERY_PICKED;
                     AnalyticsTracker.track(stat);
                     Uri imageUri = Uri.parse(strMediaUri);
-                    startCropActivity(imageUri);
+                    if (!MediaUtils.isInMediaStore(imageUri)) {
+                        // Download the picture. See https://github.com/wordpress-mobile/WordPress-Android/issues/5818
+                        Uri downloadedUri = MediaUtils.downloadExternalMedia(getActivity(), imageUri);
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.java]: Does calling `downloadExternalMedia` lock the main thread until it completes?

Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.java]: Never mind that. It does lock the main thread, but I thought it actually downloaded the media over the network which would've caused an ANR.

**Comment by nbradbury** [comment]
:shipit:
