### PR TITLE
Issue/7820 post uploaded snackbars

### LINKED ISSUE #7820: "Post is uploading"/"Post published"/.. snackbars not shown on Reader, Me and Notifications tabs
### Expected behavior
When the user publishes/saves/??? a post, snackbar with a message "Post is uploading"/"Post published"/"Draft saved"/??? is shown.

### Actual behavior
When the user publishes/saves/??? a post, snackbar with a message "Post is uploading"/"Post published"/"Draft saved"/??? is shown only when the user clicked on the "Create post" from the "My Site fragment (in other words it's not shown on the Reader/Me/Notifications screens).

### Steps to reproduce the behavior
1. Go to reader
2. Click on the "create post" button in the toolbar
3. Type any title
4. Click on the "Publish" button
5. Click on the "Publish now" button
6. Notice that Reader is shown, but the snackbar with
"your post is uploading" and "post published" is not shown.

Note: Previously the "new post" button was accessible only from "My Site" fragment, but currently it's accessible from the Bottom bar so the Snackbar should be shown on all these screens.

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #7820 - moves the handling of post-related snackbars from `MySiteFragment` to `WPMainActivity`.

To test: follow the steps outlined in [the issue](https://github.com/wordpress-mobile/WordPress-Android/issues/7820) and note that the snackbars appear regardless of which fragment is active.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListFragment.java [hunk 1]
```diff
@@ -236,15 +235,17 @@ public void handleEditPostResult(int resultCode, Intent data) {
         }
 
         UploadUtils.handleEditPostResultSnackbars(getActivity(),
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListFragment.java]: Just wondering - can't the post be null if `post == null` and `EXTRA_IS_DISCARDABLE` is true?
If it can't be null, I'd suggest removing the `(post == null)` check. Wdyt?

Comment (nbradbury) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListFragment.java]: I guess I simply assumed whoever wrote the original code had a reason for checking for null :) I _think_ it's possible it could be null, in which case there's no good reason to show a snackbar in the first place. I updated the code in f87224e to handle this.
