### PR TITLE
Use `CrashLogging` from `Tracks` 

### LINKED ISSUE #14513: Integrate `2.0.0` version of `Automattic-Tracks-Android`
https://github.com/Automattic/Automattic-Tracks-Android/releases/tag/2.0.0

This should result with removing [`CrashLogging`](https://github.com/wordpress-mobile/WordPress-Android/blob/70ce7de8817020d29768074bb408688436320220/WordPress/src/main/java/org/wordpress/android/util/CrashLogging.kt) class and [`Sentry` dependency](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/build.gradle#L364-L366) - we use `Tracks` to delegate `Sentry` integration

### PR DESCRIPTION
**Pull request by wzieba**
Fixes #14513 

To test:

1. Checkout this PR
2. Apply Git's Patch from the bottom of the description. It basically enables crash reports for debug builds and sends an issue to Sentry when `MySiteFragment` is created.
3. Perform assertions: open some different issue on Sentry and the new one side by side. Compare them, make sure they have the same information. Especially check that

- [ ] user informations are applied
- [ ] breadcrumbs are reported (both app's lifecycle and app's logs)
- [ ] release name is applied
- [ ] under `Additional Data` section there's `uuid`. Check that this `uuid` points to correct encrypted logs.

**Please remove the issue on the Sentry dashboard after finishing tests.**

## Regression Notes
1. Potential unintended areas of impact

Sending contentful issues to `Sentry`.

2. What I did to test those areas of impact (or what existing automated tests I relied on)

I've added unit tests for `WPCrashLoggingDataProvider` and tested this change manually. Also, the logic of the library itself [is unit and manually tested.](https://github.com/Automattic/Automattic-Tracks-Android/tree/develop/AutomatticTracks/src). Finally, the same library is used on `WCAndroid` and the team doesn't report any issues.

3. What automated tests I added (or what prevented me from doing so)

I didn't add any automated tests. I don't see a fit here for them, if you see an opportunity please ping me with an idea.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

```
Index: WordPress/src/main/java/org/wordpress/android/util/crashlogging/WPCrashLoggingDataProvider.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- WordPress/src/main/java/org/wordpress/android/util/crashlogging/WPCrashLoggingDataProvider.kt	(revision 4b3b2ec1da9d6236582845d2aba63cb600dc94c2)
+++ WordPress/src/main/java/org/wordpress/android/util/crashlogging/WPCrashLoggingDataProvider.kt	(date 1623673595234)
@@ -37,6 +37,7 @@
     }
 
     override fun crashLoggingEnabled(): Boolean {
+        return true
         if (buildConfig.isDebug()) {
             return false
         }
Index: WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.kt	(revision 4b3b2ec1da9d6236582845d2aba63cb600dc94c2)
+++ WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.kt	(date 1623673595246)
@@ -18,6 +18,7 @@
 import androidx.appcompat.widget.TooltipCompat
 import androidx.core.text.HtmlCompat
 import androidx.fragment.app.Fragment
+import com.automattic.android.tracks.crashlogging.CrashLogging
 import com.google.android.material.appbar.AppBarLayout
 import com.google.android.material.snackbar.Snackbar
 import com.wordpress.stories.compose.frame.FrameSaveNotifier.Companion.buildSnackbarErrorMessage
@@ -218,6 +219,7 @@
     @Inject lateinit var unifiedCommentsListFeatureConfig: UnifiedCommentsListFeatureConfig
     @Inject @Named(UI_THREAD) lateinit var uiDispatcher: CoroutineDispatcher
     @Inject @Named(BG_THREAD) lateinit var bgDispatcher: CoroutineDispatcher
+    @Inject lateinit var crashLogging: CrashLogging
     lateinit var uiScope: CoroutineScope
 
     private val selectedSite: SiteModel?
@@ -242,6 +244,7 @@
                     false
             )
         }
+        crashLogging.sendReport(message = "This is just a test. Remove me.")
     }
 
     override fun onDestroy() {
```

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/util/CrashLogging.kt [hunk 1]
```diff
@@ -1,172 +0,0 @@
...
-
-@Singleton
-class CrashLogging @Inject constructor(
-    private val accountStore: AccountStore,
-    private val encryptedLogging: EncryptedLogging
-) {
-    fun start(context: Context) {
-        SentryAndroid.init(context) { options ->
-            options.dsn = BuildConfig.SENTRY_DSN
-            options.cacheDirPath = context.cacheDir.absolutePath
```
Comment (wzieba) [inline WordPress/src/main/java/org/wordpress/android/util/CrashLogging.kt:30]: If you're be looking into `Automattic-Tracks-Android` sources, we don't set up `cacheDirPath` as Sentry does it on their own: https://github.com/getsentry/sentry-java/blob/6dbed692733c1f5867202b2b6c7ab33ed9f06aeb/sentry-android-core/src/main/java/io/sentry/android/core/AndroidOptionsInitializer.java#L27

File: WordPress/src/main/java/org/wordpress/android/util/CrashLogging.kt [hunk 2]
```diff
@@ -1,172 +0,0 @@
...
-            options.isEnableSessionTracking = true // Release Health tracking
```
Comment (wzieba) [inline WordPress/src/main/java/org/wordpress/android/util/CrashLogging.kt:31]: also here: it's `true` by default: https://github.com/getsentry/sentry-java/blob/90984b2ba4f2f94c723156fa73a7bb1eac8ba1d5/sentry/src/main/java/io/sentry/SentryOptions.java#L199

File: WordPress/src/main/java/org/wordpress/android/util/crashlogging/WPCrashLoggingDataProvider.kt [hunk 3]
```diff
@@ -0,0 +1,116 @@
...
+        get() = localeManager.getLocale()
+    override val releaseName: String = BuildConfig.VERSION_NAME
+    override val sentryDSN: String = BuildConfig.SENTRY_DSN
+
+    override fun applicationContextProvider(): Map<String, String> {
+        return emptyMap()
+    }
+
+    override fun crashLoggingEnabled(): Boolean {
+        if (buildConfig.isDebug()) {
```
Comment (wzieba) [inline WordPress/src/main/java/org/wordpress/android/util/crashlogging/WPCrashLoggingDataProvider.kt:40]: I use `BuildConfigWrapper` here as this is something I mock in tests. In other places, static `BuildConfig` fields are used. This results in some inconsistency but on the other hand, I'd have to add getters for all used fields in `BuildConfigWrapper` - what do you prefer?

File: WordPress/build.gradle [hunk 4]
```diff
@@ -8,7 +8,7 @@ buildscript {
         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
         classpath 'com.google.gms:google-services:4.3.8'
         classpath 'se.bjurr.violations:violation-comments-to-github-gradle-plugin:1.67'
-        classpath 'io.sentry:sentry-android-gradle-plugin:1.7.28'
+        classpath 'io.sentry:sentry-android-gradle-plugin:2.0.0'
```
Comment (wzieba) [inline WordPress/build.gradle:11]: I'm not sure if we want to update this plugin or remove it as in [this PR.](https://github.com/wordpress-mobile/WordPress-Android/pull/14798/files#diff-276cc53d974bad3212f8e1f709d32ea3f8d380c4dccb10419505d283fb41f2d7L553)

WDYT @oguzkocer ? I didn't test it but even if [we don't obfuscate but only minify ](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/build.gradle#L186)code on production, we would probably benefit from sending mapping files to Sentry. But again - it's just a guess. Could you please share your arguments in favour of removing this Gradle plugin (I understand that linked PR is just a draft so that might've been just testing).

File: WordPress/src/main/AndroidManifest.xml [hunk 5]
```diff
@@ -66,8 +66,6 @@
         android:supportsRtl="true"
         tools:ignore="UnusedAttribute">
 
-        <meta-data android:name="io.sentry.auto-init" android:value="false" />
```
Comment (wzieba) [inline WordPress/src/main/AndroidManifest.xml:69]: This will finally end in merged AndroidManifest as Track's library [has it declared](https://github.com/Automattic/Automattic-Tracks-Android/blob/2.1.0/AutomatticTracks/src/main/AndroidManifest.xml#L9-L11).

File: WordPress/build.gradle (hunk 4 above)
Comment (oguzkocer) [reply WordPress/build.gradle:11]: @wzieba That WPAndroid PR is not supposed to remove the plugin either. I've an unpublished commit where I was testing the obfuscation. I was worried about plugin not doing anything if the options are not set and I was comparing the old version behavior with and without the new plugin version. I didn't spend much time on it and where I landed was to just read the source code for the plugin to at least check what it's doing if no option is set.

While typing this comment, [I quickly had a look](https://github.com/getsentry/sentry-android-gradle-plugin/blob/main/plugin-build/src/main/kotlin/io/sentry/android/gradle/SentryPlugin.kt) and it looks like it's utilizing information from the android plugin, so we probably want to keep the plugin.

Anyhow, if you want to take over this work to update Sentry to the latest version, (and close that PR) you are more than welcome to do so. Actually, you'd be doing me a big favor 😄 🙇‍♂️

Comment (wzieba) [reply WordPress/build.gradle:11]: Ok, gotcha thanks for the context.

> (...) it looks like it's utilizing information from the android plugin

True! 

> if you want to take over this work to update Sentry to the latest version, (and close that PR)

Thanks, yeah I'll willingly take care of this 😃

**Comment by wzieba** [comment]
Hi @renanferrari @ravishanker @planarvoid 👋 are you ok with taking a look and reviewing this PR? Thanks!

File: WordPress/src/main/java/org/wordpress/android/modules/AppConfigModule.java [hunk 6]
```diff
@@ -25,9 +21,4 @@ public AppSecrets provideAppSecrets() {
     public UserAgent provideUserAgent(Context appContext) {
         return new UserAgent(appContext, WordPress.USER_AGENT_APPNAME);
     }
-
-    @Provides
-    public EncryptedLoggingKey provideEncryptedLoggingKey() {
-        return new EncryptedLoggingKey(Key.fromBytes(Base64.decode(BuildConfig.ENCRYPTED_LOGGING_KEY, Base64.DEFAULT)));
-    }
```
Comment (renanferrari) [inline WordPress/src/main/java/org/wordpress/android/modules/AppConfigModule.java]: Is there any reason why this was moved into `CrashLoggingModule`? Not saying it shouldn't, just curious :)

File: WordPress/src/main/java/org/wordpress/android/util/LogFileProviderWrapper.kt [hunk 7]
```diff
@@ -0,0 +1,13 @@
+package org.wordpress.android.util
+
+import android.content.Context
+import org.wordpress.android.util.helpers.logfile.LogFileProvider
+import javax.inject.Inject
+
+class LogFileProviderWrapper @Inject constructor(context: Context) {
+    val logFileProvider = LogFileProvider.fromContext(context)
```
Comment (renanferrari) [inline WordPress/src/main/java/org/wordpress/android/util/LogFileProviderWrapper.kt]: This can probably be private?

```suggestion
    private val logFileProvider = LogFileProvider.fromContext(context)
```

File: WordPress/src/main/java/org/wordpress/android/util/crashlogging/WPCrashLoggingDataProvider.kt (hunk 3 above)
Comment (renanferrari) [reply WordPress/src/main/java/org/wordpress/android/util/crashlogging/WPCrashLoggingDataProvider.kt:40]: Using `BuildConfigWrapper` only when needed for testing is probably the way I'd do it too 👍

File: WordPress/src/test/java/org/wordpress/android/util/crashlogging/WPCrashLoggingDataProviderTest.kt [hunk 8]
```diff
@@ -0,0 +1,179 @@
...
+    fun `should correctly reads and maps user`() {
+        whenever(accountStore.account).thenReturn(TEST_ACCOUNT)
+
+        val user = sut.userProvider()
+
+        SoftAssertions().apply {
+            assertThat(user?.username).isEqualTo(TEST_ACCOUNT.userName)
+            assertThat(user?.email).isEqualTo(TEST_ACCOUNT.email)
+            assertThat(user?.userID).isEqualTo(TEST_ACCOUNT.userId.toString())
+        }.assertAll()
```
Comment (renanferrari) [inline WordPress/src/test/java/org/wordpress/android/util/crashlogging/WPCrashLoggingDataProviderTest.kt]: TIL about `SoftAssertions`! I used to do something similar using Truth, but I didn't know this was possible with AssertJ.

**Review by renanferrari — COMMENTED** [review]
Hey @wzieba 👋 This PR finally gave me a chance to look at the improvements you made to the Tracks library and I really like what I see, thank you for working on that!

I've tested the app with the patch you provided and everything seems to be working as expected. 

As for the code, it looks pretty good overall! I just left a few minor comments below.

File: WordPress/src/main/java/org/wordpress/android/modules/AppConfigModule.java (hunk 6 above)
Comment (wzieba) [reply WordPress/src/main/java/org/wordpress/android/modules/AppConfigModule.java]: My motivation was that logs are encrypted only for crash logging but after revisiting this, I don't think that it should be in a common module - those are in the end two separate features. And probably in the future, we'll want to encrypt logs when sending e.g. Zendesk ticket too.

Good point, thanks! Moved back in 87a7de72ae34a999ea5712c3a6475367d150fdcb

File: WordPress/src/main/java/org/wordpress/android/util/LogFileProviderWrapper.kt (hunk 7 above)
Comment (wzieba) [reply WordPress/src/main/java/org/wordpress/android/util/LogFileProviderWrapper.kt]: True, fixed in a180062769ac8b6ffb1e37fba808e84bf0504185

File: WordPress/src/test/java/org/wordpress/android/util/crashlogging/WPCrashLoggingDataProviderTest.kt (hunk 8 above)
Comment (wzieba) [reply WordPress/src/test/java/org/wordpress/android/util/crashlogging/WPCrashLoggingDataProviderTest.kt]: True, `SoftAssertion` is a cool idea, I really like it!

I just remembered - it's quite easy to forget about calling `assertAll()` at the end, when using Kotlin's `apply`. In 7c7b1a32f12a10d168e34ccf67f958729e79e495 I've moved to use `assertSoftly` which is a static function provided by AssertJ that does the same but with no need to call `assertAll()`.

**Comment by wzieba** [comment]
Thank you for the review @renanferrari ! I've applied your suggestions, ready for the second round :)

**Review by renanferrari — APPROVED** [review]
Thanks for the changes!

LGTM :shipit:
