### PR TITLE
Fix media upload error notifications & local Urls on Aztec

### LINKED ISSUE #9159: Editor: Media image upload and publish error even though upload was successful
### Expected behavior
For the media image to upload and publish without reporting an error

### Actual behavior
Post and included image uploads correctly but still produces an error on the device saying file not uploaded.

### Steps to reproduce the behavior
STEPS TO REPRODUCE BEHAVIOUR
1) I set myself up as a beta tester on the Android app Beta 11.6
2) I used ricksstoretestsite.home.blog as the test platform.
3) I first tried uploading an image to the page titled "test 4". (https://ricksstoretestsite.home.blog/test-4/)
4) The image uploaded to the page. 
5) Clicked update
6) In the device notifications, it showed the scrolling upload arrow icon but then produced an error triangle next to it with the message "Upload failed". 
When I pulled down the notifications tab this is what it showed - Screenshot here - https://screenpresso.com/=LwGrd
7) When I went back into the same page on the device the image appeared to be there correctly published.
8) To double check, I loaded the same page on my desktop computer and the page appeared with the image correctly as well. 
9) To test this further, I tried the same steps on a post rather than a page to see if it made any difference. The post is called "Test post img" (https://ricksstoretestsite.home.blog/2019/01/30/test-post-img/)
10) I uploaded the same image and published it again getting the same error.
11) I checked again on my desktop and the post was there.
12) I tried a few more tests on the same pages but it produced the same results as above.

##### Tested on [device], Android [version]
Samsung S9 with Android 8.0.0

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #9159 along with other general error notification / Posting issues

### Foreword: How the UploadService currently works
The `UploadService` will always re-create the notifications once any of the states is updated (for example, if a failed post is re-tried and ends up successfully, the service will run again through _all_ failed Posts and re-create the error notifications for those. This happens in method `doFinalProcessingOfPosts()` within the Service). This means that even if you dismiss them, but then upload something else (a new post or anything), chances are the Service will also create the error notifications for the failed Posts reminding that there's something to care about; as well as indicate the success for the recently uploaded Post (also note, the success notification is only shown when the app is not on the foreground).
This is probably a behavior that we may want to get revisited, but may imply a more complex mechanism of detection of changes (i.e. do we want to delete notifications if the user dismissed them already? how do we know if a Post has failed, then was fixed, but then failed again - do we notify the user in that case?, etc.)

#### A) Make different error notification id for different failed local drafts

What was happening here regarding the described issue, as reported by @rachelmcr elsewhere:

> When I try to share media to the app I am now consistently seeing the issue reported here with the upload failed message: 
... (see #9159)

and

> Several upload attempts actually failed first, so that could be a factor in the failed upload message continuing to appear; I’m not sure about that.

This ˆˆˆ. 

The error notifications for media for local drafts were using a local ID that was being re-used. If you had 2 local drafts (that is, drafts that couldn't be uploaded to the server), then due to this bug there would only be _one_ error notification for the _latest_ post to have failed (first we'd generate an error notification for the first Post, then for the second, but using the same id, thus giving the impression the latest Post failed). Using step by step debugging, I could verify we were rather updating the same notification on each pass, rather than generating a different notification for each failed Post/media.

This was fixed in commit  25747a9. Steps to both reproduce the issue and test this PR fixes the bug are shown below.

This other case was only happening when sharing media to the WP app, choosing media section and choosing a site other than the one selected in the app. This is fixed in dd6cb03.

#### C) Local URL within Aztec posts with media
This is something I saw while doing tests, and is quite an important issue. When you draft and add an image to a Post and finish uploading successfully, the Post on the web contained the local URL for the media file on the Android OS instead of using the remote, because of a bad check when introducing Gutenberg that affected the condition being checked.

This was fixed in f7ecaf7.

### To test:
All of this should be done with Aztec enabled - that is, make sure you have the Gutenberg setting (Use Block Editor) set to `off`, except for CASE C, where both ON and OFF should be tested.

#### CASE A: error notification showing error for wrong Post 
(latest Post even if it was successfully uploaded, as long as there were previous failed Posts).

1. start a draft, title it "Test 1".
2. add an image
3. tap back
4. turn airplane mode ON (this will make neither the media or the enqueued Post finally reach the server, even when it started to upload).
5. observe the post is marked as failed, and the error notification appears with the right Post title. Technically this ends with a local draft with failed media in our local db.

now, still leaving airplane mode ON:

6. start a new draft and title it "Test 2".
7. insert an image
8. (PREVIOUSLY) observe the notification is reset (shows now `Upload failed for "Test 1" (1 file not uploaded)`.
8. (NOW) observe there's a new notification, one for each of the failed Posts, that show the right title for each.

What was happening here is what I described above, regarding the error notification Id being re-used and thus wrongly updated.

now, let's continue, still leaving airplane mode ON as well:

9. now, open the Photos app and share an image to WP.
10. select a site _different than the one you were using_, and create new Post.
11. this will create a new failed local draft.

12. (PREVIOUSLY) observe how there are 2 notifications: one that is just for the last failed post for the app's selected site, and another one for the shared media that failed, that also shows the wrong site name (shows the app's selected site name instead of the site for which we chose to create this Post on).
12. (NOW) observe there's 3 notifications: one for each failed post, and another one for the failed media.

finally, let's continue, this time set airplane mode OFF, and:

13. start a new draft
14. add an image
15. exit the editor before the image finishes uploading and see how it continues to upload, and the Post is enqueued to upload as well.
16. let it finish
17. observe it finishes alright, and the error notifications for the rest of the Posts still are the same. Also note the error snackbar will be shown on the main screen, as there are still outstanding failed Posts as informed by the UploadService (this is OK given the current behavior described above).

#### CASE B: error notification showing error for wrong Site
1. share an image to WP Android
2. select a site other than the currently selected in the app
3. tap on Add to Media Library
4. once the upload starts, turn airplane mode ON.
5. observe a new error notification is displayed, saying "Upload failed for _correct_sitename_", with "1 file not uploaded" as a subtext.

#### CASE C: no local urls in Posts
1. share an image to WP Android, or start a new draft and add an image
2. tap Back to exit the editor
3. once the upload finishes, make sure to open it on the web and see the image is correctly displayed
4. also, view the HTML view for the post on the web and verify the image URL starts with `http`.

cc @jtreanor @rachelmcr 🙇 

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by Skittocomilla** [comment]
Foreword: How the UploadService currently works
The UploadService will always re-create the notifications once any of the states is updated (for example, if a failed post is re-tried and ends up successfully, then service will run again through all failed Posts and re-create the error notifications for those. This happens in method doFinalProcessingOfPosts() within the Service). This means that even if you dismiss them, but then upload something else (a new post or anything), chances are the Service will also create the error notifications for the failed Posts reminding that there's something to care about; as well as indicate the success for the recently uploaded Post (also note, the success notification is only shown when the app is not on the foreground).
This is probably a behavior that we may want to get revisited, but may imply a more complex mechanism of detection of changes (i.e. do we want to delete notifications if the user dismissed them already? how do we know if a Post has failed, then was fixed, but then failed again - do we notify the user in that case?, etc.)

Fixes made in this PR
A) Make different error notification id for different failed local drafts
What was happening here regarding the described issue, as reported by @rachelmcr elsewhere:

When I try to share media to the app I am now consistently seeing the issue reported here with the upload failed message:
... (see #9159)

and

Several upload attempts actually failed first, so that could be a factor in the failed upload message continuing to appear; I’m not sure about that.

This ˆˆˆ.

The error notifications for media for local drafts were using a local ID that was being re-used. If you had 2 local drafts (that is, drafts that couldn't be uploaded to the server), then due to this bug there would only be one error notification for the latest post to have failed (first we'd generate an error notification for the first Post, then for the second, but using the same id, thus giving the impression the latest Post failed). Using step by step debugging, I could verify we were rather updating the same notification on each pass, rather than generating a different notification for each failed Post/media.

This was fixed in commit 25747a9. Steps to both reproduce the issue and test this PR fixes the bug are shown below.

B) Wrong site name for failed media shared to the app
I also noticed that the upload failed message will always show the site title for the site I selected in the app, even if that isn’t the site that the media is being uploaded to.

This other case was only happening when sharing media to the WP app, choosing media section and choosing a site other than the one selected in the app. This is fixed in dd6cb03.

C) Local URL within Aztec posts with media
This is something I saw while doing tests, and is quite an important issue. When you draft and add an image to a Post and finish uploading successfully, the Post on the web contained the local URL for the media file on the Android OS instead of using the remote, because of a bad check when introducing Gutenberg that affected the condition being checked.

This was fixed in f7ecaf7.

To test:
All of this should be done with Aztec enabled - that is, make sure you have the Gutenberg setting (Use Block Editor) set to off, except for CASE C, where both ON and OFF should be tested.

CASE A: error notification showing error for wrong Post
(latest Post even if it was successfully uploaded, as long as there were previous failed Posts).

start a draft, title it "Test 1".
add an image
tap back
turn airplane mode ON (this will make neither the media or the enqueued Post finally reach the server, even when it started to upload).
observe the post is marked as failed, and the error notification appears with the right Post title. Technically this ends with a local draft with failed media in our local db.
now, still leaving airplane mode ON:

start a new draft and title it "Test 2".
insert an image
(PREVIOUSLY) observe the notification is reset (shows now Upload failed for "Test 1" (1 file not uploaded).
(NOW) observe there's a new notification, one for each of the failed Posts, that show the right title for each.
What was happening here is what I described above, regarding the error notification Id being re-used and thus wrongly updated.

now, let's continue, still leaving airplane mode ON as well:

now, open the Photos app and share an image to WP.

select a site different than the one you were using, and create new Post.

this will create a new failed local draft.

(PREVIOUSLY) observe how there are 2 notifications: one that is just for the last failed post for the app's selected site, and another one for the shared media that failed, that also shows the wrong site name (shows the app's selected site name instead of the site for which we chose to create this Post on).

(NOW) observe there's 3 notifications: one for each failed post, and another one for the failed media.

finally, let's continue, this time set airplane mode OFF, and:

start a new draft
add an image
exit the editor before the image finishes uploading and see how it continues to upload, and the Post is enqueued to upload as well.
let it finish
observe it finishes alright, and the error notifications for the rest of the Posts still are the same. Also note the error snackbar will be shown on the main screen, as there are still outstanding failed Posts as informed by the UploadService (this is OK given the current behavior described above).
CASE B: error notification showing error for wrong Site
share an image to WP Android
select a site other than the currently selected in the app
tap on Add to Media Library
once the upload starts, turn airplane mode ON.
observe a new error notification is displayed, saying "Upload failed for correct_sitename", with "1 file not uploaded" as a subtext.
CASE C: no local urls in Posts
share an image to WP Android, or start a new draft and add an image
tap Back to exit the editor
once the upload finishes, make sure to open it on the web and see the image is correctly displayed
also, view the HTML view for the post on the web and verify the image URL starts with http.
cc @jtreanor @rachelmcr 🙇

Update release notes:

 If there are user facing changes, I have added an item to RELEASE-NOTES.txt.

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadNotifier.java [hunk 1]
```diff
@@ -426,10 +426,18 @@ void updateNotificationSuccessForMedia(@NonNull List<MediaModel> mediaList, @Non
     }
 
     public static long getNotificationIdForPost(PostModel post) {
-        long remotePostId = post.getRemotePostId();
+        long postIdToUse = post.getRemotePostId();
+        if (post.isLocalDraft()) {
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadNotifier.java]: I wonder if there could be the case where a local draft on the device, and a remote post, can get the same ID, since the ID is returned from 2 different sources.

Say, on self hosted blogs, where remote post ID start from 1 -  It's unlikely, but there could be a case where two different posts, both with media errors, can have the same ID. The first that comes from the local DB, and the second form the remote. Just wanted to point this out, not meaning to fix it in this PR.

Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadNotifier.java]: That's totally a fair concern, thanks for pointing that out so it's written somewhere - it's true that these IDs can in theory overlap, however the chances are too low so it seems it should work in practically 100% of times. Do you think maybe adding a comment in the code would be good, to alert future selves just in case?

Comment (daniloercoli) [reply WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadNotifier.java]: Yes, I think that just a short comment is OK.

Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadNotifier.java]: 👌 addressed in 928a6501dd
