### PR TITLE
Fixed missing tracks for error notifications

### LINKED ISSUE #12063: Add tracking for missing intent entry points
### Expected behavior
Events for system notification `tap`, `dismiss` and `show` for post upload success and error are being tracked, as well as any other intent that lands in WPMainActivity. The same should happen for any other entry point (not just the main activity)

### Actual behavior
However I've found there are missing tracks calls for notifications whose PendingIntent targets are i.e. `tap` for:
- MediaBrowserActivity (i.e. NotificationType.MEDIA_UPLOAD_ERROR),
- PostsListActivity and PagesActivity (see getNotificationIntent() in PostUploadNotifier) for NotificationType.POST_UPLOAD_ERROR.

There may be more.

### Steps to reproduce the behavior
1. Try to make  an post upload fail (for example when an upload is in progerss, switch airplane mode ON)
2. observe the error notification is shown
3. tap on it
4. observe there is no logcat entry for `notification_tapped` as otherwise indicated in original PR https://github.com/wordpress-mobile/WordPress-Android/pull/10679

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #12063

For a reference, check original PR in https://github.com/wordpress-mobile/WordPress-Android/pull/10679

- When a post/page upload or media upload resulted in an error notification being shown, these notifications were not being properly tracked.
This PR fixes that, by checking the proper `ARG_NOTIFICATION_TYPE` in `onNewIntent` in the related activities (it was being set properly in the upload service and related classes, but not used when intended).

~- While at it, also fixed an issue in b739754305: tracking code was only being called for new instances of WPMainActivity, when it should really have been the case for new intents to always get tracked.~  reverted in cef1846da7

### To test:
**CASE A: Post list**
1. start writing a Post
2. add a local video
3. exit the editor while it's uploading
4. send the app to the background so the notification will appear when needed (see next steps)
5. turn airplane mode ON
6. the error notification that the upload couldn't be made appears
7. tap on the error notification
8. observe the call to `trackTappedNotification` gets executed

Variant: try creating the post from the Post list or from the Main activity, results should be the same (special case is when the Posts list it still instantiated, so don't go back to the Main activity in step 4 to let it sit there).

**CASE B: Pages** 
Follow the same steps above but create a Page instead.

**CASE C: Media**
1. go to the Media section of the site / app
2. tap on the + button to create a media item and upload
3. select choose video from device
4. tap on a video
5. while the video is uploading, exit the activity
6. now send the app to the background
7. turn airplane mode ON
8. wait for the error notification to appear
9. tap on it
10. observe the call to `trackTappedNotification` gets executed

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by oguzkocer** [comment]
Hi there! `15.1` is being frozen, so this PR is being bumped to `15.2`. If these changes _have to_ be shipped with `15.1`, please target `release/15.1` and cc me in the PR so I can cut a new beta release. Also if you can keep the release dates in mind and bump the PRs & issues you are working on before the code freeze date, we'd really appreciate it.

_This is a standard release version bump message. Let me know if you have any feedback._

File: WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java [hunk 1]
```diff
@@ -257,11 +257,6 @@ public void run() {
             }
 
             if (FluxCUtils.isSignedInWPComOrHasWPOrgSite(mAccountStore, mSiteStore)) {
-                NotificationType notificationType =
-                        (NotificationType) getIntent().getSerializableExtra(ARG_NOTIFICATION_TYPE);
-                if (notificationType != null) {
-                    mSystemNotificationsTracker.trackTappedNotification(notificationType);
-                }
                 // open note detail if activity called from a push
```
Comment (develric) [inline WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java:260]: Maybe I'm missing something, but I think we should not remove this one. If I'm not making things wrong, I tried triggering a notification for a comment related to a followed site and in that case I do not get the tap track I suspect because we removed this one; getting something like:

```
🔵 Tracked: notification_tapped_segmented_control, Properties: {"selected_filter":"all"}
🔵 Tracked: notification_tapped_segmented_control, Properties: {"selected_filter":"all"}
```

Expecting something like:

```
🔵 Tracked: notification_tapped, Properties: {"notification_type":"comment"}
🔵 Tracked: notification_tapped_segmented_control, Properties: {"selected_filter":"all"}
🔵 Tracked: notification_tapped_segmented_control, Properties: {"selected_filter":"all"}
```

File: WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java [hunk 2]
```diff
@@ -500,6 +495,16 @@ protected void onNewIntent(Intent intent) {
...
+
+        if (FluxCUtils.isSignedInWPComOrHasWPOrgSite(mAccountStore, mSiteStore)) {
+            if (intent.hasExtra(ARG_NOTIFICATION_TYPE)) {
+                NotificationType notificationType =
+                        (NotificationType) intent.getSerializableExtra(ARG_NOTIFICATION_TYPE);
+                if (notificationType != null) {
+                    mSystemNotificationsTracker.trackTappedNotification(notificationType);
+                }
+            }
+        }
```
Comment (develric) [inline WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java:507]: this seems safe enough...TBH could not find the path that can trigger this code 🙃 ...happy to learn in case you want to share, thanks 🙇‍♂️

File: WordPress/src/main/java/org/wordpress/android/ui/pages/PagesActivity.kt [hunk 3]
```diff
@@ -36,6 +42,12 @@ class PagesActivity : LocaleAwareActivity(),
     }
 
     private fun handleIntent(intent: Intent) {
+        if (intent.hasExtra(ARG_NOTIFICATION_TYPE)) {
+            val notificationType: NotificationType =
+                    intent.getSerializableExtra(ARG_NOTIFICATION_TYPE) as NotificationType
+            systemNotificationTracker.trackTappedNotification(notificationType)
```
Comment (develric) [inline WordPress/src/main/java/org/wordpress/android/ui/pages/PagesActivity.kt:48]: I'm getting an error here for `systemNotificationTracker` not being initialized. I think we are missing to declare this activity Injectable (something like `void inject(PagesActivity object);` in `AppComponent.java`) and actually inject it (in this activity onCreate something like `(application as WordPress).component().inject(this)`); let me know wdyt 😊

**Comment by oguzkocer** [comment]
Hi there! `15.2` is being frozen, so this PR is being bumped to `15.3`. If these changes _have to_ be shipped with `15.2`, please target `release/15.2` and cc me in the PR so I can cut a new beta release. Also if you can keep the release dates in mind and bump the PRs & issues you are working on before the code freeze date, we'd really appreciate it.

**Comment by oguzkocer** [comment]
@mzorz @develric  This issue is being bumped a second time without any updates. Could you please either merge it until the next code freeze or update the milestone manually and document the blocker for it? Thank you!

---

Hi there! `15.3` is being frozen, so this PR is being bumped to `15.4`. If these changes _have to_ be shipped with `15.3`, please target `release/15.3` and cc me in the PR so I can cut a new beta release. Also if you can keep the release dates in mind and bump the PRs & issues you are working on before the code freeze date, we'd really appreciate it.

_This is a standard release version bump message. Let me know if you have any feedback._

**Comment by mzorz** [comment]
> @mzorz @develric This issue is being bumped a second time without any updates. Could you please either merge it until the next code freeze or update the milestone manually and document the blocker for it? Thank you!

Hi @oguzkocer ! This PR was a side contribution made in the last bit of HACK week and I was planning on following up with @develric's comments, but got busy with stories alpha, hence deprioritized this one in my ToDo list since this is not even a blocker. Should have made a comment about that here, getting back at it now 👍

**Comment by oguzkocer** [comment]
@mzorz No worries about keeping a PR open but not getting to work on it. We just need to document our intentions in the PR for others, in this case release managers, to see. For example, it'd be totally fine to remove the milestone, convert the PR to a draft and add a comment saying "This is not a priority right now, so will work on it when I can". Hope that makes sense!

**Comment by mzorz** [comment]
Your point about communication is clear @oguzkocer 👍

File: WordPress/src/main/java/org/wordpress/android/ui/pages/PagesActivity.kt (hunk 3 above)
Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/pages/PagesActivity.kt:50]: 🤦 fixed this in c23e3bf3b9

File: WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java (hunk 2 above)
Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java]: Been testing this more extensively than I did when creating the issue / PR and found out to my surprise, that onCreate() in WPMainActivity is always called upon tapping on each new comment / comment like notification, thus the tracks information was good.
I was under the (wrong) impression that new intents from tapping on the notifications would bring the existing Activity to the foreground instead of creating a new instance every time, but turns out [`showWPComNotificationForBuilder()`](https://github.com/wordpress-mobile/WordPress-Android/blob/79ec027b58af46b6eb379e4fb6d5126c68720727/WordPress/src/main/java/org/wordpress/android/push/GCMMessageHandler.java#L732) will be passing these flags to the intent:
```
            resultIntent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP | Intent.FLAG_ACTIVITY_NEW_TASK
                                  | Intent.FLAG_ACTIVITY_CLEAR_TASK);
```
Effectively this means creating a new WPMainActivity each time, and hence removing the code from `onCreate` and adding it to `onNewIntent` would incur in this new problem. Thank you for digging into this thoroughly @develric , and apologies for not testing this myself in the first place.

This change was reverted in cef1846da7 so, should be good for another pass now 👍

File: WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java (hunk 1 above)
Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java]: totally spot on @develric - more on this in https://github.com/wordpress-mobile/WordPress-Android/pull/12184#discussion_r453871238

**Comment by mzorz** [comment]
Ready for another round @develric - this time keeping the PR constrained to fixing what the issue describes 👍 🙇

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.kt [hunk 4]
```diff
@@ -177,7 +181,6 @@ class PostsListActivity : LocaleAwareActivity(),
 
         quickStartEvent = savedInstanceState?.getParcelable(QuickStartEvent.KEY)
     }
-
```
Comment (develric) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.kt:180]: This is only a np, but maybe this line was removed inadvertently?

Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.kt:180]: oh you're right! added it back in 9602501bba 🙏
