### PR TITLE
Reader - translate default tag strings

### LINKED ISSUE #5240: Reader: Menu items are not Translated
### Expected Behavior:
The Discover section should load in Spanish.

### Actual Behavior:
Discover module loads with English strings.

### Steps to reproduce the behavior:

1. Switch the app locale UI to Spanish (es)
2. Click the Reader icon
3. Reader menu items (Discover, Followed Sites, Posts I Like) shows in English

image

Tested on a Blu studio selfie phone, Android 5.1

### PR DESCRIPTION
**Pull request by tonyr59h**
Fixes #5240 

~The fix requires making `setTagTitle` public but that seems harmless.~ I've included Spanish translations (that someone should check! cc @mzorz) to help test.

To test:
* Go to App Setting and change language to/away Spanish
* Verify tags are translated on Reader tab
* Go to App Settings and change language back
* Verify tags again

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java [hunk 1]
```diff
@@ -1572,6 +1572,20 @@ public LoadTagsTask(FilteredRecyclerView.FilterCriteriaAsyncLoaderListener liste
         @Override
         protected ReaderTagList doInBackground(Void... voids) {
             ReaderTagList tagList = ReaderTagTable.getDefaultTags();
+
+            // translate default tags
+            // ref: https://github.com/wordpress-mobile/WordPress-Android/issues/5240
+            Context context = getContext();
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java]: This seems fragile since it's changing the title in a single place for a single purpose. It may work better to do this in `ReaderTag.getLabel()`, since the purpose of that method is to return the tag name for display. Example:

```
@Override
public String getLabel() {
    if (tagType == ReaderTagType.DEFAULT) {
        // translate default tags
        // ref: https://github.com/wordpress-mobile/WordPress-Android/issues/5240
        if (isDiscover()) {
            return WordPress.getContext().getString(R.string.reader_discover_default_tag);
        } else if (isFollowedSites()) {
            return WordPress.getContext().getString(R.string.reader_followed_default_tag);
        } else if (isPostsILike()) {
            return WordPress.getContext().getString(R.string.reader_liked_default_tag);
        } else {
            return getTagTitle();
        }
    } else if (isTagDisplayNameAlphaNumeric()) {
        return getTagDisplayName().toLowerCase();
    } else if (hasTagTitle()) {
        return getTagTitle();
    } else {
        return getTagDisplayName();
    }
}
```

**Comment by tonyr59h** [comment]
Thanks for the review! I originally intended to place the translation work in `ReaderTag` but had no `Context` and totally forgot we had one available via `WordPress`.

**Comment by nbradbury** [comment]
Code looks good - feel free to :shipit: once the Spanish strings have been approved.

**Comment by mzorz** [comment]
Spanish looks good! Quite accurate 👌 :)
Going to test it before giving it the go

**Comment by mzorz** [comment]
Works like a charm! :shipit:
