### PR TITLE
[Revamp Landing Screen] Jetpack App - Ignore background and animated text by screen readers

### LINKED ISSUE #17313: [Revamp Landing Screen] JPAndroid - Voice Assistant announces background image and animated texts
### Expected

Animated text should not be read by Voice Assistant since it's decorative.
Same rationale applies to the gradient background image behind it.

### Actual

Voice Assistant reads the animated text and announces the background image when focused.

### Repro Steps

1. Make sure `LandingScreenRevamp` feature flag is enabled

<details>
<summary>How to Enable the <code>LandingScreenRevamp</code> feature flag</summary>

- Either `login` → `Me` → `App Settings` → `Debug Settings` → enable `LandingScreenRevamp` → `RESTART THE APP` → `logout` or
- Apply this hard-coded solution:

<details>
<summary>Patch to enable the <code>LANDING_SCREEN_REVAMP</code> build flag</summary>

```diff
diff --git a/WordPress/build.gradle b/WordPress/build.gradle
index 63260a4ca8..fe999fa92f 100644
--- a/WordPress/build.gradle
+++ b/WordPress/build.gradle
@@ -112,7 +112,7 @@ android {
         buildConfigField "boolean", "READER_COMMENTS_MODERATION", "false"
         buildConfigField "boolean", "SITE_INTENT_QUESTION", "true"
         buildConfigField "boolean", "SITE_NAME", "false"
-        buildConfigField "boolean", "LANDING_SCREEN_REVAMP", "false"
+        buildConfigField "boolean", "LANDING_SCREEN_REVAMP", "true"
         buildConfigField "boolean", "LAND_ON_THE_EDITOR", "false"
         buildConfigField "boolean", "BLOGGING_PROMPTS", "false"
         buildConfigField "boolean", "QUICK_START_EXISTING_USERS_V2", "false"
```  
</details>

---

</details>

2. Launch Jetpack App and make sure you're logged out
3. On your device go to `Settings` → `Accessibility` → enable `Voice Assistant`
4. Return to the Login screen on the Jetpack App
5. Slide right to read next item on the screen
6. Notice **Jetpack background image** is announced
7. Slide right to read next item on the screen
8. **Notice** the prompts displayed with large text are read
9. Sliding right again will read the prompts again

### PR DESCRIPTION
**Pull request by ovitrif**
Fixes #17313

To test:

<details>
<summary><b>Prerequisite</b> - Enable the <code>LandingScreenRevamp</code> feature flag</summary>

- Either `login` → `Me` → `App Settings` → `Debug Settings` → enable `LandingScreenRevamp` → `RESTART THE APP` → `logout` or
- Apply this hard-coded solution:

<details>
<summary>Patch to enable the <code>LANDING_SCREEN_REVAMP</code> build flag</summary>

```diff
diff --git a/WordPress/build.gradle b/WordPress/build.gradle
index 63260a4ca8..fe999fa92f 100644
--- a/WordPress/build.gradle
+++ b/WordPress/build.gradle
@@ -112,7 +112,7 @@ android {
         buildConfigField "boolean", "READER_COMMENTS_MODERATION", "false"
         buildConfigField "boolean", "SITE_INTENT_QUESTION", "true"
         buildConfigField "boolean", "SITE_NAME", "false"
-        buildConfigField "boolean", "LANDING_SCREEN_REVAMP", "false"
+        buildConfigField "boolean", "LANDING_SCREEN_REVAMP", "true"
         buildConfigField "boolean", "LAND_ON_THE_EDITOR", "false"
         buildConfigField "boolean", "BLOGGING_PROMPTS", "false"
         buildConfigField "boolean", "QUICK_START_EXISTING_USERS_V2", "false"
```  
</details>

---

</details>

0. On your device go to `Settings` → `Accessibility` → enable `Voice Assistant`
1. Open the Jetpack app and make sure you're logged out
2. Slide right to read next item on the screen
3. **Expect** the screen reader to read the first button
4. Slide right again to read next item on the screen
5. **Expect** the screen reader to read the second button

## Regression Notes
1. Potential unintended areas of impact
  N/a

2. What I did to test those areas of impact (or what existing automated tests I relied on)
  N/a

3. What automated tests I added (or what prevented me from doing so)
  N/a

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/components/RepeatingColumn.kt [hunk 1]
```diff
@@ -24,7 +25,7 @@ fun RepeatingColumn(
 ) {
     Layout(
             content = {
-                Column(modifier = modifier) {
+                Column(modifier.clearAndSetSemantics {}) {
```
Comment (mkevins) [inline WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/components/RepeatingColumn.kt]: I was thinking it might be better to leave this as is, and instead add `clearAndSetSemantics` to the `LoopingTextWithBackground`, since that makes this component more reusable. Wdyt?

File: WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/components/LoopingTextWithBackground.kt [hunk 2]
```diff
@@ -23,13 +22,15 @@ fun LoopingTextWithBackground(
...
+                    .background(colorResource(R.color.bg_jetpack_login_splash))
+                    .paint(
+                            painter = painterResource(R.drawable.bg_jetpack_login_splash),
+                            sizeToIntrinsics = true,
+                            contentScale = ContentScale.FillBounds,
+                    )
+    ) {
         LoopingText(
                 modifier = Modifier
                         .fillMaxSize()
```
Comment (mkevins) [inline WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/components/LoopingTextWithBackground.kt:38]: Maybe we could add this here:

```suggestion
                        .clearAndSetSemantics {}
                        .fillMaxSize()
```

File: WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/components/RepeatingColumn.kt (hunk 1 above)
Comment (mkevins) [reply WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/components/RepeatingColumn.kt]: Like in [this suggestion](https://github.com/wordpress-mobile/WordPress-Android/pull/17317/files#r994295244).

**Review by mkevins — COMMENTED** [review]
This worked well in my testing (Pixel 3a, physical device). I left a couple of comments with a suggestion of where to invoke the modifier to clear the semantics.

File: WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/components/RepeatingColumn.kt (hunk 1 above)
Comment (ovitrif) [reply WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/components/RepeatingColumn.kt]: Makes sense to me Matthew 👍 , the fact that it remained in `RepeatingColumn` is because I was trying other options that made sense to be placed here (`semantics(mergeDescendants = true) {...})`) here but not anymore after using `clearAndSetSemantics {}` 😅 

Thank you 🙇

File: WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/components/LoopingTextWithBackground.kt (hunk 2 above)
Comment (ovitrif) [reply WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/components/LoopingTextWithBackground.kt:38]: Done in https://github.com/wordpress-mobile/WordPress-Android/pull/17317/commits/36c6e4ac85609e65d16e0a2c51773e3c48c73ad9

I was thinking to move `RepeatingColumn` to an upper level package (since initially this was the reasoning I applied to leave the modifier there), but then again it's easy enough to do it when we'd want to reuse it 😄

**Comment by ovitrif** [comment]
@antonis I added you as reviewer though I feel Matthew's review (though without Accepting the PR) already covered what's needed for this in hope we can still merge this to make it to the `21.0` milestone that is soon closing.

> without Accepting the PR

I hope this was meant to be done after applying the [suggestion](https://github.com/wordpress-mobile/WordPress-Android/pull/17317#discussion_r994295244) to keep `RepeatingColumn` reusable 🤞

**Review by antonis — APPROVED** [review]
Thank you for your work on improving the app accessibility @ovitrif 🙇 
I've tested the ci generated build on a Pixel 5 (Android 13) and the app worked as described. The code changes also LGTM and should cover @mkevins's suggestions 🎉
