### PR TITLE
Avoid tracking page accessed on static posters in the WP app

### LINKED ISSUE #20780: Notifications and reader accessed events tracked in WP app when static posters shown.
### Expected behavior
In the WP app, when a user accesses the notifications or reader and the static poster about the Jetpack app is shown, we should not track the "_accessed" event for that screen.

### Actual behavior
In the WP app, when a user accesses the notifications or reader and the static poster about the Jetpack app is shown, we track the "_accessed" event for that screen.

### Steps to reproduce the behavior
- Install the WP app
- Go to the Notifications/Reader tab (note: afaiu, this should be possible only with existing users by backend logic, not for new users for which those tabs are not available in the first place)
- Check the Jetpack static poster is shown
- Check the "notifications_accessed" or "reader_accessed" is triggered.

### PR DESCRIPTION
**Pull request by develric**
Fixes #20780

This PR fixes an issue in the WP app where we track notifications and reader accessed events even if we are showing a Jetpack static poster.

Didn't go with a deep refactor but extracted some needed logic into a helper method in `JetpackFeatureRemovalPhaseHelper.kt` and added a minimal set of unit testing coverage.

-----

## To Test:

**WP app**
- install the WP app
- Go to the Notifications/Reader tab (note: afaiu, this should be possible only with existing users by backend logic, not for new users for which those tabs are not available in the first place)
- Check the Jetpack static poster is shown
- Check the `remove_static_poster_displayed` is triggered with source `notifications` or `reader`
- Check the "notifications_accessed" or "reader_accessed" is not triggered.
- Smoke test "_accessed" event for My Site and Me screens and check they are triggered as usual.

**JP app**
- install the JP app
- Go to the Notifications/Reader tab
- Check the Jetpack static poster is not shown
- Check the `remove_static_poster_displayed` is not triggered
- Check the "notifications_accessed" or "reader_accessed" is triggered.
- Smoke test "_accessed" event for My Site and Me screens and check they are triggered as usual.

-----

## Regression Notes

1. Potential unintended areas of impact

    - Main tabs accessed tracking but the change should be safe enough.

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - Manual testing

3. What automated tests I added (or what prevented me from doing so)

    - Added a minimal set of unit testing coverage

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [x] WordPress.com sites and self-hosted Jetpack sites.
- [ ] ~~Portrait and landscape orientations.~~
- [ ] ~~Light and dark modes.~~
- [ ] ~~Fonts: Larger, smaller and bold text.~~
- [ ] ~~High contrast.~~
- [ ] ~~Talkback.~~
- [ ] ~~Languages with large words or with letters/accents not frequently used in English.~~
- [ ] ~~Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)~~
- [ ] ~~Large and small screen sizes. (Tablet and smaller phones)~~
- [ ] ~~Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)~~

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureRemovalPhaseHelper.kt [hunk 1]
```diff
@@ -126,6 +131,26 @@ class JetpackFeatureRemovalPhaseHelper @Inject constructor(
...
+        when (pageType) {
+            PageType.MY_SITE -> analyticsTrackerWrapper.track(AnalyticsTracker.Stat.MY_SITE_ACCESSED, site)
+            PageType.READER -> {
+                if (!shouldShowStaticPage()) {
+                    analyticsTrackerWrapper.track(AnalyticsTracker.Stat.READER_ACCESSED)
+                }
+            }
+
+            PageType.NOTIFS -> {
+                if (!shouldShowStaticPage()) {
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureRemovalPhaseHelper.kt]: Tested and works as expected. 

Nitpick: Maybe would be nice to include a function  that inversely wraps the `!shouldShowStaticPage()` call. Something like `private fun shouldTrackDynamicPage() = !shouldShowStaticPage()`.

Anyway, feel free to merge this!

**Review by daniloercoli — APPROVED** [review]

File: WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureRemovalPhaseHelper.kt (hunk 1 above)
Comment (develric) [reply WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureRemovalPhaseHelper.kt]: I was initially doing something like `false == shouldShowStaticPage()`, but AS was raising warning to simplify with the `!` and went with that 😄 ... but makes sense for readability 👍 , changed here 36b49c2c7fd6b6e854890cd5effd74a780bbdbc9

The change is minor, but I'll let you have a quick check as per good practice before merging since it's not urgent 🙇

**Review by daniloercoli — APPROVED** [review]
Perfect, thanks for addressing the suggestions; it makes the code more readable.
