### PR TITLE
readded null-check for extras and finishing activity if no URL found

### LINKED ISSUE #5799: Crash report 7.2: NPE in WPWebViewActivity
```

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.themes.ThemeWebActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2118)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2145)
       at android.app.ActivityThread.access$600(ActivityThread.java:130)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4847)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:535)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException
       at org.wordpress.android.ui.WPWebViewActivity.configureWebView(WPWebViewActivity.java:230)
       at org.wordpress.android.ui.WebViewActivity.onCreate(WebViewActivity.java:45)
       at org.wordpress.android.ui.WPWebViewActivity.onCreate(WPWebViewActivity.java:93)
       at android.app.Activity.performCreate(Activity.java:5187)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2064)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2145)
       at android.app.ActivityThread.access$600(ActivityThread.java:130)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4847)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:535)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)

````

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #5799 

While I haven't been able to reproduce this issue, the null check seems worth adding here. I've checked elsewhere where WPWEbActivity is used and it seems to be prevented before getting to this point. Also, tried re-creating the activity (configuration change / rotation) and it works alright.

This change, if no URL found makes the activity be finished silently (only an entry in the log is written) following the [same behavior this component already had here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java#L251-L254)

Placing this in consideration and judgment of @oguzkocer 🙇

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java [hunk 1]
```diff
@@ -227,7 +227,7 @@ protected void configureWebView() {
 
         // Configure the allowed URLs if available
         ArrayList<String> allowedURL = null;
-        if (extras.getBoolean(DISABLE_LINKS_ON_PAGE, false)) {
+        if (extras != null && extras.getBoolean(DISABLE_LINKS_ON_PAGE, false)) {
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java]: 👍 for the `null` check here!

File: WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java [hunk 2]
```diff
@@ -254,6 +254,10 @@ protected void configureWebView() {
             }
             webViewClient = new WPWebViewClient(site, mAccountStore.getAccessToken(), allowedURL);
         } else {
+            if (allowedURL == null || allowedURL.size() == 0) {
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java]: The `allowedURL` is not the url user is trying to browse, it's just a list we keep if we wanted to disable most of the links in the webview, so the user doesn't do weird stuff from it and blame the app. If we don't want to disable the links `allowedURL` would be null and this would finish the activity.

I am not sure what the intentions behind this change were but I think there was a misunderstanding about how this works. As an example, if you try to view a blog post's preview from the post list, it'll just not work. Hope that makes sense!

Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java]: Oh I see! makes sense, thanks for pointing that out, I clearly missed the purpose of `allowedURL` and confused it. Will get back on this later

Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java]: addressed in 2f13456 - ready for another round @oguzkocer 🙇
