### PR TITLE
[Reader Improvements] Fix follow unfollow button responsiveness

### LINKED ISSUE #19307: [Reader Improvements] Fix follow/unfollow button responsiveness
Context: https://github.com/wordpress-mobile/WordPress-Android/pull/19292#issuecomment-1748513205

### PR DESCRIPTION
**Pull request by thomashorta**
Fixes #19307 

Make the changes where needed to have the behavior closer to:
1. user taps the button
2. button changes state immediately and becomes disabled
3. request for the action is triggered while button is disabled
4. result from backend is received
5. if success -> button is enabled again and keeps the new state
6. if failure -> button is enabled again and reverts to previous state

To test:
Use the reader and use the follow/unfollow button in the several app areas, such as:
- feed cards (posts and recommended blogs)
- site header
- tag header
- follow/unfollow settings

## Regression Notes
1. Potential unintended areas of impact
Wrong behavior in buttons that didn't have code changed.

7. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing.

8. What automated tests I added (or what prevented me from doing so)
Updated unit tests.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:

- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by RenanLukas** [comment]
Thanks for the PR, @thomashorta ! I've tested a few scenarios in the Reader including the tag header, site header, post header, "Manage Topics & Sites" screen and post card and things seem to be working great. I wanted to raise a couple of concerns related to follow/unfollow button (but not related this PR) before I start reviewing the code.

First concern is about the "Following" tab: when we stop following a site using the post card overflow menu, shouldn't we hide the posts from that site right away? I'm asking because right now we're only updating the unfollow action after the screen is refreshed, but maybe this was done on purpose back when this feature was implemented.

https://github.com/wordpress-mobile/WordPress-Android/assets/14964993/58d1aa6b-1c9d-4f40-a132-5d26dfee285a

The second thing is that sometimes it seems like the follow/unfollow action is a bit off. Sometimes the request fails and sometimes it seems like the status is not updated everywhere. I couldn't find the exact steps to reproduce, but I'm posting a couple of videos:

https://github.com/wordpress-mobile/WordPress-Android/assets/14964993/3bb4eeb4-ef9d-449e-a8ef-9dd12ad9317d

https://github.com/wordpress-mobile/WordPress-Android/assets/14964993/c6c6d141-aa3d-47b2-86d9-da21e040111a

File: WordPress/src/main/java/org/wordpress/android/ui/reader/usecases/ReaderSiteFollowUseCase.kt [hunk 1]
```diff
@@ -104,7 +105,8 @@ class ReaderSiteFollowUseCase @Inject constructor(
             val feedId: Long,
             val following: Boolean,
             val showEnableNotification: Boolean = false,
-            val deleteNotificationSubscription: Boolean = false
+            val deleteNotificationSubscription: Boolean = false,
+            val isChangeFinal: Boolean = true,
```
Comment (RenanLukas) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/usecases/ReaderSiteFollowUseCase.kt:109]: Nice 👍

**Review by RenanLukas — APPROVED** [review]
Thanks for the changes, @thomashorta.
As mentioned above, I've tested multiple scenarios and it's working as expected :shipit:
