### PR TITLE
Fix/16689 notifications not dismissing when logged out

### LINKED ISSUE #16689: Notifications doesnt dismiss after logging out from the App
### Expected behavior
Notifications should be dismissed after logging out 

### Actual behavior
https://user-images.githubusercontent.com/17463767/171617083-fc7dcd09-4e2f-4d6d-87d9-e594b0c7e439.mp4

### Steps to reproduce the behavior
- Login to the app 
- Create Post/Reply to a comment(finish any tasks which creates a notification) 
- Dont dismiss the notification 
- Logout from the app 
- Notice that the notification is still seen 

##### Tested on [device], Android [version], WPAndroid [version]
Samsung s22, Android 12

### PR DESCRIPTION
**Pull request by carl-duncan**
Fixes #16689 
Notifications are now deleted when a user logs out

To test:

Login to the app
Create Post/Reply to a comment(finish any tasks which creates a notification)
Dont dismiss the notification
Logout from the app

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

N/A
3. What automated tests I added (or what prevented me from doing so)

N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by carl-duncan** [comment]
Hi, I resolved that issue : https://github.com/wordpress-mobile/WordPress-Android/pull/16694

File: WordPress/src/main/java/org/wordpress/android/util/NotificationsUtilsWrapper.kt [hunk 1]
```diff
@@ -0,0 +1,10 @@
+package org.wordpress.android.util
+
+import androidx.core.app.NotificationManagerCompat
+import javax.inject.Inject
+
+class NotificationsUtilsWrapper @Inject constructor() {
```
Comment (AjeshRPai) [inline WordPress/src/main/java/org/wordpress/android/util/NotificationsUtilsWrapper.kt]: Suggestion: Instead of adding a new class just for clearing the notifications, can we add this function to the `NotificationsUtils` class?.

**Review by AjeshRPai — CHANGES_REQUESTED** [review]
@carl-duncan Thanks for working on this. The fix looks good. I have tested as per the instructions. I have left a suggestion, Please let me know if you need any additional info.

File: WordPress/src/main/java/org/wordpress/android/util/NotificationsUtilsWrapper.kt (hunk 1 above)
Comment (carl-duncan) [reply WordPress/src/main/java/org/wordpress/android/util/NotificationsUtilsWrapper.kt]: Resolved this by adding the function to the NotificationUtils class , thank you for the suggestion

**Comment by carl-duncan** [comment]
Hello @AjeshRPai , I resolved the suggested change.

**Comment by AjeshRPai** [comment]
@carl-duncan Thanks for making the suggested change. I have triggered the CI. Once that is completed successfully I will merge the PR. 👍🏼 🙌🏼

**Review by AjeshRPai — APPROVED** [review]

**Comment by AliSoftware** [comment]
Good news @carl-duncan: your fix has made its way to the version `20.1` that we started to progressively roll out to end users this morning 🎉
