### PR TITLE
Fix #5420: pass the site id direclty

### LINKED ISSUE #5420: Crash report 7.0-rc-1: NPE in ReaderPostListFragment.blockBlogForPost
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
       at org.wordpress.android.ui.reader.ReaderPostListFragment.blockBlogForPost(ReaderPostListFragment.java:805)
       at org.wordpress.android.ui.reader.ReaderPostListFragment.access$3900(ReaderPostListFragment.java:85)
       at org.wordpress.android.ui.reader.ReaderPostListFragment$16.onItemClick(ReaderPostListFragment.java:1524)
       at android.widget.AdapterView.performItemClick(AdapterView.java:346)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1577)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3970)
       at android.widget.AbsListView$7.run(AbsListView.java:6065)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7409)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

### PR DESCRIPTION
**Pull request by maxme**
Fix #5420: pass the site id directly

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java [hunk 1]
```diff
@@ -800,10 +800,7 @@ public void onActionResult(boolean succeeded) {
         // they can be restored if the user undoes the block
         final BlockedBlogResult blockResult = ReaderBlogActions.blockBlogFromReader(post.blogId, actionListener);
         // Only pass the blogID if available. Do not track feedID
-        AnalyticsUtils.trackWithSiteId(
-                AnalyticsTracker.Stat.READER_BLOG_BLOCKED,
-                mCurrentBlogId != 0 ? mCurrentBlogId : null
-        );
+        AnalyticsUtils.trackWithSiteId(AnalyticsTracker.Stat.READER_BLOG_BLOCKED, mCurrentBlogId);
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java]: This resolves the issue but I'm wondering if we should be passing `post.blogId` here instead, so we track the ID of the site being blocked? I can open a separate issue for that if you like.

**Comment by nbradbury** [comment]
Opened #5429 so we can merge this one. :shipit:
