### PR TITLE
Complete the login process in epilogue when needed

### LINKED ISSUE #6417: Login Rework: empty sites list in epilogue when magiclink login
### Expected behavior
When logging in via magic link, the epilogue sites list should have the sites available on the wpcom account that just logged in.

### Actual behavior
The epilogue sites list is empty. This is a regression caused by https://github.com/wordpress-mobile/WordPress-Android/pull/6354#issuecomment-316712069

### Steps to reproduce the behavior
Clear the app data and login to your wpcom via magic link. At the end of the process, the epilogue screen will have no sites listed.

### PR DESCRIPTION
**Pull request by hypest**
**Note: #6402 needs to be merged first.**

Fixes #6417 

Enables completing the login process (fetch account details and sites) via the epilogue screen when on the magiclinks flow. In other cases, that process is performed prior to the epilogue screen appearing.

To test:
* Clear the app data and login to your wpcom via magic link
* At the end of the process, the epilogue screen should have your wpcom sites listed

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/login/Login2FaFragment.java [hunk 1]
```diff
@@ -116,6 +117,7 @@ protected void onHelp() {
     @Override
     public void onCreate(Bundle savedInstanceState) {
         super.onCreate(savedInstanceState);
+        ((WordPress) getActivity().getApplication()).component().inject(this);
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/login/Login2FaFragment.java]: If we are going to inject for every child of `LoginBaseFormFragment`, I think it'd be better if we just did the inject in that base class. This way we can remove all these injects and slim down the `AppComponent` class a little bit.

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginEpilogueFragment.java [hunk 2]
```diff
@@ -23,59 +28,83 @@
...
-        ((WordPress) getActivity().getApplication()).component().inject(this);
+    protected boolean listenForLogin() {
+        return mDoLoginUpdate;
+    }
 
-        mShowAndReturn = getArguments().getBoolean(ARG_SHOW_AND_RETURN);
-        mOldSitesIds = getArguments().getIntegerArrayList(ARG_OLD_SITES_IDS);
+    @Override
+    protected @LayoutRes int getContentLayout() {
+        return 0; // nothing specia here. The view is inflated in createMainView()
```
Comment (hypest) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginEpilogueFragment.java]: Good catch, fixed with 3359540.

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/login/Login2FaFragment.java (hunk 1 above)
Comment (hypest) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/login/Login2FaFragment.java]: The injection in the base class is more tricky because it's a generic class. That's why I moved the injection up.

Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/login/Login2FaFragment.java]: Interesting, I thought we could do it.

**Comment by hypest** [comment]
Thanks for the review and the merge @oguzkocer !

> The only thing I am not 100% sure about is that we are handling the FluxC callbacks in the base fragment.

That's a good point. I will investigate a bit further and will raise an issue if there's a problem. 🙇
