### PR TITLE
Excludes self-hosted from user blocking and reporting

### LINKED ISSUE #17826: Blocking self-hosted site authors can inadvertently block authors of other sites
### Expected behavior
Only posts from the site of the blocked author disappear from Reader.

### Actual behavior
Posts from both sites disappear from Reader.

### Steps to reproduce the behavior
1. In Reader, follow two newly created self-hosted sites (this should ensure the default user has an ID of `0` for both)
2. Ensure at least one post exists on each site, created by the default user
3. Load Reader and observe posts from both sites
4. On one post, tap the `⋮` overflow menu and choose `Block user`

### Notes
- [Related PR](https://github.com/wordpress-mobile/WordPress-Android/pull/17604)

This bug is due to the fact the author ID in Reader for self-hosted sites is **local** to that site and thus not unique, unlike author IDs for sites hosted on WordPress.com.

### PR DESCRIPTION
**Pull request by antonis**
Fixes #17826

## Description
Excludes self-hosted from user blocking and reporting to avoid the inconsistent behaviour reported in https://github.com/wordpress-mobile/WordPress-Android/issues/17826 and erroneous user reporting for non WPCOM users.

|Before|After|
|---|---|
|Screenshot_20230202_165826|Screenshot_20230202_165913|

### Self-hosted
1. In Reader, follow a self-hosted site
2. Tap on the option menu next to a site's post
3. **Verify** that the block user option is not present
4. **Verify** that the report user option is not present
### Sanity
1. In Reader, follow a wpcom site
2. Tap on the option menu next to a site's post
3. **Verify** that the block user option is present
4. **Verify** that the report user option is present

## Regression Notes
1. Potential unintended areas of impact
N/A

6. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing and relied on existing reader test

7. What automated tests I added (or what prevented me from doing so)
Added 3 new test cases in `ReaderPostMoreButtonUiStateBuilderTest`

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtils.java [hunk 1]
```diff
@@ -546,4 +546,12 @@ public static boolean postExists(long blogId, long postId) {
     public static boolean commentExists(long blogId, long postId, long commentId) {
         return ReaderCommentTable.commentExists(blogId, postId, commentId);
     }
+
+    /**
+     * Self-hosted sites have a site id of 0, but we use -1 to indicate a self-hosted site
```
Comment (antonis) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtils.java:551]: This logic seems by trying it out but I'll need to confirm that it applies in all cases.

Comment (mkevins) [reply WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtils.java:551]: I think this is correct as well, but I agree it'd be good to confirm. :+1:

File: WordPress/src/test/java/org/wordpress/android/ui/reader/discover/ReaderPostMoreButtonUiStateBuilderTest.kt [hunk 2]
```diff
@@ -309,6 +323,34 @@ class ReaderPostMoreButtonUiStateBuilderTest : BaseUnitTest() {
...
+        // Act
+        val menuItems = builder.buildMoreMenuItems(post, dummyOnClick)
+        // Assert
+        assertThat(menuItems.find {
+            it.type == ReaderPostCardActionType.BLOCK_USER
+        }).isNotNull()
+    }
+
+    @Test
+    fun `does not contain block user action for wpcom sites`() = test {
```
Comment (mkevins) [inline WordPress/src/test/java/org/wordpress/android/ui/reader/discover/ReaderPostMoreButtonUiStateBuilderTest.kt]: I guess this test name is meant to be `does not contain block user action for self-hosted sites`?

File: WordPress/src/test/java/org/wordpress/android/ui/reader/discover/ReaderPostMoreButtonUiStateBuilderTest.kt [hunk 3]
```diff
@@ -244,15 +244,29 @@ class ReaderPostMoreButtonUiStateBuilderTest : BaseUnitTest() {
...
+    fun `does not contain report user action for self-hosted sites`() = test {
+        // Arrange
+        val post = init()
+        whenever(readerUtilsWrapper.isSelfHosted(post.authorId)).thenReturn(true)
+
+        // Act
+        val menuItems = builder.buildMoreMenuItems(post, dummyOnClick)
+        // Assert
+        assertThat(menuItems.find { it.type == ReaderPostCardActionType.REPORT_USER }).isNull()
+    }
```
Comment (mkevins) [inline WordPress/src/test/java/org/wordpress/android/ui/reader/discover/ReaderPostMoreButtonUiStateBuilderTest.kt:268]: Thanks for adding these tests!

File: WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderPostMoreButtonUiStateBuilder.kt [hunk 4]
```diff
@@ -57,8 +57,8 @@ class ReaderPostMoreButtonUiStateBuilder @Inject constructor(
         menuItems.add(SpacerNoAction())
         menuItems.add(buildBlockSite(onButtonClicked))
         menuItems.add(buildReportPost(onButtonClicked))
-        menuItems.add(buildReportUser(onButtonClicked))
-        checkAndAddMenuItemForBlockUser(menuItems, onButtonClicked)
+        checkAndAddMenuItemForReportUser(post, menuItems, onButtonClicked)
+        checkAndAddMenuItemForBlockUser(post, menuItems, onButtonClicked)
```
Comment (mkevins) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderPostMoreButtonUiStateBuilder.kt]: Ever-so-minor nitpicky comment:

I think this is fine as is, but we could also consider something like the following:

```kotlin
if (!readerUtilsWrapper.isSelfHosted(post.authorBlogId)) {
    menuItems.add(buildReportUser(onButtonClicked))
    menuItems.add(buildBlockUser(onButtonClicked))
}
```

Since the extracted functions are almost identical.. otoh, the way it is now is more consistent with the other extracted functions :man_shrugging: .

Maybe we can extract a single function: `checkAndAddUserMenuItems` :thinking:

**Review by mkevins — COMMENTED** [review]
I tested this and it is working as described! Thanks for addressing this Antonis :+1:  Also, the code looks good. I left one question about the test name, but the rest of the comments are non-blocking.

File: WordPress/src/test/java/org/wordpress/android/ui/reader/discover/ReaderPostMoreButtonUiStateBuilderTest.kt (hunk 2 above)
Comment (antonis) [reply WordPress/src/test/java/org/wordpress/android/ui/reader/discover/ReaderPostMoreButtonUiStateBuilderTest.kt]: Good catch @mkevins 👍 
Fixed with 26ca9ed9bbf8c9906e3998afd4d884a88eedc43a

File: WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderPostMoreButtonUiStateBuilder.kt (hunk 4 above)
Comment (antonis) [reply WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderPostMoreButtonUiStateBuilder.kt]: That's a great suggestion @mkevins 👍 

> the way it is now is more consistent with the other extracted functions

That's true but on a second thought I too feel that this is unnecessary boilerplate code 😅 
I've implemented your suggestion with 0a0afe81ed6478d070f773aac6fd07608025f9b0

File: WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtils.java (hunk 1 above)
Comment (antonis) [reply WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtils.java:551]: This should be correct since [the `authorBlogId` is actually the `site_ID`](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/java/org/wordpress/android/models/ReaderPost.java#L279) that exists only for [WPCOM sites](https://developer.wordpress.com/docs/api/1.1/get/read/sites/%24site/posts/%24post_ID/#apidoc-response).

Comment (ovitrif) [reply WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtils.java:551]: I find the logic to be correct as well by trying with the debugger 🤔 

Another option might be to use `post.isWP()` which is computed from `!post.isExternal`, which in turn is from the `is_external` json field in the [endpoint response](https://developer.wordpress.com/docs/api/1.1/get/read/sites/%24site/posts/%24post_ID/#apidoc-response). I noticed this is used to enable/disable likes & comments on the post cards, see:
https://github.com/wordpress-mobile/WordPress-Android/blob/0002b4ede131f3bcc8f99596098d3832a81ffa95/WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderPostUiStateBuilder.kt#L439

Although personally I prefer basing the logic on `authorBlogId` because the [issue](https://github.com/wordpress-mobile/WordPress-Android/issues/17826#issue-1557329972) is caused by the value of this field being equal for different sites 🤷 

@antonis wdyt?

**Review by ovitrif — APPROVED** [review]
Looks great and works as expected 🎉 

Thank you for implementing this fix @antonis 🥇 🏆 🙇 

I left a comment regarding a possible alternative implementation for determining if a post is  on self-hosted sites, although personally I somehow prefer what you've already added 😅 . Let me know your thoughts!

File: WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtils.java (hunk 1 above)
Comment (antonis) [reply WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtils.java:551]: Good point @ovitrif 👍 
My first though was to use the `isWP` property but I haven't figured out where this value comes from  and it seems inconsistent to me 🤷 
For example for the following sites the `post.isWP` is `false` in my tests:
* https://www.tannr.com
* https://magazine.atavist.com
* https://puny-toucan.jurassic.ninja

and for the https://top-lungfish.jurassic.ninja the value is `true` 😕 
Note that I've created both JN sites at the same time 🤷 
Searching I found this old p5PDj3-Ij-p2 post that describes an issue with the `is_external` value.

Comment (ovitrif) [reply WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtils.java:551]: > For example for the following sites the post.isWP is false in my tests [...]
> Searching I found this old p5PDj3-Ij-p2 post that describes an issue with the is_external value.

Nice find @antonis ! All more reasons in favor of the current approach 🚀 👍 

I'll resolve this conversation, thank you for the follow-up and the additional info!

**Comment by ovitrif** [comment]
I'm merging this PR, it looks ready from my side and everything that was initially unclear is now validated 👍
