### PR TITLE
Fixes: Make FAB be always above snackbar.

### LINKED ISSUE #16149: Publish Snackbar Should Not Overlap FAB button
### Expected behavior
When the publish post snackbar appears, the "Publish" action no longer appears directly over the top of the Add New Post FAB button. 

One way this could be addressed would be by moving the FAB button above (i.e. toward the top of the screen) the snackbar when the snackbar appears so there would no longer be any overlap.

### Actual behavior
When the publish post snackbar appears, the "Publish" action is directly over the top of the Add New Post FAB button. 

This both (1) makes it impossible to open a new draft until that snackbar is removed and (2) makes it easy to accidentally publish a post when you intend to tap where you expect the new draft FAB button to be.

### Steps to reproduce the behavior

1. From the drafts tab of the Posts Page, open a new draft post
2. Add some content to the post and back out of the post screen
3. Observe that the snackbar is on top of the FAB button

image 

https://user-images.githubusercontent.com/4656348/159555194-04e5b0e7-3d6d-4e67-b93d-2736419b24a5.mp4

### PR DESCRIPTION
**Pull request by jarvislin**
Fixes #16149 

Removed the nested ConstraintLayout for letting FAB anchor above snackbar in CoordinatorLayout by default.

Moreover, added layout behaviors let views can anchor to the correct position with a transition animation.

To test:
Edit a draft and leave the page like the videos in **Before** and **After**.

## Before

https://user-images.githubusercontent.com/4656348/159555194-04e5b0e7-3d6d-4e67-b93d-2736419b24a5.mp4

## After

https://user-images.githubusercontent.com/3839951/161393458-65c2bb74-5fad-4170-8ea1-89ad69f2e6c8.mp4

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/LayoutBehaviors.kt [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+import androidx.core.view.marginBottom
+import com.google.android.material.floatingactionbutton.FloatingActionButton
+import com.google.android.material.snackbar.Snackbar.SnackbarLayout
+import org.wordpress.android.ui.WPTooltipView.TooltipPosition.ABOVE
+
+/**
+ * This class will let WPTooltipViewBehavior anchor above FloatingActionButton with transition animation.
+ */
+
+class WPTooltipViewBehavior : CoordinatorLayout.Behavior<WPTooltipView> {
```
Comment (mchowning) [inline WordPress/src/main/java/org/wordpress/android/ui/LayoutBehaviors.kt:18]: Minor issue: We're importing `CoordinatorLayout.Behavior`, so what would you think about either (a) removing the CoordinatorLayout qualifier here or (b) removing the import of `CoordinatorLayout.Behavior` and updating the `FloatingActionBarBehavior`'s reference to be qualified like this one is?

File: WordPress/src/main/java/org/wordpress/android/ui/WPTooltipView.kt [hunk 2]
```diff
@@ -148,4 +147,6 @@ class WPTooltipView @JvmOverloads constructor (
     fun setMessage(message: CharSequence) {
         tvMessage.text = message
     }
+
+    fun getPosition() = position
```
Comment (mchowning) [inline WordPress/src/main/java/org/wordpress/android/ui/WPTooltipView.kt]: Instead of adding this getter method, I would be inclined to update the visibility of the field's getter and setter directly with something like:

``` diff
- private var position = LEFT
+ var position = LEFT
+ private set
```

This is somewhat just my personal preference, so feel free to leave this as-is if you prefer. Or, if there's a reason it would be a bad idea to do this, definitely let me know. 🙂  Either way, this issue is not a blocker to merging this.

**Review by mchowning — COMMENTED** [review]
Great work @jarvislin! I tested this and it works perfectly. The code also looks good! 👍 

I only had two minor comments. I think it would be good to address the import comment before we merge this, but the comment about the field's getter is more of a personal preference—feel free to leave it as-is if you prefer.

Thanks again for the contribution! 🙇

File: WordPress/src/main/java/org/wordpress/android/ui/LayoutBehaviors.kt (hunk 1 above)
Comment (jarvislin) [reply WordPress/src/main/java/org/wordpress/android/ui/LayoutBehaviors.kt:18]: I would like to choose (b). Keep CoordinatorLayout here, it's easier for developers to understand what it is.
I will remove the import of CoordinatorLayout.Behavior and updating the FloatingActionBarBehavior's reference.

File: WordPress/src/main/java/org/wordpress/android/ui/WPTooltipView.kt (hunk 2 above)
Comment (jarvislin) [reply WordPress/src/main/java/org/wordpress/android/ui/WPTooltipView.kt]: Your solution is elegant 👍
will update the code in next commit

**Comment by jarvislin** [comment]
@mchowning 
Thanks for the code review, I've pushed the commit.

**Review by mchowning — APPROVED** [review]
Everything looks great. Thanks so much @jarvislin ! 🙇 

I especially appreciate how you gave this the animation that is missing if we just use the default FAB behavior. It'd be great to start using this in other parts of the app (like the Dashboard).
