### PR TITLE
Fix #3645 by retaining mSelfHosted flag

### LINKED ISSUE #3645: Sign In: Leaving the self-hosted login screen, it reverts back to WordPress.com login
When first opening the app, if you go to the self-hosted login screen, leave the screen (either within the app or by exiting and reopening the app), and the return to the login screen, it will revert back to the WordPress.com login screen.

Steps to reproduce:
1. Open the app while logged out
2. Select "Add self-hosted site"
3. Optional: begin to enter your account information
4. Tap on the Help icon (?) in the top right, or exit the app on your device
5. Go back to the login screen
Result: You see the WordPress.com login screen instead of the self-hosted login screen you were just on

I encountered this in a very normal login flow, where I entered my username and site URL but had to leave the app to get my password. When I reopened the app, I saw the wrong login screen.

Tested on Nexus 9, Android 6.0.1, app beta v. 5.0-rc-1.

### PR DESCRIPTION
**Pull request by khaykov**
Fix for #3645.

Issue can be recreated by turning on "Don't keep activities".

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInFragment.java [hunk 1]
```diff
@@ -160,6 +169,11 @@ public void onClick(View v) {
             }
         });
 
+        if (mSelfHosted) {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInFragment.java]: This duplicates code that occurs in the `mAddSelfHostedButton` click handler [above](https://github.com/wordpress-mobile/WordPress-Android/pull/3735/files#diff-d1955c04c369a8c269a4d81a5fdbe99fR160). Seems like a good candidate for a separate `setIsSelfHosted` method.

Comment (khaykov) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInFragment.java]: Thanks, Nick! You are totaly right. I refactored the code a bit.

**Comment by nbradbury** [comment]
Looks good! :shipit:
