### PR TITLE
Fixed tag toolbar overlap after calling scrollToPosition

### LINKED ISSUE #2709: Reader tag toolbar overlaps after rotating
If you rotate the device while the reader post list is scrolled, the tag toolbar appears at the top and overlaps the topmost post. A similar bug occurs after tapping the "new posts" message.

device-2015-05-15-214408

### PR DESCRIPTION
**Pull request by nbradbury**
Fix #2709 - normally the tag toolbar is repositioned after the list is scrolled via [the scroll listener](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java#L514), but it turns out there are two problems with this:

* RecycleView doesn't call the scroll listener when `scrollToPosition()` is used
* There's a very brief delay between when `scrollToPosition()` is used and when you can get an accurate scroll position

The solution in this PR required adding a brief delay before repositioning the tag toolbar after `scrollToPosition()` is called.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java [hunk 1]
```diff
@@ -463,6 +463,25 @@ public void run() {
...
     }
 
+    private void scrollRecycleViewToPosition(int position) {
+        if (!isAdded() || mRecyclerView == null) return;
+
+        mRecyclerView.scrollToPosition(position);
+
+        // we need to reposition the tag toolbar here, but we need to wait for the
+        // recycler to settle before doing so - note that RecyclerView doesn't
+        // fire it's scroll listener when scrollToPosition() is called, so we
```
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java]: :sob:

**Comment by maxme** [comment]
:shipit:

**Comment by maxme** [comment]
cherry picked  0f1d238 in `release/4.1`
