### PR TITLE
Fix loading when site model is incomplete

### LINKED ISSUE #9352: Stats not loaded right after connecting Jetpack
If you try to connect a self-hosted site to Jetpack to open stats, the loading fails the first time (you have to leave the screen and go back). The reason is that after the Jetpack install is finished the SiteModel is not yet updated with the remote `siteId`. We're triggering a `fetchSite` operation and it's up to race whether it can make it or not. 

Steps to reproduce:
* Create a self-hosted site (jurassic.ninja)
* Add the self-hosted site in the app
* Go to stats
* Install Jetpack and connect it to your account
* The stats open with en error "Data not loaded" and a retry button

### PR DESCRIPTION
**Pull request by planarvoid**
Fixes #9352
This PR introduces a `SiteModelProvider`, which provides an up-to-date version of the SiteModel and triggers a data refresh, when the SiteModel is updated. I've replaced the `SiteModel` that was passed around as a parameter all around the use cases with the provider. The only place where we're still retrieving the `SiteModel` is inside of the `StatsFragment` where we initialize the `SiteModelProvider` in the `start` method of the `StatsViewModel`.

To test:
* Create a self-hosted site (jurassic.ninja)
* Add the self-hosted site in the app
* Go to stats
* Install Jetpack and connect it to your account
* The stats open with the correct data (empty) after the process is finished

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BaseStatsUseCase.kt [hunk 1]
```diff
@@ -64,7 +63,7 @@ abstract class BaseStatsUseCase<DOMAIN_MODEL, UI_STATE>(
      * @param refresh is true when we want to get the remote data
```
Comment (0nko) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BaseStatsUseCase.kt]: You forgot to update the comments.

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BaseStatsUseCase.kt [hunk 2]
```diff
@@ -148,14 +147,14 @@ abstract class BaseStatsUseCase<DOMAIN_MODEL, UI_STATE>(
      * Loads data from a local cache. Returns a null value when the cache is empty.
      * @param site for which we load the data
```
Comment (0nko) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BaseStatsUseCase.kt]: Extra site parameter in comments.

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BaseStatsUseCase.kt [hunk 3]
```diff
@@ -148,14 +147,14 @@ abstract class BaseStatsUseCase<DOMAIN_MODEL, UI_STATE>(
...
      */
-    protected abstract suspend fun loadCachedData(site: SiteModel): DOMAIN_MODEL?
+    protected abstract suspend fun loadCachedData(): DOMAIN_MODEL?
 
     /**
      * Fetches remote data from the endpoint.
      * @param site for which we fetch the data
```
Comment (0nko) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BaseStatsUseCase.kt]: Extra site parameter in comments.

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/SiteModelProvider.kt [hunk 4]
```diff
@@ -0,0 +1,46 @@
...
+
+    fun stop() {
+        dispatcher.unregister(this)
+    }
+
+    fun hasLoadedSite(): Boolean = siteModel.siteId != 0L
+
+    @Subscribe(threadMode = ThreadMode.MAIN)
+    fun onSiteChanged(event: OnSiteChanged) {
+        val site = siteStore.getSiteByLocalId(siteModel.id)
```
Comment (0nko) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/SiteModelProvider.kt]: This looks a bit cumbersome. When updating a the site provider when the site changes you must already know what it changed to :). Would it be possible to update the `OnSiteChanged` to include the new site value? That way you it won't be necessary to call `start(site)`. Also, that way the dispatcher registration could happen in the constructor.

**Review by 0nko — COMMENTED** [review]
Looks great. I hope the `SiteProvider` will be used everywhere, eventually. I've left a couple of comments in the code. Let me know what you think.

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/SiteModelProvider.kt (hunk 4 above)
Comment (planarvoid) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/SiteModelProvider.kt]: You're totally right and I think it should be done this way. I think it's out of scope for this PR. At least we're containing this logic in one place. I think it might make sense to rename this `SiteModelProvider` to something like `StatsSiteProvider` because it shouldn't be used anywhere else right now. I think adding a full reusable `SiteModelProvider` should be a separate task. Let me know what you think :-)

**Comment by planarvoid** [comment]
@0nko This should be ready for another try

**Review by 0nko — APPROVED** [review]
Thanks for the changes. :shipit:
