### PR TITLE
Display `Quick Start` card on site switch only when `Quick Start` is started

### LINKED ISSUE #16650: Quick Start: Display `Quick Start` card on site switch only when quick start is started
### Expected behavior
When switching a site from the site-chooser on `My Site` tab, the `Quick Start` card is shown for the chosen site even when the `Quick Start ` was not started for the site. 

### Actual behavior
When switching a site from the site-chooser on `My Site` tab, the `Quick Start `card should be shown for the chosen site only when the `Quick Start ` was started for the site. 

### Steps to reproduce the behavior

1. Launch the app. 
2. Logout and login.
3. Select an existing site from the `Login Epilogue` screen.
4. Select "Show me around" on onboarding `Quick Start` dialog.
5. Notice that the `Quick Start` card is shown for the existing site.
6. Switch to another site (for which `Quick Start` is not started) from the site-chooser.
7. Notice that the `Quick Start` card is shown for the chosen site even when the `Quick Start` was not started for the site from the onboarding `Quick Start ` dialog.

### PR DESCRIPTION
**Pull request by ashiagr**
Fixes #16650

This PR displays `Quick Start` card on switching the site from the site-chooser on `My Site` tab *only when* `Quick Start` is started for the site.

Corresponding FluxC PR: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2426

To test:

1. Launch the app.
2. Logout and login.
3. Select an existing site (`Site A`) from the `Login Epilogue` screen.
4. Select "Show me around" on onboarding `Quick Start` dialog.
5. Go to `My Site` tab.
6. ✅ Notice that the `Quick Start` card is shown for the existing site `Site A`.
7. Create a new site (`Site B`)  from the site-chooser.
8. ✅ Notice that the `Quick Start` card is shown for the new site  `Site B`.
9. Re-select `Site A` from the site-chooser.
10. ✅ Notice that the `Quick Start` card is shown for the existing site `Site A` since `Quick Start` was started for `Site A`.
11. Select `Site C` (for which `Quick Start` has not started) from the site-chooser.
12. ✅ Notice that the `Quick Start` card is not shown for `Site C`.

Merge Instructions

1. Wait for corresponding FluxC PR to be merged and create FluxC tag.
2. Replace `FluxC` tag in build.gradle.
3. Wait for regression notes to be filled for 1. 
4. Remove `Not Ready for Merge` label.
5. Merge the PR.

## Regression Notes
1. Potential unintended areas of impact
Please keep in mind while testing that there's a known issue (Internal Ref: p1627036988014500-slack-C027K4MNPGQ), that after re-login, the `Quick Start` card is not shown on switching the site due to using the local site id for saving quick start data. This PR does not fix this issue.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
See `To Test` section.

3. What automated tests I added (or what prevented me from doing so)
To be added later 

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/quickstart/QuickStartType.kt [hunk 1]
```diff
@@ -53,8 +54,8 @@ sealed class QuickStartType(
         return when (this) {
             is NewSiteQuickStartType -> !isQuickStartCompleted &&
                     quickStartStore.hasDoneTask(siteLocalId, QuickStartNewSiteTask.CREATE_SITE)
-            // TODO: ashiagr update isQuickStartInProgress condition for ExistingSiteQuickStartType
-            is ExistingSiteQuickStartType -> !isQuickStartCompleted
+            is ExistingSiteQuickStartType -> quickStartStore.isQuickStartStatusSet(siteLocalId) &&
+                    !isQuickStartCompleted
         }
```
Comment (AjeshRPai) [inline WordPress/src/main/java/org/wordpress/android/ui/quickstart/QuickStartType.kt:59]: Suggestion : Since `isQuickStartCompleted` is used irregardles of the `QuickStartType` why don't we pull it out of the when expression ?. Something like this. 🤔 

```
fun isQuickStartInProgress(quickStartStore: QuickStartStore, siteLocalId: Long): Boolean {
        val isQuickStartCompleted = quickStartStore.getQuickStartCompleted(siteLocalId)
        if(!isQuickStartCompleted)return false
        return when (this) {
            is NewSiteQuickStartType -> quickStartStore.hasDoneTask(siteLocalId, QuickStartNewSiteTask.CREATE_SITE)
            is ExistingSiteQuickStartType -> quickStartStore.isQuickStartStatusSet(siteLocalId)
        }
    }
```

**Review by AjeshRPai — APPROVED** [review]
First of all, Great job finding this bug. Your observational skills are 🙌🏼 

I have looked at the code changes and tested it as per the instructions. Everything looks good to me. Great Job @ashiagr. 👍 🙌 

I have left a suggestion for you to address. Please feel free to address it if you think thats necessary. As that is non-blocking I am approving the PR. Please feel to merge according to your convenience. 👍🏼

File: WordPress/src/main/java/org/wordpress/android/ui/quickstart/QuickStartType.kt (hunk 1 above)
Comment (ashiagr) [reply WordPress/src/main/java/org/wordpress/android/ui/quickstart/QuickStartType.kt:59]: That’s because we did not save [quick start status (completed = false)](https://github.com/wordpress-mobile/WordPress-Android/pull/16651/files#diff-6106e6928a9ec7a2262d9ff7858267e9ac4b0a4b0f7827939a392f398042e2faR40) earlier when quick start started. For sites with no record for quick start status, `isQuickStartCompleted` will be false as there won't be quick start status present in db which will return incorrect quick start progress status for the existing site. 
Let's keep the existing logic for now. I'll see if I can improve it. 

Thanks for calling it out! 🙇‍♀️
