### PR TITLE
Fix reattachment

### LINKED ISSUE #6282: Media: reattachment sometimes jumps a bit
#### To test:
- CASE B: SINGLE UPLOAD, start upload and exit the editor, before it ends get back to the editor, see if it reattaches (Aztec only)

Sometimes reattaching shows a very low progress and then jumps to the current progress. We might want to save the progress to the DB for each upload, so we can accurately reflect it for reattachment.

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #6282 

With the `UploadService` in async media now in place, this PR adds `EditorMediaUploadListener.onMediaUploadReattached` interface and helper methods in `UploadService` to make sure each time the `EditPostActivity` is shown we get the highest latest progress value for each media item known, as reported by the `UploadService`.

Note: reattachment only applies to Aztec.

To test:
1. start a draft
2. include several media items, specially large ones (big images or some videos work too)
3. leave the editor
4. enter the editor again
5. repeat steps 3 and 4 repeatedly and observe the yellow/orange progress bar inside the Editor doesn't make any wild jumps right when you get back into the Editor (this was because every time the editor was opened, we had a progress value of zero, and then all of a sudden we would update to the current real progress).

cc @aforcier

### CODE REVIEW

**Comment by daniloercoli** [comment]
Reporting this here since I got the following issue testing this branch.
The app crashed while the media files were uploading, resulting in 2 media files in an inconsistent state in the editor. When you tap on one of them, the app asks if you want to stop the uploading of the file, but looking at the logging none of them are actually uploading to the server.
https://cloudup.com/cFNDmvsUD3i

**Comment by mzorz** [comment]
> The app crashed while the media files were uploading, resulting in 2 media files in an inconsistent state in the editor. When you tap on one of them, the app asks if you want to stop the uploading of the file

Just reproduced this in `develop`, opened issue: https://github.com/wordpress-mobile/WordPress-Android/issues/6455

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java [hunk 1]
```diff
@@ -409,6 +409,19 @@ public static float getMediaUploadProgressForPost(PostModel postModel) {
...
+        return MediaUploadHandler.getProgressForMedia(mediaModel);
+    }
+
+    public static List<MediaModel> getPendingMediaForPost(PostModel postModel) {
+        for (UploadingPost uploadingPost : sPostsWithPendingMedia) {
+            if (uploadingPost.postModel.getId() == postModel.getId()) {
+                return uploadingPost.pendingMedia;
+            }
+        }
+        return null;
```
Comment (aforcier) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java]: What do you think about returning `Collections.emptyList()` here instead? Then we can also annotate the method as returning `@NonNull` (and also drop [this check](https://github.com/wordpress-mobile/WordPress-Android/pull/6450/files#diff-38b6aea9cfff5f3e0e4b7389b44de602R435)).

Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java]: addressed in 2ba48bc

**Comment by aforcier** [comment]
Works well! :shipit:
