### PR TITLE
Fix stale height issue in account closure dialog

### LINKED ISSUE #18468: Fix dialog size issue on successful closure
For some reason, the Compose dialog does not change it's height after recomposition. I believe this is related with a known issue: https://issuetracker.google.com/issues/221643630. This task is to investigate this issue, and potential workarounds until it is resolved upstream.

One possible work-around worth a quick exploration is to set `usePlatformDefaultWidth` to false in the [`DialogProperties`](https://developer.android.com/reference/kotlin/androidx/compose/ui/window/DialogProperties#usePlatformDefaultWidth()). Though the issue is related with `height`, this seems to fix the stale height issue. But, this means we must also take on the responsibility of defining a `width` (instead of relying on the platform default).

### PR DESCRIPTION
**Pull request by mkevins**
Fixes #18468, #18469

### Description

This PR fixes a stale height issue in the success dialog of the account closure flow. It also makes a minor enhancement by disabling the username text input while the closure is in the pending state.

To test:

To make testing easier, it can be useful to apply the following patch, which will make account closure "fake". This makes it easier to try the flow multiple times without the need to keep creating and destroying accounts.

<details>
<summary>Fake closure patch</summary>

```patch
diff --git a/WordPress/src/main/java/org/wordpress/android/ui/prefs/accountsettings/AccountSettingsViewModel.kt b/WordPress/src/main/java/org/wordpress/android/ui/prefs/accountsettings/AccountSettingsViewModel.kt
index 420f6f3ca0..c087f69693 100644
--- a/WordPress/src/main/java/org/wordpress/android/ui/prefs/accountsettings/AccountSettingsViewModel.kt
+++ b/WordPress/src/main/java/org/wordpress/android/ui/prefs/accountsettings/AccountSettingsViewModel.kt
@@ -5,6 +5,7 @@ import androidx.lifecycle.viewModelScope
 import com.google.android.material.snackbar.Snackbar
 import kotlinx.coroutines.CoroutineDispatcher
 import kotlinx.coroutines.Job
+import kotlinx.coroutines.delay
 import kotlinx.coroutines.flow.MutableSharedFlow
 import kotlinx.coroutines.flow.MutableStateFlow
 import kotlinx.coroutines.flow.SharedFlow
@@ -333,17 +334,20 @@ class AccountSettingsViewModel @Inject constructor(
             _accountClosureUiState.value = uiState.copy(isPending = true)
 
             launch {
-                accountClosureUseCase.closeAccount { result ->
-                    when (result) {
-                        is CloseAccountResult.Success -> {
-                            _accountClosureUiState.value = Success
-                        }
-
-                        is CloseAccountResult.Failure -> {
-                            _accountClosureUiState.value = Error(result.error.errorType)
-                        }
-                    }
-                }
+                delay(5000)
+                _accountClosureUiState.value = Success
+
+//                accountClosureUseCase.closeAccount { result ->
+//                    when (result) {
+//                        is CloseAccountResult.Success -> {
+//                            _accountClosureUiState.value = Success
+//                        }
+//
+//                        is CloseAccountResult.Failure -> {
+//                            _accountClosureUiState.value = Error(result.error.errorType)
+//                        }
+//                    }
+//                }
             }
         }
     }
diff --git a/WordPress/src/main/java/org/wordpress/android/ui/prefs/accountsettings/components/AccountClosureUi.kt b/WordPress/src/main/java/org/wordpress/android/ui/prefs/accountsettings/components/AccountClosureUi.kt
index 43f742a29d..5652c24e93 100644
--- a/WordPress/src/main/java/org/wordpress/android/ui/prefs/accountsettings/components/AccountClosureUi.kt
+++ b/WordPress/src/main/java/org/wordpress/android/ui/prefs/accountsettings/components/AccountClosureUi.kt
@@ -35,7 +35,8 @@ fun AccountClosureUi(viewModel: AccountSettingsViewModel) {
                     it.errorType,
                 )
                 is Opened.Success -> DialogSuccessUi(
-                    onDismissRequest = { viewModel.userAction(ACCOUNT_CLOSED) }
+//                    onDismissRequest = { viewModel.userAction(ACCOUNT_CLOSED) }
+                    onDismissRequest = { viewModel.dismissAccountClosureDialog() },
                 )
             }
         }
```

</details>

1. Create or login with a disposable account (or any account without active purchases or Atomic sites)
2. Navigate to the account settings (Me :arrow_right: Account Settings)
3. Tap "Close Account"
4. Expect that a dialog is displayed requesting the user to type their username for confirmation
5. Enter the username
6. Expect a the dialog to go into a pending state briefly (spinner), and that the username input field becomes disabled
7. Expect a success dialog is displayed with an Ok button
8. Expect that the success dialog has a height that fits the contents (i.e. it should be shorter)

## Regression Notes
1. Potential unintended areas of impact
Closure dialog behavior

4. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

5. What automated tests I added (or what prevented me from doing so)
Adding UI tests for this task is out of scope

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by antonis — APPROVED** [review]
Thank you for tackling this @mkevins 🙇 
I've retested and everything worked as expected for me. The code also LGTM 🎉

File: WordPress/src/main/java/org/wordpress/android/ui/prefs/accountsettings/components/AccountClosureUi.kt [hunk 1]
```diff
@@ -2,11 +2,13 @@ package org.wordpress.android.ui.prefs.accountsettings.components
 
 import androidx.compose.runtime.Composable
 import androidx.compose.runtime.collectAsState
+import androidx.compose.ui.ExperimentalComposeUiApi
 import org.wordpress.android.ui.prefs.accountsettings.AccountSettingsViewModel
 import org.wordpress.android.ui.prefs.accountsettings.AccountSettingsViewModel.AccountClosureUiState.Opened
 import org.wordpress.android.ui.prefs.accountsettings.AccountSettingsViewModel.Companion.AccountClosureAction.ACCOUNT_CLOSED
 import org.wordpress.android.ui.prefs.accountsettings.AccountSettingsViewModel.Companion.AccountClosureAction.HELP_VIEWED
 
+@OptIn(ExperimentalComposeUiApi::class)
```
Comment (antonis) [inline WordPress/src/main/java/org/wordpress/android/ui/prefs/accountsettings/components/AccountClosureUi.kt:11]: TIL about `@OptIn` :)

Comment (mkevins) [reply WordPress/src/main/java/org/wordpress/android/ui/prefs/accountsettings/components/AccountClosureUi.kt:11]: I just realized that using this on `AccountClosureDialog` makes this annotation redundant :sweat_smile: . I'm not sure how this slipped through, since it is picked up as a lint error for me now, but it shouldn't affect the behavior :man_shrugging: . Originally, I had annotated at the file level, and then at some point followed the AS autocomplete tool which used the `@OptIn`.

**Comment by mkevins** [comment]
Thank you for testing this again!
