### PR TITLE
Catches SecurityException when the cursor fails to create

### LINKED ISSUE #18627: SecurityException: Content provider lookup org.wordpress.android.LocalMigrationContentProvider…
Sentry Issue: [JETPACK-ANDROID-22Y](https://a8c.sentry.io/issues/3896096809/?referrer=github_integration)

```
RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:7245)
	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7590)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2241)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2874)
	at android.os.Binder.execTransactInternal(Binder.java:1045)

SecurityException: Content provider lookup org.wordpress.android.LocalMigrationContentProvider failed: association not allowed with package org.wordpress.android
    at android.os.Parcel.createException(Parcel.java:2071)
    at android.os.Parcel.readException(Parcel.java:2039)
    at android.os.Parcel.readException(Parcel.java:1987)
    at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5401)
    at android.app.ActivityThread.acquireProvider(ActivityThread.java:6789)
...
(18 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by antonis**
Fixes #18627

## Description

This PR catches the `SecurityException` thrown when the `query` function is called in the `LocalMigrationContentResolver.getResultForEntityType`

This was indicates by the following shared stack trace
```
    at org.wordpress.android.localcontentmigration.LocalMigrationContentResolverKt.query(LocalMigrationContentResolver.kt:27)
    at org.wordpress.android.localcontentmigration.LocalMigrationContentResolver.getResultForEntityType$default
```

Related crashes:
* [JETPACK-ANDROID-9CH](https://a8c.sentry.io/issues/4307607863/?referrer=github_integration)
* [JETPACK-ANDROID-DQQ](https://a8c.sentry.io/issues/4572475623/?referrer=github_integration)
* [JETPACK-ANDROID-83N](https://a8c.sentry.io/issues/4265723926/?referrer=github_integration)

## To test:
Verify that the migration runs as expected

Note that I wasn't able to reproduce the specific crash that occurs only on `Android 10` ([related Android source](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/android10-release/services/core/java/com/android/server/am/ActivityManagerService.java#6780)).

## Regression Notes
1. Potential unintended areas of impact
Migration flow

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

3. What automated tests I added (or what prevented me from doing so)
Relied on existing tests

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:

- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationContentResolver.kt [hunk 1]
```diff
@@ -47,7 +47,11 @@ class LocalMigrationContentResolver @Inject constructor(
         }
     }.let { uriBuilder ->
         with(contextProvider.getContext().contentResolver) {
-            val cursor = query(uriBuilder, entityType, entityId)
+            val cursor = try {
+                query(uriBuilder, entityType, entityId)
+            } catch (e: SecurityException) {
+                return Failure(NullCursor(entityType, e))
+            }
```
Comment (mkevins) [inline WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationContentResolver.kt]: I wonder if we should use `runCatching` (to be consistent with the pattern in use) 🤔

Comment (mkevins) [reply WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationContentResolver.kt]: I've added [a branch with this suggestion](https://github.com/wordpress-mobile/WordPress-Android/compare/fix/18627-SecurityException...fix/18627-SecurityException--suggestion-new-error-class).

File: WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationError.kt [hunk 2]
```diff
@@ -6,7 +6,7 @@ import org.wordpress.android.localcontentmigration.LocalContentEntityData.Compan
 sealed class LocalMigrationError {
     sealed class ProviderError : LocalMigrationError() {
         data class NullValueFromQuery(val forEntity: LocalContentEntity) : ProviderError()
-        data class NullCursor(val forEntity: LocalContentEntity) : ProviderError()
+        data class NullCursor(val forEntity: LocalContentEntity, val throwable: Throwable? = null) : ProviderError()
```
Comment (mkevins) [inline WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationError.kt]: Maybe we should create a new `ProviderError` class for this (rather than repurposing `NullCursor` 🤔 ? Wdyt?

If you think this makes sense, I've added a branch with this suggestion [here](https://github.com/wordpress-mobile/WordPress-Android/compare/fix/18627-SecurityException...fix/18627-SecurityException--suggestion-new-error-class).

**Review by mkevins — COMMENTED** [review]
Thank you for investigating this and finding a way forward Antonis!

I've added a couple of comments (and a suggestion branch). Let me know what you think about it!

File: WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationError.kt (hunk 2 above)
Comment (antonis) [reply WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationError.kt]: > Maybe we should create a new ProviderError class for this (rather than repurposing NullCursor 🤔 

Thank you for your suggestion @mkevins! This makes sense 👍 
I've merged you branch on this PR.

File: WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationContentResolver.kt (hunk 1 above)
Comment (antonis) [reply WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationContentResolver.kt]: > I wonder if we should use runCatching (to be consistent with the pattern in use) 🤔

Great suggestion 👍 
I've pushed a minor fix https://github.com/wordpress-mobile/WordPress-Android/pull/19468/commits/5554e8485b036f829f496da7945f192522d10192 and merged your branch 🙇 

Ready for another pass :)

File: WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationError.kt (hunk 2 above)
Comment (mkevins) [reply WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationError.kt]: Awesome!

File: WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationContentResolver.kt (hunk 1 above)
Comment (mkevins) [reply WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationContentResolver.kt]: Oh, right, good catch! 😄

**Review by mkevins — APPROVED** [review]
I tested this on API 29 (Android 10), and was unable to reproduce the original crash on `trunk` (I tried with WordPress app in the logged in and logged out state).

I also verified that the changes in this PR do not introduce regressions in the existing migration flow. Though I couldn't verify via manual testing that this resolves the crash, it should in theory, since the caught exception should trigger a fallback to the non-migration flow (as other failures do).

Also, these changes should provide better error logging. Nice work!

**Comment by antonis** [comment]
Thank you for the prompt review and suggesting the improvements Matthew 🙇 
I'll proceed with merging the change :)
