### PR TITLE
Fix MediaSettingsScreen can't save image on atomic site

### LINKED ISSUE #8840: Media: Can't save image from media library on Atomic site
### Expected behavior

I expect to be able to save any media item in my site's media library to my device.

### Actual behavior

When I try to download a media item from a WordPress.com Atomic site, it doesn't download correctly.

I can download media from WordPress.com Simple, Jetpack, and self-hosted (non-Jetpack) sites.

### Steps to reproduce the behavior

1. On an Atomic site, go to the My Sites tab.
2. Open the Media section.
3. Tap on a media item (e.g. image) to open the details.
4. In the top right corner, tap the cloud icon (on a small screen, tap the ellipsis menu and select "Save").
5. Note that a toast message "Saving media to this device" appears.
6. Open your device files and look for the downloaded media file.

Result: The media file is not downloaded. On one device (moto e5 play with Android 8.1) I didn't see anything downloaded anywhere on the device. On another device (Nexus 9 with Android 7.1.1) I see this downloaded file that doesn't contain any filename or data:

screenshot_20181220-123131

##### Originally reported by user with two devices using WPAndroid 11.3 & 11.4.

Internal ref: p4a5px-2jX-p2

### PR DESCRIPTION
**Pull request by daniloercoli**
Fixes #8840 by making sure the default app-UA string is set on requests enqueued to the `DownloadManager`.

Note: The `AndroidDownloadManager` default UA string(s) -->  `AndroidDownloadManager/8.0.0 (Linux; U; Android 8.0.0; Android SDK built for x86 Build/OSR1.170901.043)` was blocked on our servers long time ago. We've removed the block yesterday and the app works already OK.

We also agreed that we should use the default app-UA string in the AndroidDownloadManager requests.

To test:
- Start the app
- Setup Charles proxy on your emulator
- Go to media
- Tap on a media, and try to download it locally
- The download should finish properly, and the pictures available in media gallery app.
- Go to Charles proxy (or equivalent) and check the user agent set on the request. It should be something like `Mozilla/5.0 (Linux; Android 8.0.0; Android SDK built for x86 Build/OSR1.170901.043; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/70.0.3538.80 Mobile Safari/537.36 wp-android/xxx`

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/media/MediaSettingsActivity.java [hunk 1]
```diff
@@ -991,6 +996,7 @@ private void saveMediaToDevice() {
         }
         request.allowScanningByMediaScanner();
         request.setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE);
+        request.addRequestHeader("User-Agent", WordPress.getDefaultUserAgent());
```
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/media/MediaSettingsActivity.java]: I think we should use `WordPress.getUserAgent()` instead. This adds application information as [explained here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/WordPress.java#L604-L627).
Checked the backend and effectively that's the common way we're using it to detect it's one of our apps back there.

Comment (daniloercoli) [reply WordPress/src/main/java/org/wordpress/android/ui/media/MediaSettingsActivity.java]: Oh right! I missed that method. Updated the PR.
