### PR TITLE
Stats - Do not serialize VolleyErrors

### LINKED ISSUE #2228: Crash Report 3.6: Fatal Exception: java.lang.RuntimeException
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.android.volley.ServerError)
       at android.os.Parcel.writeSerializable(Parcel.java:1316)
       at android.os.Parcel.writeValue(Parcel.java:1264)
       at android.os.Parcel.writeArray(Parcel.java:672)
       at android.os.Parcel.writeValue(Parcel.java:1251)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:618)
       at android.os.Bundle.writeToParcel(Bundle.java:1692)
       at android.os.Parcel.writeBundle(Parcel.java:636)
       at android.app.FragmentState.writeToParcel(Fragment.java:133)
       at android.os.Parcel.writeTypedArray(Parcel.java:1133)
       at android.app.FragmentManagerState.writeToParcel(FragmentManager.java:373)
       at android.os.Parcel.writeParcelable(Parcel.java:1285)
       at android.os.Parcel.writeValue(Parcel.java:1204)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:618)
       at android.os.Bundle.writeToParcel(Bundle.java:1692)
       at android.os.Parcel.writeBundle(Parcel.java:636)
       at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2755)
       at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3396)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5579)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.io.NotSerializableException: com.android.volley.NetworkResponse
       at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1364)
       at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1671)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1517)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1481)
       at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:979)
       at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:368)
       at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1074)
       at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1404)
       at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1671)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1517)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1481)
       at android.os.Parcel.writeSerializable(Parcel.java:1311)
       at android.os.Parcel.writeValue(Parcel.java:1264)
       at android.os.Parcel.writeArray(Parcel.java:672)
       at android.os.Parcel.writeValue(Parcel.java:1251)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:618)
       at android.os.Bundle.writeToParcel(Bundle.java:1692)
       at android.os.Parcel.writeBundle(Parcel.java:636)
       at android.app.FragmentState.writeToParcel(Fragment.java:133)
       at android.os.Parcel.writeTypedArray(Parcel.java:1133)
       at android.app.FragmentManagerState.writeToParcel(FragmentManager.java:373)
       at android.os.Parcel.writeParcelable(Parcel.java:1285)
       at android.os.Parcel.writeValue(Parcel.java:1204)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:618)
       at android.os.Bundle.writeToParcel(Bundle.java:1692)
       at android.os.Parcel.writeBundle(Parcel.java:636)
       at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2755)
       at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3396)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5579)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)

### PR DESCRIPTION
**Pull request by daniloercoli**
Fix #2228 by not serializing VolleyErrors as-is, but rewrite them into simple Exceptions (StatsError) before saving them.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/stats/StatsAbstractListFragment.java [hunk 1]
```diff
@@ -131,6 +132,19 @@ public void onCreate(Bundle savedInstanceState) {
...
         //AppLog.d(AppLog.T.STATS, this.getTag() + " > saving instance state");
+
+        // Do not serialize VolleyError, but rewrite in a simple stats Exception.
+        // VolleyErrors should be serializable, but for some reason they are not.
+        // FIX for https://github.com/wordpress-mobile/WordPress-Android/issues/2228
+        if (mDatamodels != null) {
+            for (int i=0; i < mDatamodels.length; i++) {
+                if (mDatamodels[i] != null && mDatamodels[i] instanceof VolleyError) {
+                    VolleyError currentVolleyError = (VolleyError) mDatamodels[i];
+                    mDatamodels[i] = StatsUtils.rewriteVolleyError(currentVolleyError, getString(R.string.error_refresh_stats));
```
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/StatsAbstractListFragment.java]: I don't like that much. We shouldn't pass exceptions (VolleyError or any other kind of exceptions) from a part of the app to another. I know we're going to rework `mDatamodels` and Stats models, but can't we just put `null` in `mDatamodels[i]` if an exception occurs?

Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/StatsAbstractListFragment.java]: If an error error object is received from the StatsService the UI displays the error message to the user (for some kind of errors, not all).
When the error is received, it's stored in the mDatamodel[i], and restored upon resume, like any other datatypes.

If mDatamodel[i] is null, an empty UI is shown, that says something like "No stats data for this period".
So to reply to your question, yes we can use null, in fact in the first version of this patch I had set the datamodel to null, but then added the logic to save the error and keep the UI is consistent upon device rotation or resume.
Otherwise, if we set it to null and the user rotates the device the UI is rebuilt with an empty mDatamodel and the "No stats data for this period" is shown.

**Comment by maxme** [comment]
:shipit:
