### PR TITLE
Issue/5434 media browser image load

### LINKED ISSUE #5434: Media browser fails to load images
Local images (images that are in the process of being uploaded, or failed to upload) don't appear the first time they're requested, resulting in either an empty image or an incorrect image showing up.

The way local images are loaded & displayed could use an overhaul.

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #5434 - This PR fixes a number of problems with the media browser.

* Local media fail to appear the first time they're requested, resulting in either missing or incorrect images
* No default image was being set while downloading remote images, also resulting in either missing or incorrect images
* Fetching local images was needlessly complicated
* Remote images in private sites were pixelated due to being requested at the wrong size
* In-flight image requests were being canceled when the view was recycled, which meant the next time the image was requested it would be re-downloaded since it wasn't being cached

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridAdapter.java [hunk 1]
```diff
@@ -329,62 +311,33 @@ public int getLocalMediaIdAtPosition(int position) {
         return INVALID_POSITION;
     }
 
-    private synchronized void loadLocalImage(final String filePath, final FadeInNetworkImageView imageView) {
```
Comment (tonyr59h) [inline WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridAdapter.java]: 👍

**Comment by tonyr59h** [comment]
Looks great _and_ runs great! I like the new image placeholder style, fits much nicer with the rest of the app.

I noticed an icon in the middle of the Themes placeholder images, I think it could be a nice touch to have one for images. Thoughts @mattmiklic?

**Comment by tonyr59h** [comment]
:shipit:
