### PR TITLE
Try to fix NPE in PostUploadHandler 

### LINKED ISSUE #7990: Crash 10.2: NPE in PostUploadHandler - prepareUploadAnalytics
```
Caused by java.lang.NullPointerException
       at org.wordpress.android.ui.uploads.PostUploadHandler$UploadPostTask.prepareUploadAnalytics(PostUploadHandler.java:275)
       at org.wordpress.android.ui.uploads.PostUploadHandler$UploadPostTask.doInBackground(PostUploadHandler.java:254)
       at org.wordpress.android.ui.uploads.PostUploadHandler$UploadPostTask.doInBackground(PostUploadHandler.java:188)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:848)
```
internal ref: `5b373e1a6007d59fcd3c70f6`

### PR DESCRIPTION
**Pull request by daniloercoli**
Fixes #7990 by synchronizing over `sQueuedPostsList` before setting/preparing `sCurrentUploadingPostAnalyticsProperties` map with properties about the post.

I noticed that in other parts of the code we're synchronizing over `sQueuedPostsList` before making changes to the 3 static variables `sQueuedPostsList, sCurrentUploadingPost, sCurrentUploadingPostAnalyticsProperties`. Instead in `prepareUploadAnalytics`, where does the crash happen, we're not sync over `sQueuedPostsList`.
In theory the code added in this PR isn't necessary, but for some reason the NPE is happening so I decided to add this synch guard, and prevent other NPE. Also tried to reproduce the problem, and checked for potential racing conditions, but had no luck with both of them.

cc @mzorz

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadHandler.java [hunk 1]
```diff
@@ -269,42 +269,49 @@ private boolean hasGallery() {
...
+                    sCurrentUploadingPostAnalyticsProperties.put("with_videos", true);
+                }
+                if (mHasCategory) {
+                    sCurrentUploadingPostAnalyticsProperties.put("with_categories", true);
+                }
+                if (!mPost.getTagNameList().isEmpty()) {
+                    sCurrentUploadingPostAnalyticsProperties.put("with_tags", true);
+                }
             }
-            sCurrentUploadingPostAnalyticsProperties.put("via_new_editor", AppPrefs.isVisualEditorEnabled());
```
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadHandler.java]: we're ditching this var here, I'd wonder if we need it? maybe let's not remove it here in this PR, wdyt?

Comment (daniloercoli) [reply WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadHandler.java]: Right, re-introduced it! will remove in a future PR.
