### PR TITLE
Reader move tab layout to parent part 3.5 - bug fixes

### LINKED ISSUE #11849: Reader Master Issue: Enable horizontal swipe gesture in the Reader
Goal of this issue is to enable swipe gesture on the Reader and prepare the ground for the Reader Improvements project. We plan to refactor/rewrite one tab (following, discover, ..) at a time so we can release the changes continuously.
The plan for this PR is to introduce a new parent fragment with a tablayout - each tab would be an instance of ReaderPostListFragment. We'll need to do several changes in order to support having multiple instances of the ReaderPostListFragment at the same time. The current implementation uses a single instance of the ReaderPostListFragment and only changes filtering criteria when a different tab is selected.

Note: We started tracking the related PRs and issues in this ticket. However, as the number of issues increased we decided to start creating real issues and adding them to the "Reader Improvements" board. So the list below is not complete.

Created PRs
- https://github.com/wordpress-mobile/WordPress-Android/pull/11840 - Introduce Tablayout in parent fragment
- https://github.com/wordpress-mobile/WordPress-Android/pull/11848 - Remove unnecessary code from ReaderPostListFragment
- https://github.com/wordpress-mobile/WordPress-Android/pull/11867 - Move NewsCard to ReaderFragment
- https://github.com/wordpress-mobile/WordPress-Android/pull/11881 - Bug fixes
- https://github.com/wordpress-mobile/WordPress-Android/pull/11890 - Move SubFilter component into it's own VM
 - https://github.com/wordpress-mobile/WordPress-Android/pull/11890 - Restore lastly selected tab
- https://github.com/wordpress-mobile/WordPress-Android/pull/11902#pullrequestreview-410802534 - Fix "discover" button on the empty screen

Remaining issues
- [x] SubFilter component on the following tab doesn't show any data (the issue is that ReaderPostListViewModel is tied to ReaderPostListFragment's scope but the component is looking for it in WPMainActivity) (fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11872)
- [x] Move "NewsCard" to the ReaderFragment - currently it's shown on all the tabs (fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11867)
- [x] Verify a correct tag is loaded in the subfilter component when you add a new tag in the tag settings(fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11872)
- [x] Move TabLayout into the ReaderFragment (fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11840)
- [x] Move Toolbar into the ReaderFragment (fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11899)
- [x] Revert b558f2a388932508dcb966c20578cf2772be21b2 this commit and come up with a proper fix. (Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11881)
- [x] If I keep switching tabs long enough the app sometime shows "discover" content on all the tabs (it keeps happening quite often on self-hosted site) (fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11890)
- [x] Store and reopen lastly selected tab after app restart (fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11890)
- [x] Verify dark mode - especially subfilter component (fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11899)
---------------------------------------
- [-] The tabs names are different from before (not sure if it is intended), I get the below instead of the Following, Discover, Likes, Saved names (check what field we use for the tab names - also check if translations work, because I had troubles with translations when using a different field for the names) (created issue - https://github.com/wordpress-mobile/WordPress-Android/issues/11905)
- [-] "Time spent in reader" tracking is broken now, since we have multiple instances of the fragment. It should be moved to the ReaderFragment. (created issue - https://github.com/wordpress-mobile/WordPress-Android/issues/11906)
- [-] Saved posts empty screen - "discover" button doesn't work (created issue - https://github.com/wordpress-mobile/WordPress-Android/issues/11900)
- [-] When the user restarts the app and half-swipes in the reader the next fragment isn't pre-loaded (created issue - https://github.com/wordpress-mobile/WordPress-Android/issues/11907)
- [-] Move the Search into the ReaderFragment (Created ticket https://github.com/wordpress-mobile/WordPress-Android/issues/11908)
- [-] Initial/default tab should be discover (created ticket - https://github.com/wordpress-mobile/WordPress-Android/issues/11909)
- [-] When you sign up with a new user and you have no sites the empty states and the content can overlap like this below (they are drawn on top of each other) - HIGH PRIORITY! (created issue - https://github.com/wordpress-mobile/WordPress-Android/issues/11910)
- [-] Verify deeplinks and regular `startActivity` navigation works as expected (created notes on the ReaderImprovements board)
- [-] Verify re-blog feature works as expected(created notes on the ReaderImprovements board)

### PR DESCRIPTION
**Pull request by malinajirka**
Partially fixes #11849

This is a 3.5th PR in a series of PRs which is trying to introduce a regular TabLayout+ViewPager2 in the main Reader view. The current implementation uses FilteredRecyclerView component (which is not a RecyclerView :P) that has some downsides (eg. swipe gesture doesn't work).

- The uiState is propagated only when the tags list isn't empty
- The logic related to fetching the tags from the server was moved to the ReaderViewModel
- LoadReaderTabsUseCase manually adds "following" tab when the user is logged in to a self-hosted site (this logic was copied from `develop`)
- Fixes crash when the onPageChange listener was registered multiple times if the tags were loaded more than once

To test:
- Clear app data
1. Log into a self-hosted site and make sure you see "following, discover, saved" tabs
-----------------
- Clear app data
1. Add Thread.sleep(5000) to https://github.com/wordpress-mobile/WordPress-Android/blob/c1a021ff0f2ef2f1345d09db8b2380f6129a14d0/WordPress/src/main/java/org/wordpress/android/ui/reader/services/update/ReaderUpdateLogic.java#L147
2. Start the app
3. Log in
4. Go to "Reader" tab
5. Notice only "following" is shown
6. Wait for 5s - the remaining tabs should appear
7. Click on any of the tabs and make sure the app doesn't crash

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/test/java/org/wordpress/android/ui/reader/viewmodels/ReaderViewModelTest.kt [hunk 1]
```diff
@@ -0,0 +1,123 @@
...
+    }
+
+    private fun <T> testWithEmptyTags(block: suspend CoroutineScope.() -> T) {
+        test {
+            whenever(loadReaderTabsUseCase.loadTabs()).thenReturn(ReaderTagList())
+            block()
+        }
+    }
+
+    private fun createNonEmptyReaderTagList(): ReaderTagList {
```
Comment (planarvoid) [inline WordPress/src/test/java/org/wordpress/android/ui/reader/viewmodels/ReaderViewModelTest.kt:120]: What do you think about making this a `testWithNonEmptyTags` function like the one above for consistency?

Comment (malinajirka) [reply WordPress/src/test/java/org/wordpress/android/ui/reader/viewmodels/ReaderViewModelTest.kt]: Good point;), fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/11881/commits/88b554dc090c97b5f2a9bd7e4af0d0c702347225
