### PR TITLE
Guard saving to smartlock on Login

### LINKED ISSUE #7182: Crash report 9.2: NPE in LoginActivity.saveCredentialsInSmartLock
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void org.wordpress.android.ui.accounts.SmartLockHelper.saveCredentialsInSmartLock(java.lang.String, java.lang.String, java.lang.String, android.net.Uri)' on a null object reference
       at org.wordpress.android.ui.accounts.LoginActivity.saveCredentialsInSmartLock(LoginActivity.java:498)
       at org.wordpress.android.login.LoginBaseFormFragment.saveCredentialsInSmartLock(LoginBaseFormFragment.java:274)
       at org.wordpress.android.login.LoginUsernamePasswordFragment.finishLogin(LoginUsernamePasswordFragment.java:460)
       at org.wordpress.android.login.LoginUsernamePasswordFragment.onSiteChanged(LoginUsernamePasswordFragment.java:513)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
       at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5348)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)
```

Please fix this one in the branch `release/9.2`

### PR DESCRIPTION
**Pull request by hypest**
Fixes #7182 

This PR does 2 things:
1. drops the attempt to save to SmartLock for Passwords if the Login activity is in the SELFHOSTED_ONLY mode. That mode doesn't setup SmartLock so, drop saving. Ticket #7300 is created as an enhancement to add such functionality.
2. drops the attempt to save to SmartLock for Passwords if `mSmartLockHelper` is `null`. The circumstances for that case are not know and for now, we'll just drop the save attempt and log some data in hope to debug the issue.

To test #1:
1. Have the app logged in to selfhosted sites only
2. Go to "MySite"
3. Tap on "Switch site"
4. Tap on the "+" button at the top right
5. Enter the WPCOM site's address and hit "Next"
6. Enter the WPCOM username and password and hit "Next"
7. After a little while, the app will have logged in to WPCOM without a crash

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java [hunk 1]
```diff
@@ -515,6 +516,28 @@ public void setHelpContext(String faqId, String faqSection) {
     @Override
     public void saveCredentialsInSmartLock(@Nullable final String username, @Nullable final String password,
                                            @NonNull final String displayName, @Nullable final Uri profilePicture) {
+        if (getLoginMode() == LoginMode.SELFHOSTED_ONLY) {
```
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java]: minor nit: can we add a `// TODO` here so we make sure to mark this as something that needs be removed?

Comment (hypest) [reply WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java]: Hmm, I'd consider that an enhancement (opened https://github.com/wordpress-mobile/WordPress-Android/issues/7300 to track that) since the selfhosted flow is not supposed to be a primary _WPCOM_ flow (and SmartLock-for-Passwords is only utilized for WPCOM anyway). Adding a `// TODO` would indicate that this is something that _needs_ to be done, but I'm not sure that's the case. WDYT?

Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java]: Ah - I understand the intention of this change better now. You're right, that'd be an enhancement. Thanks for the clarification!

**Comment by mzorz** [comment]
:shipit:

**Comment by mzorz** [comment]
(tested, works as intended)
