### PR TITLE
Magic Link: Error handling & Network check

### LINKED ISSUE #5393: Login: Need error message when attempting magic link login with no network
### Expected behavior
To see an error message saying I can't log in with no network

### Actual behavior
The app crashes, and on re-opening it gives me a weird logged-out interface:

Restarting the app again afterward gives me the login screen again.

### Steps to reproduce the behavior
1) Disable the network
2) Try to log in via magic link

Attempting to log in via password gives a "No network available" error

##### Tested on Nexus 6P, Android 7.1.2, wp alpha-39

### PR DESCRIPTION
**Pull request by oguzkocer**
Fixes #5393. This PR improves the error handling for magic link requests. We were never removing the dialog on error, which was getting the users stuck on that screen. This happens on any kind of error, not just the network one mentioned in the original issue. I also added a check for network reach-ability before the request as we do in many other places.

I had to remove the `Snackbar` and use the `Toast` instead. We don't have a `CoordinatorLayout` in the fragment or activity and even after adding it, the Snackbar never appears for me. I'd really appreciate it if there are any suggestions on how to make the Snackbar work instead.

To test:
* Disable the network
* Try to log in via magic link and make sure you get no network available error
* Comment out the following code and make sure there is an error shown and the dialog dismissed (although since it's too fast, you'll probably not see the dialog)

```
if (!NetworkUtils.isNetworkAvailable(getActivity())) {
    ToastUtils.showToast(getActivity(), R.string.no_network_message, ToastUtils.Duration.LONG);
    return;
}
```

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/login/MagicLinkRequestFragment.java [hunk 1]
```diff
@@ -150,9 +155,8 @@ public void onErrorResponse(VolleyError error) {
                 HashMap<String, String> errorProperties = new HashMap<>();
                 errorProperties.put(ERROR_KEY, error.getMessage());
                 AnalyticsTracker.track(AnalyticsTracker.Stat.LOGIN_MAGIC_LINK_FAILED, errorProperties);
-                if (getView() != null) {
-                    Snackbar.make(getView(), R.string.magic_link_unavailable_error_message, Snackbar.LENGTH_SHORT);
-                }
+                mProgressDialog.cancel();
+                ToastUtils.showToast(getActivity(), R.string.magic_link_unavailable_error_message, ToastUtils.Duration.LONG);
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/login/MagicLinkRequestFragment.java]: There should be an `isAdded()` check before using `getActivity()` in case the fragment is no longer valid (the `getView() != null` check previously did this).

**Comment by nbradbury** [comment]
> I'd really appreciate it if there are any suggestions on how to make the Snackbar work instead.

I think we're fine using a Toast instead of a Snackbar here.

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/login/MagicLinkRequestFragment.java (hunk 1 above)
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/login/MagicLinkRequestFragment.java]: Fixed in f963cb6f26f114a5eda48101092481ffcd0e0571

**Comment by nbradbury** [comment]
:shipit:
