### PR TITLE
Fix #4058: Fix some embeds by injecting a specific js resource when we load the webview

### LINKED ISSUE #4058: Reader: Instagram embeds are empty
If a post contains an Instagram embed, the embed frame and caption appear correctly in reader detail but the embedded image is blank.

device-2016-05-04-170543

### PR DESCRIPTION
**Pull request by maxme**
Fix #4058: Fix some embeds by injecting a specific js resource when we load the webview

Twitter and Tumblr don't need anything, they were already working in the Reader. Here are some screenshots from a [test post ](https://taliwutblog.wordpress.com/2017/04/04/instagram-embed/):

screenshot_1491470499
screenshot_1491470502
screenshot_1491470769
screenshot_1491470777

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostRenderer.java [hunk 1]
```diff
@@ -113,24 +118,37 @@ public void onTagFound(String imageTag, String imageUrl) {
...
             public void onTagFound(String tag, String src) {
                 replaceIframeTag(tag, src);
             }
         };
-        ReaderIframeScanner scanner = new ReaderIframeScanner(mRenderBuilder.toString());
+        ReaderIframeScanner scanner = new ReaderIframeScanner(content);
         scanner.beginScan(iframeListener);
     }
 
+    private Set<String> injectJSForSpecificEmbedSupport(String content) {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostRenderer.java]: This could use a comment which clearly explains its purpose.

**Comment by nbradbury** [comment]
The Facebook embeds in your two posts aren't showing up for me (N6 emulator, API 23). All the others work, though.

File: WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderEmbedScanner.java [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+                "https://connect.facebook.net/en_US/sdk.js#xfbml=1&amp;version=v2.8");
+    }
+
+    public void beginScan(ReaderHtmlUtils.HtmlScannerListener listener) {
+        if (listener == null) {
+            throw new IllegalArgumentException("HtmlScannerListener is required");
+        }
+
+        for (Pattern pattern : mKnownEmbeds.keySet()) {
+            if (pattern.matcher(mContent).find()) {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderEmbedScanner.java]: This sort of subverts `HtmlScannerListener` by returning the JS to insert as the `src` parameter, but it is a clean solution. This class really needs to be commented, though, to make it clear what it's doing.

File: WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderEmbedScanner.java [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+import java.util.regex.Pattern;
+
+public class ReaderEmbedScanner {
+    private final String mContent;
+
+    private final HashMap<Pattern, String> mKnownEmbeds = new HashMap<>();
+
+    public ReaderEmbedScanner(String contentOfPost) {
+        mContent = contentOfPost;
+        mKnownEmbeds.put(Pattern.compile("<blockquote[^<>]class=\"instagram-", Pattern.CASE_INSENSITIVE),
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderEmbedScanner.java]: There's likely nothing we can do about this, but hard-coding the URLs here seems fragile.

File: WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderEmbedScanner.java (hunk 2 above)
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderEmbedScanner.java]: I agree, I wanted to avoid another kind of listener for a very similar purpose.

**Comment by maxme** [comment]
I added a couple of comments in 2c5add4 - 
Known issue, won't fix: Facebook embeds don't work with all Webviews.

**Comment by nbradbury** [comment]
:shipit:
