### PR TITLE
Issue/6239 post upload notifications tap actions

### LINKED ISSUE #6239: Media: confirm notifications tap actions
using branch `feature/async-media`
Confirm success/failure notifications both direct the user to the post list for that site

### CASE A SUCCESS:
1. choose a site
2. start a new post
3. start a media upload for that post
4. exit the editor
5. repeat steps 1-4 with another site
6. wait till 2 “Post uploaded” notifications are shown.
7. now tap on the finish notification for the first post
8. observe the user is taken to the post list for that site
9. now tap on the finish notification for the second post
10. observe the user is taken to the post list for that site.

### CASE B FAILURE:
1. choose a site
2. start a new post
3. start a media upload for that post
4. exit the editor
5. repeat steps 1-4 but switching to another site
6. make both uploads fail, for example by interrupting the network connection. Wait till 2 “Upload failed” notifications are shown.
7. now tap on the error notification for the first post
8. observe the user is taken to the post list for that site
9. now tap on the error notification for the second post
10. observe the user is taken to the post list for that site.

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #6239 

To test:
Follow instructions in the issue and confirm it works as described in there.

cc @aforcier

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/services/PostUploadNotifier.java [hunk 1]
```diff
@@ -137,18 +137,19 @@ public void updateNotificationSuccess(PostModel post, SiteModel site, boolean is
...
         // Tap notification intent (open the post list)
         Intent notificationIntent = new Intent(mContext, PostsListActivity.class);
         notificationIntent.addFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP);
         notificationIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
         notificationIntent.putExtra(WordPress.SITE, site);
         notificationIntent.putExtra(PostsListActivity.EXTRA_VIEW_PAGES, post.isPage());
-        PendingIntent pendingIntentPost = PendingIntent.getActivity(mContext, 0,
-                notificationIntent, PendingIntent.FLAG_UPDATE_CURRENT);
+        PendingIntent pendingIntentPost = PendingIntent.getActivity(mContext,
+                (int)notificationId,
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/services/PostUploadNotifier.java]: What are the implications of coercing this `long` into an `int` if the `long` is greater than `Integer.MAX_VALUE`? I know the coercion will work, but wasn't sure if does this could break something else.

**Comment by nbradbury** [comment]
@mzorz I got this crash while waiting for the media to upload (Case A):

```
E/WordPress-POSTS: Permission Denial: not allowed to send broadcast android.intent.action.MEDIA_MOUNTED from pid=20725, uid=10084
    java.lang.SecurityException: Permission Denial: not allowed to send broadcast android.intent.action.MEDIA_MOUNTED from pid=20725, uid=10084
    at android.os.Parcel.readException(Parcel.java:1684)
    at android.os.Parcel.readException(Parcel.java:1637)
    at android.app.ActivityManagerProxy.broadcastIntent(ActivityManagerNative.java:3537)
    at android.app.ContextImpl.sendBroadcast(ContextImpl.java:881)
    at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:421)
    at org.wordpress.android.ui.posts.EditPostActivity.addLastTakenPicture(EditPostActivity.java:1885)
    at org.wordpress.android.ui.posts.EditPostActivity.access$3900(EditPostActivity.java:149)
    at org.wordpress.android.ui.posts.EditPostActivity$14.done(EditPostActivity.java:1847)
    at org.wordpress.android.util.WPMediaUtils$1.onClick(WPMediaUtils.java:133)
    at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6119)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

File: WordPress/src/main/java/org/wordpress/android/ui/posts/services/PostUploadNotifier.java (hunk 1 above)
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/services/PostUploadNotifier.java]: Good catch! In this case we just need some number that is different than the rest of possible numbers that we are using, and given it is not likely that anyone is going to upload more than 2 posts at the very same time, it's easier to just use a combination of the siteId plus postId (which in practice are always numbers way lower than 65535).
So yes, theoretically it can happen, but practically it won't :)

**Comment by mzorz** [comment]
Good catch @nbradbury ! just updated the branch. Ready for a new try 👍

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.java [hunk 2]
```diff
@@ -36,39 +36,73 @@ public void onCreate(Bundle savedInstanceState) {
...
+        if (intent.hasExtra(EXTRA_VIEW_PAGES)) {
+            boolean isPage = intent.getBooleanExtra(EXTRA_VIEW_PAGES, false);
+            bPageHasChanged = isPage != mIsPage;
+        }
+        mIsPage = intent.getBooleanExtra(EXTRA_VIEW_PAGES, false);
+
+        boolean bSiteHasChanged = false;
+        if (intent.hasExtra(WordPress.SITE)) {
+            SiteModel site = (SiteModel) intent.getSerializableExtra(WordPress.SITE);
+            bSiteHasChanged = site.getId() != mSite.getId();
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.java]: It's possible for `mSite` to be null here.

Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.java]: That would actually be a rare condition - if we get to this point then we already went through `onCreate` at least once, where `mSite` is instantiated. Also while technically in `onCreate` we might get a possibility that someone calls `PostsListActivity` without sending the `site` extra, I've checked that all paths to creating a new `PostListActivity` provide it with a `WordPress.SITE` extra as well. 
We can still add the null check if you think that's clearer?

Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.java]: I think we should check for null. After all, we checked for null in `onCreate()` prior to this PR.

Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.java]: 👍  addressed in 432261f

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.java [hunk 3]
```diff
@@ -36,39 +36,75 @@ public void onCreate(Bundle savedInstanceState) {
...
+        handleIntent(intent);
+    }
+
+    private void handleIntent(Intent intent) {
+        mIsPage = intent.getBooleanExtra(EXTRA_VIEW_PAGES, false);
+
+        // get new intent extras and compare whether the running instance of PostsListActivity has
+        // the same values or not. If not, we need to create a new fragment and show the corresponding
+        // requested content
+        boolean bPageHasChanged = false;
```
Comment (aforcier) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.java]: What's the reason for the Hungarian-style type prefix here? We don't use that anywhere else to my knowledge, could we just use `pageHasChanged`?

Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.java]: my past is chasing me 👴 LOL good catch addressed in 9d786fa

**Comment by nbradbury** [comment]
:shipit:
