### PR TITLE
Aztec - Switch the `Title` field EditText

### LINKED ISSUE #580: New posts can be created on hidden blogs
Steps to reproduce:
1. Signin with a user who owns at least 2 blogs
2. Go to "Settings" -> "Show all blogs" and back
3. Open the drawer, notice all blogs are in the blogs drop down
4. Go to "Settings" -> hide the first blog and back
5. Open the drawer, notice the first blog is not in the blogs drop down
6. Create a new post and notice the first blog (hidden) appears as the action bar title

### PR DESCRIPTION
**Pull request by daniloercoli**
The `title` field in AztecEditorFragment is a `AztecText` object. Since there is no formatting, no advanced features on the title we can switch back to EditText.

Don't think this will fix https://github.com/wordpress-mobile/AztecEditor-Android/issues/580, but didn't try.

### CODE REVIEW

**Comment by maxme** [comment]
This doesn't fix wordpress-mobile/AztecEditor-Android#580 - removing the input filter on the title fixes the issue.

File: libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java [hunk 1]
```diff
@@ -129,7 +129,7 @@
     private boolean mEditorWasPaused = false;
     private boolean mHideActionBarOnSoftKeyboardUp = false;
 
-    private AztecText title;
+    private org.wordpress.android.editor.SourceViewEditText title;
```
Comment (maxme) [inline libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java]: Not a fan of using 2 different classes with the same name here, should we just rename the one in `org.wordpress.android.editor` to a more generic name since it's only a listening for IMEBack events?

**Comment by maxme** [comment]
Note: that I tried to replace the input filter with a text watcher doing the same thing to prevent newlines and it works fine with Swype.

**Comment by maxme** [comment]
Pushed a commit in here, if you want to have a look: https://github.com/wordpress-mobile/WordPress-Android/commit/189e467f772a852c9ef2cd5a03a27fcbcc209a3d
