### PR TITLE
Fixing support for reader page jump

### LINKED ISSUE #7654: Reader: anchor "page jump" links don't work in the Reader view
### Expected behavior

When viewing a post that contains anchor links ("page jumps"), I expected to be taken to section that's linked to in the post.

### Actual behavior

Tapping on the the anchor links has no effect when viewed within the app. The links work correctly when selected in a browser (both from the Reader and the site itself).

### Steps to reproduce the behavior

1. Follow the steps in [this support documentation](https://en.support.wordpress.com/splitting-content/page-jumps/) to add "page jumps" to a post.

2. View the post from within the app's Reader and tap on the anchor links.

##### Tested on Pixel, Android 8.1.0, alpha-107

Reported in 275749-h. iOS version of issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/9140.

### PR DESCRIPTION
**Pull request by develric**
Fixes #7654 

Inspired by a @khaykov comment [here](https://github.com/wordpress-mobile/WordPress-Android/issues/7654#issuecomment-640883823) I tried to further explore that solution in this PR.

Result below

<p align="center">
  
</p>

## To test

You can use this link to the post shown in the gif https://demo2020061600.wordpress.com/2020/07/31/up-bottom-2/
- check the page jump up to bottom works
- check the page jump bottom up works
- check the external link works
- smoke test the reader post detail

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt [hunk 1]
```diff
@@ -1504,6 +1504,19 @@ class ReaderPostDetailFragment : Fragment(),
         return true
     }
 
+    override fun onPageJumpClick(pageJump: String?): Boolean {
+        val jsWasEnabled = readerWebView.settings.javaScriptEnabled
+
+        readerWebView.settings.javaScriptEnabled = true
+
+        readerWebView.evaluateJavascript("document.getElementById('$pageJump').offsetTop") {
+            val yOffset = (readerWebView.scale * it.toFloat()).toInt()
```
Comment (khaykov) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt:1513]: AS tells me that scale getter is deprecated. Do you think we can use an alternative? StackOverflow suggests `getResources().getDisplayMetrics().density`, but I haven't tried it :)

**Review by khaykov — CHANGES_REQUESTED** [review]
@develric thanks for taking over this! It works amazingly 👍 

I noticed just one issue - if the anchor does not exist on the webpage, tapping on the link will crash the app:

```
org.wordpress.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.wordpress.android, PID: 19162
    java.lang.NumberFormatException: For input string: "null"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
        at java.lang.Float.parseFloat(Float.java:451)
        at org.wordpress.android.ui.reader.ReaderPostDetailFragment$onPageJumpClick$1.onReceiveValue(ReaderPostDetailFragment.kt:1513)
        at org.wordpress.android.ui.reader.ReaderPostDetailFragment$onPageJumpClick$1.onReceiveValue(ReaderPostDetailFragment.kt:129)
        at hm.a(Unknown Source:2)
        at org.chromium.android_webview.AwContents.a(PG:1020)
        at zp.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by develric** [comment]
Hey @khaykov 👋! Thanks for the review and spotting that issue 🙇‍♂️. I tried to fix it (also adding a Toast in case the landing page jump cannot be found). Your suggestion on using `density` seems to work well for me 😊 ! Let me know and thanks 🙇‍♂️!

PS: updated the test page to include a jump to a missing anchor reference if it can come handy for testing.

**Review by khaykov — APPROVED** [review]
Thanks for the fix! Works well 👍
