### PR TITLE
Fix Media Browser message after adding or removing a photo

### LINKED ISSUE #7304: Media Browser: "You don't have any images" message is visible after adding a photo.
Steps to reproduce:

1. Open empty media library.
2. From the add menu at the top right, take a photo.
3. Make sure photo is added to the media library.
4. Notice that "You don't have any images" is still visible. 

screenshot_1519708679

Tested on Nexus 5X API 25 emulator.

### PR DESCRIPTION
**Pull request by jorgecasariego**
Fixes #7304 

To test:

**Test 1**
1. Open empty media library.
2. From the add menu at the top right, take a photo.
3. Make sure photo is added to the media library.
4. "You don't have any images" is no more visible.

**Test 2**
1. Open media library.
2. Click on the photo taken in **test 1** to show File Details
3. Delete the photo 
4. The screen is empty with the message:"You don't have any images."

Tested on Nexus 5X API 25 emulator.

cc @khaykov @theck13

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridFragment.java [hunk 1]
```diff
@@ -468,6 +468,7 @@ public void onMediaListFetched(OnMediaListFetched event) {
     void reload() {
         if (isAdded()) {
             getAdapter().setMediaList(getFilteredMedia());
+            setFilter(mFilter);
```
Comment (theck13) [inline WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridFragment.java]: The `setFiler` method contains the `getAdapter().setMediaList(getFilteredMedia())` statement so we can remove it from the `reload` method to avoid duplicate calls.

Comment (jorgecasariego) [reply WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridFragment.java]: After changing RecyclerView to EmptyViewRecyclerView I deleted the `setFilter` method

**Comment by jorgecasariego** [comment]
After changing from RecyclerView to `EmptyViewRecyclerView` is working fine Tes1, Test2 and your Test with multiple images.

But I'm noticing a strange behavior that I don't know if it needs to be fixed in this PR or if it's better to create a new issue.

**Test:**
1. Add one or more images
2. Move to Tab `Documents`
2. Search for a value (any value)
3. Tap the back button of the SearchView without clear the text
4. Notice that you're still in `Document` tab but now showing the images added in (1)



**The expected result** after pressing the the  back button of the SearchView should be an empty screen with the message:

_"You don't have any documents"_

A partial solution I added to this PR was call to `reloadMediaGrid()` method in MediaBrowserActivity.  Now, after tap the back button of SearchView _it shows the desired message if we don't write anything in SearchView_

**Comment by jorgecasariego** [comment]
@theck13 I create a new issue (#7398) to manage the incorrect behavior when displaying search results

Just let me know  if I need to do another change to this PR.

File: WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java [hunk 2]
```diff
@@ -516,6 +516,8 @@ public boolean onMenuItemActionCollapse(MenuItem item) {
 
         enableTabs(true);
 
+        reloadMediaGrid();
```
Comment (theck13) [inline WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java]: Since we'll handle the search behavior in https://github.com/wordpress-mobile/WordPress-Android/issues/7398, we should probably remove this addition to keep the changes in their respective pull request.

Comment (jorgecasariego) [reply WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java]: Done!
