### PR TITLE
Fix string translation in Stats

### LINKED ISSUE #8114: Some strings use the previous language when it is changed in app on API > 24
### Expected behavior

When the language is changed in the app settings, all strings should be in the new language.

### Actual behavior

Some strings (most noticeable on the Stats screen) stay in the old language. I encountered this while working on screenshot automation across locales but it also happens in normal usage.

Note that the issue resolves itself on next launch of the app.

Here is a screenshot of the stats screen with mixed language:

screenshot_1532695671

### Steps to reproduce the behavior

1. Open the app on an API version > 24 device/emulator.
2. Change language via Me -> App Settings.
3. Go to the stats screen (My Site -> Stats).
4. The screen will be partially in the original language and partially in the newly chosen language.

##### Tested on Emulator, Android 24

Worked as expected (stats screen was fully translated).

##### Tested on Emulator, Android 25

The behaviour was broken as in the screenshot above.

##### Tested on Emulator, Android 27

Same as version 25.

### PR DESCRIPTION
**Pull request by planarvoid**
Fixes #8114

This fixes the issue with dates and other strings not being translated when the user changes the language within the App settings. This uses the injected `ContextProvider` instead of `Context`. The `ContextProvider` keeps a copy of the context which gets updated whenever the user selects a new language. 

To test:
* Have system language in English
* Go to Me/App settings
* Change language to something with different Month names (Czech)
* Go to Stats
* Check that all the strings are translated to your new language (except the strings which are missing translations in your selected language)

Update release notes:

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by planarvoid** [comment]
@malinajirka I think we have to use the `getSafeLocale` just for strings, it's not necessary for Dates (as is this case). For the other changes I've followed the example of other parts of the app.

File: WordPress/src/main/java/org/wordpress/android/viewmodel/ContextProvider.kt [hunk 1]
```diff
@@ -0,0 +1,18 @@
+package org.wordpress.android.viewmodel
+
+import android.content.Context
+import org.wordpress.android.util.LocaleManager
+import javax.inject.Inject
+import javax.inject.Singleton
+
+@Singleton
+class ContextProvider
+@Inject constructor(private var context: Context) {
```
Comment (develric) [inline WordPress/src/main/java/org/wordpress/android/viewmodel/ContextProvider.kt]: Like this Singleton Provider approach 👍

File: WordPress/src/main/java/org/wordpress/android/viewmodel/ContextProvider.kt [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+    fun refreshContext() {
+        this.context = LocaleManager.setLocale(this.context)
+    }
+
+    fun getContext(): Context {
+        return context
+    }
```
Comment (develric) [inline WordPress/src/main/java/org/wordpress/android/viewmodel/ContextProvider.kt]: Really minor np: what about using expression body function here? Eventually keeping the return data type for readability. I'm in any case fine with as it is already.

**Comment by develric** [comment]
Hi @planarvoid, I followed the testing steps with Android API level 21 and 28 (with and without this patch) and it worked as expected. Good job! 👍

> @malinajirka I think we have to use the `getSafeLocale` just for strings, it's not necessary for Dates (as is this case). For the other changes I've followed the example of other parts of the app.

This is also my guess also based on this [comment](https://github.com/wordpress-mobile/WordPress-Android/blob/6b82cc80c0767bb88929e7449d62c5a5ad42262a/WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java#L157) 

I left an extremely minor np in the code comments if you want to consider but you can leave as it is if you prefer.

During testing with develop branch without this patch I found an issue when selecting RTL languages (for example Hebrew). Basically the order of quick actions buttons and of the bottom nav bar items are not updated in RTL order with API > 24 unless you restart the app. Don't know if it was intentional but this PR seems to fix also that. I will open a dedicated issue to track this but wanted to mention in case you prefer to look into it in this PR explicitly, let me know 😊.

File: WordPress/src/main/java/org/wordpress/android/viewmodel/ContextProvider.kt (hunk 2 above)
Comment (planarvoid) [reply WordPress/src/main/java/org/wordpress/android/viewmodel/ContextProvider.kt]: sounds good 👍 anything that reduces the boilerplate code is a good change :-)

**Comment by planarvoid** [comment]
> I'm not fully sure to get all the possible implications of the modification in ResourceProvider class in places like this and in general outside of stats code.

I don't think there should be any problem with the `ResourceProvider`. What I've done is that I've replaced the injected Application context with the same context from the provider. The only difference is that it's now updated when we change the language.

> Don't know if it was intentional but this PR seems to fix also that.

We use the `ResourceProvider` all over the place so I think it will fix more stuff than we think :-)
