### PR TITLE
Marking failed image uploads in Aztec as FAILED upon start

### LINKED ISSUE #6153: Aztec - upload image then cancel leaves the app unstable
### Expected behavior
Starting the Aztec Editor and uploading an image, then exiting the editor without letting the upload finish should (for now) mimick the behavior that we have for the Visual editor - that is, the upload should be canceled and the image marked FAILED so getting to the Editor again would show the "RETRY" option on such image.

### Actual behavior
The image is left marked "UPLOADING" which causes several other issues to happen.
Using Aztec, try to upload an image, exit the editor (which stops the upload), then come back.

- This is what gets pushed to the server:
```
some text here

<img class="uploading" src="/storage/emulated/0/DCIM/Camera/IMG_20170625_161628.jpg">
```

This is what the logs show
```
06-26 17:32:20.617 12944-13385/org.wordpress.android.beta D/WordPress-API: Dispatching action: MediaAction-UPLOADED_MEDIA
06-26 17:32:20.648 12944-13068/org.wordpress.android.beta D/OpenGLRenderer: endAllActiveAnimators on 0x7aa1496000 (RippleDrawable) with handle 0x7aa20a02e0
06-26 17:32:20.874 12944-12944/org.wordpress.android.beta D/WordPress-MEDIA: Cancelling current upload, id 60
06-26 17:32:20.874 12944-12944/org.wordpress.android.beta I/WordPress-MEDIA: Dispatching cancel upload action for media with local id: 60 and path: /storage/emulated/0/DCIM/Camera/IMG_20170625_161638.jpg
06-26 17:32:20.874 12944-12944/org.wordpress.android.beta D/WordPress-API: Dispatching action: MediaAction-CANCEL_MEDIA_UPLOAD
06-26 17:32:20.906 12944-13063/org.wordpress.android.beta D/WordPress-MEDIA: Canceled in-progress upload: IMG_20170625_161638.jpg
06-26 17:32:20.906 12944-13063/org.wordpress.android.beta D/WordPress-MEDIA: mediaXMLRPCClient: removed id: 60 from current uploads, remaining: 0
06-26 17:32:20.906 12944-13063/org.wordpress.android.beta D/WordPress-API: Dispatching action: MediaAction-CANCELED_MEDIA_UPLOAD
06-26 17:32:20.907 12944-12944/org.wordpress.android.beta W/WordPress-MEDIA: Media event not recognized: org.wordpress.android.fluxc.model.MediaModel@ae238df
06-26 17:32:21.157 12944-13385/org.wordpress.android.beta W/WordPress-MEDIA: media upload failed: java.io.IOException: Canceled
```

- if you get back in the Editor after doing this, the image has been marked `uploading` so tapping on it shows  the “_Stop uploading? cancel/ok_” popup.

- tapping on OK shows “_Can’t stop the upload because it’s already finished_”.

-> the uploads should be marked FAILED when you exit the editor.

### Steps to reproduce the behavior
1. make sure you choose the Beta editor in App Settings
2. start a new draft
3. pick an image from the image picker
4. while the image uploads, but before it finishes uploading, exit the editor
5. get back to edit that draft post you just created in step 2
6. you'll se the image with no overlays, tapping on it shows the "_Stop  uploading? cancel/ok_" popup.

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #6153 

This behavior mimmicks the same [we have for the Visual Editor](https://github.com/wordpress-mobile/WordPress-Android/blob/feature/async-media/libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragment.java#L1228): 
When the content is set (i.e. the Editor is started) we convert all `UPLOADING` images to `FAILED`.

To test:
1. start a new draft using the Aztec editor
2. insert an image using the image picker
3. as the image starts uploading, exit the Editor
4. tap into the draft post to open the Editor again
5. verify the image has the "Failed" overlay (sepia tone and retry icon)
6. tapping on the image should start the upload again
7. repeat steps 3-6 a couple of times to verify the image gets the FAILED state every time you exit/enter again, and you can always tap the image to start uploading again.
8. finally let the image finish uploading, then exit, come back and verify the image loaded is the remote version of it (i.e. it first shows the placeholder, then it shows the image after having loaded it from its remote URL).

cc @aforcier

### CODE REVIEW

File: libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java [hunk 1]
```diff
@@ -323,6 +323,11 @@ public void setContent(CharSequence text) {
         content.fromHtml(text.toString());
         updateFailedMediaList();
         overlayFailedMedia();
+
+        // ToDo:  this is to be removed when feature/async-media is merged
+        // If there are images that are still in progress (because the editor exited before they completed),
```
Comment (aforcier) [inline libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java]: This comment is very familiar 🤔 😉

File: libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java [hunk 2]
```diff
@@ -323,6 +323,11 @@ public void setContent(CharSequence text) {
...
+        // set them to failed, so the user can restart them (otherwise they will stay stuck in 'uploading' mode)
+        convertUploadingUponStartToFailed();
```
Comment (aforcier) [inline libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java]: Maybe we can call this `markAllUploadingMediaAsFailed()` like the `EditorFragment` so it's clear this has to do with media?

Comment (mzorz) [inline libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java]: nice! addressed in 94f62f0

**Comment by aforcier** [comment]
This looks good to me, tested your steps on a couple of API levels and everything works as promised 👍.

I'll let @theck13 give it a once-over too.
