### PR TITLE
Download audio files when clicked

### LINKED ISSUE #9879: Reader: audio files cannot be downloaded using the audio player and the "Download" button cannot be dismissed by tapping elsewhere
Steps to reproduce:

1. On the web, like a post that has an embedded audio file ([example post](https://nickbradbury.com/music-by-nick-bradbury/)).
1. Open the Android app.
1. Go to Reader > My Likes and open the example post.
1. Tap the three dots on the right of the audio player.
1. Tap "Download".
1. Try to dismiss the download button.

<strong>Result:</strong> tapping "Download" doesn't seem to do anything and then the "Download" button cannot be dismissed by tapping elsewhere on the post. ([57s](https://cloudup.com/cLXMw1Ijz31))

Screenshot_20190516-175421
<sup>Tested with WPAndroid 12.4-rc-3 on Pixel 3 Android 9.</sup>

<sub>(internal reference: p5T066-Qy-p2#comment-2857 h/t Rina for reporting this during beta testing!)</sub>

### PR DESCRIPTION
**Pull request by planarvoid**
Fixes #9879 

This PR adds a download listener to the Reader web view. This allows us to catch the audio file URL when the user clicks the "Download" button. The app asks for a permission to download the file and downloads it if approved.

To test:
* Go to a post with audio files
* Click on the overflow button and click "Download"
* Notice that the app asks for permission to write to storage
* The file gets downloaded 
* The file has the name from URL
* Try denying the permission
* Nothing gets downloaded and the app doesn't crash

PR submission checklist:

- [x] I have considered adding unit tests where possible.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.java [hunk 1]
```diff
@@ -103,6 +111,7 @@
         ReaderWebViewUrlClickListener,
         BasicFragmentDialog.BasicDialogPositiveClickInterface {
     private static final String BOOKMARKS_SAVED_LOCALLY_DIALOG = "bookmarks_saved_locally_dialog";
+    private static final int FILE_DOWNLOAD_PERMISSION_REQUEST_CODE = 123;
```
Comment (develric) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.java]: Not fully sure if it can make sense but I would consider to add this request code in the list [here](https://github.com/wordpress-mobile/WordPress-Android/blob/0b681e358496663bce0ed4a4eb133c2738fdbe37/WordPress/src/main/java/org/wordpress/android/util/WPPermissionUtils.java#L34). wdyt?

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.java [hunk 2]
```diff
@@ -1371,6 +1382,44 @@ public boolean onImageUrlClick(String imageUrl, View view, int x, int y) {
...
+        }
+    }
+
+    @Override
+    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions,
+                                           @NonNull int[] grantResults) {
+        FragmentActivity activity = getActivity();
+        if (activity != null
+            && requestCode == FILE_DOWNLOAD_PERMISSION_REQUEST_CODE
+            && (grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED)) {
```
Comment (develric) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.java]: Same as previous comment; maybe can make sense to reuse the `WPPermissionUtils.setPermissionListAsked` as for example in [here](https://github.com/wordpress-mobile/WordPress-Android/blob/0b681e358496663bce0ed4a4eb133c2738fdbe37/WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java#L525)?

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.java (hunk 1 above)
Comment (planarvoid) [reply WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.java]: good point

**Comment by planarvoid** [comment]
> Unless I'm missing something I think we have not addressed in this PR the fact that the download menu is not dismissed tapping outside nor in other ways I could find; in this case you can for example open more Download menus and you must download the file to dismiss.

You're right but I don't think we can control this as this behaviour happens in the WebView and we can't access the overflow menu to dismiss it.
