### PR TITLE
Fix #9760: Fix the empty screen in the History Revision when in airplane mode

### LINKED ISSUE #9760: Revision history: missing an empty screen while offline
We should display the default empty screen, eventually with a Snackbar to let the user know their network is down. 

Current UI:
Screenshot_1556622271

### PR DESCRIPTION
**Pull request by maxme**
Fix #9760: Fix the empty screen in the History Revision when in airplane mode

Update release notes:

- There are user facing changes but too minor to be added in the `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by maxme** [comment]
> You either need to leave the editor or pull-to-refresh. I'd suggest at least adding a retry button on the error screen. I feel like not all users are familiar with Pull-to-refresh. Wdyt?

Good point, I wonder if we can use `ConnectionChangeReceiver.ConnectionChangeEvent` and run the PTR action when we detect the device is connected. The user wouldn't need to do any action and the revision history should be updated. 

I'll try to implement this and if there is something blocking, I'll add a "retry" button on that empty screen.

**Comment by maxme** [comment]
> I'll try to implement this and if there is something blocking, I'll add a "retry" button on that empty screen.

I'll do both, auto-PTR  on connection + retry button.

**Comment by malinajirka** [comment]
>Good point, I wonder if we can use ConnectionChangeReceiver.ConnectionChangeEvent and run the PTR action when we detect the device is connected. The user wouldn't need to do any action and the revision history should be updated.

Good idea! I've used the same approach in the PostListViewModel recently. So I think it should work;).

>I'll do both, auto-PTR on connection + retry button.

Awesome, thanks!

**Comment by maxme** [comment]
@malinajirka updated the PR in 7ecda42 and d3c9bc3

File: WordPress/src/main/java/org/wordpress/android/viewmodel/history/HistoryViewModel.kt [hunk 1]
```diff
@@ -126,10 +145,15 @@ class HistoryViewModel @Inject constructor(
...
-            dispatcher.dispatch(PostActionBuilder.newFetchRevisionsAction(payload))
+        if (networkUtils.isNetworkAvailable()) {
+            _listStatus.value = HistoryListStatus.FETCHING
+            val payload = FetchRevisionsPayload(post, site)
+            uiScope.launch {
+                dispatcher.dispatch(PostActionBuilder.newFetchRevisionsAction(payload))
+            }
+        } else {
+            _listStatus.value = HistoryListStatus.NO_NETWORK
+            createRevisionsList(emptyList())
```
Comment (shiki) [inline WordPress/src/main/java/org/wordpress/android/viewmodel/history/HistoryViewModel.kt]: This part was odd to me. It looks like if the `onPullToRefresh()` method is called, we would be resetting the list to empty if there is no internet connection. However, we never get to this point because `HistoryListFragment. checkConnectionAndPullToRefresh` checks for the internet connection before calling `onPullToRefresh()`. 

I think there shouldn't be a need for the `Fragment` to check for the internet connection. The `ViewModel` should decide what happens in regards to that. With that said, I'm not quite sure how big of a refactoring that would entail so I'm fine with this for now. 😁

Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/viewmodel/history/HistoryViewModel.kt]: >I think there shouldn't be a need for the Fragment to check for the internet connection. The ViewModel should decide what happens in regards to that. 

💯 I'd consider moving the `checkConnectionAndPullToRefresh` logic into the VM.

Comment (maxme) [reply WordPress/src/main/java/org/wordpress/android/viewmodel/history/HistoryViewModel.kt]: Updated in 5eea3b6

File: WordPress/src/main/java/org/wordpress/android/ui/posts/HistoryListFragment.kt [hunk 2]
```diff
@@ -115,7 +119,32 @@ class HistoryListFragment : Fragment() {
...
+            }
+            when (listStatus) {
+                HistoryListStatus.DONE -> {
+                    updatePostOrPageEmptyView()
+                }
+                HistoryListStatus.FETCHING -> {
+                    actionable_empty_view.title.setText(R.string.history_fetching_revisions)
+                    actionable_empty_view.subtitle.visibility = View.GONE
+                    actionable_empty_view.button.visibility = View.GONE
+                    reloadList(viewModel.revisions.value ?: emptyList())
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/HistoryListFragment.kt]: How would you feel about removing `reloadList(..)` from `viewModel.listStatus.observe` and adding `_revisions.value = emptyList()` into `HistoryViewModel.create(..)`? It feels a bit weird we need to manually update the list from the view layer even though we are already observing for its changes. Wdyt?

**Comment by loremattei** [comment]
I'm moving this to 12.5 since 12.4 has been cut. If this PR has to land 12.4, please feel free to target the release branch and to ping me to build a new beta.

File: WordPress/src/main/java/org/wordpress/android/viewmodel/history/HistoryViewModel.kt (hunk 1 above)
Comment (shiki) [reply WordPress/src/main/java/org/wordpress/android/viewmodel/history/HistoryViewModel.kt]: It's looking good. 👌 Thanks for changing that!

File: WordPress/src/main/java/org/wordpress/android/ui/posts/HistoryListFragment.kt (hunk 2 above)
Comment (maxme) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/HistoryListFragment.kt]: The problem with resetting the `_revisions.value` is when you have some data cached and then do a PTR while offline, this will shows the empty screen instead of keeping the cached data.

Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/HistoryListFragment.kt]: I'm not suggesting to reset in on `onRevisionsFetched`, but set it to `emptyList` in `vm.create(..)`. 

We'd basically set it to emptyData when the VM is created and we'd update it only after we successfully fetch a new data.

I'm sorry if I'm missing something, but I'd like to clarify it before I merge it;).

Comment (maxme) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/HistoryListFragment.kt]: 🤦‍♂ I misread your first comment - yes that makes sense, I'll change that.

**Comment by malinajirka** [comment]
LGTM! Thank you 🙇
