### PR TITLE
Fix #4115: validate self hosted url, add https *and* http variants if scheme is unknown

### LINKED ISSUE #4114: Enter "hppt://test.com" as self hosted URL during login crashes the app
That's weird, I was sure we were checking for `http` or `https` scheme when validating URLs.

### LINKED ISSUE #4115: Can't login to self hosted site with http to https redirect
Try to login with `bia.is`, app says "invalid url" - it's valid but the `?rsd` url redirect to `https://bia.is/xmlrpc.php`

We should fix this, users in that case have to enter the full url (in this example `https://bia.is`)

### PR DESCRIPTION
**Pull request by maxme**
Fixes #4115 
Fixes #4114

Before the patch the following valid URL was not working:

* `bia.is`

And this invalid URL was crashing the app:

* `hppt://bia.is`

Note: Instead of autoremoving invalid scheme, we could throw and "invalid URL" exception and notify the user they made a typo (From the crash reports, it's always typo like `htt://`, `hppt://`, `htp://`, etc. so I think it's just better to fix it for the user).

### CODE REVIEW

File: libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/UrlUtils.java [hunk 1]
```diff
@@ -86,25 +86,25 @@ public static String removeLeadingDoubleSlash(String url, String scheme) {
...
         // switch between http or https
-        url = removeLeadingDoubleSlash(url, (isHTTPS ? "https" : "http") + "://");
+        url = removeLeadingDoubleSlash(url, (isHttps ? "https" : "http") + "://");
 
-        if (!URLUtil.isValidUrl(url)) {
-            if (!(url.toLowerCase().startsWith("http://")) && !(url.toLowerCase().startsWith("https://"))) {
-                url = (isHTTPS ? "https" : "http") + "://" + url;
-            }
+        // If the URL is a valid http or https URL, we're good to go
+        if (URLUtil.isHttpUrl(url) || URLUtil.isHttpsUrl(url)) {
```
Comment (daniloercoli) [inline libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/UrlUtils.java]: It's not clear to me why we're not checking the parameter `isHttps` here. 
The doc states that `isHTTPS true will make the url starts with https://`, but the if above returns the passed URL if it's a valid HTTP URL.

File: libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/UrlUtils.java [hunk 2]
```diff
@@ -86,25 +86,25 @@ public static String removeLeadingDoubleSlash(String url, String scheme) {
      * http client will work as expected.
      *
      * @param url url entered by the user or fetched from a server
-     * @param isHTTPS true will make the url starts with https;//
-     * @return transformed url prefixed by its http;// or https;// scheme
+     * @param isHTTPS true will make the url starts with https://
```
Comment (daniloercoli) [inline libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/UrlUtils.java]: We should update the doc with the new parameter name `isHttps`.

**Comment by maxme** [comment]
@daniloercoli ready for a second pass, I updated comments and parameter names in 12a0a47.

File: WordPress/src/main/java/org/xmlrpc/android/XMLRPCUtils.java [hunk 3]
```diff
@@ -313,13 +313,25 @@ private static String discoverSelfHostedXmlrpcUrl(String siteUrl, String httpUse
...
-            urlsToTry.add(sanitizedURL);
+        // add a sanitized version of the http url (if the user didn't specify it)
+        final String sanitizedHttpsURL = sanitizeSiteUrl(siteUrl, true);
+        if (!urlsToTry.contains(sanitizedHttpsURL)) {
+            urlsToTry.add(sanitizedHttpsURL);
+        }
+
+        String appendedXmlrpcUrl = appendXMLRPCPath(sanitizedHttpsURL);
+        if (!urlsToTry.contains(appendedXmlrpcUrl)) {
+            appendedXmlrpcUrl += "?rsd";
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/xmlrpc/android/XMLRPCUtils.java]: Don't think `?rsd` parameter should be added here. The discovery procedure adds it (if necessary) few lines later.

File: WordPress/src/main/java/org/xmlrpc/android/XMLRPCUtils.java [hunk 4]
```diff
@@ -313,13 +313,25 @@ private static String discoverSelfHostedXmlrpcUrl(String siteUrl, String httpUse
...
+        // add a sanitized version of the https url (if the user didn't specify it)
+        final String sanitizedHttpURL = sanitizeSiteUrl(siteUrl, false);
+        if (!urlsToTry.contains(sanitizedHttpURL)) {
+            urlsToTry.add(sanitizedHttpURL);
         }
 
-        String appendedXmlrpcUrl = appendXMLRPCPath(sanitizedURL);
+        appendedXmlrpcUrl = appendXMLRPCPath(sanitizedHttpURL);
         if (!urlsToTry.contains(appendedXmlrpcUrl)) {
             appendedXmlrpcUrl += "?rsd";
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/xmlrpc/android/XMLRPCUtils.java]: Same as above.

File: WordPress/src/main/java/org/xmlrpc/android/XMLRPCUtils.java (hunk 3 above)
Comment (maxme) [inline WordPress/src/main/java/org/xmlrpc/android/XMLRPCUtils.java]: The discovery procedure tries to parse HTML document to get the rsd URL. But it doesn't add it if it's not found. 

But you're right this is useless since the code below doesn't try to parse the result document as an RSD file (this was also wrong before the patch).

It also doesn't try to POST on it, so `urlsToTry` with URL ending by `/xmlrpc.php` are useless too.

Comment (daniloercoli) [inline WordPress/src/main/java/org/xmlrpc/android/XMLRPCUtils.java]: Right, because `verifyXmlrpcUrl` tries to append `xmlrpc.php` and does POST.
The function here is used to discovery the endpoint by doing all the steps, in the correct order (without shortcuts). @hypest could confirm this, since he refactored all of my code about the new login.

**Comment by maxme** [comment]
Some cleaning done in e2eb459  - note: the "forced discovery by appending /xmlrpc.php" is done [here](https://github.com/wordpress-mobile/WordPress-Android/blob/e2eb459c8ca77a76de4a15a981719d7c7619c84e/WordPress/src/main/java/org/xmlrpc/android/XMLRPCUtils.java#L250-L250) anyway.

File: WordPress/src/main/java/org/xmlrpc/android/XMLRPCUtils.java [hunk 5]
```diff
@@ -307,23 +305,17 @@ private static String verifyXmlrpcUrl(final String siteUrl, final String httpUse
     // whole process.
     private static String discoverSelfHostedXmlrpcUrl(String siteUrl, String httpUsername, String httpPassword) throws
             XMLRPCUtilsException {
-        // Array of Strings that contains the URLs we want to try
-        final List<String> urlsToTry = new ArrayList<>();
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/xmlrpc/android/XMLRPCUtils.java]: Wonder why we want to use a set here. It's just a small list accessed sequentially.

Comment (maxme) [inline WordPress/src/main/java/org/xmlrpc/android/XMLRPCUtils.java]: Just to clean some "if not in array add it", not a big deal.

Comment (daniloercoli) [inline WordPress/src/main/java/org/xmlrpc/android/XMLRPCUtils.java]: Hehe, but we don't have "if not in array add it" anymore. :) 
I'm ok with it though.

Comment (maxme) [inline WordPress/src/main/java/org/xmlrpc/android/XMLRPCUtils.java]: > Hehe, but we don't have "if not in array add it" anymore. :)

We don't have them because we use a set :) - I noticed `siteUrl`, `sanitizeSiteUrl(siteUrl, true)` and `sanitizeSiteUrl(siteUrl, false)` is the same string if `siteUrl` is already correct, so we would need to not add the same URL 3 times.

File: WordPress/src/main/java/org/xmlrpc/android/XMLRPCUtils.java (hunk 3 above)
Comment (hypest) [inline WordPress/src/main/java/org/xmlrpc/android/XMLRPCUtils.java]: @daniloercoli not very sure I understand what you want me to confirm here. Let me try to though:
So, the `+= "?rsd";` part was actually taken from the old `smartURLCleanerForRSD()` (see here for example: https://github.com/wordpress-mobile/WordPress-Android/blob/fcf063d2db80d6d9dc5c5b7d3769a6de00526ed0/WordPress/src/main/java/org/wordpress/android/ui/accounts/helpers/FetchBlogListWPOrg.java#L229) and is indeed part of the "discovery" process. Not sure I covered you here. Let me know if not! Thanks!

**Comment by daniloercoli** [comment]
:shipit:
