### PR TITLE
Page/Site design picker: Fixes flickering when changing the preview mode

### LINKED ISSUE #13952: Home Page Picker: On preview mode change the previously selected mode appears for a while
### Expected behavior

The selected preview mode renders without the previous mode appearing

### Actual behavior

The selected preview mode renders after the previous mode appears for ~1s

### Steps to reproduce the behavior

1. Start the site creation flow (e.g. Choose site > Add button)
2. Select the Create WordPress.com site option
3. Select a design
4. Press Preview
5. Press the preview mode button at the top right of the screen
6. Notice that the current preview mode flashes before the selected mode renders

### Screenshots

https://user-images.githubusercontent.com/304044/106746175-d4d01b80-662a-11eb-91ed-e05ed9409f1d.mp4

### PR DESCRIPTION
**Pull request by antonis**
Fixes #13952

## Description
Fixes flickering when changing the preview mode in the Page and Site design pickers by accounting for the rendering delay before updating the webview loading state.

### Site Design Picker
1. Start the site creation flow (e.g. Choose site > Add button)
2. Select the Create WordPress.com site option
3. Select a design
4. Press Preview
5. Press the preview mode button at the top right of the screen
6. **Verify** that the current preview mode does not flash before the selected mode renders

### Page Layout Picker
1. Press the Fab ➕ icon at the *My Site* screen
2. Choose *Site Page*
3. Select a layout
4. Press Preview
5. Press the preview mode button at the top right of the screen
6. **Verify** that the current preview mode does not flash before the selected mode renders

<details>
<summary>Before</summary>

https://user-images.githubusercontent.com/304044/153589175-53021f24-55ac-4e45-8a87-a17d16d18d91.mp4
</details>

<details>
<summary>After</summary>

https://user-images.githubusercontent.com/304044/153589219-0bfe300b-28ee-4fd6-936a-c730d9081c38.mp4
</details>

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing and relied on existing tests (`ModalLayoutPickerViewModelTest`, `HomePagePickerViewModelTest`)

3. What automated tests I added (or what prevented me from doing so)
The fix involves a UI improvement for which a stable test might not be possible

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutPreviewFragment.kt [hunk 1]
```diff
@@ -127,8 +129,12 @@ abstract class LayoutPreviewFragment : FullscreenBottomSheetDialogFragment() {
                 setWebViewWidth(view, width)
                 val widthScript = context?.getString(R.string.web_preview_width_script, width)
                 if (widthScript != null) {
-                    Handler().postDelayed({
-                        view.evaluateJavascript(widthScript) { viewModel.onPreviewLoaded() }
+                    Handler(Looper.getMainLooper()).postDelayed({
+                        view.evaluateJavascript(widthScript) {
+                            Handler(Looper.getMainLooper()).postDelayed({
```
Comment (ovitrif) [inline WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutPreviewFragment.kt]: As you already mentioned, this approach might not be ideal since it's based on a constant value for delaying the rendering regardless of the actual status.

Although a lot less often, while testing the fix I still encountered a few small flickers, which appear to be specific only to multi-column layouts; and for some reason happen more frequently in the **Site Design Picker**. The preview in the **Page Layout Picker** appears to be more stable and the only minor flickers I managed to notice are with gallery page templates.

I did some more digging afterwards and after several attempts at approaching this in a different way I was able to apply the suggestion from [Android docs &rarr; refs &rarr; WebView#postVisualStateCallback](https://developer.android.com/reference/android/webkit/WebView#postVisualStateCallback(long,%20android.webkit.WebView.VisualStateCallback)):

> Because updates to the DOM are processed asynchronously, updates to the DOM may not immediately be reflected visually by subsequent [WebView#onDraw](https://developer.android.com/reference/android/webkit/WebView#onDraw(android.graphics.Canvas)) invocations. The [VisualStateCallback](https://developer.android.com/reference/android/webkit/WebView.VisualStateCallback) provides a mechanism to notify the caller when the contents of the DOM at the current time are ready to be drawn the next time the [WebView](https://developer.android.com/reference/android/webkit/WebView) draws.
> 
> The next draw after the callback completes is guaranteed to reflect all the updates to the DOM up to the point at which the [VisualStateCallback](https://developer.android.com/reference/android/webkit/WebView.VisualStateCallback) was posted, but it may also contain updates applied after the callback was posted.

What I've tried is replacing the block in `if (widthScript != null)` with:
```kotlin
// I'm not sure if this can be improved or how reliable it is:
Handler(Looper.getMainLooper()).postDelayed({
    view.evaluateJavascript(widthScript) {
        view.postVisualStateCallback(Long.MIN_VALUE,  object: WebView.VisualStateCallback() {
            override fun onComplete(p0: Long) {
                if (p0 == Long.MIN_VALUE) {
                    viewModel.onPreviewLoaded()
                }
            }
        })
    }
}, JS_EVALUATION_DELAY)
```
To my surprise this fixed the issue on my physical device, and I couldn't notice any more flickers even for tablet & desktop previews of gallery page templates.

Wdyt?

P.S. I looked at `WebView#postVisualStateCallback` after reading the docs for `WebViewClient#onPageFinished`:
> Receiving an onPageFinished() callback does not guarantee that the next frame drawn by WebView will reflect the state of the DOM at this point. In order to be notified that the current DOM state is ready to be rendered, request a visual state callback with WebView.postVisualStateCallback and wait for the supplied callback to be triggered.

**Review by ovitrif — CHANGES_REQUESTED** [review]
Thank you for looking into this @antonis! 🙇 

### Site Design Picker
- When testing the fix I could still repro the issue first on business theme **Leven** in **Site Design Picker** (see preview)
- Then I tried on other theme categories (Professional, Highlights, Blog) and I could only repro it on: Professional & one Blog theme. It seems to be more common with multi-column layouts and on tablet & desktop previews.
- In my tests of the fix it was always the mobile preview flickering before the tablet or desktop preview renders.
<details>
<summary>Preview</summary>

| <video src="https://user-images.githubusercontent.com/4588074/153634522-9fc93aeb-1d98-42fa-8e45-fb0dd8f5c4e9.mov"></video> |
| --- |

</details>

### Page Layout Picker
- Seems more stable (I retested on prod version 19.1.1 after noticing this, and there it's not)
- Only one time I noticed a brief flickering preview for tablet on a multi-column layout
- The only flicker I was able to repro more than once was in the rendering of the gallery page template, which got me thinking it's a different issue:

<details>
<summary>Preview</summary>

| <video src="https://user-images.githubusercontent.com/4588074/153637542-79126ccc-a0ee-460f-9b69-9f7196a2f7eb.mov"></video> |
| --- |

</details>

I also noticed that the issue reproduces more often on my device when recording the screen.  

---

- Tested the **fix** on Samsung Galaxy S8+ (Android 9)
- Tested the **issue** on Samsung Galaxy S8+ (Android 9) (v19.1.1)

**Review by ovitrif — COMMENTED** [review]
Sorry for toggling "🔴 request changes" on my initial review, what I meant was to request your feedback on the different approach proposed in the [comment](https://github.com/wordpress-mobile/WordPress-Android/pull/15943#discussion_r804836429) on `LayoutPreviewFragment`

The changes in this PR look good to me, since there's a noticeable improvement compared to how the previews worked before.

Please check if the suggested change removes the flickering entirely, as that would be very nice. It was the case when I tested on Friday, but I wasn't very thorough 🙂

File: WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutPreviewFragment.kt (hunk 1 above)
Comment (ovitrif) [reply WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutPreviewFragment.kt]: I tried removing the `JS_EVALUATION_DELAY` too and noticed sometimes an issue when switching from 'Mobile' to 'Tablet': The 'Tablet' preview was not resized properly to the width of the screen, and I could scroll horizontally.

It doesn't always reproduce, but It did more than once. Keeping an eye on it 👀 

<details>
<summary>Preview</summary>

https://user-images.githubusercontent.com/4588074/153830692-b8352223-1858-4f75-ae7f-f8ee7dfb26a5.mp4
</details>

EDIT:
I reverted my removal of the delay with `JS_EVALUATION_DELAY`, and I couldn't reproduce the issue from the above preview clip. In conclusion we still need the `JS_EVALUATION_DELAY` to provide a better experience with the previews 👍

Comment (antonis) [reply WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutPreviewFragment.kt]: Thank you for testing this extensively and suggesting a new approach @ovitrif 🙇 

> I did some more digging afterwards and after several attempts at approaching this in a different way I was able to apply the suggestion from [Android docs → refs → WebView#postVisualStateCallback](https://developer.android.com/reference/android/webkit/WebView#postVisualStateCallback(long,%20android.webkit.WebView.VisualStateCallback)):

TIL! I integrated your suggestion with 78459ea72ae680985d19316793a16644ccd1baf2. I tested on a Pixel 5 (Android 12), a Huawei P9 (Android 7) and a couple of emulators and worked reliably in all cases 🎉

File: RELEASE-NOTES.txt [hunk 2]
```diff
@@ -5,6 +5,7 @@
 * [*] Comment editor: Notification comments support in the new editor [https://github.com/wordpress-mobile/WordPress-Android/pull/15884]
 * [*] Site creation: Fixed bug where sites created within the app were not given the correct time zone, leading to post scheduling issues. [https://github.com/wordpress-mobile/WordPress-Android/pull/15904]
 * [*] Fixes flickering when changing the preview mode in Page or Site design picker [https://github.com/wordpress-mobile/WordPress-Android/pull/15943]
+* [*] Login Epilogue: Fixed bug where if no sites available, then new login epilogue screen without clickable sites and with "create new site" is shown instead of no sites empty "My Site" view. [https://github.com/wordpress-mobile/WordPress-Android/pull/15944]
```
Comment (ovitrif) [inline RELEASE-NOTES.txt:7]: Thank you for making sure this point from PR #15944 is included in the release notes for 19.3! 🙇

**Review by ovitrif — APPROVED** [review]
Thank you @antonis for testing the suggested approach and optimising it further!

I tested the latest changes and confirm it's working like a charm on my testing device! 👍 

From my side this PR is ready to be merged!
