### PR TITLE
Check null source in JSONUtils.queryJSON()

### LINKED ISSUE #3249: Crash report 4.5.1: NPE in NotificationsSettingsDialogPreference
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.json.JSONObject.has(java.lang.String)' on a null object reference
       at org.wordpress.android.util.JSONUtils.queryJSON(JSONUtils.java:33)
       at org.wordpress.android.ui.prefs.notifications.NotificationsSettingsDialogPreference.configureLayoutForView(NotificationsSettingsDialogPreference.java:82)
       at org.wordpress.android.ui.prefs.notifications.NotificationsSettingsDialogPreference.onCreateDialogView(NotificationsSettingsDialogPreference.java:71)
       at android.preference.DialogPreference.showDialog(DialogPreference.java:307)
       at android.preference.DialogPreference.onClick(DialogPreference.java:286)
       at android.preference.Preference.performClick(Preference.java:1121)
       at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
       at android.widget.AdapterView.performItemClick(AdapterView.java:334)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1544)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3682)
       at android.widget.AbsListView$3.run(AbsListView.java:5596)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5832)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

### PR DESCRIPTION
**Pull request by maxme**
fix #3249

### CODE REVIEW

File: libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/JSONUtils.java [hunk 1]
```diff
@@ -25,6 +24,10 @@
      * traverse the object graph and pull out the desired property
      */
     public static <U> U queryJSON(JSONObject source, String query, U defaultObject) {
+        if (source == null) {
```
Comment (nbradbury) [inline libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/JSONUtils.java]: Since we're checking for a null `source`, should we also check for a null `query`?

Comment (maxme) [inline libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/JSONUtils.java]: > should we also check for a null query?

Yep, queries could come from an unitialized param added in 172378e

Unit Tests added in 63a24f8
 - can be run with: `./gradlew :libs:utils:WordPressUtils:connectedAndroidTest --offline`

**Comment by nbradbury** [comment]
:shipit:
