### PR TITLE
Issue/5667 iae sanitizeurl

### LINKED ISSUE #5667: Crash report on may versions: IAE in sanitizeSiteUrl
```
Fatal Exception: java.lang.IllegalArgumentException: U_STRINGPREP_PROHIBITED_ERROR
       at libcore.icu.NativeIDN.convertImpl(NativeIDN.java)
       at libcore.icu.NativeIDN.convert(NativeIDN.java:39)
       at libcore.icu.NativeIDN.toASCII(NativeIDN.java:21)
       at java.net.IDN.toASCII(IDN.java:64)
       at org.wordpress.android.util.UrlUtils.convertUrlToPunycodeIfNeeded(UrlUtils.java:61)
       at org.wordpress.android.fluxc.network.discovery.SelfHostedEndpointFinder.sanitizeSiteUrl(SelfHostedEndpointFinder.java:347)
       at org.wordpress.android.fluxc.network.discovery.SelfHostedEndpointFinder.verifyOrDiscoverXMLRPCEndpoint(SelfHostedEndpointFinder.java:129)
       at org.wordpress.android.fluxc.network.discovery.SelfHostedEndpointFinder.access$100(SelfHostedEndpointFinder.java:40)
       at org.wordpress.android.fluxc.network.discovery.SelfHostedEndpointFinder$1.run(SelfHostedEndpointFinder.java:108)
       at java.lang.Thread.run(Thread.java:818)
```

### PR DESCRIPTION
**Pull request by mzorz**
**DEPENDS ON:** https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/437

Fixes #5667 and #5832, and also fixes a rare native crash that I managed to get (and I believe would never get to be reported) when the url contains newlines , with an android library call (`java.net.IDN.toASCII()`) on 4.2.2 and 5.0.1:

```
05-04 12:13:23.540 19758-20904/org.wordpress.android.beta A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x6e0068 in tid 20904 (Thread-317)
05-04 12:13:23.645 85-85/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-04 12:13:23.645 85-85/? I/DEBUG: Build fingerprint: 'generic/vbox86p/vbox86p:5.1/LMY47D/buildbot06092001:userdebug/test-keys'
05-04 12:13:23.645 85-85/? I/DEBUG: Revision: '0'
05-04 12:13:23.645 85-85/? I/DEBUG: ABI: 'x86'
05-04 12:13:23.645 85-85/? I/DEBUG: pid: 19758, tid: 20904, name: Thread-317  >>> org.wordpress.android.beta <<<
05-04 12:13:23.646 85-85/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x6e0068
05-04 12:13:23.653 85-85/? I/DEBUG:     eax 00000000  ebx 006f0069  ecx 9affeac0  edx 00000000
05-04 12:13:23.653 85-85/? I/DEBUG:     esi 0073006a  edi 00340062
05-04 12:13:23.653 85-85/? I/DEBUG:     xcs 00000073  xds 0000007b  xes 0000007b  xfs 000001e7  xss 0000007b
05-04 12:13:23.653 85-85/? I/DEBUG:     eip 006e0068  ebp 00370036  esp 9affed10  flags 00210286
05-04 12:13:23.653 85-85/? I/DEBUG: backtrace:
05-04 12:13:23.654 85-85/? I/DEBUG:     #00 pc 006e0068  <unknown>
05-04 12:13:23.934 85-85/? I/DEBUG: Tombstone written to: /data/tombstones/tombstone_05

```

This PR cherry-picks commits in this other PR #5820 
And applies a small change in FluxC to catch and transform the `IllegalArgumentException` in `sanitizeUrl()` into a `DiscoveryException`, which is more meaningful and is correctly handled by WPAndroid's logic.

Test string used:

```
あー、原因わかりました！
ログインURLが違いますね。

www.somedomain.com/word

でログインしてください。
アプリの仕様が変わったのか、元からそうだったのかわかりませんが、WordPressのシステムをインストールしたディレクトリを指定しないといけないようです。


不正アクセス防止の為わざとわかりにくい下層ディレクトリにしてありますので覚えておいてください。

ちなみにパソコンからはブックマークしていると思いますが↓です
www.somedomain.com/word/wp-login.php
```

To test:

1. in the login screen, tap  on "add self hosted", entering some user name and some password, and enter the test string (copy & paste)
2. instead of crashing, it should highlight the URL field and show the error sign `"Check that the site URL entered is valid".`

Note: this depends on https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/437

cc @tonyr59h

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInFragment.java [hunk 1]
```diff
@@ -836,6 +836,7 @@ private void signInAndFetchBlogListWPCom() {
     private void signInAndFetchBlogListWPOrg() {
         startProgress(getString(R.string.signing_in));
         String url = EditTextUtils.getText(mUrlEditText).trim();
+        url = url.replace("\n", "").replace("\r", "");
```
Comment (tonyr59h) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInFragment.java]: I think these two calls can be consolidated to `replace("\r|\n", "")` safely.

File: WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerActivity.java [hunk 2]
```diff
@@ -145,7 +145,7 @@ private void updateMenuItemVisibility() {
             mMenuAdd.setVisible(false);
         } else {
             // don't allow editing visibility unless there are multiple wp.com and jetpack sites
```
Comment (tonyr59h) [inline WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerActivity.java]: Should this comment be dropped? Looks like they're being dropped elsewhere.

File: WordPress/src/main/java/org/wordpress/android/util/AnalyticsUtils.java [hunk 3]
```diff
@@ -59,14 +59,23 @@ public static void refreshMetadata(AccountStore accountStore, SiteStore siteStor
...
         AnalyticsTracker.refreshMetadata(metadata);
     }
 
+    /***
+     * @return true if the siteStore has sites accessed via the WPCom Rest API that are not WPCom sites. This only
+     * counts Jetpack sites connected via WPCom Rest API. If there are Jetpack sites in the site store and they're
+     * all accessed via XMLRPC, this method returns false.
+     */
+    private static boolean isJetpackUser(SiteStore siteStore) {
+        return siteStore.getSitesAccessedViaWPComRestCount() - siteStore.getWPComSitesCount() > 0;
```
Comment (tonyr59h) [inline WordPress/src/main/java/org/wordpress/android/util/AnalyticsUtils.java]: Seems like this could cause errors down the line if we add support for the [WordPress REST API](https://wordpress.org/plugins/rest-api/). Maybe we should add a comment?

**Comment by tonyr59h** [comment]
Few nitpicky comments but this is working well 👍

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInFragment.java (hunk 1 above)
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInFragment.java]: addressed in 5a36d4c

**Comment by mzorz** [comment]
Ready for another pass @tonyr59h ! Only addressed the merge of the 2 `replace` calls - the other comments should belong to this other PR as mentioned above: https://github.com/wordpress-mobile/WordPress-Android/pull/5820

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInFragment.java (hunk 1 above)
Comment (tonyr59h) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInFragment.java]: My bad on the wrong method! It should be `replaceAll(...` to handle the regex.

**Comment by tonyr59h** [comment]
:shipit:
