### PR TITLE
Fix for local auto save that  doesn't work in Gutenberg

### LINKED ISSUE #10415: Local auto-save doesn't work in Gutenberg
### Expected behavior
When I'm editing a post in Gutenberg it's being auto-saved periodically into the local database.

### Actual behavior
When I'm editing a post in Gutenberg it's not being auto-saved into the local storage.

### Steps to reproduce the behavior
1. Create a draft
2. Edit title and content
3. Notice `https://github.com/wordpress-mobile/WordPress-Android/blob/180162d62b568319f497ae3b82f22d0b98d87448/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L2333` is never invoked
4. Restart/kill the app using ADB
5. Open the app and notice the Title and Content you created in step 2 is lost.

@hypest Could you please look into this issue or ping someone who might have some insights. Thanks

### PR DESCRIPTION
**Pull request by daniloercoli**
Fixes #10415 by signaling to the host app that changes has been made in GB.
The app then, once received the event, follow the normal flow already implemented for Aztec: asks the content and title to the editor and check for changes.

To test: Follow the steps in the original issue.

GB-Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1351

Update release notes:

- [ x ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java [hunk 1]
```diff
@@ -1687,7 +1687,7 @@ private synchronized void updatePostObject(boolean isAutosave) throws EditorFrag
             }
         }
 
-        // only makes sense to change the publish date and locallychanged date if the Post was actaully changed
+        // only makes sense to change the publish date and locally changed date if the Post was actaully changed
```
Comment (mkevins) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: Just noting there's another typo that can be fixed (same line): `s/actaully/actually/`
