### PR TITLE
Fix empty views on Posts List screen

### LINKED ISSUE #9240: Use appropriate empty view in Post List tabs
We currently show for example `No posts yet. Why not create one?` in `Trashed` posts tab, which doesn't make any sense. Goal of this task is to update the empty views with something relevant to the currently selected tab.

### PR DESCRIPTION
**Pull request by malinajirka**
Fixes #9240 

Fixes Empty View state on the Posts List screen.

post-list-empty-views

Note: 
- changing tabs using swipe gesture doesn't update selected tab in the tab layout (#9285)
- the code touches other empty states - error/hidden list. However, it seems those states haven't been working even before this PR. (#9286)

To test:
1. Switch to a blog with no posts
2. My Site
3. Blog Posts
4. Swipe from left to right
- Make sure the text corresponds to the selected tab
- Make sure the button isn't visible only on the Trashed posts tab

Update release notes:

- [ x ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt [hunk 1]
```diff
@@ -264,30 +262,45 @@ class PostListFragment : Fragment() {
...
             }
         }
     }
 
+    private fun setupButtonOrHide(
+        buttonView: Button,
+        textResId: Int?,
+        onButtonClick: (() -> Unit)?
+    ) {
+        buttonView.visibility = if (textResId == null) View.GONE else View.VISIBLE
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt]: Nitpick: I think we can cleanup this method a little bit. Here is an approach that might work:

```
with(buttonView) {
    uiHelpers.updateVisibility(this, textResId != null)
    textResId?.let {
        setText(textResId)
        setOnClickListener { onButtonClick?.invoke() }
    }
}
```

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt [hunk 2]
```diff
@@ -264,30 +262,45 @@ class PostListFragment : Fragment() {
...
+        textResId?.let {
+            buttonView.setText(textResId)
+            buttonView.setOnClickListener { onButtonClick?.invoke() }
+        }
+    }
+
+    private fun setImageOrHide(imageView: ImageView, resId: Int?) {
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt]: Can we add `@DrawableRes` annotation to `resId`?

This also looks like a good addition to `UiHelper`, what do you think?

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt [hunk 3]
```diff
@@ -264,30 +262,45 @@ class PostListFragment : Fragment() {
...
+        imageView.visibility = if (resId == null) View.GONE else View.VISIBLE
+        resId?.let {
+            imageView.setImageResource(resId)
+        }
+    }
+
+    private fun setTextOrHide(textView: TextView, resId: Int?) {
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt]: Can we add `@StringRes` annotation to `resId`? Or.. use `UiStringRes`?

This also looks like a good addition to `UiHelper`, what do you think?

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt (hunk 1 above)
Comment (oguzkocer) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt]: I think this can be done better with the `setTextOrHide` which I only just saw during the review. Here is an alternative approach:

```
setTextOrHide(buttonView, textResId)
buttonView.setOnClickListener { onButtonClick?.invoke() }
```

I haven't tried this, but I think it'll work. It should be safe to assign the `onClickListener` even if the view is not visible. It just won't do anything, because it'll never be called.

File: WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt [hunk 4]
```diff
@@ -179,30 +181,100 @@ class PostListViewModel @Inject constructor(
...
+            }
+        }
+    }
+
+    private fun createEmptyListUiState(): PostListEmptyUiState.EmptyList {
+        return when (postListType) {
+            PUBLISHED -> PostListEmptyUiState.EmptyList(
+                    R.string.posts_published_empty,
+                    R.string.posts_empty_list_button,
+                    this@PostListViewModel::newPost
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt]: Nitpick: I don't think you need the `@PostListViewModel` here, but it doesn't hurt to be explicit either 🤷‍♂️

File: WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt [hunk 5]
```diff
@@ -179,30 +181,100 @@ class PostListViewModel @Inject constructor(
...
-            }
+            createEmptyUiState()
         }
         result.addSource(pagedListWrapper.isEmpty) { result.value = update() }
         result.addSource(pagedListWrapper.isFetchingFirstPage) { result.value = update() }
         result.addSource(pagedListWrapper.listError) { result.value = update() }
         result
     }
 
+    private fun createEmptyUiState(): PostListEmptyUiState {
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt]: I think it'd be better to take a `PagedListWrapper` instance in this method instead of accessing the global value. Just looking at this method alone, it's not clear that it's safe to read the value of `PagedListWrapper`s state values directly. I'd even take it one step further and pass whatever this method needs, such as `isEmpty`, `listError` etc, and not expose the `PagedListWrapper` at all. It really doesn't matter if we use a `PagedListWrapper` or something else to generate this empty ui state.

We might also consider moving all this empty list logic to a helper somewhere? Maybe we could add it all to a file called `PostListEmptyUiState` and make the helpers just `internal` functions. It's not like they are testable as is, since they are private, so we wouldn't really lose anything if I am not missing anything.

File: WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt [hunk 6]
```diff
@@ -179,30 +181,100 @@ class PostListViewModel @Inject constructor(
...
+        @DrawableRes val imgResId: Int? = null,
+        @StringRes val buttonTextResId: Int? = null,
+        val onButtonClick: (() -> Unit)? = null,
+        val listVisible: Boolean = true
+    ) {
+        class EmptyList(
+            titleResId: Int,
+            @StringRes buttonTextResId: Int? = null,
+            onButtonClick: (() -> Unit)? = null
+        ) : PostListEmptyUiState(
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt]: Nitpick: Could we add the parameter names for the constructor calls in this `sealed class`?

File: WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt [hunk 7]
```diff
@@ -179,30 +181,100 @@ class PostListViewModel @Inject constructor(
...
+            TRASHED -> PostListEmptyUiState.EmptyList(R.string.posts_trashed_empty)
+        }
+    }
+
+    sealed class PostListEmptyUiState(
+        @StringRes val titleResId: Int? = null,
+        @DrawableRes val imgResId: Int? = null,
+        @StringRes val buttonTextResId: Int? = null,
+        val onButtonClick: (() -> Unit)? = null,
+        val listVisible: Boolean = true
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt]: I think my poor initial naming has been carried over to this PR. If I am not mistaken, this property is supposed to indicate whether the `ActionableEmptyView` should be hidden or not. Can we update the name to reflect that? Probably even `isVisible` is a better name than `hidden_list` which was my original enum. Sorry :(

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt [hunk 8]
```diff
@@ -264,30 +262,45 @@ class PostListFragment : Fragment() {
...
-            it.image.setImageResource(R.drawable.img_illustration_posts_75dp)
-            it.image.visibility = if (isNewPostActionVisible) View.VISIBLE else View.GONE
-            it.title.setText(stringId)
-            it.button.setText(R.string.posts_empty_list_button)
-            it.button.visibility = if (isNewPostActionVisible) View.VISIBLE else View.GONE
-            it.button.setOnClickListener {
-                viewModel.newPost()
+    private fun updateEmptyViewForState(state: PostListEmptyUiState) {
+        if (state.listVisible) {
+            actionableEmptyView?.visibility = View.GONE
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt]: I believe this needs to be exactly the opposite. See my comment in `PostListEmptyUiState.listVisible` for why that's the case.

Here is how my post list looks like in this state: https://cloudup.com/cp5-WEa70H1. Here is how it looks like after I make that change: https://cloudup.com/cdQa-SyCZ-u

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt [hunk 9]
```diff
@@ -264,30 +262,45 @@ class PostListFragment : Fragment() {
...
-        val isNewPostActionVisible = emptyViewState == EMPTY_LIST
-        actionableEmptyView?.let {
-            it.image.setImageResource(R.drawable.img_illustration_posts_75dp)
-            it.image.visibility = if (isNewPostActionVisible) View.VISIBLE else View.GONE
-            it.title.setText(stringId)
-            it.button.setText(R.string.posts_empty_list_button)
-            it.button.visibility = if (isNewPostActionVisible) View.VISIBLE else View.GONE
-            it.button.setOnClickListener {
-                viewModel.newPost()
+    private fun updateEmptyViewForState(state: PostListEmptyUiState) {
```
[the remark this answers is not in the document]
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt]: 👍 Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/9287/commits/326dd47136c142a6e8c4e9b7871f35217d7e8e94

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt [hunk 10]
```diff
@@ -264,30 +262,45 @@ class PostListFragment : Fragment() {
...
+                setTextOrHide(view.title, state.titleResId)
+                setImageOrHide(view.image, state.imgResId)
+                setupButtonOrHide(view.button, state.buttonTextResId, state.onButtonClick)
             }
         }
     }
 
+    private fun setupButtonOrHide(
+        buttonView: Button,
+        textResId: Int?,
```
[the remark this answers is not in the document]
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt]: 👍 Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/9287/commits/326dd47136c142a6e8c4e9b7871f35217d7e8e94

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt (hunk 1 above)
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt]: Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/9287/commits/ea42218089634be251bd350787f301bf6a57647a

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt (hunk 2 above)
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt]: >Can we add `@DrawableRes` annotation to `resId`?

Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/9287/commits/ea42218089634be251bd350787f301bf6a57647a

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt (hunk 3 above)
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt]: >Can we add a `@StringRes` annotation to this?

👍 Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/9287/commits/326dd47136c142a6e8c4e9b7871f35217d7e8e94

File: WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt (hunk 5 above)
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt]: >I think it'd be better to take a `PagedListWrapper` instance in this method instead of accessing the global value. Just looking at this method alone, it's not clear that it's safe to read the value of `PagedListWrapper`s state values directly. I'd even take it one step further and pass whatever this method needs, such as `isEmpty`, `listError` etc, and not expose the `PagedListWrapper` at all. It really doesn't matter if we use a `PagedListWrapper` or something else to generate this empty ui state.

Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/9287/commits/d19f6131895b51e69cc26d8f10e12a990b41141f.

>We might also consider moving all this empty list logic to a helper somewhere? Maybe we could add it all to a file called `PostListEmptyUiState` and make the helpers just `internal` functions. It's not like they are testable as is, since they are private, so we wouldn't really lose anything if I am not missing anything.

I feel like everyone will look for the UiState in the ViewModel - especially it's in there in all the other ViewModels.

File: WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt (hunk 7 above)
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt]: My bad sorry. I've renamed it to "emptyViewVisible" to avoid any future confusion.

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt (hunk 8 above)
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt]: You are right:X. I'm totally confused now. How come I haven't noticed this during the tests/while I was taking the screenshots ... I might have broken it during a last minute change 😕

Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt]: Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/9287/commits/9e1f8628c383e44886678f16378f9616f341825a

File: WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt (hunk 7 above)
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt]: Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/9287/commits/9e1f8628c383e44886678f16378f9616f341825a

File: WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt (hunk 6 above)
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt]: Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/9287/commits/9e1f8628c383e44886678f16378f9616f341825a

**Comment by malinajirka** [comment]
Thanks @oguzkocer! I've fixed the issues.

>Or.. you can use the `UiStringRes` wrapper :)

I think if we decide to go ahead with this change, we should do it in another PR as we'll need to refactor even other fragments.

File: WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt (hunk 4 above)
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt]: Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/9287/commits/814f3bd81f73ce905d99fa165978e697dbffcfcd

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt (hunk 8 above)
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt]: Btw I've also noticed the empty views in https://cloudup.com/cdQa-SyCZ-u don't look right -> did you record the gif on this branch?

Comment (oguzkocer) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt]: Oh, maybe I made a mistake. I am actually fairly sure that I did, because I changed that code to record those gifs, but maybe I didn't pull the latest changes or something, I am not sure.
