### PR TITLE
Issue/clarify trash message

### LINKED ISSUE #12165: Discarding unsaved changes unexpectedly deletes the whole post
3032851-zen

User says their posts and pages on the app show a message saying `You've made unsaved changes to this post` and they claimed they have not made any changes to the post. 

Screenshot: https://d.pr/i/48pCRQ+
Annotation on 2020-06-11 at 09-05-50

I was able to find an open issue here for the same thing but for iOS (https://github.com/wordpress-mobile/WordPress-iOS/issues/9614) but not for Android. So, talking to @rezzap about this we started testing following the steps on this post p7cLQ7-Td-p2

### Expected behavior

We expected the app to discard the changes and It should sync the post with the version of the post that is published on the website.

### Actual behavior

Instead, it moves it to trash on the app and on the browser version as well and  if the user doesn’t notice, in 30 days it will be permanently deleted.

### Steps to reproduce the behavior

1. Start with a post that has ‘You’ve made unsaved changes to this post’
2. Select the post and choose the option to edit the version from this app.
3. Make some changes.
4. Click on the arrow to go back (you now see the label change to Local Changes)
5. Go back to the post, type more content to make a change.
6. Go back to the blog post list.
7. Click the ...More button and opt to Bin the changes. Message shows up (Local Changes, binning this post will discard local changes, are you sure you want to continue?)
8. Click okay, the post disappears from the post list and is completely deleted.
9. Visit the link to the post that was published, the post is no longer available and 404s.

Pixel3 Android 10 WP app 15.0-rc-3 (@rossanafmenezes) and Samsung Tab A, Android 9, WP app 15.0-rc-2 (@rezzap)

### PR DESCRIPTION
**Pull request by mchowning**
Addresses, but does not fully fix #12165 ([relevant comment](https://github.com/wordpress-mobile/WordPress-Android/issues/12165#issuecomment-651799879)). First, this PR adds the word "also" to the confirmation dialog when deleting a post with local changes, "trashing" the post does not only just remove the local changes:

Screen Shot 2020-07-06 at 4 08 25 PM

Second, this adds a similar dialog when deleting posts with unsaved changes to clarify the effect of trashing such a post (previously there was no confirmation dialog when deleting posts with unsaved changes):

Screen Shot 2020-07-06 at 4 08 43 PM

#### 1. Deleting Post With Local Changes
1. Open a published post on WPAndroid, make changes that are saved, and close the post without "updating" the published post.
2. Observe that the post list entry for the post states that it has "Local changes"
3. Tap More -> Trash for that post
4. Observe that a confirmation dialog appears that includes the word "also"
5. Tap Ok
6. Observe that the post is deleted

#### 2. Deleting Post With Unsaved Changes
1. Open a published post **on the web**, make changes to it, preview the post (to insure it autosaves), and close the post without "updating" the published post.
2. Open the post on WPAndroid
3. Observe that the post list entry for the post states "You've made unsaved changes to this post"
4. Tap More -> Trash for that post
5. Observe that a confirmation dialog appears stating that "Trashing this post will also discard unsaved changes, are you sure you want to continue?"
6. Tap "Cancel"
7. Observe that the post is **not** deleted
8. Tap More -> Trash for that post
9. Tap "Ok" this time when the confirmation dialog appears
10. Observe that the post is deleted

#### 3. Deleting "Normal" Post
1. Open a post that does not have either unsaved or local changes
2. Tap More -> Trash for that post
3. Observe that there is **not** a confirmation dialog and the post is immediately deleted.

PR submission checklist:

- [X] I have considered adding unit tests where possible.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt [hunk 1]
```diff
@@ -352,26 +352,28 @@ class PostListViewModel @Inject constructor(
...
+                hasAutoSave = hasAutoSave,
+                capabilitiesToPublish = uploadUtilsWrapper.userCanPublish(connector.site),
+                statsSupported = isStatsSupported,
+                featuredImageUrl =
+                convertToPhotonUrlIfPossible(connector.getFeaturedImageUrl(post.featuredImageId)),
+                formattedDate = PostUtils.getFormattedDate(post),
+                performingCriticalAction = connector.postActionHandler.isPerformingCriticalAction(LocalId(post.id)),
+                onAction = { postModel, buttonType, statEvent ->
+                    trackPostListAction(connector.site, buttonType, postModel, statEvent)
+                    connector.postActionHandler.handlePostButton(buttonType, postModel, hasAutoSave)
```
Comment (mchowning) [inline WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt:371]: The diff appears large in this `transformPostModelToPost...` but the only change to the logic was to extract the `hasAutoSave` value so that it could be (re)used: assigned to the `hasAutoSave` parameter and passed in the `handlePostButton` function call.

**Comment by mchowning** [comment]
Thanks for the review @malinajirka ! :bow:

> I don't see any reason why would we want to delete an auto-save - perhaps there is a technical limitation on the backend 🤷. 

I do see the same behavior (auto-save is lost on a post that is trashed and then restored) when I just use the web, so that makes me think it may be a backend issue like you suggest. I haven't had time to investigate this though.
