### PR TITLE
Fix #2768: Move comment moderation from NotificationsListFragment.onActivityResu…

### LINKED ISSUE #2768: Notifications: Comment moderation doesn't work when opened from push
If you open a comment push notification and then try to perform a moderation action, nothing happens.

From a quick debug, it appears that NotificationsListFragment is null in the `onActivityResult()` of WPMainActivity.

### PR DESCRIPTION
**Pull request by maxme**
Fix #2768

Move comment moderation from NotificationsListFragment.onActivityResult to WPMainActivity.onActivityResult so comment will be moderated even if NotificationsListFragment is not instantiated.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java [hunk 1]
```diff
@@ -242,6 +246,18 @@ private void resetFragments() {
         }
     }
 
+    private void moderateCommentOnActivityResult(Intent data) {
+        try {
+            Note note = SimperiumUtils.getNotesBucket().get(StringUtils.notNullStr(data.getStringExtra
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java]: Looking through other places that call `getNotesBucket()`, it's possible for it to return null. So this needs a null check.

File: WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationEvents.java [hunk 2]
```diff
@@ -1,6 +1,32 @@
...
+        String mNoteId;
+        public NoteVisibilityChanged(String noteId, boolean isHidden) {
+            mNoteId = noteId;
+            mIsHidden = isHidden;
+        }
+    }
+    public static class NoteModerationFailed {
+        CommentStatus mStatus;
+        String mNoteId;
+        public NoteModerationFailed(String noteId, CommentStatus status) {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationEvents.java]: Both `noteId` and `status` are unused and can be removed.

**Comment by nbradbury** [comment]
:shipit:
