### PR TITLE
Fixes help button on NewSiteCreation segments, verticals and site info screens

### LINKED ISSUE #8711: [Site Creation] Fix help button in the Toolbar
The app crashes when the user clicks on the HELP button in the toolbar.

### PR DESCRIPTION
**Pull request by malinajirka**
Fixes #8711 

Fixes `Help` button in the toolbar on Segments, Verticals and Site Info screens.
I didn't want to create unnecessary conflicts on the domain screen so I didn't fix it there, but we can fix it in a PR for #8507.

To test:
- set `NEW_SITE_CREATION_ENABLED` in build.gradle to true
1. `My Site` -> `Switch site` -> plus sign icon
2. Click on `Help` button in the top right corner
3. Make sure it works
4. Press back
5. Select a segment
6. Click on `Help` button in the top right corner
7. Make sure it works
8. Type something
9. Select a vertical
10. Click on `Help` button in the top right corner
11. Make sure it works

### CODE REVIEW

**Comment by malinajirka** [comment]
I've been thinking about it, but I felt like we don't navigate the user away from the fragment. We just show a modal window over it. However, I don't feel strong about it, so we can just go with the listener approach;).

File: WordPress/src/main/java/org/wordpress/android/ui/sitecreation/NewSiteCreationSiteInfoFragment.kt [hunk 1]
```diff
@@ -104,6 +110,9 @@ class NewSiteCreationSiteInfoFragment : NewSiteCreationBaseFormFragment<NewSiteC
                 }
             }
         })
+        viewModel.onHelpClicked.observe(this, Observer {
+            helpClickedListener.onHelpClicked(HelpActivity.Origin.NEW_SITE_CREATION_SITE_INFO)
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/sitecreation/NewSiteCreationSiteInfoFragment.kt]: I don't have a preference one way or another, but should the origin be coming from the VM instead?

Comment (oguzkocer) [reply WordPress/src/main/java/org/wordpress/android/ui/sitecreation/NewSiteCreationSiteInfoFragment.kt]: Even if that's a good idea, we probably shouldn't do it in this PR, because I think we'll need to move the `Origin` out of `HelpActivity`, because it's kind of weird to import something from the Activity in the VM.

Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/sitecreation/NewSiteCreationSiteInfoFragment.kt]: @oguzkocer That was exactly my reasoning why I didn't put it into the VM. But I agree it'd be cleaner.
