### PR TITLE
[Stats] Add year to date picker for weeks.

### LINKED ISSUE #20488: Stats Traffic tab dates should include year
### Expected behavior
The date shown on the Stats Traffic tab when "By week" is selected should include the year to avoid confusion about which year is being displayed. (e.g. "Feb 19 - Feb 25, 2024")

Discussed in:
- p1709586750284709/1709585366.152709-slack-C06BR07TJHK
- p1709042259067229/1709042158.468369-slack-C06BR07TJHK

### Actual behavior
The dates on "By week" granularity" are shown without a year (e.g. "Feb 19 - Feb 25")

### Steps to reproduce the behavior
1. Open Stats
2. Go to the Traffic tab
3. Switch "By day" to different periods and notice the dates are displayed without a year.

### PR DESCRIPTION
**Pull request by notandyvee**
Fixes #20488

Add year to the week granularity label in datepicker. The screenshot below is on a small screen width.

Note: this affects both the stats that is currently out to everyone and the traffic tab under the week granularity.

Screenshot_20240403_172130

-----

## To Test:

- [ ] Turn on `stats_traffic_tab` feature flag in debug settings.
- [ ] Go to stats and make sure you are on the traffic tab
- [ ] Select the "By Week" granularity.
- [ ] You should see a year on the from/to dates.
- [ ] Turn off `stats_traffic_tab`.
- [ ] Go back into stats and go to the weeks tab.
- [ ] The date picker there should also have the year.

-----

## Regression Notes

1. Potential unintended areas of impact

    This would only affect adding the year to the date picker label on the old stats week granularity.

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    Manual test.

3. What automated tests I added (or what prevented me from doing so)

    n/a

-----

## PR Submission Checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by irfano — CHANGES_REQUESTED** [review]
@notandyvee , can we make this change for only the traffic tab by checking `stats_traffic_tab` flag. The iOS is also doing it this way.
Additionally, I noticed that `StatsDateFormatterTest` is failing.

**Comment by notandyvee** [comment]
> can we make this change for only the traffic tab by checking stats_traffic_tab flag. The iOS is also doing it this way

That's fine. I'll make the changes.

**Comment by notandyvee** [comment]
@irfano ready for re-review. Fixed the unit tests and added the feature flag check.

File: WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/utils/StatsDateFormatterTest.kt [hunk 1]
```diff
@@ -72,6 +77,42 @@ class StatsDateFormatterTest : BaseUnitTest() {
         assertThat(parsedDate).isEqualTo("Dec 17 - Dec 23")
     }
 
+    @Test
+    fun `prints a week date in string format in granular stats screen`() {
+        whenever(statsTrafficTabFeatureConfig.isEnabled()).thenReturn(true)
```
Comment (irfano) [inline WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/utils/StatsDateFormatterTest.kt:82]: `statsTrafficTabFeatureConfig.isEnabled()` should return false for the granular stats screen.
```suggestion
        whenever(statsTrafficTabFeatureConfig.isEnabled()).thenReturn(false)
```

And `parsedDate` should be "Dec 17 - Dec 18".

**Review by irfano — CHANGES_REQUESTED** [review]

File: WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/utils/StatsDateFormatterTest.kt (hunk 1 above)
Comment (notandyvee) [reply WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/utils/StatsDateFormatterTest.kt:82]: Hey! Sorry about that @irfano . It wasn't clear because the test description was poorly named. The two tests I added are for testing with the traffic tab feature on. This verifies that when the feature is on, that's when we add the year to the week date picker. I renamed it to be more clear.

**Review by irfano — APPROVED** [review]
LGTM! 👍🏻
