### PR TITLE
Site Creation Visual Cue for Unavailable or Invalid Domains

### LINKED ISSUE #10089: [Site Creation] Show visual cue when exact match on domain suggestions is taken
### Expected behavior
Show a visual cue when the exact match for the provided query is already taken. Should probably work even for the default list of suggestions which is derived from "Site title" entered on the previous screen.

### Actual behavior
The app displays only a list of _available_ domains. It might be quite confusing for the user and they might even think the search doesn't work as expected.

### Steps to reproduce the behavior
1. My Site
2. Switch Site
3. Plus sign icon in the top right corner
4. Select a site type
5. Skip 
6. Enter a title and click on next
7. Notice the app displays only available domains - eg. if you type "test" it doesn't show "test.wordpress.com" as it's already taken

cc @SylvesterWilmott 

Proposed solution is in [this comment](https://github.com/wordpress-mobile/WordPress-Android/issues/10089#issuecomment-546062587)

### PR DESCRIPTION
**Pull request by jd-alexander**
Fixes #10089 
Now when the user navigates to the 3rd step of the Site Creation process and they are selecting their domain they will be notified if the query they entered is already in use or invalid. Previously, only suggestions would have been shown. 

To test:
1. My Site. 
2. Switch site.
3. Press the add button.
4. Create a new WordPress.com site. 
5. Skip to the screen where you can search for a domain and begin utilizing different search queries to see the behavior. 

Below is a gif of this in action. 

Before on the left and the after on the right.
  

 

### Todo

- [ ] Do accessibility audit on the layout and make changes to support it. 
- [ ] Verify the domain cases that the app needs to validate.

PR submission checklist:

- [x] I have considered adding unit tests where possible.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainValidator.kt [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+     * Checks to see if the supplied query is a valid domain. If not then it could be a word, so a WP.com
+     * sub domain is created with it and then that's checked. If none of those are valid then we assume the supplied
+     * query isn't a valid domain for site creation.
+     */
+    fun validateDomain(query: String): ValidationResult {
+        var isValidUrl: Boolean
+
+        var fullUrl = urlUtilsWrapper.addUrlSchemeIfNeeded(query, false)
+
+        isValidUrl = urlUtilsWrapper.isValidUrlAndHostNotNull(fullUrl) && suffixDatabase.getEffectiveTldPlusOne(
```
Comment (jd-alexander) [inline WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainValidator.kt]: @malinajirka what I attempted to do in this class is to reuse the `URLUtils` that existed in the project to perform the domain validation. However, on it's own it wasn't verifying that a domain would contain a TLD so I ended up using the PublicSuffixDatabase that's shipped with `OkHttp` not sure how you feel about this, but it was the easier solution so I definitely want some feedback on this.

**Comment by jd-alexander** [comment]
I will fix the build in the morning. Need to update Gutenberg it seems.

File: WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainValidatorTest.kt [hunk 2]
```diff
@@ -0,0 +1,27 @@
+package org.wordpress.android.ui.sitecreation.domains
+
+import junit.framework.Assert.assertFalse
+import junit.framework.Assert.assertTrue
+import org.junit.Test
+import org.wordpress.android.RobolectricSetupTest
+import org.wordpress.android.util.UrlUtilsWrapper
+
+class SiteCreationDomainValidatorTest : RobolectricSetupTest() {
```
Comment (jd-alexander) [inline WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainValidatorTest.kt]: Also for the tests, I utilized `Robolectric` so that I could get a working version of the `UrlUtilsWrapper` to power the domain validation logic. What do you think?

File: WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt [hunk 3]
```diff
@@ -283,6 +320,24 @@ class SiteCreationDomainsViewModelTest {
...
+     */
+    private fun verifyVisibleItemsContentUiAndDomainValidityState(
+        uiState: DomainsUiState,
+        showClearButton: Boolean = false,
+        numberOfItems: Int = MULTI_RESULT_DOMAIN_FETCH_RESULT_SIZE
+    ) {
+        assertThat(uiState.searchInputUiState.showProgress, Is(false))
+        assertThat(uiState.searchInputUiState.showClearButton, Is(showClearButton))
+        assertThat(uiState.contentState, instanceOf(DomainsUiContentState.VisibleItems::class.java))
+        assertThat(uiState.contentState.items.size, Is(numberOfItems.inc()))
```
Comment (jd-alexander) [inline WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt]: For this test, I simply increment the total number of items since when the `Unavailability` state gets added then an extra state item exists. Should this be more explicit or it's fine?

File: WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt [hunk 4]
```diff
@@ -76,9 +87,13 @@ class SiteCreationDomainsViewModelTest {
 
     private fun <T> testWithSuccessResponse(
         queryResultSizePair: Pair<String, Int> = MULTI_RESULT_DOMAIN_FETCH_QUERY,
+        domainValidResultType: ValidationResultType = VALID_AVAILABLE,
         block: suspend CoroutineScope.() -> T
     ) {
         test {
+            whenever(siteCreationDomainValidator.validateDomain(any())).thenReturn(
```
Comment (jd-alexander) [inline WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt]: Here, I add the domain validation logic since in the `ViewModel` the check is being run there once the domains have been successfully fetched.

File: WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt [hunk 5]
```diff
@@ -170,13 +185,30 @@ class SiteCreationDomainsViewModelTest {
...
+            testWithSuccessResponse {
+                viewModel.start(null, SEGMENT_ID)
+                viewModel.updateQuery(MULTI_RESULT_DOMAIN_FETCH_QUERY.first)
+                val captor = ArgumentCaptor.forClass(DomainsUiState::class.java)
+                verify(uiStateObserver, times(3)).onChanged(captor.capture())
+                verifyVisibleItemsContentUiState(captor.thirdValue, showClearButton = true)
+            }
+
+    /**
+     * Verifies the UI state for after the user enters a non-empty query which results in multiple domain suggestions.
```
Comment (malinajirka) [inline WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt]: It seems the comment doesn't correspond to what the method tests.

File: WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt [hunk 6]
```diff
@@ -170,13 +185,30 @@ class SiteCreationDomainsViewModelTest {
...
+     */
+    @Test
+    fun verifyDomainUnavailableUiStateAfterResponseWithMultipleResults() =
```
Comment (malinajirka) [inline WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt]: We might want to consider testing only that "domain unavailable" ui state is present, so the test has only a single reason to fail. Wdyt?

**Comment by jd-alexander** [comment]
A question to those who have worked on the API team. So here we are working on an issue in Site Creation. In particular, the domain selection stage where a user can enter a query and they get domain suggestions (“/domains/suggestions”). Currently, the app only shows the suggestions but it doesn’t state if the domain query that was entered is available or not or if it was invalid altogether so we are working on adding that. At first we were thinking to add the logic on the client-side due to not wanting to make two server-side requests(p1571736509104000-slack-CFF433YSG); that is one to “/domains/suggestions” and another to “/domains/$domain/is-available but now after trying to do the domain verification logic on the client we want more feedback before finalizing this since the behavior would have to replicated on iOS as well.

**Comment by jkmassel** [comment]
Howdy folks! I'm freezing `13.6` today, so this is being bumped to `13.7`. If you'd like it to go out as part of `13.6`, please target `release/13.6` for this PR, and DM me once it's merged – I'll be happy to cut a new beta release!

**Comment by jkmassel** [comment]
Howdy folks! I'm freezing `13.7` today, so this is being bumped to `13.8`. If you'd like it to go out as part of `13.7`, please target `release/13.7` for this PR, and DM me once it's merged – I'll be happy to cut a new beta release!

**Comment by jd-alexander** [comment]
As per the discussion with @malinajirka the domain validation process will be as follows : 
1. Remove everything after a first .
2. Remove "https:// or http://` if present
3. To lower case
4. Remove all characters but [a-z][0-9] = let's call the result of this process modifiedQuery
5. Take each item from the result list and call .startsWith(modifiedQuery)
6. Show hint if no match is found (just to clarify, we won't show the hint even if we find just "query.art.blog")

**Comment by jd-alexander** [comment]
Hi @SylvesterWilmott @mbshakti for the domain unavailability I was thinking to accompany this implementation with a message that says the "domain isn't available" ( so that could mean it's either taken, invalid, or need to bought). This would be implemented with an information icon that is clickable with a dialog or snackbar popping up that gives a full explanation of how the domain search works. So if the user entered a full dot com domain and they don't see it this in the domain suggestions it could give more context as to why. Let me know what you both think about this. Thanks :slightly_smiling_face:

@mbshakti I know I just threw you into this discussion. Sorry 👋 for more context you can check this discussion `p1571736509104000-slack-CFF433YSG`

File: WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainValidator.kt (hunk 1 above)
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainValidator.kt]: I am just commenting here to finalize these discussions we had started and somewhat concluded in the past. The `PublicSuffixDatabase` is an actively updated database with TLDs that being used in the world right now. Nonetheless, it's an overkill for this solution so it will be removed.

File: WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt (hunk 3 above)
Comment (jd-alexander) [reply WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt]: Great 👍

File: WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/PublicSuffixDatabaseWrapper.kt [hunk 7]
```diff
@@ -0,0 +1,15 @@
+package org.wordpress.android.ui.sitecreation.domains
+
+import okhttp3.internal.publicsuffix.PublicSuffixDatabase
+import javax.inject.Inject
+
+/**
+ * Injectable wrapper around  * Injectable wrapper around PublicSuffixDatabase.
```
[the remark this answers is not in the document]
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/PublicSuffixDatabaseWrapper.kt]: This was removed in its entirety.

File: WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java [hunk 8]
```diff
@@ -472,6 +473,8 @@
 
     void inject(PublishNotificationReceiver object);
 
+    void inject(SiteCreationDomainValidator siteCreationDomainValidator);
```
[the remark this answers is not in the document]
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java]: Thanks. Mistakenly missed this 👍

File: WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainValidatorTest.kt (hunk 2 above)
Comment (jd-alexander) [reply WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainValidatorTest.kt]: Since the implementation has been simplified I can now remove Robolectric.

Comment (jd-alexander) [reply WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainValidatorTest.kt]: Removed this in e9e7275

File: WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt (hunk 3 above)
Comment (jd-alexander) [reply WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt]: Great 👍

File: WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/PublicSuffixDatabaseWrapper.kt (hunk 7 above)
[the remark this answers is not in the document]
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/PublicSuffixDatabaseWrapper.kt]: Removed in e9e7275

File: WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java]: Removed in e9e7275

File: WordPress/src/main/java/org/wordpress/android/modules/ApplicationModule.java [hunk 9]
```diff
@@ -100,6 +101,11 @@ public static NewsService provideLocalNewsService(ContextProvider contextProvide
         return new WizardManager<>(stepsProvider.getSteps());
     }
 
+    @Provides
+    public static PublicSuffixDatabaseWrapper providePublicSuffixDatabaseWrapper() {
```
[the remark this answers is not in the document]
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/modules/ApplicationModule.java]: Removed in e9e7275

File: WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainValidatorTest.kt [hunk 10]
```diff
@@ -0,0 +1,27 @@
...
+    private val domainResolver = SiteCreationDomainValidator(
+            UrlUtilsWrapper(),
+            PublicSuffixDatabaseWrapper()
+    )
+
+    @Test
+    fun validateDomains() {
```
[the remark this answers is not in the document]
Comment (jd-alexander) [reply WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainValidatorTest.kt]: These tests were removed e9e7275 in favor of the new approach.

File: WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainValidator.kt [hunk 11]
```diff
@@ -0,0 +1,52 @@
...
+            host
+        }
+    }
+
+    /**
+     * Checks to see if the supplied query is a valid domain. If not then it could be a word, so a WP.com
+     * sub domain is created with it and then that's checked. If none of those are valid then we assume the supplied
+     * query isn't a valid domain for site creation.
+     */
+    fun validateDomain(query: String): ValidationResult {
```
[the remark this answers is not in the document]
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainValidator.kt]: Removed in e9e7275

File: WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt [hunk 12]
```diff
@@ -283,6 +320,24 @@ class SiteCreationDomainsViewModelTest {
         assertThat(uiState.contentState.items.size, Is(numberOfItems))
     }
 
+    /**
+     * Helper function to verify a [DomainsUiState] with [DomainsUiContentState.VisibleItems] content state & [DomainsModelUnavailabilityUiState] Ui State.
+     */
+    private fun verifyVisibleItemsContentUiAndDomainValidityState(
```
[the remark this answers is not in the document]
Comment (jd-alexander) [reply WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt]: Thanks! Your suggestion is great. I made the change for this in d01fc2c

File: WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModel.kt [hunk 13]
```diff
@@ -233,21 +243,32 @@ class SiteCreationDomainsViewModel @Inject constructor(
...
+                    messageResId = errorResId
+                            ?: R.string.site_creation_fetch_suggestions_error_unknown,
                     retryButtonResId = R.string.button_retry
             )
             errorUiState.onItemTapped = onRetry
             items.add(errorUiState)
         } else {
+            if (data.isNotEmpty())
+                query?.value?.let {
+                    val itemUiState = getDomainUnavailableUiState(it, data)
```
[the remark this answers is not in the document]
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModel.kt]: Great idea. Removes unneeded variable. Thanks for spotting this. I am making a mental note of all these things for future work. I appreciate the effort put into this review. Resolved here d01fc2c

File: WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModel.kt [hunk 14]
```diff
@@ -233,21 +243,32 @@ class SiteCreationDomainsViewModel @Inject constructor(
 
     private fun createSuggestionsUiStates(
         onRetry: () -> Unit,
+        query: DomainSuggestionsQuery?,
```
[the remark this answers is not in the document]
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModel.kt]: Yes, that makes alot of sense. The other properties of the type aren't needed so it simplifies the intent of the method parameter by passing what truly matters which is the `String` query. Resolved here d01fc2c

File: WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt [hunk 15]
```diff
@@ -316,4 +371,40 @@ class SiteCreationDomainsViewModelTest {
...
+        VALID_AVAILABLE,
+        VALID_UNAVAILABLE,
+        INVALID
+    }
+
+    private fun createDomainValidationResult(resultType: ValidationResultType): ValidationResult {
+        return when (resultType) {
+            VALID_AVAILABLE -> ValidationResult(
+                    true,
+                    "${MULTI_RESULT_DOMAIN_FETCH_QUERY.first}-1.wordpress.com"
```
[the remark this answers is not in the document]
Comment (jd-alexander) [reply WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt]: Understood. I had just reused it to make it easy for someone to follow again with how it connects with the rest of the tests that use the value. As someone could do a find usages and see that the same suggestions are being used to supply the overall suggestions. I did this for the new test as well but I could hardcode it for sure.

File: WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt [hunk 16]
```diff
@@ -316,4 +371,40 @@ class SiteCreationDomainsViewModelTest {
...
+
+            VALID_UNAVAILABLE -> ValidationResult(
+                    true,
+                    "${MULTI_RESULT_DOMAIN_FETCH_QUERY.first}-" +
+                            "${MULTI_RESULT_DOMAIN_FETCH_QUERY.second.inc()}.wordpress.com"
+            )
+
+            INVALID -> ValidationResult(
+                    false,
+                    "${MULTI_RESULT_DOMAIN_FETCH_QUERY.first}-&&.wordpress.com"
```
[the remark this answers is not in the document]
Comment (jd-alexander) [reply WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt]: Removed.

File: WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt [hunk 17]
```diff
@@ -316,4 +371,40 @@ class SiteCreationDomainsViewModelTest {
...
+        return when (resultType) {
+            VALID_AVAILABLE -> ValidationResult(
+                    true,
+                    "${MULTI_RESULT_DOMAIN_FETCH_QUERY.first}-1.wordpress.com"
+            )
+
+            VALID_UNAVAILABLE -> ValidationResult(
+                    true,
+                    "${MULTI_RESULT_DOMAIN_FETCH_QUERY.first}-" +
+                            "${MULTI_RESULT_DOMAIN_FETCH_QUERY.second.inc()}.wordpress.com"
```
[the remark this answers is not in the document]
Comment (jd-alexander) [reply WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt]: I was just using this to generate a random domain that was somewhat related to the test ones. Not needed and was removed.

File: WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt [hunk 18]
```diff
@@ -316,4 +371,40 @@ class SiteCreationDomainsViewModelTest {
...
+     */
+    enum class ValidationResultType {
+        VALID_AVAILABLE,
+        VALID_UNAVAILABLE,
+        INVALID
+    }
+
+    private fun createDomainValidationResult(resultType: ValidationResultType): ValidationResult {
+        return when (resultType) {
+            VALID_AVAILABLE -> ValidationResult(
```
[the remark this answers is not in the document]
Comment (jd-alexander) [reply WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt]: True. This was removed in favor of a simpler implementation.

File: WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModel.kt [hunk 19]
```diff
@@ -258,6 +279,33 @@ class SiteCreationDomainsViewModel @Inject constructor(
         return items
     }
 
+    private fun getDomainUnavailableUiState(
+        query: String,
+        domains: List<String>
+    ): DomainsModelUiState? {
+        val domainValidationResult = domainValidator.validateDomain(query)
```
[the remark this answers is not in the document]
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModel.kt]: Thanks. This was simplified in  d01fc2c

File: WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt (hunk 5 above)
Comment (jd-alexander) [reply WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt]: Resolved in 4e9a57a

File: WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt (hunk 6 above)
Comment (jd-alexander) [reply WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt]: Yes, that makes alot of sense. It makes it easier to follow. Resolved here in d01fc2c

**Comment by jd-alexander** [comment]
Hi @malinajirka I responded to all the comments you made about the previous implementation and cross-referenced them with the current implementation that follows the algorithm you came up with it. Let me know what you think after your review. Happy to answer any questions you might have 🙌 Again, thanks for the thorough reviews you have been providing. They have been really helpful 🙏

File: WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt [hunk 20]
```diff
@@ -316,4 +362,17 @@ class SiteCreationDomainsViewModelTest {
...
+
+    /**
+     * Helper function that creates the current sanitized query being used to generate the domain suggestions.
+     * It returns a test domain that's based on the test suggestions being used so that the app can behave in it's
+     * normal [DomainsModelAvailableUiState] state. It also returns an unavailable domain query so that the
+     *  [DomainsModelUnavailabilityUiState] state is activated.
+     */
+    private fun createSanitizedDomainResult(isDomainAvailableInSuggestions: Boolean) =
+            if (isDomainAvailableInSuggestions) {
+                "${MULTI_RESULT_DOMAIN_FETCH_QUERY.first}-1"
```
Comment (jd-alexander) [inline WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt]: Let me know if I should hardcode this. I just utilized it so that there's a domain match with the first item in the list and the unavailability state wouldn't show since the domain would be available. So I think it's fine but I am more than open to more thoughts on what will be clearer for the overall codebase 🙇

File: WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainSanitizer.kt [hunk 21]
```diff
@@ -0,0 +1,24 @@
...
+                val periodIndex = indexOf(".")
+                if (periodIndex > 0) {
+                    substring(0, periodIndex)
+                } else {
+                    this
+                }
+            }.replace("http://", "")
+                    .replace("https://", "")
+                    .replace("[^a-zA-Z0-9]".toRegex(), "")
+                    .toLowerCase(Locale.getDefault())
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainSanitizer.kt]: I'm wondering if we want to use the default locale. `toLowerCase` doesn't produce 1:1 mapping in some languages. Since this is a URL it might make sense to use Locale.ROOT. Wdyt?

File: WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainSanitizer.kt [hunk 22]
```diff
@@ -0,0 +1,24 @@
...
+class SiteCreationDomainSanitizer
+@Inject constructor() {
+    /**
+     * Sanitizes a query by taking the value before it's first period if it's present,
+     * removes it's scheme and finally, removes any characters that aren't alphanumeric.
+     */
+    fun sanitizeDomainQuery(query: String) =
+            query.run {
+                val periodIndex = indexOf(".")
+                if (periodIndex > 0) {
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainSanitizer.kt]: Just to double check: I noticed you use `>` without `=`. Is this intentional, because you know that if the query starts with `.`, the dot will get removed in `.replace("[^a-zA-Z0-9]".toRegex(), "")`?

SideNote: We might want to add a unit tests for this scenario. Wdyt?

File: WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModel.kt [hunk 23]
```diff
@@ -233,21 +243,30 @@ class SiteCreationDomainsViewModel @Inject constructor(
...
         data: List<String>,
         errorFetchingSuggestions: Boolean,
         @StringRes errorResId: Int?
     ): List<DomainsListItemUiState> {
         val items: ArrayList<DomainsListItemUiState> = ArrayList()
         if (errorFetchingSuggestions) {
             val errorUiState = DomainsFetchSuggestionsErrorUiState(
-                    messageResId = errorResId ?: R.string.site_creation_fetch_suggestions_error_unknown,
+                    messageResId = errorResId
+                            ?: R.string.site_creation_fetch_suggestions_error_unknown,
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModel.kt]: NitPick: Could you please revert this change. Having this an a new line seems weird.

File: WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModel.kt [hunk 24]
```diff
@@ -233,21 +243,30 @@ class SiteCreationDomainsViewModel @Inject constructor(
...
                     retryButtonResId = R.string.button_retry
             )
             errorUiState.onItemTapped = onRetry
             items.add(errorUiState)
         } else {
+            if (data.isNotEmpty())
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModel.kt]: Are we missing `{` here? I assume we want to wrap both `query?.let` and `data.forEach`, right? In case you really want to wrap just `query?.let`, I'd suggest adding the `{` explicitly - we try to avoid using `ifs` without specifying a block explicitly, as it leads to hard to notice bugs. Wdyt?

File: WordPress/src/main/java/org/wordpress/android/util/UrlUtilsWrapper.kt [hunk 25]
```diff
@@ -18,4 +18,8 @@ class UrlUtilsWrapper @Inject constructor() {
     fun addUrlSchemeIfNeeded(url: String, addHttps: Boolean): String {
         return UrlUtils.addUrlSchemeIfNeeded(url, addHttps)
     }
+
+    fun getHost(urlString: String?): String {
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/util/UrlUtilsWrapper.kt]: It seems `UrlUtils.getHost` can return null (result of `return uri.getHost();` is nullable). We probably either want to return `String?` or we might simply consider removing this method as it's not used anymore. Wdyt?

File: WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt (hunk 20 above)
Comment (malinajirka) [reply WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt]: Thanks for the explanation! The usage makes sense ;)

File: WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainSanitizer.kt (hunk 21 above)
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainSanitizer.kt]: Yes, this make sense. It's safer to use this than default and it's more likely to have the desired behavior in different languages.

File: WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainSanitizer.kt (hunk 22 above)
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainSanitizer.kt]: Yes, that was intentional. I thought if it begins with a `.` we should just remove it altogether. Especially since this check is ensuring that there will be characters present to perform the substring operation on. 

Yes, I was thinking to write a test for it but then I decided that the test case for the alphanumeric case covered it but it's something that can be done if we decide to change it's implementation.

File: WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModel.kt (hunk 23 above)
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModel.kt]: Yes, will revert it 🙏

File: WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModel.kt (hunk 24 above)
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModel.kt]: Thanks for spotting this. Didn't realize there wasn't a brace. I will put them. 

> Are we missing { here? I assume we want to wrap both query?.let and data.forEach, right? 

Not necessarily. I put this there so the query doesn't run a check against an empty set of domains because if it does then it won't find it and will show the unavailability state which would be incorrect since it wasn't compared against an actual result. Before doing this check the unavailability state would be visible while the suggestions are being loaded.

File: WordPress/src/main/java/org/wordpress/android/util/UrlUtilsWrapper.kt (hunk 25 above)
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/util/UrlUtilsWrapper.kt]: I am going to remove this because it's no longer used. 

> It seems UrlUtils.getHost can return null (result of return uri.getHost(); is nullable).
Yes, it is indeed nullable but they are doing a null check before accessing it so doesn't that negate its the ability for the result to be null? or can the state of it still be changed? Let me know.

File: WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainSanitizer.kt (hunk 22 above)
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainSanitizer.kt]: 👍 Thanks! ;)

File: WordPress/src/main/java/org/wordpress/android/util/UrlUtilsWrapper.kt (hunk 25 above)
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/util/UrlUtilsWrapper.kt]: >but they are doing a null check before accessing it 

You are absolutely right. I'm sorry, I missed it;).

File: WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModel.kt (hunk 24 above)
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModel.kt]: Thanks for the clarification;). I'm wondering if it would be better to move it to the `getDomainUnavailableUiState` since it's basically a logic related to it. Wdyt?

Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModel.kt]: Thanks that's a good suggestion. Will do the move!

**Comment by jkmassel** [comment]
We're freezing `13.8` today, so I'm moving this forward to `13.9`. If you'd like it released as part of `13.8`, please adjust the target from `develop` to `release/13.8`, and let me know once this PR has been merged – I'll be happy to ship a new release candidate!

File: WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModel.kt (hunk 24 above)
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModel.kt]: Resolved here 9efa053

File: WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainSanitizer.kt (hunk 21 above)
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainSanitizer.kt]: Resolved here 9156018
