### PR TITLE
[Jetpack Social] Hide Jetpack Social container if PostStatus is PRIVATE

### LINKED ISSUE #18927: Jetpack Social section is visible on private posts
Refs pctCYC-W4-p2#comment-989

### Expected behavior
The Jetpack Social section should be hidden from the pre-publishing sheet and post settings when the post is set to private.

### Actual behavior
The Jetpack Social section is shown for private posts, but the post is not auto-shared.

### Steps to reproduce the behavior

- Launch the Jetpack app.
- Create a new blog post.
- Set it to private.
- Observe that the Jetpack Social section is visible in post settings and pre-publishing sheet.

##### Tested on Jetpack Android 23.0-rc-1

### PR DESCRIPTION
**Pull request by RenanLukas**
Fixes #18927

To test:
You should not be able to reproduce the bug anymore. Steps to reproduce can be found in https://github.com/wordpress-mobile/WordPress-Android/issues/18927

## Regression Notes
1. Potential unintended areas of impact
Jetpack Social containers should continue to work as expected.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing + unit testing.

3. What automated tests I added (or what prevented me from doing so)
Updated `EditorJetpackSocialViewModelTest.kt`.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:

- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditorJetpackSocialViewModel.kt [hunk 1]
```diff
@@ -383,6 +391,10 @@ class EditorJetpackSocialViewModel @Inject constructor(
         if (trackEvent) jetpackSocialSharingTracker.trackAddConnectionCtaDisplayed(jetpackSocialFlow)
     }
 
+    fun onPostVisibilityChanged() {
```
Comment (thomashorta) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditorJetpackSocialViewModel.kt]: 🔍  Nitpick: the name of the field we are checking is `status`, should this method be called `onPostStatusChanged`? 

`Visibility` might be a confusing term since it might make one think of Android View visibility, especially since this is not the name of the post field we are using.

**Review by thomashorta — APPROVED** [review]
Looks good to me! I tested it as well and it's working correctly.

I only added a small nitpick regarding the naming of a method, but feel free to ignore if it doesn't make sense.
