### PR TITLE
Recover from inconsistent QUEUED/UPLOADING states - take 2

### LINKED ISSUE #6516: Media library inconsistent states
### Expected behavior
Uploading media items in the Media library should keep a coherent state even when the app is stopped.

### Actual behavior
If a media item was uploading and the app closes itself, the uploading item will remain uploading forever, unless the app's data is deleted (or app uninstalled and re-installed)

### Steps to reproduce the behavior
1. start uploading somethign (either by including media in a draft or by going to the media library  and adding a new item
2. stop the app (settings-> apps -> WordPress -> force stop)
3. open the app again
4. verify the item shows "UPLOADING" in the Media library

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #6516 by checking which media items have a `QUEUED` or `UPLOADING` state in FluxC's MediaStore, but are not being tracked by the UploadService (i.e. they're no really being queued to upload or uploading).

To test:
1. start uploading something (either by including media in a draft or by going to the media library  and adding a new item
2. stop the app (settings-> apps -> WordPress -> force stop)
3. open the app again
4. verify the item shows "RETRY" in the Media library

cc @aforcier

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java [hunk 1]
```diff
@@ -434,6 +435,33 @@ public static float getUploadProgressForMedia(MediaModel mediaModel) {
         return Collections.emptyList();
     }
 
+    public static boolean isPendingOrInProgressMediaUpload(MediaModel media) {
+        return MediaUploadHandler.isPendingOrInProgressMediaUpload(media);
+    }
+
+    /*
```
Comment (aforcier) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java]: Should make this a proper Javadoc comment.

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java [hunk 2]
```diff
@@ -434,6 +435,33 @@ public static float getUploadProgressForMedia(MediaModel mediaModel) {
         return Collections.emptyList();
     }
 
+    public static boolean isPendingOrInProgressMediaUpload(MediaModel media) {
```
Comment (aforcier) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java]: Since this is `public`, we should either mark `media` as `@NonNull`, or null-check it before we hand it off to `MediaUploadHandler` (or do this inside `MediaUploadHandler.isPendingOrInProgressMediaUpload()`).

**Comment by aforcier** [comment]
Looks good @mzorz! Aside from a few small nits above, this is good to go.

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java (hunk 1 above)
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java]: addressed in 36bfcb1

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java (hunk 2 above)
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java]: addressed in 7c9d18e

**Comment by mzorz** [comment]
> Looks good @mzorz! Aside from a few small nits above, this is good to go.

Cool! Ready for another round 👍

**Comment by aforcier** [comment]
:shipit:
