### PR TITLE
Remove inline styling from reader post content

### LINKED ISSUE #15547: Reader: Buttons not showing up in Reader
It was reported in 4440212-zd-woothemes that the buttons added to a post did not show up when the post was viewed on the app's Reader screen. However, the buttons are displaying correctly when viewed on a mobile browser.

### Expected behavior

Buttons show up in the app's Reader.

### Actual behavior

The buttons added to the post displayed as a blank rectangle. According to the user, they added the buttons through the web editor.

Screenshot_20211110_090032_org wordpress android

### Steps to reproduce the behavior

1. Open the app's reader, look for the site reported in the ticket.
2. Tap the latest post (titled MTL – 76+77) and scroll down to the bottom of the post.
3. Noticed that there are a few blank rectangles as shown in my screenshot above.
4. View the post on a web browser, notice the buttons are displayed correctly.

##### Tested on Huawei Nova 2i, Android 9, WPAndroid 18.5, Android System WebView 95.0.4638.74
Originally reported on Samsung SM-F711B, WPAndroid 18.5, Android System WebView 95.0.4638.74

### PR DESCRIPTION
**Pull request by zwarm**
Fixes #15547

This PR adds logic to `ReaderPostRenderer` to strip all inline `style` attributes from reader post content. This is done in place using jsoup, before the html is reworked to include any Android reader specific styling. Stripping all inline styles matches iOS processing.

**Notes**
This is the very first time that Android is stripping the inline styles. In addition to testing this as a fix for buttons, I also recommend testing all blocks in the reader to ensure we haven't introduced any other rendering issues. Having a few eyes on this would be better than just mine. Thanks. cc: @reginabally @yaelirub 

**To test:**
**Prerequisites**
- Two accounts are needed. 
- Account 1: Used to create the post.
- Account 2: Is a follower of account 1 

**Test**
- Login in to WP as Account 1 (via calypso or the app) 
- Create a new post
- Add a button (or multiple buttons)
- Publish the post

- Login in to the App as Account 2
- Navigate to reader
- Tap the post to view the details
- Note that buttons are shown as expected and not as empty boxes

*** Sometimes the cache doesn't refresh enough between new post creation and the post being injected with inline styles. So instead of the above instructions, you can run the test with the following post:  https://premiumtestsite20190311.blog/2021/11/10/test-button/

## Regression Notes
1. Potential unintended areas of impact
Block rendering weirdness across the board

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [X] I have completed the Regression Notes.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostRenderer.java [hunk 1]
```diff
@@ -277,6 +281,23 @@ private String getPostContent() {
...
+     */
+    private String removeInlineStyles(String content) {
+        if (content.length() == 0) {
+            return content;
+        }
+
+        try {
+            Document doc = Jsoup.parse(content);
+            doc.getAllElements().removeAttr("style");
+            return doc.select("body").toString();
```
Comment (twstokes) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostRenderer.java]: Nice solution!

I noticed that the returned HTML included the outer `body` tag, which appears to have been generated by jsoup since it wasn't included in the original `content` string. Do you think we should just return everything inside `body`?

[input.txt](https://github.com/wordpress-mobile/WordPress-Android/files/7549196/input.txt)
[output.txt](https://github.com/wordpress-mobile/WordPress-Android/files/7549197/output.txt)

**Review by twstokes — COMMENTED** [review]
I tested this PR on Android and it properly rendered the buttons. 🎉 

- [Test post](https://twstokes.wordpress.com/2021/11/12/testing-another-button-failure/) with [content that includes inline styles](https://public-api.wordpress.com/rest/v1.2/read/sites/38994839/posts/335?fields=content).

**Android Before / After**
<div>
Android before
Android after
</div>

**iOS**
<div>
iOS
</div>

**Comment by twstokes** [comment]
@zwarm, in my testing new posts didn't exhibit the problems in current Android builds until some time had passed (the caching issue we discovered). Context: p1636727292109300-slack-C011BKNU1V5

I can keep the post [I shared here](https://github.com/wordpress-mobile/WordPress-Android/pull/15576#pullrequestreview-807737695) up if you'd like to update the testing steps to ensure the user lands on a post that includes the inline styles.

**Comment by zwarm** [comment]
> @zwarm, in my testing new posts didn't exhibit the problems in current Android builds until some time had passed (the caching issue we discovered). Context: p1636727292109300-slack-C011BKNU1V5
> 
> I can keep the post [I shared here](https://github.com/wordpress-mobile/WordPress-Android/pull/15576#pullrequestreview-807737695) up if you'd like to update the testing steps to ensure the user lands on a post that includes the inline styles.

Aah, good idea, I have so many old button posts that I didn't need to worry about it. I'll update the testing instructions so that folks can use the original post in which the issue was exposed.

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostRenderer.java (hunk 1 above)
Comment (zwarm) [reply WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostRenderer.java]: Nice catch, 60a5853 changes that.

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostRenderer.java [hunk 2]
```diff
@@ -3,7 +3,10 @@
 import android.annotation.SuppressLint;
 import android.net.Uri;
 import android.os.Handler;
+import android.util.Log;
```
Comment (twstokes) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostRenderer.java]: Do we need to keep this?

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostRenderer.java [hunk 3]
```diff
@@ -277,6 +282,23 @@ private String getPostContent() {
...
+    /*
+     * Strips inline styles from post content
+     */
+    private String removeInlineStyles(String content) {
+        if (content.length() == 0) {
+            return content;
+        }
+
+        try {
+            return Jsoup.parse(content)
```
Comment (twstokes) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostRenderer.java]: Nice! I tested this in case a tagless string were to get through with a length > 0 (e.g. `"    "`) and it still worked well since we should always have a `first()` body, and `toString()` on an empty list of `children()` is OK. 👍 

**Optional thought:**
- We may want to consider parsing this content [as a body fragment](https://jsoup.org/cookbook/input/parse-body-fragment) since we're not looking for document correctness. This would involve just replacing `Jsoup.parse()` with `Jsoup.parseBodyFragment()`.

**Review by twstokes — APPROVED** [review]

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostRenderer.java (hunk 2 above)
Comment (zwarm) [reply WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostRenderer.java]: nope, removed

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostRenderer.java (hunk 3 above)
Comment (zwarm) [reply WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostRenderer.java]: > I tested this in case a tagless string were to get through with a length > 0 (e.g. " ")

Me too, but html is funky and you never know what you're going to get. That's why I guarded jsoup with a `try/catch`. No matter how well you think you've covered all the permutations, one misplaced bracket and all goes awry. 

BTW, I did use `Jsoup.parseBodyFragment()` originally, but the resulting document still included the html/head/body tags. Ultimately it didn't make a difference whether `parse` vs `parseBodyFragment` was used. I chose `parse` 🤷  I have no issues changing it to `Jsoup.parseBodyFragment()`, as it sounds like you have more experience with the library than I do. With that said, I did find a way to remove the `children` call. So thanks for that.

**Review by twstokes — APPROVED** [review]
LGTM! @zwarm you may want to run this by another Android dev for total assurance since I'm mostly iOS, but it seems solid to me. 😄

**Comment by zwarm** [comment]
> LGTM! @zwarm you may want to run this by another Android dev for total assurance since I'm mostly iOS, but it seems solid to me. 😄

**Review by ashiagr — APPROVED** [review]
Hey @zwarm 

I tested your changes and confirm that I can now see button text properly in the `Reader` in both light and dark mode.

I also noted that earlier, the button text was visible only in the dark mode. So it seems like inline styling did not work well with the light and dark modes. Keeping this in mind and matching with iOS processing to strip all inline styles looks like the way to go. 👍

**Comment by zwarm** [comment]
@ashiagr 

> I also noted that earlier, the button text was visible only in the dark mode. So it seems like inline styling did not work well with the light and dark modes.  

Exactly - the inline styles include #fff as the text color - would never work on light mode, plus the alignment was all wrong. 

Many thanks for reviewing, appreciate it. 🙇
