### PR TITLE
issue/5076-reader-unfollow-deleted-site

### LINKED ISSUE #5076: Reader: Error unfollowing a site that has been deleted
To reproduce:

1. Create a new wpcom blog.
2. Follow the blog
3. In your Reader's following stream, confirm that posts from the blog appear.
4. Delete the wpcom blog.
5. Go to the Reader's Manage Sites screen and try to unfollow the delete blog. 

You'll see an error message stating that API requests have been disabled for that site, and the site is not removed from your following list.

I tried to reproduce this in the web reader and was able to successfully unfollow the site.  This suggests we need to update which endpoints the app calls to unfollow a site.

@nbradbury 

cc @aerych as this is present in the iOS reader as well.
https://github.com/wordpress-mobile/WordPress-iOS/issues/6457

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #5076 

To test: 
* Create a temporary blog
* Follow it in the reader
* Delete the blog
* Try to unfollow it from the mobile reader

Prior to this change, it would be impossible to unfollow a deleted blog.

Note: This was originally going to be resolved on the backend but that proved problematic. The solution is for the mobile apps to detect when unfollowing a blog by ID results in a 403 and then use the `/read/following/mine/delete?url=` endpoint to unfollow by URL (that endpoint isn't as reliable as unfollowing by ID, which is why we don't use it in the first place).

cc: @aerych

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderBlogActions.java [hunk 1]
```diff
@@ -80,9 +80,17 @@ public void onResponse(JSONObject jsonObject) {
...
-                    actionListener.onActionResult(false);
+                // check if we get a 403 when unfollowing - this will happen when we attempt
+                // to unfollow a blog that no longer exists - the workaround is to unfollow
+                // by url - note that the v1.2 endpoint will return a 404 in this situation
+                int status = VolleyUtils.statusCodeFromVolleyError(volleyError);
+                if (status == 403 && !isAskingToFollow) {
+                    internalUnfollowBlogByUrl(blogId, actionListener);
+                } else {
+                    localRevertFollowBlogId(blogId, isAskingToFollow);
+                    if (actionListener != null) {
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderBlogActions.java]: I know this is actually not new, but should we use `ReaderActions.callActionListener(actionListener, false);` here to be consistent?

File: WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderBlogActions.java [hunk 2]
```diff
@@ -80,9 +80,17 @@ public void onResponse(JSONObject jsonObject) {
...
                 AppLog.e(T.READER, volleyError);
-                localRevertFollowBlogId(blogId, isAskingToFollow);
-                if (actionListener != null) {
-                    actionListener.onActionResult(false);
+                // check if we get a 403 when unfollowing - this will happen when we attempt
+                // to unfollow a blog that no longer exists - the workaround is to unfollow
+                // by url - note that the v1.2 endpoint will return a 404 in this situation
+                int status = VolleyUtils.statusCodeFromVolleyError(volleyError);
+                if (status == 403 && !isAskingToFollow) {
+                    internalUnfollowBlogByUrl(blogId, actionListener);
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderBlogActions.java]: This is super minor, but it might be helpful to add a comment here stating that the `actionListener` methods will be called from within the method. At first glance, it looks no action is called after the request which of course not the case.

**Comment by oguzkocer** [comment]
@nbradbury this is not directly related to this PR, but while reviewing I have noticed that we are tracking the follow/unfollow actions before the requests are completed [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderBlogActions.java#L54-L58). Do you think we should do them after successful requests, especially since there are some expected edge cases like the one in the PR and probably some more?

File: WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderBlogActions.java (hunk 1 above)
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderBlogActions.java]: Good catch - I just updated `ReaderBlogActions` to use `callActionListener` in 30efed3

File: WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderBlogActions.java (hunk 2 above)
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderBlogActions.java]: I think the fact that the action listener is passed to `internalUnfollowBlogByUrl` makes it clear that it will take care of calling it. I'd rather not add another comment (seems like more noise) but it's not a big deal to me and I'll do it if you still feel it's necessary.

**Comment by nbradbury** [comment]
> I have noticed that we are tracking the follow/unfollow actions before the requests are completed here. Do you think we should do them after successful requests, especially since there are some expected edge cases like the one in the PR and probably some more?

I think what we want to track is user behavior rather than app behavior. I just discussed this with @aerych and he agrees and has coded the iOS app to do the same.

File: WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderBlogActions.java (hunk 2 above)
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderBlogActions.java]: Makes sense, we can leave it as is :)

**Comment by oguzkocer** [comment]
> I think what we want to track is user behavior rather than app behavior. I just discussed this with @aerych and he agrees and has coded the iOS app to do the same.

Cool, it makes sense then! Thanks for the clarification!

**Comment by oguzkocer** [comment]
Looks good :shipit:
