### PR TITLE
FluxC migration fixes

### LINKED ISSUE #5287: Crash report alpha-37: NPE in WPLegacyMigrationUtils.getDraftsFromDeprecatedDB
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at org.wordpress.android.util.WPLegacyMigrationUtils.getDraftsFromDeprecatedDB(WPLegacyMigrationUtils.java:253)
       at org.wordpress.android.util.WPLegacyMigrationUtils.migrateDraftsFromDeprecatedDB(WPLegacyMigrationUtils.java:80)
       at org.wordpress.android.WordPress.migrateDrafts(WordPress.java:349)
       at org.wordpress.android.WordPress.migrateSelfHostedSites(WordPress.java:343)
       at org.wordpress.android.WordPress.onSiteChanged(WordPress.java:544)
       at java.lang.reflect.Method.invoke(Method.java)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
       at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

### PR DESCRIPTION
**Pull request by aforcier**
Fixes #5287 and #5298.

* Added tests for self-hosted site and draft migration (with special attention to null values)
* Fixed source of #5287 NPE: https://github.com/wordpress-mobile/WordPress-Android/commit/2a819f45a9cc81098cae97e63f31c458be23f73c
* Fixed an issue where self-hosted sites connected to a different WP.com account than the current one would cause any self-hosted sites after it to fail to be migrated: https://github.com/wordpress-mobile/WordPress-Android/commit/7471bc17ff93c318edff9df0a00c2fea45da4927
* Fixed a potential NPE when the local site for a post doesn't exist (hasn't happened yet): https://github.com/wordpress-mobile/WordPress-Android/commit/ef5de08a07395cfee2fb1b7c026007f5fdb67a2a
* Change the migration message to `Updating the WordPress app...`

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/util/WPLegacyMigrationUtils.java [hunk 1]
```diff
@@ -144,10 +145,10 @@ public static boolean hasSelfHostedSiteToMigrate(Context context) {
         }
     }
 
-    private static List<SiteModel> getSelfHostedSitesFromDeprecatedDB(Context context) {
+    static List<SiteModel> getSelfHostedSitesFromDeprecatedDB(Context context) {
```
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/util/WPLegacyMigrationUtils.java]: I found one thing we should do here (or maybe change the default value in the SiteModel in FluxC). We must set the isVisible flag to true, self hosted sites are always visible. Also I'm not sure we update that flag for self hosted on site fetched in FluxC.

Comment (aforcier) [inline WordPress/src/main/java/org/wordpress/android/util/WPLegacyMigrationUtils.java]: It looks like we [do update it](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/1939af38af3d07f620a0ab507cfee0c584a63bff/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/site/SiteXMLRPCClient.java#L166) when newly fetching self-hosted sites in FluxC (through `FETCH_SITES_XML_RPC`, which WPAndroid calls in `SignInFragment`).

But we don't call `FETCH_SITES_XML_RPC` for migrated sites, so we don't update the flag.

I think it would make the most sense to init `SiteModel.mIsVisible` as `true`, and only worry about changing it for REST sites.

Comment (aforcier) [inline WordPress/src/main/java/org/wordpress/android/util/WPLegacyMigrationUtils.java]: I've opened a new issue to fix `SiteModel` fields not populated during migration (including `isVisible`): https://github.com/wordpress-mobile/WordPress-Android/issues/5306.

**Comment by maxme** [comment]
:shipit:
