### PR TITLE
Login: Adds error details to events.

### LINKED ISSUE #5439: Analytics/Login: Include error information as properties when tracking login failures.
Currently we only track that a login failed.  It would be helpful to include error information (if any) as properties for the login failure event.
Properties can include: 
`error_code` : An HTTP status code, or domain specific error code.
`error_description` : The plain text description of the error. 
`error_domain` : A platform specific "domain" for the error, if one is defined.
to match what is tracked on iOS.

### PR DESCRIPTION
**Pull request by aerych**
Fixes #5439 
This adds a new tracker method to the AnalyticsTracker and calls this method for login failures.

To test:
- Set a break point in the newly added `track` method. 
- Be signed out of the app. 
- Try logging into wpcom with bad credentials.  Confirm that the new track method is called.
- Try logging into a self-hosted blog but mistype the URL to point to a non-WordPress site.  (Get a cup of coffee while you wait.)  Confirm that the new track method is called.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInFragment.java [hunk 1]
```diff
@@ -1226,7 +1226,8 @@ public void onAccountChanged(OnAccountChanged event) {
     public void onAuthenticationChanged(OnAuthenticationChanged event) {
         if (event.isError()) {
             AppLog.e(T.API, "onAuthenticationChanged has error: " + event.error.type + " - " + event.error.message);
-            AnalyticsTracker.track(Stat.LOGIN_FAILED);
+            AnalyticsTracker.track(Stat.LOGIN_FAILED, event.getClass().getSimpleName(), event.error.type.toString(), event.error.message);
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInFragment.java]: Are we sure that `event.getClass().getSimpleName()` is what we want to use as the `errorContext`? This is the simplified Java class name of the event object.

File: libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java [hunk 2]
```diff
@@ -269,6 +270,13 @@ public static void track(Stat stat, Map<String, ?> properties) {
         }
     }
 
+    public static void track(Stat stat, String errorContext, String errorType, String errorDescription) {
```
Comment (nbradbury) [inline libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java]: It would be helpful to have a comment header explaining what each of these parameters is.

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInFragment.java (hunk 1 above)
Comment (aerych) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInFragment.java]: Yeah, I'm not sure what would be best, but the class name is probably fine for now.  The goal is to just get more context about the failure event.

**Comment by aerych** [comment]
Thanks for taking a peek @nbradbury.  Good call about adding a comment.  
On the other issue, I think its fine to use the simplified class name for now, but I'm open to suggestions on a better choice.

**Comment by nbradbury** [comment]
:shipit:

**Comment by aerych** [comment]
Thanks Nick!! :)
