### PR TITLE
Comments list: fixed images embedded within comments

### LINKED ISSUE #3946: Comments: Images in a comment in the comment list show up as a small "OBJ" inside a dotted border.
I have a few comments that include images.   In the comments list the images are replaced with a small dotted square, with "OBJ" inside.  It looks a bit odd.  Maybe we should filter out image tags from the comment in the list? 
(Nexus 5x)
screenshot_20160411-192401

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #3946

To test: 
Just go the Comments section in the app, and check the list. If you have comments with embedded images, those should appear right there, as in the following screenshot

screen shot 2016-04-27 at 7 44 05 pm

Needs review: @nbradbury

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/comments/CommentAdapter.java [hunk 1]
```diff
@@ -425,7 +425,8 @@ protected Boolean doInBackground(Void... params) {
                 return false;
             }
 
-            final int maxImageWidth = ImageUtils.getMaximumImageWidthForComment(mContext);
+            final int maxImageWidth = (int) mContext.getResources().getDimension(R.dimen.reader_comment_embedded_image_max_size); //ImageUtils.getMaximumImageWidthForComment(mContext);
```
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/comments/CommentAdapter.java]: That works well for image based emojis, but IMO that's not a good solution for other images (especially photos)
screenshot-2016-04-28_11 01 19 993

Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/comments/CommentAdapter.java]: Also since it's just a comment preview, I wonder if we should strip all images from the previews.

Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/comments/CommentAdapter.java]: agh! that's ugly - ok makes sense, let me work on that and get back to you. Thanks!

**Comment by mzorz** [comment]
Ok @maxme fixed this one - I'm [passing a null ImageGetter](https://github.com/wordpress-mobile/WordPress-Android/pull/4027/files#diff-9bf89cfb41a8e6dc16df599edefa9f06R437) because the "stripping" is taken care of by the WPHtml parser now ([here](https://github.com/wordpress-mobile/WordPress-Android/pull/4027/files#diff-b95d8b18221fd9c725b09c3ba2ff2112R873)), which is something I think we would like to keep now that it's done. 
Now, if another dev wants to use our WPHtml class for parsing html with the things that have been modified in there, they can just add an ImageGetter the same way it's done on the Android Html class (before this, our class would just never use the ImageGetter even if passed in as a parameter).

This is how it looks now (check the first comment and compare to the screenshot in [my first comment](https://github.com/wordpress-mobile/WordPress-Android/pull/4027#issue-151510743)) 
screen shot 2016-04-28 at 10 44 54 am

**Comment by maxme** [comment]
> if another dev wants to use our WPHtml class for parsing html with the things that have been modified in there, they can just add an ImageGetter the same way it's done on the Android Html class (before this, our class would just never use the ImageGetter even if passed in as a parameter).

👍 

Looks good, :shipit:
