### PR TITLE
Fix NPE crash when reponse doesn't contains settings object

### LINKED ISSUE #12552: NullPointerException: Attempt to invoke virtual method 'int org.json.JSONObject.optInt(java.lang.String, int)' on a nul...
Another issue with very low number of users but very high number of events, so might be worth prioritizing. The first release seems wrong to me, not sure why. `15.0` seems like the first meaningful release for this.

**Sentry Url**: https://sentry.io/share/issue/cdafd860323d4df49e911de5ce5af741/
**User Count**: 5
**Count**: 590
**First Release**: org.wordpress.android-12.8
**First Seen**: 2019-07-25T20:17:52Z
**Last Seen**: 2020-07-20T14:26:07Z
**24 Hours**: 0
**30 Days**: 515

```
NullPointerException: Attempt to invoke virtual method 'int org.json.JSONObject.optInt(java.lang.String, int)' on a null object reference
     at org.wordpress.android.ui.prefs.WPComSiteSettings.deserializeWpComRestResponse(WPComSiteSettings.java:662)
     at org.wordpress.android.ui.prefs.WPComSiteSettings.access$000(WPComSiteSettings.java:31)
     at org.wordpress.android.ui.prefs.WPComSiteSettings$1.onResponse(WPComSiteSettings.java:178)
     at org.wordpress.android.ui.prefs.WPComSiteSettings$1.onResponse(WPComSiteSettings.java:171)
...
(4 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by planarvoid**
Fixes #12552 

This PR fixes a NPE crash when the response JSON doesn't contain the "Settings" object. I think logging this state and just returning in this case is a good enough solution (as we do the same thing in other cases as well). Let me know what you think

To test:
- I don't know how to reproduce this issue. 

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/prefs/WPComSiteSettings.java [hunk 1]
```diff
@@ -653,6 +653,10 @@ private void onSaveResponseReceived(Exception error) {
     private void deserializeWpComRestResponse(SiteModel site, JSONObject response) {
         if (site == null || response == null) return;
         JSONObject settingsObject = response.optJSONObject("settings");
+        if (settingsObject == null) {
+            AppLog.w(AppLog.T.API, "Error: Settings response doesn't contain settings object");
```
Comment (mchowning) [inline WordPress/src/main/java/org/wordpress/android/ui/prefs/WPComSiteSettings.java]: Not a big deal, but I'm curious why you decided to go with a warning instead of an error. It seems like this is a pretty exceptional case that shouldn't really ever happen (unless you're the one user who seems to get this error all the time). This certainly is not a blocker.

**Review by mchowning — APPROVED** [review]
One small question, but code looks good and tested this by forcing `settingsObject` to be `null` and I didn't observe any issues.

File: WordPress/src/main/java/org/wordpress/android/ui/prefs/WPComSiteSettings.java (hunk 1 above)
Comment (planarvoid) [reply WordPress/src/main/java/org/wordpress/android/ui/prefs/WPComSiteSettings.java]: I was following the same approach as we have in the `onFailure` callback when requesting settings. However, I think you're right so I'm changing it 👍
