### PR TITLE
Issue/people management username fixes

### LINKED ISSUE #4350: People: Backspace v. tapping to remove a username/email address from an invitation
### Expected behavior

When inviting a new user, after entering a username or email address in the invitation form I expect to be able to backspace or tap the "x" to remove them. (Both methods work in Calypso web for removing an invited user from the invitation form.)

### Actual behavior

I can only tap the "x" to remove the username or email address I entered in the invitation. Although I have a cursor (for entering more in the username/email field) I can't backspace to remove a previous entry in that field:

### Steps to reproduce the behavior

1. In the app, go to the site dashboard > People
2. Tap the plus icon to invite a new user
3. Enter a username or email address in the "Usernames or Emails" field
4. Tap enter or tap outside the "Usernames or Emails" field to complete the entry (an "x" will appear next to the username/email you entered)
5. Backspace to try to remove that username/email. Result: The cursor can't backspace over that username/email.
6. Tap the "x" to try to remove that username/email. Result: the username/email is removed.

### LINKED ISSUE #4356: People: Should not be possible to enter more than 10 usernames/emails in invite form
### Expected behavior

When inviting users to join a site, I expect the invite form to limit me to 10 usernames/emails at a time, like in Calypso web:

screen shot 2016-07-06 at 3 03 21 pm

After entering 10 usernames/emails in that web form, the "Usernames or Emails" field won't accept any more entries.

### Actual behavior

I can enter as many usernames/emails as I want in the "Usernames or Emails" field in the invite form.

However, after I hit "Send" 10 of the usernames/emails I entered (not necessarily the first 10) disappear from the form, and this message appears: `An error occured while trying to send the invite!`

After that message disappears, this message appears: `Invite sent successfully`

The 10 usernames/emails that disappeared receive an invite, but any remaining usernames/emails in the invite form don't get the invite. It isn't clear from the app messaging what happened and why.

### Steps to reproduce the behavior

1. Go to the site dashboard > People in the app
2. Tap the plus icon in the top right to invite new users
3. In the "Usernames or Emails" field, enter at least 11 usernames/emails
4. Tap SEND in the top right to send the invite

##### Tested on Nexus 9, Android 6.0.1, WPAndroid alpha-16

### LINKED ISSUE #4357: People Management: comma should act as separator when inviting users
### Expected behavior
When I type in multiple users into the 'Usernames or Emails' textbox, I expect to be able to separate them using a comma.

### Actual behavior
Instead, the comma is added as part of the email/username and the email/username is marked as invalid

screenshot_20160706-115403

### Steps to reproduce the behavior
1. Go to the People area for a site
2. Click on the '+' 
3. Try to add new users with a comma separating the users on the list

##### Tested on [device], Android [version]
alpha-16, nexus 6, android 6.0.1

### PR DESCRIPTION
**Pull request by khaykov**
This PR addresses multiple related issues with inviting users (People Management). 

Fixes #4350 - Adds the ability to remove usernames by pressing backspace. You can't detect backspace in empty EditText, so this solution is based on maintaining permanent whitespace inside EditText and managing the cursor position to hide it from user. A bit hacky, but works.

Fixes #4356 - Adds the hard limit (10) of usernames that could be entered by user and adds the explanation text (copied from Calypso).

Fixes #4357 - Adds the comma (,) as a delimiter for usernames. Comma is not actually displayed but used for convenience when entering multiple usernames. Code also adds possibility to easily add other delimiters.

people

### CODE REVIEW

**Comment by oguzkocer** [comment]
pinging @hypest to make sure he sees the PR. Thanks @khaykov!

File: WordPress/src/main/java/org/wordpress/android/ui/people/PeopleInviteFragment.java [hunk 1]
```diff
@@ -113,28 +119,69 @@ public View onCreateView(final LayoutInflater inflater, ViewGroup container, Bun
...
 
         String role = mRole;
         if (role == null) {
             role = loadDefaultRole();
         }
 
-        mUsernameEditText = (EditText) getView().findViewById(R.id.invite_usernames);
+        mUsernameEditText = (MultiUsernameEditText) view.findViewById(R.id.invite_usernames);
+        mUsernameEditText.setText(" ");
+        mUsernameEditText.setSelection(1);
```
Comment (hypest) [inline WordPress/src/main/java/org/wordpress/android/ui/people/PeopleInviteFragment.java]: Hey @khaykov , let'a add a comment here about the setting of the space char and the selection.

Additionally and since this `setText(" ")` is used a few times, what about having it in function even though it's one line of code? I think it would benefit the code readability. Thanks!

File: WordPress/src/main/java/org/wordpress/android/ui/people/PeopleInviteFragment.java [hunk 2]
```diff
@@ -113,28 +119,69 @@ public View onCreateView(final LayoutInflater inflater, ViewGroup container, Bun
...
             @Override
-            public void beforeTextChanged(CharSequence s, int start, int count, int after) {}
+            public void beforeTextChanged(CharSequence s, int start, int count, int after) {
+            }
 
             @Override
             public void onTextChanged(CharSequence s, int start, int before, int count) {
-                if (mUsernameEditText.getText().toString().endsWith(" ")) {
+                if (shouldIgnoreChanges) //used to avoid double call after calling setText from this method
+                    return;
```
Comment (hypest) [inline WordPress/src/main/java/org/wordpress/android/ui/people/PeopleInviteFragment.java]: Let's wrap this in braces to respect the coding style (see: https://source.android.com/source/code-style.html#use-standard-brace-style). Thanks!

File: WordPress/src/main/java/org/wordpress/android/ui/people/PeopleInviteFragment.java [hunk 3]
```diff
@@ -195,11 +237,36 @@ public void onTextChanged(CharSequence s, int start, int before, int count) {
...
 
             @Override
-            public void afterTextChanged(Editable s) {}
+            public void afterTextChanged(Editable s) {
+            }
         });
         updateRemainingCharsView(remainingCharsTextView, mCustomMessage, MAX_CHARS);
     }
 
+    private boolean isUsernameContainsDelimiter(String username) {
```
Comment (hypest) [inline WordPress/src/main/java/org/wordpress/android/ui/people/PeopleInviteFragment.java]: Nit: may I suggest renaming this to something like `endsWithDelimiter(String str)`?
Currently, the "...Contains.." part gives the wrong impression on the functionality. Also, it's a plain string function so no need for using "username" anyway.

File: WordPress/src/main/java/org/wordpress/android/ui/people/PeopleInviteFragment.java [hunk 4]
```diff
@@ -261,7 +328,7 @@ private void addUsername(EditText editText, ValidationEndListener validationEndL
 
         mUsernameButtons.put(username, usernameButton);
 
-        validateAndStyleUsername(Arrays.asList(new String[]{ username }), validationEndListener);
+        validateAndStyleUsername(Arrays.asList(new String[]{username}), validationEndListener);
```
Comment (hypest) [inline WordPress/src/main/java/org/wordpress/android/ui/people/PeopleInviteFragment.java]: Since we're modifying this line, feel free to remove the String array creation, just like AS suggests (`Array.asList` is a varargs method). Thanks!

File: WordPress/src/main/java/org/wordpress/android/ui/people/PeopleInviteFragment.java [hunk 5]
```diff
@@ -113,28 +119,69 @@ public View onCreateView(final LayoutInflater inflater, ViewGroup container, Bun
...
 
-        mUsernameEditText = (EditText) getView().findViewById(R.id.invite_usernames);
+        mUsernameEditText = (MultiUsernameEditText) view.findViewById(R.id.invite_usernames);
+        mUsernameEditText.setText(" ");
+        mUsernameEditText.setSelection(1);
+
+        mUsernameEditText.setOnSelectionChangeListener(new MultiUsernameEditText.OnSelectionChangeListener() {
+            @Override
+            public void onSelectionChanged(int selStart, int selEnd) {
+                if (selEnd == 0) {
```
Comment (hypest) [inline WordPress/src/main/java/org/wordpress/android/ui/people/PeopleInviteFragment.java]: I'm afraid this picks up a case we might not want the deletion to happen: when doing a "select all" in the EditText the empty space is selected as well and so, deleting it ends up removing the previous username as well.

**Comment by hypest** [comment]
Hey @khaykov , thanks for this PR!

I've finished my review pass. There's only one "blocker" for me: the accidental removal of the last username when "selecting all" the text and deleting.

BTW, I wish the PR wasn't bundling more than one issue fix. I would actually merge the fixes for the delimiters and the 10-username limit :)

Let me know when you want me to do another pass. Thanks!

**Comment by khaykov** [comment]
@hypest Thanks for the review! I changed the way backspace is handled, and I think I'm ready for another pass!

File: WordPress/src/main/java/org/wordpress/android/ui/people/PeopleInviteFragment.java [hunk 6]
```diff
@@ -244,14 +244,18 @@ private boolean endsWithDelimiter(String string) {
         }
 
         for (String usernameDelimiter : USERNAME_DELIMITERS) {
-            if (string.endsWith(usernameDelimiter)) return true;
+            if (string.endsWith(usernameDelimiter)){
```
Comment (hypest) [inline WordPress/src/main/java/org/wordpress/android/ui/people/PeopleInviteFragment.java]: Hey @khaykov , not sure if you made this change due to my earlier braces comment but, just wanted to mention that the brace-less single line is acceptable anyway. Notice that in https://source.android.com/source/code-style.html#use-standard-brace-style, the non-acceptable form is the multiline-without-braces. Thanks!

**Comment by khaykov** [comment]
@hypest I fixed the issue with hardware keyboard and black EditText on api 16. Thanks for waiting!

**Comment by hypest** [comment]
Thanks for the effort @khaykov ! I think this works well!

:ship: it!
