### PR TITLE
fix #3379: replace outdated GCMRegistrar/GCMIntentService with Google Play Services

### LINKED ISSUE #3379: Replace GCMBaseIntentService with GcmListenerService
`GCMBaseIntentService` has been deprecated for a while now, and we have some NPEs due it:

```
Fatal Exception: java.lang.NullPointerException
       at com.google.android.gcm.GCMBaseIntentService.onHandleIntent(GCMBaseIntentService.java:194)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

This NPE has been fixed in newer GCM services. See https://developers.google.com/android/reference/com/google/android/gms/gcm/GcmListenerService

### PR DESCRIPTION
**Pull request by maxme**
fix #3379: replace outdated GCMRegistrar/GCMIntentService with Google Play Services

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/notifications/utils/NotificationsUtils.java [hunk 1]
```diff
@@ -85,11 +84,6 @@ public static void getPushNotificationSettings(Context context, RestRequest.List
         if (!AccountHelper.isSignedInWordPressDotCom()) {
             return;
         }
-
-        if (TextUtils.isEmpty(GCMRegistrar.getRegistrationId(context))) {
-            AppLog.e(T.NOTIFS, "can't get push notification settings, gcm token is null.");
-        }
-
```
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/notifications/utils/NotificationsUtils.java]: @roundhill I removed the Log above cause we can't test synchronously for a Registration Id anymore. But we'll still have error messages in logs if Play Services are not available or if gcm token is not ready (added in 5febc66259e7de56020f208d59f7ada3641458d7)

Comment (roundhill) [inline WordPress/src/main/java/org/wordpress/android/ui/notifications/utils/NotificationsUtils.java]: OK, thanks for the heads up.

File: WordPress/src/zbetagroup/AndroidManifest.xml [hunk 2]
```diff
@@ -1,28 +0,0 @@
...
-    <!-- GCM configuration -->
-    <permission
-        android:name="org.wordpress.android.beta.permission.C2D_MESSAGE"
-        android:protectionLevel="signature"/>
-
-    <uses-permission android:name="org.wordpress.android.beta.permission.C2D_MESSAGE"/>
-
-    <application>
-
-        <!-- We've used a custom receiver here. The one that is bundled in GCM API wasn't able to start the service. -->
```
Comment (daniloercoli) [inline WordPress/src/zbetagroup/AndroidManifest.xml]: No more custom receiver? Is the configuration of PNs for the beta release done in another place, or it is handled automatically by GCM?

File: WordPress/src/main/java/org/wordpress/android/GCMRegistrationIntentService.java [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+            String token = instanceID.getToken(gcmId, GoogleCloudMessaging.INSTANCE_ID_SCOPE, null);
+            sendRegistrationToken(token);
+        } catch (Exception e) {
+            // SecurityException can happen on some devices without Google services (these devices probably strip
+            // the AndroidManifest.xml and remove unsupported permissions).
+            AppLog.e(T.NOTIFS, "Google Play Services unavailable: ", e);
+        }
+    }
+
+    public void sendRegistrationToken(String gcmToken) {
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/GCMRegistrationIntentService.java]: Can we add a log line here ?
` AppLog.d(T.NOTIFS, "Registering the following PN token : " + gcmToken);`

File: WordPress/src/main/java/org/wordpress/android/GCMRegistrationIntentService.java [hunk 4]
```diff
@@ -0,0 +1,65 @@
...
+        if (!TextUtils.isEmpty(gcmToken)) {
+            // Register to WordPress.com notifications
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/GCMRegistrationIntentService.java]: Can we add a log line here ?
`AppLog.d(T.NOTIFS, "Registering the following PN token : " + gcmToken);`

That way we can see the token in the log the user uploads when asking for help, without querying the DB on the server side.

File: WordPress/src/zbetagroup/AndroidManifest.xml (hunk 2 above)
Comment (maxme) [inline WordPress/src/zbetagroup/AndroidManifest.xml]: I read the documentation again, I got confused because their sample app doesn't reflect it: ([AndroidManifest](https://github.com/googlesamples/google-services/blob/master/android/gcm/app/src/main/AndroidManifest.xml))

The doc says `C2D_MESSAGE` perm is only needed to prevent other apps to hijack PNs - I'll add that again, but I don't think we need a specific case for release or beta.

File: WordPress/src/main/java/org/wordpress/android/GCMRegistrationIntentService.java (hunk 4 above)
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/GCMRegistrationIntentService.java]: Added in 197b565

File: WordPress/src/zbetagroup/AndroidManifest.xml (hunk 2 above)
Comment (maxme) [inline WordPress/src/zbetagroup/AndroidManifest.xml]: Added the permission in da7558a - tested on both release/beta versions - work as expected.

Comment (daniloercoli) [inline WordPress/src/zbetagroup/AndroidManifest.xml]: :+1:

**Comment by daniloercoli** [comment]
:shipit:
