### PR TITLE
Guard the opening of invite screen for null blogid

### LINKED ISSUE #4812: Crash report 6.1: IAE in PeopleInviteFragment.isPrivateSite
```
Fatal Exception: java.lang.IllegalArgumentException: the bind value at index 2 is null
       at android.database.sqlite.SQLiteProgram.bindString(SQLiteProgram.java:176)
       at android.database.sqlite.SQLiteProgram.bindAllArgsAsStrings(SQLiteProgram.java:212)
       at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:47)
       at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1454)
       at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1301)
       at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1172)
       at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1340)
       at org.wordpress.android.WordPressDB.getBlogForDotComBlogId(WordPressDB.java:934)
       at org.wordpress.android.ui.people.PeopleInviteFragment.isPrivateSite(PeopleInviteFragment.java:660)
       at org.wordpress.android.ui.people.PeopleInviteFragment.getDefaultRole(PeopleInviteFragment.java:279)
       at org.wordpress.android.ui.people.PeopleInviteFragment.onViewCreated(PeopleInviteFragment.java:123)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:998)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1163)
       at android.app.BackStackRecord.run(BackStackRecord.java:793)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1552)
       at android.app.FragmentManagerImpl$1.run(FragmentManager.java:487)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7225)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

### PR DESCRIPTION
**Pull request by hypest**
Fixes #4812 

Adds a check (and a log entry) early on around the opening of the People's Invite screen to guard for the case where the (remote) blogId is null. 

/cc @maxme

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/people/PeopleManagementActivity.java [hunk 1]
```diff
@@ -226,9 +228,15 @@ public boolean onOptionsItemSelected(final MenuItem item) {
 
             if (peopleInviteFragment == null) {
                 Blog blog = WordPress.getCurrentBlog();
-                peopleInviteFragment = PeopleInviteFragment.newInstance(blog.getDotComBlogId());
+                String dotComBlogId = blog.getDotComBlogId();
+                if (dotComBlogId != null && !dotComBlogId.isEmpty()) {
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/people/PeopleManagementActivity.java]: We could probably use  `if(!TextUtils.isEmpty(dotComBlogId))` here to simplify it a little bit.

File: WordPress/src/main/java/org/wordpress/android/ui/people/PeopleManagementActivity.java [hunk 2]
```diff
@@ -226,9 +228,15 @@ public boolean onOptionsItemSelected(final MenuItem item) {
...
+                    peopleInviteFragment = PeopleInviteFragment.newInstance(dotComBlogId);
+                } else {
+                    AppLog.e(T.PEOPLE, "getDotComBlogId() returned null or empty string!");
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/people/PeopleManagementActivity.java]: Assuming that blog is not null here, could we please log some info about the current blog? Like the URL of it, or any other info you think it's relevant to debug this further.

Comment (hypest) [inline WordPress/src/main/java/org/wordpress/android/ui/people/PeopleManagementActivity.java]: I'll add extra info without checking for `blog` being null since there is code above that will crash if `blog` is null anyway. Thanks!

Having said that and as a note, I think guarding for null `blog` as well would be out of scope of this PR (a case like that would affect many more lines and places than just this one) so, I'm not planning to add such a guard here.

File: WordPress/src/main/java/org/wordpress/android/ui/people/PeopleManagementActivity.java (hunk 1 above)
Comment (hypest) [inline WordPress/src/main/java/org/wordpress/android/ui/people/PeopleManagementActivity.java]: Addressed with 2ca925d. Thanks!

**Comment by hypest** [comment]
Hey @daniloercoli , thanks for the review pass. Ready for another one!

**Comment by daniloercoli** [comment]
:shipit:
