### PR TITLE
remove media count from progress notification when media canceled

### LINKED ISSUE #6800: Async media: count should decrement on item deletion while editing
### Expected behavior
When editing on Aztec with media being uploaded, deleting an image that is being uploaded should decrement the count in the foreground progress notification accordingly

### Actual behavior
No changes to the totals are seen in the foreground notification (also not sure whether the upload is cancelled)

### Steps to reproduce the behavior
1. start a new draft
2. insert 4 media items
3. exit the editor, verify the progress notifications says 4 items are being uploaded
4. open the editor,
5. position the cursor to the right of an image being uploaded
6. hit backspace
7. observe the foreground notification did not count one less item as it should have, and the progress bar jumps to almost at 100%

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #6800 

(keeps the right count of media files being uploaded when media items are deleted from Aztec)

To test:
1. start a new draft on Aztec
2. insert some media in it. Preferrably, large files (such as videos) to let you perceive the changes. Please add at least 3 of them.
3. as upload start for all 3, you should see the progress notification appears, reading "3 of 3 media files remaining"
4. place the cursor to the right of one of the videos (because of some strange Aztec behavior, it's very difficult to place the cursor right after any media item except the last one - tracked in https://github.com/wordpress-mobile/AztecEditor-Android/issues/492).
5. press backspace to delete the media item
6. observe the progress notification (if you did this before any 3 items completed uploading), reads now "2 of 2 media files remaining"
7. repeat steps 4 and 5, and observe the progress notification now reads "1 media file remaining"
8. repeat steps 4 and 5, and observe the progress notification is now gone.

cc @nbradbury

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadNotifier.java [hunk 1]
```diff
@@ -150,6 +150,16 @@ void removePostInfoFromForegroundNotification(@NonNull PostModel post, @Nullable
     void removeMediaInfoFromForegroundNotification(@NonNull List<MediaModel> mediaList) {
         if (sNotificationData.totalMediaItems >= mediaList.size()) {
             sNotificationData.totalMediaItems -= mediaList.size();
+            // update Notification now
+            updateForegroundNotification(null);
+        }
+    }
+
+    void removeOneMediaItemInfoFromForegroundNotification() {
+        if (sNotificationData.totalMediaItems >= 1) {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadNotifier.java]: Should this be `>= 0` instead? Also, minor nit: there's an extra space before ` --`.

Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadNotifier.java]: no, if it's 0 we can't take 1 from it (that would make it a negative count). We could express it like `> 0` or `>=1` which are equivalent.
Removed the extra space in 10a869a

Comment (nbradbury) [reply WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadNotifier.java]: Apparently I took my brain out before I made that comment. Ignore me!

**Comment by nbradbury** [comment]
:shipit:
