### PR TITLE
Issue/4888 notifications allow horizontal nav always

### LINKED ISSUE #4888: Notifications: Unable to swipe between in-app notifs after opening from system notification
### Steps to reproduce the behavior
1) Spawn a WP.com notification, such as by leaving a comment on your site as another user
2) Open the Android notification, which should launch the app to the WP notification
3) Try to swipe to older notifications

### Expected behavior
To have the same swiping behavior as when opening the notification from inside the app

### Actual behavior
Nothing happens.  Backing out of the notification and re-opening it restores the swiping ability

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #4888 

(Note the functionality to limit horizontal navigation was there on purpose, so we got rid of it now after having users expect things to work differently)

To test:
1. being logged in to the app, have some other user make a comment on a blog post of a blog you're an admin of
2. you should receive a notification for such comment
3. tap on the comment, the detail view will be shown.
4. you should be able to swipe right to see more notifications in your list (and then left/right accordingly as you navigate along)

cc @nbradbury

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragment.java [hunk 1]
```diff
@@ -276,10 +275,7 @@ public static void openNoteForReply(Activity activity,
         if (!TextUtils.isEmpty(replyText)) {
             detailIntent.putExtra(NOTE_PREFILLED_REPLY_EXTRA, replyText);
         }
-        if (allowNavigateList) {
-            detailIntent.putExtra(NOTE_ALLOW_NAVIGATE_LIST_EXTRA, true);
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragment.java]: Now that `NOTE_ALLOW_NAVIGATE_LIST_EXTRA` is no longer used, it can be dropped entirely (it's still defined in this fragment).

Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragment.java]: oops! addressed in 3d5a625

**Comment by nbradbury** [comment]
Looks good! I'll wait for Travis then merge. :shipit:
