### PR TITLE
Fixes #4147 translated original size

### LINKED ISSUE #4147: Crash report 5.4: NumberFormatException in EditPostActivity.addMediaVisualEditor
Looks like a zealous i18n plugin that translated the "Original Size" we check [here](https://github.com/wordpress-mobile/WordPress-Android/blob/7e5af7926f6a7b91a8ffa938394494975e09a5ac/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L1563-L1563)

(Note that we check this value in other places)

```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2000, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:39798 flg=0x1 }} to activity {org.wordpress.android/org.wordpress.android.ui.posts.EditPostActivity}: java.lang.NumberFormatException: Invalid int: "Tamanho original"
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3720)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3763)
       at android.app.ActivityThread.-wrap16(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by java.lang.NumberFormatException: Invalid int: "Tamanho original"
       at java.lang.Integer.invalidInt(Integer.java:138)
       at java.lang.Integer.parse(Integer.java:410)
       at java.lang.Integer.parseInt(Integer.java:367)
       at java.lang.Integer.parseInt(Integer.java:334)
       at org.wordpress.android.ui.posts.EditPostActivity.addMediaVisualEditor(EditPostActivity.java:1565)
       at org.wordpress.android.ui.posts.EditPostActivity.addMedia(EditPostActivity.java:1530)
       at org.wordpress.android.ui.posts.EditPostActivity.fetchMedia(EditPostActivity.java:1442)
       at org.wordpress.android.ui.posts.EditPostActivity.onActivityResult(EditPostActivity.java:1622)
       at android.app.Activity.dispatchActivityResult(Activity.java:6442)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3716)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3763)
       at android.app.ActivityThread.-wrap16(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

### PR DESCRIPTION
**Pull request by maxme**
Fixes #4147 translated original size.

This also fixes a minor bug where the initial max width value in image settings was incorrectly set (fixed in c925f2d).

Note: commits dated pre "Jan 30, 2016" comes from the pull of the utils subtree.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/util/WPHtml.java [hunk 1]
```diff
@@ -449,22 +450,20 @@ public static String getContent(WPImageSpan imageSpan) {
...
             Blog currentBlog = WordPress.wpDB.instantiateBlogByLocalId(Integer.parseInt(localBlogID));
             // If it's not a gif and blog don't keep original size, there is a chance we need to resize
-            if (currentBlog != null && !mediaFile.getMimeType().equals("image/gif") &&
-                !currentBlog.getMaxImageWidth().equals("Original Size")) {
-                int maxImageWidth = Integer.parseInt(currentBlog.getMaxImageWidth());
-                // use the correct resize settings.
-                width = Math.min(width, maxImageWidth);
+            if (currentBlog != null && !mediaFile.getMimeType().equals("image/gif")
+                    && MediaUtils.getImageWidthSettingFromString(currentBlog.getMaxImageWidth()) != Integer.MAX_VALUE) {
+                width = MediaUtils.getMaximumImageWidth(width, currentBlog.getMaxImageWidth());
```
Comment (hypest) [inline WordPress/src/main/java/org/wordpress/android/util/WPHtml.java]: Just a note here, the older code was keeping the `0` for `width` while the newer code will have `width` become `1024`.

**Comment by hypest** [comment]
🚢 it!
