### PR TITLE
Issue 12317/keyboard above bottomsheet

### LINKED ISSUE #12317: WordPress Stories : Keyboard shown above bottom sheet
### Expected behavior
The bottom sheet should adjust once the keyboard is in use.

### Actual behavior
 Currently, the bottom sheet isn't above the keyboard due to the Story Composer being a full-screen activity. A custom solution will be created to solve this issue.
<kbd></kbd>

### Steps to reproduce the behavior
1. Create a new story. 
2. Click Publish. 
3. Try to type a title and you will see the keyboard being above the layout. 

Tested on Google Pixel 4 XL, Android 10, WPAndroid https://github.com/wordpress-mobile/WordPress-Android/pull/12307 ()

### PR DESCRIPTION
**Pull request by jd-alexander**
Fixes #12317

## Solution
The keyboard now sits below the bottom sheet. 

## Story Post

1. Create a new story post.
2. Click Publish. 
3. Now try to add a title and see that the bottom sheet readjusts to sit above the keyboard. 
4. Click to add tags as well. 
5. Ensure that when you focus on the `EditText` the tags list pushed up above the keyboard. 

Add Tags | Story Title 
--------|-------
 <kbd></kbd>    |<kbd></kbd>
      

## Concerns

1. Currently, the EditText doesn't show the blinking cursor when the keyboard is opened. I tried to figure this out but will need to investigate more.
2. If you set a title and then go to set tags when you return the story title is cleared. I will investigate to see what's causing this. 

## Reviewing 
Only 1 reviewer is needed but anyone can review. 

## Submitter Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
- [x] I have considered adding accessibility improvements for my changes.
- [x] If it's feasible, I have added unit tests.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/util/KeyboardResizeViewUtil.java [hunk 1]
```diff
@@ -0,0 +1,64 @@
+package org.wordpress.android.util;
+
+import android.app.Activity;
+import android.graphics.Rect;
+import android.view.View;
+import android.view.ViewTreeObserver;
+
+/**
```
Comment (jd-alexander) [inline WordPress/src/main/java/org/wordpress/android/util/KeyboardResizeViewUtil.java:8]: @mzorz so I got this class from Stack Overflow so I left this comment as is to note its source? That's the appropriate way to credit the author right?

Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/util/KeyboardResizeViewUtil.java:8]: Sounds good

**Comment by jd-alexander** [comment]
All the concerns on this PR are being addressed separately 🙏 https://github.com/wordpress-mobile/WordPress-Android/issues/12334
