### PR TITLE
Fix submit/publish button on post list items on self-hosted sites

### LINKED ISSUE #10354: Post list on self hosted site shows a "Submit" button instead of "Publish"
### Expected behavior

- On self hosted sites.
- On an edited published post on the publish tab in the Post list.
- Admin users (on other users who have publish permission) should see the "Publish" button.

### Actual behavior

- On self hosted sites.
- On an edited published post on the publish tab in the Post list.
- The app shows a "Submit" button.
- Also, tapping that "Submit" button updates the post, so the publish permission is confirmed.

Screenshot_1565253097

### Notes

I haven't checked, but I wonder if that comes from a site capability that is unset on self hosted sites.

### PR DESCRIPTION
**Pull request by malinajirka**
Fixes #10354 

Fixes issue where "submit" button was shown instead of "Publish" button on self-hosted sites.

To test:
1. Log-in as admin on a self-hosted site.
2. Edit a published post 
3. Press the back button (exit the editor)
4. Notice the item with "Local changes" label contains "Publish" button and not "Submit" as before

Update release notes:

- The changes are too minor.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtilsWrapper.kt [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+import javax.inject.Inject
+import javax.inject.Singleton
+
+/**
+ * Injectable wrapper around UploadUtils.
+ *
+ * UploadUtils interface is consisted of static methods, which makes the client code difficult to test/mock.
+ * Main purpose of this wrapper is to make testing easier.
+ */
+@Singleton
```
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtilsWrapper.kt]: Any upside of using `Singleton` instead of `Reusable` here?

Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtilsWrapper.kt]: Nope, copy-pasting mistake:). Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/10356/commits/de673a9a9f11fcde78b35229da9f76fefb9cdddc

Comment (maxme) [reply WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtilsWrapper.kt]: Ahah, you taught me about `Reusable` I was really wondering what was going on there :)
