### PR TITLE
fix #2293: remove leading double slash in URLs returned by wporg servers

### LINKED ISSUE #2293: Crash report 3.7-rc-2: invalid rsd or xmlrpc URL starting with "//example.com" (no scheme)
It happens rarely on site defining RSD link like `<link rel="EditURI" type="application/rsd+xml" title="RSD" href="//example.com/xmlrpc.php?rsd" />`

See the HTML source of blog.chewyland.com for instance.

### PR DESCRIPTION
**Pull request by maxme**
fix #2293: remove leading double slash in URLs returned by wporg servers

### CODE REVIEW

File: libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/UrlUtils.java [hunk 1]
```diff
@@ -52,11 +55,30 @@ public static String convertUrlToPunycodeIfNeeded(String url) {
         return url;
     }
 
+    /**
+     * Remove leading double slash, and inherit protocol scheme
+     */
+    public static String removeLeadingDoubleSlash(String url, String scheme) {
```
Comment (nbradbury) [inline libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/UrlUtils.java]: For consistency, how about using the same `boolean isHTTPS` parameter that's used by `addUrlSchemeIfNeeded` instead of passing the scheme as a string?

**Comment by nbradbury** [comment]
I think it would be helpful to future devs if there was a comment somewhere (perhaps above `addUrlSchemeIfNeeded`?) explaining why this PR was necessary.

File: libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/UrlUtils.java (hunk 1 above)
Comment (maxme) [inline libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/UrlUtils.java]: > For consistency, how about using the same boolean isHTTPS parameter that's used by addUrlSchemeIfNeeded instead of passing the scheme as a string?

In theory, double slash notation means "inherit from the current scheme used", so it's not limited to http or https. In reality, I'm pretty sure we'll never use it for anything else.

**Comment by nbradbury** [comment]
:shipit:
