### PR TITLE
Invite followers & viewers

### LINKED ISSUE #4458: People: Invite Followers/Viewers to a site
### Expected behavior

I expect to be able to invite followers or viewers to a site, as in Calypso (web).

Calypso invite for a public site (option to invite a follower):

screen shot 2016-08-01 at 1 58 31 pm

Calypso invite for a private site (option to invite a viewer):

screen shot 2016-08-01 at 1 58 45 pm

### Actual behavior

Currently you can only invite someone as an Administrator, Editor, Author, or Contributor. On a public site there is no option to invite someone as a follower, and on a private site there is no option to invite someone as a viewer.

### Steps to reproduce the behavior

Try the following steps for both a public site and a private site:

1. Go to the My Site screen for a site
2. Select "People"
3. Tap the + icon to send an invite
4. Tap on "Role" to select the role

### PR DESCRIPTION
**Pull request by oguzkocer**
Closes #4458. This PR introduces "Follower" and "Viewer" roles to invite feature. The default selected role for invite has been set to "Follower" for public sites and "Viewer" for private ones to match the Calypso behavior.

To test:
* Select a public site and go into people section
* Open the invite page with + sign and send a "Follower" invite.
* Repeat the process for private site and "Viewer" role

/cc @hypest & @astralbodies 

Anyone can review this!

### CODE REVIEW

**Comment by nbradbury** [comment]
@oguzkocer In the app I changed my site from public to private, and confirmed in the web app that it was successfully changed to private. I then tried to use the app to send a Viewer invite, but the Role dropdown didn't contain "Viewer." Killing and restarted the app corrected the problem.

File: WordPress/src/main/java/org/wordpress/android/ui/people/PeopleInviteFragment.java [hunk 1]
```diff
@@ -191,11 +193,13 @@ public void onFocusChange(View v, boolean hasFocus) {
             populateUsernameButtons(usernames);
         }
 
+        final boolean isPrivateSite = isPrivateSite();
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/people/PeopleInviteFragment.java]: This variable is unnecessary since the click listener is the only place it's used.

**Comment by nbradbury** [comment]
Are the strings in `invite_roles_public` and `invite_roles_private` only for display? I'm not certain, but it looks like these strings are also passed to the backend when sending an invitation, which would be a problem when translated into different languages.

File: WordPress/src/main/java/org/wordpress/android/ui/people/utils/PeopleUtils.java [hunk 2]
```diff
@@ -501,6 +503,11 @@ public void onErrorResponse(VolleyError volleyError) {
             }
         };
 
+        // This is an ugly hack but the remote accepts "follower" as parameter when you're inviting a viewer
+        if (role.toLowerCase().equals(ROLE_VIEWER)) {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/people/utils/PeopleUtils.java]: What happens if this hack is skipped? Does inviting as a "viewer" fail?

**Comment by oguzkocer** [comment]
> In the app I changed my site from public to private, and confirmed in the web app that it was successfully changed to private. I then tried to use the app to send a Viewer invite, but the Role dropdown didn't contain "Viewer." Killing and restarted the app corrected the problem.

@nbradbury this is a known issue #4459 and it's kind of an edge case we're not handling right now. With the new network layer we might re-visit it, but I don't think it's worth pursuing right now. You can find more details about it in the said issue #4459.

File: WordPress/src/main/java/org/wordpress/android/ui/people/utils/PeopleUtils.java (hunk 2 above)
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/people/utils/PeopleUtils.java]: Yeap, it fails if we use `viewer` as the parameter :(

**Comment by oguzkocer** [comment]
> Are the strings in `invite_roles_public` and `invite_roles_private` only for display? I'm not certain, but it looks like these strings are also passed to the backend when sending an invitation, which would be a problem when translated into different languages.

It looks like they are translatable, so it'd be a problem with the localization. It actually affects role change and invites for other roles as well. I'll checkin with @maxme and open a separate issue which will likely target `release` branch. Great catch!

**Comment by nbradbury** [comment]
> It looks like they are translatable, so it'd be a problem with the localization.

Can we simply change `translatable="true"` to `translatable="false"` in the xml?

**Comment by oguzkocer** [comment]
Well, if we do that it'd show up in English for every locale, I don't think that's what we want. We can maybe do it for now, until it's fixed. But even then we'd better do it for release branch.

**Comment by oguzkocer** [comment]
@nbradbury After chatting with Maxime I verified that `strings.xml` is the only string file that's being translated and the `translatable` flag doesn't make a difference here. I'll move all of these roles to `strings.xml` and fix the API parameter issue in a separate issue #4496.

**Comment by nbradbury** [comment]
:shipit:
