### PR TITLE
Issue/13812 fix site notifications on following tab

### LINKED ISSUE #13812: Reader: Enable/Disable site notifications action doesn't work
### Expected behavior
When I click on "Turn on/off site notifications" I'd expect the site notifications get enabled/disabled.

### Actual behavior
When I click on "Turn on/off site notifications" nothing happens.

```2021-01-19 09:31:24.885 8257-8509/org.wordpress.android.beta E/SQLiteDatabase: Error inserting SHOULD_EMAIL_COMMENTS=false BLOG_NAME=Writing Rhymes SUBSCRIPTION_ID=617136108 FEED_ID=83396915 URL=http://writingrhymes.wordpress.com SHOULD_NOTIFY_POSTS=false BLOG_ID=107850799 EMAIL_POSTS_FREQUENCY=instantly SHOULD_EMAIL_POSTS=true
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: SubscriptionModel.FEED_ID, SubscriptionModel.URL (code 2067 SQLITE_CONSTRAINT_UNIQUE)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:938)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1701)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1570)
        at com.yarolegovich.wellsql.InsertQuery.execute(InsertQuery.java:61)
        at org.wordpress.android.fluxc.persistence.AccountSqlUtils.updateSubscriptions(AccountSqlUtils.java:147)
        at org.wordpress.android.fluxc.store.AccountStore.updateSubscriptions(AccountStore.java:1307)
        at org.wordpress.android.fluxc.store.AccountStore.onAccountAction(AccountStore.java:912)
        at org.wordpress.android.fluxc.store.AccountStore.onAction(AccountStore.java:818)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501)
        at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
```

### Steps to reproduce the behavior
1. Open Reader
2. Open Following tab
3. Click on the more menu icon on one of the posts
4. Click on "Turn on site notifications"
5. Notice the error in the logcat, also notice the notifications don't get enabled

##### Tested on [device], Android [version], WPAndroid [version]
Emulator API 30

### PR DESCRIPTION
**Pull request by ashiagr**
Fixes #13812

This PR checks if the blog is an external feed [here](https://github.com/wordpress-mobile/WordPress-Android/blob/b7a62482dd80bc50c227d52be059c65b552999b3/WordPress/src/main/java/org/wordpress/android/datasets/ReaderBlogTableWrapper.kt#L15-L29), when site follow status is checked in the db. This resolves an occasional follow blog issue occurring when a blog is followed by url and feed id gets generated for it. 

It also fixes `SQLiteConstraintException: UNIQUE constraint failed` exception seen in the logs when site notifications are subscribed.

Details below:

To test:

1. Follow a simple WP.com site using the site url on Reader -> gear icon -> Manage Topics & Sites

2. Notice that the user's followed sites response does not contain `feed_id`. Details are updated in `tbl_blog_info` with `feed_id` = 0.
    Eg: [read-following-mine_meta=site%2Cfeed.txt](https://github.com/wordpress-mobile/WordPress-Android/files/5854302/read-following-mine_meta.site.2Cfeed.txt)

3. Return from "Manage Topics & Sites" to the following tab. Notice that followed site posts contains feed id and are inserted into `tbl_posts` with `feed_id` set.
    Eg: [read-following_number=20&meta=site,likes.txt](https://github.com/wordpress-mobile/WordPress-Android/files/5854296/read-following_number.20.meta.site.likes.txt)

4. Toggle follow site menu few times. Also toggle follow button on the post details screen.

5. Notice that site is followed/ unfollowed properly.
    
    With the external feed check in the `ReaderBlogTableWrapper` class, site is now retrieved from the `tbl_blog_info` using the `blog_id` instead of the `feed_id`. Earlier it wasn't found in the `tbl_blog_info` since `feed_id` was not set at step 2 and returned wrong followed status, sending incorrect follow request. 

https://user-images.githubusercontent.com/1405144/105350203-cd634800-5c10-11eb-80b7-2f9bf546e89a.mp4 

https://user-images.githubusercontent.com/1405144/105350250-deac5480-5c10-11eb-984f-2dbf6ae226f3.mp4

Also `AlreadyRunning` state is added when request to follow blog is running and `updateSubscription` method in FluxC is synchronised. This fixes `SQLiteConstraintException: UNIQUE constraint failed:` exception in the logs. Issue existed even before reader refactoring, occurred on trying to follow/ unfollow blog/ site in quick succession, resulting in desynchronisation while updating user's subscriptions [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/a097f94c384cc146c9a187144ea73eb1ab64c893/fluxc/src/main/java/org/wordpress/android/fluxc/persistence/AccountSqlUtils.java#L145-L148).

Merge instructions:
- ~~Review, merge https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1851 and create a FluxC tag~~ Done
- ~~Replace FluxC commit hash with tag on develop~~ Done
- Remove 'Not Ready for Merge' label
- Merge this PR

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/reader/usecases/ReaderSiteFollowUseCase.kt [hunk 1]
```diff
@@ -25,36 +26,37 @@ class ReaderSiteFollowUseCase @Inject constructor(
     private val readerBlogTableWrapper: ReaderBlogTableWrapper,
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/usecases/ReaderSiteFollowUseCase.kt:26]: ❓ I'm not sure, but should we add some tests since we changed this class?

**Review by malinajirka — APPROVED** [review]
Thanks @ashiagr! LGTM ;)

File: WordPress/src/main/java/org/wordpress/android/ui/reader/usecases/ReaderSiteFollowUseCase.kt (hunk 1 above)
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/reader/usecases/ReaderSiteFollowUseCase.kt:26]: As discussed, we'll add tests when we wrap up Jetpack Section project.
