### PR TITLE
Replace/Fix media library placeholders

### LINKED ISSUE #6292: Media Library error placeholder looks bad
I was on a poor connection on the device, and ended up with having a media library filled with "horrible" icon placeholder. (As usual I'm on Android 5.0 ;) )

device-2017-07-13-141845
device-2017-07-13-141855
device-2017-07-13-141907

cc @nbradbury

### PR DESCRIPTION
**Pull request by daniloercoli**
Fixes #6292 

Hey @nbradbury - I've started woking on fixing #6292, and replaced `FadeInNetworkImageView` with `WPNetworkImageView`. Is there any reason to use `FadeInNetworkImageView` instead?

At the moment I replaced the error placeholders with the default background drawable. I didn't find an easy way to reuse the already available `ic_gridicons_*` files without modifying them. The grid looks odd in case of errors, since there is no border, and the padding is different.

### CODE REVIEW

**Comment by nbradbury** [comment]
> Is there any reason to use FadeInNetworkImageView instead?

I can't think of any reasons.

**Comment by nbradbury** [comment]
> At the moment I replaced the error placeholders with the default background drawable.

That's probably fine. It looks better than the previous default background.

**Comment by daniloercoli** [comment]
This is ready for review then. I opened another issue here https://github.com/wordpress-mobile/WordPress-Android/issues/6296 that we can work later.

File: WordPress/src/main/java/org/wordpress/android/ui/media/WordPressMediaUtils.java [hunk 1]
```diff
@@ -260,6 +261,29 @@ public static void loadNetworkImage(String imageUrl, NetworkImageView imageView,
         }
     }
 
+    public static void loadNetworkImage(String imageUrl, WPNetworkImageView imageView) {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/media/WordPressMediaUtils.java]: This is almost a copy of the above `loadNetworkImage` except that it's written for a WPNetworkImageView, which seems like a maintenance problem down the road. Is there not a way to use a single routine?

File: WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridAdapter.java [hunk 2]
```diff
@@ -173,12 +173,12 @@ public void onBindViewHolder(GridViewHolder holder, int position) {
             if (isLocalFile) {
                 loadLocalImage(media.getFilePath(), holder.imageView);
             } else {
-                WordPressMediaUtils.loadNetworkImage(getBestImageUrl(media), holder.imageView, mImageLoader);
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridAdapter.java]: Now that the image loader isn't being passed, `mImageLoader` is unused and can be dropped.

File: WordPress/src/main/java/org/wordpress/android/ui/media/WordPressMediaUtils.java (hunk 1 above)
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/media/WordPressMediaUtils.java]: Yes, the other one will be gone soon (I hope) once https://github.com/wordpress-mobile/WordPress-Android/issues/6296 is done.

File: WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridAdapter.java (hunk 2 above)
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridAdapter.java]: Same as above, I think `mImageLoader` should be re-added once that PR is done. Since the new 
Anyway dropped it for now!

Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridAdapter.java]: Ready for another round of testing.

**Comment by nbradbury** [comment]
Looks good! :shipit:
