### PR TITLE
Fix errors not shown in some locales on the people invite screen

### LINKED ISSUE #7230: Invite people screen - 'user not found' error is not shown for some locales
### Expected behavior
When a user enters unknown username, the "user not found" error is shown.

### Actual behavior
When a user enters unknown username, the "user not found" error is NOT shown for some locales.

### Steps to reproduce the behavior
1. Set default locale to Spanish or Hebrew.
2. Go to Invite people screen and enter some random string such as "jhfdakfhakh35hkh3" into the username field.
3. Error is not shown.

##### Tested on [device], Android [version]
Emulator - SDK 18, 27

### PR DESCRIPTION
**Pull request by malinajirka**
Fixes #7230

To test:
1. Set default locale to Spanish or Hebrew.
2. Go to Invite people screen and enter some random string such as "jhfdakfhakh35hkh3" into the username field.
3. Error "user not found" is shown.

Note: Json attribute "message" received from the API is already translated. The switch statement doesn't work as expected, since it expects that the json attribute "message" is in English. 

This quickfix will always fallback to "User not found" message. We may consider separating "invalid_input - user not found" and "invalid_input - invalid email" into two different "codes" (eg. invalid_input_unknown_user" and "invalid_input_invalid_email").

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/people/utils/PeopleUtils.java [hunk 1]
```diff
@@ -361,14 +361,14 @@ public void onResponse(JSONObject jsonObject) {
                             switch (userError.optString("code")) {
                                 case "invalid_input":
                                     switch (userError.optString("message")) {
-                                        case "User not found":
-                                            callback.onUsernameValidation(username, ValidationResult.USER_NOT_FOUND);
-                                            continue;
                                         case "Invalid email":
                                             callback.onUsernameValidation(username, ValidationResult.INVALID_EMAIL);
                                             continue;
+                                        case "User not found":
```
Comment (hypest) [inline WordPress/src/main/java/org/wordpress/android/ui/people/utils/PeopleUtils.java]: WDYT about adding a small comment here like "fall through to the default case" to make it explicit?

**Comment by malinajirka** [comment]
Thank you @hypest for the review! I've added the comment. It's definitely a good idea to make it explicit so no-one has to wonder whether I did it on purpose or by mistake.

**Comment by hypest** [comment]
🛳️it!
