### PR TITLE
Notifications: Proper retrieval of note comment actions object

### LINKED ISSUE #2322: Notifications: Correct comment notification 'action' block retrieval
The app is incorrectly looking for the comment actions in the last item in the array. It should instead look for a comment type block within the body, and grab the actions from that:

https://github.com/wordpress-mobile/WordPress-Android/blob/b52152bd09be90550a6a61b9d0c78d8d0e7085f2/WordPress/src/main/java/org/wordpress/android/models/Note.java#L234-L240

### PR DESCRIPTION
**Pull request by roundhill**
Get the note comment actions by looping through the note body. Match is found when the note meta comment id equals the meta id of the body item.

Note to PR reviewer: To test that this works properly, look for actions on a comment notification ('Like', 'Approve', etc)

Fixes #2322

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/models/Note.java [hunk 1]
```diff
@@ -231,9 +231,23 @@ private String getNoticonCharacter() {
...
+                    JSONObject bodyItem = bodyArray.getJSONObject(i);
+                    if (bodyItem.has("type") && bodyItem.optString("type").equals("comment")
+                            && commentId == JSONUtil.queryJSON(bodyItem, "meta.ids.comment", 0)) {
+                        mActions = JSONUtil.queryJSON(bodyItem, "actions", new JSONObject());
+                        break;
+                    }
+                } catch (JSONException e) {
+                    break;
+                }
+            }
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/models/Note.java]: I'm not sure if this would make any real performance difference, but would it make sense to detect when `mActions` is null after the for loop and if so set it to any empty `JSONObject`? That way this loop wouldn't be performed again when it isn't necessary.

Comment (roundhill) [inline WordPress/src/main/java/org/wordpress/android/models/Note.java]: :+1:

Comment (roundhill) [inline WordPress/src/main/java/org/wordpress/android/models/Note.java]: Added in b041812

**Comment by nbradbury** [comment]
Looks good, just waiting for Travis so I can merge :shipit:
