### PR TITLE
Media Sharing - Latitude Column Fix

### LINKED ISSUE #10843: Crash when sharing a video with the app
The app crashes when you try to share a video with the app on API 29. 

Steps to reproduce: 
- Share a video with the app
- Select the "Add to a new post" option
- The editor crashes

Stacktrace: 
```
java.lang.IllegalArgumentException: Invalid column latitude
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:944)
        at android.content.ContentResolver.query(ContentResolver.java:880)
        at android.content.ContentResolver.query(ContentResolver.java:836)
        at org.wordpress.android.util.MediaUtils.getFilenameFromURI(MediaUtils.java:173)
        at org.wordpress.android.util.MediaUtils.downloadExternalMedia(MediaUtils.java:214)
        at org.wordpress.android.util.MediaUtilsWrapper.copyFileToAppStorage(MediaUtilsWrapper.kt:39)
        at org.wordpress.android.ui.posts.editor.media.CopyMediaToAppStorageUseCase.copyToAppStorage(CopyMediaToAppStorageUseCase.kt:48)
        at org.wordpress.android.ui.posts.editor.media.CopyMediaToAppStorageUseCase.access$copyToAppStorage(CopyMediaToAppStorageUseCase.kt:17)
        at org.wordpress.android.ui.posts.editor.media.CopyMediaToAppStorageUseCase$copyFilesToAppStorageIfNecessary$2.invokeSuspend(CopyMediaToAppStorageUseCase.kt:31)
        at org.wordpress.android.ui.posts.editor.media.CopyMediaToAppStorageUseCase$copyFilesToAppStorageIfNecessary$2.invoke(Unknown Source:10)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:155)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
        at org.wordpress.android.ui.posts.editor.media.CopyMediaToAppStorageUseCase.copyFilesToAppStorageIfNecessary(CopyMediaToAppStorageUseCase.kt:27)
        at org.wordpress.android.ui.posts.editor.media.AddLocalMediaToPostUseCase.addNewMediaToEditorAsync(AddLocalMediaToPostUseCase.kt:48)
        at org.wordpress.android.ui.posts.editor.media.EditorMedia$addNewMediaItemsToEditorAsync$1.invokeSuspend(EditorMedia.kt:116)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

### PR DESCRIPTION
**Pull request by jd-alexander**
Fixes #10843

This crash is occurring because, in API 29, [they depreciated the latitude column](https://developer.android.com/reference/android/provider/MediaStore.Images.ImageColumns#LATITUDE). 
So the query is currently calling for all columns including the depreciated column even though it isn't used.

## Solution

To specify the column that is needed by the query so that the depreciated columns are no longer accessed. 

## Testing
1. Share a video with the WordPress app. 
2. Add it to a new post. 
3. Thumbnail should appear and there should be no crash. 

**Note:** I haven't reproduced the fix as yet. I am resolving an API error so this hasn't been tested.

## Reviewing 
Only 1 reviewer is needed but anyone can review. 

## Submitter Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
- [x] If it's feasible, I have added unit tests.

### CODE REVIEW

**Comment by jkmassel** [comment]
We're freezing `14.2` today, so this PR is being bumped to `14.3`. If you'd like it to ship with `14.2`, please merge it into `release/14.2` and ping me – I'll be happy to cut a new beta release.

**Comment by oguzkocer** [comment]
Hey @jd-alexander! It looks like this PR hasn't been reviewed yet and there hasn't been an update on it for some time. Do you mind following up on it when you get a chance?

**Comment by jd-alexander** [comment]
> Hey @jd-alexander! It looks like this PR hasn't been reviewed yet and there hasn't been an update on it for some time. Do you mind following up on it when you get a chance?

Hey Oguz! Thanks for the ping. It's going to get looked into in groundskeeping as noted here https://github.com/wordpress-mobile/WordPress-Android/issues/10843#issuecomment-587929307

I didn't figure out how to reproduce it as yet so during the review that will happen. Is it being marked as a draft sufficient enough? Let me know. Thanks!

**Comment by oguzkocer** [comment]
Thanks for the update @jd-alexander! If @khaykov can't get to it, please feel free to ping me for a review.

**Comment by khaykov** [comment]
Hey @jd-alexander 👋 Looks like there are some changes not related to the issue mixed in?

File: libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/MediaUtils.java [hunk 1]
```diff
@@ -170,7 +170,8 @@ public static boolean isInMediaStore(Uri mediaUri) {
     }
 
     public static @Nullable String getFilenameFromURI(Context context, Uri uri) {
-        Cursor cursor = context.getContentResolver().query(uri, null, null, null, null);
+        Cursor cursor = context.getContentResolver().query(uri, new String[]{OpenableColumns.DISPLAY_NAME},
+                null, null, null);
```
Comment (jd-alexander) [inline libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/MediaUtils.java]: This the only line that matters for the solution @khaykov

**Comment by jd-alexander** [comment]
> Hey @jd-alexander 👋 Looks like there are some changes not related to the issue mixed in?

yes, this happened because the subtree needed updating. 

What's the better way to go about this without including those other changes? I would have to take another look at it. I don't remember exactly why it happened since I haven't worked with subtrees alot.

File: libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/MediaUtils.java (hunk 1 above)
Comment (jd-alexander) [reply libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/MediaUtils.java]: This crash is occurring because, in API 29, [they depreciated the latitude column](https://developer.android.com/reference/android/provider/MediaStore.Images.ImageColumns#LATITUDE). 
So the query is currently calling for all columns including the depreciated column even though it isn't used.

**Comment by khaykov** [comment]
@jd-alexander Subtrees is the bane of my existence. Yes, looks like there are some changes in utils repo that did not made it into wpandroid yet. Usually, it's another way around :) It's no biggie, and we can merge this one with them.

I was not able to replicate the issue but googling revealed that it's pretty common in various photo-pickers, and your fix makes sense. Could you add some description to the PR so we can proceed?

**Comment by jd-alexander** [comment]
> @jd-alexander Subtrees is the bane of my existence. Yes, looks like there are some changes in utils repo that did not made it into wpandroid yet. Usually, it's another way around :) It's no biggie, and we can merge this one with them.

Okay awesome!

> I was not able to replicate the issue but googling revealed that it's pretty common in various photo-pickers, and your fix makes sense. Could you add some description to the PR so we can proceed?

Great! Just did.
