### PR TITLE
[Blogging Prompts Enhancements] Fix prompt setting reset after reminder is changed

### LINKED ISSUE #17893: [Blogging Prompts] Changing Reminders reset "show prompts" setting
## Expected behavior
The "show prompts" setting stays the same after updating Blogging Reminder settings.

## Actual behavior
The "show prompts" setting is reset to `true` after updating Blogging Reminder settings.

## Steps to reproduce
See video:

https://user-images.githubusercontent.com/5091503/217109254-f61628fa-073a-496f-a6cc-c22894cba163.mp4

### PR DESCRIPTION
**Pull request by thomashorta**
Fixes #17893

Prompts and Reminders settings share the same FluxC model to be persisted, so we need to propagate the whole model value to the Reminders UI model to make sure it will be persisted properly and not reset.

https://user-images.githubusercontent.com/5091503/217286930-b54312bf-7bc2-46ac-b283-e2b0adc9e994.mp4

This also fixes the issue of not properly setting the initial value for the `Show prompts` setting, see this PR's comments for more details.

To test:
1. Select a blogging site
2. Go to `My Site` -> `Menu`
3. Tap `Site Settings`
4. Turn off the `Show prompts` option
5. Set up `Reminders` 
6. **Verify** `Show prompts` keeps its value
7. Clear `Reminders`
8. **Verify** `Show prompts` keeps its value
9. Turn on the `Show prompts` option
5. Set up `Reminders` 
6. **Verify** `Show prompts` keeps its value
7. Clear `Reminders`
8. **Verify** `Show prompts` keeps its value

## Regression Notes
1. Potential unintended areas of impact
N/A

10. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

11. What automated tests I added (or what prevented me from doing so)
Updated existing tests and added new test to avoid regression on this bug.

PR submission checklist:

- [X] I have completed the Regression Notes.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersViewModel.kt [hunk 1]
```diff
@@ -81,7 +81,7 @@ class BloggingRemindersViewModel @Inject constructor(
                 Screen.SELECTION -> daySelectionBuilder.buildPrimaryButton(
                     bloggingRemindersModel,
                     isFirstTimeFlow == true,
-                    this::showEpilogue
+                    this::onSelectionButtonClick
```
Comment (RenanLukas) [inline WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersViewModel.kt:84]: 💯

**Comment by RenanLukas** [comment]
Thanks for the PR @thomashorta , it works as expected and code LGTM.

The only thing I wanted to confirm before approving is that when I first installed this version the `Show prompts` switch was off even though the prompts card is being shown at "My Site". Is this expected?

After switching `Show prompts` on and off again, the card disappeared.

**Comment by thomashorta** [comment]
> The only thing I wanted to confirm before approving is that when I first installed this version the `Show prompts` switch was off even though the prompts card is being shown at "My Site". Is this expected?

Thanks for catching that. It seems it was not introduced in this PR but I am fixing it here as its an extra line change and is in the somewhat same scope as the original changes.

The issue was using `setDefaultValue` instead of `setChecked` when getting the initial value for the `mBloggingPref` setting. It seems `setDefaultValue` only works if it's called before the setting is attached to the settings list.

**Review by RenanLukas — APPROVED** [review]
Thanks for the changes, it's working as expected. LGTM :shipit:
