### PR TITLE
Post Settings: Publish Date

### LINKED ISSUE #5989: Drafts shouldn't have a date if not specified by the user
Whenever a draft is created, we add a date to it which means when it's published, the date it's published actually shows when the draft is created. Here are the steps to reproduce it:

1. Create a draft and go back to the post list (it’ll become a remote draft if you have network)
2. Wait for a minute and publish the post. Now you have a published post 1 min ago

### PR DESCRIPTION
**Pull request by oguzkocer**
Fixes #5989, #5927, #2891, #5990. This PR updates the publish date flow completely. We have been discussing this for a while now and trying to come up with a good solution. I think this is the best solution available to us.

A bit about the problem:

A user can do several things with publish date. They can set a past date, set it to immediately, schedule it to future, update it on remote and so on. However, the only field available to us in the API is `date` which doesn't tell us enough. It's added when a draft is first created, updated automatically when it's published and can be updated by the user in several ways. As far as we can tell, there is no perfect solution in the current structure.

Our solution:
1. Always use & show the `date` property in "Publish Date" and let the user update it to whenever they want (including past dates)
2. If the post is a draft, let the user set a future date. If a future date is set, treat it like the option 1.
3. Don't let the user set a past date for a draft. Theoretically they can do so if they select the current date and a prior time, but this doesn't matter too much. The only reason we do this is to avoid confusing the user due to 4 & 5.
4. If the post is a draft and if the `date` field is now or in the past, show "Immediately" instead
5. If 4 is true, just before a post is published, update the date field to current time which should be consistent with Calypso and wp-admin.

To test:
* Make sure to try each case for both drafts and published posts (or any other status like private, pending review etc)
* Since the solution section is pretty detailed and test-like, please make sure the follow the flows described and make sure to add a comment if a certain scenario is missed.
* This PR should, hopefully, be closing multiple issues. We should check each one before merging this PR. I'll do that as well.

cc @tonyr59h @maxme

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java [hunk 1]
```diff
@@ -597,59 +559,64 @@ private void showPostDateSelectionDialog() {
...
-        datePickerDialog.setButton(DialogInterface.BUTTON_NEGATIVE, getResources().getText(android.R.string.cancel),
+        datePickerDialog.setButton(DialogInterface.BUTTON_NEGATIVE, resources.getString(android.R.string.cancel),
                 new DialogInterface.OnClickListener() {
                     public void onClick(DialogInterface dialog, int id) {
                     }
                 });
+        if (PostUtils.shouldPublishImmediatelyOptionBeAvailable(mPost)) {
+            // We shouldn't let the user pick a past date since we'll just override it to Immediately if they do
+            // We can't set the min date to now, so we need to subtract some amount of time
+            datePickerDialog.getDatePicker().setMinDate(System.currentTimeMillis() - 1000);
```
Comment (tonyr59h) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java]: Thanks for the comment, this would have been very confusing without it 😄

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java [hunk 2]
```diff
@@ -597,59 +559,64 @@ private void showPostDateSelectionDialog() {
...
             return;
         }
-        final DatePickerDialog datePickerDialog = new DatePickerDialog(getActivity(), null, mYear, mMonth, mDay);
+
+        Calendar calendar = getCurrentPublishDateAsCalendar();
+        int year = calendar.get(Calendar.YEAR);
+        int month = calendar.get(Calendar.MONTH);
+        int day = calendar.get(Calendar.DAY_OF_MONTH);
+
+        Resources resources = getResources();
```
Comment (tonyr59h) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java]: 👍

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java [hunk 3]
```diff
@@ -597,59 +559,64 @@ private void showPostDateSelectionDialog() {
...
-                            mCustomPublishDate = DateTimeUtils.iso8601FromDate(javaDate);
-                            mPublishDateTextView.setText(formattedDate);
-                            mIsCustomPublishDate = true;
-
-                            updateSaveButton();
-                        } catch (RuntimeException e) {
-                            AppLog.e(T.POSTS, e);
-                        }
+                        Calendar selectedCalendar = Calendar.getInstance();
+                        selectedCalendar.set(selectedYear, selectedMonth, selectedDay, selectedHour, selectedMinute);
```
Comment (tonyr59h) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java]: The code for the entire date selection process is much cleaner now 👍

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java [hunk 4]
```diff
@@ -283,4 +284,23 @@ public static int indexOfPostInList(final PostModel post, final List<PostModel>
         }
         return list;
     }
+
+    static boolean shouldPublishImmediately(PostModel postModel) {
+        boolean optionAvailable = shouldPublishImmediatelyOptionBeAvailable(postModel);
+        Date pubDate = DateTimeUtils.dateFromIso8601(postModel.getDateCreated());
+        Date now = new Date();
+        // For drafts with publish dates in the past, we should publish immediately
+        return optionAvailable && !pubDate.after(now);
```
Comment (tonyr59h) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java]: We could avoid creating the two `Date` objects by returning `false` immediately if `!shouldPublishImmediatelyOptionBeAvailable(postModel)`

**Comment by tonyr59h** [comment]
I get a NPE when clicking the `Publish` setting on a local draft:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object reference
         at java.util.Calendar.setTime(Calendar.java:1197)
         at org.wordpress.android.ui.posts.EditPostSettingsFragment.getCurrentPublishDateAsCalendar(EditPostSettingsFragment.java:910)
         at org.wordpress.android.ui.posts.EditPostSettingsFragment.showPostDateSelectionDialog(EditPostSettingsFragment.java:563)
         at org.wordpress.android.ui.posts.EditPostSettingsFragment.access$1200(EditPostSettingsFragment.java:96)
         at org.wordpress.android.ui.posts.EditPostSettingsFragment$12.onClick(EditPostSettingsFragment.java:341)

**Comment by tonyr59h** [comment]
This one is good to go, very nice work 🎉 

We'll keep the issues open until their fixes are verified in a future PR. :shipit:
