### PR TITLE
issue/4884-gravatar-error-toast

### LINKED ISSUE #4884: Me: Gravatar error when account has no Gravatar image set
### Expected behavior

I expect to be able to use an account without a Gravatar if I choose not to upload one.

### Actual behavior

Using an account with no Gravatar, every time I launch the app (after closing it, not just putting it in the background) I get the error message "Error reloading your Gravatar."

After uploading a Gravatar, the Gravatar appears on the Me screen and the error stops appearing.

### Steps to reproduce the behavior

1. Create a new account in the app, or log in to an account with no Gravatar
2. On the Me screen, the error "Error reloading your Gravatar" appears
3. Swipe the app closed
4. Relaunch the app, and the error reappears

##### Tested on Nexus 9, Android 7.0, WPAndroid alpha-30

Reported in 147872-h

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #4884 

To test: remove the image from your Gravatar account. Prior to this fix you'd see a toast saying "Error reloading your gravatar" every time you ran the app. The fix was to simply remove this message, since it's not really necessary.

cc: @hypest Mind reviewing this one, since this feature was your baby? I'm pretty sure we don't need that toast but wanted to run it by you.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.java [hunk 1]
```diff
@@ -660,10 +660,6 @@ public GravatarLoadFinished(boolean success) {
 
     public void onEventMainThread(GravatarLoadFinished event) {
         showGravatarProgressBar(false);
-
-        if (!event.success) {
```
Comment (hypest) [inline WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.java]: Hey @nbradbury , instead of removing the toast, may I suggest guarding it with a `mIsUpdatingGravatar` check as well? Originally, the toast was added to inform the user of errors on reloading the Gravatar after updating it so, it should suffice to have it only in that case.

As a headsup, and if you choose to add the check, notice that `mIsUpdatingGravatar` is modified by `showGravatarProgressBar()` so you might want to re-arrange the code lines order here. Thanks!

**Comment by nbradbury** [comment]
@hypest I made the changes you suggested, so ready for round two.

**Comment by hypest** [comment]
LGTM!
