### PR TITLE
Fix IllegalArgumentException in Glide ImageManager

### LINKED ISSUE #8591: Crash: IllegalArgumentException in Glide ImageManager
```
Fatal Exception: java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
       at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:312)
       at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:131)
       at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:115)
       at com.bumptech.glide.Glide.with(Glide.java:697)
       at org.wordpress.android.modules.GlideApp.with(GlideApp.java:88)
       at org.wordpress.android.util.image.ImageManager.load(ImageManager.kt:44)
       at org.wordpress.android.ui.reader.views.ReaderTagHeaderView.setTagHeaderInfo(ReaderTagHeaderView.java:87)
       at org.wordpress.android.ui.reader.views.ReaderTagHeaderView.access$300(ReaderTagHeaderView.java:31)
       at org.wordpress.android.ui.reader.views.ReaderTagHeaderView$2.onResponse(ReaderTagHeaderView.java:153)
       at org.wordpress.android.ui.reader.views.ReaderTagHeaderView$2.onResponse(ReaderTagHeaderView.java:121)
       at com.wordpress.rest.RestRequest.deliverResponse(RestRequest.java:76)
       at com.wordpress.rest.RestRequest.deliverResponse(RestRequest.java:19)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:7000)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
``` 

5b632e5a6007d59fcd957655-fabric

### PR DESCRIPTION
**Pull request by daniloercoli**
This PR tries to fix #8591 by making sure the passed target view of a Glide request has still a valid context. 

To test this:
- Open the app
- Go to the Reader
- Select a tag in the reader
- Throttle the following network request https://github.com/wordpress-mobile/WordPress-Android/blob/59f821944ae40035519b20444c1905303a82cfeb/WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderTagHeaderView.java#L121
- When the connection to the REST API starts (and before it ends) go back to another section of the app
- Try to make sure the Reader Fragment or activity is destroyed
- Wait until the call to the REST API ends, and check in `ImageManager.kt` that the connection to request the picture is not made due to activity already destroyed. 
The connection is enqueued here: https://github.com/wordpress-mobile/WordPress-Android/blob/59f821944ae40035519b20444c1905303a82cfeb/WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderTagHeaderView.java#L87

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by daniloercoli** [comment]
Btw, I should have added that the original problem happens when `WPMainActivity` is not there anymore. The context returned by `ReaderTagHeaderView.mImageView.context` is an instance of `WPMainActivity`, set during the init of `ReaderTagHeaderView`.

I guess this could happen if the user does the logout immediately after the REST API request is made.
I was not able to reproduce the problem, but probably having those checks in the ImageManager doesn't hurt.

**Comment by mzorz** [comment]
> I should have added that the original problem happens when WPMainActivity is not there anymore
[...]
> I was not able to reproduce the problem

I was wondering, did you use the developer options to make all Activities killed when they are dismissed? Maybe that's a way to reproduce.

**Comment by daniloercoli** [comment]
> I was wondering, did you use the developer options to make all Activities killed when they are dismissed? Maybe that's a way to reproduce.

Yep, tried that already, but the activity passed as context to `ReaderTagHeaderView.mImageView.context` is an instance of `WPMainActivity`... that's is always there when the user is logged to the app. So, even if you enable the Kill activities switch in developer settings, there is no way to get a destroyed activity with a classic user-flow.

That's why I mentioned in a comment that the problem can only happen when `WPMainActivity` was there  when the Reader request enqueued, but not available anymore when the network request finished (logout?). I guess there are other ways to get it empty after a reader request is made, but don't have a clear idea.

File: WordPress/src/main/java/org/wordpress/android/util/image/ImageManager.kt [hunk 1]
```diff
@@ -33,6 +36,25 @@ class ImageManager @Inject constructor(val placeholderManager: ImagePlaceholderM
...
     }
 
+    /**
+     * Return true if this [Context] is available.
+     * Availability is defined as the following:
+     * + [Context] is not null
+     * + [Context] is not destroyed (tested with [FragmentActivity.isDestroyed] or [Activity.isDestroyed])
+     */
+    private fun Context?.isAvailable(): Boolean {
+        if (this == null) {
```
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/util/image/ImageManager.kt]: is this check necessary? if `this == null` then this code shouldn’t be running IIUC

Comment (daniloercoli) [reply WordPress/src/main/java/org/wordpress/android/util/image/ImageManager.kt]: It's not required for this particular crash, #8591, but this new method is going to be used on almost all Glide calls, so that check does't hurt.

Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/util/image/ImageManager.kt]: I meant - does that expression make sense?

Comment (daniloercoli) [reply WordPress/src/main/java/org/wordpress/android/util/image/ImageManager.kt]: It should be ok, we've defined an extension on a nullable receiver type, and can check for null inside the body. https://kotlinlang.org/docs/reference/extensions.html#nullable-receiver

Btw, i'm not expert in Kotlin.
