### PR TITLE
Fix #5179: fix video upload in the editor

### LINKED ISSUE #5179: Fluxc - Media Integration - Video upload UI is broken in the editor
Video capture flow in both browser and editor needs to be verified

### PR DESCRIPTION
**Pull request by maxme**
Fix #5179: fix video upload in the editor

Set the correct Thumbnail (or make sure the editor set its own placeholder). Also make sure the `fromMediaModel` and `fromMediaFile` utils convert the required fields for video handling.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/util/FluxCUtils.java [hunk 1]
```diff
@@ -54,6 +55,8 @@ public static MediaFile fromMediaModel(MediaModel media) {
         mediaFile.setDescription(media.getDescription());
         mediaFile.setCaption(media.getCaption());
         mediaFile.setUploadState(media.getUploadState());
+        mediaFile.setVideo(media.getMimeType().startsWith("video"));
+        mediaFile.setVideoPressShortCode(ShortcodeUtils.getVideoPressShortcodeFromId(media.getVideoPressGuid()));
```
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/util/FluxCUtils.java]: I know this is kind of stupid, especially because we're doing the exact opposite in the `EditorFragment`, we should just drop the `MediaFile` completely at some point.

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java [hunk 2]
```diff
@@ -1776,6 +1783,23 @@ private void startMediaUploadService() {
...
+            File outputFile = File.createTempFile("thumb", ".png", getCacheDir());
+            FileOutputStream outputStream = new FileOutputStream(outputFile);
+            Bitmap thumb = ThumbnailUtils.createVideoThumbnail(videoPath,
+                    android.provider.MediaStore.Images.Thumbnails.MINI_KIND);
+            if (thumb != null) {
+                thumb.compress(Bitmap.CompressFormat.PNG, 100, outputStream);
+                thumbnailPath = outputFile.getAbsolutePath();
+            }
+        } catch (IOException e) {
+            // no op
```
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: wouldn't we like to call `AppLog` here?

File: WordPress/src/main/java/org/wordpress/android/util/FluxCUtils.java (hunk 1 above)
Comment (aforcier) [inline WordPress/src/main/java/org/wordpress/android/util/FluxCUtils.java]: Definitely would be great to phase out `MediaFile` altogether.

**Comment by aforcier** [comment]
I tested both WP.com and self-hosted, and I also merged https://github.com/wordpress-mobile/WordPress-Android/pull/5220 into this branch locally to test errors/retrying for video, all looks good 👍.

This is good to go apart from addressing @mzorz's comment.

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java [hunk 3]
```diff
@@ -1827,6 +1851,10 @@ private MediaModel queueFileForUpload(Uri uri, String mimeType, ArrayList<Long>
             filename += "." + fileExtension;
         }
 
+        if (org.wordpress.android.fluxc.utils.MediaUtils.isVideoMimeType(mimeType)) {
```
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: Yes, we should eventually move this to wputils.

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java (hunk 2 above)
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: Thanks Mario, fixed in  	3c06f59

**Comment by aforcier** [comment]
:shipit:
