### PR TITLE
Remove assignment of EditPostAcivityHook in onAttach

### LINKED ISSUE #6721: Crash (8.3): NullPointerException in EditPostSettingsFragment.fetchSiteSettingsAndUpdateDefaultPostFormatIfNecessary
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.posts.EditPostActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.wordpress.android.fluxc.model.PostModel.getPostFormat()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2699)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2773)
       at android.app.ActivityThread.access$900(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1434)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5930)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.wordpress.android.fluxc.model.PostModel.getPostFormat()' on a null object reference
       at org.wordpress.android.ui.posts.EditPostSettingsFragment.fetchSiteSettingsAndUpdateDefaultPostFormatIfNecessary(EditPostSettingsFragment.java:169)
       at org.wordpress.android.ui.posts.EditPostSettingsFragment.onActivityCreated(EditPostSettingsFragment.java:155)
       at android.app.Fragment.performActivityCreated(Fragment.java:2120)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:928)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1083)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1065)
       at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1885)
       at android.app.Activity.performCreateCommon(Activity.java:6173)
       at android.app.Activity.performCreate(Activity.java:6199)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2652)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2773)
       at android.app.ActivityThread.access$900(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1434)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5930)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
```

https://fabric.io/automattic/android/apps/org.wordpress.android/issues/59ddfbbebe077a4dcc1aeb05

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #6721  (hopefully)

This PR gets the EditPostActivityHook interface instance through calling `getActivity()`, to get the freshest copy each time, instead of relying on `onAttach` being callled

#### Explanation

Ok so, the only way both `getPost()` and `getSite()` return null is for `mEditPostActivityHook` to be null (see also https://github.com/wordpress-mobile/WordPress-Android/pull/6709). That in turn means that `onAttach` is not executed, because that’s the only place where `mEditPostActivityHook` gets assigned a value.
The `EditPostSettingsFragment` lives behind a `FragmentPagerAdapter`, so this is what is handling their lifecycle (`FragmentManager`)  rather than the Activity (`EditPostActivity`)  in a direct way. 
I’ve been looking into possible problems like having the FragmentPagerAdapter not be calling `onAttach` or so, but didn’t find anything consistent.

As per my local tests running Android 8 `onAttach(Context)` seems to get called every time, and as expected these 3 fragments that live in the adapter when editing a Post are created pretty much right away after instantiating the `EditPostActivity`.

Looking into the Crashlytics session logs I can see the crash happens on healthy (somewhat good memory levels) conditions and EditPost activity is the last activity to be created ofc, and judging from the logs the latest thing to happen is some kind of fetching, specifically `SiteActionBuilder.newFetchPostFormatsAction()` or `TaxonomyActionBuilder.newFetchCategoriesAction(siteModel)`.

I came up with this hypothesis here: 
1) Given the order in which methods are executed should be this (https://developer.android.com/guide/components/fragments.html#Lifecycle):
-onAttach, onCreate, onCreateView, onActivityCreated, onStart, onResume —> onPause, onStop, onDestroyView, onDestroy, onDetach.

2) Also, considered that onAttach seems to not be executed all times as per other people’s findings (URL https://stackoverflow.com/questions/32083053/android-fragment-onattach-deprecated).

3) Furthermore, the NPE happens in `onActivityCreated`, which is supposed to be executed immediately after `onAttach`, therefore, it is clear that `onAttach` is not being executed.
(the other crash that #6709 fixed we had it ocurr in `onCreateView`, which also is supposed to be created after `onAttach` gets called).

4) finally, we know the FluxC calls are happening, so the dispatcher registering (which happens in `onCreate`) is getting executed for sure.

Why is onAttach not being executed here? I don’t have an answer to that yet, but I’ve searched elsewhere in the app and we use the same mechanism in various parts of it, the only difference being that this particular fragment is behind a `FragmentPagerAdapter` and not directly attached to an Activity, as explained at the beginning.

The next possibility that comes to mind is to use `getActivity()` so we always get the freshest copy, and check that it’s not null and is of type `EditPostActivityHook` as well.

Therefore, what we’ll try in this PR is to get the reference to the Activity, each time we need it, by eliminating the class member `mEditPostActivityHook ` and making sure we always get the latest reference to whichever Activity we’re attached to by calling `getActivity()`. 

cc @maxme

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java [hunk 1]
```diff
@@ -626,19 +608,28 @@ public void onTimeSet(TimePicker timePicker, int selectedHour, int selectedMinut
...
-        return mEditPostActivityHook.getSite();
+        return getHook().getSite();
+    }
+
+    private EditPostActivityHook getHook() {
+        Activity activity = getActivity();
+        if (activity != null && activity instanceof EditPostActivityHook) {
+            return (EditPostActivityHook) activity;
+        } else {
+            throw new RuntimeException(activity.toString() + " must implement EditPostActivityHook");
```
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java]: We should split the test here

Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java]: addressed in de18b51

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java [hunk 2]
```diff
@@ -626,19 +608,28 @@ public void onTimeSet(TimePicker timePicker, int selectedHour, int selectedMinut
...
-        if (mEditPostActivityHook == null) {
+        if (getHook() == null) {
             // This can only happen during a callback while activity is re-created for some reason (config changes etc)
             return null;
         }
-        return mEditPostActivityHook.getSite();
+        return getHook().getSite();
+    }
+
+    private EditPostActivityHook getHook() {
```
[the remark this answers is not in the document]
Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java]: addressed in 800958e
