### PR TITLE
Post edit: moved SuggestionServiceConnectionManager to fragment

### LINKED ISSUE #4013: Reader: EditPostActivity activity leaks ServiceConnection when back is pressed / sent to the background
### Expected behavior
No leaks :)

### Actual behavior
A leak exception is thrown when EditPostActivity is finished

### Steps to reproduce the behavior
1) create a new post
2) press back
3) check stacktrace

```
04-25 16:28:15.215 2252-2252/org.wordpress.android E/ActivityThread: Activity org.wordpress.android.ui.posts.EditPostActivity has leaked ServiceConnection org.wordpress.android.ui.suggestion.util.SuggestionServiceConnectionManager@de2d97 that was originally bound here
                                                                     android.app.ServiceConnectionLeaked: Activity org.wordpress.android.ui.posts.EditPostActivity has leaked ServiceConnection org.wordpress.android.ui.suggestion.util.SuggestionServiceConnectionManager@de2d97 that was originally bound here
                                                                         at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1077)
                                                                         at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:971)
                                                                         at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1782)
                                                                         at android.app.ContextImpl.bindService(ContextImpl.java:1765)
                                                                         at android.content.ContextWrapper.bindService(ContextWrapper.java:539)
                                                                         at org.wordpress.android.ui.suggestion.util.SuggestionServiceConnectionManager.bindToService(SuggestionServiceConnectionManager.java:27)
                                                                         at org.wordpress.android.ui.suggestion.util.SuggestionUtils.setupTagSuggestions(SuggestionUtils.java:57)
                                                                         at org.wordpress.android.ui.suggestion.util.SuggestionUtils.setupTagSuggestions(SuggestionUtils.java:44)
                                                                         at org.wordpress.android.ui.posts.EditPostActivity.onCreateOptionsMenu(EditPostActivity.java:426)
                                                                         at android.app.Activity.onCreatePanelMenu(Activity.java:2823)
                                                                         at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:298)
                                                                         at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:85)
                                                                         at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:241)
                                                                         at android.support.v7.app.AppCompatDelegateImplV7.preparePanel(AppCompatDelegateImplV7.java:1273)
                                                                         at android.support.v7.app.AppCompatDelegateImplV7.doInvalidatePanelMenu(AppCompatDelegateImplV7.java:1553)
                                                                         at android.support.v7.app.AppCompatDelegateImplV7.access$100(AppCompatDelegateImplV7.java:89)
                                                                         at android.support.v7.app.AppCompatDelegateImplV7$1.run(AppCompatDelegateImplV7.java:126)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:549)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

```

### PR DESCRIPTION
**Pull request by mzorz**
(cont'd from this PR https://github.com/wordpress-mobile/WordPress-Android/pull/4021, which fixes #4013 )

Detail:
There were some tags initialisers in `onCreateOptionsMenu` in EditPostActivity.java. This PR moves that code out of the Activity and makes it be part of the EditPostSettingsFragment where it belongs.

To test:
1) go to blog posts
2) edit/create a blog post for a site that has no tags yet (or erase the app's data before starting to test)
3) go to Post settings screen (see option at the bottom of the Edit screen)

Things to observe:
a) It should not break (force close), and tags for your post should be saved. 
b) It should bind/unbind the service once per fragment creation for EditPostSettingsFragment only (to be checked by placing breakpoints [here](https://github.com/wordpress-mobile/WordPress-Android/compare/issue/4013-serviceconnection-leak-part-2?expand=1#diff-2a05761a1946e0ddb314645e44ab3eb6R132) and [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/suggestion/util/SuggestionUtils.java#L57)

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java [hunk 1]
```diff
@@ -237,6 +254,23 @@ public boolean onTouch(View view, MotionEvent motionEvent) {
                         }
                     }
             );
+
+            mTags = (SuggestionAutoCompleteText) mRootView.findViewById(R.id.tags);
+            if (mTags != null) {
+                mTags.setTokenizer(new SuggestionAutoCompleteText.CommaTokenizer());
+
+                remoteBlogId = -1;
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java]: Rather than have `remoteBlogId` as a class variable, would it make more sense to have it as a method variable that's passed to `setupSuggestionServiceAndAdapter()`?

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java [hunk 2]
```diff
@@ -237,6 +254,23 @@ public boolean onTouch(View view, MotionEvent motionEvent) {
...
+                String blogID = WordPress.getCurrentRemoteBlogId();
+                if (blogID != null) {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java]: This could be simplified by using `StringUtils.stringToInt()`.

**Comment by mzorz** [comment]
changes made @nbradbury ! good call on encapsulating a bit more inside `setupSuggestionServiceAndAdapter()` - thanks!

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java [hunk 3]
```diff
@@ -267,6 +292,20 @@ public boolean onContextItemSelected(MenuItem item) {
...
+    private void setupSuggestionServiceAndAdapter() {
+        if (!isAdded()) return;
+
+        int remoteBlogId = -1;
+        String blogID = WordPress.getCurrentRemoteBlogId();
+        remoteBlogId = StringUtils.stringToInt(blogID, -1);
+
+        mSuggestionServiceConnectionManager = new SuggestionServiceConnectionManager(getActivity(), remoteBlogId);
+        mTagSuggestionAdapter = SuggestionUtils.setupTagSuggestions(remoteBlogId, getActivity(), mSuggestionServiceConnectionManager);
+        if (mTagSuggestionAdapter != null) {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java]: Since `mTagSuggestionAdapter` is only used within this method, can it also be downgraded from a class variable to a method variable?

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java [hunk 4]
```diff
@@ -93,6 +99,10 @@
     private TextView mFeaturedImageLabel;
     private NetworkImageView mFeaturedImageView;
     private Button mFeaturedImageButton;
+    private SuggestionAutoCompleteText mTags;
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java]: This points to the same view as `mTagsEditText` so one of them can be dropped.

Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java]: good catch! 👍

**Comment by nbradbury** [comment]
@mzorz This PR looks good, but Travis is reporting conflicts. I'll merge this after the conflicts are resolved.

**Comment by nbradbury** [comment]
:shipit:
