### PR TITLE
Fix #4274: Add a new Unspam button and hide the Spam button when selected comments are all spams

### LINKED ISSUE #4274: Batch “Unspam" of comments is unclear
### Steps to reproduce the behavior

Go to Comments.
Select Spam from dropdown list.
Select multiple comments using long press.
From context menu select SPAM.
Nothing happens.
### Expected behavior

Context menu label should say "Not Spam" and comments will be “unspammed” after clicking on it.

### PR DESCRIPTION
**Pull request by maxme**
Fix #4274: Add a new Unspam button and hide the Spam button when selected comments are all spams

Here is what it looks like in portrait and landscape modes:
https://cloudup.com/ij2OQe5ojc2

A new unspam icon would be nice for landscape mode, even if that kind of works with the current one.

Also note: the current unspam action in comment detail use the normal "spam" icon.

screenshot-2017-04-11_11 43 18 559

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/comments/CommentsListFragment.java [hunk 1]
```diff
@@ -585,10 +585,11 @@ public boolean onCreateActionMode(ActionMode actionMode, Menu menu) {
             return true;
         }
 
-        private void setItemEnabled(Menu menu, int menuId, boolean isEnabled) {
+        private void setItemEnabled(Menu menu, int menuId, boolean isEnabled, boolean isVisible) {
             final MenuItem item = menu.findItem(menuId);
             if (item == null || item.isEnabled() == isEnabled)
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/comments/CommentsListFragment.java]: Should we also check `isVisible` here?

Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/comments/CommentsListFragment.java]: Fixed in d199a130935163e504eb13df7de88374b004e317

**Comment by nbradbury** [comment]
:shipit:
