### PR TITLE
Crash in full screen dialog

### LINKED ISSUE #12036: NullPointerException: Attempt to read from field 'java.util.List org.wordpress.android.ui.accounts.signup.UsernameChang...
@bummytime This is not a new crash, but it looks like it'd be very easy to fix this. The reason it went kind of unnoticed despite its numbers is because we had 20+ separate issues for it and merging them all revealed the number. I only noticed these crashes while working on a different crash.

**Sentry Url**: https://sentry.io/share/issue/d57306c7818b40978d4e71420f3acf5d/
**User Count**: 544
**Count**: 1266
**First Release**: org.wordpress.android-13.3
**First Seen**: 2019-10-09T06:24:15Z
**Last Seen**: 2020-05-27T05:20:26Z
**24 Hours**: 6
**30 Days**: 228

```
NullPointerException: Attempt to read from field 'java.util.List org.wordpress.android.ui.accounts.signup.UsernameChangerRecyclerViewAdapter.mItems' on a null object reference
     at org.wordpress.android.ui.accounts.signup.BaseUsernameChangerFullScreenDialogFragment.onSaveInstanceState(BaseUsernameChangerFullScreenDialogFragment.java:247)
     at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2766)
     at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManagerImpl.java:2289)
     at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2348)
     at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2768)
     at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManagerImpl.java:2289)
     at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2348)
     at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:151)
     at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:513)
     at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:533)
...
(16 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by planarvoid**
Fixes #12036

I couldn't reproduce this issue but I'm pretty sure it happens because the `onActivityCreated` is not called in some cases when the activity is destroyed before the fragment is fully created. In this case the `onSaveInstanceState` is still called and the adapter is not initialised so the app crashes. I've fixed this by moving the initialization into the `onViewCreated` method. As part of this refactoring I've also renamed the `onViewCreated` method that was previously coming from an interface and which was used to set the controller. The new name is `setController`. I've made this because it was confusing to have two `onViewCreated` methods in the fragment. 

To test:
- Go to Account settings
- Open the dialog to change your username
- Stress test it (rotation, go to background and back)
- See that there is no crash

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/BaseUsernameChangerFullScreenDialogFragment.java [hunk 1]
```diff
@@ -209,6 +210,12 @@ public void onStop() {
         mDispatcher.unregister(this);
     }
 
+    @Override
+    public void onDestroy() {
+        mGetSuggestionsHandler.removeCallbacksAndMessages(null);
```
Comment (planarvoid) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/BaseUsernameChangerFullScreenDialogFragment.java:215]: This should help with the possible memory leak in the runnable passed to the handler.

**Comment by planarvoid** [comment]
thanks for the review @khaykov I've implemented a fix in 8708955 and 0082dd7. Please let me know if I got it right. I could get the app to crash even when not keeping the activities. The fix checks whether the list of suggestions is present and if it's not, it triggers the loading.
