### PR TITLE
Save page info to PostRepository when creating a new page from Layout picker

### LINKED ISSUE #2701: [Android] Gutenberg changes a posts content without informing the UI
**Describe the bug**
In some cases `Gutenberg` seems to change a posts content without informing the UI. This causes an `WordPress-Android` crash only on **DEBUG** mode with a log message `Post had changes that needed to be saved when exiting the editor, and there was NOT an autosave pending. This means that the editor's autosave mechanism failed.` indicating that the autosave mechanism failed.

**To Reproduce**

This is reproduced consistently with the Layout picker feature. You can use the app from https://github.com/wordpress-mobile/WordPress-Android/pull/13105 (use the `wasabi` build flavor)

Layout Picker should show [when creating a new page from *My Site* or *Site Pages* the *Modal Layout Picker* appears](https://github.com/wordpress-mobile/WordPress-Android/pull/12482).

1. Run the WPApp in DEBUG mode from the PR above.
1. In the **My Site** screen press the **Add(+)** floating button
1. Select **Site page** from the bottom menu
1. Scroll to the bottom and select the first layout of the **Contact pages** category
1. Press the **Create page** button
1. Wait for the page to load
1. Press the **back button** **without editing** the page
1. Notice that the app crashes

**Expected behavior**
`Gutenberg` should inform of the changes preventing the app from crashing.

**Screenshots**

Comparing the post content reveals differences that seem to occur on the `Gutenberg` side and are not tracked.

The issue also is reproduced consistently with the layout of the **Team pages** category. With other supported layouts no crash does not seem to occur.

**Smartphone:**
 - OS: Android

**Additional context**
Though this seems to occur rarely it might be possible to be reproduced in other cases where the content is set without the user editing it. Such cases are creating posts from the share action, rebloging a post or setting a page layout (as in the reproduction steps above).

### PR DESCRIPTION
**Pull request by cameronvoell**
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/2701

To test:

1. Run the WPApp in DEBUG mode from the PR above.
2. In the My Site screen press the Add(+) floating button
3. Select Site page from the bottom menu
4. Scroll to the bottom and select the first layout of the Contact pages category
5. Press the Create page button
6. Wait for the page to load
7. Press the back button without editing the page
8. Notice that the app no longer crashes

PR submission checklist:

- [X] I have considered adding unit tests where possible.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by cameronvoell** [comment]
Note that this PR fixes one case of this issue: https://github.com/wordpress-mobile/WordPress-Android/issues/13003, but I do not expect it to fix all cases (some Sentry events are for posts not pages).

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java [hunk 1]
```diff
@@ -451,6 +451,31 @@ private void newPostSetup() {
         mShortcutUtils.reportShortcutUsed(Shortcut.CREATE_NEW_POST);
     }
 
+    private void newPageFromLayoutPickerSetup(String title, String content) {
```
Comment (antonis) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java:454]: We can probably reuse the implementation of `newPostSetup` since the only difference is the `instantiatePostModel` call.
This is just a suggestion and I understand that the way that it is implemented now might be more clear and easier to extend in the future.

**Review by antonis — APPROVED** [review]
Great work tracking down this issue and fixing it @cameronvoell 👍 
I tested this on a Google Pixel 2 XL with Android 11 and works as expected. The code LGTM 🎉 
I added only one comment but it is just a suggestion.
