### PR TITLE
Fixes #9122: remote preview for pages

### LINKED ISSUE #9122: Pages: Viewing/previewing a page only shows local preview
### Expected behavior

If a page doesn't have local changes (all changes are synced to remote) I expect to be able to view/preview the remote version of the page, as it looks on my site.

### Actual behavior

When I view/preview a page, I only ever see the local preview.

### Steps to reproduce the behavior

1. Open My Sites > Site Pages.
2. Go to the Published filter and find a page with no local changes.
3. Tap the ellipsis menu next to the page and select "View."

Result: You see the local preview and not the remote version of the published page.

screenshot_20190125-140141

### PR DESCRIPTION
**Pull request by maxme**
Fixes #9122

## Description

Before this patch we were only showing the local preview on pages (even on published post without modifications).

Before|After
-|-
Screenshot_1563894218|Screenshot_1563894787

For draft with modification, we were also showing the local preview:

Before|After
-|-
Screenshot_1563894240 | Screenshot_1563894815

Notes;
- I removed `EditPostPreviewFragment` in this PR, because it wasn't used anymore. It was worth it's own PR 😬 .

### Test - published post

From the page list:

- On a published page
- Tap the "View" button from the 3 dots button
- Make sure the preview is displayed in the "preview" webview

### Test - published post with modifications

From the page list:

- On a published page with modifications
- Tap the "View" button from the 3 dots button
- Make sure the preview is generated and displayed in the "preview" webview

### Test - preview draft from the editor

- Open an existing draft
- From Overflow  menu, press "Preview"
- Make sure the preview is generated and displayed in the "preview" webview

### Test - preview draft with local changes from the editor

- Open an existing draft in the editor, modify it.
- From Overflow  menu, press "Preview"
- Make sure the preview is generated and displayed in the "preview" webview

### Test - new draft

- Create a new draft in the editor, add a title.
- From Overflow  menu, press "Preview"
- Make sure the preview is generated and displayed in the "preview" webview

## Known issues:

- Same as for posts, if the user edit concurrently edit drafts on Calypso (or another device), and preview it, the preview process will push the new version and could override some post edits silently.
- The "Saving / Generating" preview is not cancellable https://github.com/wordpress-mobile/WordPress-Android/issues/10141

## Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/pages/PagesFragment.kt [hunk 1]
```diff
@@ -249,6 +264,44 @@ class PagesFragment : Fragment() {
...
 
+    private fun showToast(toastMessageHolder: ToastMessageHolder) {
+        context?.let {
+            toastMessageHolder.show(it)
+        }
+    }
+
+    private fun previewPage(activity: FragmentActivity, page: PageModel) {
+        val post = postStore.getPostByLocalPostId(page.pageId)
+        val action = PreviewPost(
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/ui/pages/PagesFragment.kt]: I'd consider trying to move most of this code into the VM. It'll require some changes, but it would make the code much cleaner and testable. Wdyt?

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PageAndPostListPreviewStateHelper.kt [hunk 2]
```diff
@@ -0,0 +1,83 @@
+package org.wordpress.android.ui.posts
+
+import androidx.fragment.app.FragmentActivity
+import org.wordpress.android.fluxc.model.PostModel
+import org.wordpress.android.ui.posts.RemotePreviewLogicHelper.RemotePreviewType
+import org.wordpress.android.ui.uploads.UploadService
+import org.wordpress.android.util.AppLog
+
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/PageAndPostListPreviewStateHelper.kt]: Tbh I'm not a big fan of functions. I think they are really useful for some scenarios, but I prefer to use methods wherever possible. I'd consider wrapping these functions with an injectable (@Reusable) class.

- Afaik functions can't be mocked which is a huge downside with very little/no gain. 
- The autocompletion can easily become very messy - making sure we don't have that many collisions in class names is already difficult enough, making sure we don't have collisions in function names is almost impossible.

Wdyt?

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PageAndPostListPreviewStateHelper.kt [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+    newState: PostListRemotePreviewState,
+    prevState: PostListRemotePreviewState?,
+    postInfo: PostInfoType,
+    handleRemotePreview: (localPostId: Int, RemotePreviewType) -> Unit
+) = when (newState) {
+    PostListRemotePreviewState.PREVIEWING -> {
+        prevState?.let {
+            if (it == PostListRemotePreviewState.UPLOADING_FOR_PREVIEW ||
+                    it == PostListRemotePreviewState.REMOTE_AUTO_SAVING_FOR_PREVIEW) {
+                (postInfo as? PostInfoType.PostInfo)?.let { info ->
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/PageAndPostListPreviewStateHelper.kt]: Do we want to simply ignore the invocation when the client provides a wrong PostInfo object? I think we should consider either 
- assume we have the correct object
`handleRemotePreview((postInfo as PostInfoType.PostInfo).post.id, getRemotePreviewType(prevState))`
- throw an `InvalidArgumentException` when the cast fails
- log an error message

I'm a fan of fail fast principle so I'd personally go with either 1 or 2. 

Wdyt?

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PageAndPostListPreviewStateHelper.kt [hunk 4]
```diff
@@ -0,0 +1,83 @@
...
+                AppLog.d(
+                        AppLog.T.POSTS,
+                        "Upload for preview not possible: post already uploading or queued"
+                )
+            }
+        }
+    }
+}
+
+private fun getRemotePreviewType(prevState: PostListRemotePreviewState): RemotePreviewType {
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/PageAndPostListPreviewStateHelper.kt]: This private function seems a bit misleading. It returns `RemotePreviewType.REMOTE_PREVIEW_WITH_REMOTE_AUTO_SAVE` for `PostListRemotePreviewState.NONE` and `PostListRemotePreviewState.PREVIEWING`. I understand that it's called from a spot where we know it'll be either `PostListRemotePreviewState.UPLOADING_FOR_PREVIEW` or `PostListRemotePreviewState.REMOTE_AUTO_SAVING_FOR_PREVIEW`, but imho we should try to prevent the client from making a mistake. I'd consider throwing an exception if the method is called with an unexpected argument.

**Comment by shakeebshams** [comment]
Thanks, works as expected

File: RELEASE-NOTES.txt [hunk 5]
```diff
@@ -1,17 +1,15 @@
 13.0
 -----
- 
-12.9
------
-* Add Remote Preview support for Drafts, Published and Scheduled posts with local changes
+* Add Remote Preview support for posts and pages.
```
[the remark this answers is not in the document]
Comment (maxme) [reply RELEASE-NOTES.txt]: Yes, `Post List: Trashed post must now be restored before edit or previe` live in the master branch `feature/master-remote-previews`, we'll have to update the RELEASE-NOTES when we merge the feature branch to `develop`.

File: WordPress/src/main/java/org/wordpress/android/ui/pages/PagesFragment.kt [hunk 6]
```diff
@@ -249,6 +264,44 @@ class PagesFragment : Fragment() {
...
     }
 
+    private fun showToast(toastMessageHolder: ToastMessageHolder) {
+        context?.let {
+            toastMessageHolder.show(it)
+        }
+    }
+
+    private fun previewPage(activity: FragmentActivity, page: PageModel) {
+        val post = postStore.getPostByLocalPostId(page.pageId)
```
[the remark this answers is not in the document]
Comment (maxme) [reply WordPress/src/main/java/org/wordpress/android/ui/pages/PagesFragment.kt]: Fixed in 5706894ad87038c328af3a0b34ffc80eb1413e8f

File: WordPress/src/main/java/org/wordpress/android/ui/pages/PagesFragment.kt (hunk 1 above)
Comment (maxme) [reply WordPress/src/main/java/org/wordpress/android/ui/pages/PagesFragment.kt]: I'm not sure about that one. This is the equivalent code of the handlePostListAction in the post list activity. Ideally we would share the same "coreVM" with both page and post list, but it's out of scope for this patch IMO.

File: WordPress/src/main/java/org/wordpress/android/ui/pages/PagesFragment.kt [hunk 7]
```diff
@@ -280,7 +333,25 @@ class PagesFragment : Fragment() {
...
         viewModel.previewPage.observe(this, Observer { page ->
-            page?.let { ActivityLauncher.viewPagePreview(this, page) }
+            page?.let {
+                previewPage(activity, page)
+            }
+        })
+
+        viewModel.browsePreview.observe(this, Observer { preview ->
+            preview?.let {
+                val post = postStore.getPostByLocalPostId(preview.pageId)
```
[the remark this answers is not in the document]
Comment (maxme) [reply WordPress/src/main/java/org/wordpress/android/ui/pages/PagesFragment.kt]: Fixed in 5706894

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PageAndPostListPreviewStateHelper.kt (hunk 2 above)
Comment (maxme) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/PageAndPostListPreviewStateHelper.kt]: Fixed in 59a4a3a2ff66e2514e627f09322a7602af44ed73

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PageAndPostListPreviewStateHelper.kt (hunk 3 above)
Comment (maxme) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/PageAndPostListPreviewStateHelper.kt]: Updated in fa5c0dee700a549a22f557e3abdef5efa8e4b9a6

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PageAndPostListPreviewStateHelper.kt (hunk 4 above)
Comment (maxme) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/PageAndPostListPreviewStateHelper.kt]: Fixed in ad64d06d3915d0720af6a38fd6456e74ed0040af

**Comment by maxme** [comment]
@malinajirka this is ready for a second pass

**Comment by malinajirka** [comment]
LGTM! Thanks
