### PR TITLE
7.3 - NPE PlansUpdate service

### LINKED ISSUE #5798: Crash report 7.2: NPE in PlanUpdateService
```
Fatal Exception: java.lang.RuntimeException: Unable to start service org.wordpress.android.ui.plans.PlanUpdateService@41365be8 with Intent { cmp=org.wordpress.android/.ui.plans.PlanUpdateService }: java.lang.NullPointerException
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2608)
       at android.app.ActivityThread.access$1900(ActivityThread.java:130)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4847)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:535)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException
       at org.wordpress.android.ui.plans.PlanUpdateService.downloadAvailablePlansForSite(PlanUpdateService.java:125)
       at org.wordpress.android.ui.plans.PlanUpdateService.onStartCommand(PlanUpdateService.java:71)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2591)
       at android.app.ActivityThread.access$1900(ActivityThread.java:130)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4847)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:535)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
````

### PR DESCRIPTION
**Pull request by daniloercoli**
Fixes #5798 by making sure `mSite` is not null when starting the service.

cc @mzorz

### CODE REVIEW

**Comment by mzorz** [comment]
Hi @daniloercoli ! I understand the NPE would be saved now, but this call here would return and the progress would be shown forever here https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/plans/PlansActivity.java#L113

Maybe we should: 
1 - add a return value to `public boolean static startService()` and make it `true` if the service was started, or `false`  if the preconditions (context and site not being null) aren't met
2- if the service was started but later on in `onStartCommand` the `mSite` property was null or empty, then trigger an EventBus event to tell the Activity that we couldn't move any further:

```            EventBus.getDefault().post(new PlanEvents.PlansUpdateError(mSite));
```
(or alike)
and the Activity should show an error to the user here, and maybe finish the Activity.

What do you think?

**Comment by daniloercoli** [comment]
Right, I was thinking to go with option 2 this morning, but then forgot to go down that road. :face_with_head_bandage: 
Will implement required changes.

**Comment by mzorz** [comment]
Cool np - BTW I think we should implement both option 1 and 2, as the first one just validates the preconditions exist (context and site not being null) , while the third one could be used in case of any kind of error while trying to update plans. Also if conditions in (1) are not met, we'd also never trigger the event in (2)  (because the service is not even started)

**Comment by daniloercoli** [comment]
Agree, both options are required.

**Comment by daniloercoli** [comment]
Ready for another round of review.

File: WordPress/src/main/java/org/wordpress/android/ui/plans/PlanUpdateService.java [hunk 1]
```diff
@@ -65,6 +74,11 @@ public void onDestroy() {
     @Override
     public int onStartCommand(Intent intent, int flags, int startId) {
         mSite = (SiteModel) intent.getSerializableExtra(WordPress.SITE);
+        if (mSite == null) {
+            AppLog.e(AppLog.T.PLANS, "PlanUpdateService was started with an empty site.");
+            requestFailed();
+            return START_NOT_STICKY;
```
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/plans/PlanUpdateService.java]: should we call `stopSelf();` before returning?

**Comment by mzorz** [comment]
Just added a last comment and then we'll be good to go @daniloercoli

**Comment by daniloercoli** [comment]
Good question, I had checked Stats service, and ReaderUpdate service and both of them use `START_NOT_STICKY` without stopping them self. System should stop the service since there is nothing ongoing.

**Comment by mzorz** [comment]
:shipit:
