### PR TITLE
Show the correct error message when reply to comment fails

### LINKED ISSUE #3977: Obscur error message when replying to a closed thread
### Steps to reproduce the behavior

1. Go to the site Comments section
1. Select a comment from a closed thread
1. Try to reply and get a "Reply failed" toast

XMLRPC response is pretty clear:
```
04-15 09:25:24.599 1971-3601/org.wordpress.android.beta W/WordPress-API: Response document received from the server: <?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
 <fault>
   <value>
     <struct>
       <member>
         <name>faultCode</name>
         <value><int>403</int></value>
       </member>
       <member>
         <name>faultString</name>
         <value><string>Sorry, comments are closed for this item.</string></value>
       </member>
     </struct>
   </value>
 </fault>
</methodResponse>
04-15 09:25:24.599 1971-3601/org.wordpress.android.beta E/WordPress-COMMENTS: Error while sending the new comment
org.xmlrpc.android.XMLRPCFault: Sorry, comments are closed for this item. [Code: 403]
    at org.xmlrpc.android.XMLRPCClient.parseXMLRPCResponse(XMLRPCClient.java:334)
    at org.xmlrpc.android.XMLRPCClient$Caller.callXMLRPC(XMLRPCClient.java:515)
    at org.xmlrpc.android.XMLRPCClient$Caller.access$000(XMLRPCClient.java:430)
    at org.xmlrpc.android.XMLRPCClient.call(XMLRPCClient.java:231)
    at org.xmlrpc.android.XMLRPCClient.call(XMLRPCClient.java:215)
    at org.wordpress.android.ui.comments.CommentActions$2.run(CommentActions.java:177)

```

### PR DESCRIPTION
**Pull request by daniloercoli**
Fixes #3977 

To test: 
- Go to the site Comments section
- Select a comment from a closed thread
- Try to reply and get a "Reply failed" toast

~~Needs review: @roundhill~~

The error message returned from the server is shown to the user in case of `XMLRPCFault` only (that means when the server replies correctly with a XML-RPC response document). Default error message is shown when IOErrors, or any other problem.
Errors are always shown to the user in case of replying to a comment by using the the REST layer.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/comments/CommentActionResult.java [hunk 1]
```diff
@@ -0,0 +1,19 @@
+package org.wordpress.android.ui.comments;
+
+public class CommentActionResult {
+
+    public static int COMMENT_ID_ON_ERRORS = -1;
+    public static int COMMENT_ID_UNKNOWN = -2;
+
+    long mCommentID;
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/comments/CommentActionResult.java]: I think we want `mCommentID` and `mMessage` to be private.

File: WordPress/src/main/java/org/wordpress/android/ui/comments/CommentActionResult.java [hunk 2]
```diff
@@ -0,0 +1,19 @@
+package org.wordpress.android.ui.comments;
+
+public class CommentActionResult {
+
+    public static int COMMENT_ID_ON_ERRORS = -1;
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/comments/CommentActionResult.java]: `COMMENT_ID_ON_ERRORS` and `COMMENT_ID_UNKNOWN` should be `final`.

File: WordPress/src/main/java/org/wordpress/android/ui/comments/CommentActionResult.java [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+    public static int COMMENT_ID_UNKNOWN = -2;
+
+    long mCommentID = COMMENT_ID_UNKNOWN;
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/comments/CommentActionResult.java]: I think we want `mCommentID` and `mMessage` to be private.

File: WordPress/src/main/java/org/wordpress/android/ui/comments/CommentActionResult.java [hunk 4]
```diff
@@ -0,0 +1,19 @@
+package org.wordpress.android.ui.comments;
+
+public class CommentActionResult {
+
+    public static int COMMENT_ID_ON_ERRORS = -1;
+    public static int COMMENT_ID_UNKNOWN = -2;
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/comments/CommentActionResult.java]: Am I correct in thinking that `COMMENT_ID_UNKNOWN` is used primarily for replies, when the commentID isn't known yet? If so, a comment stating this purpose would be helpful (otherwise it might be assumed `COMMENT_ID_UNKNOWN` should be treated as an error, which is what I initially thought).

**Comment by daniloercoli** [comment]
@nbradbury - Sorry for those minor lackings. It's now ready for another round of review!

**Comment by nbradbury** [comment]
Looks good! :shipit:
