### PR TITLE
[Prompts] Fix CTA text flickering in Prompts card

### LINKED ISSUE #18671: [Blogging Prompts] Card CTA line break flickering
### Expected behavior
The CTA that says "View all responses" should have a consistent text break / number of lines (which is ideally 1 for most regular-sized phones).

### Actual behavior
The CTA that says "View all response" flickers between having 2 lines and 1 line, even when all the text fits 1 line. This happens whenever the dashboard refreshes (pull-to refresh / coming back to the dashboard from another screen / etc). 

Here's the original report from @hypest: https://github.com/wordpress-mobile/WordPress-Android/issues/17876#issuecomment-1594752334

### Steps to reproduce the behavior
1. Open the Jetpack app with a blog site (containing a few published posts)
2. **Check** the Prompts card shows up on the Home dashboard
3. Tap "View all responses" to get to the reader tag screen
4. Go back to the dashboard
5. **Verify** the text keeps flickering between 2 lines and 1 line

### Video
https://github.com/wordpress-mobile/WordPress-Android/assets/1032913/b09aa00e-266c-4e1d-981b-ae82e100acf6

### PR DESCRIPTION
**Pull request by thomashorta**
Fixes #18671 

It doesn't make sense to use a `FlexboxLayoutManager` here and it seems to be introducing issues with spacing, positioning, and measurement of the items when the card is updated multiple times. 

This causes the spacing between avatars to be inconsistent and was also causing the more visible issue of the text flickering between having 2 lines and 1 line.

I tried changing the Layout Manager to `LinearLayoutManager` fix this issue, but it seems the issue is actually related to the `TrainOfAvatarsAdapter` we are using and how it's measuring child items. I ended up creating a `View` wrapper around the `TrainOfIcons` Composable and using that paired with a `TextView` to achieve the same UI.

To test:
1. Open the Jetpack app with a blog site (containing a few published posts)
2. **Check** the Prompts card shows up on the Home dashboard
3. Tap "View all responses" to get to the reader tag screen
4. Go back to the dashboard
5. **Verify** the text and icons inside the Prompts card don't change

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:

- [x] Portrait and landscape orientations.
- [x] Light and dark modes.
- [x] Fonts: Larger, smaller and bold text.
- [x] High contrast.
- [x] Talkback.
- [x] Languages with large words or with letters/accents not frequently used in English.
- [x] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [x] Large and small screen sizes. (Tablet and smaller phones)
- [x] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by thomashorta** [comment]
While testing with a really big text I noticed the issue still happens if the RecyclerView is bigger than the width of the card, so maybe some extra changes are needed. Marking the PR as "Not ready for Review" for now.

File: WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingDialogFragment.kt [hunk 1]
```diff
@@ -115,29 +110,34 @@ class BloggingPromptsOnboardingDialogFragment : FeatureIntroductionDialogFragmen
     }
 
     private fun setupContent(readyState: Ready) {
+        print(readyState)
```
Comment (RenanLukas) [inline WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingDialogFragment.kt]: 💡 Should we replace this with `Log` or remove it in case it's not needed?

File: WordPress/src/main/java/org/wordpress/android/ui/compose/views/TrainOfAvatarsView.kt [hunk 2]
```diff
@@ -0,0 +1,140 @@
...
+    private val avatarsState: MutableState<List<AvatarItem>> = mutableStateOf(emptyList())
+
+    // icon size in DP used by the Composable
+    private val iconSizeState: MutableState<Int> = mutableStateOf(DEFAULT_ICON_SIZE_DP)
+
+    // icon border width in DP used by the Composable
+    private val iconBorderWidthState: MutableState<Int> = mutableStateOf(DEFAULT_ICON_BORDER_WIDTH_DP)
+
+    // placeholder drawable/color resource to be used by the Composable
+    private val placeHolderResState: MutableState<Int> = mutableStateOf(R.color.placeholder)
```
Comment (RenanLukas) [inline WordPress/src/main/java/org/wordpress/android/ui/compose/views/TrainOfAvatarsView.kt]: Nitpick: I think placeholder is just one word. Would it make sense to rename the variable to `placeholderResState`?

File: WordPress/src/main/java/org/wordpress/android/ui/compose/views/TrainOfAvatarsView.kt [hunk 3]
```diff
@@ -0,0 +1,140 @@
...
+    @Composable
+    override fun Content() {
+        if (avatarsState.value.isEmpty()) return
+
+        AppTheme {
+            TrainOfIcons(
+                iconModels = avatarModels(),
+                iconSize = iconSizeState.value.dp,
+                iconBorderWidth = iconBorderWidthState.value.dp,
+                placeholder = placeholderPainter()
```
Comment (RenanLukas) [inline WordPress/src/main/java/org/wordpress/android/ui/compose/views/TrainOfAvatarsView.kt]: 💡 For the icon dimensions we have the words `Size` and `Width`. Would it make sense to have the word `Color` for this attribute so it's clearer?
e.g. `placeholderColor`

**Review by RenanLukas — COMMENTED** [review]
Thanks for the PR, @thomashorta. It's working as expected.

I've left a couple of comments. Please let me know if they make sense.

File: WordPress/src/main/java/org/wordpress/android/ui/compose/views/TrainOfAvatarsView.kt (hunk 3 above)
Comment (thomashorta) [reply WordPress/src/main/java/org/wordpress/android/ui/compose/views/TrainOfAvatarsView.kt]: This is not a color necessarily, it can be any painter, so `placeholder` makes sense here, which is how it's declared in Coil's `AsyncImage`, but maybe it could be `placeholderPainter` to be clearer, wdyt?

File: WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingDialogFragment.kt (hunk 1 above)
Comment (thomashorta) [reply WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingDialogFragment.kt]: Ooops, added that when testing something and forgot to remove, thanks!

**Review by RenanLukas — APPROVED** [review]
LGTM :shipit:
