### PR TITLE
Fix #6314: use a boolean to track receiver registration state

### LINKED ISSUE #6314: Crash report 7.8-rc-1: Receiver not registered: ConnectionChangeReceiver
```
Fatal Exception: java.lang.IllegalArgumentException: Receiver not registered: org.wordpress.android.networking.ConnectionChangeReceiver@423e7298
       at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:654)
       at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1248)
       at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:389)
       at org.wordpress.android.WordPress$ApplicationLifecycleMonitor$1.run(WordPress.java:845)
       at java.util.Timer$TimerImpl.run(Timer.java:284)
```

### PR DESCRIPTION
**Pull request by maxme**
Fix #6314: use a boolean to track receiver registration state

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/WordPress.java [hunk 1]
```diff
@@ -812,44 +815,49 @@ private void updatePushNotificationTokenIfNotLimited() {
...
+            properties.put("last_visible_screen", lastActivity.toString());
+            if (mApplicationOpenedDate != null) {
+                Date now = new Date();
+                properties.put("time_in_app", DateTimeUtils.secondsBetween(now, mApplicationOpenedDate));
+                mApplicationOpenedDate = null;
+            }
+            AnalyticsTracker.track(AnalyticsTracker.Stat.APPLICATION_CLOSED, properties);
+            AnalyticsTracker.endSession(false);
+            // Methods onAppComesFromBackground / onAppGoesToBackground are only workarounds to track when the
+            // app goes or comes to background, but there are not 100% reliable, and here we could try
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/WordPress.java]: Nitpick: It might be better to change `there` with `they` here. Also, do you think the following would be better overall?
```
app goes to or comes from background, but they are not 100% reliable, so we should avoid unregistering the receiver twice
```

Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/WordPress.java]: Good catch, updated in  8d5ee7b

Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/WordPress.java]: Thanks for the change! I'll merge once Travis does it's thing! (Not that it can fail after a comment change)

Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/WordPress.java]: "its" thing ;)

Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/WordPress.java]: lol, yes!
