### PR TITLE
issue/1406-self-hosted-gallery

### LINKED ISSUE #1406: Gallery doesn't work well on self-hosted sites
Some of the features in "Gallery Settings" are available to WordPress.com sites only. The app doesn't check if the current blog is Self-Hosted or not when creating that screen, resulting in unexpected result on self-hosted blogs.
For example if the user select type = Slideshow.

Ref: http://android.forums.wordpress.org/topic/slideshow-gallery-seems-not-to-work?replies=1

http://codex.wordpress.org/The_WordPress_Gallery

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #1406 - resolves a long-standing issue with gallery settings. Self-hosted sites don't support gallery types, so this PR hides the type selection from the gallery settings for self-hosted sites.

* Create/edit a post
* Tap the icon to add media
* Tap the "W" icon at the bottom right to choose from WP Media
* Select multiple photos then tap the checkmark to insert them
* For self-hosted sites, the resulting dialog should be the one below, with the gallery type selection removed

screenshot_1494879000

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/InsertMediaDialog.java [hunk 1]
```diff
@@ -73,15 +76,18 @@ public String toString() {
...
 
 
-    public static InsertMediaDialog newInstance(@NonNull InsertMediaCallback callback) {
+    public static InsertMediaDialog newInstance(@NonNull InsertMediaCallback callback, @NonNull SiteModel site) {
         InsertMediaDialog dialog = new InsertMediaDialog();
         dialog.setStyle(AppCompatDialogFragment.STYLE_NORMAL, R.style.Theme_AppCompat_Light_Dialog);
         dialog.setCallback(callback);
+        Bundle args = new Bundle();
+        args.putSerializable(WordPress.SITE, site);
         return dialog;
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/InsertMediaDialog.java]: It seems that `dialog.setArguments(args);` is missing here.

Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/InsertMediaDialog.java]: @daniloercoli That was really dumb of me. Corrected in 0655416, thanks for catching it.

**Comment by daniloercoli** [comment]
Looks good! :shipit:
