### PR TITLE
Fix NPE in EditPostActivty onPostUploaded 

### LINKED ISSUE #20953: NullPointerException
Sentry Issue: [JETPACK-ANDROID-88M](https://a8c.sentry.io/issues/4269666684/?referrer=github_integration)

```
NullPointerException: None
    at org.wordpress.android.ui.posts.EditPostRepository.getId(EditPostRepository.kt:56)
    get() = post!!.id
    at org.wordpress.android.ui.posts.EditPostActivity.onPostUploaded(EditPostActivity.kt:3816)
    if (post != null && post.id == editPostRepository.id) {
...
(8 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by zwarm**
Fixes #20953 

This PR addresses a potential NullPointerException in the `onPostUploaded` event handler by ensuring that the `editPostRepository.id` is safely accessed. In `EditPostActivity`, the EventBus is registered before `EditPostRepository` is fully initialized. As such, there is a risk that an onPostUploaded event might be posted before the EditPostRepository has completed its initialization process, thus causing an NPE when "id" is accessed.

Changes:
- Updated the onPostUploaded method to use val editPostId = editPostRepository.getPost()?.id.
This ensures that the check post.id == editPostId will fail if editPostRepository.getPost() returns null, preventing a NullPointerException.

-----

## To Test:
As I was unable to recreate the issue, please validate that the Create/Edit post flow works as expected.

-----

## Regression Notes

1. Potential unintended areas of impact
The crash still occurs

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

3. What automated tests I added (or what prevented me from doing so)
N/A

-----

## PR Submission Checklist:
- [X] I have completed the Regression Notes.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/wordpress-mobile/WordPress-Android/milestone/285">25.0 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt [hunk 1]
```diff
@@ -3813,7 +3813,9 @@ class EditPostActivity : LocaleAwareActivity(), EditorFragmentActivity, EditorIm
     @Subscribe(threadMode = ThreadMode.MAIN)
     fun onPostUploaded(event: OnPostUploaded) {
         val post: PostModel? = event.post
-        if (post != null && post.id == editPostRepository.id) {
+        val editPostId = editPostRepository.getPost()?.id
```
Comment (irfano) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt]: > there is a risk that an onPostUploaded event might be posted before the EditPostRepository has completed its initialization process

if `editPostRepository` has not completed its initialization process, wouldn't `editPostRepository.getPost()?.id` still throw `NullPointerException`?

I'm still approving the PR since this prevents a null `post` from causing a crash.

**Review by irfano — APPROVED** [review]

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt (hunk 1 above)
Comment (zwarm) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt]: @irfano 

If `editPostRepository.getPost()`  returns null, then editPostId will be null and id won't be accessed, then we can safely perform the comparison post.id == editPostId without throwing a NullPointerException. From the looks of the EditPostRepository, id isn't nullable. 

Are you are asking what if the `EditPostRepository` property is not initialized itself? Am I correct here? In that cause I would expect a `UninitializedPropertyAccessException` and not an NPE. I added a check for that in [08efcdc](https://github.com/wordpress-mobile/WordPress-Android/pull/20954/commits/08efcdcc847da37754daf6551dafef301045b7d9)

Comment (irfano) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt]: > Are you are asking what if the EditPostRepository property is not initialized itself? Am I correct here? In that cause I would expect a UninitializedPropertyAccessException and not an NPE. 

Yes, I asked that because I thought you meant the initialization of `EditPostRepository`, but you actually meant the initialization of its members, such as `post`. Still, thanks for adding an extra check for `EditPostRepository`. 👍🏻
