### PR TITLE
Guard for null Activity

### LINKED ISSUE #7386: Crash on v9.4: NPE in getLoadingMediaErrorPlaceholder()
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getString(int)' on a null object reference
       at org.wordpress.android.util.ToastUtils.showToast(ToastUtils.java:23)
       at org.wordpress.android.util.ToastUtils.showToast(ToastUtils.java:19)
       at org.wordpress.android.editor.AztecEditorFragment.getLoadingMediaErrorPlaceholder(AztecEditorFragment.java:927)
       at org.wordpress.android.editor.AztecEditorFragment.appendMediaFile(AztecEditorFragment.java:906)
       at org.wordpress.android.ui.posts.EditPostActivity.addMediaVisualEditor(EditPostActivity.java:2183)
       at org.wordpress.android.ui.posts.EditPostActivity.access$4400(EditPostActivity.java:161)
       at org.wordpress.android.ui.posts.EditPostActivity$AddMediaListThread$3.run(EditPostActivity.java:2170)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

### PR DESCRIPTION
**Pull request by hypest**
Fixes #7386 

appendMediaFile() may be called from a background thread but Activity may already be gone so, bail.

To test:
No steps known.

### CODE REVIEW

File: libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java [hunk 1]
```diff
@@ -799,6 +799,14 @@ public CharSequence getContent() {
 
     @Override
     public void appendMediaFile(final MediaFile mediaFile, final String mediaUrl, ImageLoader imageLoader) {
+        if (getActivity() == null) {
```
Comment (daniloercoli) [inline libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java]: Niptick: should we use `isAdded()` here for consistency with other part of the code?

Comment (hypest) [reply libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java]: Not a nitpick at all, thanks for bringing it up @daniloercoli !

Since we don't have steps to reproduce the crash, I opted for code that does exactly what's needed to guard the NPE. `isAdded()` would most probably do the job as well but, since it does some extra checks beyond making sure the Fragment's host is null or not, I'm sure if it could produce false positives.

That said, if you have better insight that `isAdded()` can be safely used in place of `getActivity()` in this case, happy to replace!

**Comment by daniloercoli** [comment]
:shipit:
