### PR TITLE
Fix #4875: 6.2 crash in signinfragment

### LINKED ISSUE #4875: Crash report 6.2: ISE in SignInFragment.showSelfHostedSignInForm
```
Fatal Exception: java.lang.IllegalStateException: Fragment SignInFragment{5c59e3a} not attached to Activity
       at android.support.v4.app.Fragment.getResources(Fragment.java:651)
       at android.support.v4.app.Fragment.getString(Fragment.java:673)
       at org.wordpress.android.ui.accounts.SignInFragment.showSelfHostedSignInForm(SignInFragment.java:369)
       at org.wordpress.android.ui.accounts.SignInFragment$14.onResponse(SignInFragment.java:925)
       at org.wordpress.android.ui.accounts.SignInFragment$14.onResponse(SignInFragment.java:908)
       at com.wordpress.rest.RestRequest.deliverResponse(RestRequest.java:76)
       at com.wordpress.rest.RestRequest.deliverResponse(RestRequest.java:19)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5451)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

### PR DESCRIPTION
**Pull request by maxme**
Fix #4875: 6.2 crash in signinfragment

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInFragment.java [hunk 1]
```diff
@@ -904,6 +904,23 @@ protected void signIn() {
         }
     }
 
+    private void onWPComEmailCheckError(boolean forceWordPressComDisplay) {
+        if (!isAdded()) {
+            return;
+        }
+
+        if (forceWordPressComDisplay) {
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInFragment.java]: Is this `IF` condition correct? The guard says force wpcom display, but later we show the self hosted sign in form.

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInFragment.java [hunk 2]
```diff
@@ -913,25 +930,17 @@ public void onResponse(JSONObject response) {
...
-                        showPasswordFieldAndFocus();
-                    }
+                    onWPComEmailCheckError(false);
                 }
             }
         }, new RestRequest.ErrorListener() {
             @Override
             public void onErrorResponse(VolleyError error) {
-                showPasswordFieldAndFocus();
+                onWPComEmailCheckError(true);
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInFragment.java]: In case of errors, even a classic network error, we're calling `onWPComEmailCheckError(true);` that shows the password field and tries to give the focus to it. The username field is left unchanged. We probably need to check the kind of error here, and change the response according to it.

**Comment by daniloercoli** [comment]
:shipit: Since this fix the crash, but I've left a comment in the PR that we could fix later.
