### PR TITLE
[Reader IA] Fix Discover scrolling to top when loading more posts

### LINKED ISSUE #19968: [Reader][Bug] Discover scrolls to top when loading more posts
### Expected behavior
When scrolling down the Discover feed to load older posts, after doing a pull to refresh, the screen should not scroll back to the top.

### Actual behavior
When scrolling down the Discover feed to load older posts, **after doing a pull to refresh**, the screen scrolls back to the first item, even though it's loading items on the end of the list (older posts).

https://github.com/wordpress-mobile/WordPress-Android/assets/5091503/79db6249-0fb2-41b8-ba0f-8d67b6dce89a

### Steps to reproduce the behavior
1. Install and log into Jetpack
2. Go to the Reader
3. Go to the Discover feed
4. Swipe to refresh the Discover feed
5. Start scrolling the feed (preferably slowly so it's easy to see the issue)
6. When a progress spinner appears on the bottom and the feed jumps back to the first item
7. You can do steps 4-6 several times to see the issue happening consistently

### Initial investigation
It looks like this bug has existed for a while (since 2020 or before), as the culprit code is this one:
https://github.com/wordpress-mobile/WordPress-Android/blob/81060a8036577dac90abf29e483f1d723ca53777/WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverViewModel.kt#L277-L279

It only happens on the Discover Feed, and only happens on the first request for more posts after using the pull-to-refresh, because the way that the loading indicator is shown simply copies the current state (code above) modifying the `loadMoreProgressVisibility` to `true`.

The issue is that the latest UI state for the swipe-to-refresh contains a `scrollToTop` variable that is still `true` (since the last pull to refresh UI state had that set that way [here](https://github.com/wordpress-mobile/WordPress-Android/blob/81060a8036577dac90abf29e483f1d723ca53777/WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverViewModel.kt#L154-L159) with `swipeToRefreshTriggered` being set [here](https://github.com/wordpress-mobile/WordPress-Android/blob/81060a8036577dac90abf29e483f1d723ca53777/WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverViewModel.kt#L507-L513)). 

Also, the `ViewModel` controls the state of that `scrollToTop` using a class field `swipeToRefreshTriggered`, and resets only that field, but not the actual UI state used for refreshing the screen after the pull-to-refresh content is updated [here](https://github.com/wordpress-mobile/WordPress-Android/blob/81060a8036577dac90abf29e483f1d723ca53777/WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverViewModel.kt#L160). So we have those 2 places controlling the same state but not being synchronized properly.

### Fix suggestion
A quick idea for a fix is making sure that whenever the `_uiState` is updated using `.copy` we also set the `scrollToTop` field to the current `swipeToRefreshTriggered` View Model field.

Note this is far from ideal though, since a more proper fix would be to make sure the `_uiState` is the source of truth, also the `scrollToTop` feels more of an `Event` than an actual `State`, so maybe a solution would be making the `scrollToTop` be a separate Event LiveData/Flow that is observed by the UI and is **not** part of the UI State.

### PR DESCRIPTION
**Pull request by thomashorta**
Fixes #19968 

This prevents the stale information of this field from being kept in the `uiState` and being consumed by the UI incorrectly multiple times. An event makes more sense here since we want the action to happen once at a very specific moment, only that event is triggered.

### Demo
_Note: the first flow shown in the video is the correct scroll-to-top behavior that should happen if the user made a swipe-to-refresh but scrolled the list. The second flow (after the swipe-to-refresh load is finished) is the one that was fixed, which was simply scrolling until the point where the feed fetches more posts._

https://github.com/wordpress-mobile/WordPress-Android/assets/5091503/fcd916ba-c0d0-43be-b8b5-455868763756

-----

## To Test:
1. Install and log into Jetpack
2. Go to the Reader
3. Go to the Discover feed
4. Swipe to refresh the Discover feed
5. Start scrolling the feed (preferably slowly)
6. **Verify** the screen doesn't jump to the top when the progress indicator appears on the bottom 
7. You can do steps 4-6 several times to see the original issue doesn't happen anymore

-----

## Regression Notes

1. Potential unintended areas of impact

    - N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - N/A

3. What automated tests I added (or what prevented me from doing so)

    - Add a unit test for the case that was broken before

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WordPress/src/test/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverViewModelTest.kt [hunk 1]
```diff
@@ -628,7 +629,34 @@ class ReaderDiscoverViewModelTest : BaseUnitTest() {
         }
         fakeDiscoverFeed.value = createDummyReaderCardsList()
         // Assert
-        assertThat(uiStates.last().scrollToTop).isFalse
+        assertThat(scrollToTopCounter.count).isZero()
+    }
+
+    @Test
+    fun `Scroll to top is triggered only once when discover feed is updated with load more after swipe to refresh`() =
```
Comment (RenanLukas) [inline WordPress/src/test/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverViewModelTest.kt:636]: 👍

**Review by RenanLukas — APPROVED** [review]
Thanks for the PR, @thomashorta 

It's working as expected and code LGTM :shipit:
