### PR TITLE
Processing screen lock/unlock within a new thread to allow icon downloading

### LINKED ISSUE #4897: Notifications: avatar is not shown when notification is rebuilt
### Expected behavior

When setting WPPin enabled, locking/unlocking the device re-builds notifications to hide/show quick actions. The avatar and icon for the notification should remain unchanged.

### Actual behavior

When setting WPPin enabled, locking/unlocking the device re-builds notifications to hide/show quick actions. In this, the avatar is sometimes lost and replaced by the W logo placeholder.

### Steps to reproduce the behavior
1. Having WPPin enabled, receive a notification from a user that has an avatar configured.
2. Observe the avatar is shown in the notification in the system's dashboard
3. lock the screen and unlock
4. observe the avatar is not shown in the notification anymore

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #4897 

To test:
1. Having WPPin enabled, receive a notification from a user that has an avatar configured.
2. Observe the avatar is shown in the notification in the system's dashboard
3. lock the screen and unlock
4. observe the avatar is not lost and is shown in the notification

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/notifications/ScreenLockUnlockBroadcastReceiver.java [hunk 1]
```diff
@@ -11,13 +11,18 @@
  */
 public class ScreenLockUnlockBroadcastReceiver extends BroadcastReceiver {
     @Override
-    public void onReceive(Context context, Intent intent) {
+    public void onReceive(final Context context, Intent intent) {
         final String action = intent.getAction();
         if (Intent.ACTION_SCREEN_OFF.equals(action) || Intent.ACTION_USER_PRESENT.equals(action)) {
             // only rebuild notifications if WPpin not enabled, notifications don't need be updated
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/notifications/ScreenLockUnlockBroadcastReceiver.java]: Is there a typo in the comment? `if WPpin not enabled` ?

Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/notifications/ScreenLockUnlockBroadcastReceiver.java]: oh that's true!

**Comment by daniloercoli** [comment]
:shipit:
