### PR TITLE
Issue/10370 auto upload error labels

### LINKED ISSUE #10370: Unclear message if a media was not uploaded
This was from https://github.com/wordpress-mobile/WordPress-Android/pull/10319#issuecomment-519909269 and can only be reproduced when using the `master-auto-upload` branch. 

In #10319, we will automatically publish posts if the user has explicitly pressed the _Published_. This now works. However, when a post has pending or failed media uploads, we do not see the “Post will be published next time your device is online” error message as described in https://github.com/wordpress-mobile/WordPress-iOS/issues/12227. We see this instead:

## Steps to reproduce 

1. Go offline.
2. Create a post and add an image. The media should fail to upload.
3. Press the _Publish_ button. The error shown will not be the usual “Post will be published...” error.

- [x] @osullivanchris I'm not sure if we have considered this part. Please let us know if you think it should be done in another way. 

## Decision 2019-Aug-27

This was decided on a Slack conversation. We will limit the retry count to 3. 

- if the post has failed upload (no matter whether it's media or post upload), we'll show "Post couldn't be published. We'll try again later"" and "cancel" action. The text will be yellow and we'll also show grey "Retry" action in case the user wants to invoke the retry manually.

**Media upload error:**

Retry Number | Post List Error/Warning Message | Next automatic action |
--------|-------|---
 0 - 2      |       “Post couldn't be published. We'll try again later” | Auto-publish
 3       |       “Could not upload media. Post not *published.” | Nothing. 

**Post upload error:**

Retry Number | Post List Error/Warning Message | Next automatic action |
--------|-------|---
 0 - 2      |       “Post couldn't be published. We'll try again later"” | Auto-publish
 3       |       “Couldn\'t perform operation. Post not *published.” | Nothing. 

*Published/submitted/saved/scheduled

### PR DESCRIPTION
**Pull request by malinajirka**
Fixes #10370 

- Replaces `getNumberOfPostUploadErrorsOrCancellations` with `getNumberOfPostAutoUploadAttempts`. The `getNumberOfPostUploadErrorsOrCancellations` counter was used as a guard so we don't keep auto-uploading a post indefinitely. However, the counter was incremented whenever a media or post upload failed (even in offline). So if the user added 10 images in offline, the counter would be incremented ten times. Whereas `getNumberOfPostAutoUploadAttempts` is incremented only when the UploadStarter actually initiates the auto-upload. More info https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1366

- Decreases the number of auto-upload attempts to 3 (MAXIMUM_AUTO_UPLOAD_RETRIES)

- Updates the error messages when upload fails as desribed in #10370  - `Decision 2019-Aug-27`

To test:
1. Turn on airplane mode
2. Create a post
3. Add some media files
4. Click on publish
5. Notice "Post couldn't be published. We'll try again later" label is shown. Also notice both Cancel and Retry (under more) buttons are visible. The Label and Cancel button should be yellow.
------
1. Turn on airplane mode
2. Create a post
3. Add some media files
4. Change the post status to pending in Post settings and click on Submit
5. Notice "Post couldn't be submitted. We'll try again later" label is shown. Also notice both Cancel and Retry (under more) buttons are visible. The Label and Cancel button should be yellow.
6. Make the auto-upload fail 3 times (eg. turn the airplane mode off and on)
7. Notice after three attempts the message changes to "Couldn't perform operation. Post not submitted.". The cancel button should disappear and the label and Retry should be red.
------------
1. Create a post while online
2. Add some title and content (no media files)
3. Click on publish
4. Turn on airplane mode before the upload finishes
5. Notice "Post couldn't be published. We'll try again later" label is shown. Also notice both Cancel and Retry (under more) buttons are visible. The Label and Cancel button should be yellow.

Update release notes:

- [ x ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostListUploadStatusTracker.kt [hunk 1]
```diff
@@ -35,19 +31,13 @@ class PostListUploadStatusTracker(
...
                 hasPendingMediaUpload = UploadService.hasPendingMediaUploadsForPost(post),
-                isEligibleForAutoUpload = isEligibleForAutoUpload(siteModel, post)
+                isEligibleForAutoUpload = uploadActionUseCase.isEligibleForAutoUpload(siteModel, post),
+                uploadWillPushChanges = uploadActionUseCase.willUploadPushChanges(post)
         )
         uploadStatusMap[post.id] = newStatus
         return newStatus
     }
 
-    private fun isEligibleForAutoUpload(site: SiteModel, post: PostModel): Boolean {
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/PostListUploadStatusTracker.kt]: Moved to uploadActionUseCase

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadStarter.kt [hunk 2]
```diff
@@ -165,6 +167,7 @@ class UploadStarter @Inject constructor(
                     .toList()
                     .forEach { post ->
                         AppLog.d(AppLog.T.POSTS, "UploadStarter for post title: ${post.title}")
+                        dispatcher.dispatch(UploadActionBuilder.newIncrementNumberOfAutoUploadAttemptsAction(post))
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadStarter.kt]: We want to increment the number of auto upload attempts only at this place - when we actually initiate the auto upload.

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtils.java [hunk 3]
```diff
@@ -86,6 +86,37 @@ UiString getErrorMessageResIdFromPostError(boolean isPage, PostError error) {
             case GENERIC_ERROR:
             default:
                 AppLog.w(T.MAIN, "Error message: " + error.message + " ,Error Type: " + error.type);
+                if (eligibleForAutoUpload) {
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtils.java]: This method is used even in failed upload notification, so I've changed even that. But I think it's actually a bonus.

File: WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt [hunk 4]
```diff
@@ -277,17 +275,38 @@ class PostListItemUiStateHelper @Inject constructor(private val appPrefsWrapper:
...
+
     @ColorRes private fun getStatusesColor(
         postStatus: PostStatus,
         isLocalDraft: Boolean,
         isLocallyChanged: Boolean,
         uploadUiState: PostUploadUiState,
         hasUnhandledConflicts: Boolean
     ): Int? {
-        val isError = uploadUiState is PostUploadUiState.UploadFailed || hasUnhandledConflicts
+        val isError = (uploadUiState is UploadFailed && !uploadUiState.isEligibleForAutoUpload) || hasUnhandledConflicts
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt]: When the upload fails but the post is eligible for auto-upload we want to show a yellow text (not red) as the user doesn't need to take any action and the post will be uploaded later.

File: WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt [hunk 5]
```diff
@@ -314,7 +333,9 @@ class PostListItemUiStateHelper @Inject constructor(private val appPrefsWrapper:
         statsSupported: Boolean
     ): List<PostListButtonType> {
         val canRetryUpload = uploadUiState is PostUploadUiState.UploadFailed
-        val canCancelPendingAutoUpload = uploadUiState is UploadWaitingForConnection && postStatus != DRAFT
+        val canCancelPendingAutoUpload = (uploadUiState is UploadWaitingForConnection ||
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt]: We want to show "cancel" even when there is a failed upload in case the post is eligible for auto-upload.

**Comment by malinajirka** [comment]
@shiki This is now ready for review. Thank you 🙇

**Comment by jkmassel** [comment]
Howdy! The `13.3` code freeze is today, so I'm bumping this to `13.4`. If you'd like it to be part of the `13.3` release, please target the `release/13.3` branch, and DM me once it's merged so that I can include it as a new beta release!

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadStarter.kt (hunk 2 above)
Comment (shiki) [reply WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadStarter.kt]: ⚠️ I don't see this being covered in `UploadStarterTest`. Did I miss it?

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostListUploadStatusTracker.kt [hunk 6]
```diff
@@ -4,10 +4,6 @@ import org.wordpress.android.fluxc.model.PostModel
 import org.wordpress.android.fluxc.model.SiteModel
 import org.wordpress.android.fluxc.store.UploadStore
 import org.wordpress.android.ui.uploads.UploadActionUseCase
-import org.wordpress.android.ui.uploads.UploadActionUseCase.UploadAction.DO_NOTHING
-import org.wordpress.android.ui.uploads.UploadActionUseCase.UploadAction.REMOTE_AUTO_SAVE
-import org.wordpress.android.ui.uploads.UploadActionUseCase.UploadAction.UPLOAD
-import org.wordpress.android.ui.uploads.UploadActionUseCase.UploadAction.UPLOAD_AS_DRAFT
 import org.wordpress.android.ui.uploads.UploadService
 import org.wordpress.android.viewmodel.posts.PostListItemUploadStatus
```
[the remark this answers is not in the document]
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/PostListUploadStatusTracker.kt]: I agree the name `Tracker` is a bit misleading/confusing. Especially since we use `Tracker` suffix for feature specific Tracks/Analytics classes.
I feel like caching statuses in a "Builder" would be confusing as well. Perhaps something like "Provider/Manager/.." -> or create two separate classes `PostListUploadStatusBuilder` and `PostListUploadStatusCache`

>Should we remove that “This is a temporary class” comment?

:D it's still a "temporary" class -> the plan was to refactor it when we have more time, but we never did. I guess we can remove it ;).

File: WordPress/src/main/res/values/strings.xml [hunk 7]
```diff
@@ -1507,6 +1504,25 @@
     <string name="error_unknown_page">Could not find the page on the server</string>
     <string name="error_unknown_post_type">Unknown post format</string>
 
+    <string name="error_media_recover_post">Couldn\'t upload media</string>
+    <string name="error_media_recover_post_not_published">Couldn\'t upload media. Post not published</string>
+    <string name="error_media_recover_post_not_published_private">Couldn\'t upload media. Private post not published</string>
+    <string name="error_media_recover_post_not_scheduled">Couldn\'t upload media. Post not scheduled</string>
+    <string name="error_media_recover_post_not_submitted">Couldn\'t upload media. Post not submitted</string>
+    <string name="error_media_recover_post_not_published_retrying" translatable="false">@string/error_post_not_published_retrying</string>
```
[the remark this answers is not in the document]
Comment (malinajirka) [reply WordPress/src/main/res/values/strings.xml]: >Now we just need real namespaces in resource files. 😉

💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostListUploadStatusTracker.kt (hunk 6 above)
[the remark this answers is not in the document]
Comment (shiki) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/PostListUploadStatusTracker.kt]: If it's still temporary, we can hold off renaming it and making more changes. 🙂

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadActionUseCase.kt [hunk 8]
```diff
@@ -74,4 +74,13 @@ class UploadActionUseCase @Inject constructor(
...
     }
+
+    fun isEligibleForAutoUpload(site: SiteModel, post: PostModel): Boolean {
+        return when (getAutoUploadAction(post, site)) {
+            UPLOAD -> true
+            UPLOAD_AS_DRAFT, REMOTE_AUTO_SAVE, DO_NOTHING -> false
+        }
+    }
+
+    fun uploadWillPushChanges(post: PostModel) = post.changesConfirmedContentHashcode == post.contentHashcode()
```
[the remark this answers is not in the document]
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadActionUseCase.kt]: We decided to keep it as it is (at least for now).

**Comment by malinajirka** [comment]
Thanks @shiki !!! ;) I added the missing unit test and replied to your comments.
