### PR TITLE
Only show failure/success notifications for actions triggered from within the NotificationsProcessingService

### LINKED ISSUE #8947: After spamming comment app notifies "comment successfully approved!"
### Expected behavior
After I spam a comment via the app, I expect that if I get a notification, it would read "Comment successfully spammed"

### Actual behavior
After spamming a comment via the app, I get a notification that the comment was successfully approved. It hasn't been (fortunately).

### Steps to reproduce the behavior
Open app, navigate to Notifications.
Open a comment notification
Tap on Spam
Close the app or otherwise carry on with your day, and await the notification.

##### Tested on [device], Android [version]
App version: alpha-144
Moto x4 running Android 9 Pie

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #8947

Comes from https://github.com/wordpress-mobile/WordPress-Android/issues/8947#issuecomment-486267765

#### Analysis
The only place where `Comment approved!` message notification is shown in code is (supposedly) when a notification's quick action has been triggered and [has completed](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java#L397).
I can think of the following situation as a possible case:
If the `NotificationsProcessingService` (used mainly for notifications quick actions processing) is running, which also means the class has been [registered with FluxC's dispatcher](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java#L148) and as such [`onCommentChanged()` subscription callback gets called not only for actions triggered from the service but also for any kind of actions on the FluxC database](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java#L620). If the network is slow enough, this could mean something you do to [moderate (approve/spam) a comment on the app's Notifications tab](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/comments/CommentsListFragment.java#L529), after already having approved a comment as a quick action, will also get collected by the registered callback.
Furthermore, the callback assumes there are only effectively `like/reply/approve`  actions (as that's the design for quick actions), and maps [a successful FluxC level action `CommentAction.PUSH_COMMENT` to be equal to approving](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java#L624-L629), when it might actually not be the case.
Hence, tapping on a quick action and then opening the app while the action is taking place, and spaming something there can lead to this situation. Difficult to reproduce, but still plausible. There are still other reasons why the Service could still exist in memory even if not really running, and given it hasn't been destroyed it will still be "listening" to FluxC events, producing these notifications as well.

#### Solution
Been looking into FluxC's code to see if we can match the API responses to which notifications quick action triggered them, and it seems we do have `event.changedCommentsLocalIds` in the response's payload, so in theory it should suffice to be able to compare triggered actions and responses by their Comment's local ids to make sense of what to notify the user about and what not (that is, for the time being, we should only produce notifications for quick action buttons-triggered actions within the `NotificationsProcessingService`, and none in particular for handling those that are triggered from the app's main screens).

To test:

TEST A:
This test goes through the code path that compares Comment ids to make sure it needs to show the success notification for comment moderation (approval)
1. create 2 comment notification (make comments that should need approval - make the user a Contributor and go to site settings -> Discussion -> check "Comment must be manually approved")
2. dismiss one of the notifications, this will provoke the Service to get created (because of the notification dismiss PEndingIntent) and make the Service registered to FluxC
3. now, tap on the APPROVE notification quick action for the remaining notification
4. observe the comment gets approved and a final success notification is shown "Comment approved!"

TEST B:
This test goes through the same path as TEST A, but makes sure the action is _not_ from a quick action
1. create 2 comment notification (make comments that should need approval)
2. dismiss one of the notifications, this will provoke the Service to get created (because of the notification dismiss PEndingIntent) and make the Service registered to FluxC
3. now, open the app on the Notifications tab screen
4. open the any comment
5. mark it as spam
6. observe the there is no "Comment approved!" successnotification

TEST C:
This test goes through a different path that doesn't test moderation
1. create 2 comment notification (make comments that should NOT need approval, so the LIKE quick action is shown).
2. dismiss one of the notifications, this will provoke the Service to get created (because of the notification dismiss PEndingIntent) and make the Service registered to FluxC
3. now, tap on the LIKE notification quick action for the remaining notification
4. observe the comment gets liked without a problem.

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by mzorz** [comment]
This one is now ready for review when you have time @daniloercoli  🙇 
I've slightly changed the steps to reproduce to make sure the Service is running before marking with Spam, and going through the different parts changed as well 👍

File: WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java [hunk 1]
```diff
@@ -554,6 +563,10 @@ private void approveComment() {
                 return;
             }
 
+            // keep the local CommentId, we'll use it later to know whether to trigger the end processing notification
+            // or not
+            keepRemoteCommentIdForPostProcessing(comment.getRemoteCommentId());
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java]: Should we move this call in `performRequestedAction` to be sure to catch comment like and other quick actions that may generate notifications?

File: WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java [hunk 2]
```diff
@@ -621,11 +634,29 @@ public void onCommentChanged(OnCommentChanged event) {
...
+                    for (Integer commentLocalId : event.changedCommentsLocalIds) {
+                        CommentModel localComment = mCommentStore.getCommentByLocalId(commentLocalId);
+                        if (localComment != null) {
+                            if (mActionedCommentsRemoteIds.contains(localComment.getRemoteCommentId())) {
+                                containedCount++;
+                            }
+                        }
+                    }
+
+                    if (containedCount != mActionedCommentsRemoteIds.size()) {
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java]: Not quite sure this will work fine when there are multiple quick actions ongoing in background.
What does happen when ` event.changedCommentsLocalIds` is a list that only contains the ID of the first comment being moderated?

File: WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java (hunk 1 above)
Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java]: I was using it like that (added the `keepRemoteCommentIdForPostProcessing()` call in all 3 possible actions in the Service) but then decided to leave it only for the FluxC `PUSH` action as it was where the reported case was happening, but I think you're right, we should move it back and make it work for all cases. Will do and comment back here 👍

**Comment by mzorz** [comment]
Addressed https://github.com/wordpress-mobile/WordPress-Android/pull/9710/files#r278892334 by making a list of comparable `remoteIds` when the action is about to be dispatched and looking into the `event.changedCommensLocalIds` later on in the FluxC callback (converting it to remote Id to be able to compare).

Re: this https://github.com/wordpress-mobile/WordPress-Android/pull/9710/files#r278890934 other suggestion to treat all quick actions with this same approach, I've been investigating and even tried the approach in commit 5d016b4, but it wasn't really feasible in the current state of FluxC, I'll explain below:

Turned out, `LIKE`-type events don't carry the `changedCommentsLocalIds` property filled out in the event, and a `REPLY` quick action will generate a new comment (`CREATE_NEW_COMMENT`) with a new id that we didn't know of before so, we can't match those as well (been looking into `CommentModel.getRemoteParentCommentId()` but it seems to be always zero as per my tests).

For now I think we should just treat `APPROVE` with this code as that's  as far as it can go (and what has appeared as problematic as per the issue described). The secondary behavior that results from not treating LIKE and REPLY likewise is that, in the case the service is running, and the user taps on LIKE on the Notification detail Activity or Replies to a Comment, they will get an extra success / error notification when the action is finished (depending on whether their action was successful or not). I think that's acceptable, what do you think @daniloercoli ?

If we wanted to make it all work, I think we could potentially make `changedCommentsLocalIds` be populated for LIKE-type events in FluxC, as well as figure out a way to match the corresponding parent Comment, but this sounds like is going out of the extent of fixing the issue in particular maybe?

If that's fine for you, then this should be ready for another round. Thanks in advance @daniloercoli !

**Comment by daniloercoli** [comment]
>  I think that's acceptable, what do you think @daniloercoli ?

Sure, let's make this merged! :shipit:

**Comment by mzorz** [comment]
Thank you @daniloercoli ! 🙇
