### PR TITLE
Issue/6957 image delete shows error

### LINKED ISSUE #6957: Aztec / media: deleting an image triggers an error notification (it shouldn't)
### Expected behavior
Deleting an image in the Aztec Editor should be allowed and the progress notification either decremented or dismissed if only 1 image being uploaded.

### Actual behavior
When an image that is being uploaded is deleted (using backspace) in the Editor, an error notification reading "1 file not uploaded" is shown, when it shouldn't be shown because it was actively deleted by the uer.

### Steps to reproduce the behavior
1. Start a draft with a video, 
2. while its being uploaded, delete it from aztec by positioning the cursor on the right of the image and hit BACKSPACE.
3. See the error notification says “1 file not uploaded”. It shouldn’t show an error, as it was deleted by the user.

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #6957 

While fixing this specific case, I realized some things were not being worked out correctly in the background (i.e. some associations between Media and Posts were being left even when no visible glitch was shown to the user).

These are the test cases:

TEST CASE A: force close the app while in the Editor
1. start a draft
2. include an image/video
3. while it’s uploading, and without exiting the editor, force close the app
4. restart the app and check the image is there and can be retried.
 

TEST CASE B (purge):
1. start a draft
2. include image
3. delete it, wait for autosave to save the post
4. restart the app
5. check that the image is not there anymore as per autosave
6. also check the purge is run upon opening the Editor, deleting the association for the previous media associated to the Post.

TEST CASE C: notification should not appear anymore (this is the specific fix for #6957)
1. start a draft
2. include image
3. while it’s uploading, delete it.
4. observe the progress notification is gone, and the error notification doesn’t appear.

TEST CASE D: error notification appears when an external cause makes the upload fail
1. start a draft
2. include image
3. while it’s uploading, turn airplane mode ON
4. observe the progress notification is gone, and the error notification appears.

TEST CASE E: reattachment wasn't working if the RETRY quick action is tapped, after having an errored image upload within the Editor.
1. start a draft
2. include image
3. while its uploading, turn airplane mode ON/OFF to make it fail and make the error notification appear.
4. without exiting the editor, tap on the RETRY quick action in the error notification
5. note that the image overlay and progress gets reattached in the Editor.

cc @daniloercoli

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java [hunk 1]
```diff
@@ -433,6 +437,38 @@ private void initializePostObject() {
...
+    private void purgeMediaToPostAssociationsIfNotInPostAnymore() {
+        ArrayList<MediaModel> allMedia = new ArrayList<>();
+        Set<MediaModel> failedMedia = mUploadStore.getFailedMediaForPost(mPost);
+        Set<MediaModel> completedMedia = mUploadStore.getCompletedMediaForPost(mPost);
+        Set<MediaModel> uploadingMedia = mUploadStore.getUploadingMediaForPost(mPost);
+        allMedia.addAll(failedMedia);
+        allMedia.addAll(completedMedia);
+        allMedia.addAll(uploadingMedia);
+
+        if (allMedia != null && !allMedia.isEmpty()) {
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: Niptick - `allMedia` cannot be `null` here.

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java [hunk 2]
```diff
@@ -212,6 +204,26 @@ private void unpackMediaIntent(@NonNull Intent intent) {
         }
     }
 
+    private void registerPostModelsForMedia(List<MediaModel> mediaList, boolean isRetry) {
+        if (mediaList != null && !mediaList.isEmpty()) {
+            Set<PostModel> postsToRefresh = PostUtils.getPostsThatIncludeThisMedia(mPostStore, mediaList);
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java]: `PostUtils.getPostsThatIncludeThisMedia(mPostStore, mediaList)` - Should we rename this function?
From the name of the function it seems to me that it gets a single media in input, instead it's a list of media.

Checking the code of it, it adds posts that contain at least one media available in the list.

Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java]: Good call, renamed method to `getPostsThatIncludeAnyOfTheseMedia` in 40566eb

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java (hunk 1 above)
Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: 👍 removed unnecessary check in cb62466

**Comment by daniloercoli** [comment]
While testing this PR I found an issue with the text in the error notification. It seems that the 
 notification says that the number of posts failed are equals to the number of media added to the single post I was creating. See below:
- Started a new post
- Added 9 media to the post
- Waited in the editor while some of them are uploaded
- Exited the editor and the app
- Turned Wifi off (no data on the device)
- Got the following error notification (see the wording)
screenshot_2018-01-11-12-59-31


- Turned WiFi ON again
- Tap on the "Retry" button in the notification
- Got the following notification with the correct wording
screenshot_2018-01-11-13-01-25

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java [hunk 3]
```diff
@@ -433,6 +437,38 @@ private void initializePostObject() {
...
+    }
+
+    private void purgeMediaToPostAssociationsIfNotInPostAnymore() {
+        ArrayList<MediaModel> allMedia = new ArrayList<>();
+        Set<MediaModel> failedMedia = mUploadStore.getFailedMediaForPost(mPost);
+        Set<MediaModel> completedMedia = mUploadStore.getCompletedMediaForPost(mPost);
+        Set<MediaModel> uploadingMedia = mUploadStore.getUploadingMediaForPost(mPost);
+        allMedia.addAll(failedMedia);
+        allMedia.addAll(completedMedia);
+        allMedia.addAll(uploadingMedia);
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: What do you think if we just add those sets to `allMedia` without introducing 3 variables?

Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: nice - made the change in 750a385

**Comment by mzorz** [comment]
> While testing this PR I found an issue with the text in the error notification. It seems that the
notification says that the number of posts failed are equals to the number of media added to the single post I was creating. 

🤕 sorry for that! I was effectively incrementing the counter for each new media item - addressed in 1986a09

**Comment by mzorz** [comment]
Been testing this a bit as I thought I found a possible problem of duplicate posts, but realized it has nothing to do with this PR in particular (I was running in the condition when a new Post payload is sent to the server, but the answer from it is lost before we can read it, thus effectively retrying the Post ends up generating a new Post with the same content, hence the duplication- quite a corner case).

That said, this is good for another pass @daniloercoli 👍

**Comment by daniloercoli** [comment]
It seems that the are still problems with the uploading and errors notifications in case of failures when a post is sent to server. 
Steps to repro:
- Create a new post with Media
- Close the editor
- There is the uploading in progress notification in the notification center
- Put the device in Airplane mode
- There are now 2 notifications for the same post:
screenshot_20180112-110649
- Turn the device on line again
- The app finishes the uploading of the post without issue
- But the error notification is still there
screenshot_20180112-110732

**Comment by daniloercoli** [comment]
As per chat convo we're opening a new ticket for my latest comment since it's not related to this PR.
