### PR TITLE
[Reader] Fix IllegalStateException in ReaderPostListFragment

### LINKED ISSUE #20228: IllegalStateException: Fragment ReaderPostListFragment{bc6bf07} (280f24d9-396c-4b35-8ad0-22c50360a20f) not attached to a...
Sentry Issue: [JETPACK-ANDROID-JMJ](https://a8c.sentry.io/issues/4999358916/?referrer=github_integration)

```
IllegalStateException: Fragment ReaderPostListFragment{bc6bf07} (280f24d9-396c-4b35-8ad0-22c50360a20f) not attached to an activity.
    at androidx.fragment.app.Fragment.requireActivity(Fragment.java:1000)
    at org.wordpress.android.ui.reader.ReaderPostListFragment$11.run(ReaderPostListFragment.java:2322)
```

### PR DESCRIPTION
**Pull request by daniloercoli**
Fixes #20228

I was unable to reproduce the problem, and the occurrences of it ([JETPACK-ANDROID-JMJ](https://a8c.sentry.io/issues/4999358916/?referrer=github_integration)) are very low. Ensuring that the Fragment is still attached to the Activity in onResume should fix the problem.

-----

## To Test:

* Smoke test the Reader.

-----

## PR Submission Checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by RenanLukas — APPROVED** [review]
Thanks for the PR, @daniloercoli . LGTM :shipit:

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java [hunk 1]
```diff
@@ -745,6 +745,9 @@ public void onPause() {
     @Override
     public void onResume() {
         super.onResume();
+        if (!isAdded() || getView() == null) {
```
Comment (thomashorta) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java]: I don't think this will help though, it looks like the line that's crashing is [line 2322 here](https://github.com/wordpress-mobile/WordPress-Android/blob/7295f27fe546883d1f043addef8ec6f5e43c6a7a/WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java#L2322), according to the stack trace of the crash:
```
java.lang.IllegalStateException: Fragment ReaderPostListFragment{b2c45df} (12cf4b19-e069-4888-ab5a-911d5ed99a51) not attached to an activity.
    at androidx.fragment.app.Fragment.requireActivity(Fragment.java:1000)
    at org.wordpress.android.ui.reader.ReaderPostListFragment$11.run(ReaderPostListFragment.java:2322)
```

If you look a couple of lines above the crashing line you will see that a similar check is already being made and even then the crash happened to a few users. I guess that, since the code is being run asynchronously, it might have been delayed enough that when line 2322 is reached the Fragment is no longer attached.

If that's indeed the case, we probably shouldn't be using `requireActivity` there, but instead just get the activity and only run the code **if** it is not null, since being null should mean that Fragment is no longer attached so that update is no longer needed anyway. Wdyt?

**Review by thomashorta — CHANGES_REQUESTED** [review]
I'm marking it a "change requested" because I don't think this addresses the root cause and will also not fix the crash, see my comment in the code.

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java [hunk 2]
```diff
@@ -2320,10 +2321,15 @@ private void updateCurrentTagIfTime() {
         new Thread() {
             @Override
             public void run() {
+                // Check the fragment is attached to the activity when this Thread starts.
+                FragmentActivity activity = getActivity();
+                if (activity == null) {
```
Comment (thomashorta) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java]: 💡 I think doing the check here still has a great chance of not solving the crash, since the function that probably takes the most time to run is `shouldAutoUpdateTag`. This means that even with this check here, when the code reaches line 2330 or 2332 the fragment might already be dettached anyway, which will likely yield other issues.

Because of that, I think it would be better if the check is done in each of the if clause's blocks (before line 2330 and line 2332) below.

I know the code will look a bit repetitive, but since we're working with Java here, there's not much way around it. 😞

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java (hunk 1 above)
Comment (daniloercoli) [reply WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java]: Thank you for your suggestions 🙇 . I've made the adjustments as recommended, although it resulted in about 4 isAdded checks and 2 getActivity() != null conditions within a few lines of code. 😵‍💫 

Side note: I believe the bottleneck isn't the `shouldAutoUpdateTag` function itself, but rather the delay in starting the thread, likely due to many other threads running concurrently to update the Reader in the background.

Regardless, we should have significantly reduced the likelihood of the crash occurring now.

**Review by thomashorta — APPROVED** [review]
Looks good to me! Thanks! 🙇🏼
