### PR TITLE
Fixed VM context and empty field focus issue.

### LINKED ISSUE #10241: Domain Registration: cannot select Country or State in the "Domain contact information" form
Steps to reproduce:

1. Select a site with a Personal or Premium plan with an unused domain credit.
1. Tap "Register Domain".
1. Search for and select a domain.
1. Select the "Register privately with Privacy Protection" option.
1. In the "Domain contact information form", try to select a "Country".
1. In the "Domain contact information form", try to select a "State".

<strong>Result:</strong> none of the dropdown fields in the "Domain contact information form" are letting me set a value and I am blocked from completing the form using the "Register Domain" button. (<a href="https://cloudup.com/cBR7fwfM9V8">2m32s</a>)

**Note:** sometimes these fields are pre-filled, you may need to do a brand new sign up and use an account that has never been used to register a domain before in order to get a clean slate for testing this form.

register-privately-with-privacy-protection domain-contact-information-form-select-country
<sup>Tested with WPAndroid alpha-180 (12.9 alpha) on Pixel 3 Android 9.</sup>

### LINKED ISSUE #10242: Domain Registration: cannot see off-screen form errors when there are missing required fields in the "Domain contact information form"
Steps to reproduce:

1. Select a site with a Personal or Premium plan with an unused domain credit.
1. Tap "Register Domain".
1. Search for and select a domain.
1. Select the "Register privately with Privacy Protection" option.
1. In the "Domain contact information form", skip the Phone field.
1. Fill out the rest of the form and tap the "Register Domain" button.

<strong>Result:</strong> if there are any problems in the form and I tap the "Register Domain" button at the bottom of the form, I am not scrolled up to see that there were errors and no feedback is given about the form errors so it's hard to tell what's wrong. ([27s](https://cloudup.com/cjBhyP7HCyC))

register-domain-form-with-off-screen-errors
<sup>Tested with WPAndroid alpha-180 (12.9 alpha) on Pixel 3 Android 9.</sup>

### PR DESCRIPTION
**Pull request by khaykov**
Fixes #10242
Fixes #10241

Fixing provider of domain registration ViewModel and adding focusing for empty fields.

To test:
- Switch to a site with unredeemed domain credit.
- Tap on domain registration CTA, pick a domain name and proceed to domain contact details forms.
- Make sure country and state selectors are working (selected country or state is reflected in form).
- Clear "First Name" field, scroll to the bottom of the form and make sure soft keyboard is visible (tap on postal code field, for example).
- Press "Register Domain" button, and notice that form is focused on "First Name" field and error is displayed.

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationDetailsFragment.kt [hunk 1]
```diff
@@ -86,7 +86,7 @@ class DomainRegistrationDetailsFragment : Fragment() {
 
         mainViewModel = ViewModelProviders.of(activity!!, viewModelFactory)
                 .get(DomainRegistrationMainViewModel::class.java)
-        viewModel = ViewModelProviders.of(this, viewModelFactory)
+        viewModel = ViewModelProviders.of(activity!!, viewModelFactory)
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationDetailsFragment.kt]: Can you please elaborate why we need to make this change. We might want to consider adding a comment into the code as it's not a usual practice.

Note:
I feel like this viewModel should be tied to the lifecycle of the fragment and not the lifecycle of the activity. It shouldn't be an issue in most cases, but could be. We could consider replacing `activity` with `targetFragment` [here](https://github.com/wordpress-mobile/WordPress-Android/blob/21f1484cf40df0f8129a991dcf586f7d7188b0de/WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationDetailsFragment.kt#L480) and [here](https://github.com/wordpress-mobile/WordPress-Android/blob/21f1484cf40df0f8129a991dcf586f7d7188b0de/WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationDetailsFragment.kt#L434). Would that work?
Wdyt?

File: WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationDetailsFragment.kt [hunk 2]
```diff
@@ -293,15 +293,23 @@ class DomainRegistrationDetailsFragment : Fragment() {
                 country_input, address_first_line_input, city_input, postal_code_input
         )
 
+        var fieldToFocusOn: TextInputEditText? = null
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationDetailsFragment.kt]: Just note: Ideally this business logic would be encapsulated in the VM so it can be tested. However, let's not refactor it in this PR as the number of changes would be significant.

File: WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationDetailsFragment.kt (hunk 1 above)
Comment (khaykov) [reply WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationDetailsFragment.kt]: Yes, the reason you mentioned is the one :)

I replaced `activity` with `targetFragment`.
