### PR TITLE
issue/6694 Sharing does not continue after login

### LINKED ISSUE #6694: Sharing does not continue after login
### Expected behavior
Precondition - User is not logged into WordPress

1. User shares an image/video/text with WordPress.
2. Login flow is shown
3. When the user logs in, the sharing flow continues.

### Actual behavior
1. User shares an image/video/text with WordPress.
2. Login flow is shown along with an error toast message.
3. When the user logs in, the sharing flow **doesn't** continue. 
4. The Main screen is displayed.

### Steps to reproduce the behavior
1. Clear app data.
2. Share image/video/text with WordPress app.
3. The app redirects you to the Login screen and displays an error message - "No WordPress account found, add an account and try again".
4. Log in.
5. The app doesn't continue with the sharing flow and displays the Main screen.

### PR DESCRIPTION
**Pull request by malinajirka**
Fixes #6694 - Add support for login while sharing to WordPress

To test:
With the app data cleared, try to share a photo to WordPress from the device's gallery. The app should let you log in and continue with the sharing action.

### CODE REVIEW

**Comment by malinajirka** [comment]
@hypest Take a look at this PR please.

**Comment by hypest** [comment]
There is an ongoing discussion about how to implement a post-login experience when sharing-to-wordpress so, perhaps we can delay reviewing this PR for now. Is that OK @malinajirka ? Thanks!

**Comment by malinajirka** [comment]
This is the first iteration. It adds support for login while sharing, but it still uses the old Dialog window. It's up to you @hypest.

**Comment by hypest** [comment]
I think that at this stage, this PR offers too little value to be merged on its own, especially since we now have a better idea how the feature will proceed (discussions over P2s) so, I'd prefer if this PR is worked on some more to become more complete.

By the way, the description (`MasterIssue #5814`) is too broad as it is. Can you please create a ticket with more expanded information of what is the issue/feature this PR would be a solution to? Then use that ticket as the "Fixes" reference. Thanks!

**Comment by malinajirka** [comment]
@hypest Would you please give me a feedback. Thanks
P.S. I can't test other than 'site' login (because of the dummy oauth keys). However, I tried to mock the data and everything worked as expected.

**Comment by hypest** [comment]
I'll have a look @malinajirka , thanks!

In the meantime, I've added the `Needs Design Review" label since there are some UI/flow changes and it's better to have a designer's eye on it too.

**Comment by malinajirka** [comment]
> In the meantime, I've added the `Needs Design Review" label since there are some UI/flow changes and it's better to have a designer's eye on it too.

Great, should I take and upload some screenshots? Or do you have an "Automattic :)" CI to build and upload the apk somewhere where testers can access it?

**Comment by hypest** [comment]
We use BuddyBuild to auto-generate APKs from time to time but it's not enabled for this PR. I'm sure screenshots of what have changed will be appreciated! Thanks!

**Comment by malinajirka** [comment]
:) Ok, I'll upload some screenshots in about 3 hours.

File: WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java [hunk 1]
```diff
@@ -352,6 +350,18 @@ public static void loginForDeeplink(Activity activity) {
         activity.startActivityForResult(intent, RequestCodes.DO_LOGIN);
     }
 
+    public static void loginForShareIntent(Activity activity) {
+        if (AppPrefs.isLoginWizardStyleActivated()) {
+            Intent intent = new Intent(activity, LoginActivity.class);
+            LoginMode.SHARE_INTENT.putInto(intent);
```
Comment (hypest) [inline WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java]: I'm under the impression that this flow allows the magiclink login to happen, which by its nature breaks the continuation of the Sharing action after login. What do you think?

File: WordPress/src/main/res/layout/share_intent_sites_listitem.xml [hunk 2]
```diff
@@ -0,0 +1,62 @@
...
+      style="@style/TextAppearance.AppCompat.Caption"
+      android:id="@+id/text_domain"
+      android:layout_width="wrap_content"
+      android:layout_height="wrap_content"
+      android:ellipsize="end"
+      android:maxLines="1"
+      tools:text="text_domain" />
+  </LinearLayout>
+
+  <RadioButton
```
[the remark this answers is not in the document]
Comment (malinajirka) [reply WordPress/src/main/res/layout/share_intent_sites_listitem.xml]: Fixed

File: WordPress/src/main/res/layout/share_intent_sites_listitem.xml [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+    android:id="@+id/radio_selected"
+    android:layout_width="wrap_content"
+    android:layout_alignParentRight="true"
+    android:visibility="gone"
+    android:clickable="false"
+    android:focusableInTouchMode="false"
+    android:layout_centerVertical="true"
+    android:layout_height="wrap_content" />
```
[the remark this answers is not in the document]
Comment (malinajirka) [reply WordPress/src/main/res/layout/share_intent_sites_listitem.xml]: Fixed

File: WordPress/src/main/res/values/strings.xml [hunk 4]
```diff
@@ -1928,6 +1930,7 @@
     <string name="login_checking_site_address">Checking site address</string>
     <string name="login_error_while_adding_site">Error while adding site. Error code: %s</string>
     <string name="login_log_in_for_deeplink">Log in to WordPress.com to access the post.</string>
+    <string name="login_log_in_for_share_intent">Log in to WordPress.com to share the content.</string>
```
[the remark this answers is not in the document]
Comment (malinajirka) [reply WordPress/src/main/res/values/strings.xml]: Sounds good:).

File: WordPress/src/main/res/values/styles.xml [hunk 5]
```diff
@@ -678,4 +678,25 @@
         <item name="android:maxHeight">8dip</item>
     </style>
 
+  <!--Share intent styles-->
```
[the remark this answers is not in the document]
Comment (malinajirka) [reply WordPress/src/main/res/values/styles.xml]: I didn't want to use the LoginTheme in a non-login flow. That was one of the reasons why I created the new layout files. But if it's ok to reuse the LoginTheme, I can pretty much reuse most of the layout files from the epilogue screen.... Just an idea -> wouldn't be better to rename the LoginTheme to something more generic/reusable?

File: WordPress/src/main/res/layout/share_intent_header.xml [hunk 6]
```diff
@@ -0,0 +1,83 @@
+<?xml version="1.0" encoding="utf-8"?>
+<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
```
[the remark this answers is not in the document]
Comment (malinajirka) [reply WordPress/src/main/res/layout/share_intent_header.xml]: Same reason - I didn't want to use a "login" layout in a non login flow.

File: WordPress/src/main/res/layout/share_intent_fragment.xml [hunk 7]
```diff
@@ -0,0 +1,45 @@
+<?xml version="1.0" encoding="utf-8"?>
+<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
```
[the remark this answers is not in the document]
Comment (malinajirka) [reply WordPress/src/main/res/layout/share_intent_fragment.xml]: Same reason - I didn't want to use a "login" layout in a non login flow.

File: WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java (hunk 1 above)
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java]: Ohh, very good point! I haven't realized that.

**Comment by malinajirka** [comment]
Thank you for the feedback!! :) I fixed all the issues you pointed out. I'm really glad you noticed that the normal operation of the SitePickerAdapter is broken. Good job!

I'll push the code tomorrow. I'm about to go AFK and I want to test it one more time.
Thanks!

**Comment by malinajirka** [comment]
sharingflow
I've just pushed the updated code. Thank you @hypest for taking a look.

File: WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerAdapter.java [hunk 8]
```diff
@@ -35,6 +37,8 @@
 
 public class SitePickerAdapter extends RecyclerView.Adapter<RecyclerView.ViewHolder> {
 
+    private static final int NOT_DEF = -1;
```
Comment (hypest) [inline WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerAdapter.java]: I can't say I'm fond of how this constant is used. It seems it appears in at least 3 instances that are totally unrelated to each other:
1. As an indication that the UI is not initialised yet [here](https://github.com/malinajirka/WordPress-Android/blob/152af75eced32ad80ca9f755f47de235551e4c15/WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerAdapter.java#L294)
2. As the indicator when a list can't find an item [here](https://github.com/malinajirka/WordPress-Android/blob/152af75eced32ad80ca9f755f47de235551e4c15/WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerAdapter.java#L333)
3. As the indicator an item is `less than` another when sorting the sites [here](https://github.com/malinajirka/WordPress-Android/blob/152af75eced32ad80ca9f755f47de235551e4c15/WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerAdapter.java#L577)

I can be wrong but, I think that the use of `-1` in all these cases is circumstantial and putting it behind a common constant is confusing and can lead to subtle bugs if the value changes.

Here's what I would recommend instead:
1. Use the numeral (`-1`) directly for the "item not found" and "item comparison" cases. `-1` is normally expected in such APIs as per the documentation. Defining a new constant on top of this probably makes it less clear.
2. Don't rely on a special value (`-1) for an integer variable to denote UI state. Make `mSelectedItemPos` zero-based and holding the position of the selected item _in the dataset_. The initial value (zero) is a valid and expected initial selection anyway. Let me know if this is not clear and I can expand. Thanks!

File: WordPress/src/main/res/values/strings.xml [hunk 9]
```diff
@@ -1920,6 +1922,7 @@
     <string name="login_already_logged_in_wpcom">Already logged in to WordPress.com</string>
     <string name="login_username_at">\@%s</string>
     <string name="enter_site_address">Enter the address of your WordPress site you\'d like to connect.</string>
+    <string name="enter_site_address_share_intent">Enter the address of your WordPress site you\'d like to share the content to</string>
```
Comment (hypest) [inline WordPress/src/main/res/values/strings.xml]: Let's add a final period `.` to this string to match its sibling (`enter_site_address`). Thanks!

File: WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverFragment.java [hunk 10]
```diff
@@ -0,0 +1,242 @@
...
+        holder.mMySitesHeadingTextView.setText(R.string.share_intent_pick_site);
+        holder.mMySitesHeadingTextView.setVisibility(View.VISIBLE);
+    }
+
+    enum ShareAction {
+        SHARE_TO_POST(1, "new_post", EditPostActivity.class), SHARE_TO_MEDIA_LIBRARY(2, "media_library",
+            MediaBrowserActivity.class);
+
+        public final Class targetClass;
+        public final int id;
```
[the remark this answers is not in the document]
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverFragment.java]: I prefer using a custom field for enum identifier over ordinal/name because it's safe in all use-cases. 
* Ordinal is very tricky since the identifier can change when you swap two enum constants.
* Name is a bit tricky as well because it changes the id when you rename the enum constant.

On the other hand in this specific use-case, it doesn't really matter. It's just an internal representation and it's never stored into persistent storage or provided to another system. 

I'll use the name/valueof directly:).

File: WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverFragment.java [hunk 11]
```diff
@@ -0,0 +1,242 @@
...
+        if (!isAdded()) {
+            return;
+        }
+        holder.update(getContext(), holder, mAfterLogin && mAccountStore.hasAccessToken(), mAccountStore.getAccount());
+        holder.mMySitesHeadingTextView.setText(R.string.share_intent_pick_site);
+        holder.mMySitesHeadingTextView.setVisibility(View.VISIBLE);
+    }
+
+    enum ShareAction {
+        SHARE_TO_POST(1, "new_post", EditPostActivity.class), SHARE_TO_MEDIA_LIBRARY(2, "media_library",
```
[the remark this answers is not in the document]
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverFragment.java]: Yes, it's better. :) Done

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java [hunk 12]
```diff
@@ -145,6 +146,8 @@ private void loggedInAndFinish(ArrayList<Integer> oldSitesIds) {
             case WPCOM_REAUTHENTICATE:
                 ActivityLauncher.showLoginEpilogueForResult(this, true, oldSitesIds);
                 break;
+            case SHARE_INTENT:
+                // skip the epilogue when sharing to WordPress
```
[the remark this answers is not in the document]
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java]: Fixed

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginEpilogueFragment.java [hunk 13]
```diff
@@ -149,15 +149,15 @@ private SitePickerAdapter getAdapter() {
...
-    private class HeaderViewHolder extends RecyclerView.ViewHolder {
-        private final View mLoggedInAsHeading;
-        private final View mUserDetailsCard;
-        private final WPNetworkImageView mAvatarImageView;
-        private final TextView mDisplayNameTextView;
-        private final TextView mUsernameTextView;
-        private final TextView mMySitesHeadingTextView;
-
-        HeaderViewHolder(View view) {
+    public static class HeaderViewHolder extends RecyclerView.ViewHolder {
```
[the remark this answers is not in the document]
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginEpilogueFragment.java]: Good point:).

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginEpilogueFragment.java [hunk 14]
```diff
@@ -166,6 +166,34 @@ private SitePickerAdapter getAdapter() {
             mUsernameTextView = (TextView) view.findViewById(R.id.username);
             mMySitesHeadingTextView = (TextView) view.findViewById(R.id.my_sites_heading);
         }
+
+        public void update(Context context, HeaderViewHolder holder, boolean showHeader, AccountModel defaultAccount) {
+            if (showHeader) {
```
[the remark this answers is not in the document]
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginEpilogueFragment.java]: The mMySitesHeadingTextView needs to be part of the ViewHolder/header in order to scroll along with the 'logged in as' section.

Creating a new ViewHolder and a layout for the 'logged in as' section and second layout which includes 'logged in as' section and adds mMySitesHeadingTextView seems like a huge overkill.

I could wrap 'logged in as' section into a layout and show/hide just the layout. It would save 2 lines in the java code, but add a needless layout to the xml.

Am I missing something?:) 

I divided the showHeader parameter into hasAccessToken and isAfterLogin parameters. The naming was very confusing. Nevertheless, I'll be happy to improve the code more if you clarify your thoughts. Thanks @hypest!

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginSiteAddressFragment.java [hunk 15]
```diff
@@ -80,7 +77,14 @@
 
     @Override
     protected void setupLabel(TextView label) {
-        label.setText(R.string.enter_site_address);
+        switch (mLoginListener.getLoginMode()) {
+            case SHARE_INTENT:
```
[the remark this answers is not in the document]
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginSiteAddressFragment.java]: To be honest I prefer the switch statement. 'setupLabel' method is a overridden method and I believe it should have the same structure (if possible) in all subclasses. Moreover, it's a bit more transparent, that there are other cases which can be specified. WDYT @hypest ?

File: WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerAdapter.java (hunk 8 above)
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerAdapter.java]: Completely agree! I'm not sure what was I thinking.

File: WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerAdapter.java [hunk 16]
```diff
@@ -81,6 +85,10 @@
     private OnSelectedCountChangedListener mSelectedCountListener;
     private OnDataLoadedListener mDataLoadedListener;
 
+    private boolean mIsSingleItemSelectionEnabled;
+    private int mSelectedItemPos = NOT_DEF;
+    private int mSelectedItemLocalId = NOT_DEF;
```
[the remark this answers is not in the document]
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerAdapter.java]: Fixed

File: WordPress/src/main/res/values/strings.xml (hunk 9 above)
Comment (malinajirka) [reply WordPress/src/main/res/values/strings.xml]: Fixed

**Comment by malinajirka** [comment]
Thank you for the review! :) I've fixed most of the issues, and I've left some comments for the rest.

File: WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverFragment.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (hypest) [reply WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverFragment.java]: Indeed, when persistence is involved, using a custom `id` is the safe path to follow.

As you already noted, in this specific use case where any change to the order or the names doesn't practically matter, an `id` is redundant. Thanks for making the change!

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginEpilogueFragment.java (hunk 14 above)
[the remark this answers is not in the document]
Comment (hypest) [reply WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginEpilogueFragment.java]: > in order to scroll along with the 'logged in as' section.

Ah, I see. Yes, makes sense to keep mMySitesHeadingTextView in the header layout. It doesn't worth the hassle to extract it so, 👍 

> I divided the showHeader parameter into hasAccessToken and isAfterLogin parameters. 

I think `isAfterLogin` is quite clear but `hasAccessToken` not so much. How about renaming it to `isLoggedInWpcom`?

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginSiteAddressFragment.java (hunk 15 above)
[the remark this answers is not in the document]
Comment (hypest) [reply WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginSiteAddressFragment.java]: I see where you're coming from. 👍  to keep it as is, thanks!

File: WordPress/src/main/res/values/styles.xml (hunk 5 above)
[the remark this answers is not in the document]
Comment (hypest) [reply WordPress/src/main/res/values/styles.xml]: > Just an idea -> wouldn't be better to rename the LoginTheme to something more generic/reusable?

Sorry I left that unanswered before.
Sure, now that a second screen uses the theme and it's not strictly related to Login, something more generic would be more appropriate. We actually tried to follow Material design as close as we could with the Login Rework project so, this theme is pretty generic in its definitions. Perhaps we can rename it to "WPMaterialTheme" but please, feel free to come up with something different. Thanks!

**Comment by hypest** [comment]
Thanks for the changes @malinajirka ! I'm pretty much done with my review passes.

@folletto you think you can give a pass on the design side of things? Thanks!

In the meantime, I've only left one [new comment here](https://github.com/wordpress-mobile/WordPress-Android/pull/6690#discussion_r144264198) @malinajirka which is not blocking so, let me know if you'd like to address it in this PR, a separate one or not at all.

I also have another non-blocking comment which is that the last few commits on the PR were encompassing too many fixes. That's not a problem generally but it usually helps both the PR review and any future debugging attempts to keep the commits "narrow" enough. Again, this is not blocking this PR; it's more like a general comment.

Finally, not 100% sure it's this PR's issue but, it seems that if we revoke the Storage permission the Share action doesn't work. Steps to reproduce:
* Clean the app data
* Share a photo to wpandroid, login, accept the Media permission and choose to "new post"
* Don't finish the post and just go back
* Switch to the system settings and revoke the Storage permission
* Try to share a photo again

Tried it on a 7.1.1 emulator. Can you give is try @malinajirka ? Thanks!

**Comment by folletto** [comment]
> you think you can give a pass on the design side of things? Thanks!

Design looks good according to the specs. 

The only tweak I would make is for a single site: if it's just one:

1. Change the header to "Adding to" (instead of "Pick site")
2. Remove the selection indicator — as there's just one option

File: WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverActivity.java [hunk 17]
```diff
@@ -4,233 +4,158 @@
...
-
-        // If type is text/plain hide Media Gallery option
-        if (isSharingText()) {
-            mActionIndex = ADD_TO_NEW_POST;
-            mActionGroup.setVisibility(View.GONE);
-            findViewById(R.id.action_spinner_title).setVisibility(View.GONE);
-            // if text/plain and only one blog, then don't show this fragment, share it directly to a new post
-            if (mSiteNames.length == 1) {
-                // Single site, startActivityAndFinish will pick the first one by default
-                startActivityAndFinish(new Intent(this, EditPostActivity.class));
```
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverActivity.java]: Looks like this changeset killed a small shortcut here: if the user shares text and have one only site, we didn't show the picker at all but we opened the editor directly.

File: WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverActivity.java [hunk 18]
```diff
@@ -4,233 +4,158 @@
...
 
-        setContentView(R.layout.share_intent_receiver_dialog);
-
-        TextView blogSpinnerTitle = (TextView) findViewById(R.id.blog_spinner_title);
-        mBlogSpinner = (Spinner) findViewById(R.id.blog_spinner);
-        mActionGroup = (RadioGroup) findViewById(R.id.share_actions);
-
-        initSiteLists();
-
-        if (mSiteNames == null) {
```
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverActivity.java]: This (ugly) test, was checking if the user had at least one visible site, and if not, we were closing the share activity with a toast message:

```
ToastUtils.showToast(getBaseContext(), R.string.cant_share_no_visible_blog, ToastUtils.Duration.LONG);
```

Also, some wordpress.com users don't have any site, in this situation, the picker crash after tapping the "add to new post" button:

```
 java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
     at java.util.ArrayList.get(ArrayList.java:411)
     at org.wordpress.android.ui.main.SitePickerAdapter.getItem(SitePickerAdapter.java:188)
     at org.wordpress.android.ui.main.SitePickerAdapter.getSelectedItemLocalId(SitePickerAdapter.java:329)
     at org.wordpress.android.ui.ShareIntentReceiverFragment$1.onClick(ShareIntentReceiverFragment.java:128)
     at android.view.View.performClick(View.java:5609)
     at android.view.View$PerformClick.run(View.java:22259)
     at android.os.Handler.handleCallback(Handler.java:751)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:154)
     at android.app.ActivityThread.main(ActivityThread.java:6077)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverActivity.java]: The check is in the ShareIntentReceiverFragment -> createSiteAdapter() -> mAdapter.getItemCount() == 0. But you are right, there is a bug. The mAdapter.getItemCount() returns 1 if there is a header and no sites.

File: WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverActivity.java (hunk 17 above)
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverActivity.java]: Good point! I must have missed that. Thanks

Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverActivity.java]: I'm having some troubles with activity transitions when skipping the 'pick site' fragment. The ShareIntentReceiverActivity UI is shown for a short time which looks pretty bad. When the UI was just a dialog, the activity had "NoDisplay" theme so the transition was invisible. 
The only solution I can think of is to create a new activity with NoDisplay theme, which would decide whether to go directly to EditPostActivity or shown the 'pick site' activity.
Is there any better solution? Thanks @maxme

**Comment by malinajirka** [comment]
Thanks @hypest for the review.

- I have hidden the radio button when the user has just one visible site
- I have fixed the 'no visible blog' case

> In the meantime, I've only left one new comment here @malinajirka which is not blocking so, let me know if you'd like to address it in this PR, a separate one or not at all.

Renaming the theme would affect 16 files related to login. I think this PR is big enough. I would rename it in a separate PR.  

> I also have another non-blocking comment which is that the last few commits on the PR were encompassing too many fixes per commit. That's not a problem generally but it usually helps both the PR review and any future debugging attempts to keep the commits "narrow" enough. Again, this is not blocking this PR; it's more like a general comment.

Thanks for the tip. I'll do my best;-).

> Finally, not 100% sure it's this PR's issue but, it seems that if we revoke the Storage permission the Share action doesn't work. 

Hmm, it's an interesting issue. I was able to reproduce it. Nevertheless, the problem occurs only when sharing an image from the gallery. When I shared an image from the chrome for instance it worked. The only difference between those two sharing intents were activity flags. I made the ShareIntentReceiverActivity 'singleTask' and it works as expected. I always try to be careful when using non-default launch mode. But I couldn't think of any reason why this activity shouldn't have 'singleTask' launch mode. WDYT?

> Looks like this changeset killed a small shortcut here: if the user shares text and have one only site, we didn't show the picker at all but we opened the editor directly.

I'm not sure how to proceed. See my <a href="https://github.com/wordpress-mobile/WordPress-Android/pull/6690#discussion_r144340396">comment</a>.

File: WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverActivity.java (hunk 17 above)
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverActivity.java]: N/C :) ... I'm using the TaskStackBuilder and I was setting the FLAG_ACTIVITY_NO_ANIMATION on a wrong intent. It works as expected.

Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverActivity.java]: It didn't work when the app was dead and a user wanted to share a text. The activity transition was still visible to the user. So I had to use the NoDisplay layout after all and set the 'LoginTheme' directly on the views.

File: WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverFragment.java [hunk 19]
```diff
@@ -0,0 +1,226 @@
...
+        if (savedInstanceState != null) {
+            mLastUsedBlogLocalId = savedInstanceState.getInt(ARG_LAST_USED_BLOG_LOCAL_ID);
+        }
+    }
+
+    @Override
+    public void onSaveInstanceState(Bundle outState) {
+        super.onSaveInstanceState(outState);
+        int selectedItemLocalId = mAdapter.getSelectedItemLocalId();
+        if (selectedItemLocalId != 1) {
```
Comment (hypest) [inline WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverFragment.java]: Should the conditional be against `-1` perhaps?

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginHeaderViewHolder.java [hunk 20]
```diff
@@ -0,0 +1,63 @@
...
+        super(view);
+        mLoggedInAsHeading = view.findViewById(R.id.logged_in_as_heading);
+        mUserDetailsCard = view.findViewById(R.id.user_details_card);
+        mAvatarImageView = (WPNetworkImageView) view.findViewById(R.id.avatar);
+        mDisplayNameTextView = (TextView) view.findViewById(R.id.display_name);
+        mUsernameTextView = (TextView) view.findViewById(R.id.username);
+        mMySitesHeadingTextView = (TextView) view.findViewById(R.id.my_sites_heading);
+    }
+
+    public void update(Context context, LoginHeaderViewHolder holder, boolean isLoggedInWpcom, boolean isAfterLogin,
```
Comment (hypest) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginHeaderViewHolder.java]: Do we need to pass `holder` as a parameter at this point?

File: WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerAdapter.java [hunk 21]
```diff
@@ -276,6 +291,50 @@ public boolean onLongClick(View view) {
                 }
             });
         }
+
+        if (mIsSingleItemSelectionEnabled) {
+            if(getSitesCount() == 1){
```
Comment (hypest) [inline WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerAdapter.java]: I know we're basically handling the `0` sites case elsewhere (by not showing the Site picker at all) but I would feel safer if we check it here as well.

For example, let's check for `<= 1` than just `== 1` in order to hide the checkbox. WDYT?

**Comment by hypest** [comment]
> Renaming the theme would affect 16 files related to login. I think this PR is big enough. I would rename it in a separate PR.

Totally, the renaming can happen in some future PR. 👍 

> But I couldn't think of any reason why this activity shouldn't have 'singleTask' launch mode. WDYT?

I think `singleTask` is cool for the sharing action. Any problem arising from that we can tackle it in a future PR. 👍

File: WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverActivity.java [hunk 22]
```diff
@@ -4,233 +4,189 @@
...
-                startActivityAndFinish(new Intent(this, EditPostActivity.class));
+    @Override
+    protected void onResume() {
+        super.onResume();
+        // keep setBackground in the onResume, otherwise the transition between activities is visible to the user when
+        // sharing text with an account with one visible site
+        findViewById(R.id.main_view).setBackgroundResource(R.color.login_background_color);
+    }
+
+    protected void refreshContent(){
```
[the remark this answers is not in the document]
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverActivity.java]: Fixed

File: WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverActivity.java [hunk 23]
```diff
@@ -4,233 +4,189 @@
...
+            ActivityLauncher.loginForShareIntent(this);
         }
     }
 
-    @Override
-    public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
-        if (parent.getId() == R.id.blog_spinner) {
-            mSelectedSiteLocalId = mSiteIds[position];
-        }
+    protected void initShareFragment(boolean afterLogin) {
```
[the remark this answers is not in the document]
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverActivity.java]: Fixed

File: WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverActivity.java [hunk 24]
```diff
@@ -4,233 +4,189 @@
...
+        ShareIntentReceiverFragment shareIntentReceiverFragment = ShareIntentReceiverFragment
+            .newInstance(!isSharingText(), loadLastUsedBlogLocalId(), afterLogin);
```
[the remark this answers is not in the document]
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverActivity.java]: I was using googleJavaStyle instead of AospJavaStyle. My bad. Thanks! 

No reason to apologize :). Tbh, I'm usually the one who is being pedantic about code formatting. I like to have a codestyle.xml included in the repository, so everyone has the same settings.

File: WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverFragment.java (hunk 19 above)
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverFragment.java]: :) Good job! Thanks

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginHeaderViewHolder.java (hunk 20 above)
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginHeaderViewHolder.java]: fixed

File: WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerAdapter.java (hunk 21 above)
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerAdapter.java]: The code is in the onBindViewHolder which can't be called when there is no item in the adapter. WDYT @hypest

**Comment by malinajirka** [comment]
I've fixed the last few issues. Feel free to merge the PR @hypest.

Thank you so much for the review and for all the tips!!!

File: WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerAdapter.java (hunk 21 above)
Comment (hypest) [reply WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerAdapter.java]: > ...which can't be called when there is no item in the adapter.

True, but i'm referring to the zero *sites* case which is different to the zero *items* case since there might be a header item.

The assumption here is that execution won't reach this point if `getSitesCount() == 0` but that's not apparent while reading the code so, we should either handle that case as commented [originally](https://github.com/wordpress-mobile/WordPress-Android/pull/6690#discussion_r144536607) or we should add a comment that we're expecting never to reach this line when no sites are available.

Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerAdapter.java]: Ohh I see your point. Fixed:)

**Comment by hypest** [comment]
OK, let's 🚢  this!
