### PR TITLE
SingInActivity magic link crash fix

### LINKED ISSUE #5661: Crash report on 7.0: IllegalStateException in SignInActivity
```
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1842)
       at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1860)
       at android.support.v4.app.FragmentManagerImpl.popBackStack(FragmentManager.java:770)
       at org.wordpress.android.ui.accounts.SignInActivity.popBackStackToSignInFragment(SignInActivity.java:203)
       at org.wordpress.android.ui.accounts.SignInActivity.onEnterPasswordRequested(SignInActivity.java:270)
       at org.wordpress.android.ui.accounts.login.MagicLinkRequestFragment$5.onErrorResponse(MagicLinkRequestFragment.java:157)
       at com.android.volley.Request.deliverError(Request.java:590)
       at com.wordpress.rest.RestRequest.deliverError(RestRequest.java:87)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:101)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:155)
       at android.app.ActivityThread.main(ActivityThread.java:5727)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```

### PR DESCRIPTION
**Pull request by 0nko**
Fixes #5661.

I wasn't able to reproduce this but this should prevent the exception from happening, because it's being thrown when `FragmentManager` transaction's `commit()` is called after `onStop()`. Since we're popping from a backstack asynchronously, we can't use `commitAllowingStateLoss()`, therefore we must check for the activity state.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInActivity.java [hunk 1]
```diff
@@ -195,12 +213,16 @@ public SmartLockHelper getSmartLockHelper() {
     }
 
     private void popBackStackToSignInFragment() {
-        FragmentManager fragmentManager = getSupportFragmentManager();
-        while (fragmentManager.getBackStackEntryCount() > 1) {
-            fragmentManager.popBackStackImmediate();
-        }
 
-        getSupportFragmentManager().popBackStack();
+        // this can bee called asynchronously from Volley onError handler so we must check if state is OK
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInActivity.java]: Volley's error callback happens on the main thread, so I don't think this is the problem. I'm not sure, but perhaps the issue is [here](https://github.com/wordpress-mobile/WordPress-Android/blob/issue/5661-magic-link-crash/WordPress/src/main/java/org/wordpress/android/ui/accounts/login/MagicLinkRequestFragment.java#L162), where we call `mListener.onEnterPasswordRequested()` without checking `isAdded()`?

Comment (0nko) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInActivity.java]: Even though they both run on the main thread, it could happen that the activity's `onStop()` runs first and then the REST client invokes the error handler, couldn't it? Also since the fragment's `onDetach()` event is called after `onStop()`, could we not still get this exception with the right timing?

Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInActivity.java]: I guess it's possible - that exception seems possible anytime we use `commit()` :) But I'm not sure why we can't just use `commitAllowingStateLoss()` here?

Comment (0nko) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInActivity.java]: Because we're not calling the `commit()` function directly, it's is called inside `popBackStack()`.

Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/SignInActivity.java]: D'oh! Sorry, I should've figured that out :)

**Comment by nbradbury** [comment]
:shipit:
