### PR TITLE
Fix: Show Quickstart focus point when Site Info header Toolbar is collapsed

### LINKED ISSUE #16153: Quickstart focus point on Site Header
Parent #16002

Todo 

- [ ] Check quick start functionality with the Site header collapsed 
- [ ] Site header should scroll up, expand and show the quick start focus point in case of the active task 

The active task in the My Site Header are 
- Site Title change task
- Site Icon change task

### PR DESCRIPTION
**Pull request by AjeshRPai**
Fixes #16153 

After the changes of moving the site header to the toolbar(#16030), the quick start focus point won't be shown for Site Title and Site Icon quick start task if the Site info header toolbar is collapsed. This PR fixes the issue by auto-scrolling to the top and expanding the toolbar if the Quickstart task is either `UPDATE_SITE_TITLE` or `UPLOAD_SITE_ICON`. Please find below the video showing the auto-scroll behaviour 

Video captures:
1. "Site title" QS step (time stamp 0:05)
2.  Auto-scroll (time stamp 0:06)
3. "Site Icon" QS step (time stamp 0:23)
4.  Auto-scroll (time stamp 0:24)
5. "Edit your page" QS step(time stamp 0:45) - Captured this to show the behaviour when the QS step focus point is not inside Site Header. 
6.  No Scroll or the Site Header is not expanded(0:46) 

https://user-images.githubusercontent.com/17463767/160091236-10ae51f4-c6a7-46c3-8965-68ddaf759035.mp4

To test:

Test.1: Regression test Quick Start in single view with tabs disabled

- Launch the app.
- Go to My Site -> Me -> App Settings -> Debug settings.
- Turn off the MySiteDashboardTabsFeatureConfig flag under the Features in development section.
- Restart the app.
- Logout/login and select "Show me around" when the quick start prompt is shown.
- Run tests in [wpandroid-quick-start-testing-instructions.txt](https://github.com/wordpress-mobile/WordPress-Android/files/8246096/wpandroid-quick-start-testing-instructions.txt).
- [ Notice that in **Test 1 - Quick start notice display** or **Test 2 - snackbar action** in the text file, when the Site info header is collapsed and quick start task is **Check your site title or Choose a unique site icon**,  The site info header is expanded and focus point is shown]

Test.2: Quick Start with tabs enabled

- Launch the app.
- Go to My Site -> Me -> App Settings -> Debug settings.
- Turn on the MySiteDashboardTabsFeatureConfig flag under the Features in development section.
- Restart the app.
- Logout/login and select "Show me around" when the quick start prompt is shown.
- Note the "Quick Start" shows in the Dashboard/ Home tab only.
- Run tests in [wpandroid-quick-start-testing-instructions.txt](https://github.com/wordpress-mobile/WordPress-Android/files/8246096/wpandroid-quick-start-testing-instructions.txt).
- [ Notice that in **Test 1 - Quick start notice display** or **Test 2 - snackbar action** in the text file, when the Site info header is collapsed and quick start task is **Check your site title or Choose a unique site icon**,  The site info header is expanded and focus point is shown]

## Review Instructions
- Code review from only one reviewer is sufficient.

## Regression Notes
1. Potential unintended areas of impact
- Quick start focus point not being shown properly 
- Auto-scrolling to the top and the app bar getting expanded for Quickstart tasks other than **Check your site title or Choose a unique site icon**.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
- Manual tests 

4. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt [hunk 1]
```diff
@@ -463,17 +470,23 @@ class MySiteViewModel @Inject constructor(
         }.toList()
     }
 
-    private fun scrollToQuickStartTaskIfNecessary(
-        quickStartTask: QuickStartTask?,
+    private fun scrollToQuickStartTask(
```
Comment (zwarm) [inline WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt]: @AjeshRPai - ❓ Why did you remove the `IfNecessary` part from the fun name? It's a pattern generally used throughout the app to denote whether the action is required.

**Review by zwarm — APPROVED** [review]
@AjeshRPai - Nice work. 👍 

The testing works as expected - when the header is collapsed and Site title/icon are selected from QS, the header expands and the notification focus dot shows correctly. We'll probably need to retest after the merge with #16159 .

I'm going to approve, but I left one nit-pick question, so I'll leave the merge for you if you decide to change it first.

File: WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt (hunk 1 above)
Comment (AjeshRPai) [reply WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt]: @zwarm I am sorry, I changed it thinking since `quickStartTask` is non-null, I should drop the `IfNecessary`. Revisiting it and checking other functions I get it.  Reverted the `IfNecessary` in 7c2221b. Good catch. 👍

**Comment by tiagomar** [comment]
👋 @AjeshRPai I could only test this today, everything looks good. Good job! =]
