### PR TITLE
Fixes duplicate notifications

### LINKED ISSUE #3101: Notifications: Duplicate notifications for same noteId
The recent changes to support stacked notifications are showing duplicate notifications for the same noteId.

Scenario: You get a post like, and then 5 minutes later you receive another like for the same post. You'll see both of the notifications in the inbox style notification. It should instead replace the notification if the noteId's match.

### PR DESCRIPTION
**Pull request by roundhill**
Fixes #3101 by looping through the map of current notifications and updating an entry if a matching noteId is found.

You can test by liking one of your posts from two different test accounts. You should see the notification content get updated, instead of seeing two versions of the same notification.

Also cleaned up a bit of the coding style.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/GCMIntentService.java [hunk 1]
```diff
@@ -55,6 +55,12 @@
     private static long mPreviousNoteTime = 0L;
     private static final int mMaxInboxItems = 5;
 
+    private static final String PUSH_ARG_USER = "user";
+    private static final String PUSH_ARG_TYPE = "type";
+    private static final String PUSH_ARG_TITLE = "title";
+    private static final String PUSH_ARG_MSG = "msg";
+    private static final String PUSH_ARG_NOTE_ID = "note_id";
+
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/GCMIntentService.java]: :+1:

File: WordPress/src/main/java/org/wordpress/android/GCMIntentService.java [hunk 2]
```diff
@@ -76,17 +82,17 @@ protected void onError(Context context, String errorId) {
...
     private void handleDefaultPush(Context context, Bundle extras) {
-        long wpcomUserID = AccountHelper.getDefaultAccount().getUserId();
-        String userIDFromPN = extras.getString("user");
-        // userIDFromPN is always set server side, but better to double check it here.
-        if (userIDFromPN != null) {
-            if (!String.valueOf(wpcomUserID).equals(userIDFromPN)) {
+        long wpcomUserId = AccountHelper.getDefaultAccount().getUserId();
+        String pushUserId = extras.getString(PUSH_ARG_USER);
+        // pushUserId is always set server side, but better to double check it here.
+        if (pushUserId != null) {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/GCMIntentService.java]: Minor nit: no need for the separate null check since the `equals` comparison below returns false if `pushUserId` is null.

File: WordPress/src/main/java/org/wordpress/android/GCMIntentService.java [hunk 3]
```diff
@@ -126,10 +132,22 @@ private void handleDefaultPush(Context context, Bundle extras) {
...
+            if (noteBundle.getString(PUSH_ARG_NOTE_ID, "").equals(noteId)) {
+                pushId = id;
+                mActiveNotificationsMap.put(pushId, extras);
+                matchedNoteId = true;
+                break;
+            }
+        }
 
-        if (noteId != null && !mActiveNotificationsMap.containsKey(noteId)) {
+        if (!matchedNoteId) {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/GCMIntentService.java]: The variable `matchedNoteId` isn't really necessary since we can simply check whether `pushId` is still zero.

**Comment by nbradbury** [comment]
@roundhill I tested this and it's working just fine. Let me know whether you want to address those nits I brought up, otherwise I can merge it now.

**Comment by roundhill** [comment]
> Let me know whether you want to address those nits I brought up, otherwise I can merge it now.

I've just seen another bug this morning, I think I'm cursed! I'll get it fixed in this branch and also fix the nits and get back to you.

File: WordPress/src/main/java/org/wordpress/android/GCMIntentService.java (hunk 3 above)
Comment (roundhill) [inline WordPress/src/main/java/org/wordpress/android/GCMIntentService.java]: Oh yeah, nice :) Cylon genius at work.

**Comment by roundhill** [comment]
All set, the bug I found was a non-issue so I just corrected the things you already mentioned.

**Comment by nbradbury** [comment]
:shipit:
