### PR TITLE
Accessibility : Posting Stats Improvement v2 

### LINKED ISSUE #10975: Accessibility : Stats Posting Activity Improvements
### Expected behavior

You should be able to select each month and navigate through the different days to hear an overview of the activity.

### Actual behavior
The entire component is selected but you aren't able to get any details of what's within it. 

### Steps to reproduce the behavior
1. Go to my site. 
2. Select Stats 
3. Select the "Posting Activity" section

### PR DESCRIPTION
**Pull request by jd-alexander**
Fixes #10975 
## Findings
The Posting Stats was inaccessible when using TalkBack. This improvement makes it more accessible for visually impaired users who are navigating the stats functionality. 

## Solution
The solution for this is to highlight the views by grouping them by the days that share the same ranking([This solution was discussed in detail on this PR](https://github.com/wordpress-mobile/WordPress-Android/pull/10980#pullrequestreview-334602495)). Once this is done, the user is able to hear the days with the highest views as soon as they interact with the component and then can continue to cycle through the rest of activity with subsequent clicks. 

Before | After 
--------|-------
[Before Video ](https://drive.google.com/open?id=18ErO8-vpZxLuxucriVecOq218nEcmaSK) |   [After Video    ](https://drive.google.com/file/d/19AwFLbvKmtyl16pL9nG3BLGEDjRnKA_h/view?usp=sharing)

## Testing

1. Enable TalkBack. 
2. Navigate to the Stats page.
3. Ensure you are on the Insights Tab. 
4. Select each Month under "Posting Activity" and follow the instructions to hear the announcement.

Tap To Hear Day Stats | Stat Announced 
--------|-------
        |       

All Stats Announced | No Stats Available 
--------|-------
   |    

## Reviewing 
Only 1 reviewer is needed but anyone can review. 

## Submitter Checklist

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
- [x] If it's feasible, I have added unit tests.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/PostingActivityMapper.kt [hunk 1]
```diff
@@ -55,7 +57,13 @@ class PostingActivityMapper
                                     Calendar.SHORT,
                                     localeManagerWrapper.getLocale()
                             ),
-                            boxes
+                            boxes,
```
Comment (jd-alexander) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/PostingActivityMapper.kt]: I needed to create this content description for the Block because the label is the short version of the month so "Dec" is being read as "Deck" so this content description allows me to pass the long version of the month.

File: WordPress/src/main/java/org/wordpress/android/util/ContentDescriptionListAnnouncer.kt [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+                    override fun onInitializeAccessibilityNodeInfo(
+                        host: View?,
+                        info: AccessibilityNodeInfoCompat?
+                    ) {
+                        super.onInitializeAccessibilityNodeInfo(host, info)
+
+                        clickActionText?.let {
+                            info?.addAction(
+                                    AccessibilityNodeInfoCompat.AccessibilityActionCompat(
+                                            ACTION_CLICK, host?.context?.getString(
```
Comment (jd-alexander) [inline WordPress/src/main/java/org/wordpress/android/util/ContentDescriptionListAnnouncer.kt]: In this class, I utilize the `context` of the host view so I don't have to inject the `ResourceProvider` since this class isn't testable and doesn't need to be right now since it's just a view related one. What do you think?

File: WordPress/src/main/java/org/wordpress/android/util/ContentDescriptionListAnnouncer.kt [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+class ContentDescriptionListAnnouncer constructor(
+    @StringRes private val emptyListText: Int,
+    @StringRes private val endOfListText: Int,
+    @StringRes private val clickActionText: Int? = null,
+    private val contentDescriptions: List<String>,
+    targetView: View
+) {
+    private var currentIndex = 0
+
+    init {
```
Comment (jd-alexander) [inline WordPress/src/main/java/org/wordpress/android/util/ContentDescriptionListAnnouncer.kt]: I am using the `init` to wire up the behavior. What I noticed is that the class is just instantiated and the functionality works so I am wondering if that's fine from a readable/architecture standpoint or should there be a function that's called so that the action being taken when the class is created is easily expressed.

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/PostingActivityUseCase.kt [hunk 4]
```diff
@@ -55,11 +61,43 @@ class PostingActivityUseCase
...
+    private fun addBlockContentDescriptions(activityItem: ActivityItem): ActivityItem {
+        val blocks = mutableListOf<Block>()
+
+        activityItem.blocks.forEach { block ->
+            val descriptions = mutableListOf<String>()
+            block.boxes.filter { box -> box.boxType != BoxType.INVISIBLE && box.boxType != BoxType.VERY_LOW }
+                    .sortedByDescending { box -> box.boxType }
+                    .groupBy { box -> box.boxType }
+                    .forEach { entry ->
+                        val readableBoxType = entry.key.name.replace(
```
Comment (jd-alexander) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/PostingActivityUseCase.kt]: I just realized this isn't localized so I will switch this out with an implementation that is.

**Comment by jkmassel** [comment]
I'm moving this PR to 14.1 since we're code freezing today.

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt [hunk 5]
```diff
@@ -233,8 +233,16 @@ sealed class BlockListItem(val type: Type) {
...
-        data class Block(val label: String, val boxes: List<Box>)
-        enum class Box {
+        data class Block(
+            val label: String,
+            val boxes: List<Box>,
+            val contentDescription: String,
+            val activityContentDescriptions: List<String>? = null
+        )
+
+        data class Box(val boxType: BoxType, val day: Int? = null)
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt]: I'm not familiar with this part of the app. However, I'm wondering whether it makes sense to introduce `day` field in the `Box` class => the field isn't being used on the UI. It's being used only when we are building the ActivityItem. We might want to consider reverting some of the changes in `ActivityItem` and moving `buildActivityItem` to `PostingActivityMapper`, wdyt?

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/PostingActivityMapper.kt [hunk 6]
```diff
@@ -29,33 +29,38 @@ class PostingActivityMapper
...
             }
             blocks.add(
                     Block(
-                            firstDayOfMonth.getDisplayName(
-                                    Calendar.MONTH,
-                                    Calendar.SHORT,
-                                    localeManagerWrapper.getLocale()
-                            ),
-                            boxes
+                            getMonthDisplayName(Calendar.SHORT),
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/PostingActivityMapper.kt]: We might want to consider settings the content description to something like "Posting Activity for $getMonthDisplayName". Wdyt?

File: WordPress/src/main/java/org/wordpress/android/util/ContentDescriptionListAnnouncer.kt (hunk 2 above)
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/util/ContentDescriptionListAnnouncer.kt]: Yep, I agree that it's ok => the class isn't testable anyway and making it testable would require more changes.

File: WordPress/src/main/res/values/strings.xml [hunk 7]
```diff
@@ -884,9 +884,19 @@
...
-    <string name="stats_posting_activity_graph">Graph of posting activity.</string>
     <string name="stats_list_item_description">%1$s: %2$s, %3$s: %4$s</string>
 
+    <string name="stats_box_type_low">low</string>
+    <string name="stats_box_type_medium">medium</string>
+    <string name="stats_box_type_high">high</string>
+    <string name="stats_box_type_very_high">very high</string>
+
+    <string name="stats_posting_activity_action">navigate all stats for this period</string>
+    <string name="stats_posting_activity_content_description">"The days with %1$s views for %2$s are : %2$s %3$s."</string>
```
Comment (malinajirka) [inline WordPress/src/main/res/values/strings.xml]: We might want to consider ending this announcement with ", tap for more". Or is it a common practice that clicking multiple times on the same view keeps going more into detail?

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/ActivityViewHolder.kt [hunk 8]
```diff
@@ -50,6 +51,23 @@ class ActivityViewHolder(val parent: ViewGroup) : BlockListItemViewHolder(
...
+        setupBlocksForAccessibility(item)
+    }
+
+    private fun setupBlocksForAccessibility(item: ActivityItem) {
+        val blocks = listOf(firstBlock, secondBlock, thirdBlock)
+
+        blocks.forEachIndexed { index, block ->
+            block.label.contentDescription = item.blocks[index].contentDescription
+
+            ContentDescriptionListAnnouncer(
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/ActivityViewHolder.kt]: It feels a bit weird that we create an Object and we don't do anything with it. I know the class isn't testable anyway, but putting logic into constructor/init methods is a code smell. I'd consider moving the logic into a method. Wdyt?

**Review by malinajirka — APPROVED** [review]
Really great job @jd-alexander! I haven't found any issues and the code looks good.

I've left a few comments for consideration. Especially one of them might result in more changes, but I don't feel strongly about it. It just feels a bit weird. Let me know what you think;)

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/PostingActivityMapper.kt (hunk 6 above)
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/PostingActivityMapper.kt]: That sounds good! I will look into it.

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt (hunk 5 above)
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt]: Hi Jirka! Thanks for this observation. It's something we can think of modifying if it makes sense. The reason I put it here is the `contentDescription` is somewhat a UI element, it's just a different kind of UI for other users so I thought it made sense to include it.

File: WordPress/src/main/res/values/strings.xml (hunk 7 above)
Comment (jd-alexander) [reply WordPress/src/main/res/values/strings.xml]: This is a good observation. I will include this change. Thanks!

Comment (jd-alexander) [reply WordPress/src/main/res/values/strings.xml]: Resolved 40cd081

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/PostingActivityMapper.kt (hunk 6 above)
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/PostingActivityMapper.kt]: Resolved 40cd081

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/ActivityViewHolder.kt (hunk 8 above)
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/ActivityViewHolder.kt]: Resolved 962663d

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt (hunk 5 above)
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt]: >contentDescription is somewhat a UI element, it's just a different kind of UI for other users so I thought it made sense to include it.

I absolutely agree with this statement. Having `contentDescription` field in `Block` is ok. 
However, it seems `ActivityItem` and `Box` are UIStates and `day` is not part of their UIState = it isn't being used in the view layer. We use it only to store some data we need to use while we are building the UIState.

It's not a big deal, it just feels weird.

File: WordPress/src/main/res/values/strings.xml [hunk 9]
```diff
@@ -893,6 +893,7 @@
 
     <string name="stats_posting_activity_action">navigate all stats for this period</string>
     <string name="stats_posting_activity_content_description">"The days with %1$s views for %2$s are : %2$s %3$s, tap for more."</string>
+    <string name="stats_posting_activity_label_content_description">"Posting Activity for %1$s</string>
```
Comment (malinajirka) [inline WordPress/src/main/res/values/strings.xml]: The string starts with `"`, is it intentional?

File: WordPress/src/main/res/values/strings.xml [hunk 10]
```diff
@@ -884,9 +884,20 @@
...
-    <string name="stats_posting_activity_graph">Graph of posting activity.</string>
     <string name="stats_list_item_description">%1$s: %2$s, %3$s: %4$s</string>
 
+    <string name="stats_box_type_low">low</string>
+    <string name="stats_box_type_medium">medium</string>
+    <string name="stats_box_type_high">high</string>
+    <string name="stats_box_type_very_high">very high</string>
+
+    <string name="stats_posting_activity_action">navigate all stats for this period</string>
+    <string name="stats_posting_activity_content_description">"The days with %1$s views for %2$s are : %2$s %3$s.Tap for more."</string>
```
Comment (malinajirka) [inline WordPress/src/main/res/values/strings.xml]: I have missed this during the review, but it seems there are at least 3 strings starting or/and ending with `"`. Is it intentional?

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt (hunk 5 above)
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt]: Okay! I totally get what you mean now when you connect it to the concept of `UIState`. Thanks for the explanation. So are you saying I should move this logic to the `UseCase` then?

File: WordPress/src/main/res/values/strings.xml (hunk 10 above)
Comment (jd-alexander) [reply WordPress/src/main/res/values/strings.xml]: Thanks for catching this 😅

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt (hunk 5 above)
Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt]: `PostingActivityMapper.buildActivityItem` returns an instance of `ActivityItem`, we pass that `ActivityItem` into `addBlockContentDescriptions` and we create a different instance of `ActivityItem` there, which also feels a bit weird. 
I think the best place for the contentDescription logic would be in `PostingActivityMapper` =>`PostingActivityMapper.buildActivityItem` would return a complete `ActivityItem`. Wdyt?

File: WordPress/src/main/res/values/strings.xml (hunk 10 above)
Comment (jd-alexander) [reply WordPress/src/main/res/values/strings.xml]: Resolved b5f6951

File: WordPress/src/main/res/values/strings.xml (hunk 9 above)
Comment (jd-alexander) [reply WordPress/src/main/res/values/strings.xml]: Resolved b5f6951

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt (hunk 5 above)
Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt]: Resolved 50224c5

**Comment by jd-alexander** [comment]
Hey @malinajirka I made all the changes we discussed and I even included unit tests for the content description logic f077555 😉

**Comment by malinajirka** [comment]
Thanks @jd-alexander ;)! Really glad to see the unit tests.

I noticed the days read by the TalkBack don't match the days one the UI. To be more specific, it works for the first month, but the same day is read for the other months.

posting-activity
- Notice it keeps reading "25." for all the months

**Comment by jd-alexander** [comment]
Thanks for the review of the whole component. This issue was resolved acf5db7 and the tests were updated 0f7afe1 to ensure that the data that corresponds to each month is accurate.

**Comment by malinajirka** [comment]
Thanks @jd-alexander !

I've tested the changes and everything seems to work as expected now. Thank you for extending the unit test so it covers even the scenario which wasn't working.

SideNote:
I don't want to block this PR anymore, but I'll leave a brief feedback about the unit test here. Unit tests have several goals. Probably the two main goals are to test the logic (facilitate refactoring/modifications) and serve as a documentation. I think the unit test in this PR somewhat meets the first goal, however I feel like it doesn't server as a documentation. I believe the main reason for this is that we are testing everything within one test method. In general, it's better to have each scenario tested in a separate method so each test has only a single reason to fail.
