### PR TITLE
[Reader IA] Fix RTL drop-down menu not being shown 

### LINKED ISSUE #19839: [Reader IA] Fix RTL drop-down menu not being shown
Fix bug where in RTL layout direction the drop-down menu is not being shown.

### PR DESCRIPTION
**Pull request by RenanLukas**
Fixes #19839

> [!CAUTION]
> Should not be merged before https://github.com/wordpress-mobile/WordPress-Android/pull/19805

Also fixed back icon in sub-menu considering layout direction.

### LTR
https://github.com/wordpress-mobile/WordPress-Android/assets/14964993/f7c9c413-cf74-4085-89be-1513a8fa94ba

### RTL
https://github.com/wordpress-mobile/WordPress-Android/assets/14964993/db76a523-8616-4a60-bd8e-04df8d50b6ae

-----

## To Test:

Run the `JetpackDropdownMenu` in RTL and LTR. A way to test it is to run `ReaderTopAppBarPreview` forcing RTL and then LTR. You can do so by wrapping the view with this `CompositionLocalProvider`:

```
CompositionLocalProvider(LocalLayoutDirection provides LayoutDirection.Rtl ) {
     // Add menu view here
}
```

-----

## Regression Notes

1. Potential unintended areas of impact
 None

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing

3. What automated tests I added (or what prevented me from doing so)
UI only

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## UI Changes Testing Checklist:

- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/compose/components/menu/dropdown/JetpackDropdownMenu.kt [hunk 1]
```diff
@@ -60,10 +64,17 @@ fun JetpackDropdownMenu(
                 isMenuVisible = !isMenuVisible
             }
         )
+        val cascadeMenuWidth = 200.dp
         CascadeDropdownMenu(
-            modifier = Modifier.background(MenuColors.itemBackgroundColor()),
+            modifier = Modifier
+                .background(MenuColors.itemBackgroundColor())
+                .width(cascadeMenuWidth),
```
Comment (thomashorta) [inline WordPress/src/main/java/org/wordpress/android/ui/compose/components/menu/dropdown/JetpackDropdownMenu.kt]: 💡 I noticed the `CascadeDropdownMenu` already has a `fixedWidth` parameter that defaults to 196dp, maybe we should use that parameter when defining the width for this component instead of passing a `Modifier.height` since I am not 100% sure if it's treated differently by the lib.

File: WordPress/src/main/java/org/wordpress/android/ui/compose/components/menu/dropdown/JetpackDropdownMenu.kt [hunk 2]
```diff
@@ -60,10 +64,17 @@ fun JetpackDropdownMenu(
...
             expanded = isMenuVisible,
             onDismissRequest = { isMenuVisible = false },
+            offset = if (LocalLayoutDirection.current == LayoutDirection.Rtl) DpOffset(
+                cascadeMenuWidth,
+                0.dp
+            ) else DpOffset.Zero,
```
Comment (thomashorta) [inline WordPress/src/main/java/org/wordpress/android/ui/compose/components/menu/dropdown/JetpackDropdownMenu.kt]: ❤️  Nice solution! Thanks!

🔍  Nitpick: when an if statement spawns multiple lines I would expect the usage of braces `{ }`. Maybe you can fit a 1-line `if-else` clause by writing it like this:

```kotlin
offset = DpOffset(
    if (LocalLayoutDirection.current == LayoutDirection.Rtl) cascadeMnuWidth else 0.dp,
    0.dp,
)
```

**Review by thomashorta — APPROVED** [review]
Thanks for looking into this and providing a reliable solution! It works as expected.

I added a couple of small comments to improve the code a bit.

File: WordPress/src/main/java/org/wordpress/android/ui/compose/components/menu/dropdown/JetpackDropdownMenu.kt (hunk 1 above)
Comment (RenanLukas) [reply WordPress/src/main/java/org/wordpress/android/ui/compose/components/menu/dropdown/JetpackDropdownMenu.kt]: Good point, done

File: WordPress/src/main/java/org/wordpress/android/ui/compose/components/menu/dropdown/JetpackDropdownMenu.kt (hunk 2 above)
Comment (RenanLukas) [reply WordPress/src/main/java/org/wordpress/android/ui/compose/components/menu/dropdown/JetpackDropdownMenu.kt]: Done 👍 

I've added name arguments instead (for `x` and `y`) since I thought it was clearer to read.

**Comment by RenanLukas** [comment]
Thanks for the review, @thomashorta ! I've implemented your suggestions.
