### PR TITLE
Issue/4429 plans appends text 5.7

### LINKED ISSUE #4429: Plans: Reopening app on plans page appends plans text
### Expected behavior

When reopening the app when already on the plans page, I expect the to see the same plans text

### Actual behavior

Each time the app is reopened, the plans text is added to the page, resulting in a large blob of duplicated text (see screenshots below)

### Steps to reproduce the behavior

1. Navigate to plans page
2. Close app
3. Reopen app - see plans text
4. Rinse & Repeat

##### Tested on Galaxy Tab A, 5.0.2

android - 1
android - 2

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #4429 - refer to [the issue](https://github.com/wordpress-mobile/WordPress-Android/issues/4429) for details.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/plans/PlanFragment.java [hunk 1]
```diff
@@ -73,17 +72,16 @@ public void onSaveInstanceState(Bundle outState) {
     }
 
     private void refreshPlanUI() {
```
Comment (hypest) [inline WordPress/src/main/java/org/wordpress/android/ui/plans/PlanFragment.java]: Hey @nbradbury , with `refreshPlanUI()` called only in `onActivityCreated()` now, its function is more like setting up some View instead or refreshing it. It might be useful to rename it accordingly to avoid confusion. Thanks!

File: WordPress/src/main/java/org/wordpress/android/ui/plans/PlanFragment.java [hunk 2]
```diff
@@ -93,16 +91,16 @@ private void refreshPlanUI() {
...
         String productName = mPlanDetails.getProductName().replace(productShortName,
                 "<b>" + productShortName + "</b>");
         txtProductName.setText(Html.fromHtml(productName));
 
-        TextView txtTagLine = (TextView) mPlanContainerView.findViewById(R.id.text_tagline);
+        TextView txtTagLine = (TextView) getView().findViewById(R.id.text_tagline);
         txtTagLine.setText(HtmlUtils.fastUnescapeHtml(mPlanDetails.getTagline()));
 
-        // The current plan could probably have some features to highlight on the details screen
+        mPlanContainerView.removeAllViews();
```
Comment (hypest) [inline WordPress/src/main/java/org/wordpress/android/ui/plans/PlanFragment.java]: It seems that now that `refreshPlanUI()` is called in `onActivityCreated()` instead of `onResume()`, mPlanContainerView will always be found empty anyway. May I suggest removing this line if so? Thanks!

**Comment by nbradbury** [comment]
@hypest Ready for another round, thanks!

**Comment by hypest** [comment]
LGTM!
