### PR TITLE
Issue/5491 missing posts in reader

### LINKED ISSUE #5491: Reader: missing posts
### Expected behavior

All posts that I see at https://wordpress.com/ with a browser also appear in Reader on WPAndroid.

### Actual behavior

Posts are missing in Reader on WPAndroid compared to viewing on the web.

### Steps to reproduce the behavior

1. Go to Reader in WPAndroid and browse posts.
1. Look for any large gaps in time such as from 5h to 2d.
1. Compare to https://wordpress.com/ in a browser to see if any posts are missing while viewing Reader in WPAndroid.

Note: I don't check Reader on WPAndroid every day. I can't remember exactly, but it's likely I haven't checked Reader on WPAndroid in 2d and that could be why the gap starts at that time for me.

screenshot_20170323-161509

screen shot 2017-03-23 at thu mar 23 4 16 59 pm

Maybe related: #3908

### PR DESCRIPTION
**Pull request by malinajirka**
Fixes #5491 

This PR fixes several bugs which all had the same result - some posts in Reader were missing.

To test - since posts are fetched in batches (max 20 posts per request), it's quite difficult to manually test all the cases. To facilitate the testing I locally set the ReaderConstants.READER_MAX_POSTS_TO_REQUEST constant to '2' and I kept publishing posts on a blog which I followed.

Prerequisite: 
- have more than 4 posts in the reader "followed sites" stream
- set ReaderConstants.READER_MAX_POSTS_TO_REQUEST to 2

Case 'publish a post -> potential gap not detected'
1. Go to reader
2. Select 'followed sites' stream
3. Pull-to-refresh
4. Publish a post
5. Go to reader
6. Pull-to-refresh 
7. Notice the post is visible and the 'load more posts' button is not visible

Case 'publish two posts -> potential gap detected'
1. Go to reader
2. Select 'followed sites' stream
3. Pull-to-refresh
4. Publish two posts
5. Go to reader
6. Pull-to-refresh (One of the two published posts is displayed along with the "load more posts button")
7. Click on the "load more posts" button
8. Notice that both posts are visible

Case 'publish four posts -> potential gap detected'
1. Go to reader
2. Select 'followed sites' stream
3. Pull-to-refresh
4. Publish four posts
5. Go to reader
6. Pull-to-refresh (One of the four published posts is displayed along with the "load more posts button")
7. Click on the "load more posts" button
8. Notice that all four posts are visible

Case 'publish two posts + publish two posts -> two potential gaps detected'
1. Go to reader
2. Select 'followed sites' stream
3. Pull-to-refresh
4. Publish two posts
5. Go to reader
6. Pull-to-refresh (One of the two published posts is displayed along with the "load more posts button")
7. Publish another two posts
8. Go to reader
9. Pull-to-refresh -> second gap is detected -> the first gap is automagically filled (old posts are actually removed and fetched again)
10. Click on the "load more posts" button
11. Notice that all four posts are visible

Case 'publish two posts + publish a post -> one potential gap detected'
1. Go to reader
2. Select 'followed sites' stream
3. Pull-to-refresh
4. Publish two posts
5. Go to reader
6. Pull-to-refresh (One of the two published posts is displayed along with the "load more posts button")
7. Publish another post
8. Go to reader
9. Pull-to-refresh -> new posts is fetched, however the "load more posts" button is still visible
10. Click on the "load more posts" button
11. Notice that all three posts are visible

Case 'publish two posts -> potential gap detected but there is actually no gap'
1. Go to reader
2. Select 'followed sites' stream
3. Pull-to-refresh
4. Publish two posts
5. Go to reader
6. Pull-to-refresh (One of the two published posts is displayed along with the "load more posts button")
7. Pull-to-refresh again
8. Notice that both posts are displayed
9. Click on the "load more posts" button
11. Notice that the 'load more posts" button disappears

There might be some cases I didn't think of :).

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java [hunk 1]
```diff
@@ -649,7 +649,7 @@ public static void deletePostsBeforeGapMarkerForTag(ReaderTag tag) {
         }
 
         String dateColumn = getSortColumnForTag(tag);
-        String[] args = {gapMarkerDate, tag.getTagSlug(), Integer.toString(tag.tagType.toInt())};
+        String[] args = {tag.getTagSlug(), Integer.toString(tag.tagType.toInt()), gapMarkerDate};
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java]: Wow, can't believe I missed this when I wrote the original code. Glad you caught it!

Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java]: 👍

**Comment by nbradbury** [comment]
:shipit:

**Comment by designsimply** [comment]
I wasn't sure how to change `ReaderConstants.READER_MAX_POSTS_TO_REQUEST` locally, but I did spot check this and found missing posts in the app compared to my web view. I recorded some videos and here is a screenshot showing what I found to be missing. I don't really have good steps to reproduce as I simply spot-checked my normal account (a8c, staging) to test this so I am not sure the issue needs to be re-opened but I did want to leave a quick note showing what I found.

screen shot 2018-05-22 at tue may 22 4 46 01 pm

Video from the app: [2m21s](https://cloudup.com/cY990M0GQr9)
<sup>Tested with Pixel, Android 8.1.0, WPAndroid alpha-110.</sup>

Video from the web: [1m6s](https://cloudup.com/cDtJDbjTyVA)
<sup>Tested with Chrome 66.0.3359.139 on macOS 10.13.4.</sup>

**Comment by malinajirka** [comment]
Thank you for your comment;). It seems that we haven't fixed all the bugs:(.

@nbradbury AFAIRemember we use different version of the api than Calypso. Do you think these two APIs might return different results?

**Comment by nbradbury** [comment]
@malinajirka I'd be surprised if they returned different results but I guess it's possible. To find out for sure, I recommend asking in the #reader Slack channel or their P2.

**Comment by malinajirka** [comment]
I've tried to reproduce the behavior on all of my accounts without success:(.

However there is a case which doesn't actually work - > when you fetch posts in the app and than you start following a new site. In that case older post from the newly followed site might be missing -> the gap wasn't detected (when the posts were fetched), since there wasn't any gap at that time.

@nbradbury Can you think of any solution? Partial solution I can think of is to remove all posts when the user manually refreshes the list (with the pull-to-refresh gesture), but it will drastically reduce number of posts which are being cached.

@designsimply Do you think it might have been this case or did you just logged in and the posts were missing? 

Thanks!

**Comment by malinajirka** [comment]
Another case which won't probably work is when a post is published with a date in the past.

**Comment by nbradbury** [comment]
> Can you think of any solution?

I'm not sure how feasible this is, but we could detect when a site has been added and fetch its posts separately. That's probably overkill, though, especially since the user can already tap the post header to see all posts from that site.

**Comment by nbradbury** [comment]
@malinajirka Your comment about clearing cached posts on PTR made we wonder how important keeping cached posts really is. I'm not sure how we determine whether users really want to keep older posts, but looking at our analytics less than a fourth of them perform an infinite scroll (to load more posts) when using the reader.

**Comment by malinajirka** [comment]
>we could detect when a site has been added and fetch its posts separately.
I agree with you that it feels like an overkill.

Thanks @nbradbury for the insights! Since only 1/4 of users perform an infinite scroll and we've added Save-for-later feature I think it's save to clear the cache on PTR. I've created a new ticket #7834. However if you feel it's not a good idea or we should try to find more analytics data or you have any other suggestions, please feel free to comment on or close the ticket. Thanks!!
