### PR TITLE
Disable navigation in post preview

### LINKED ISSUE #4141: Disable links in post preview
Currently, when you preview a post you get a fully functional in-app browser. As a result, you can follow links e.g. to WP Admin or Calypso in that browser view, which causes confusion (and frustration when the in-app browser does not behave as expected).

### Steps to reproduce

1. Open the WordPress app
2. Go to the My Site tab
3. Select a site
4. Select Blog Posts
5. For a non-local post (published or draft), select View
6. On the preview screen, tap a link in the admin bar to navigate away from the site. For example, tap "Reader" and then "Followed Sites" to open the Reader.

Result: You can navigate away from the site and end up using the in-app browser as a regular browser.

We should disable links in the post preview screen so users can't browser/navigate away from the preview. (This feature is already in the iOS app.)

##### Tested on Nexus 9, Android 6.0.1, WPAndroid alpha-10

### PR DESCRIPTION
**Pull request by daniloercoli**
Fixes #4141 by adding a list of allowed URLs the web view could load.

Note that "top navigation" is still visible, and the top items open menus, but the links in those menus are disabled (same in iOS). It’s not ideal, hiding the masterbar entirely would be the best, but it’s possible atm.

To test:
- Open the WordPress app
- Go to the My Site tab
- Select a site
- Select Blog Posts
- For a non-local post (published or draft), select View
- On the preview screen, tap a link in the page, or at the bottom of it.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/util/URLFilteredWebViewClient.java [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+
+import java.util.ArrayList;
+import java.util.List;
+
+/**
+ * WebViewClient that adds the ability of restrict URL loading (navigation) to a list of allowed URLs.
+ * Generally used to disable links and navigation in admin pages.
+ */
+public class URLFilteredWebViewClient extends WebViewClient {
+    ArrayList<String> allowedURLs = new ArrayList<>();
```
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/util/URLFilteredWebViewClient.java]: Would make sense to use a `Set` instead of a `List` here since we only use it to check for `.contains()` later in `shouldOverrideUrlLoading`

**Comment by maxme** [comment]
I wonder if we should show a toast message like `Links disabled on the preview screen` when the user tries to tap on links here. It's a bit weird to tap a link, wait for it to load, but nothing happens.

File: WordPress/src/main/java/org/wordpress/android/util/URLFilteredWebViewClient.java (hunk 1 above)
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/util/URLFilteredWebViewClient.java]: Agree, will change it to `Set`.

**Comment by daniloercoli** [comment]
I've a toast that informs users Links are disabled on the preview screen.

**Comment by maxme** [comment]
Looks good and can be reused in other place if/when we need it (Theme preview maybe?).
:shipit:

**Comment by daniloercoli** [comment]
@kwonye Any thoughts on reusing this in ThemePreview?

**Comment by kwonye** [comment]
Theme Preview actually hides the masterbar already. That said, I'll make sure to keep this in mind for any other webviews, thanks!
