### PR TITLE
now showing unlimited storage space for business plans

### LINKED ISSUE #7571: Media: storage space available for a business plan says 1,023.7 GB while the plans page says it's unlimited
### Expected behavior

I expected the media quota for a WP.com Business Plan to be unlimited.

### Actual behavior

I see "Space Used 0.3% of 1,023.7 GB".

### Steps to reproduce the behavior

1. Select a WordPress.com Business Plan (non-Atomic) site in the app.
1. Make sure you've uploaded some media to the site.
1. Go to My Sites > Settings > Space Used and check to see if the total amount of space allotted matches the storage space noted for the plan at https://wordpress.com/pricing/ [screenshot](https://user-images.githubusercontent.com/1119271/38110122-d1c9fa04-3357-11e8-9172-fe7bfddbcc4d.png)

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #7571 

To test:
1. select a site with a Business Plan
2. on the main screen, go to Settings
3. scroll down to the Media section and observe the "Space Used" section under "Media" shows the amount of space used, "of unlimited", i.e. `2.8 GB of unlimited`, as shown in the screenshot below

untitled 4

cc @nbradbury as you mentioned this particular case in #7569 🙇

### CODE REVIEW

**Comment by mzorz** [comment]
Travis  is 💚 now @nbradbury 🙇

File: WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsInterface.java [hunk 1]
```diff
@@ -1051,9 +1052,17 @@ private void loadCachedSettings() {
                     mContext.getString(R.string.file_size_in_megabytes),
                     mContext.getString(R.string.file_size_in_gigabytes),
                     mContext.getString(R.string.file_size_in_terabytes) };
-            String spaceAllowed = FormatUtils.formatFileSize(mSite.getSpaceAllowed(), units);
-            String quotaAvailableSentence = String.format(mContext.getString(R.string.site_settings_quota_space_value),
-                    percentage, spaceAllowed);
+
+            String quotaAvailableSentence;
+            if (mSite.getPlanId() == PlansConstants.BUSINESS_PLAN_ID) {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsInterface.java]: Do we also need to consider `JETPACK_BUSINESS_PLAN_ID` here?

Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsInterface.java]: Good question @nbradbury I checked this morning with @elibud and jetpack plans only count for CDN unlimited storage / backup storage, but the actual site content storage is not something jetpack would cover (i.e. a jetpack connected site is self hosted so storage is up to whoever is giving the customer such a service)

**Comment by nbradbury** [comment]
:shipit:
