### PR TITLE
Handle audio files in media browser

### LINKED ISSUE #2474: Incorrect handling of audio files in media browser
I have several MP3s in my media library, and they display incorrectly in the media browser. When I first visit the media browser there's just an empty white box for each MP3, but after scrolling that white box changes to a thumbnail of one the images in my library.

device-2015-03-29-091401

### PR DESCRIPTION
**Pull request by fadils**
Fix #2474

### CODE REVIEW

File: libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/MediaUtils.java [hunk 1]
```diff
@@ -71,6 +71,13 @@ public static boolean isVideo(String url) {
                 url.endsWith(".3g2");
     }
 
+    public static boolean isAudio(String url) {
+        if (url == null) {
+            return false;
+        }
+        return url.endsWith(".mp3") || url.endsWith(".ogg") || url.endsWith(".wav");
```
Comment (nbradbury) [inline libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/MediaUtils.java]: This will catch the most prevalent audio file formats, but might be worth adding .wma, .aiff, .aif, .aac, and .m4a.

**Comment by nbradbury** [comment]
Looks good! :shipit:
