### PR TITLE
Fix #6071 add more context to action buttons

### LINKED ISSUE #6071: Reader: Add more context to action buttons on posts
### Expected behavior

When I navigate the Reader in the Android app with a screen reader, I expect to find more context on buttons.

### Actual behavior

* I found the "Visit" icon button was unlabeled. The word "Visit" lacked context for a screen reader user. I want to know what I'm visiting. This can be combined into one button, labeled with "Visit Post Title Name" "Post Title Name" can be hidden visually.
* The Likes button should be labeled with Like "Post Title Name" Has 77 Likes. Or Like "Post Title Name" No Likes yet. You could also communicate state here. So if a post is in a liked state, it could say: Like "Post Title Name" Pressed Has 77 Likes (or  No Likes yet).
*  Similarly with the Comments button, it needs a more specific label. Comment on "Post Title Name"
* The More button is labeled, but could use more context. "Follow Site Menu" maybe?

### Steps to reproduce the behavior

* Start Talk Back
* Open WordPress app
* Open Reader.
* Begin navigating a list of post by swiping right to navigate forward, reaching the action button area.

##### Tested on [device], Android [version]

* Tested on Nexus 6P, Version Alpha-60.

### PR DESCRIPTION
**Pull request by maxme**
Fix #6071 add more context to action buttons

props to @iegorka

I only fixed a minor margin issue in 3ca1417 and targeted the `develop` branch.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderPostAdapter.java [hunk 1]
```diff
@@ -436,6 +437,8 @@ private void renderPost(int position, ReaderPostViewHolder holder) {
             params.topMargin = titleMargin;
         }
 
+        holder.visit.setContentDescription(holder.cardView.getContext().getString(R.string.reader_label_visit) + " " + post.getTitle());
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderPostAdapter.java]: I'm not sure about this. First, is it locale-friendly to append the post title to the word "Visit?" Also, it seems a bit confusing to have "Visit [Title of Post]" - it's not clear to me that I'll be visiting the post unless I already know that's the title of the post. How about just updating the layout XML instead and using "Visit post" or the existing "View in browser" (`R.string.view_in_browser`)?

File: WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderPostAdapter.java [hunk 2]
```diff
@@ -785,6 +788,8 @@ private void showComments(final ReaderPostViewHolder holder, final ReaderPost po
         if (canShowComments) {
             holder.commentCount.setCount(post.numReplies);
             holder.commentCount.setVisibility(View.VISIBLE);
+            holder.commentCount.setContentDescription(holder.cardView.getContext().getString(R.string.theme_view) + " "
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderPostAdapter.java]: Similar to my previous comment, is it locale-friendly to append the strings like this? I'm also not wild about using `R.string.theme_view` here since that could be changed in a future themes redesign.

How about simply updating the layout XML to use "View comments?"

File: WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderPostAdapter.java [hunk 3]
```diff
@@ -200,8 +202,7 @@ public void onClick(View view) {
                     }
                 }
             };
-            txtVisit.setOnClickListener(visitListener);
-            imgVisit.setOnClickListener(visitListener);
+            visit.setOnClickListener(visitListener);
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderPostAdapter.java]: 👍

**Comment by nbradbury** [comment]
:shipit:

**Comment by maxme** [comment]
Thanks @iegorka!
