### PR TITLE
fix #2373: new CustomSwipeRefreshLayout with a workaround to catch onTouchEvent IllegalArgumentException

### LINKED ISSUE #2373: Crash report 3.7: pointerIndex out of range in SwipeRefreshLayout
```
java.lang.IllegalArgumentException: pointerIndex out of range
       at android.view.MotionEvent.nativeGetAxisValue(MotionEvent.java)
       at android.view.MotionEvent.getY(MotionEvent.java:2155)
       at android.support.v4.view.MotionEventCompatEclair.getY(MotionEventCompatEclair.java:35)
       at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getY(MotionEventCompat.java:95)
       at android.support.v4.view.MotionEventCompat.getY(MotionEventCompat.java:228)
       at android.support.v4.widget.SwipeRefreshLayout.onTouchEvent(SwipeRefreshLayout.java:772)
```

Workaround for `SwipeRefreshLayout.onTouchEvent`?

https://github.com/android/platform_frameworks_support/blob/5476e7f4203acde2b2abbee4e9ffebeb94bcf040/v4/java/android/support/v4/widget/SwipeRefreshLayout.java#L673-L811

### PR DESCRIPTION
**Pull request by maxme**
fix #2373: new CustomSwipeRefreshLayout with a workaround to catch onTouchEvent IllegalArgumentException

I don't like that solution much (I don't want to maintain a custom `SwipeRefreshLayout`) but I don't see any better workaround for this crash.

### CODE REVIEW

File: libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/ptr/CustomSwipeRefreshLayout.java [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+    public CustomSwipeRefreshLayout(Context context) {
+        super(context);
+    }
+
+    public CustomSwipeRefreshLayout(Context context, AttributeSet attrs) {
+        super(context, attrs);
+    }
+
+    @Override
+    public boolean onTouchEvent(MotionEvent event) {
```
Comment (nbradbury) [inline libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/ptr/CustomSwipeRefreshLayout.java]: This could use a comment explaining why it's necessary, perhaps with a link to the [platform fix](https://github.com/android/platform_frameworks_support/blob/5476e7f4203acde2b2abbee4e9ffebeb94bcf040/v4/java/android/support/v4/widget/SwipeRefreshLayout.java#L673-L811) for reference.

**Comment by nbradbury** [comment]
:shipit:
