### PR TITLE
Crash on the installation of a plugin that is already installed

### LINKED ISSUE #15144: NullPointerException: Attempt to invoke virtual method 'int org.wordpress.android.fluxc.model.SiteModel.getId()' on a n...
**Sentry Url**: https://sentry.io/share/issue/da5b4a53f2eb43c494c88d42c01c3c10/
**User Count**: 102
**Count**: 510
**First Release**: 17.8-rc-1
**First Seen**: 2021-07-15T15:08:33.212000Z
**Last Seen**: 2021-08-06T10:40:22Z
**24 Hours**: 69
**30 Days**: 511

```
NullPointerException: Attempt to invoke virtual method 'int org.wordpress.android.fluxc.model.SiteModel.getId()' on a null object reference
     at org.wordpress.android.ui.plugins.PluginDetailActivity.onSitePluginInstalled(PluginDetailActivity.java:1091)
...
(1 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by irfano**
Fixes #15144 

This PR prevents the crash on the installation of a plugin that is already installed. 

Before merging this,
- [x] https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2793 should be merged, and the FluxC reference should be updated in this PR.

#### Fix on FluxC
Before, FluxC was using the cached data for the plugins of the site. This caused showing the installed plugin as not installed and a crash when the user tried to re-install it.
After the fix, FluxC will always fetch and show the fresh data.

#### Fix on WPAndroid
Even though we disable caching the plugins, this case still can be created by:
- Opening the detail screen of the Jetpack plugin and keeping it open,
- Installing the Jetpack plugin via the web,
- Tapping the INSTALL button on the app (when it's already installed via the web).

To prevent this case, `InstallSitePluginErrorType .PLUGIN_ALREADY_INSTALLED` error type is caught on the app, and the new plugin state is fetched to update the screen.

To test:
**Case 1:** 
1. Launch the app.
2. Add a self-hosted site that is not connected with Jetpack.
3. Go to "My Site → Plugins".
4. Search for the "Jetpack - WP Security, Backup, Speed, & Growth" plugin and tap on it.
5. Install the Jetpack plugin and ensure it's installed successfully without a crash.
6. Open the Plugins screen for your site on the web and verify the Jetpack plugin is installed.
7. Open the "MANAGE" screen in the "Installed" section on the Plugins screen and ensure the Jetpack plugin is in the list.
8. Delete the Jetpack plugin from the web.
9. Repeat item 4.
10. Verify the plugin is displayed as not installed.
11. Repeat 5.

**Case 2:**
1. Install the Jetpack plugin that is already installed by following the instructions in the **Fix on WPAndroid** section.
2. Verify the screen is updated successfully, and the plugin is displayed as installed.

## Regression Notes
1. Potential unintended areas of impact
Disabling caching could also disable storing the site plugins in db.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
I checked the db and verified `SitePluginModel` table is still existing as before.

3. What automated tests I added (or what prevented me from doing so)
"This crash can only be tested as a UI test, and I believe it is a too rare case to include it in the automated tests.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginDetailActivity.java [hunk 1]
```diff
@@ -1102,13 +1103,16 @@ public void onSitePluginInstalled(OnSitePluginInstalled event) {
...
+                fetchPluginDirectory(0);
+            } else {
+                refreshPluginVersionViews();
+                showInstallFailedSnackbar();
+            }
             return;
         }
 
-        mIsInstallingPlugin = false;
-
```
Comment (mkevins) [inline WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginDetailActivity.java:1111]: Thank you for cleaning this up 👍 !

**Review by mkevins — APPROVED** [review]
Thanks for this fix @irfano , and also for improving the nearby code. The code changes look good. I tested this on a Pixel 3a (physical device), first by reproducing the crash on `trunk`, and then confirming that it is fixed with this PR.

One observation I made: on `trunk`, I was not able to reproduce the issue on case 1, but only on case 2. Also, on both `trunk` and this PR, I observed that I had to leave the search screen and come back again to validate step 10 (i.e. I had to do step 4 twice 🤷‍♂️). Since this is not a regression (i.e. this PR fixes case 2 and does not introduce any new issue with step 1), I'm still approving. I just wanted to mention this, in case it was unexpected, or if it is a known existing issue.

**Comment by irfano** [comment]
> I was not able to reproduce the issue on case 1, but only on case 2.

Initially, I couldn't reproduce it either, but later on, it started happening. In any case, it has been fixed now.

> Also, on both trunk and this PR, I observed that I had to leave the search screen and come back again to validate step 10 (i.e. I had to do step 4 twice 🤷‍♂️)

Yes, I noticed that as well. The search screen needs to be updated after the plugin is installed. I will search for existing issues and open a new one for it.

Thank you for the review and testing cases comprehensively. 🚀
