### PR TITLE
Stats: Fall back to using URL when loading blog preview of private blogs

### LINKED ISSUE #2170: Stats: Should we fall back to using URL when loading blog preview of private blogs, or HTTP protected blogs
Some wp.com users have a primary site marked as private, so the Reader API will receive a 403 as response code (ex: https://public-api.wordpress.com/rest/v1/sites/kevinjmorrisuk.wordpress.com ) and the UI shows a simple error message "Unable to show this blog" in a Toast.

screen shot 2015-01-14 at 00 26 55

I don't have much control over the Reader Blog Preview page from Stats, so it's hard for me to do something if an error occurs in the Reader. Should we modify the Blog preview page, and open the blog URL in the in-app browser when something is wrong with the REST API call?

I bet we have the same issue on self-hosted blog that are HTTP password protected.

/cc @nbradbury @roundhill

### PR DESCRIPTION
**Pull request by daniloercoli**
Fix #2170 by checking the "follow" data before opening the follower's primary blog in the reader.
Follow data is empty if the dotcom blog is maked as private. 

Also added an additional check that force the Reader in case the app user is a member of the blog marked as private.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/stats/StatsFollowersFragment.java [hunk 1]
```diff
@@ -191,12 +195,28 @@ protected boolean isExpandableList() {
...
 
         public DotComFollowerAdapter(Activity context, List<FollowerModel> list) {
             super(context, R.layout.stats_list_cell, list);
             this.context = context;
             this.list = list;
             inflater = LayoutInflater.from(context);
+
+            // Read all the dotcomBlog blogs and get the list of home URLs.
+            // This will be used later to check if the user is a member of followers blog marked as private.
+            List <Map<String, Object>> dotComUserBlogs = WordPress.wpDB.getAccountsBy("dotcomFlag=1", new String[]{"homeURL"});
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/StatsFollowersFragment.java]: Consider moving this off the UI thread since it has the potential to cause an ANR. That may sound unlikely, but I've seen some ANRs in the reader that were due to db lookups on the UI thread.

File: WordPress/src/main/java/org/wordpress/android/ui/stats/StatsFollowersFragment.java [hunk 2]
```diff
@@ -216,11 +236,34 @@ public View getView(int position, View convertView, ViewGroup parent) {
...
-                if (!TextUtils.isEmpty(currentRowData.getURL())) {
+            if (mTopPagerSelectedButtonIndex == 0 && !TextUtils.isEmpty(currentRowData.getURL())) {
+                // WPCOM followers with no empty URL
+
+                boolean openInReader = true;
+                if (followData == null) {
+                    // If follow data is empty, we cannot follow the blog, or access it in the reader.
+                    // We need to check if the user is a member of this blog.
+                    // If so, we can launch open the reader, otherwise open the blog in the in-app browser.
+                    openInReader = false;
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/StatsFollowersFragment.java]: This seems like a lot of work to do in `getView()`, where performance is important. Also, could this be simplified to compare domains instead? So `dotComUserDomains` would be a list of domains and here you would simply use:

```
if (followData == null) {
	String domain = UrlUtils.getDomainFromUrl(currentRowData.getURL());
	openInReader = dotComUserDomains.contains(domain);
}
```

Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/StatsFollowersFragment.java]: We should compare the URL of the blog, since Jetpack blogs can live in subfolders.

File: WordPress/src/main/java/org/wordpress/android/ui/stats/StatsFollowersFragment.java (hunk 1 above)
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/StatsFollowersFragment.java]: Nice catch. I've moved the code to a BG thread.

File: WordPress/src/main/java/org/wordpress/android/ui/stats/StatsFollowersFragment.java [hunk 3]
```diff
@@ -63,6 +71,28 @@ public void onCreate(Bundle savedInstanceState) {
...
+        ThreadPoolExecutor blogsListCreatorExecutor = (ThreadPoolExecutor) Executors.newFixedThreadPool(1);
+        blogsListCreatorExecutor.submit(new Thread() {
+            @Override
+            public void run() {
+                // Read all the dotcomBlog blogs and get the list of home URLs.
+                // This will be used later to check if the user is a member of followers blog marked as private.
+                List <Map<String, Object>> dotComUserBlogs = WordPress.wpDB.getAccountsBy("dotcomFlag=1", new String[]{"homeURL"});
+                for (Map<String, Object> blog : dotComUserBlogs) {
+                    if (blog != null && blog.get("homeURL") != null) {
+                        String normURL = UrlUtils.normalizeUrl(blog.get("homeURL").toString()).toLowerCase();
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/StatsFollowersFragment.java]: It seems error-prone to me to duplicate this same URL formatting code [here](https://github.com/wordpress-mobile/WordPress-Android/pull/2180/files#diff-7f97a9a7e8ae77d48b26a20bdb986d46R260) since future devs may not be careful enough to update both of them if they need changing. How about using a separate routine to provide the formatting, like this:

```
private static String normalizeAndRemoveScheme(String url) {
    if (TextUtils.isEmpty(url)) {
        return "";
    }
    String normURL = UrlUtils.normalizeUrl(url.toLowerCase());
    int pos = normURL.indexOf("://");
    if (pos > -1) {
        return normURL.substring(pos + 3);
    } else {
        return normURL;
    }
}
```

**Comment by nbradbury** [comment]
Looks good! :shipit:
