### PR TITLE
Stats - Fix for graph that looks off on low numbers Stats

### LINKED ISSUE #2562: Graph looks a bit off on low numbers Stats
Seems that the graph library grabs the highest number and then uses it as the top line of the graph.
It then tries to find the halfway mark by dividing that by two and displaying that line. However if the highest number is odd it still only displays the half way line as a rounded integer which throws off the visual. 

screenshot_2015-04-20-09-17-42
screenshot_2015-04-17-23-53-58

### PR DESCRIPTION
**Pull request by daniloercoli**
Fix #2562 by making sure the highest label number is always even, so the halfway mark is correctly balanced in the middle of the graph.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/stats/StatsBarGraph.java [hunk 1]
```diff
@@ -286,6 +286,22 @@ protected double getMinY() {
...
+    // Make sure the highest number is always even, so the halfway mark is correctly balanced in the middle of the graph
+    // Also make sure to display a default value when there is no activity in the period.
+    @Override
+    protected double getMaxY() {
+        double maxY = super.getMaxY();
+        if (maxY == 0) {
+            return 10;
+        }
+
+        if (maxY % 2 == 0) {
```
Comment (tonyr59h) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/StatsBarGraph.java]: nitpick; could be replaced with `return maxY + (maxY % 2);` if you want to get tricky ;)

File: WordPress/src/main/java/org/wordpress/android/ui/stats/StatsBarGraph.java [hunk 2]
```diff
@@ -286,6 +286,22 @@ protected double getMinY() {
         return 0;
     }
 
+    // Make sure the highest number is always even, so the halfway mark is correctly balanced in the middle of the graph
+    // Also make sure to display a default value when there is no activity in the period.
+    @Override
+    protected double getMaxY() {
+        double maxY = super.getMaxY();
+        if (maxY == 0) {
+            return 10;
```
Comment (tonyr59h) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/StatsBarGraph.java]: Could you throw this into a constant?

**Comment by tonyr59h** [comment]
All good to merge when the constant is in :+1:

File: WordPress/src/main/java/org/wordpress/android/ui/stats/StatsBarGraph.java (hunk 2 above)
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/StatsBarGraph.java]: Done.

File: WordPress/src/main/java/org/wordpress/android/ui/stats/StatsBarGraph.java (hunk 1 above)
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/StatsBarGraph.java]: I like it!!

**Comment by tonyr59h** [comment]
:shipit:
