### PR TITLE
Hotfix - Consolidated Media Picker : Resolve issue where site is null during the avatar picker flow

### LINKED ISSUE #14699: NullPointerException: Attempt to invoke virtual method 'boolean org.wordpress.android.fluxc.model.SiteModel.isWPCom()' ...
Sentry Issue: [WORDPRESS-ANDROID-1E1Z](https://sentry.io/organizations/a8c/issues/2408055193/?referrer=github_integration)

```
NullPointerException: Attempt to invoke virtual method 'boolean org.wordpress.android.fluxc.model.SiteModel.isWPCom()' on a null object reference
    at org.wordpress.android.util.WPMediaUtils.getSitePlanForMimeTypes(WPMediaUtils.java:248)
    at org.wordpress.android.util.WPMediaUtils.isMimeTypeSupportedBySitePlan(WPMediaUtils.java:260)
    at org.wordpress.android.util.MediaUtilsWrapper.isMimeTypeSupportedBySitePlan(MediaUtilsWrapper.kt:60)
    at org.wordpress.android.ui.mediapicker.loader.DeviceListBuilder.loadMedia(DeviceListBuilder.kt:107)
    at org.wordpress.android.ui.mediapicker.loader.DeviceListBuilder.access$loadMedia(DeviceListBuilder.kt:27)
...
(7 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by jd-alexander**
Fixes #14699

## Description 
This PR resolves a crash that was being caused when the `Consolidated Media Picker` was being utilized to select an avatar via the `Me` screen. 

The issue was that for most flows, a site is available so the `mediaUtilsWrapper.isMimeTypeSupportedBySitePlan(
                                site,
                                mimeType
                        )` would work as expected but in this case, when selecting an avatar, the site can be empty, so this PR adds null-safety to the usage of the `SiteModel` within the `DeviceListBuilder`. 
                        
With this in place, all mime types are automatically supported once a site is not available since the site plan's logic wouldn't be required.
                        
### Verify the bug has been resolved. 

1. Go to the Me screen. 
2. Click `Change Photo`. 
3. Notice the app does not crash. 

### Smoke Testing

Smoke test the media browser https://github.com/wordpress-mobile/WordPress-Android/pull/14353 The existing behavior is fine since this null-safety change just ensures the functionality works as it would without a site. 

## Regression Notes
1. Potential unintended areas of impact
The potential areas of impact by this change would be other behavior that relies on the `MediaPicker`. Since the code modifications here are related to enabling the support of a mime type when a site isn't available, the remaining logic functions as is, before these changes were introduced in #14353

2. What I did to test those areas of impact (or what existing automated tests I relied on)

- I tested the "Change Photo" flow in the Me screen. 
- I verified that on a free site I wasn't able to upload a `key`, `zip` file and on a premium one I was able to do that. 
- I verified that on a free site, I am not able to upload audio files, but on a premium plan I am able to. 
- I verified that the File, Audio, Video, Image Block all work as expected with the Media Picker.

3. What automated tests I added (or what prevented me from doing so)
In this case, no automated tests were added for this flow. Pre-existing `MediaPicker` related tests verify that the changes did not break the existing functionality.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/mediapicker/MediaPickerViewModel.kt [hunk 1]
```diff
@@ -353,8 +353,10 @@ class MediaPickerViewModel @Inject constructor(
             this.mediaLoader = mediaLoaderFactory.build(mediaPickerSetup, site)
             this.mediaInsertHandler = mediaInsertHandlerFactory.build(mediaPickerSetup, site)
             launch {
-                mediaLoader.loadMedia(loadActions).flowOn(bgDispatcher).collect { domainModel ->
-                    _domainModel.value = domainModel
+                site?.let {
```
Comment (planarvoid) [inline WordPress/src/main/java/org/wordpress/android/ui/mediapicker/MediaPickerViewModel.kt]: As discussed in DM, it is valid to have an empty site when selecting avatar without a site so I'd rather make the call in `DeviceListBuilder` null-safe.

Comment (jd-alexander) [reply WordPress/src/main/java/org/wordpress/android/ui/mediapicker/MediaPickerViewModel.kt]: Understood. Thanks for sharing. I will make the necessary changes.

File: WordPress/src/main/java/org/wordpress/android/ui/mediapicker/loader/DeviceListBuilder.kt [hunk 2]
```diff
@@ -103,8 +103,16 @@ class DeviceListBuilder(
         val deviceMediaList = deviceMediaLoader.loadMedia(mediaType, filter, pageSize, lastDateModified)
         val result = deviceMediaList.items.mapNotNull {
             val mimeType = deviceMediaLoader.getMimeType(it.uri)
-            if (mimeType != null && MediaUtils.isSupportedMimeType(mimeType) &&
-                    mediaUtilsWrapper.isMimeTypeSupportedBySitePlan(site, mimeType)) {
+            val isMimeTypeSupported = mimeType != null && site?.let {
```
Comment (jd-alexander) [inline WordPress/src/main/java/org/wordpress/android/ui/mediapicker/loader/DeviceListBuilder.kt:106]: I ended up putting the condition-based logic into a variable ( here and below) because detekt was complaining that it was too complex.

**Comment by jd-alexander** [comment]
Currently adding a release notes entry.

**Review by oguzkocer — APPROVED** [review]
For a hotfix, this changeset is good enough. However, I'd really appreciate if you can refactor the logic to remove duplication and make it a bit easier to understand once this is merged to develop @jd-alexander.

I've verified the crash in `17.3.1` and the fix in this branch. 👍

**Comment by jd-alexander** [comment]
@oguzkocer thanks for the review

> For a hotfix, this changeset is good enough. However, I'd really appreciate if you can refactor the logic to remove duplication and make it a bit easier to understand once this is merged to develop @jd-alexander.

Great suggestion. The logic can definitely be moved to the `MediaUtils` class for code reusability and clarity.
