### PR TITLE
Issue/5217 stop image upload

### LINKED ISSUE #5217: Stopping a media upload doesn't remove the media from the post
### Expected behavior

If I tap to stop an image from uploading, I expect the image to be removed from the post.

### Actual behavior

If I tap to stop the upload while an image is uploading (in Aztec), the image stops uploading, but it stays in the post. The image retains the "uploading" status (so I can keep tapping it and selecting "stop upload" over and over).

It looks fine in the editor because the image is being displayed from my device but it's broken on the site.

##### Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-35

### PR DESCRIPTION
**Pull request by 0nko**
Fixes #5217.

I've branched off of `issue/5296-image-settings` because this PR depends on the changes there. That's why the [image settings PR](https://github.com/wordpress-mobile/WordPress-Android/pull/5709) needs to be merged first.

To test:

1. Start uploading an image
2. Tap on the image
3. Tap OK to cancel the upload
4. Notice the image is removed

### CODE REVIEW

File: libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java [hunk 1]
```diff
@@ -883,17 +882,31 @@ public void onClick(DialogInterface dialog, int id) {
...
+                            mEditorFragmentListener.onMediaRetryClicked(localMediaId);
+                        } catch (NumberFormatException e) {
+                            // invalid id
+                        }
                         dialog.dismiss();
                     }
                 });
 
+                // stop the media upload while the dialog is being shown
+                // otherwise the upload might finish and we won't find the element for removal
```
Comment (hypest) [inline libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java]: This seems pretty drastic. Even canceling the dialog will cause a re-upload of the image, consuming power and network traffic, both quite important resources on the mobile.

The commit title mentions that the upload will "resume" but I don't think it actually resumes. I think it restarts from the beginning, right?

> we won't find the element for removal

I don't think this is be a big problem. The removal will fail silently and the user can delete the image again if they really want to. Silently is not optimal so, we can put up a Toast message if we want, saying that the image has finished uploading anyway.

Comment (0nko) [inline libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java]: You're right, it is drastic and it's true the upload is restarted. I just couldn't figure out the a better solution. But silently failing with a toast is a reasonable compromise so I'll go ahead with that. Thanks for the tip 👍.

**Comment by 0nko** [comment]
Done.
