### PR TITLE
Using AztecParser + Plugins to do background async media operation on Post content

### LINKED ISSUE #6531: Async Media: Video not uploaded correctly after exiting Aztec editor
### Expected behavior

I expect that with async media uploads, when I exit the editor, the video will continue uploading in the post.

### Actual behavior

In Aztec, if I exit the editor while uploading a video, the video is not uploaded correctly:

- The draft is uploaded with a reference to a local video file on the device.
- When I reopen the editor and tap on the video, it tells me the file is still uploading but the progress bar doesn't move and it never finishes the upload.

I confirmed that the same video file uploads correctly if I remain in the editor during the upload; it's only a problem if I exit the editor before the upload finishes.

### Steps to reproduce the behavior

1. Enable the Aztec editor.
2. Start a new post.
3. Add a video to the post.
4. Before the video finishes uploading, exit the editor. Note that there is no message about "Uploading Media" on the post in the post list, and the draft is saved/uploaded to the server.
5. Open the editor again. Tapping on the video or trying to switch to HTML mode indicates that the video is still uploading, but there is no sign that the upload is happening.
6. In a browser, open the post and view it in HTML mode. Note that a reference to a local video on the device is included in the `[video]` shortcode.

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #6531, supersedes #6536 

Video uploads started to work incorrectly in async after upgrading Aztec to beta 7, where the `VideoShortcodePlugin` was introduced.
We're fixing that by making our background processing also make use of the necessary plugins to be able to parse Post contents correctly.
Also, we're now only using `AztecParser` for any non-UI (i.e. background) operations  on Posts while async media operations are happening.

To test videos:
1. start a new draft
2. include a video
3. exit the editor, and observe the posts list show the post upload progressing
4. enter the editor for that post again, observe the upload progress re-attaches seamlessly
5. exit the editor again, as many times as you wish, it should still be working alright
6. confirm the video is uploaded when it finished while you're within the editor
7. make tests again and confirm the video is finished uploading while you're out of the editor.

Also, given this PR touches a bit of how all processing is done, pelase test uploading images and going back and forth the editor, specially letting uploads finish while you're outside the editor.

cc @aforcier

### CODE REVIEW

File: libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java [hunk 1]
```diff
@@ -1469,19 +1472,52 @@ private static void addVideoUploadingClassIfMissing(AztecAttributes attributes)
         attributes.setValue(ATTR_CLASS, attrs.getAttributes().getValue(ATTR_CLASS));
     }
 
+    private static Attributes getElementAttributes(Spanned content, AztecText.AttributePredicate predicate) {
```
Comment (daniloercoli) [inline libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java]: May I suggest to change the name of this method to `getFirstElementAttributes`?

Comment (daniloercoli) [inline libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java]: Do you think we should find a way to merge this method with the one below  `getAllElementAttributes` to not repeat code? Maybe get all elements and just return the first of the list? (Maybe this is not wise performances side :))

Comment (mzorz) [inline libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java]: good idea @daniloercoli ! addressed in b616388

File: libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java [hunk 2]
```diff
@@ -1469,19 +1472,60 @@ private static void addVideoUploadingClassIfMissing(AztecAttributes attributes)
...
+            return null;
+        }
+    }
+
+    private static @NonNull List<Attributes> getAllElementAttributes(Spanned content,
+                                                                  AztecText.AttributePredicate predicate) {
+        return getElementAttributes(content, predicate, false);
+    }
+
+    private static @NonNull List<Attributes> getElementAttributes(Spanned content,
```
Comment (aforcier) [inline libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java]: Duplicating `getElementAttributes()` and `updateElementAttributes()` from `AztecText` feels a bit ugly - I think it works for now, but we should probably look at tucking these back into the Aztec library at some point.

File: libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java [hunk 3]
```diff
@@ -1494,12 +1538,11 @@ public static String replaceMediaFileWithUrl(Context context, @NonNull String po
             addDefaultSizeClassIfMissing(attrs);
 
             // clear overlay
-            content.clearOverlays(predicate);
-            content.updateElementAttributes(predicate, attrs);
-            content.refreshText();
+            // content.clearOverlays(predicate);
```
Comment (aforcier) [inline libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java]: Is this no longer necessary? If there's a reason to leave it in, commented out, it could use an explanatory comment.

**Comment by aforcier** [comment]
Looks great aside from [my comment above](https://github.com/wordpress-mobile/WordPress-Android/pull/6540#discussion_r133917035) :+1:.

File: libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java (hunk 3 above)
Comment (mzorz) [inline libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java]: oops! forgot to remove :) - removed in f499b40

**Comment by aforcier** [comment]
:shipit:
