### PR TITLE
Reverting paging3 migration

### LINKED ISSUE #14860: Post list fails to refresh or crashes the app when you scroll quickly
### Expected behavior
The posts list refreshes in all cases

### Actual behavior

The post list fails to refresh when you scroll down too quickly (sometimes causing a crash) or after cleaning the cache

<details>
 <summary>Unable to refresh</summary>

https://user-images.githubusercontent.com/304044/122415971-0372e100-cf91-11eb-8c51-00b0e55de301.mp4
</details>

<details>
 <summary>Crash log</summary>

```
    java.lang.IllegalArgumentException: Illegal start(60) or end(80) position for totalSize(62)
        at org.wordpress.android.fluxc.model.list.datasource.InternalPagedListDataSource.getItemIds(InternalPagedListDataSource.kt:61)
        at org.wordpress.android.fluxc.model.list.datasource.InternalPagedListDataSource.getItemsInRange(InternalPagedListDataSource.kt:51)
        at org.wordpress.android.fluxc.model.list.PagedListPositionalDataSource.loadRangeInternal(PagedListFactory.kt:58)
        at org.wordpress.android.fluxc.model.list.PagedListPositionalDataSource.loadRange(PagedListFactory.kt:49)
        at androidx.paging.PositionalDataSource.loadRange(PositionalDataSource.kt:430)
        at androidx.paging.PositionalDataSource.load$paging_common(PositionalDataSource.kt:348)
        at androidx.paging.LegacyPagingSource$load$2.invokeSuspend(LegacyPagingSource.kt:116)
        at androidx.paging.LegacyPagingSource$load$2.invoke(Unknown Source:10)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
        at androidx.paging.LegacyPagingSource.load(LegacyPagingSource.kt:115)
        at androidx.paging.LegacyPageFetcher$scheduleLoad$1.invokeSuspend(LegacyPageFetcher.kt:53)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
```
</details>

This seems to be new to `17.6` [according to Sentry](https://sentry.io/share/issue/09d3b8128d0e448abd3e8c3be693bcd9/)

#### By scrolling
1. Go to the post list and scroll down quickly
2. Notice that the list fails to refresh **or the app crashes**
3. Notice that the list is empty (and it shouldn't)
4. Try to refresh by pulling down
5. Notice that the screen does not refresh
6. Go back to the My Sites screen
7. Open the post list again
8. Notice the the posts are there

#### By clearing the cache (not reproduced consistently)
1. Go to the app settings and clear the cache and stored data
2. Open the app and login again
3. Go to the post list
4. Notice that the list is empty (and it shouldn't)
5. Try to refresh by pulling down
6. Notice that the screen does not refresh
7. Go back to the My Sites screen
8. Open the post list again
9. Notice the the posts are there

### PR DESCRIPTION
**Pull request by develric**
This cherry pick changes from #14949 as an hotfix for 17.6

NOTE: code that was cherry picked from 17.7 was slightly ahead respect the original code in 17.6. This required adding the `UnifiedCommentListItemDecoration` that was added in 17.7. All this code is behind a feature flag, so as far as it compiles and we confirm the fix works we should be ok.

Reporting below the description from the original PR for convenience.

Fixes #14860

Migration to Paging 3 is causing some issues with Post List. We need a bit more for a partial or full migration to Paging 3.

This PR removes the Paging 3 dependency and comments out the code that is using it, since it's behind the feature flag.

To test:
- Make sure that the app builds without any issue.
- Go to the post list and scroll down quickly
- Notice that post loading is performed correctly, the list remains visible and nothing crashes.

## Regression Notes
1. Potential unintended areas of impact
We are removing the offending library so should be none.

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/comments/unified/CommentPagingSource.kt [hunk 1]
```diff
@@ -1,48 +1,55 @@
...
-            } else {
-                commentModel.status = CommentStatus.APPROVED.toString()
-            }
-
-            commentListItems.add(commentModel)
-        }
-        return commentListItems
-    }
+/**
+ * Temporarily commented out until migration between Paging 2 and 3 is sorted out.
```
Comment (AliSoftware) [inline WordPress/src/main/java/org/wordpress/android/ui/comments/unified/CommentPagingSource.kt:4]: nit: worth a reference to the Slack discussion, Sentry issue, and past PRs here to track it when we get back to it? 🤔

File: WordPress/src/main/java/org/wordpress/android/ui/comments/unified/UnifiedCommentListFragment.kt [hunk 2]
```diff
@@ -37,18 +39,35 @@ class UnifiedCommentListFragment : Fragment(R.layout.comment_list_fragment) {
...
+//            }
+//            else -> {
+//            }
+//        }
+//    }
+
+    override fun onDestroyView() {
+        super.onDestroyView()
+        binding = null
+    }
```
Comment (AliSoftware) [inline WordPress/src/main/java/org/wordpress/android/ui/comments/unified/UnifiedCommentListFragment.kt:69]: I don't see this part being _added_ in the diff of the cherry-picked commit – https://github.com/wordpress-mobile/WordPress-Android/pull/14949/files#diff-d3f669617284dbfa52ea7b4aeb770607c0f206258a309d4140a8a417153a1b02L65, but I see it was already there back then tho.
Just double-checking this re-addition is thus intentional given this was not part of the release/17.6 branch when we did 17.6 back then.

File: WordPress/src/main/java/org/wordpress/android/ui/comments/unified/UnifiedCommentListViewModel.kt [hunk 3]
```diff
@@ -1,55 +1,76 @@
...
-                    )
-                }
-                        .insertSeparators { before, after ->
-                            when {
-                                before == null -> SubHeader("Date Sub Header", -1)
-                                // TODO add the logic for determining if subheader is necessary or not
-                                else -> null
-                            }
-                        }
-            }
```
Comment (AliSoftware) [inline WordPress/src/main/java/org/wordpress/android/ui/comments/unified/UnifiedCommentListViewModel.kt:52]: Side note that the diff is slightly different here from what was removed in [the other PR](https://github.com/wordpress-mobile/WordPress-Android/pull/14949/files#diff-bb41a4453c1a2ef9ede4980e28a061c4aedc44774ee4434bf93b19bf61e49d9dL36-L90). Probably expected given this part of the code like changed between release and develop, but just wanted to highlight this to double-check that the different code being removed did not have side effects that the original didn't have.

Also, that means that the code that is actually added and commented out on the following lines 18-73 does not match what was removed, so when we get back to this later to "revert this revert" and try to get back to migrating to paging 3, there is a risk that we would just uncomment the lines 18-73 (instead of reverting this PR) and land in a different state of the code that what was expected, introducing regressions and bugs or behavior changes that were fixed by the new code that was _removed_ above but were still present in the code that was _commented_ below

File: WordPress/src/main/java/org/wordpress/android/ui/comments/unified/UnifiedCommentListItemDecoration.kt [hunk 4]
```diff
@@ -0,0 +1,90 @@
+package org.wordpress.android.ui.comments.unified
```
Comment (AliSoftware) [inline WordPress/src/main/java/org/wordpress/android/ui/comments/unified/UnifiedCommentListItemDecoration.kt:1]: This whole file was not part of the other PR. Is this file addition expected there?

**Review by AliSoftware — COMMENTED** [review]
Left a few questions while comparing the diff with the other PR.

Note that I'm no Android developer and only blindly compared the diff with other PR, or compared what was removed with what was commented, without trying to decipher the Android logic behind it, so those are merely questions and incentives to double-check, but might be false positives.

Even if there are differences in the two diffs that are correct and make sense because develop and release/17.6 differ, I think it would still be valuable to ensure the code that is marked as +added but commented out matches the code that is marked as -removed in the diff, otherwise this will lead to regressions when we uncomment them later.

**Comment by AliSoftware** [comment]
Note that the BuildKite CI failure (pipeline-pipeline-upload) is expected, as we didn't have BuildKite configured in the release branch yet back then.

File: WordPress/src/main/java/org/wordpress/android/ui/comments/unified/UnifiedCommentListItemDecoration.kt (hunk 4 above)
Comment (develric) [reply WordPress/src/main/java/org/wordpress/android/ui/comments/unified/UnifiedCommentListItemDecoration.kt:1]: as mentioned in the PR description

>NOTE: code that was cherry picked from 17.7 was slightly ahead respect the original code in 17.6. This required adding the UnifiedCommentListItemDecoration that was added in 17.7. All this code is behind a feature flag, so as far as it compiles and we confirm the fix works we should be ok.

being the code behind a feature flag AFAIU if it compiles it should not have an impact since it is not run and we removed the dependency on the paging 3 lib (happy to have your thoughts on this as well @ashiagr 🙇 )

**Comment by develric** [comment]
hey @AliSoftware 👋 , was reading your notes above; let me share my reasoning so we can double-check if it makes sense (and adapt to whatever we decide it's the best approach 🙇 ; cc @ashiagr for another opinion as well)

- As you said code evolved a bit from 17.6 to 17.7
- my intention was to cherry pick the original fix PR changes only adding minimal changes to the 17.6 to allow building the cherry picked changes (this for example is the case for adding `UnifiedCommentListItemDecoration`
- All the code changes above are behind a feature flag so as far as it compiles (and we removed the dependency on paging 3) the code should not be run at all
- as for the conflicts when coming back to develop; I think it's something we will need to deal with when bringing back the code to develop after the hotfix. In my understanding the code we cherry picked above will be aligned with develop and we will merge the code under the comments.unified package probably just accepting the develop version (but @khaykov will know more about it)

Does the above makes sense? (especially the last point). 

Another possibility is to manual comment out the not needed code instead of cherry picking from the original fix

File: WordPress/src/main/java/org/wordpress/android/ui/comments/unified/UnifiedCommentListItemDecoration.kt (hunk 4 above)
Comment (ashiagr) [reply WordPress/src/main/java/org/wordpress/android/ui/comments/unified/UnifiedCommentListItemDecoration.kt:1]: Since it behind a feature flag + there are no compilation issues (and we need the new file after the latest changes since last fix) + no fast scrolling/ refresh issues, so 👍 from me.

**Comment by AliSoftware** [comment]
> as for the conflicts when coming back to develop; I think it's something we will need to deal with when bringing back the code to develop after the hotfix. In my understanding the code we cherry picked above will be aligned with develop and we will merge the code under the comments.unified package probably just accepting the develop version (but @khaykov will know more about it)


Actually, after taking my late morning coffee, I realized I was wrong with my suggestion above: the code that is added but commented out in this PR's diff should match what's in `develop`, as opposed to match what was removed in this PR, because as you said once this hotfix lands and is merged back into `develop`, we want the commented-out code to match what's already in `develop` 🙂  (And in fact if we applied my incorrect suggestion, that would lead to conflicts and could be what would risk causing regressions later when we uncomment it as it wouldn't match develop)

So nevermind, sorry for the misleading suggestion, and you were correct in your changes made then 👍  As long as the commented code added matches the commented code in develop we should be good 🙂

**Review by ashiagr — APPROVED** [review]
Thanks for a fast turnaround @develric.  I tested the PR according to the testing steps and could not reproduce the crash. Comments load fine as well after removing the feature flag. 

I agree with your reasoning in https://github.com/wordpress-mobile/WordPress-Android/pull/14968#issuecomment-872106616, 👍 from me.
