### PR TITLE
Fix #3321: uploaded pictures were disappearing in the Media Library

### LINKED ISSUE #3321: Media Library: Image disappears from view shortly after upload - 4.6-rc-3
When uploading a picture to the media library I see it show up in the view momentarily, and then it disappears.  After leaving and going back in it shows up just fine.  Here's a screencap recorded off of my emulator (on a self-compiled apk using the latest source from git) connected to a self-hosted site, although I saw the same problem on the latest beta on my OnePlus One connected to WordPress.com.

https://cloudup.com/iyGvmEjotjP

The difference is that the logfile on the emulator has an exception relating to the media library that isn't present on the real device.  Although you'll see in the video that re-opening the Media Library was unresponsive for a moment, so the exception may be related to that.  The full logfile can be found here:

http://wp-srstancil.rhcloud.com/2015/10/09/wordpress-application-log/

### PR DESCRIPTION
**Pull request by maxme**
* Fix #3321: uploaded pictures were disappearing in the Media Library
* Better experience when uploading mulitpie pictures (ref #3445): uploading states are updated
* Cleaned up events / callbacks in that part of the app

### CODE REVIEW

**Comment by nbradbury** [comment]
This does fix #3321, but the count in the spinner also needs to be updated. When I added an image to an empty media library the count next to "All" remained at zero.

media-zero

**Comment by nbradbury** [comment]
This may be a separate issue, but after uploading several images from the Photos app, they all appear blank in the media browser:

blank-media

File: WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java [hunk 1]
```diff
@@ -501,14 +505,36 @@ public void onBackPressed() {
...
+    public void onEventMainThread(MediaEvents.MediaUploadFailed event) {
+        ToastUtils.showToast(this, event.mErrorMessage, ToastUtils.Duration.SHORT);
+    }
+
+    public void updateOnMediaChanged(String blogId, String mediaId) {
+        if (mediaId == null) {
             return;
         }
-        String blogId = String.valueOf(WordPress.getCurrentBlog().getLocalTableBlogId());
         Cursor cursor = WordPress.wpDB.getMediaFile(blogId, mediaId);
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java]: The addition of the event(s) causes this routine to be called quite frequently, and it's opening a cursor simply to check whether the media file exists. Perhaps it'd be more efficient to add a routine like this to `WordPressDB`?

```
public boolean mediaFileExists(String blogId, String mediaId) {
    return SqlUtils.boolForQuery(db, 
            "SELECT 1 FROM " + MEDIA_TABLE + " WHERE blogId=? AND mediaId=?", 
            new String[]{blogId, mediaId});
}
```

File: WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java [hunk 2]
```diff
@@ -501,14 +505,36 @@ public void onBackPressed() {
...
+    }
+
+    @SuppressWarnings("unused")
+    public void onEventMainThread(MediaEvents.MediaFetched event) {
+        updateOnMediaChanged(event.mLocalBlogId, event.mMediaId);
+    }
+
+    @SuppressWarnings("unused")
+    public void onEventMainThread(MediaEvents.MediaUploadFailed event) {
+        ToastUtils.showToast(this, event.mErrorMessage, ToastUtils.Duration.SHORT);
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java]: We probably want `Duration.LONG` here.

File: WordPress/src/main/java/org/wordpress/android/ui/media/services/MediaEvents.java [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+    public static class MediaUploadFailed {
+        public final String mLocalMediaId;
+        public final String mErrorMessage;
+        MediaUploadFailed(String localMediaId, String errorMessage) {
+            mLocalMediaId = localMediaId;
+            mErrorMessage = errorMessage;
+        }
+    }
+
+    public static class MediaAdded {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/media/services/MediaEvents.java]: Looking at the code, separate events for `MediaAdded`, `MediaFetched` and `MediaStateChanged` aren't necessary. A single `MediaChanged` event could replace all three of these.

**Comment by nbradbury** [comment]
:shipit:
