### PR TITLE
Changed to removeGlobalOnLayoutListener()

### LINKED ISSUE #2341: 3.7 ReaderPostList NoSuchMethod exception
Caused by using API 16 `removeOnGlobalLayoutListener()` instead of the deprecated `removeGlobalOnLayoutListener()` [here](https://github.com/wordpress-mobile/WordPress-Android/blob/release/3.7/WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java).

### PR DESCRIPTION
**Pull request by nbradbury**
Fix #2341 - NoSuchMethod exception resolved by using the deprecated `removeGlobalOnLayoutListener()` instead of `removeOnGlobalLayoutListener()` (which requires API 16).

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java [hunk 1]
```diff
@@ -357,7 +356,6 @@ public void onAttach(Activity activity) {
     /*
      * animate in the blog/tag info header after a brief delay
      */
-    @SuppressLint("NewApi")
```
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java]: This annotation is still needed - `ViewAnimationUtils.createCircularReveal` (that's why travis is :crying_cat_face:)

**Comment by nbradbury** [comment]
@maxme I just re-added @SuppressLint("NewApi"), but it's annoying that Travis requires it here since AS doesn't. The existence of that is what prevented AS lint from warning about the mistake in the first place.

**Comment by nbradbury** [comment]
The Travis build started failing after I switched to `@SuppressLint({"NewApi", "LocalSuppress"})` so I switched back to `@SuppressLint("NewApi")`.
