### PR TITLE
Fixes IllegalArgumentException due to uninitialised site in page template picker

### LINKED ISSUE #15408: IllegalArgumentException: Required value was null.
**Sentry Url**: https://sentry.io/share/issue/57908413e39d4891b640114deac3f418/
**User Count**: 614
**Count**: 818
**First Release**: 17.8
**First Seen**: 2021-08-03T07:48:48.154000Z
**Last Seen**: 2021-10-04T09:03:54Z
**24 Hours**: 54
**30 Days**: 808

```
IllegalArgumentException: Required value was null.
     at org.wordpress.android.viewmodel.mlp.ModalLayoutPickerViewModel$site$2.invoke(ModalLayoutPickerViewModel.kt:65)
     at org.wordpress.android.viewmodel.mlp.ModalLayoutPickerViewModel$site$2.invoke(ModalLayoutPickerViewModel.kt:40)
     at org.wordpress.android.viewmodel.mlp.ModalLayoutPickerViewModel.getSite(null:2)
     at org.wordpress.android.viewmodel.mlp.ModalLayoutPickerViewModel.canShowModalLayoutPicker(ModalLayoutPickerViewModel.kt:139)
     at org.wordpress.android.ui.pages.PagesFragment$setupObservers$2.onChanged(PagesFragment.kt:354)
     at org.wordpress.android.ui.pages.PagesFragment$setupObservers$2.onChanged(PagesFragment.kt:73)
     at org.wordpress.android.viewmodel.SingleLiveEvent$observe$1.onChanged(SingleLiveEvent.kt:50)
     at org.wordpress.android.viewmodel.SingleLiveEvent.setValue(SingleLiveEvent.kt:58)
...
(11 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by antonis**
Fixes #15408

To test:
* I don't have consistent steps to trigger the [reported crash](https://github.com/wordpress-mobile/WordPress-Android/issues/15408). A way to test this may involve using the debugger to set a null value for the SiteModel.
* Verify that the tests pass

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
Added a [test case](https://github.com/wordpress-mobile/WordPress-Android/commit/3613d887c532e743587af305226c4be3f6986ad3)

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by antonis** [comment]
Hey @ParaskP7, @planarvoid 👋 
I've added you as reviewers since you seem to be familiar with this part of the codebase and handling the [case where the SiteModel has not been initialised](https://github.com/wordpress-mobile/WordPress-Android/commit/63d877ad6d063aa03de8795bbb620c677257c255#). Any suggestions for improvements or alternative approaches are more than welcome 🙇

**Comment by ParaskP7** [comment]
👋 @antonis !

> I've added you as reviewers since you seem to be familiar with this part of the codebase and handling the case where the SiteModel has not been initialised. Any suggestions for improvements or alternative approaches are more than welcome 🙇

Thanks for creating the fix, I am on it! 🙏

File: WordPress/src/main/java/org/wordpress/android/viewmodel/mlp/ModalLayoutPickerViewModel.kt [hunk 1]
```diff
@@ -61,15 +61,19 @@ class ModalLayoutPickerViewModel @Inject constructor(
     private val _onCreateNewPageRequested = SingleLiveEvent<PageRequest.Create>()
     val onCreateNewPageRequested: LiveData<PageRequest.Create> = _onCreateNewPageRequested
 
-    private val site: SiteModel by lazy {
-        requireNotNull(siteStore.getSiteByLocalId(selectedSiteRepository.getSelectedSiteLocalId()))
+    private val site: SiteModel? by lazy {
+        siteStore.getSiteByLocalId(selectedSiteRepository.getSelectedSiteLocalId())
```
Comment (ParaskP7) [inline WordPress/src/main/java/org/wordpress/android/viewmodel/mlp/ModalLayoutPickerViewModel.kt]: 1. Praise (❤️): Making the `SiteModel` nullable is definitely the right way to avoid the crash that is happening, especially since the `siteStore.getSiteByLocalId(...)` can return a nullable value. Thanks for making this improvement.
2. History (⏲️): This piece of code was updated as part of this [refactor PR](https://github.com/wordpress-mobile/WordPress-Android/pull/15197), which did a major change to using the `Repository` in favor of the `Prefs` in order to getting a `Selecting Site`, for at least most of the cases. In this instance, the previous logic was using the `Prefs` to do so, but in this PR it was updated to use the `Repository` instead.
3. Suggestion (💡): By making the `SiteModel` nullable, this will solve the crashed, but I wonder whether showing the `Error Screen` instead is better, as the users will not be able to recover from that anyway and thus will not be able to use the `Layout Picker`. I am also seeing that these crashes started happening from the `20th/21st of September 2021`, which is when [18.2](https://github.com/wordpress-mobile/WordPress-Android/releases/tag/18.2) was released, which included the [refactor PR](https://github.com/wordpress-mobile/WordPress-Android/pull/15197) I explained above, which started causing these crashes. Thus, my suggestion would be to maybe update this to `selectedSiteRepository.getSelectedSiteLocalId(true)` in order to revert getting the `Selected Repository` from the `Prefs`. I am still not sure in which situation and why getting it from `Prefs` doesn't crash the app, since it is almost guaranded that when the user enters the `Layout Picker` screen, this `Selected Repository` value will be present in the `Repository` cache. However, maybe something is clearing that cache and getting it from `Prefs` makes it more robust. I am not sure... Maybe this whole flows needs a bit of additional investigating to understand what is what. 🤔

File: WordPress/src/test/java/org/wordpress/android/viewmodel/mlp/ModalLayoutPickerViewModelTest.kt [hunk 2]
```diff
@@ -172,6 +179,14 @@ class ModalLayoutPickerViewModelTest {
         assertThat(viewModel.uiState.value is Error).isEqualTo(true)
     }
 
+    @ExperimentalCoroutinesApi
+    @Test
+    fun `when modal layout picker starts and the site is unavailable errors are handled`() =
```
Comment (ParaskP7) [inline WordPress/src/test/java/org/wordpress/android/viewmodel/mlp/ModalLayoutPickerViewModelTest.kt:184]: Praise (❤️): Kudos for adding this test here!

**Review by ParaskP7 — APPROVED** [review]
👋 @antonis !

I have reviewed and tested this PR as per the instructions, everything works as expected, good job! 🌟 

I have left one suggestion (💡) for you to consider. I am going to approve this PR anyway, since none is blocking. I am **NOT** going to merge this PR yet to give you some time to think about and maybe apply this suggestions. However, feel free to ignore them and merge the PR yourself.

Extra Suggestion (💡): Consider making the `SiteModel site` within the `SiteUtils.isBlockEditorDefaultForNewPost(...)` method explicitly `@Nullable` to make it explicit that this method can accept a nullable site.

File: WordPress/src/main/java/org/wordpress/android/viewmodel/mlp/ModalLayoutPickerViewModel.kt (hunk 1 above)
Comment (antonis) [reply WordPress/src/main/java/org/wordpress/android/viewmodel/mlp/ModalLayoutPickerViewModel.kt]: Thank you for the prompt review @ParaskP7. I really appreciate this 🙇 

> I wonder whether showing the Error Screen instead is better, as the users will not be able to recover from that anyway and thus will not be able to use the Layout Picker

I haven't been able to trigger this behaviour in real conditions but setting a `null` value for the site model should result in an error screen where the user is able to retry (this won't actually work), proceed with a blank page or close the screen.
<details>
<summary>screenshot</summary>

device-2021-10-05-154801
</details>

> I am also seeing that these crashes started happening from the 20th/21st of September 2021, which is when 18.2 was released

It seems that with 18.2 the issue became more common but this started to happen since `17.8` ([e.g.](https://sentry.io/organizations/a8c/issues/2550920306/events/b2eb6b0500924a52b781c68fd8de7946/?project=1438088)) 🤔 

> my suggestion would be to maybe update this to selectedSiteRepository.getSelectedSiteLocalId(true)

I agree with that. I changed it with 7871b05dd010f50dc71a4be3846b033a1276d4d9

> Consider making the SiteModel site within the SiteUtils.isBlockEditorDefaultForNewPost(...) method explicitly @Nullable 

Nice suggestion 👍 . Applied with 1f8f1005aa5adf0ab228977c36c51dd6ffb29144

I also added a release note with 391efede26d747ce1a5714050348031478ae7f27

Comment (ParaskP7) [reply WordPress/src/main/java/org/wordpress/android/viewmodel/mlp/ModalLayoutPickerViewModel.kt]: 👋 @antonis !

Thanks so much for the updates and all your thoughts! 🥇 

> It seems that with 18.2 the issue became more common but this started to happen since 17.8 (e.g.) 🤔

Hmmm, seems weird, let's keep an eye on this. I wonder how can we track this going forward, maybe through the analytics that exist on the `Layout Picker`, at least once a while, and see if the error screen shown increases as time passes-by.

**Comment by ParaskP7** [comment]
👋 @antonis !

Thanks for your updates, those LGTM, I am still on the approved side, feel free to merge when CI completes.

File: WordPress/src/main/java/org/wordpress/android/viewmodel/mlp/ModalLayoutPickerViewModel.kt (hunk 1 above)
Comment (antonis) [reply WordPress/src/main/java/org/wordpress/android/viewmodel/mlp/ModalLayoutPickerViewModel.kt]: > I wonder how can we track this going forward, maybe through the analytics that exist on the Layout Picker, at least once a while, and see if the error screen shown increases as time passes-by.

That's a great idea @ParaskP7. I'll add a reminder to check on this.

Comment (ParaskP7) [reply WordPress/src/main/java/org/wordpress/android/viewmodel/mlp/ModalLayoutPickerViewModel.kt]: You are the best Mr. Antonis! ❤️
