### PR TITLE
fix #2226 - create a menu drawer even when stats are shown as modal

### LINKED ISSUE #2226: Crash report 3.6: NullPointerException in WPDrawerActivity
```
java.lang.RuntimeException: Unable to resume activity {org.wordpress.android/org.wordpress.android.ui.stats.StatsActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2772)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2801)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2253)
       at android.app.ActivityThread.access$600(ActivityThread.java:145)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1246)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5095)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:665)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.NullPointerException
       at org.wordpress.android.ui.WPDrawerActivity.onResume(WPDrawerActivity.java:158)
       at org.wordpress.android.ui.stats.StatsActivity.onResume(StatsActivity.java:237)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1193)
       at android.app.Activity.performResume(Activity.java:5194)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2751)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2801)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2253)
       at android.app.ActivityThread.access$600(ActivityThread.java:145)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1246)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5095)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
```

### PR DESCRIPTION
**Pull request by maxme**
fix #2226 - create a menu drawer even when stats are shown as modal (opened from a Notification for instance).

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/stats/StatsActivity.java [hunk 1]
```diff
@@ -545,8 +548,10 @@ public void onClick(DialogInterface dialog, int id) {
     @Override
     public boolean onCreateOptionsMenu(Menu menu) {
         super.onCreateOptionsMenu(menu);
-        MenuInflater inflater = getMenuInflater();
-        inflater.inflate(R.menu.stats, menu);
+        if (!mNoMenuDrawer) {
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/StatsActivity.java]: I think this is not needed here, otherwise the "View full site" will not be available.

screen shot 2015-01-21 at 18 54 57
screen shot 2015-01-21 at 18 55 55

Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/StatsActivity.java]: > I think this is not needed here, otherwise the "View full site" will not be available.

Ok I thought we wanted the user to stay on that level only (and not go deeper). I'll remove that.

Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/StatsActivity.java]: done in 57411f8

**Comment by daniloercoli** [comment]
:shipit:
