### PR TITLE
Fixes #5571: retry upload issue

### LINKED ISSUE #5571: Fail to retry media uploads
1. Create new post
2. Add new media
3. Quit the editor before media has been uploaded (tap back button)
4. Re-open the same post
5. Tap the "retry" button on the image -> upload never end 💥 

Note: it seems caused by the `mCurrentUpload` state not being reset after upload cancellation

### PR DESCRIPTION
**Pull request by maxme**
cc @mzorz 

Cancel All uploads when the hybrid editor fragment is detached.

This was the behavior previously, but it changed when we made we transformed the bound service to an independent service.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/media/services/MediaUploadService.java [hunk 1]
```diff
@@ -26,6 +27,8 @@
 
 import javax.inject.Inject;
 
+import de.greenrobot.event.EventBus;
```
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/media/services/MediaUploadService.java]: I'm not a fan of mixing event buses, but it was the simplest solution to communicate with the service.

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java [hunk 2]
```diff
@@ -2144,10 +2143,7 @@ public void onMediaRetryClicked(String mediaId) {
 
     @Override
     public void onMediaUploadCancelClicked(String mediaId, boolean delete) {
-        MediaModel media = new MediaModel();
-        media.setMediaId(Long.valueOf(mediaId));
-        MediaPayload payload = new MediaPayload(mSite, media);
-        mDispatcher.dispatch(MediaActionBuilder.newCancelMediaUploadAction(payload));
+        EventBus.getDefault().post(new PostEvents.PostMediaCanceled());
```
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: Note: this is called for all unfinished uploads.

**Comment by maxme** [comment]
Sorry, this is not ready for review, I just noticed this is actually called when someone click an image to cancel an upload...

**Comment by maxme** [comment]
Now ready for review, and also fixes #5566

File: WordPress/src/main/java/org/wordpress/android/ui/media/services/MediaUploadService.java (hunk 1 above)
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/media/services/MediaUploadService.java]: Me neither, would have thought of using a LocalBroadcastReceiver to keep it more Androidish but no worries, we're using this mechanism elsewhere in the app and I agree it's the simplest of the alternatives when both things happen in the same process

Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/media/services/MediaUploadService.java]: Yes, we actually replaced LocalBroadcastReceiver by the event bus a long time ago, but we should do the switch and use event bus 3.0 everywhere.

File: WordPress/src/main/java/org/wordpress/android/ui/media/services/MediaUploadService.java [hunk 3]
```diff
@@ -224,9 +227,30 @@ private boolean matchesInProgressMedia(final @NonNull MediaModel media) {
...
+    private void cancelUpload(int localMediaId) {
+        // Cancel if it's currently uploading
+        if (mCurrentUpload != null && mCurrentUpload.getId() == localMediaId) {
+            cancelCurrentUpload();
+        }
+        // Remove from the queue
+        for(Iterator<MediaModel> i = mQueue.iterator(); i.hasNext();) {
+            MediaModel mediaModel = i.next();
+            if (mediaModel.getId() == localMediaId) {
+                i.remove();
```
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/media/services/MediaUploadService.java]: I think it's safer in case we have duplicates.

File: WordPress/src/main/java/org/wordpress/android/ui/media/services/MediaUploadService.java [hunk 4]
```diff
@@ -224,9 +227,30 @@ private boolean matchesInProgressMedia(final @NonNull MediaModel media) {
...
-    private void cancelUpload() {
+    private void cancelCurrentUpload() {
         if (mCurrentUpload != null) {
             dispatchCancelAction(mCurrentUpload);
+            mCurrentUpload = null;
+        }
+    }
+
+    private void cancelAllUploads() {
+        mQueue.clear();
```
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/media/services/MediaUploadService.java]: Yes, I'll null check mQueue here.

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java [hunk 5]
```diff
@@ -2144,10 +2151,13 @@ public void onMediaRetryClicked(String mediaId) {
...
-        MediaModel media = new MediaModel();
-        media.setMediaId(Long.valueOf(mediaId));
-        MediaPayload payload = new MediaPayload(mSite, media);
-        mDispatcher.dispatch(MediaActionBuilder.newCancelMediaUploadAction(payload));
+        if (!TextUtils.isEmpty(mediaId)) {
+            int localMediaId = Integer.valueOf(mediaId);
+            EventBus.getDefault().post(new PostEvents.PostMediaCanceled(localMediaId));
+        } else {
+            // Passed mediaId is incorrect: cancel all uploads
+            EventBus.getDefault().post(new PostEvents.PostMediaCanceled(true));
```
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: > I understand we are cancelling everything to make sure we also cancel the tapped image as intended by the user, even when cancelling everything else is undesired, as opposed to not cancelling anything.

Not exactly, we're cancelling everything to make sure the upload service state is clean and next uploads will work.

File: WordPress/src/main/java/org/wordpress/android/ui/media/services/MediaUploadService.java (hunk 3 above)
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/media/services/MediaUploadService.java]: 👍

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java (hunk 5 above)
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: Gotcha. The toast message would be a nice addition though, so the user knows we know

**Comment by maxme** [comment]
> which looks weird as it doesn't really add anything but a comment and it's not related to the commit message itself bc950ba,

It's actually fixing an issue when the media is not local (already uploaded) but this action is still called.

**Comment by maxme** [comment]
Ready for a second round.

**Comment by mzorz** [comment]
>> which looks weird as it doesn't really add anything but a comment and it's not related to the commit message itself bc950ba,

> It's actually fixing an issue when the media is not local (already uploaded) but this action is still called.

Ah sorry, missed this call here https://github.com/wordpress-mobile/WordPress-Android/commit/bc950baf602a61aa19f69ea18aa8d5ba1beea5ea#diff-38b6aea9cfff5f3e0e4b7389b44de602R2125
👍 thanks

**Comment by mzorz** [comment]
LGTM :shipit:
