### PR TITLE
Fix crash in GutenbergContainerFragment

### LINKED ISSUE #20831: NullPointerException: Attempt to invoke virtual method 'org.wordpress.mobile.WPAndroidGlue.GutenbergProps org.wordpress...
Sentry Issue: [JETPACK-ANDROID-PE5](https://a8c.sentry.io/issues/5150897861/?referrer=github_integration)

```
RuntimeException: Failure delivering result ResultInfo{who=null, request=1538644274, result=-1, data=Intent { (has extras) }} to activity {com.jetpack.android/org.wordpress.android.ui.posts.EditPostActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'org.wordpress.mobile.WPAndroidGlue.GutenbergProps org.wordpress.android.editor.gutenberg.GutenbergPropsBuilder.build(android.app.Activity, boolean)' on a null object reference
    at android.app.ActivityThread.deliverResults(ActivityThread.java:6063)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:6102)
    at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
...
(9 additional frame(s) were not displayed)

NullPointerException: Attempt to invoke virtual method 'org.wordpress.mobile.WPAndroidGlue.GutenbergProps org.wordpress.android.editor.gutenberg.GutenbergPropsBuilder.build(android.app.Activity, boolean)' on a null object reference
    at org.wordpress.android.editor.gutenberg.GutenbergContainerFragment.updateCapabilities(GutenbergContainerFragment.java:319)
    at org.wordpress.android.editor.gutenberg.GutenbergEditorFragment.onActivityResult(GutenbergEditorFragment.java:684)
    at org.wordpress.android.ui.posts.EditPostActivity.onActivityResult(EditPostActivity.kt:2784)
    super.onActivityResult(requestCode, resultCode, data)
...
(19 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by aditi-bhatia**
Fixes #20831

This PR fixes a crash in `GutenbergContainerFragment` caused by `gutenbergPropsBuilder` being null. Since it is possible for `gutenbergPropsBuilder == null` if `db == null` in `GutenbergEditorFragment.java (line 208)`, I've annotated it to be `@NonNull` and added a null check in the function calling it.

-----

## To Test:

I haven't been able to reproduce, so code check + smoke test the post editor. 

-----

## Regression Notes

1. Potential unintended areas of impact

    - None

3. What I did to test those areas of impact (or what existing automated tests I relied on)

    - None

4. What automated tests I added (or what prevented me from doing so)

    - None
-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [ ] ~WordPress.com sites and self-hosted Jetpack sites.~
- [ ] ~Portrait and landscape orientations.~
- [ ] ~Light and dark modes.~
- [ ] ~Fonts: Larger, smaller and bold text.~
- [ ] ~High contrast.~
- [ ] ~Talkback.~
- [ ] ~Languages with large words or with letters/accents not frequently used in English.~
- [ ] ~Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)~
- [ ] ~Large and small screen sizes. (Tablet and smaller phones)~
- [ ] ~Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)~

### CODE REVIEW

File: libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergContainerFragment.java [hunk 1]
```diff
@@ -311,11 +311,11 @@ public void onRedoPressed() {
         mWPAndroidGlueCode.onRedoPressed();
     }
 
-    public void updateCapabilities(GutenbergPropsBuilder gutenbergPropsBuilder) {
+    public void updateCapabilities(@Nullable GutenbergPropsBuilder gutenbergPropsBuilder) {
         // We want to make sure that activity isn't null
         // as it can make this crash to happen: https://github.com/wordpress-mobile/WordPress-Android/issues/13248
         final Activity activity = getActivity();
-        if (activity != null) {
+        if (activity != null && gutenbergPropsBuilder != null) {
```
Comment (irfano) [inline libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergContainerFragment.java]: Since `updateCapabilities()` doesn't do anything if `gutenbergPropsBuilder` is null, I think it shouldn't accept null `gutenbergPropsBuilder`. And we should handle nullability where we are calling `updateCapabilities()` based on the case. WDYT? I wonder in which cases the db is null and what we're doing for these cases in other places of the app.

Comment (aditi-bhatia) [reply libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergContainerFragment.java]: Agreed, handling nullability in the functions calling `updateCapabilities()` does make more sense to me. I've updated the PR if you'd like to take a look again, appreciate any other feedback!

**Comment by irfano** [comment]
I have good news: I was able to reproduce the crash.
- Enable "Don't keep activities" from the developer settings. This will mimic a low memory state.
- Add an unsupported block to a post from the web, e.g., "Blog posts".
- Open the post from the mobile app.
- Tap on the block and open the web editor.
- Make a change and press the apply button.

<details>
  <summary>before video</summary>
 
[crash.webm](https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/835d4b0a-efa7-4d51-addc-e91fa772bda3)

</details>

However, I have bad news. This fix only prevents the crash but results in an unexpected outcome. After making a change in the editor and tapping the apply button, the React Native editor logs numerous error messages and does not save the updated change. If we add a null check without addressing this issue, we may lose opportunity to track the actual problem and fix it. 

I think the issue is related to low memory, but it may need further investigation. But, we could at least show a warning message to inform the user about the problem. Data loss is a critical issue, and if we cannot prevent it, we should at least inform the user. I am interested in your thoughts.

<details>
  <summary>after video</summary>
 
[after-fix.webm](https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/b0d46225-fffe-4892-b2cd-d64a6c2cd2d1)

</details>

**Comment by aditi-bhatia** [comment]
Hi @irfano thank you for looking into it and finding a way to reproduce the issue. Since I wasn't able to reproduce it earlier, I initially assumed the issue was due to the `db` being null since that case was not being handled.

 However, after reproducing the crash, it appears that actually isn't the root cause of the issue. The issue appears to stem from `mCurrentGutenbergPropsBuilder` becoming `null` (when it previously wasn't) by the time it reaches `GutenbergEditorFragment.java - onActivityResult()`. 

I tried a few things including trying to re-initialize the value of `mCurrentGutenbergPropsBuilder` if it's null, but this doesn't seem to fix the issue either: 
```
                if (mCurrentGutenbergPropsBuilder == null) {
                    SavedInstanceDatabase db = SavedInstanceDatabase.Companion.getDatabase(context);
                    if (db != null) {
                        mCurrentGutenbergPropsBuilder = db.getParcel(ARG_GUTENBERG_PROPS_BUILDER,
                                GutenbergPropsBuilder.CREATOR);
                    }
               }
```
Since this seems to be a tricky issue, I'm wondering if you have any thoughts. I agree with your points above re: data loss and I think for now, we can display a notice to the user so that they are aware that the changes haven't saved. What do you think?

**Comment by irfano** [comment]
I tried reinitializing `mCurrentGutenbergPropsBuilder`. It fixes the crash but the issue still occurs, as you mentioned. I investigated further, and guess the issue is that `GutenbergContainerFragment` and `GutenbergEditorFragment` are recreated when navigating back from GutenbergWebViewActivity. This results in reinitialization of `GutenbergContainerFragment.mWPAndroidGlueCode`. Consequently, when calling `WPAndroidGlueCode.replaceUnsupportedBlock()`, `mReplaceUnsupportedBlockCallback` is null, which causes the issue.

Ideally, we shouldn't lose data when recreating an activity or fragment. I think the best solution is to be able to recreate and reuse all fragment members, even if the fragment is recreated. I tried to determine why `mReplaceUnsupportedBlockCallback` is null but couldn't find the reason yet. I am stopping my investigation for now; maybe you can look into it further. 

As an alternative, we can add reinitializing `mCurrentGutenbergPropsBuilder` in `onActivityResult`, as you did above in this PR, and open another issue with our findings related to issue.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>AppRatingDialogWrapper</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>WellSqlInitializer</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          3 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><code>strings.xml</code> files should only be updated on release branches, when the translations are downloaded by our automation.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by irfano — APPROVED** [review]
LGTM! 👍🏻
