### PR TITLE
Fix crash when showing a dialog on Google signup/login error

### LINKED ISSUE #8360: Occasional crash when showing a dialog on Google signup/login error
### Expected behavior
The app doesn't crash when the Google Signup/Login fails

### Actual behavior
The app sometimes crashes when the Google Signup/Login fails - when the activity's state is saved before the `show()` method is invoked.

### Steps to reproduce the behavior
Unknown

```

android.support.v4.app.FragmentManagerImpl.checkStateLoss (FragmentManager.java:2053)
--
  | android.support.v4.app.DialogFragment.show (DialogFragment.java:143)
  | org.wordpress.android.ui.accounts.LoginActivity.onGoogleSignupError (LoginActivity.java:765)
  | org.wordpress.android.login.GoogleFragment.showError (GoogleFragment.java:225)
  | org.wordpress.android.login.LoginGoogleFragment.onSocialChanged (LoginGoogleFragment.java:192)
  | java.lang.reflect.Method.invoke (Method.java)
  | java.lang.reflect.Method.invoke (Method.java:372)
  | org.greenrobot.eventbus.EventBus.invokeSubscriber (EventBus.java:485)
  | org.greenrobot.eventbus.EventBus.invokeSubscriber (EventBus.java:479)
  | org.greenrobot.eventbus.HandlerPoster.handleMessage (HandlerPoster.java:67)
```

5ba05f2ef8b88c2963465633-fabric

### PR DESCRIPTION
**Pull request by malinajirka**
Fixes #8360 

This PR fixes an occasional crash when the `FragmentDialog.show()` method is invoked after the activity's state has already been saved.

Steps to reproduce the crash are unknown.

```

android.support.v4.app.FragmentManagerImpl.checkStateLoss (FragmentManager.java:2053)
--
  | android.support.v4.app.DialogFragment.show (DialogFragment.java:143)
  | org.wordpress.android.ui.accounts.LoginActivity.onGoogleSignupError (LoginActivity.java:765)
  | org.wordpress.android.login.GoogleFragment.showError (GoogleFragment.java:225)
  | org.wordpress.android.login.LoginGoogleFragment.onSocialChanged (LoginGoogleFragment.java:192)
  | java.lang.reflect.Method.invoke (Method.java)
  | java.lang.reflect.Method.invoke (Method.java:372)
  | org.greenrobot.eventbus.EventBus.invokeSubscriber (EventBus.java:485)
  | org.greenrobot.eventbus.EventBus.invokeSubscriber (EventBus.java:479)
  | org.greenrobot.eventbus.HandlerPoster.handleMessage (HandlerPoster.java:67)
```

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java [hunk 1]
```diff
@@ -756,13 +756,18 @@ public void onGoogleSignupFinished(String name, String email, String photoUrl, S
...
     @Override
     public void onGoogleSignupError(String msg) {
-        BasicFragmentDialog dialog = new BasicFragmentDialog();
-        dialog.initialize(GOOGLE_ERROR_DIALOG_TAG, getString(R.string.error),
-                msg,
-                getString(org.wordpress.android.login.R.string.login_error_button),
-                null,
-                null);
-        dialog.show(this.getSupportFragmentManager(), GOOGLE_ERROR_DIALOG_TAG);
+        // allow state loss
```
Comment (hypest) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java]: Not too important but, I'm kinda puzzled by the comment @malinajirka . If I understand it correctly, the logic here is to avoid showing the dialog because that will cause a FragmentManager state change and we should avoid that ([as per the docs](https://developer.android.com/reference/android/support/v4/app/FragmentManager.html#isStateSaved())). So, I'm not sure which state are we allowing to get lost. It doesn't seem that we are going to commit a transaction with allowing state loss. Am I missing something?

Comment (hypest) [reply WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java]: > or implement another fix

I'm cool with the actual solution here so, no need for more effort 👍.

Apparently, It's the comment that threw me off here since it's not a "commit with state loss" operation that happens below. So, yeah, let's just rephrase the comment. Maybe something along the lines "Only show the error dialog if the activity is still active", or something.

Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java]: 👍
