### PR TITLE
Stories: crash fix - allow null value for event.frameId, simply don't process it

### LINKED ISSUE #13662: IllegalArgumentException: Required value was null
Sentry Url: https://sentry.io/share/issue/a32c45528c414af8973965f6c9edd293/
Senry Url 2: https://sentry.io/share/issue/fa68ef7d97294b979c94299bb1d78f0d/

```
java.lang.IllegalArgumentException: Required value was null.
    at org.wordpress.android.ui.posts.editor.StoriesEventListener.onStoryFrameSaveCompleted(StoriesEventListener.kt:123)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501)
    at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
    at android.os.Handler.dispatchMessage(Handler.java:111)
    at android.os.Looper.loop(Looper.java:194)
    at android.app.ActivityThread.main(ActivityThread.java:5648)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

Logs for the user show a low memory situation, let's keep an eye on this and see if it has more occurences:

```
state: saveInstanceState
screen: PagesActivity
info
19:48:43
ui.lifecycle
state: stopped
screen: PagesActivity
info
19:48:43
generic
d/WordPress-API: ReactNativeStore: executeRequest
info
19:48:44
generic
d/WordPress-API: Dispatching action: PostAction-UPDATE_POST
info
19:48:46
generic
d/WordPress-API: Dispatching action: ListAction-LIST_DATA_INVALIDATED
info
19:48:46
generic
d/WordPress-POSTS: PageStore: getPagesFromDb
info
19:48:46
device.event
Low memory
level: 10
action: LOW_MEMORY
warning
19:49:03
exception
IllegalArgumentException: Required value was null.
```

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #13662 

This PR allows null value for event.frameId in StoriesEventListener. It was required to be no null mainly for ediitng existing Story blocks, but a sticky event for a newly created Story (without using the Gutenberg Editor) is perfectly possible, we should just disregard processing those events.

What was happening here was that after creating a Story and after the introduction of this PR https://github.com/Automattic/stories-android/pull/632 all events from Stories are sticky. This makes "old" events come in every now and then but this should be harmless since we're removing as soon as these are first seen.
So, for a new Story we don't really have frame `id`s , so there's no need to process such a new Story frame.
Hope that makes sense!

To test:
1. create a story and publish it
2. create a new Post
3. observe the ~crash~ app doesn't crash anymore 🎉

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/editor/StoriesEventListener.kt [hunk 1]
```diff
@@ -166,10 +166,14 @@ class StoriesEventListener @Inject constructor(
...
+        // in onStoryFrameSaveCompleted we should always get a frameId that has the TEMPORARY_ID_PREFIX prefix
+        // for Stories being edited only
+        // otherwise we can exit
+        if (event.frameId == null) return
+
         if (!lifecycle.currentState.isAtLeast(CREATED)) {
             return
         }
-        // in onStoryFrameSaveCompleted we should always get a frameId that has the TEMPORARY_ID_PREFIX prefix
         val localMediaId = requireNotNull(event.frameId)
```
Comment (jd-alexander) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/editor/StoriesEventListener.kt]: @mzorz what do you think about removing the `requireNotNull` check here since we are checking if the `frameId` is null above and returning? Let me know.

**Review by jd-alexander — COMMENTED** [review]
Changes look good to me @mzorz Thanks for the detailed explanation and accompanying notes. I tested the app and I was able to do the story post and post creation steps and observed no crashes. I left a comment, once that's resolved we can get this merged in.

File: WordPress/src/main/java/org/wordpress/android/ui/posts/editor/StoriesEventListener.kt (hunk 1 above)
Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/editor/StoriesEventListener.kt]: oops good catch - addressed in 5b81779d13

**Comment by mzorz** [comment]
Thank you for your review @jd-alexander 🙇 

Merging as [agreed](https://github.com/wordpress-mobile/WordPress-Android/pull/14351#pullrequestreview-622614159)
