### PR TITLE
[Post Upload] Crash fix: remove call to mutex#unlock from UploadStarter

### LINKED ISSUE #18958: CompletionHandlerException: Exception in resume onCancellation handler for CancellableContinuation(DispatchedContinuation[Dis...
Sentry Issue: [JETPACK-ANDROID-92S](https://a8c.sentry.io/issues/4295575735/?referrer=github_integration)

```
IllegalStateException: This mutex is not locked
    at kotlinx.coroutines.sync.MutexImpl.unlock(Mutex.kt:207)
    at kotlinx.coroutines.sync.MutexImpl$CancellableContinuationWithOwner$tryResume$token$1.invoke(Mutex.kt:255)
    at kotlinx.coroutines.sync.MutexImpl$CancellableContinuationWithOwner$tryResume$token$1.invoke(Mutex.kt:252)
    at kotlinx.coroutines.CancellableContinuationImpl.callOnCancellation(CancellableContinuationImpl.kt:259)
    at kotlinx.coroutines.CompletedContinuation.invokeHandlers(CancellableContinuationImpl.kt:659)
...
(8 additional frame(s) were not displayed)

CompletionHandlerException: Exception in resume onCancellation handler for CancellableContinuation(DispatchedContinuation[Dispatchers.IO, Continuation at org.wordpress.android.ui.uploads.UploadStarter$upload$2.invokeSuspend(UploadStarter.kt:211)@df58903]){Completed}@c9c7080
    at kotlinx.coroutines.CancellableContinuationImpl.callOnCancellation(CancellableContinuationImpl.kt:264)
    at kotlinx.coroutines.CompletedContinuation.invokeHandlers(CancellableContinuationImpl.kt:659)
    at kotlinx.coroutines.CancellableContinuationImpl.cancelCompletedResult$kotlinx_coroutines_core(CancellableContinuationImpl.kt:180)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
    at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
...
(5 additional frame(s) were not displayed)
```

This is not a duplicate of #17463 since this is now happening on coroutines 1.7.1 which fixed the underlying root cause of that other ticket. This has a similar stacktrace, but it looks like we might be misusing the Mutex in our `UploadStarter` implementation.

### PR DESCRIPTION
**Pull request by thomashorta**
Fixes #18958

The `mutex.unlock` call is redundant (because we already use `withLock`, which unlocks after the block runs) and can be the source of crashes since the mutex cannot be unlocked if it's not locked and the internal `Mutex` source code tries to unlock it in certain Cancellation situations.

More info in the issue comment: https://github.com/wordpress-mobile/WordPress-Android/issues/18958#issuecomment-1675239908

To test:
We could not find a way of reproducing this issue as it might be related to some race conditions, multiple threads, and likely, how the device / system handles them.

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
WIP

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

UI Changes testing checklist:
None

### CODE REVIEW

**Comment by thomashorta** [comment]
I was able to create a unit test that consistently reproduces the crash when the code for `UploadStarter` does not contain the fixes introduced by this PR and consistently passes after the fix. 🎉 

The stack trace is exactly the same as the crash reported on Sentry which gives me confidence this is a valid test, even though the breadcrumbs might differ a bit because of the testing environment running on a host machine and not on Android.

This confirms my hypothesis from https://github.com/wordpress-mobile/WordPress-Android/issues/18958#issuecomment-1675239908 that the `mutex.unlock` called by us is the culprit of the mutex unexpectedly being unlocked and causing the crash inside the `Mutex` class.

While writing the test I was able to also confirm that the issue is caused by a race condition, so the code doesn't ALWAYS crash when `uploadServiceFacade.uploadPost` throws an exception, it really depends on the number of existing threads being used, so the crash was likely happening for users with multiple sites + multiple local posts, which also matches my initial hypothesis. 

We were making the issue more likely to happen because we were incorrectly using the `Dispatchers.IO` which has way more threads, 64 by default, (and shouldn't really be used for processing) than `Dispatchers.Default`, which defaults to the number of CPU cores. So I also made sure we only offload to `Dispachers.IO` for IO calls.

Here's the test failing (before the fix):
mutex-upload-starter-test-fail

And here's the test passing (after the fix):
mutex-upload-starter-test-success

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadStarter.kt [hunk 1]
```diff
@@ -136,7 +136,7 @@ class UploadStarter @Inject constructor(
         }
 
         sites.forEach {
-            launch(ioDispatcher) {
+            launch {
```
Comment (mkevins) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadStarter.kt:139]: Good idea 👍

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadStarter.kt [hunk 2]
```diff
@@ -181,9 +181,7 @@ class UploadStarter @Inject constructor(
             }
         } catch (e: CancellationException) {
             AppLog.e(T.MEDIA, e)
-            // Do any needed actions while we are still holding the mutex lock, then release it and rethrow the
-            // exception so it can be handled upstream
-            mutex.unlock()
+            // rethrow the exception so it can be handled upstream
```
Comment (mkevins) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadStarter.kt:184]: Thanks for also updating the comment 😄

File: WordPress/src/test/java/org/wordpress/android/ui/uploads/UploadStarterMutexTest.kt [hunk 3]
```diff
@@ -0,0 +1,142 @@
...
+            bgDispatcher = bgDispatcher,
+            ioDispatcher = ioDispatcher,
+            uploadServiceFacade = uploadServiceFacade,
+            networkUtilsWrapper = networkUtilsWrapper,
+            connectionStatus = connectionStatus
+        )
+    }
+
+    @Test
+    fun `should not crash if uploadPost throws an exception`() = test {
```
Comment (mkevins) [inline WordPress/src/test/java/org/wordpress/android/ui/uploads/UploadStarterMutexTest.kt:91]: Awesome job creating a test to reproduce this and validate the fix!

**Review by mkevins — APPROVED** [review]
Awesome work tracking this down and finding a solution @thomashorta 🥇 🎉 

> The stack trace is exactly the same as the crash reported on Sentry which gives me confidence this is a valid test, even though the breadcrumbs might differ a bit because of the testing environment running on a host machine and not on Android.

I agree that we may not get the exact same breadcrumbs, and I confirmed that the trace is the same by reverting all commits except the unit test and seeing it fail in the same way. Great work!
 
> While writing the test I was able to also confirm that the issue is caused by a race condition, so the code doesn't ALWAYS crash when `uploadServiceFacade.uploadPost` throws an exception, it really depends on the number of existing threads being used, so the crash was likely happening for users with multiple sites + multiple local posts, which also matches my initial hypothesis.

Indeed! I think this fix will reduce (or possibly even eliminate 🤞) the occurrences of this crash.
 
> We were making the issue more likely to happen because we were incorrectly using the `Dispatchers.IO` which has way more threads, 64 by default, (and shouldn't really be used for processing) than `Dispatchers.Default`, which defaults to the number of CPU cores. So I also made sure we only offload to `Dispachers.IO` for IO calls.

Nice. 👍 As discussed in the previous (similar) issue (https://github.com/wordpress-mobile/WordPress-Android/issues/17463), ideally we wouldn't even use concurrency here (out of scope for this fix, imo) - and this change, imo, is a step in that direction (i.e. the outer parts of the implementation will run with the default dispatcher).
