### PR TITLE
Verify non-empty credentials required by Smart Lock

### LINKED ISSUE #5850: Crash report 7.2.1: java.lang.IllegalArgumentException: password cannot be empty
```
Fatal Exception: org.greenrobot.eventbus.EventBusException: Invoking subscriber failed
       at org.greenrobot.eventbus.EventBus.handleSubscriberException(EventBus.java:505)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:487)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
       at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5219)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
Caused by java.lang.IllegalArgumentException: password cannot be empty
       at com.google.android.gms.auth.api.credentials.Credential.<init>(Unknown Source)
       at com.google.android.gms.auth.api.credentials.Credential$Builder.build(Unknown Source)
       at org.wordpress.android.ui.accounts.SmartLockHelper.saveCredentialsInSmartLock(SmartLockHelper.java:114)
       at org.wordpress.android.ui.accounts.NewUserFragment.fetchSiteAndAccount(NewUserFragment.java:630)
       at org.wordpress.android.ui.accounts.NewUserFragment.onNewSiteCreated(NewUserFragment.java:719)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
       at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5219)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
```

### PR DESCRIPTION
**Pull request by tonyr59h**
Fixes #5850 by verifying username and password fields are not empty.

It looks like any call to create a new site is behind an [isUserDataValid](https://github.com/wordpress-mobile/WordPress-Android/blob/45224a17fa4939743added2652792eafcfa0c863/WordPress/src/main/java/org/wordpress/android/ui/accounts/NewUserFragment.java#L145) call so I don't know why the fields would be empty when building the credentials. Maybe another call to `isUserDataValid` would be appropriate [here](https://github.com/wordpress-mobile/WordPress-Android/blob/45224a17fa4939743added2652792eafcfa0c863/WordPress/src/main/java/org/wordpress/android/ui/accounts/NewUserFragment.java#L636) instead of checking in `SmartLockHelper`?

cc @maxme

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/accounts/SmartLockHelper.java [hunk 1]
```diff
@@ -106,6 +106,12 @@ public void onResult(@NonNull CredentialRequestResult result) {
 
     public void saveCredentialsInSmartLock(@NonNull final String username, @NonNull final String password,
                                            @NonNull final String displayName, @Nullable final Uri profilePicture) {
+        // need username and password fields for Smart Lock
+        // https://github.com/wordpress-mobile/WordPress-Android/issues/5850
+        if (password.isEmpty() || username.isEmpty()) {
```
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/accounts/SmartLockHelper.java]: I think we should use `TextUtils.isEmpty()` here, the `@NonNull` annotation doesn't prevent NPEs. Also we should `AppLog` it, just to make sure we won't miss it if this happen recurrently in the future due to bad input.

**Comment by maxme** [comment]
:shipit:
