### PR TITLE
Only show error toast if post is null and it wasn't empty

### LINKED ISSUE #7382: Post list: Error when coming back from empty Editor
### Expected behavior
Entering the editor and exiting without adding any content should not show any errors

### Actual behavior
Entering the editor and exiting without adding any content shows this Toast:

screenshot_20180305-112016

### Steps to reproduce the behavior
1. go to posts list
2. tap on the orange floating button to create a new draft
3. when the editor is shown, tap either the back arrow on the top of the screen, or the Android back button
4. Observe the Toast reading `An error occurred when loading the post. Refresh your posts and try again.` is shown.

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #7382 

To test:
1. go to Posts list
2. tap on the floating "Edit new post" button
3. without adding any content, just tap BACK
4. observe the error Toast is not shown anymore.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java [hunk 1]
```diff
@@ -1477,6 +1479,13 @@ public void run() {
         }).start();
     }
 
+    private boolean isDiscardable() {
+        if (!PostUtils.isPublishable(mPost) && isNewPost()) {
+            return true;
+        }
+        return false;
+    }
```
Comment (theck13) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: The `isDiscardable` method can be simplified to this:
``` java
private boolean isDiscardable() {
    return !PostUtils.isPublishable(mPost) && isNewPost();
}
```

Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: nice! addressed in 3d06f66
