### PR TITLE
Remove media file extension from the media file title

### LINKED ISSUE #15108: Media file extension added to the media file title
It was reported in 4190221-zd-woothemes that the media file extension was added to the media file title in the Media Library when the file was uploaded through the app. In the case reported, it was JPEG files.

However, when uploading the same file on Calypso, the file extension didn't get added to the media file title.

### Expected behavior

The user expects the file extension won't get added to the media file title.

### Actual behavior

The media files uploaded through the app contain the media file extension at the media file title.

### Steps to reproduce the behavior

1. Go to My Site > Media
2. Tap the "+" icon > Choose from device, and upload a JPEG image file
3. Once the media file is uploaded, tap the image and see that the file title contains the file extension

Markup on 2021-08-02 at 10:13:03

##### Tested on OPPO Reno 4, Android 11, WPAndroid 17.9-rc-2

### PR DESCRIPTION
**Pull request by ashiagr**
Fixes #15108 

This PR removes file extension from the local media title before upoad. 

To test:

1. Go to "My Site" tab
2. Click "Media" from "Quick Links"
3. Click + button on the media grid screen
4. Click "Take photo" from the menu
5. Wait for the upload to complete
6. Click the newly uploaded photo
7. Notice that the photo title does not contain a file extension
8. Repeat above steps for "Choose from device" and "Take video" menu options 
9. Notice that the media title still does not contain a file extension

## Regression Notes
1. Potential unintended areas of impact
Minimal changes are applied to just update the title,  should not affect the rest of the code.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
See above

3. What automated tests I added (or what prevented me from doing so)
None. `FluxCUtils` is a legacy class accessing static methods from classes like `MediaUtils`, `TextUtils`, `UrlUtils` and refactoring it to support tests is currently out of scope of this PR.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/util/FluxCUtils.java [hunk 1]
```diff
@@ -122,14 +122,20 @@ public static MediaModel mediaModelFromLocalUri(@NonNull Context context,
             }
         }
 
+        String title = filename;
+        // Remove extension from title
+        if (fileExtension != null && title.contains("." + fileExtension)) {
+            title = title.substring(0, title.lastIndexOf(fileExtension) - 1);
+        }
+
```
Comment (develric) [inline WordPress/src/main/java/org/wordpress/android/util/FluxCUtils.java:131]: If I'm not wrong, filename (and so title) could be null; maybe we should null check on title. wdyt?

**Review by develric — COMMENTED** [review]
Hey @ashiagr , thanks for the changes 🙇 ! I tested as per steps and it worked as described 👍 . Before to approve I left a comment for you to double check; let me know wdyt 🙇

File: WordPress/src/main/java/org/wordpress/android/util/FluxCUtils.java (hunk 1 above)
Comment (ashiagr) [reply WordPress/src/main/java/org/wordpress/android/util/FluxCUtils.java:131]: Good point!

Although filename doesn't seem to be set to null as in a previous line it checks if `!file.exists()` which means it should be a valid file location from where the file name is derived. But there's no harm adding a null check 😄.

I'm setting file name to an empty string if null in fc052ec so that we don't set a null filename as well. 

Ready for another look 🙇

**Review by zwarm — APPROVED** [review]
@ashiagr - I gave it a whirl too and all works as expected. 🥳

File: WordPress/src/main/java/org/wordpress/android/util/FluxCUtils.java (hunk 1 above)
Comment (develric) [reply WordPress/src/main/java/org/wordpress/android/util/FluxCUtils.java:131]: Ah yep, I see what you mean 👍 ! And agree with you no harm in adding the check 😄 .

**Review by develric — APPROVED** [review]
Thanks for the clarification @ashiagr, LGTM as well :shipit:
