### PR TITLE
Notifications now refresh periodically

### LINKED ISSUE #7851: Links are not highlighted on notifications
The iOS app highlights links on notifications allowing the user to navigate to them. This doesn't seem to be working in Android. Was this feature ever implemented and this is a regression? Or was it never there?

Reported by @m

### PR DESCRIPTION
**Pull request by kwonye**
Fixes #7851

Ignore the title of the issue. The problem is us getting the most recent edits of comments.

I went back and forth between multiple solutions, including refreshing every time someone tapped a notification and we went into the detail activity. The problem with that is if a user is scrolling through multiple notifications they'll be making a ton of calls. Also it introduces a delay when clicking a notification which is most likely up-to-date.

The way this implementation works:

1. When a user goes to the notification screen for the first time since app booting we sync the notifications with server.
2. If a user goes into a specific notification and comes back, there is no refresh.
3. If a user goes into another tab and comes back to the notification list, we refresh.

This guarantees we always show the most-correct list of notifications when the user comes into the notifications list.

If you have any other suggestions I'm open to it!

To test:
1. Send the user a notification by commenting on a post
2. Verify you got a notification and click into the notification
3. Edit the comment from the web
4. Go back into the notifications list and select the notification again. It should show the old text.
5. Go back and select a different tab (Reader)
6. Select the notifications tab and tap the same notification. The comment should be updated.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragment.java [hunk 1]
```diff
@@ -223,9 +228,17 @@ public void onResume() {
             mFilterRadioGroup.setVisibility(View.GONE);
         } else {
             getNotesAdapter().reloadNotesFromDBAsync();
+            if (mShouldRefreshNotifications) {
+                fetchNotesFromRemote();
+            }
         }
     }
 
+    @Override public void onPause() {
```
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragment.java]: Let's add a newline here, after `@Override`

Comment (kwonye) [reply WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragment.java]: Well that's embarrassing... and not a nitpick at all! I'd hope you'd flag this everytime you saw it.

Thanks for catching this!

**Comment by mzorz** [comment]
:shipit:
