### PR TITLE
Fix fb publicize

### LINKED ISSUE #9924: Cannot connect to Facebook to automatically publish posts to a page
### Expected behavior
Connect to my Facebook page so that my Wordpress posts also publish to my Facebook page

### Actual behavior
When connecting to a Facebook page, after the flow is complete a toast appears saying 'An Error occured' and it does not seem to have been successful

### Steps to reproduce the behavior
1. In the Android app, go to a site
2. Choose sharing under configuration near the bottom
3. There is the option to automatically share on networks. Choose Facebook.
4. Tap the 'connect' button below the information
5. Go through flow the Facebook steps (login/continue, choose the page to use with wordpress, choose what wordpress is allowed to do)
6. See message 'you've now linked Wordpress to Facebook', which makes it seem like we've been successful
7. Returning to the same screen as step 4 within wordpress, a toast message appears saying 'An error has occured'

##### Tested on [device], Android [version], WPAndroid [version]
A user reported on ticket 2047729-zen 
I have verified the same issue is happening to me on a Google Pixel 3a, Wordpress for Android v 12.4, Android version 9

##### Related ticket
https://github.com/wordpress-mobile/WordPress-Android/issues/8715
But in that case the user has no Facebook pages. In this case, even when having a Facebook page an error occurs.

user screenshot

### PR DESCRIPTION
**Pull request by malinajirka**
Hopefully fixes #9924

Fixes bug which prevented some users from establishing connection with their social media services.

To test:
- Set "don't keep activities in the System developer settings"
1. My Site
2. Sharing
3. Facebook
4. Connect
5. Enter your Facebook credentials
6. The Webview asks you to provide 2-fa code 
7. Switch to the Facebook app and get the code (this is the place where we lose `mServiceId`)[in case your account isn't 2-fa protected, just move another app into foreground and then bring the WordPress app back]
8. Finish the FB login and give the app access to at least one published fb page
9. A connection to your FB page should be successfully established

Update release notes:

- [ x ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeWebViewFragment.java [hunk 1]
```diff
@@ -86,6 +86,7 @@ public void onSaveInstanceState(Bundle outState) {
         super.onSaveInstanceState(outState);
         outState.putSerializable(WordPress.SITE, mSite);
         outState.putInt(PublicizeConstants.ARG_CONNECTION_ID, mConnectionId);
+        outState.putString(PublicizeConstants.ARG_SERVICE_ID, mServiceId);
```
Comment (mkevins) [inline WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeWebViewFragment.java]: Good catch :+1:
