### PR TITLE
Check for activity state on image loader response

### LINKED ISSUE #6347: Crash report 7.8: NullPointerException in DisplayUtils.dpToPx
Fatal Exception: java.lang.NullPointerException
at org.wordpress.android.util.DisplayUtils.dpToPx(DisplayUtils.java:49)
at org.wordpress.android.editor.AztecEditorFragment$8.onResponse(AztecEditorFragment.java:604)
at com.android.volley.toolbox.ImageLoader$4.run(ImageLoader.java:474)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5584)
at java.lang.reflect.Method.invokeNative(Method.java)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
at dalvik.system.NativeStart.main(NativeStart.java)

### PR DESCRIPTION
**Pull request by 0nko**
Fixes #6347.

### CODE REVIEW

File: libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java [hunk 1]
```diff
@@ -579,6 +579,11 @@ public void appendMediaFile(final MediaFile mediaFile, final String mediaUrl, Im
                 imageLoader.get(mediaUrl, new ImageLoader.ImageListener() {
                     @Override
                     public void onErrorResponse(VolleyError error) {
+                        if (getActivity() == null) {
```
Comment (daniloercoli) [inline libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java]: Should we use `isAdded` instead?

Comment (0nko) [inline libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java]: You're right.

**Comment by daniloercoli** [comment]
Looks good! :shipit:
