### PR TITLE
Parcel marshaling issue with preview and edit

### LINKED ISSUE #13132: Issue in parcel marshaling when preview/edit
### Expected behavior
In pick from device or from tenor, I would expect to be able to edit/preview a selected item.

### Actual behavior
In pick from device or from tenor, trying to edit/preview a selected item cause the following:

```
-- pick from device

2020-10-14 15:18:02.312 11249-11249/org.wordpress.android.beta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.wordpress.android.beta, PID: 11249
    java.lang.RuntimeException: Parcel: unable to marshal value content://media/external/images/media/33
        at android.os.Parcel.writeValue(Parcel.java:1782)
        at org.wordpress.android.ui.mediapicker.MediaItem$Identifier$LocalUri.writeToParcel(Unknown Source:7)
        at android.os.Parcel.writeParcelable(Parcel.java:1801)
        at android.os.Parcel.writeValue(Parcel.java:1707)
        at android.os.Parcel.writeList(Parcel.java:1045)
        at android.os.Parcel.writeValue(Parcel.java:1729)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:928)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1584)
        at android.os.Bundle.writeToParcel(Bundle.java:1253)
        at android.os.Parcel.writeBundle(Parcel.java:997)
        at androidx.fragment.app.FragmentState.writeToParcel(FragmentState.java:127)
        at android.os.Parcel.writeTypedObject(Parcel.java:1634)
        at android.os.Parcel.writeTypedList(Parcel.java:1513)
        at android.os.Parcel.writeTypedList(Parcel.java:1470)
        at androidx.fragment.app.FragmentManagerState.writeToParcel(FragmentManagerState.java:51)
        at android.os.Parcel.writeParcelable(Parcel.java:1801)
        at android.os.Parcel.writeValue(Parcel.java:1707)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:928)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1584)
        at android.os.Bundle.writeToParcel(Bundle.java:1253)
        at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:4505)
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)


```

```
-- pick from tenor

2020-10-14 16:06:39.643 15911-15911/org.wordpress.android.beta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.wordpress.android.beta, PID: 15911
    java.lang.RuntimeException: Parcel: unable to marshal value https://media.tenor.com/images/aab2790fa0c8f652998de4381807feeb/tenor.gif
        at android.os.Parcel.writeValue(Parcel.java:1782)
        at org.wordpress.android.ui.mediapicker.MediaItem$Identifier$GifMediaIdentifier.writeToParcel(Unknown Source:12)
        at android.os.Parcel.writeParcelable(Parcel.java:1801)
        at android.os.Parcel.writeValue(Parcel.java:1707)
        at android.os.Parcel.writeList(Parcel.java:1045)
        at android.os.Parcel.writeValue(Parcel.java:1729)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:928)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1584)
        at android.os.Bundle.writeToParcel(Bundle.java:1253)
        at android.os.Parcel.writeBundle(Parcel.java:997)
        at androidx.fragment.app.FragmentState.writeToParcel(FragmentState.java:127)
        at android.os.Parcel.writeTypedObject(Parcel.java:1634)
        at android.os.Parcel.writeTypedList(Parcel.java:1513)
        at android.os.Parcel.writeTypedList(Parcel.java:1470)
        at androidx.fragment.app.FragmentManagerState.writeToParcel(FragmentManagerState.java:51)
        at android.os.Parcel.writeParcelable(Parcel.java:1801)
        at android.os.Parcel.writeValue(Parcel.java:1707)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:928)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1584)
        at android.os.Bundle.writeToParcel(Bundle.java:1253)
        at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:4505)
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

```

**Note 1:** Stock seems to work well
**Note 2:** The issue seems present only if you edit/preview on an item that is currently selected; non selected items work well.

### Steps to reproduce the behavior

- Go to Media Lin -> Choose from device -> Select an item
- Long press the selected item to get the preview
- Check the exception in logcat and notice the preview screen is closed if waiting a few seconds
- Same steps above for editing

### PR DESCRIPTION
**Pull request by develric**
Fixes #13132 

The issue is related to parceling of UriWrapper; since UriWrapper is widely used I tried to play simple and used a more classic approach explicitly implementing the `Parcelable` interface on the sealed class (maybe a bit old school but should do the job 😄  ). Since the changed code was related to the [comment here](https://github.com/wordpress-mobile/WordPress-Android/pull/13104#discussion_r503851806) I tried to address that here simplifying `GifMediaIdentifier` and introducing `LocalId`. Hope I interpreted your intention in that comment correctly 🙇 

## To test
We are talking about the Wasabi flavor with the `CONSOLIDATED_MEDIA_PICKER` flag on

- trigger the long press preview on all the sources and check it works as expected
- trigger the edit action in the device picker (selecting one or more images) and check you can edit images and insert them in the media library or GB image block(s)

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/mediapicker/MediaItem.kt [hunk 1]
```diff
@@ -14,21 +19,91 @@ data class MediaItem(
     val mimeType: String? = null,
     val dataModified: Long
 ) {
-    sealed class Identifier : Parcelable {
-        @Parcelize
-        data class LocalUri(val value: @RawValue UriWrapper) : Identifier()
+    enum class IdentifierType {
+        LocalUri,
```
Comment (planarvoid) [inline WordPress/src/main/java/org/wordpress/android/ui/mediapicker/MediaItem.kt]: this is very minor but I'd rather have these looking like `LOCAL_URI` and so on. The reason is that things like `data class LocalUri(val value: UriWrapper) : Identifier(LocalUri)` are a bit confusing - to see which `LocalUri` you're using. WDYT?

**Review by planarvoid — APPROVED** [review]
Thanks for this PR, it's working well 👍 . I have one comment

**Comment by develric** [comment]
Thanks @planarvoid 🙇 , agree with your feedback, changed here 2f6538d

**Review by planarvoid — APPROVED** [review]
