### PR TITLE
fix #3461: Show an error message if mediaUrl is null

### LINKED ISSUE #3461: Crash report 4.7: NPE in EditPostActivity.fetchMedia
```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2000, result=-1, data=Intent { (has extras) }} to activity {org.wordpress.android/org.wordpress.android.ui.posts.EditPostActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3319)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3362)
       at android.app.ActivityThread.access$1100(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1282)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5041)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException
       at org.wordpress.android.ui.posts.EditPostActivity.fetchMedia(EditPostActivity.java:1100)
       at org.wordpress.android.ui.posts.EditPostActivity.onActivityResult(EditPostActivity.java:1226)
       at android.app.Activity.dispatchActivityResult(Activity.java:5293)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3315)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3362)
       at android.app.ActivityThread.access$1100(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1282)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5041)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

### PR DESCRIPTION
**Pull request by maxme**
fix #3461: Show an error message if mediaUrl is null

Note: the `gallery_error` label is incorrect (should be something like `media_cant_be_retrieved_error`) but if I change it now, GlotPress translations will be erased.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java [hunk 1]
```diff
@@ -1113,6 +1113,11 @@ public void updatePostContent(boolean isAutoSave) {
      */
 
     private void fetchMedia(Uri mediaUri) {
+        if (mediaUri == null) {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: What are the chances that there may be multiple null media URLs? I'm thinking we want to avoid barraging the user with toasts if there are multiple failures.

Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: This `fetchMedia` method is called when the user selects one video or one picture from the local library. So maximum one toast at a time when the user comes back the image/video picker.

Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: :+1:

**Comment by nbradbury** [comment]
:shipit:
