### PR TITLE
Issue/6253 adjust cancelled uploads

### LINKED ISSUE #6253: Media async: adjust cancelled uploads when coming back to Aztec
### Expected behavior
If an upload is in progress and you exit the editor (Aztec), then the media upload fails, then get back into the editor, the image should be shown/marked as available for retry (i.e. marked failed)

### Actual behavior
The image is shown as being still in upload progress, which is incorrect.

### Steps to reproduce the behavior
on branch `feature/async-media`
1. open a new draft
2. include an image to upload
3. while it's uploading, exit the editor
4. make the image upload fail (i.e. turn airplane mode on)
5. get back to the editor
6. see the image is shown as "still uploading"

### Proposed solutions

We considered 2 options: 

1) either the AztecEditorFragment is in charge of this, and when it opens up again, we should check if there’s any canceled images and mark them properly, or 

2) when the `MediaUploadService` service is done with something and ends in error, we can do the same as we were doing for the success case: go ahead and call a static method in `AztecEditorFragment` that properly replaces the `class` properties for error ones

The PR tackling this, if not otherwise noted, should go with option number 2

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #6253

This PR makes sure that we track failed media item uploads and update the post contents accordingly while an upload fail happens in the background. The solution implemented here corresponds to the second option as described in the issue.

To test:

1. create a new draft
2. include media items
3. exit the editor
4. turn airplane mode ON
5. edit the post again: you should see media items marked as FAILED
 
cc @aforcier

### CODE REVIEW

**Comment by mzorz** [comment]
also updated https://github.com/wordpress-mobile/WordPress-Android/issues/6352 with the reference to `private static final ConcurrentHashMap<Integer, List<MediaModel>> sFailedMediaByPost = new ConcurrentHashMap<>();`

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java [hunk 1]
```diff
@@ -564,12 +642,23 @@ public void onMediaUploaded(OnMediaUploaded event) {
...
+                                // finally, save the PostModel
                                 mDispatcher.dispatch(PostActionBuilder.newUpdatePostAction(updatedPost));
 
                                 // TODO Should do some extra validation here
                                 // e.g. what if the post has local media URLs but no pending media uploads?
-                                iterator.remove();
-                                mPostUploadHandler.upload(updatedPost);
+
+                                // only upload Post if there are no failed media as well
+                                if (!hasAnyFailedMediaUploadsForPost(uploadingPost.postModel)) {
```
Comment (aforcier) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java]: It doesn't look like it's possible for `hasAnyFailedMediaUploadsForPost()` to be `true` at this point - if this post had failed media, we'd have already removed it from `sPostsWithPendingMedia` when we received a cancelled or errored `OnMediaUploaded` event. What do you think about simplifying this logic and using what was there before?

File: WordPress/src/main/java/org/wordpress/android/ui/media/services/MediaUploadReadyListener.java [hunk 2]
```diff
@@ -5,9 +5,15 @@
 import org.wordpress.android.fluxc.model.PostModel;
 import org.wordpress.android.util.helpers.MediaFile;
 
+import java.util.List;
```
Comment (aforcier) [inline WordPress/src/main/java/org/wordpress/android/ui/media/services/MediaUploadReadyListener.java]: Unused import.

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java [hunk 3]
```diff
@@ -107,9 +112,14 @@ public void onDestroy() {
             mPostUploadHandler.unregister();
         }
 
-        // Update posts with any completed uploads in our post->media map
-        for (Integer postId : sCompletedMediaByPost.keySet()) {
+        // Update posts with any completed AND failed uploads in our post->media map
+        ConcurrentHashMap<Integer, List<MediaModel>> tmpMap = new ConcurrentHashMap<>();
```
Comment (aforcier) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java]: This can just be a plain `Map`.

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListFragment.java [hunk 4]
```diff
@@ -772,7 +772,21 @@ public void onMediaUploaded(OnMediaUploaded event) {
 
         PostModel post = mPostStore.getPostByLocalPostId(event.media.getLocalPostId());
         if (post != null) {
-            mPostsListAdapter.updateProgressForPost(post);
+            if ((event.media.isError() || event.canceled)){
+                // if a media is cancelled or ends in error, and the post is not uploading nor queued,
+                // (meaning there is no other pending media to be uploaded for this post)
+                // then we should refresh it to show its new state
+                if (post != null && !UploadService.isPostUploadingOrQueued(post)) {
```
Comment (aforcier) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListFragment.java]: We already checked `post != null` above.

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListFragment.java [hunk 5]
```diff
@@ -772,7 +772,21 @@ public void onMediaUploaded(OnMediaUploaded event) {
...
+                    // TODO: replace loadPosts for getPostListAdapter().notifyItemChanged(); kind of thing,
```
Comment (aforcier) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListFragment.java]: We can clean up this comment a bit - I think even just this TODO is more than enough. #6343 ended up using a different approach, and the link to `PostsListAdapter` is a 404.

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/MediaUploadReadyProcessor.java [hunk 6]
```diff
@@ -29,4 +32,24 @@ public PostModel replaceMediaFileWithUrlInPost(@Nullable PostModel post, String
 
         return post;
     }
+
+    @Override
+    public PostModel markMediaUploadFailedInPost(@Nullable PostModel post, String localMediaId, final MediaFile mediaFile) {
```
Comment (aforcier) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/MediaUploadReadyProcessor.java]: This line is over 120 chars.

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/MediaUploadReadyProcessor.java [hunk 7]
```diff
@@ -5,11 +5,14 @@
 import org.wordpress.android.WordPress;
 import org.wordpress.android.editor.AztecEditorFragment;
 import org.wordpress.android.editor.EditorFragment;
+import org.wordpress.android.fluxc.model.MediaModel;
```
Comment (aforcier) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/MediaUploadReadyProcessor.java]: Unused import (also `java.util.List` below).

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java [hunk 8]
```diff
@@ -362,12 +391,20 @@ public static boolean hasPendingOrInProgressMediaUploadsForPost(PostModel postMo
         return postModel != null && MediaUploadHandler.hasPendingOrInProgressMediaUploadsForPost(postModel);
     }
 
+    public static boolean hasAnyFailedMediaUploadsForPost(PostModel postModel) {
```
Comment (aforcier) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java]: Could can drop the `Any` from the method name so it's more consistent with the others?

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java (hunk 1 above)
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java]: 👍 addressed in b057f2a

File: WordPress/src/main/java/org/wordpress/android/ui/media/services/MediaUploadReadyListener.java (hunk 2 above)
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/media/services/MediaUploadReadyListener.java]: addressed in 0425820

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListFragment.java (hunk 4 above)
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListFragment.java]: addressed in fe1e21c

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListFragment.java (hunk 5 above)
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListFragment.java]: addressed in 27ae325

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/MediaUploadReadyProcessor.java (hunk 7 above)
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/MediaUploadReadyProcessor.java]: addressed in fcce6ee

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/MediaUploadReadyProcessor.java (hunk 6 above)
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/MediaUploadReadyProcessor.java]: addressed in 4c69335

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java (hunk 3 above)
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java]: IIUC it is true it would be okay to just use a plain Map here in `onDestroy`, but I wanted to keep the same code as in `stopServiceIfUploadsComplete()`, where the map needs to be concurrent-aware as per the several entry points. As a matter of fact, given these were identical pieces of code, refactored them into one method in 7418804

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java (hunk 8 above)
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java]: Removed the method altogether in 2c577cb. As of the change requested in https://github.com/wordpress-mobile/WordPress-Android/pull/6366/files/7194bbd103ac9e944350af320ea82911152633ab#r129034268 the method was left unused.

**Comment by mzorz** [comment]
I think it's ready for another round @aforcier ! 🙇

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java (hunk 3 above)
Comment (aforcier) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java]: Looking at this again, we're not actually using the `List<MediaModel>` part of the map - we only want a list of the post ids with either completed or failed media. So what if we just did something like:

```java
List<Integer> postIdList = new ArrayList<>();
postIdList.addAll(sCompletedMediaByPost.keySet());
postIdList.addAll(sFailedMediaByPost.keySet());
```

and dropped the `ConcurrentHashMap<Integer, List<MediaModel>> tmpMap`?

Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java]: good call! done in bf5c381

**Comment by aforcier** [comment]
:shipit:
