### PR TITLE
Fix #5205 Replace Merriweather by default Android serif font.

### LINKED ISSUE #3358: Missing Characters for Tajik Cyrilic language
Note: missing characters appears in the Post List, but probably everywhere else
b6863fb4b4ddb3bd6a1bb2942b265f43aab1b8da

Example of failing characters: 
- [Ҳ](https://en.wiktionary.org/wiki/%D2%B2)
- [Ҷ](https://en.wiktionary.org/wiki/%D2%B6)

as in `ҲИҶРАТ – ОРЗУ ИСО`

I don't think it comes from the font. I tried this sentence in https://typecast.com/preview/google/Merriweather and everything was correctly displayed. I wonder if that comes from the font renderer.

Ref https://github.com/wordpress-mobile/WordPress-Android/issues/2460 (vietnamese characters bug)

### LINKED ISSUE #5205: Remove Merriweather from the app, use Noto Serif where Merriweather was used
Noto is a native font, so we don't have to add it to our assets. There is a dirty patch [here](https://github.com/wordpress-mobile/WordPress-Android/compare/feature/replace-merriweather-by-noto) but it was only made for a test.

### PR DESCRIPTION
**Pull request by maxme**
Fix #5205 Replace Merriweather by default Android serif font.

Note the default `serif` setting on recent Android version (4.4+) will use Noto Serif, on older versions the old Droid Serif font will be used.

I also removed the extra code we had used to replace Roboto by Open Sans, this simplifies some of our layout and views.

~Note: I labelled this "Not ready for review" because I want to make sure this patch fixes #3358.~

We also need to make sure Merriweather is not used in other of our sub projects (I'll open a PR in the Aztec project).

cc @mattmiklic - here is a [test apk](https://cloudup.com/cjqaq4h8eqG).

### CODE REVIEW

**Comment by mattmiklic** [comment]
> cc @mattmiklic - here is a test apk.

Hey @maxme; I'm getting an error from Cloudup when I try to download ("The download of this file has been disabled for security reasons."

**Comment by maxme** [comment]
@mattmiklic I think cloudup disabled zip files (apks are special zip files) - I uploaded the same apk here: https://bia.is/s/dr35/wpandroid-wasabi-noto.apk

**Comment by mattmiklic** [comment]
@maxme Got it, thanks!

**Comment by maxme** [comment]
I confirm this patch fixes #3358 on older devices (DroidSerif is used in this case).

File: libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/SourceViewEditText.java [hunk 1]
```diff
@@ -43,18 +41,4 @@ public boolean onKeyPreIme(int keyCode, KeyEvent event) {
     public void setOnImeBackListener(OnImeBackListener listener) {
         this.mOnImeBackListener = listener;
     }
-
-    private void setCustomTypeface(AttributeSet attrs) {
```
Comment (nbradbury) [inline libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/SourceViewEditText.java]: Now that this is removed, there are several imports that can also be removed.

File: libs/editor/WordPressEditor/src/main/res/layout/fragment_editor.xml [hunk 2]
```diff
@@ -42,7 +42,7 @@
                 android:textColorHint="@color/sourceview_placeholder_text"
                 android:inputType="textCapSentences|textAutoCorrect"
                 android:imeOptions="flagNoExtractUi"
-                editor:fontFile="Merriweather-Bold.ttf"/>
```
Comment (nbradbury) [inline libs/editor/WordPressEditor/src/main/res/layout/fragment_editor.xml]: Since we dropped Merriweather Bold here, should we add `android:textStyle="bold"`?

File: libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/SourceViewEditText.java (hunk 1 above)
Comment (nbradbury) [inline libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/SourceViewEditText.java]: Unrelated to this PR, should this extend `AppCompatEditText` rather than `EditText`?

**Comment by nbradbury** [comment]
I'm done with this round. Apart from some small nits, it looks good.

**Comment by mattmiklic** [comment]
Looking pretty good overall. It looks like we're not seeing the correct font in a few places:

- In the editor, the post title is correct but the post content is in Roboto instead of Noto Serif.
- In the Reader full post view, the post content is in Roboto instead of Noto Serif.

Curiously, text inside an H2 tag uses the correct typeface, as does text that is italicized. Screenshot below.

screen shot 2017-03-06 at 1 59 10 pm

**Comment by maxme** [comment]
@mattmiklic I can repro, this is really weird - even the Chome inspect tools shows the correct font is used (same for all elements) but Noto is only rendered for the h2 tag...

H1 tag:
screen shot 2017-03-06 at 20 39 23

H2 tag:
screen shot 2017-03-06 at 20 39 29

File: libs/editor/WordPressEditor/src/main/res/layout/fragment_editor.xml (hunk 2 above)
Comment (maxme) [inline libs/editor/WordPressEditor/src/main/res/layout/fragment_editor.xml]: Yes, I missed that one.

**Comment by mattmiklic** [comment]
> even the Chome inspect tools shows the correct font is used (same for all elements) but Noto is only rendered for the h2 tag...

That is super strange. I see `sans-serif` listed after `serif` in the `font-family` rule, could that be related? Probably not, as I see it on both examples, but we probably don't need `sans-serif` as a fallback for our serif fonts.

File: libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/SourceViewEditText.java (hunk 1 above)
Comment (maxme) [inline libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/SourceViewEditText.java]: Fixed in  	8c1dac0

File: libs/editor/WordPressEditor/src/main/res/layout/fragment_editor.xml (hunk 2 above)
Comment (maxme) [inline libs/editor/WordPressEditor/src/main/res/layout/fragment_editor.xml]: Fixed in  	d9c0eef

**Comment by maxme** [comment]
@mattmiklic css weirdness fixed in 021f007.
@nbradbury ready for a second round.

**Comment by nbradbury** [comment]
@maxme This looks good to me, but another quick look by @mattmiklic would be a good idea since his designer eyes spot things my don't. Once he gives the nod I'll merge this.

**Comment by maxme** [comment]
> but another quick look by @mattmiklic would be a good idea since his designer eyes spot things mine don't. Once he gives the nod I'll merge this.

👍 - new apk: https://bia.is/s/WuOM/wpandroid-wasabi-noto-v2.apk

**Comment by mattmiklic** [comment]
Everything is looking good now! :y:

FWIW, I don't think it's necessary to call `Noto Serif` by name in CSS; in my mobile web experience Android devices will load either Noto or Droid (for older versions of the OS) if you use the `serif` keyword on its own.
