### PR TITLE
Fix: Missing featured images in Post List

### LINKED ISSUE #5575: Featured image missing in posts list
After a fresh install, featured image won't show up for the first time it's fetched. This is probably overlooked during fluxc integration.

### PR DESCRIPTION
**Pull request by oguzkocer**
Fixes #5575. This PR fixes the missing featured images for when the relevant media is not yet in the DB. (fresh install, new post etc). It also makes sure multiple posts with the same featured image are updated once the media is downloaded as we were assuming only one post has a specific featured image.

To test:
* Setup some posts with featured images, make sure at least 2 posts have the same featured image (pick from media library, so the same id is used)
* Fresh install the app (to make things easier)
* Go into the blog posts page for that site, just scroll up and down and make sure the featured images show up. Pay special attention to the 2 posts you setup with the same featured image.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListFragment.java [hunk 1]
```diff
@@ -639,4 +630,19 @@ public void onPostUploaded(OnPostUploaded event) {
...
     }
+
+    /*
+     * Media info for a post's featured image has been downloaded, tell
+     * the adapter so it can show the featured image now that we have its URL
+     */
+    @SuppressWarnings("unused")
+    @Subscribe(threadMode = ThreadMode.MAIN)
+    public void onMediaChanged(MediaStore.OnMediaChanged event) {
+        if (isAdded() && !event.isError() && getPostListAdapter() != null) {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListFragment.java]: Calling `getPostListAdapter()` will create the adapter if it doesn't already exist, so instead we should use `mPostsListAdapter != null` here.

File: WordPress/src/main/java/org/wordpress/android/ui/posts/adapters/PostsListAdapter.java [hunk 2]
```diff
@@ -660,12 +660,15 @@ public void unhidePost(PostModel post) {
...
-        if (isValidPostPosition(position)) {
-            int postId = mPosts.get(position).getId();
-            mFeaturedImageUrls.put(postId, mediaUrl);
-            notifyItemChanged(position);
+    public void mediaChanged(MediaModel mediaModel) {
+        // Multiple posts could have the same featured image
+        List<Integer> indexList = PostUtils.indexesOfFeaturedMediaIdInList(mediaModel.getMediaId(), mPosts);
+        for (int position : indexList) {
+            if (isValidPostPosition(position)) {
+                int postId = mPosts.get(position).getId();
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/adapters/PostsListAdapter.java]: Rather than access `mPosts` directly, can we use `getItem(position)` here? Example:
```
for (int position : indexList) {
    PostModel post = getItem(position);
    if (post != null) {
        mFeaturedImageUrls.put(post.getId(), mediaModel.getUrl());
        notifyItemChanged(position);
    }
}
```

**Comment by nbradbury** [comment]
@oguzkocer Only a couple of minor nits here, otherwise code looks good and works great!

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListFragment.java (hunk 1 above)
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListFragment.java]: You're right. I just used the previous implementation and didn't really think about it, which is my bad. Fixed in 39163f0892929902f88e6808a06694836a1a26ab

File: WordPress/src/main/java/org/wordpress/android/ui/posts/adapters/PostsListAdapter.java (hunk 2 above)
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/adapters/PostsListAdapter.java]: Similar to above, just used the previous implementation, but `getItem` is definitely better. Thanks! Fixed in 7729152999b27693ee4ce7405c108baa88d6dbbe

**Comment by oguzkocer** [comment]
Thanks for the review @nbradbury! Ready for another round.

**Comment by nbradbury** [comment]
Looks good! :shipit:
