### PR TITLE
Fix #5032: show a dialog if jetpack is not installed or enabled/connected

### LINKED ISSUE #5032: Visiting Stats on a self hosted site should show an "Install Jetpack" dialog or an error message
### Expected behavior

Ask the user to install Jetpack or show a Dialog "You must install Jetpack to get your Statistics on this site, blablabla".

### Actual behavior

Duplicated error:

screenshot-2017-01-19_13 41 15 838

### PR DESCRIPTION
**Pull request by maxme**
Fix #5032

### CODE REVIEW

**Comment by maxme** [comment]
Oh and this https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/288 must be merged before testing this PR.

**Comment by aforcier** [comment]
At the moment, for any self-hosted site that's not Jetpack-connected, I don't get any popups at all - I get a toast saying "Stats couldn't be refreshed at this time" and remain on the "My Site" screen.

(Unless I'm not signed into WP.com yet, in which case I'm sent to the WP.com login page with the correct "To view your stats, log in..." screen, but still the the "Stats couldn't be refreshed at this time" toast.)

**Comment by maxme** [comment]
@aforcier I removed an extra check that was causing the activity to stop in `onResume` - this fix the issue you mentioned.

I tried the full process from a pure self hosted site to a jetpack connected site. There is an issue on the FluxC side, the `isWPCom` flag is not updated and thus the StatsActivity doesn't consider this site can be used for Stats.

Currently the `isWPCom` flag is set when sites came from the REST API fetch all sites. But we use it as "can this site be accessed via the WPCom REST API", so we should set this flag to true [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/7fd7a800ac3900d3a95a430fbe86de7e03ba00cd/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/site/SiteXMLRPCClient.java#L201-L201) (if `JETPACK_CLIENT_ID_KEY` != 0).

**Comment by maxme** [comment]
Documentation of the `wp.getOptions` response by Jetpack status:

* Jetpack not installed: field `jetpack_client_id` not included in the response
* Jetpack installed but not activated: field `jetpack_client_id` not included in the response
* Jetpack installed, activated but not connected: field `jetpack_client_id` included and is `0` (boolean see the note1 below)
* Jetpack installed, activated and connected: field `jetpack_client_id` included and is correctly set to wpcom unique id eg. `1234` (see note2)


Note1: the exact response is:
```
<member>
  <name>jetpack_client_id</name>
  <value>
    <struct>
      <member>
        <name>value</name>
        <value>
          <boolean>0</boolean>
        </value>
      </member>
    </struct>
  </value>
</member>
```

Note2:
```
<member>
  <name>jetpack_client_id</name>
  <value>
    <struct>
      <member>
        <name>value</name>
        <value>
          <int>1234</int>
        </value>
      </member>
    </struct>
  </value>
</member>
```

**Comment by daniloercoli** [comment]
Side note: In those cases of missing `jetpack_client_id` in the response
-  Jetpack not installed: field `jetpack_client_id` not included in the response
- Jetpack installed but not activated: field `jetpack_client_id` not included in the response
we can check if Jetpack is actually installed or not on the site by doing a GET request to the address
site/$plugins-folder/jetpack/. If the HTTP response code is != 404 the plugin is installed on the site.

**Comment by maxme** [comment]
@daniloercoli I don't think we need to distinguish these 2 cases, and I would prefer to not do that ;)

**Comment by maxme** [comment]
Marking this PR not ready for review until https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/302 is merged.

**Comment by daniloercoli** [comment]
Mine comment was just just food for thought. If we can distinguish between those two states, we can redirect the user to different pages, and provide different error messages. My .2$

**Comment by maxme** [comment]
Related to https://github.com/wordpress-mobile/WordPress-Android/issues/5134

**Comment by aforcier** [comment]
Looks like all uses of `isWPCom()` in FluxC need to be looked at - we're still relying on that in `PostStore` (and I'm sure elsewhere) to decide between REST API and XML-RPC, and this is causing Jetpack sites to use XML-RPC (and fail).

**Comment by aforcier** [comment]
There's an issue with enabling Jetpack for self-hosted sites through the app:

1. Clear app data
2. Log into .com account without Jetpack site
3. Add self-hosted site with Jetpack installed but not connected
4. Visit stats
5. Get "installed but not connected prompt" 👍 
6. Go through connecting in WebView, finish, navigate back to the app
7. Stats don't load, refreshing shows permanent refresh animation 💥
8. Exit stats screen, go back
9. Get "Jetpack not connected" prompt again 💥
10. Click through to open WebView again, Jetpack definitely already connected
11. Switch sites in the picker and back again
12. Visit stats
13. Stats load, but I get a "Jetpack not connected" prompt 💥
14. Press 'no', booted out of stats
15. Open stats again
16. Success!

File: WordPress/src/main/java/org/wordpress/android/ui/stats/StatsActivity.java [hunk 1]
```diff
@@ -180,6 +180,14 @@ public void run() {
...
         }
 
+        if (mSite == null) {
+            ToastUtils.showToast(this, R.string.blog_not_found, ToastUtils.Duration.SHORT);
+            finish();
+            return;
+        }
+
+        // If the site is not connected via wpcom (Jetpack included), then show a dialog to the user.
+        checkIfSiteHasAccessibleStats(mSite);
```
Comment (aforcier) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/StatsActivity.java]: Somewhere around here we need to make sure the user is actually signed into WP.com.

From a clean app, add a self-hosted site that is Jetpack-connected, and visit stats. You get the old repeated message shown in https://github.com/wordpress-mobile/WordPress-Android/issues/5032, because we determined that it's WP API-accessible but haven't verified a token.

File: WordPress/src/main/java/org/wordpress/android/util/AuthenticationDialogUtils.java [hunk 2]
```diff
@@ -30,6 +30,8 @@ public static void showAuthErrorView(Activity activity, int titleResId, int mess
             return;
         }
 
+        // TODO: isJetpackConnected - there is probably
```
Comment (aforcier) [inline WordPress/src/main/java/org/wordpress/android/util/AuthenticationDialogUtils.java]: Something's missing here 😁

File: WordPress/src/main/java/org/wordpress/android/ui/stats/StatsActivity.java (hunk 1 above)
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/StatsActivity.java]: Hmm, I should actually move the test on line 277

Comment (aforcier) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/StatsActivity.java]: Confirm fixed by a3b2600.

**Comment by aforcier** [comment]
> There's an issue with enabling Jetpack for self-hosted sites through the app

Confirm fixed by 546f587 - stats refresh immediately upon dismissing the `WebView` and everything works.

**Comment by aforcier** [comment]
When following the prompt in Stats and opening the WebView to connect Jetpack, if I back out without actually connecting Jetpack, I get a blank Stats screen with a perpetual loading animation.

If I exit and come back, I get the popup again as expected.

File: WordPress/src/main/java/org/wordpress/android/util/AuthenticationDialogUtils.java (hunk 2 above)
Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/util/AuthenticationDialogUtils.java]: Fixed in 792cb930f7

**Comment by maxme** [comment]
> When following the prompt in Stats and opening the WebView to connect Jetpack, if I back out without actually connecting Jetpack, I get a blank Stats screen with a perpetual loading animation.
> 
> If I exit and come back, I get the popup again as expected.

Fixed in d750823 by checking if the updated site is accessible.

**Comment by aforcier** [comment]
Tested:

* Sign in to WP.com with Jetpack site -> Visit stats for pure and Jetpack sites :+1:
* Sign in to WP.com -> Add self-hosted site with installed but not connected Jetpack -> Stats -> Connect -> Go back to Stats -> Sign out :+1:
* Sign in to Jetpack-connected self-hosted site -> Stats -> Login to WP.com screen -> no dupes appear -> Stats work -> Fetch posts -> Using REST API :+1:
* Sign in to non-Jetpack self-hosted site -> Stats -> Login to WP.com screen -> Stats -> "Install Jetpack" prompt -> Connect Jetpack -> Go back to Stats :+1:
* Jetpack not installed vs not connected is properly identified :+1:

I also tested the unsupported flow of WP.com site -> add self-hosted Jetpack site connected to another account. Nothing works and it's pretty obvious (which is good), but nothing explodes either - obviously it needs work but we can live with this for now.

Nice work @maxme, :shipit:!
