### PR TITLE
issue/7389-signin-site-link-hidden

### LINKED ISSUE #7389: Sign in with site link hidden by keyboard
On some devices, the link to sign in using the site URL is hidden by the soft keyboard. We should hide the keyboard when the user fails to sign in with their email to ensure this link is visible.

screenshot_20180305-181343

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #7389 - When email isn't registered, we now hide the keyboard to ensure the link to login using the site address is visible (on some devices it would be hidden by the keyboard).

### CODE REVIEW

File: libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailFragment.java [hunk 1]
```diff
@@ -37,8 +37,10 @@
 import org.wordpress.android.login.util.SiteUtils;
 import org.wordpress.android.login.widgets.WPLoginInputRow;
 import org.wordpress.android.login.widgets.WPLoginInputRow.OnEditorCommitListener;
+import org.wordpress.android.util.ActivityUtils;
 import org.wordpress.android.util.AppLog;
 import org.wordpress.android.util.AppLog.T;
+import org.wordpress.android.util.DisplayUtils;
```
Comment (mzorz) [inline libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailFragment.java]: this is unused

File: libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailFragment.java [hunk 2]
```diff
@@ -346,6 +348,8 @@ public void onAvailabilityChecked(OnAvailabilityChecked event) {
         if (event.isError()) {
             // report the error but don't bail yet.
             AppLog.e(T.API, "OnAvailabilityChecked has error: " + event.error.type + " - " + event.error.message);
+            // hide the keyboard to ensure the link to login using the site address is visible
+            ActivityUtils.hideKeyboardForced(mEmailInput);
```
Comment (mzorz) [inline libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailFragment.java]: If the event is not `isError()` and also `event.type == EMAIL` and `event.isAvailable`, then we enter [this case here](https://github.com/wordpress-mobile/WordPress-Android/pull/7391/files#diff-81a24078c194c1cab83eb26f8fe1bceeR361) , so we should insert these same 2 lines there as well.

```
// hide the keyboard to ensure the link to login using the site address is visible
ActivityUtils.hideKeyboardForced(mEmailInput);
```

Also, what do you think about replacing [this line here ](https://github.com/wordpress-mobile/WordPress-Android/pull/7391/files#diff-81a24078c194c1cab83eb26f8fe1bceeR363) `EditTextUtils.hideSoftInput(mEmailInput.getEditText());`  (marked deprecated) with `ActivityUtils.hideKeyboardForced(mEmailInput);` to keep it consistent?

**Comment by nbradbury** [comment]
Thanks for the review @mzorz! I made the changes you suggested.

**Comment by mzorz** [comment]
Thank you @nbradbury ! :shipit:
