### PR TITLE
fix #2848 by using WPViewPager including a workaround

### LINKED ISSUE #2848: Crash report 4.1: IllegalArgumentException: pointerIndex out of range
We're already using a workaround in `WPMainViewPager`, we should replace all our standard `ViewPager` by it.

```
java.lang.IllegalArgumentException: pointerIndex out of range
       at android.view.MotionEvent.nativeGetAxisValue(MotionEvent.java)
       at android.view.MotionEvent.getX(MotionEvent.java:1979)
       at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
       at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:91)
       at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:219)
       at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:1839)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1852)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2209)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1952)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2209)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1952)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2209)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1952)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2209)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1952)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2209)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1952)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2209)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1952)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1966)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1418)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2424)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1914)
       at android.view.View.dispatchPointerEvent(View.java:7564)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3883)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3778)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3483)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3540)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5419)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5399)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5370)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5493)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:182)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:174)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5472)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5512)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
       at android.view.Choreographer.doCallbacks(Choreographer.java:562)
       at android.view.Choreographer.doFrame(Choreographer.java:530)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
       at android.os.Handler.handleCallback(Handler.java:730)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5103)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

### PR DESCRIPTION
**Pull request by maxme**
fix #2848 by using WPViewPager including a workaround.

Merge WPViewPager and WPMainViewPager, remove dead code, and use WPViewPager everywhere we were using the standard ViewPager.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/widgets/WPViewPager.java [hunk 1]
```diff
@@ -5,45 +5,51 @@
...
-    @Override
-    public void setCurrentItem(int currentItem) {
-        mPreviousPage = getCurrentItem();
-        super.setCurrentItem(currentItem);
-    }
-
-    public int getPreviousPage() {
-        return mPreviousPage;
+    public void setPagingEnabled(boolean pagingEnabled) {
+        mPagingEnabled = pagingEnabled;
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/widgets/WPViewPager.java]: This would previously disable the ViewPager (so the user couldn't change pages), but it's not doing anything here.

Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/widgets/WPViewPager.java]: `mPagingEnabled` is used [here](https://github.com/wordpress-mobile/WordPress-Android/blob/issue/2848-viewpager-merge/WordPress/src/main/java/org/wordpress/android/widgets/WPViewPager.java#L30) and [here](https://github.com/wordpress-mobile/WordPress-Android/blob/issue/2848-viewpager-merge/WordPress/src/main/java/org/wordpress/android/widgets/WPViewPager.java#L42) - and it's used in the MediaPicker and the Editor.

Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/widgets/WPViewPager.java]: Ah, I missed that it was being used in those touch events. Ignore me :)

**Comment by nbradbury** [comment]
:shipit:
