### PR TITLE
fixed notifications being cleared on device rotation / on resume

### LINKED ISSUE #4647: Notification is dismissed when device is rotated
### Expected behavior
When I have the WordPress app on the foreground and I receive a push notification, the notification icon should stay there even if I rotate the device.

### Actual behavior
When I have the WordPress app on the foreground and I receive a push notification, I notice the notification icon appears in the system bar.
If I rotate the device, the notification icon for the WordPress app is now gone.

### Steps to reproduce the behavior
1. Open the app and leave it in the foreground
2. make something happen in the outside that triggers a push notification (for example, have some other user comment on a blog post you're an admin of)
3. observe the notification icon appear
4. rotate the device
5. observe the notification icon disappear

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #4647 by moving the notification removal code from NotificationsListFragment.onResume() to the onPageSelected event for the viewpager.

To test:
1. Open the app and leave it in the foreground
2. make something happen in the outside that triggers a push notification (for example, have some other user comment on a blog post you're an admin of)
3. observe the notification icon appear
4. rotate the device
5. observe the notification icon is still there in the system bar

Repeat steps 4-5 while switching the tabs in the app. Notification icon should only be dismissed when the Notifications tab is selected.

Needs review @daniloercoli

### CODE REVIEW

**Comment by daniloercoli** [comment]
PR seems fine to me, even though I found an issue that's very close to the reported issue in your PR.

Go to the Notifications List screen, then tap on a Note and stay on the details screen.
Open a browser and make a comment..(same steps of above)... 
You will receive a PN. If you tap back, the app takes you back to the Notifications list again, but the notification is not cleared from the status bar.  Base branch doesn't have this issue, since `onResume` is called and then notes are cleared.
Thoughts?

**Comment by mzorz** [comment]
Nice catch! And interesting too. Will look into it, maybe if we use `setResult` on the called fragment or alike. Let me think a bit and get back to this 👍

**Comment by mzorz** [comment]
Just added another commit (https://github.com/wordpress-mobile/WordPress-Android/pull/4648/commits/f80ece5487a571d46eb06d109009eb12b6a2c048) to cover both sides for "entering the Notification list" 
Let me know what you think @daniloercoli 👍

File: WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsDetailActivity.java [hunk 1]
```diff
@@ -148,6 +148,14 @@ protected void onSaveInstanceState(Bundle outState) {
         super.onSaveInstanceState(outState);
     }
 
+    @Override
+    public void onBackPressed() {
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsDetailActivity.java]: This for sure fixes the issue :)

The only thing that makes me thing a little bit more before merging this PR, is that we're clearing Notifications status bar from a details fragment. Note that `NotificationsDetailActivity` is also called from `WPMainActivity` when the app is started from PN https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java#L266.

Right before launching the Note details activity we're setting Notifications as default tab `mViewPager.setCurrentItem(WPMainTabAdapter.TAB_NOTIFS);` , but what if we will call this details activity from some other place in the future? Maybe without having `NotificationsList` in the back stack? Notifications will be cleared in the status bar, but the user isn't in the NotificationsList. 
Don't know if I was clear in the description...

I remember we had tackled a similar issue for Analytics in the past. See https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java#L328
Hope we can clear notifications there, only when the current active tab is `Notifications`. Would you mind to explore this other way?

**Comment by daniloercoli** [comment]
:shipit:
