### PR TITLE
Fix page not found preview on jetpack sites

### LINKED ISSUE #10544: Draft preview fails to load: Page not found
Test Online-SelfHosted-4

### Expected behavior
The preview of a draft without local changes loads.

### Actual behavior
The preview of a draft without local changes fails to load - page not found message is shown.

### Steps to reproduce the behavior
0. ~Log into a Self-hosted site~ (update: Login into a Jetpack site using self-hosted login)
1. On the post list, Draft tab selected
2. Open the editor (Aztec) with a draft without local changes
3. Tap “… More” -> “View”
3. Remote view (webview) should open

##### Tested on [device], Android [version], WPAndroid [version]
Samsung Galaxy S9 (Android 9)

See comments on p77Llu-cHb-p2 for more info and video.

### PR DESCRIPTION
**Pull request by malinajirka**
Fixes #10544 

Post preview didn't work if you logged into a jetpack site using self-hosted login. The app would try to use `frame_nonce` even though it didn't have it. If you logged into the same site using wpcom login, everything would work.

This PR simply checks whether `frame_nonce` is available and if it's not we try to load the preview using self-hosted sites credentials.

To test:
1. Log in into a Jetpack site using self-hosted login
2. Open Post List on draft tab
3. Click on More -> Preview on a post without local changes
4. Make sure the preview loads

--------------------
1. Log in into a wpcom account and select a jetpack site
2. Open Post List on draft tab
3. Click on More -> Preview on a post without local changes
4. Make sure the preview loads

PR submission checklist:

- [x] I have considered adding unit tests where possible.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java [hunk 1]
```diff
@@ -609,7 +609,7 @@ private static void browsePostOrPageEx(
                     shareSubject,
                     true,
                     startPreviewForResult);
-        } else if (site.isJetpackConnected()) {
+        } else if (site.isJetpackConnected() && !TextUtils.isEmpty(site.getFrameNonce())) {
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java]: I believe we can achieve the same thing with this:

```suggestion
        } else if (site.isJetpackConnected() && site.isUsingWpComRestApi()) {
```

Alternatively we can just add the `site.isUsingWpComRestApi()` but also keep `!TextUtils.isEmpty(site.getFrameNonce())`.

I think all 3 of these solutions would work, I just like the explicit `isUsingWpComRestApi` check because it makes the code a bit clearer for me since we call `openJetpackBlogPostPreview` afterwards.

Comment (malinajirka) [reply WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java]: It crossed my mind that `isUsingWpComRestApi` is identical to `frameNonce != empty`, but I wasn't sure. 👍 Definitely a nice improvement. Thanks

**Comment by malinajirka** [comment]
Thanks @oguzkocer !

I've committed your suggestion and tested the app and it works like a charm! It's much clearer now. 

Since you've proposed this change and approve this PR, I'm merging it ;).
