### PR TITLE
Fix blaze animation and click behavior

### LINKED ISSUE #18091: Blaze: Blaze card animates a second ripple animation around the flame regardless of where the card is tapped.
### Expected behavior
The card should animates as a whole when tapped.

### Actual behavior
When tapping anywhere within the card a separate ripple animation around the flame is triggered.

|  |
| - |
|  | 
| <video width="300" src="https://user-images.githubusercontent.com/42008628/224832874-1cba2880-a241-4b06-ab61-d32ebe8ded3c.mp4"> |

### Steps to reproduce the behavior
0. Make sure that Blaze is enabled via the debug menu
1. Select a site that has Blaze enabled.
2. Tap the Blaze Card in Dashboard.

### PR DESCRIPTION
**Pull request by zwarm**
Fixes #18091 and #18092 

This PR address two issues with Blaze:
(1) Blaze Card: Eliminates the second ripple animation around the flame regardless of where the card is tapped
(2) Makes the “Blaze a Post now 🔥” button tappable across the entire width

**To test:**
- Install and launch the app
- Login with a wp.com account that has blaze access 

**Test: No more second ripple animation**
- Navigate to the dashboard
- Tap on the Blaze Card
- ✅ Verify there is no longer a second ripple on the flame image

**Test: Entire button is clickable**
- Navigate to the dashboard
- Tap on the Blaze Card
- Tap the "Blaze a post Now" button
- ✅ Verify the entire button is tappable by tapping anywhere except the text (although tapping on the text will also work)

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:
- [X] I have completed the Regression Notes.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/compose/components/ImageButton.kt [hunk 1]
```diff
@@ -60,7 +58,8 @@ fun ImageButton(
     button: Button,
     onClick: () -> Unit
 ) {
-    ConstraintLayout(modifier = modifier) {
+    ConstraintLayout(modifier = modifier
+        .clickable { onClick.invoke() }) {
```
Comment (AjeshRPai) [inline WordPress/src/main/java/org/wordpress/android/ui/compose/components/ImageButton.kt:62]: 👏🏼 Nice 🙌🏼

**Review by AjeshRPai — APPROVED** [review]
Hey @zwarm 

Everything works as expected now. Nice work. Thanks 

- The click on the whole width of the button works 👍🏼 
- The ripple animation is only shown once 👍🏼 

cc: @tiagomar am merging this PR so that it will be included in the new beta.
