### PR TITLE
[Reader] Fix like button responsiveness in "Discover" feed

### LINKED ISSUE #19533: [Reader Improvements] Fix like/dislike button responsiveness on Discover
When user taps on the like/dislike post button on `Discover` tab it takes a while to update the button status. This happens because we wait for the network response and also the local DB update before updating the UI. The same doesn't happen on `Following` and `Liked` tabs.

We should update the UI immediately after the user taps on the like button and if the network request fails we show the previous status.

### PR DESCRIPTION
**Pull request by RenanLukas**
Fixes #19533 

-----

## To Test:

1. Install JP and sign in.
2. Open Reader and select "Discover".
3. 🔍 Like a post with internet connection available: it should work as expected.
4. 🔍 Tap the like button again to remove the like with internet connection available: it should work as expected.
5. 🔍 Repeat steps 3 and 4 with no internet connection (e.g. airplane mode) and bad internet connection (e.g. 100% loss on Network Link Conditioner). If there's no connection, the like button state shouldn't change and if there's bad network connection the button should change right away and then when the request fails return to the previous state.

-----

## Regression Notes

1. Potential unintended areas of impact

    - Reader post list like button

2. What I did to test those areas of impact (or what existing automated tests I relied on)

    - Manual testing

3. What automated tests I added (or what prevented me from doing so)

    --

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WordPress/src/main/java/org/wordpress/android/ui/reader/discover/viewholders/ReaderPostNewViewHolder.kt [hunk 1]
```diff
@@ -164,7 +167,14 @@ class ReaderPostNewViewHolder(
         view.isVisible = state.isEnabled
         view.isSelected = state.isSelected
         view.contentDescription = state.contentDescription?.let { uiHelpers.getTextOfUiString(view.context, it) }
-        view.setOnClickListener { state.onClicked?.invoke(postId, blogId, state.type) }
+        view.setOnClickListener {
+            // If it's a like action, we want to update the UI right away. If there's an error, we'll revert
+            // the UI change.
+            if (state.type == ReaderPostCardActionType.LIKE && networkUtilsWrapper.isNetworkAvailable()) {
```
Comment (RenanLukas) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/discover/viewholders/ReaderPostNewViewHolder.kt:173]: > networkUtilsWrapper.isNetworkAvailable()

This is ugly and shouldn't be here, but after spending a few hours trying to solve the problem the "right way" by using `PostLikeUseCase`, `ReaderPostCardActionsHandler` and a few other classes I realized it wasn't worth it. If you're aware of another way to handle the no internet connection scenario, please let me know.

Comment (daniloercoli) [reply WordPress/src/main/java/org/wordpress/android/ui/reader/discover/viewholders/ReaderPostNewViewHolder.kt:173]: It appears that the UI is updated immediately when a network connection is detected, but independently of the network status, the event that attempt to contact the server is triggered. Therefore, if I'm on a spotty connection, there's a scenario where my first tap (like) doesn't update the UI, but the connection is established, and the server processes the like action for the post. Am I correct in assuming this behavior?

On the client side, is the UI updated when the server responds with success?

Comment (daniloercoli) [reply WordPress/src/main/java/org/wordpress/android/ui/reader/discover/viewholders/ReaderPostNewViewHolder.kt:173]: After discussing the details on Slack, it appears that the scenario I mentioned in the comment above isn't even an edge case, because the networkUtilsWrapper.isNetworkAvailable() check would have returned true even on spotty connections.

**Review by daniloercoli — APPROVED** [review]
LGTM!
