### PR TITLE
Fix WP Screenshot Automation UI Tests

### LINKED ISSUE #16845: WP/JP Failing UI Tests for Screenshots automation
Project thread: paaHJt-3wL-p2

This issue is for point [a1] WordPress + Jetpack Android - Make the UI Tests pass.

### Expected behavior
UI tests to capture the screenshots that we're submitting to the Play store are not working.
They seem to be outdated as they are failing when locating specific elements to click on during the tests.

### Actual behavior
The UI tests succeed so that we can use them via `fastlane` to take screenshots for the play store.

Fastlane command:
```sh
bundle exec fastlane android screenshots locale:en-US app:[either: wordpress or jetpack]
```

### Steps to reproduce the behavior
1. Create a virtual device, or
   Follow the guide in `SCREENSHOT_DEVICE_SETUP.md` to create a device like the ones we're using for screenshots automation (this won't be super easy as the guide is a bit outdated and if you're on an M1 Mac you have to change the generated `.ini` files manually set the `arm64` architecture or else the emultators won't start.
2. Run `wPScreenshotTest` from `WPScreenshotTest` and `jPScreenshotTest` from `JPScreenshotTest` a few times and notice they never succeed.

#### Note:
There could be 2 pull requests for fixing the issue:
1. One for the WordPress app
2. One for the Jetpack app

##### Tested on `Pixel 3 API 28` Emulator

### PR DESCRIPTION
**Pull request by ovitrif**
Fixes #16845 Partially — only the `WPScreenshotTest` and with the code for taking the editor screenshot commented out.

Changes:
- Add missing mock for the wpcom v2 dashboard cards request of site `106707880`.
- Fix navigation to post list.
- Fix navigation to stats.
- Fix navigation to media and back.
- Make navigating back from media more stable.
- Add navigation utilities to `MySitesPage` and use them.
- Create method for going to drafts in `PostsListPage` and use it.
- Refactor code to remove `moveToStats` - Ideally there'll be only methods for screenshots in `WPScreenshotTest`. More granular methods that concern only specific tests add to the cognitive load and make it harder to understand the class.
- Comment out `editBlogPost` and add info explaining why.

### To test:
 - Run the `wPScreenshotTest` from `WPScreenshotTest` 5 times in Android Studio to check that it succeeds consecutively and it's pretty stable.

 - Ideally we run them on an emulator created by `fastlane`. See the notes in the issue for how this can be done:
   > Create a virtual device, or
Follow the guide in `SCREENSHOT_DEVICE_SETUP.md` to create a device like the ones we're usin for screenshots automation (this won't be super easy as the guide is a bit outdated and if you're on an M1 Mac you have to change the generated .ini files manually to set the arm64 architecture or else the emultators won't start.

## Regression Notes
1. Potential unintended areas of impact
   The code I changed has only one usage which is this test.
   I'm not sure how the `fastlane screenshot` command will behave with the editor screenshot missing.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
   N/a

3. What automated tests I added (or what prevented me from doing so)
   N/a

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by AliSoftware** [comment]
At first I tested (just using the "Pixel 2 API 31" emulator I already had in Android Studio, not creating one via `fastlane`) and was surprised how fast the `wPScreenshotTest` test ran and passed. Like, the test was marked as passed in 2 seconds only. Felt suspicious.

Took me a couple of minutes to realize that I had `jetpackJalapenoDebug` selected in my active build variant… 🤦  (that shows you how little I use Android Studio, not being an Android dev 😂 ). So no wonder it was so fast: it encountered the `if (!BuildConfig.IS_JETPACK_APP)` test at the very beginning of the `wpScreenshotTest`, saw it as `false`, and skipped the entire thing 😂 

---

Then I switched my active build variant to `wordpressJalapenoDebug` instead.

 - On first try of the test, I got a `androidx.test.espresso.PerformException: Error performing 'androidx.test.espresso.contrib.RecyclerViewActions$ActionOnItemAtPositionViewAction@8568b2a' on view 'view.getId() is <2131363750/org.wordpress.android.prealpha:id/recycler_view>'.`. I'm. assuming that was because of the flakiness of the tests and it failing to find an element in a timely manner 😒 
 - On second try, it passed though — I was more attentive on what was happening on the emulator, and saw it log out then back in, then go to Discover, My Site, Stats, Notifications, Media, then log back out (and switching from light to dark mode on and off, I'm assuming at the moments when it took screenshots), and finally succeed the test. 🎉 
 - On subsequent runs number 3, 4, 5 and 6, it passed again.

So despite the first run that failed, it seems that it's a good start and at least in a better shape than before, so for me it's a ✅  😃 

_Obviously, I'm looking forward to the future follow-up PRs after this one to (1) fix then re-enable editor tests (as you mentioned in pbArwn-4Xj-p2#editblogposts-commented-out), and (2) also fix the JP screenshots 🤞_

---

I'll let @zwarm do a review and potential approval though, because I know she raised some points during our call last week about handling A/B tests (though I'm not sure that ends up being a real concern, because we confirms that the mocks are used during those Screenshots UI Tests so those AB tests should be mocked as well not dependent on any live flag in FRC, right?), and knows Android way better than I do, and worked on those as well… so I feel she'll be better placed to do the formal approval.

**Comment by ovitrif** [comment]
Thank you @AliSoftware for testing the PR 🙇 .

> On first try of the test, I got a androidx.test.espresso.PerformException: Error performing 'androidx.test.espresso.contrib.RecyclerViewActions$ActionOnItemAtPositionViewAction@8568b2a' on view 'view.getId() is <2131363750/org.wordpress.android.prealpha:id/recycler_view>'.. I'm. assuming that was because of the flakiness of the tests and it failing to find an element in a timely manner 😒

Indeed tough it's a bit interesting. The only line where I'd expect that to happen out of my head, given that we've disabled `editBlogPost()` is this:
```
waitForElementToBeDisplayedWithoutFailure(R.id.recycler_view);
```
But this one won't make the tests fail — as the name suggest it will wait for a while but the error is caught even if the element is not found, thus not resulting in the tests failing.

On another note, I do remember getting failures from time to time on the Site Picker. I wonder if it was there.

> I'll let @zwarm do a review and potential approval though, because I know she raised some points during our call last week about handling A/B tests (though I'm not sure that ends up being a real concern, because we confirms that the mocks are used during those Screenshots UI Tests so those AB tests should be mocked as well not dependent on any live flag in FRC, right?), and knows Android way better than I do, and worked on those as well… so I feel she'll be better placed to do the formal approval.

Awesome! I hope she'll have time or otherwise let me know to reach out to an Android developer from the WP mobile team.

**Comment by ovitrif** [comment]
> Obviously, I'm looking forward to the future follow-up PRs after this one to (1) fix then re-enable editor tests (as you mentioned in pbArwn-4Xj-p2#editblogposts-commented-out, and (2) also fix the JP screenshots 🤞

Indeed! I'm picking up the JP screenshots today (2), and I do expect it to go much faster, some problems will just be the same that were fixed for WP (in one instance for sure as I've had a quick look at the code).

File: WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java [hunk 1]
```diff
@@ -85,8 +87,8 @@ private void editBlogPost() {
 
         (new SitePickerPage()).chooseSiteWithURL("fourpawsdoggrooming.wordpress.com");
 
-        // Choose "Blog Posts"
-        clickOn(R.id.quick_action_posts_button);
+        // Choose "Posts"
+        clickOn(onView(withText(R.string.posts)));
```
Comment (zwarm) [inline WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java]: @ovitrif 
❓ - Help me understand the move from ID to Text for navigation. It feels like "ID" would be more stable than text, but I could be splitting hairs.

File: WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java [hunk 2]
```diff
@@ -262,7 +261,7 @@ private void manageMedia() {
 
         takeScreenshot("6-upload-on-the-go");
 
-        pressBackUntilElementIsDisplayed(R.id.quick_link_ribbon_item_list);
+        pressBackUntilElementIsDisplayed(R.id.site_info);
```
Comment (zwarm) [inline WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java]: @ovitrif - If in the future we had a test that scrolled down on the menu tab too far, neither of these views will be visible. I wonder if checking for the presence of one of the bottom nav tabs would be better for future proofing. This is only an FYI, not a request for a change. :) wdyt?

File: WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/MySitesPage.java [hunk 3]
```diff
@@ -107,4 +109,28 @@ private void clickItem(final Matcher<View> itemViewMatcher) {
                     .perform(actionOnItem(hasDescendant(itemViewMatcher), click()));
         }
     }
+
+    public static void goToPosts() {
+        goToMenuTab();
```
Comment (zwarm) [inline WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/MySitesPage.java]: @ovitrif - love this improvement, as it makes it very clear that we have to navigate to the menu tab first. ❤️

File: WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java [hunk 4]
```diff
@@ -62,7 +62,9 @@ public void wPScreenshotTest() {
 
             wpLogin(); // TODO commented for quicker debugging
 
-            editBlogPost();
+            // Disabled because it keeps failing with the `AppNotIdleException` caused by an infinite auto-save loop
```
Comment (zwarm) [inline WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java]: I am seeing this same issue if I uncomment the `editBlogPost()` test. :(

**Review by zwarm — APPROVED** [review]
@ovitrif - Nicely done. 👍  I left a question or two inline, but I did not encounter any show stoppers. I know you are readjusting the way `elements are clicked in the site menu` in the JP PR, so I am just leaving this comment for our future selves.

The only issue, and I think it's a local issue, is I did encounter "grey" background when viewing dark mode. See attached 
Alt desc

I am approving the PR, but won't merge until you can 👍 the gray background is a local issue for me. 

Thanks for tackling this. :)

File: WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java (hunk 2 above)
Comment (ovitrif) [reply WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java]: > I wonder if checking for the presence of one of the bottom nav tabs would be better for future proofing. This is only an FYI, not a request for a change. :) wdyt?

I agree, thank you 🙇  relying on the bottom nav tabs is more future proof ;), we're already doing this in another "test" so it makes sense to me to update it in this PR 👍

**Comment by ovitrif** [comment]
> The only issue, and I think it's a local issue, is I did encounter "grey" background when viewing dark mode. [...]

Thank you for the review @zwarm 🙇 !

I've been seeing this since I've first started wrangling UI tests on Android 👀 .

It would be really great to understand what's the actual cause of it and why it's appearing in (all?) apps during UI testing by default. If you have some useful links to read more about it please share 🙏 , to me it's one of those things that's not easy to Google 😥.

I found this method in `JPScreenshotTests`, I wonder if it's for fixing the same problem or something different 🤔

```java
// In some cases there's a gray overlay on view pager screens when taking screenshots
// this function swipes left and then right as a workaround to clear it
// resourceID should be the ID of the viewPager
private void swipeToAvoidGrayOverlay(int resourceID) {
    // Workaround to avoid gray overlay
    swipeLeftOnViewPager(resourceID);
    idleFor(1000);
    swipeRightOnViewPager(resourceID);
    idleFor(1000);
}
```

I'll try it out in the meantime.

File: WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java (hunk 1 above)
Comment (ovitrif) [reply WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java]: I agree with you, ID's are generally more stable and less likely to change in isolation, that is without changing the reference to them in the tests code.

The actual reason for changing to text is because we're not seeing the quick actions buttons by default anymore, but we do have the Posts item and more in the site menu, which as we've discussed it's presenting the menu items in a `RecyclerView`.

Could be that quick actions is behind a feature flag, I don't know for sure to be honest. This was based on my observation when exploring the app during the failure either with a breakpoint or just after the tests were failing.

Update: I've asked other developers and confirmed it's behind a feature flag / and part of an experiment that the user in tests is assigned to: `my_site_default_tab_experiment`.
See internal slack thread: p1657100190631169-slack-C011BKNU1V5

File: WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java (hunk 2 above)
Comment (ovitrif) [reply WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java]: > so it makes sense to me to update it in this PR 👍

Coming back to this, my plan at the moment is to open a PR for the Jetpack App UI tests fixes that will target the branch of this one.

If that's ok I'll be addressing this comment with a change in that PR 👍

File: WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/MySitesPage.java (hunk 3 above)
Comment (ovitrif) [reply WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/MySitesPage.java]: Thank you 🎉 💯 🚀

File: WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java (hunk 4 above)
Comment (ovitrif) [reply WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java]: > I am seeing this same issue if I uncomment the editBlogPost() test. :(

It's an interesting one that will need further investigation. Could be either something off in the app code (which I'd assume is more unlikely) or something off coming from the request mocks / some specifics in the request mocks that's making the app refresh the list again and again.

This will be for a bit later, presumably after the Jetpack screenshots UI tests PR is open.
Main reason for planning it this way is that it does seem to be a bigger issue that's well defined, we can dedicate all focus only on that problem while at it 👍 .

File: WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java (hunk 1 above)
Comment (zwarm) [reply WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java]: 👍 - Thank you for the explanation. You are 100% correct, even the dashboard itself is behind a feature flag and may not show at all in future WordPress versions. That could render the navigate by "tab" invalid. 🤔 That's the future though. I think if we add the screenshot tests to our connected test list, we'll catch those instances as the app evolves. All good with this one then.

File: WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java (hunk 2 above)
Comment (zwarm) [reply WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java]: >  If that's ok I'll be addressing this comment with a change in that PR 👍

Okay with me 👍

**Comment by zwarm** [comment]
@ovitrif - I think this one is ready to merge. Shall I go ahead or do you want to take care of it?

File: WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java (hunk 2 above)
Comment (ovitrif) [reply WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java]: Done in 9d0d7157cbad939d59b559963b697b3c36cdcfca from #16877 that is targeting this branch 👍 .

**Comment by ovitrif** [comment]
> @ovitrif - I think this one is ready to merge. Shall I go ahead or do you want to take care of it?

@zwarm Let's first review and get #16877 merged into this one, since it's changing a few things that were needed to get both tests working, plus it's improving bits from here ;), if you're ok with this plan 🙏 !

**Comment by ovitrif** [comment]
> I'll try it out in the meantime.

Still have to do that (trying out `swipeToAvoidGrayOverlay` to see if it fixes the reported issue with the gray-ish coloring on dark/white mode), but I can only do it [update] next week given I'm AFK the next 2 days.
