### PR TITLE
[Reader][0 blogs/0 tags] Fix Subscription feed infinite loading and fetch when tapping filters

### LINKED ISSUE #20009: [Reader IA][Bug][0 blogs/tags] Subscription feed tries refreshing when tapping filter pill
### Expected behavior
When tapping a filter pill (either blogs or tags) the Subscription post feed should not try to refresh, unless the fetch for the filters updates the subscribed blog list and it now has at least 1 blog.

### Actual behavior
When tapping a filter pill (either blogs or tags) the Subscription post feed always tries to refresh.

### Steps to reproduce the behavior
Make sure to unsubscribe from all tags and blogs.

1. Install and log into Jetpack on a `feature/reader-ia` branch build
2. Go to reader
3. Go to the Subscriptions feed
4. Tap either the "0 blogs" or "0 tags" filter pill
5. **Verify** the feed tries to refresh (show the refresh indicator)

### LINKED ISSUE #20010: [Reader IA][Bug][0 tags/blogs] Infinite loading indicator on Subscription feed after subscribing to tags
### Expected behavior
After going to "Suggested tags" flow inside the Tag filter bottom and returning to the Subscriptions feed it should still show the empty state (as there are still 0 blogs being followed) and not show a loading indicator indefinitely.

### Actual behavior
After going to "Suggested tags" flow inside the Tag filter bottom and returning to the Subscriptions feed it shows a loading indicator indefinitely on top of a blank feed.

https://github.com/wordpress-mobile/WordPress-Android/assets/5091503/5e88ec3f-7199-49e1-a5e8-eafcadecf4c0

### Steps to reproduce the behavior
Make sure to unsubscribe from all tags and blogs.

1. Install and log into Jetpack on a `feature/reader-ia` branch build
2. Go to reader
3. Go to the Subscriptions feed
4. Tap "0 tags" filter pill
5. Tap "Suggested tags"
6. Choose zero or more tags and tap "Done"/back
7. **Verify** it goes back to Subscription Feed in an infinite loading state

### PR DESCRIPTION
**Pull request by thomashorta**
Fixes #20009 
Fixes #20010 

The biggest change in this PR is fixing the logic inside `ReaderUpdateLogic` to avoid unnecessary DB writes which were happening always, even when the server tag list was the same as the local tag list, which in turn made the `FollowTagsChanged` stop being triggered every single time a fetch was done.

Fixing that issue made the `FollowTagsChanged` event only be triggered when we, in fact, had changes in the local tag DB, which solved the issues referenced above BUT broke a lot of other things, since much of the existing code listening to that event was relying on `FollowTagsChanged` being triggered at the end of all tag fetching tasks.

To solve that I renamed the `FollowTagsChanged` to `FollowTagsFetched` and made it trigger in the same situation as it was before (regardless of changes being made to the local DB), added a new field `didChange` to propagate the information if a change was done locally or not, and updated the logic in `ReaderPostListFragment` event listener that caused the 2 bugs above to happen, by guarding with the specific conditions in which we really want fetching to happen

-----

## To Test:

Before running each test scenarios below make sure you have 0 blogs and 0 tags followed.

### Infinite loading after subscribing to tags
1. Install and log into Jetpack on a `feature/reader-ia` branch build
2. Go to reader
3. Go to the Subscriptions feed
4. Tap "0 tags" filter pill
5. Tap "Suggested tags"
6. Choose zero or more tags and tap "Done"/back
7. **Verify** it goes back to Subscription Feed and the page has no infinite loading indicator

### Tapping the blog/tag filter pills causes the empty list to refresh
1. Install and log into Jetpack on a `feature/reader-ia` branch build
2. Go to reader
3. Go to the Subscriptions feed
4. Tap either the "0 blogs" or "0 tags" filter pill
5. **Verify** the feed does not try to refresh since there are no subscribed blogs

-----

## Regression Notes

1. Potential unintended areas of impact
    - Normal scenarios of reader (with tags/blogs subscriptions)

2. What I did to test those areas of impact (or what existing automated tests I relied on)
    - Manual testing

3. What automated tests I added (or what prevented me from doing so)
    - Updated existing unit tests

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist:

- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderEvents.java [hunk 1]
```diff
@@ -26,16 +26,27 @@ private ReaderEvents() {
         throw new AssertionError();
     }
 
-    public static class FollowedTagsChanged {
+    public static class FollowedTagsFetched {
```
Comment (RenanLukas) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderEvents.java:29]: 💯

File: WordPress/src/main/java/org/wordpress/android/ui/reader/services/update/ReaderUpdateLogic.java [hunk 2]
```diff
@@ -176,11 +177,10 @@ public void run() {
...
+                localTopics.addAll(ReaderTagTable.getDiscoverPostCardsTags());
 
-                if (
-                        !localTopics.isSameList(serverTopics)
-                        || displayNameUpdateWasNeeded
-                ) {
+                boolean didChangeFollowedTags = false;
+                if (!localTopics.isSameList(serverTopics)) {
                     AppLog.d(AppLog.T.READER, "reader service > followed topics changed "
                                               + "updatedDisplayNames [" + displayNameUpdateWasNeeded + "]");
```
Comment (RenanLukas) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/services/update/ReaderUpdateLogic.java]: Since the variable `displayNameUpdateWasNeeded` was removed from the `if` and is now only used in this `AppLog`, would it make sense to remove it? If so, perhaps we can even remove the `displayNameUpdateWasNeeded` method.

**Review by RenanLukas — APPROVED** [review]
Thanks for the PR, @thomashorta . It's working as expected.
I'm approving since code LGTM but left a suggestion.

**Review by daniloercoli — APPROVED** [review]
Looks good to me. However, I noticed that we're retrieving the tags list and triggering the FollowTagsChanged event too many times, even when it seems unnecessary. The event is fired when tapping on the Tags pills to open the bottom sheet and also when tapping on the edit button in the bottom sheet. I'm wondering if we really need to sync tags with this frequency.

File: WordPress/src/main/java/org/wordpress/android/ui/reader/services/update/ReaderUpdateLogic.java (hunk 2 above)
Comment (thomashorta) [reply WordPress/src/main/java/org/wordpress/android/ui/reader/services/update/ReaderUpdateLogic.java]: Good point, I thought I had removed it but I think I forgot! Thanks for noticing that!

**Comment by thomashorta** [comment]
> Looks good to me. However, I noticed that we're retrieving the tags list and triggering the FollowTagsChanged event too many times, even when it seems unnecessary. The event is fired when tapping on the Tags pills to open the bottom sheet and also when tapping on the edit button in the bottom sheet. I'm wondering if we really need to sync tags with this frequency.

Do you mean the logic to fetch the tags, which ends up triggering now the `FollowTagsFetched`? If that's the case I kind of agree but as said in the PR comments and some of the commit messages unfortunately there are a lot of places currently starting the "fetching" tasks and waiting for that "fetch ended" event, so a proper rearchitecture would be great to check if we indeed need all that fetching.

For the examples you mentioned ("tapping the tag pills" and "edit button") I think those are actually very good examples that makes sense to keep fetching and syncing the tags, since they are the main entry points for screens that display the subscribed tags to the user, so in my opinion those scenarios need to keep fetching data from the backend.

But like any other app/feature that has caching, the "fetch policy" is hard to get right and there's always a trade-off. Ex: using "cache-first" will return fast but might show stale data, while "network-only" might be slow but will guarantee we're synced with the backend.

**Comment by daniloercoli** [comment]
> For the examples you mentioned ("tapping the tag pills" and "edit button") I think those are actually very good examples that makes sense to keep fetching and syncing the tags, since they are the main entry points for screens that display the subscribed tags to the user, so in my opinion those scenarios need to keep fetching data from the backend.

I don't completely agree with the part above. It's ok to fetch from the server when tapping `Edit`, since the intent is to modify the list. If you regularly use the Reader, and switch between tags during a single session, there's no need to sync every time you tap to open the bottom sheet. In my case, and i think on most regular users, a single sync at app startup is more than sufficient, as I don't add/remove tags daily but instead often check the content of my preferred tags.

**Comment by thomashorta** [comment]
Regarding CodeCov message above (https://github.com/wordpress-mobile/WordPress-Android/pull/20216#issuecomment-1954817827), I don't think there's any action to be done, since none of those files were covered by unit tests, and adding those tests in this fix is out of scope.

**Comment by thomashorta** [comment]
> If you regularly use the Reader, and switch between tags during a single session, there's no need to sync every time you tap to open the bottom sheet. In my case, and I think on most regular users, a single sync at app startup is more than sufficient, as I don't add/remove tags daily but instead often check the content of my preferred tags.

That's a good point! There's definitely room for improvement there in terms of fetching that should be investigated when we decide to refactor the business logic and architecture behind the Reader.
