### PR TITLE
Check for upload changes to determine need to update Post content

### LINKED ISSUE #6654: Async media: broken reattachment identification
### Expected behavior
You should be able to insert a video or image in a Post and exit the editor or come back into it as many times as you want, and the Post will end up being updated remotely (as long as connectivity exists) each time.

### Actual behavior
When uploading a video, exiting, re-attaching, then waiting to finish:
once it finishes, exiting the editor shows a [video] tag in the Post list, and entering the editor again shows the failed/retry overlay on the video.

For images, it seems to be working but when you come back again and tap on the image (expecting to see the image settings screen), it RETRIES THE UPLOAD, even when the failed/retry overlay wasn’t showing there.

### Steps to reproduce the behavior

FOR VIDEO:
1. start a new draft
2. insert a video
3. while the video is uploading, exit the editor
4. enter the editor again
5. confirm the progress gets re-attached
6. wait until the video is finished uploading
7. tap on the video, confirm the player is executed
8. exit the editor
9. enter the editor for that post again
10. observe it's shown with the failed/retry overlay

FOR IMAGES:
1. start a new draft
2. insert an image
3. while the image is uploading, exit the editor
4. enter the editor again
5. confirm the progress gets re-attached
6. wait until the image is finished uploading
7. tap on the image, confirm the image settings screen is displayed
8. exit the editor
9. enter the editor for that post again
10. tap on the image, observe the image settings screen is not displayed this time, but rather the image starts to upload again, as if it was a failed image.

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #6654 

The reason it was failing as described in #6654 is because we look for changes only by checking whether the Aztec editor has a Change History (change introduced in https://github.com/wordpress-mobile/WordPress-Android/pull/6610). Given the completed uploads actually do change the URL but they do so in the background, thus not affecting Aztec’s Change History, we think there’s nothing new and thus we don’t save the latest Post content (with the updated remote URLS for media that have been uploaded).

It is not trivial to understand which changes need to be saved, given a dumb string comparison can return different strings for semantically identical HTML content (for instance, the order in which a div class appears makes the string different but the HTML piece is no different from each other).

So, this PR tackles this by relying on what we _do_ know: when the Editor is opened, we know which media items in the Post content are marked as being uploaded. Same thing when the Editor is closed: when the user exits the editor, and we have any change in uploads for this Post (i.e. the existing uploads when we opened the Editor have now completed when we try to exit the Editor), then we need to save the Post content as a change in the media items URL has happened.

To test:

FOR IMAGES:
1. start a new draft
2. insert an image
3. while the image is uploading, exit the editor
4. enter the editor again
5. confirm the progress gets re-attached
6. wait until the image is finished uploading
7. tap on the image, confirm the image settings screen is displayed
8. exit the editor
9. enter the editor for that post again
10. tap on the image, observe the image settings screen is displayed

FOR VIDEOS:
1. start a new draft
2. insert a video
3. while the video is uploading, exit the editor
4. enter the editor again
5. confirm the progress gets re-attached
6. wait until the video is finished uploading
7. tap on the video, confirm the player is executed
8. exit the editor
9. enter the editor for that post again
10. observe it's there and can be played - also observe the URL to it is the remote one.

cc @nbradbury

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java [hunk 1]
```diff
@@ -1775,19 +1780,23 @@ public boolean updatePostContentNewEditor(boolean isAutoSave, String title, Stri
...
         boolean titleChanged = PostUtils.updatePostTitleIfDifferent(mPost, title);
-        boolean contentChanged;
-        if (mEditorFragment instanceof AztecEditorFragment) {
-            contentChanged = ((AztecEditorFragment)mEditorFragment).hasHistory();
-            if (contentChanged) {
-                mPost.setContent(content);
-            } else if (!((AztecEditorFragment)mEditorFragment).isHistoryEnabled()){
-                // if history is not enabled, then we can only confirm whether there's been a content change
-                // by comparing content
+        boolean contentChanged = compareCurrentMediaMarkedUploadingToOriginal(content);
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: It feels like this whole block could be simplified to:
```
boolean contentChanged;
if (compareCurrentMediaMarkedUploadingToOriginal(content)) {
    contentChanged = true;
} else if (mEditorFragment instanceof AztecEditorFragment 
        && ((AztecEditorFragment) mEditorFragment).isHistoryEnabled()) {
    contentChanged = ((AztecEditorFragment) mEditorFragment).hasHistory();
} else {
    contentChanged = mPost.getContent().compareTo(content) != 0;
}
if (contentChanged) {
    mPost.setContent(content);
}
```

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java [hunk 2]
```diff
@@ -1798,6 +1807,18 @@ public boolean updatePostContentNewEditor(boolean isAutoSave, String title, Stri
...
+    /*
+      * for as long as the user is in the Editor, we check whether there are any differences in media items
+      * being uploaded since they opened the Editor for this Post. If some items have finished, the current list
+      * won't be equal and thus we'll know we need to save the Post content as it's changed, given the local
+      * URLs will have been replaced with the remote ones.
+     */
+    private boolean compareCurrentMediaMarkedUploadingToOriginal(String newContent) {
+        List<String> currentUploadingMedia = AztecEditorFragment.getMediaMarkedUploadingInPostContent(this, newContent);
+        Collections.sort(currentUploadingMedia);
+        return !mMediaMarkedUploadingOnStartIds.equals(currentUploadingMedia);
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: Since `mMediaMarkedUploadingOnStartIds` is left unchanged here, won't this method return true every time it's called if uploaded media changed at any time?

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java (hunk 1 above)
Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: Excellent - just tested it in all 3 cases (images, video, and just user changes through the editor). Replaced the code with your block in ccf116b

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java (hunk 2 above)
Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: As long as changes happen in between the user opened the Editor (which is when `mMediaMarkedUploadingOnStartIds` is populated) and exiting the Editor, that's exactly the window we want to cover, so yes it'd be fine. Unless I'm not seeing some side effect of it that could potentially be harmful?

Comment (nbradbury) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: If a media item finished uploading between the start of the activity and the first time `updatePostContentNewEditor` is called, then every time it's called afterwards it will also return true. Looking at the flow from `savePostAsync` > `updatePostObject` > `updatePostContentNewEditor`, won't this mean that the post could be updated (and uploaded) unnecessarily?

Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: ok good catch, addressed in 9015bff

**Comment by nbradbury** [comment]
:shipit:
