### PR TITLE
Check change history size to test for content changes in Post

### LINKED ISSUE #6599: Local changes on posts even if not modifying them
### Expected behavior
When opening an existing Post in the editor, and just exiting the editor without modifying anything, should just leave things as they were.

### Actual behavior
For some posts, opening an existing Post in the editor, then just exiting the editor (both Aztec and Visual) triggers the  `Post saved on device` snackbar and marks it `Local changes` in the Posts list.

### Steps to reproduce the behavior
1. pick a Post that has images and videos in it, and has been written on the web admin (wp-admin or Calypso)
2. open it in the editor
3. exit the editor
4. observe the snackbar appears, and the post is marked "Local changes" in the Posts list.

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #6599 partially (on Aztec only).

In investigating this, we realized the problem was that both Aztec and the Visual editors do change the content even if the user doesn't do anything with it, as follows. 

#### Aztec

Using the Aztec editor to open a post that contains 1 media item (at least) and has been written using wp-admin or Calypso, this is how the original Post content looks like:

**Original content**
```
some text
<img src="https://testmzorz2.files.wordpress.com/2017/08/img_20170826_160114_12137624278.jpg?w=300" alt="" width="300" height="169" class="alignnone size-medium wp-image-1957" />
```

When getting this content into Aztec and then exiting the editor, re-creating the html back using `AztecText.toHtml()`, the produced content looks like this:

**Content as rendered by the editor**
```
some text
<img class="alignnone size-medium wp-image-1957" src="https://testmzorz2.files.wordpress.com/2017/08/img_20170826_160114_12137624278.jpg?w=300" alt="" width="300" height="169">
```

Look at the two `img` tags, I'll put them together here:
```
<img class="alignnone size-medium wp-image-1957" src="https://testmzorz2.files.wordpress.com/2017/08/img_20170826_160114_12137624278.jpg?w=300" alt="" width="300" height="169">
<img src="https://testmzorz2.files.wordpress.com/2017/08/img_20170826_160114_12137624278.jpg?w=300" alt="" width="300" height="169" class="alignnone size-medium wp-image-1957" />
```
So two things are different:
1) the placement of the `class` property within the string is different (`wp-admin` places it in the end of the tag, while Aztec places it at the beginning)
2) Aztec is not closing the self-containing tag with `/>`. (BTW don't know whether this is a bug or not, as the Visual Editor behaves the same way as we'll see).

#### Visual Editor

**Original content**
```
some text
<img src="https://testmzorz2.files.wordpress.com/2017/08/wp-image-511380693.jpg?w=225" alt="" width="225" height="300" class="alignnone size-medium wp-image-1941" />
```

**Content rendered by the editor**
```
some text
<img src="https://testmzorz2.files.wordpress.com/2017/08/wp-image-511380693.jpg?w=225" alt="" width="225" height="300" class="alignnone size-medium wp-image-1941">
```

=> Here, the only difference is the wrong closing of the ``).

The way we were using to test if something changed is by means of a [string comparison between the original and new content](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L1763). Because the string actually changes, we [mark the Post as `Locally changed`](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L1766).

#### The proposed solution on Aztec

Now, trying to compare whether two HTML expressions are semantically identical is a difficult thing to achieve, and probably fairly off the scope of this issue in particular. So what this PR does, is it takes advantage of the change history capability placed in Aztec, which keeps track of a change history and makes it possible to undo/redo changes. If the user does anything with the content, it will be tracked in its history tracker. So in order to learn if the content has been edited at all, all we need to do is checking if the change history size is any different than zero.

#### The proposed solution on the Visual Editor
None that I can think of without incurring in a significant effort. I think we could leave it as is, as eventually it will be replaced by Aztec at some point.

To test:
1. on the web admin (wp-admin or Calypso), write a draft that has images and/or videos in it
2. now open the Android app and check for it in the Posts list
3. open it in the editor (Aztec only)
4. exit the editor
5. observe the Post remains unchanged

cc @nbradbury @aforcier

### CODE REVIEW

File: libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java [hunk 1]
```diff
@@ -312,6 +312,10 @@ public void onPrepareOptionsMenu(Menu menu) {
         super.onPrepareOptionsMenu(menu);
     }
 
+    public boolean hasAnyChanges() {
+        return (content.history.getHistoryEnabled() && !content.history.getHistoryList().isEmpty());
```
Comment (nbradbury) [inline libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java]: I'm fairly new to Aztec so I have to ask: when would history *not* be enabled?

Comment (mzorz) [reply libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java]: Good question! I think never in WPandroid, but given it is a possibility (that Aztec allows to enable/disable the feature) I thought it would be better to future-proof it and make the check anyway

Comment (nbradbury) [reply libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java]: In that case, maybe this method should be renamed to `hasHistory()`?

Comment (mzorz) [reply libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java]: sounds good 👍 , changed in 8035d97

**Comment by nbradbury** [comment]
Good call on only tackling this for Aztec, and for relying on the history rather than string comparison to determine if anything has changed. 💯 

I wonder, though, why this is branched from `release/8.2` rather than `develop`? It makes me nervous to fix non-critical issues in release branches, especially ones related to editor content.

**Comment by mzorz** [comment]
> it makes me nervous to fix non-critical issues in release branches, especially ones related to editor content.
:D fair enough, changing the base branch to `develop` 👍

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java [hunk 2]
```diff
@@ -1734,7 +1734,14 @@ public boolean updatePostContentNewEditor(boolean isAutoSave, String title, Stri
...
 
         boolean titleChanged = PostUtils.updatePostTitleIfDifferent(mPost, title);
-        boolean contentChanged = PostUtils.updatePostContentIfDifferent(mPost, content);
+        boolean contentChanged = true;
+        if (mEditorFragment instanceof AztecEditorFragment) {
+            contentChanged = ((AztecEditorFragment)mEditorFragment).hasHistory();
+        }
+
+        if (contentChanged) {
+            contentChanged = PostUtils.updatePostContentIfDifferent(mPost, content);
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: I think we can skip the call to [updatePostContentIfDifferent()](https://github.com/wordpress-mobile/WordPress-Android/blob/issue/6599-local-changes-on-web-written-posts/WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java#L322) since all that does is update the passed post model if the content is changed, and we already know the content is changed. Seems like we could just use `mPost.setContent(content)` if we know the content has changed and skip the potentially expensive string comparison.

Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: "strictly" addressed in 602a29c, but then realized that it wouldn't be future-proof anymore (i.e. if history could be disabled, then it would never save it). So added these checks in 6fc5a69. What do you think?

Comment (nbradbury) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: Yeah, that's why I was asking about history - if it was disabled, the changes would never be saved. Adding that check probably isn't necessary but I feel safer having it there :)

**Comment by nbradbury** [comment]
Looks good! :shipit:
