### PR TITLE
Invalid XML-RPC fault responses crash the app

### LINKED ISSUE #3841: Invalid XML-RPC fault responses crash the app
Title has it. 
Just send an invalid XML-RPC response to the app and make it crashing :(

### PR DESCRIPTION
**Pull request by daniloercoli**
Fixes #3841

To test:
Try to pass to the app an invalid XMLRPC Fault response, and it should not crash.

### CODE REVIEW

**Comment by daniloercoli** [comment]
Please, merge this in `5.1.1`.

**Comment by daniloercoli** [comment]
> int faultCode = MapUtils.getMapInt(map, TAG_FAULT_CODE);

Which value should we return in case the key doesn't exist, or is not of the correct type? We can't return any valid int value in those cases, since the server could return any valid int as error_code.

**Comment by nbradbury** [comment]
> Which value should we return in case the key doesn't exist, or is not of the correct type?

Understood, ignore my suggestion!

File: WordPress/src/main/java/org/xmlrpc/android/XMLRPCClient.java [hunk 1]
```diff
@@ -319,8 +319,17 @@ public static Object parseXMLRPCResponse(InputStream is, HttpEntity entity)
...
+                throw new XMLRPCException("Bad XMLRPC Fault response received - neither <faultCode> nor <faultString>");
+            }
+            String faultString = String.valueOf(map.get(TAG_FAULT_STRING));
+            int faultCode;
+            try {
+                faultCode = (int) map.get(TAG_FAULT_CODE);
+            } catch (NumberFormatException | ClassCastException e) {
+                throw new XMLRPCException("Bad XMLRPC Fault response received - <faultCode> value is not an integer");
+            }
             consumeHttpEntity(entity);
```
Comment (nbradbury) [inline WordPress/src/main/java/org/xmlrpc/android/XMLRPCClient.java]: If an exception is thrown above, then `consumeHttpEntity` won't be called here.

Comment (daniloercoli) [inline WordPress/src/main/java/org/xmlrpc/android/XMLRPCClient.java]: Right. I changed the code by moving `consumeHttpEntity` in the correct place. It was not even necessary to consume the entity in this case, since the whole parsing fails and the connection is closed.
XML-RPC response is just one, we're not using XML-RPC multicalls in the app.

**Comment by nbradbury** [comment]
Looks good! :shipit:

**Comment by nbradbury** [comment]
Cherry picked into `hotfix/5.1.1`.
