### PR TITLE
Post List: Fix excessive media requests

### LINKED ISSUE #20905: Excessive Media Requests Delay Critical Post Operations
### Expected behavior
- The app only generates one request to the media endpoint for each featured image of the posts to be fetched.
- Post management operations aren't locked due to fetching featured images of posts.

### Actual behavior
When opening the app for the first time and navigating a site with a long list of posts with featured images, the app generates significantly more requests to the media endpoint than the number of posts. For instance, 40 posts with featured images resulted in 177 requests. This issue is exacerbated by slow network connections, leading to even more requests.

During this period, critical post operations like saving, publishing, and deleting are locked until all the featured image requests are completed. This results in a situation where post management is blocked for several minutes, severely impacting the user experience.

### Steps to reproduce the behavior

**Preparation:** 
- Create multiple posts (20 or more) and attach a featured image. This can be done quickly by using the [WPCOM console](https://developer.wordpress.com/docs/api/console/) and the endpoint rest/v1.1/sites/${siteId}/posts/new.

#### Extra requests to the media endpoint
1. On the device/emulator, clear storage of the app, or delete and reinstall the app.
2. Open the app and navigate to the site.
3. Connect the device/emulator to the Charles proxy.
4. Open the app and go to the Post screen.
5. Observe all extra requests to the media endpoint in the Charles proxy.

#### Post manage operations locked
1. On the device/emulator, clear storage of the app, or delete and reinstall the app.
2. Open the app and navigate to the site.
3. Connect the device/emulator to the Charles proxy.
4. Slow down the network connection. This can be achieved by enabling throttling in the Charles proxy.
5. Open the app and go to the Post screen.
6. Edit a post and save it.
7. Observe that the saving operation takes a significant delay.

### PR DESCRIPTION
**Pull request by zwarm**
Fixes #20905 

This PR fixes the excessive calls to fetch media when loading the post list by introducing and managing ongoing fetch requests in `PostListFeaturedImageTracker`. These changes aim to prevent redundant fetch requests.

Changes include
- In `PostListFeaturedImageTracker` Introduced `ongoingRequests`, to keep track of ongoing image fetch requests and prevent redundant requests.
- Updated the `getFeaturedImageUrl()` to check and update the `ongoingRequests` set appropriately.
- Updated `PostListEventListener.onMediaChanged()` to invoke `invalidateFeaturedMedia` on both success and error. This ensures that the `featuredImageMap` and `ongoingRequests` are properly updated whether the media fetch was successful or not.
-----

## To Test:
**Steps to reproduce the behavior**
**Preparation:**
1. Create multiple posts (20 or more) and attach a featured image. This can be done quickly by using the [WPCOM console](https://developer.wordpress.com/docs/api/console/) and the endpoint rest/v1.1/sites/${siteId}/posts/new.

**Existing: Extra requests to the media endpoint for the same featuredImageId**
1. Using "trunk" branch
2. On the device/emulator, **clear storage of the app**, or delete and reinstall the app.
3. Open the app and navigate to the site (the same site that you created the 20+ posts with featured images)
4. Connect the device/emulator to the Charles proxy (or see below for alternative)
5. Open the app and go to the Post List screen.
6. Observe all extra requests to the media endpoint in the Charles proxy.

**Fix: Extra requests to the media endpoint are eliminated**
1. Using the app from this PR
2. On the device/emulator, **clear storage of the app**, or delete and reinstall the app.
3. Open the app and navigate to the site (the same site that you created the 20+ posts with featured images)
4. Connect the device/emulator to the Charles proxy (or see below for alternative)
5. Open the app and go to the Post list screen.
6. ✅ Verify all the extra requests for the same media id have been eliminated.

<details>
<summary>Alternative to using Charles</summary>

- Checkout the branch you will test (trunk for pre-existing test or this branch for the fix test
- Checkout FluxC (trunk)
- Use local FluxC to build WP
- Update `GSONRequest.parseNetworkRequest` to log info

```
@Override
    protected Response<T> parseNetworkResponse(NetworkResponse response) {
        logGsonRequest();
        try {
            String json = new String(response.data, HttpHeaderParser.parseCharset(response.headers));
            T res;
            if (mClass == null) {
                res = mGson.fromJson(json, mType);
            } else {
                res = mGson.fromJson(json, mClass);
            }
            return Response.success(res, createCacheEntry(response));
        } catch (UnsupportedEncodingException | JsonSyntaxException e) {
            logRequestPath();
            return Response.error(new ParseError(e));
        }
    }

    private void logGsonRequest() {
        String path = getPath();
        String url = getUrl();

        if (path != null && (path.contains("media"))) {
            if (url != null) {
                Log.i("GsonRequest", "***=> Request URL is: " + url);
            }
        }
    }

```
</details>

-----

## Regression Notes

1. Potential unintended areas of impact
Multiple media requests continue to be excessive

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual and unit testing

3. What automated tests I added (or what prevented me from doing so)
Existing tests

-----

## PR Submission Checklist:
- [X] I have completed the Regression Notes.
- [X] I have considered adding accessibility improvements for my changes.
- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFeaturedImageTracker.kt [hunk 1]
```diff
@@ -47,6 +66,9 @@ class PostListFeaturedImageTracker(private val dispatcher: Dispatcher, private v
     }
 
     fun invalidateFeaturedMedia(featuredImageIds: List<Long>) {
-        featuredImageIds.forEach { featuredImageMap.remove(it) }
+        featuredImageIds.forEach {
+            featuredImageMap.remove(it)
+            ongoingRequests.remove(it)
+        }
```
Comment (fluiddot) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFeaturedImageTracker.kt:72]: Will this be called when the featured image request is completed? I mention this because I haven't found any other place where the ongoing request is removed.

**Review by fluiddot — APPROVED** [review]
I followed the testing instructions and confirmed that only one request is made per featured image. Thanks @zwarm for addressing this issue 🙇 !

I've checked the code and looks good to me, however, I'd defer the approval to an Android developer.

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFeaturedImageTracker.kt (hunk 1 above)
Comment (AjeshRPai) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFeaturedImageTracker.kt:72]: Hey @fluiddot 
The places where this funcation gets called is `PostListEventListener` → `featuredMediaChanged`. 
The `featuredMediaChanged` is called when the media is changed or uploaded. Correct me if I am wrong. @zwarm

**Review by AjeshRPai — APPROVED** [review]
@zwarm 

The changes looks good to me. Feel free to merge 👍🏼

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFeaturedImageTracker.kt (hunk 1 above)
Comment (zwarm) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFeaturedImageTracker.kt:72]: Thanks for the question, which @AjeshRPai answered before me down below https://github.com/wordpress-mobile/WordPress-Android/pull/20939#discussion_r1630880715

Comment (zwarm) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFeaturedImageTracker.kt:72]: > The places where this funcation gets called is PostListEventListener → featuredMediaChanged.
The featuredMediaChanged is called when the media is changed or uploaded. Correct me if I am wrong.

This is correct, previously only success calls were removed from the featureImageMap and in the updated version, both success and errors are removed. We need to make sure we don't have requests hanging around when they shouldn't be.
