### PR TITLE
Async error gathering

### LINKED ISSUE #6835: Async media: an isolated upload failure appears to abort other uploads
This one comes from https://github.com/wordpress-mobile/WordPress-Android/pull/6713#issuecomment-341569407

### Expected behavior
When uploading a Post with several media items in it, if anything fails it should still try to upload the rest of the media items and wait for all uploads to end (either successfully or with error) to inform the user about a defintive error (i.e. snackbar, and post list reflecting this).

The error notification should show / update the state as items fail, and the progress notification should continue to show what's going on.

### Actual behavior
An error on any first item will show the error notification and snackbar and reflect in the Posts list as if no items were uploaded (but in reality items are still being uploaded in the background).

### TEST CASE H: multiple media upload & selective error & recover, outside the Editor (fully async)
For this one you’ll need to go through Charles proxy as I want to intentionally abort specific uploads.
1. go to the Posts list and start a new draft
2. open the media picker to include several media items
3. see the foreground progress notification starts and remains there for as long as it takes for the media item to upload. If you drag the drawer down, you should see the Notification shows title “Uploading…” and subtext “x of x media files remaining”. (with x being the number of items you included in the Post)
4. exit the editor.
5. you should see the progress notification there, and now it reads “1 post, x of x media files remaining”.
6. before the upload finishes, cancel one of the uploads. You can do so by setting a breakpoint in Charles for the endpoint `https://public-api.wordpress.com/rest/v1.1/sites/<site_id>/media/new/`
7. an error notification is shown for all items, the foreground progress notification is gone, and a snackbar appears with the same error message.

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #6835  by providing a way to update the error notification as errors occur, but not stop the progress notification (that is, letting all other uploads still happen and inform of their progresses while there are things being uploaded still).

This PR comprises the following changes:
- bb8a7444a324f16438672fa78919bbed160b2c87 this prevents any error from showing up in the Posts list if such a Post still has in-progress items (otherwise, if a Post with 5 items fails to upload the first one, it would show as failed while in reality the other items were still uploading).
- 483785aa554f29ef7b8e198dfb26b095e8597547 does a final processing of posts only when the queue seems to be empty (it was being done right after receiving a media error event from FluxC, which made it unnecessary as some other uploads might be still in progress as well)
- a7351ec88b146a59b724c3fc0169f3066a8cc2a7 repurposes the `updateNotificationErrorForPost()` method in `UploadNotifier` to allow for media failed count to be overriden. This is particularly handy to keep the user informed about what's going on with a specific Post for which some items might have failed but some other items are still in progress.

For example, this is how the notifications change before the following screenshot, which captures moment number 3 below:
1. 4 items have been included in a Post, and the user exited the editor. The progress notification shows "1 post, 4 of 4 media files remaining"
2. (not seen in the picture), 1 media file has been uploaded successfully, so the progress notification changes to "1 post, 3 of 4 media files remaining"
3. 1 media file has been uploaded sucessfully already, but another one failed. The error notification appears, saying "1 post, 1 media file not uploaded (1 successfully uploaded).", and the progress notification will show "1 post, 2 of 4 media files remaining".
screen shot 2017-11-08 at 11 50 32 am

Find some live video captures here below. Not shown in the captures, I purposedly cancel some of the requests on Charles, to trigger errors in different situations.

async_errors

async_errors_retry

async_errors_retry_last

To test:

### TEST CASE H: multiple media upload & selective error & recover, outside the Editor (fully async)
For this one you’ll need to go through Charles proxy as I want to intentionally abort specific uploads.
1. go to the Posts list and start a new draft
2. open the media picker to include several media items
3. see the foreground progress notification starts and remains there for as long as it takes for the media item to upload. If you drag the drawer down, you should see the Notification shows title “Uploading…” and subtext “x of x media files remaining”. (with x being the number of items you included in the Post)
4. exit the editor.
5. you should see the progress notification there, and now it reads “1 post, x of x media files remaining”.
6. before the upload finishes, cancel one of the uploads. You can do so by setting a breakpoint in Charles for the endpoint `https://public-api.wordpress.com/rest/v1.1/sites/<site_id>/media/new/`
7. an error notification is shown for that specific item, and the foreground notiification keeps informing you of other remaining items. Note as well that the sum of items make for the complete items initially in the Post, for example if you inserted 5 items, the foreground notification will read "5 of 5 media files remaining", make one of them fail, you'll have an error notification saying 1 media file could not be uploaded, and the progress notification will read "4 of 5 media files remaining", etc.

cc @nbradbury

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java [hunk 1]
```diff
@@ -637,6 +631,17 @@ private PostModel updateOnePostModelWithCompletedAndFailedUploads(PostModel post
         return updatedPost;
     }
 
+    private boolean mediaBelongsToAPost(MediaModel media) {
+        PostModel postToCancel = mPostStore.getPostByLocalPostId(media.getLocalPostId());
+        if (postToCancel == null) return false;
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java]: This can be simplified to `return (postToCancel != null && mUploadStore.isRegisteredPostModel(postToCancel));`

Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java]: nice! 0d5bdc5

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadNotifier.java [hunk 2]
```diff
@@ -419,7 +420,8 @@ public static long getNotificationIdForMedia(SiteModel site) {
         }
     }
 
-    void updateNotificationErrorForPost(@NonNull PostModel post, @NonNull SiteModel site, String errorMessage) {
+    void updateNotificationErrorForPost(@NonNull PostModel post, @NonNull SiteModel site, String errorMessage,
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadNotifier.java]: Can we add a comment here explaining what `overrideMediaNotUploadedCount` is? I think if we have this explainer, we can drop the `K_DONT_OVERRIDE_MEDIA_COUNT` constant and simply pass `0`.

Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadNotifier.java]: ok, addressed in 284d681, would you check whether the comment seems clear enough please? thx

Comment (nbradbury) [reply WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadNotifier.java]: Looks good, except for the minor typo ("youn" instead of "you").

Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadNotifier.java]: 😁 545b4a1

File: WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java [hunk 3]
```diff
@@ -836,6 +819,43 @@ public void onMediaUploaded(OnMediaUploaded event) {
         }
     }
 
+    private boolean doFinalProcessingOfPosts() {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java]: I think it would be helpful to add a comment stating what the true/false result means.

Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java]: Totally - added in e14878b

**Comment by nbradbury** [comment]
:shipit:
