### PR TITLE
[Analytics] - Tracking the number of blogs

### LINKED ISSUE #3487: Analytics - Tracking user_info_number_of_blogs property
Hey @astralbodies do you remember what we should track in `user_info_number_of_blogs` ?

Is it meaning the number of visible blogs? or the number of total blogs for a user?

Asking this because we're tracking it wrong on sign in, since the `me` endpoint is called asynchronously in the app, resulting in empty visible blogs list.
```
   [0] => Array
                (
                    [_en] => wpandroid_signed_in
                    [_ts] => 1449658481291
                    [_ui] => 29188508a93f4bdb98f990719d3ed414
                    [_ut] => anon
                    [user_info_number_of_blogs] => 0
                    [dotcom_user] => true
                )

            [1] => Array
                (
                    [_en] => _aliasUser
                    [_ts] => 1449658481331
                    [_ul] => daniloercoli
                    [_ut] => wpcom:user_id
                    [user_info_number_of_blogs] => 0
                    [anonId] => 29188508a93f4bdb98f990719d3ed414
                )
```

### PR DESCRIPTION
**Pull request by daniloercoli**
Fix #3487  by tracking all blogs, including hidden ones.

Also fix a couple of issues tracking number of blogs during sign in.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/util/AnalyticsUtils.java [hunk 1]
```diff
@@ -49,7 +49,7 @@ public static void refreshMetadata() {
         boolean isUserConnected = AccountHelper.isSignedIn();
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/util/AnalyticsUtils.java]: This is an aside since it's not tied to the current PR, but can't this routine be simplified to call the one above? Ex:
```
public static void refreshMetadata() {
    String username = AccountHelper.getDefaultAccount().getUserName();
    String email = AccountHelper.getDefaultAccount().getEmail();
    refreshMetadata(username, email);
}
```

**Comment by nbradbury** [comment]
:shipit:
