### PR TITLE
Pages: Fix for a crash when setting a page parent

### LINKED ISSUE #8597: Crash: NPE in Parent Page View Model
New in 11.0

```
Fatal Exception: kotlin.KotlinNullPointerException
       at org.wordpress.android.viewmodel.pages.PageParentViewModel.isNotChild(PageParentViewModel.kt:93)
       at org.wordpress.android.viewmodel.pages.PageParentViewModel.access$isNotChild(PageParentViewModel.kt:25)
       at org.wordpress.android.viewmodel.pages.PageParentViewModel$loadPages$1.doResume(PageParentViewModel.kt:70)
       at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
       at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:149)
       at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:13)
       at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
       at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
       at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1152)
       at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1990)
       at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1938)
       at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
``` 
5bc6aeeff8b88c29631774a4-fabric

### PR DESCRIPTION
**Pull request by 0nko**
Fixes #8597. 

This bug was caused by attempts to change a parent of a local-only page that doesn't have a remote ID yet. 

We now try to use a local page ID. Since for local pages we don't know a required remote page ID for undoing actions (both page status and page parent change), we skip it to prevent a crash.

#### To test:
1. Open Site pages with at least 1 published page
2. Turn on the flight mode
3. Create a local-only page
4. Turn off the flight mode
5. Open the Set parent screen for the local page
6. Change the page parent and tap Save
7. Wait for the page list to update successfully
8. Notice the snackbar doesn't offer the Undo action

### CODE REVIEW

**Comment by 0nko** [comment]
Thanks for the review!

> The page overflow menu was hidden when returning from the editor after creating a local page (i.e. Step 3). I created an issue since it happens on develop as well so it wasn't introduced with these changes.

This was a bug, it should now come back after a few seconds.

> The comment implies the PageStore is to blame for the negative value. Can you explain why that is the behavior? Is that documented anywhere?

This is also on purpose. We couldn't rely on local page IDs because whenever a page list gets updated, the local IDs change. So if you modified some page you wouldn't know which one it was. So we have to use remote IDs. However, new pages don't have one (it's 0), so in order to have them in a map we needed some unique ID. So we used the negative local ID (so we know it's temporary).

> Since a network connection is required to actually save a parent for a page, is it possible to allow the Undo action somehow or is the remote ID not assigned to the local page until after the Undo action would occur?

I added the Undo action back when changing the status to Draft. 

Ready for another pass.

File: WordPress/src/main/java/org/wordpress/android/viewmodel/pages/ActionPerformer.kt [hunk 1]
```diff
@@ -1,25 +1,26 @@
...
 import kotlin.coroutines.experimental.Continuation
 
 class ActionPerformer
 @Inject constructor(private val dispatcher: Dispatcher) {
-    private var continuations: MutableMap<Long, Map<EventType, Continuation<Boolean>>> = mutableMapOf()
+    private var continuations: MutableMap<Pair<Long, EventType>, Continuation<Pair<Boolean, Long>>> = mutableMapOf()
 
     companion object {
-        private const val ACTION_TIMEOUT = 30L * 1000
+        private const val ACTION_TIMEOUT = 10L * 1000
```
Comment (theck13) [inline WordPress/src/main/java/org/wordpress/android/viewmodel/pages/ActionPerformer.kt]: Why was this changed from 30 seconds to 10 seconds?

File: WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt [hunk 2]
```diff
@@ -46,11 +48,12 @@ import java.util.SortedMap
 import javax.inject.Inject
 import javax.inject.Named
 import kotlin.coroutines.experimental.Continuation
-import kotlin.coroutines.experimental.suspendCoroutine
 
 private const val ACTION_DELAY = 100
 private const val SEARCH_DELAY = 200
+private const val SNACKBAR_DELAY = 500
 private const val SEARCH_COLLAPSE_DELAY = 500
+private const val PAGE_UPLOAD_TIMEOUT = 5000L
```
Comment (theck13) [inline WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt]: Is this timeout based on another constant or arbitrary?

File: WordPress/src/main/java/org/wordpress/android/viewmodel/pages/ActionPerformer.kt (hunk 1 above)
Comment (0nko) [reply WordPress/src/main/java/org/wordpress/android/viewmodel/pages/ActionPerformer.kt]: I realized that 30s may seem too long when there's something going on with the network and nothing's happening visually. For a page update, 10s should be enough and if it's not the connection is probably wonky.

File: WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt (hunk 2 above)
Comment (0nko) [reply WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt]: Short answer - gut feeling 😆
