### PR TITLE
Stats - fix class cast exception in comments followers

### LINKED ISSUE #2219: Crash report 3.6: ClassCastException in StatsCommentsFragment
```
java.lang.ClassCastException: com.android.volley.NoConnectionError cannot be cast to org.wordpress.android.ui.stats.models.CommentFollowersModel
       at org.wordpress.android.ui.stats.StatsCommentsFragment.updateUI(StatsCommentsFragment.java:87)
       at org.wordpress.android.ui.stats.StatsAbstractListFragment$3.onReceive(StatsAbstractListFragment.java:412)
       at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
       at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
       at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:5317)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

### PR DESCRIPTION
**Pull request by daniloercoli**
Fix #2219

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/stats/StatsCommentsFragment.java [hunk 1]
```diff
@@ -82,7 +82,7 @@ protected void updateUI() {
             return;
         }
 
-        if (mDatamodels[1] != null) { // check if comment-followers is already here
+        if (mDatamodels[1] != null && !isErrorResponse(1)) { // check if comment-followers is already here
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/StatsCommentsFragment.java]: This ensures that it's not a VolleyError, but there's no guarantee that it's a CommentFollowersModel. It would be safer to explicitly check `(mDatamodels[1] instanceof CommentFollowersModel)`.

Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/StatsCommentsFragment.java]: Each fragment receive a notification and then update the UI when receive a datamodel Obj that it can handle.
https://github.com/wordpress-mobile/WordPress-Android/blob/issue/2219-ClassCastException-StatsCommentsFragment/WordPress/src/main/java/org/wordpress/android/ui/stats/StatsAbstractListFragment.java#L388

Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/StatsCommentsFragment.java]: If it was safe to assume it was a CommentFollowersModel then this exception wouldn't have happened. I still think the safest thing to do here is explicitly check whether it's the expected type.

Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/StatsCommentsFragment.java]: Sorry, I was not clear. The object received is either a CommentFollowersModel or a Error Type.
