### PR TITLE
Fix reader post details crash

### LINKED ISSUE #15070: NullPointerException: Attempt to invoke virtual method 'boolean org.wordpress.android.ui.reader.viewmodels.ReaderPostDe...
**Sentry Url**: https://sentry.io/share/issue/43f418072d9d4e2587273d757d3ffee7/
**User Count**: 154
**Count**: 182
**First Release**: 17.7-rc-2
**First Seen**: 2021-07-08T06:23:06.957000Z
**Last Seen**: 2021-07-26T11:27:11Z
**24 Hours**: 17
**30 Days**: 181

```
NullPointerException: Attempt to invoke virtual method 'boolean org.wordpress.android.ui.reader.viewmodels.ReaderPostDetailViewModel$UiState.getErrorVisible()' on a null object reference
     at org.wordpress.android.ui.reader.ReaderPostDetailFragment$initViewModel$1.onChanged(ReaderPostDetailFragment.kt:442)
     at org.wordpress.android.ui.reader.ReaderPostDetailFragment$initViewModel$1.onChanged(ReaderPostDetailFragment.kt:132)
     at org.wordpress.android.ui.reader.viewmodels.ReaderPostDetailViewModel.updateRelatedPostsUiState(ReaderPostDetailViewModel.kt:480)
     at org.wordpress.android.ui.reader.viewmodels.ReaderPostDetailViewModel.access$buildLikersUiState(ReaderPostDetailViewModel.kt:77)
     at org.wordpress.android.ui.reader.viewmodels.ReaderPostDetailViewModel.access$updateRelatedPostsUiState(ReaderPostDetailViewModel.kt:77)
     at org.wordpress.android.ui.reader.viewmodels.ReaderPostDetailViewModel$onRelatedPostsRequested$1.invokeSuspend(ReaderPostDetailViewModel.kt:401)
...
(10 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by ashiagr**
Fixes #15070

I was sometimes able to reproduce this crash on the Reader post details screen on rotating the device.

### Observations

`_uiState.value` is sometimes set to `LoadingUiState` when checked inside `updateRelatedPostsUiState`.
In this case,  `(_uiState.value as? ReaderPostDetailsUiState)` converts to null and `_uiState` is updated with a null value causing a crash in the `initViewModel$1.onChanged` where it is not expected to be null. 

   ```
   E: _uiState.value: 
   org.wordpress.android.ui.reader.viewmodels.ReaderPostDetailViewModel$UiState$LoadingUiState@eed3862
   E: FATAL EXCEPTION: main
    Process: org.wordpress.android.prealpha, PID: 8564
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.wordpress.android.ui.reader.viewmodels.ReaderPostDetailViewModel$UiState.getErrorVisible()' on a null object reference
        at org.wordpress.android.ui.reader.ReaderPostDetailFragment$initViewModel$1.onChanged(ReaderPostDetailFragment.kt:443)
        at org.wordpress.android.ui.reader.ReaderPostDetailFragment$initViewModel$1.onChanged(ReaderPostDetailFragment.kt:133)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at org.wordpress.android.ui.reader.viewmodels.ReaderPostDetailViewModel.updateRelatedPostsUiState(ReaderPostDetailViewModel.kt:483)
   ```

### Solution

As `onRelatedPostsRequested` is called [only when the post is available in the VM](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt#L1282-L1287), `_uiState` is now updated with `LoadingUiState` only when the post is fetched from the server and not when the post exists in the DB (see 3aeee11) so that the above scenario doesn't happen.

Also, in 08e4395, `_uiState` is updated only when the current UI state is `ReaderPostDetailsUiState` inside `updateRelatedPostsUiState` and `updatePostActions` as related posts and actions UI should be displayed only when the selected post is available and already laid on the screen. If UI is in any other state at this time, it should be an invalid state and the UI should not be updated.

### Merge Notes

I'm a bit surprised why this issue started appearing in `17.7-rc-2`, considering refactoring for reader post details was done in a much earlier release `17.0`. Considering rising numbers in Sentry, targeting `release/17.9` as a beta fix.

### To test

1. Go to Reader. 
2. Tap a reader post.
3. Rotate the device 2-3 times.
4. Go back and repeat steps 2, 3 for few more random posts.
5. Note that the app doesn't crash.

## Regression Notes
1. Potential unintended areas of impact
None, changes have minimal impact. 

2. What I did to test those areas of impact (or what existing automated tests I relied on)
NA

3. What automated tests I added (or what prevented me from doing so)
Updated existing UI tests for the loading state.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/test/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModelTest.kt [hunk 1]
```diff
@@ -238,14 +238,14 @@ class ReaderPostDetailViewModelTest : BaseUnitTest() {
 
     /* SHOW POST - LOADING */
     @Test
-    fun `when show post is triggered, then loading state is shown`() = test {
-        val observers = init(showPost = false)
-        whenever(readerGetPostUseCase.get(anyLong(), anyLong(), anyBoolean())).thenReturn(Pair(readerPost, false))
+    fun `given local post not found, when show post is triggered, then loading state is shown`() =
```
Comment (ParaskP7) [inline WordPress/src/test/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModelTest.kt:241]: Suggestion (💡): How about including the `given local post found` as well to cover both scenarios? For example:

```
    @Test
    fun `given local post found, when show post is triggered, then loading state is not shown`() =
            test {
                val observers = init(showPost = false)

                viewModel.onShowPost(blogId = readerPost.blogId, postId = readerPost.postId)

                assertThat(observers.uiStates.first()).isNotInstanceOf(LoadingUiState::class.java)
            }
```

**Review by ParaskP7 — APPROVED** [review]
👋 @ashiagr !

I have reviewed and tested this PR as per the instructions, everything works as expected, good fix! 🌟 

I was able to replicate the crash with the existing code from `develop` and then able to verify that your fix actually solves this problem.

I have left only one test suggestion (💡) for you to consider. I am going to approve this PR anyway, since none is blocking. I am **NOT** going to merge this PR yet to give you some time to apply any of my suggestions. However, feel free to ignore them and merge the PR yourself.

File: WordPress/src/test/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModelTest.kt (hunk 1 above)
Comment (ashiagr) [reply WordPress/src/test/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModelTest.kt:241]: Added in 9e56773

Comment (ParaskP7) [reply WordPress/src/test/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModelTest.kt:241]: Thank you @ashiagr , we are good to go! ✅

**Comment by ashiagr** [comment]
Targeting `release/17.9` as a beta fix.

cc @AliSoftware

**Comment by AliSoftware** [comment]
This fix is now available to beta testers as part of 17.9-rc-2 🎉
