### PR TITLE
Moved static xml creation of PostsListFragment to code

### LINKED ISSUE #5796: Crash report 7.2: NPE in PostsListAdapter
Check already reported/fixed https://github.com/wordpress-mobile/WordPress-Android/issues/5539

````
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.posts.PostsListActivity}: android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class fragment
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2947)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3008)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6688)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class fragment

Caused by android.view.InflateException: Binary XML file line #11: Error inflating class fragment

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.wordpress.android.fluxc.model.SiteModel.isWPCom()' on a null object reference
       at org.wordpress.android.util.SiteUtils.isAccessibleViaWPComAPI(SiteUtils.java:37)
       at org.wordpress.android.ui.posts.adapters.PostsListAdapter.<init>(PostsListAdapter.java:109)
       at org.wordpress.android.ui.posts.PostsListFragment.getPostListAdapter(PostsListFragment.java:269)
       at org.wordpress.android.ui.posts.PostsListFragment.requestPosts(PostsListFragment.java:336)
       at org.wordpress.android.ui.posts.PostsListFragment.onCreateView(PostsListFragment.java:183)
       at android.app.Fragment.performCreateView(Fragment.java:2352)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:959)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1149)
       at android.app.FragmentManagerImpl.addFragment(FragmentManager.java:1255)
       at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2315)
       at android.app.FragmentController.onCreateView(FragmentController.java:99)
       at android.app.Activity.onCreateView(Activity.java:6065)
       at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:36)
       at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:79)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:784)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:378)
       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
       at org.wordpress.android.ui.posts.PostsListActivity.onCreate(PostsListActivity.java:38)
       at android.app.Activity.performCreate(Activity.java:6912)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2900)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3008)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6688)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

### PR DESCRIPTION
**Pull request by mzorz**
This PR attempts to fix #5796 (NPE upon `PostsListFragment` creation as the `SiteModel` is null) by making sure the `PostsListFragment` fragment is created through its `newInstance` method and passing the `SiteModel` as a serializable argument.

The way it was being handled was by static xml reference in `post_list_activity.xml`, which could lead to potentially having a situation where the `PostsListActivity` activity's intent extras would still not be present by the time they were needed in `PostsListFragment` (probably after a configuration change?).

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.java [hunk 1]
```diff
@@ -62,7 +63,12 @@ public void onCreate(Bundle savedInstanceState) {
             return;
         }
 
-        mPostList = (PostsListFragment) fm.findFragmentById(R.id.postList);
+        mPostList = PostsListFragment.newInstance(mSite);
+
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.java]: It shouldn't be necessary to create the fragment when the activity is recreated. Instead you can find the existing fragment, and if it's not there create it. Ex:

```
mPostList = (PostsListFragment) getFragmentManager().findFragmentByTag(PostsListFragment.TAG);
        if (mPostList == null) {
            mPostList = PostsListFragment.newInstance(mSite);
            getFragmentManager().beginTransaction()
                    .add(R.id.post_list_container, mPostList, PostsListFragment.TAG)
                    .commit();
        }
```

Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.java]: good catch! addressed in c16be14

**Comment by mzorz** [comment]
ready for another go @nbradbury 🙇

**Comment by nbradbury** [comment]
:shipit:
