### PR TITLE
Media Settings design pass through along with fix for image size settings

### LINKED ISSUE #6485: Media settings design audit
We'll be making the wording/functionality somewhat consistent with iOS

Biggest functionality we'll be changing is that we'll limit the image size by width and height dimension, not simply by width.

### PR DESCRIPTION
**Pull request by kwonye**
Fixes #6485 

@iamthomasbishop do you mind also doing a design pass in case I missed anything please? Thanks.

@daniloercoli please test the max-size of the image calculation. I'm not sure if I did it the optimal way.

### CODE REVIEW

File: libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/ImageUtils.java [hunk 1]
```diff
@@ -428,8 +428,12 @@ private static boolean resizeImageAndWriteToStream(Context context,
         // determine correct scale value (should be power of 2)
         // http://stackoverflow.com/questions/477572/android-strange-out-of-memory-issue/3549021#3549021
         int scale = 1;
-        if (maxWidth > 0 && optBounds.outWidth > maxWidth) {
-            double d = Math.pow(2, (int) Math.round(Math.log(maxWidth / (double) optBounds.outWidth) / Math.log(0.5)));
+        boolean isPortrait = optBounds.outWidth < optBounds.outHeight;
+        int optBoundsMaxSize = Math.max(optBounds.outWidth, optBounds.outHeight);
```
Comment (daniloercoli) [inline libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/ImageUtils.java]: Can we declare here `double largestSizeOfOutBounds = Math.max(optBounds.outWidth, optBounds.outHeight);` and get rid of both `isPortrait` and `optBoundsMaxSize` ?

Comment (daniloercoli) [inline libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/ImageUtils.java]: Something like the following:
```
        double largestSizeOfOutBounds = Math.max(optBounds.outWidth, optBounds.outHeight);
        if (maxSize > 0 && largestSizeOfOutBounds > maxSize) {
            double d = Math.pow(2, (int) Math.round(Math.log(largestSizeOfOutBounds / largestSizeOfOutBounds) / Math.log(0.5)));

            scale = (int) d;
        }
```

File: libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/ImageUtils.java [hunk 2]
```diff
@@ -875,4 +872,22 @@ public static Bitmap getThumbnail(ContentResolver contentResolver, long id, int
 
         return null;
     }
+
+    private static float getScaleImageBy(float maxSize, Bitmap bmpResized, boolean isPortrait) {
```
Comment (daniloercoli) [inline libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/ImageUtils.java]: Is the parameter `isPortrait` necessary here? It seems that we can get height and width dimensions from `bmpResized` parameter.

**Comment by daniloercoli** [comment]
Should we apply the same patch to videos? 
Video resizing option does only consider the width. Regardless of the orientation of the video.

**Comment by daniloercoli** [comment]
I see video resizing dimensions changed a bit. 

**Niptick:**
We should change the code that sets the previous value here https://github.com/wordpress-mobile/WordPress-Android/pull/6556/files#diff-cdcbc2d7423e158442299f266c956df1L102
```
 setDetailListPreferenceValue(mVideoWidthPref,
                String.valueOf(AppPrefs.getVideoOptimizeWidth()),
                getLabelForVideoMaxWidthValue(AppPrefs.getVideoOptimizeWidth()));
```

Otherwise for users that had selected 1024px `String.valueOf(AppPrefs.getVideoOptimizeWidth()),` will return 1024 and result in empty selection in the dialog as seen in pictures below:
device-2017-08-22-114452

device-2017-08-22-114502

**Comment by kwonye** [comment]
> Should we apply the same patch to videos?
> Video resizing option does only consider the width. Regardless of the orientation of the video.

With video I think it's slightly different where it's expected to be a certain resolution, regardless of orientation, e.g. 720p is 1280x720px or 720x1280px. I tested that the videos are the correct resolution regardless of orientation, so I think we should keep it as is.

File: libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/ImageUtils.java [hunk 3]
```diff
@@ -530,19 +525,19 @@ public static String optimizeImage(Context context, String path, int maxImageWid
         String fileName = MediaUtils.getMediaFileName(file, mimeType);
         String fileExtension = MimeTypeMap.getFileExtensionFromUrl(fileName).toLowerCase();
 
-        int selectedWidth = getImageSize(srcImageUri, context)[0];
-        if (selectedWidth == 0) {
+        int selectedMaxSize = getImageSize(srcImageUri, context)[0];
```
Comment (daniloercoli) [inline libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/ImageUtils.java]: I noticed that selecting Original Dimensions doesn't work as expected, since we're taking in consideration the width of the picture only here, where is should be
```
int[] imageDimensions = getImageSize(srcImageUri, context);
int selectedMaxSize = Math.max(imageDimensions[0], imageDimensions[1]);
```

**Comment by kwonye** [comment]
@daniloercoli added tests with the "new" aka "old" image scale calculation. Can you verify it please and run the tests?

**Comment by kwonye** [comment]
Also, since I changed WordPressUtils, I have to make a new version right?

**Comment by daniloercoli** [comment]
Don't think you need to make a new version; feel free to do that though. 
We usually release a new version when a project that use the artifacts version of the library needs latests change.

**Comment by daniloercoli** [comment]
This PR looks good! :shipit: 
@kwonye We should make sure that iOS will follow the same logic on resizing pictures (i.e: taking both width and height in consideration when finding the scale).

**Comment by iamthomasbishop** [comment]
@kwonye @daniloercoli  How did we determine which values to show for max image size? (`1000px`, `2000px`, `2500px`, `3000px` and `Original`). Is there any reason for those specific options? I'm wondering if this would make more sense in a slider format...

Example: 
screenshot 2017-08-29 11 40 14

Also, what are the differences in Image Quality? (low, medium, high, very high, maximum...are all of these options necessary?) Same question for Video Quality.

**Comment by daniloercoli** [comment]
>  I'm wondering if this would make more sense in a slider format...

Unfortunately we can't use sliders in Android stock Preferences screen. There are 3rd party library for that, but we've decided to not use them (Ref: https://github.com/wordpress-mobile/WordPress-Android/pull/5590#issuecomment-292302293), since we will migrate away from "pure android" preferences implementation soon. Once the migration is done we can use the all of the standard Android UI widgets, including sliders.

> How did we determine which values to show for max image size? (1000px, 2000px, 2500px, 3000px and Original).

Not quite sure, I bet it was a legacy thing we imported from the earlier versions of the Android app.

**Comment by daniloercoli** [comment]
> Also, what are the differences in Image Quality? (low, medium, high, very high, maximum...are all of these options necessary?) Same question for Video Quality.

Image quality labels `low, medium, high, very high, maximum`  is a way to summarize  the compression parameters passed to the video encoder.  Not sure if all of these options are necessary or not, maybe keep 3 or 4 only?

**Comment by kwonye** [comment]
> Not quite sure, I bet it was a legacy thing we imported from the earlier versions of the Android app.

@iamthomasbishop definitely if you have different values for these that you'd like, please let us know and we'd be more than glad to modify. One thing I was told about max size (previously width) by @daniloercoli was that it was for people uploading the correct size for header/background images... use that info as you will assuming it's correct.

> Not sure if all of these options are necessary or not, maybe keep 3 or 4 only?

I wouldn't mind if we simplified it at all.

**Comment by iamthomasbishop** [comment]
> Unfortunately we can't use sliders in Android stock Preferences screen. There are 3rd party library for that, but we've decided to not use them (Ref: #5590 (comment)), since we will migrate away from "pure android" preferences implementation soon. Once the migration is done we can use the all of the standard Android UI widgets, including sliders.

So if I'm hearing you correctly, we can't easily use sliders here at the moment, but we will be able to in the near future? Only offering a handful of arbitrary sizes for max image size doesn't really make sense to me, so I'm open to ideas. In the future, we should probably switch to something like I've described, which after looking - I believe is exactly how we handle it on iOS.

> Image quality labels low, medium, high, very high, maximum is a way to summarize the compression parameters passed to the video encoder. Not sure if all of these options are necessary or not, maybe keep 3 or 4 only?

I'd recommend slimming down quality labels wherever possible (video + image) to reduce cognitive load - perhaps something like low, medium, high, max? We could also eventually put this in a slider, but I'm okay with it using this same dialog UI we're currently using for now.

**Comment by daniloercoli** [comment]
> So if I'm hearing you correctly, we can't easily use sliders here at the moment

Yes, right. No sliders until we migrate this entire app settings screen away from default Android `Preferences` & `PreferenceFragment` .

> I'd recommend slimming down quality labels wherever possible (video + image) to reduce cognitive load - perhaps something like low, medium, high, max? 

Seems ok to me. @kwonye Are you ok on reducing the available choices in this PR?

**Comment by daniloercoli** [comment]
Let's merge this PR in `develop` and open new issue for slimming down quality choices.

**Comment by daniloercoli** [comment]
:shipit:
