### PR TITLE
[Reader] Fix `Reader` showing posts from a language different than the selected one

### LINKED ISSUE #19969: [Reader][Bug] Locale not working properly on some Reader requests
### Expected behavior
An appropriate locale-related parameter should be sent on Reader requests, based on the current language of the System/App to provide relevant results and content to the user.

### Actual behavior
Several Reader screens/requests are not using the locale-related parameter expected by the backend, which causes the backend to return results using defaults (which are either English or the Interface language set in the WordPress.com account on web).

Examples:
- Requests to `/rest/v1.2/read` path (such as search and tags) send a `locale` query parameter, but the endpoints on that path seem to expect a `lang` parameter. When they return, it seems to be using the interface language from the WP.com account.
- Requests to `/wpcom/v2/read` path (such as discover) send a `locale` query parameter, but the endpoints on that path seem to expect a `_locale` parameter. When they return, it seems to be using English as default. (not 100% sure)

### Steps to reproduce the behavior
1. Install and log into Jetpack
2. Set the app language to something other than English (also, preferably not matching the interface language setting of the WP.com account)
3. Go to the Reader
4. Go to Discover Feed
5. Verify that Discover results don't match the app language
6. Tap on a suggested tag
7. Verify that the tag results don't match the app language
8. Go to Search
9. Search for anything, ideally a generic word used in several languages (ex: Android, iPhone)
10. Verify that the search results don't match the app language

### PR DESCRIPTION
**Pull request by RenanLukas**
Fixes #19969 

-----

There are many testing steps, but basically the goal of this PR is to make sure the content shown in the Reader matches the app selected language. If you see any `Reader` content using the wrong language, please let me know.

## To Test:

1. Install Jetpack and sign in.
2. Open "Me" screen.
3. Tap "App Settings".
4. Change the "Interface Language" to a language **different than English and different than the one selected in `wordpress.com`** (it seems like when the language query parameter is missing, the response defaults to the language selected in web. Thanks @thomashorta  for the tip).
5. Open "Reader".
6. Make sure you're following at least one tag and open "Discover" feed.
7. 🔍 Verify the posts list: they should be posts matching the selected language in step 4.
8. Open the search screen (tap on 🔍).
9. 🔍 Search for something: the results should match the selected language in step 4 even if you search use words from a different language (e.g. searching for the word "football" while having Portuguese selected). **Ideally this step should be tested using a version before and after Android O (see [here](https://github.com/wordpress-mobile/WordPress-Android/blob/ac56c495d4f5cecf2a50f349576f23515679d8b1/WordPress/src/main/java/org/wordpress/android/ui/reader/services/search/ReaderSearchServiceStarter.java#L26))**.
10. Open "My Site" tab with a blog selected.
11. Look for the daily prompts card and tap "View all responses".
12. 🔍 The posts should match the selected language in step 4. **Ideally this step should be tested using a version before and after Android O (see [here](https://github.com/wordpress-mobile/WordPress-Android/blob/7843d4e88d4b6ded2656df769e305c9c7f326d0b/WordPress/src/main/java/org/wordpress/android/ui/reader/services/post/ReaderPostServiceStarter.java#L42))**
13. Open "Reader" and select "Discover".
14. Scroll until you find a tags card and select any tag.
15. 🔍 The posts should match the selected language in step 4. **Ideally this step should be tested using a version before and after Android O (see [here](https://github.com/wordpress-mobile/WordPress-Android/blob/7843d4e88d4b6ded2656df769e305c9c7f326d0b/WordPress/src/main/java/org/wordpress/android/ui/reader/services/post/ReaderPostServiceStarter.java#L42))**
16. Unfollow all tags using "Subscriptions" feed.
17. Open "Discover" feed: the empty state should be triggered and you'll see a button (the label in English is "Get Started")
image

18. 🔍  Tap the button: the suggested tags should match the language selected in step 4.

Feel free to change to pick language at any point: things should work as expected. Just be sure that the selected language is not the same as the one in `wordpress.com`.

-----

## Regression Notes

1. Potential unintended areas of impact

    - Language of "Reader" results

20. What I did to test those areas of impact (or what existing automated tests I relied on)

    - Manual testing

21. What automated tests I added (or what prevented me from doing so)

    - Had to update legacy code, which is not testable without a significant refactor.

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WordPress/src/main/java/org/wordpress/android/ui/notifications/utils/NotificationsUtils.java [hunk 1]
```diff
@@ -87,7 +87,7 @@ public static void getPushNotificationSettings(Context context, RestRequest.List
         if (!TextUtils.isEmpty(deviceID)) {
             settingsEndpoint += "?device_id=" + deviceID;
         }
-        WordPress.getRestClientUtilsV1_1().get(settingsEndpoint, listener, errorListener);
+        WordPress.getRestClientUtilsV1_1().getWithLocale(settingsEndpoint, listener, errorListener);
```
Comment (RenanLukas) [inline WordPress/src/main/java/org/wordpress/android/ui/notifications/utils/NotificationsUtils.java:90]: I've renamed the existing `get` method to `getWithLocale` because it adds a `"locale"` query parameter to every request. As you can see in this PR, some of our endpoints expect `"_locale"` or even `"lang"` query parameters instead of `"locale"`, so I've renamed it and created a `get` method that doesn't add any locale query parameter automatically.

**Review by daniloercoli — APPROVED** [review]
Tested and LGTM!
