### PR TITLE
Stats - Do not cache responses > 2MB

### LINKED ISSUE #2862: Potential IllegalStateException in Stats Cache
Stats cache may crash when a very large response is stored in the `tbl_stats.jsonData` 'text' column.
Never happened yet, but storing very large text columns could result in an IllegalStateException when the row was read due to the 2MB size limit for Android's CursorWindow ( see [here](https://github.com/android/platform_frameworks_base/blob/master/core/res/res/values/config.xml#L946) and [here](https://github.com/android/platform_frameworks_base/blob/3bdbf644d61f46b531838558fabbd5b990fc4913/core/java/android/database/CursorWindow.java#L103) ).

Easy fix is to detect the size of the JSON text when parsing the response and limiting how much of it is stored.

See: https://github.com/wordpress-mobile/WordPress-Android/pull/1878

### PR DESCRIPTION
**Pull request by daniloercoli**
Fix #2862

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/stats/datasets/StatsTable.java [hunk 1]
```diff
@@ -107,6 +108,20 @@ public static void insertStats(final Context ctx, final int blogId, final StatsT
...
+         * with a very large text column, causing an IllegalStateException when the
+         * row is read - prevent this by limiting the amount of text that's stored in
+         * the text column - note that this situation very rarely occurs
+         * https://github.com/android/platform_frameworks_base/blob/master/core/res/res/values/config.xml#L1268
+         * https://github.com/android/platform_frameworks_base/blob/3bdbf644d61f46b531838558fabbd5b990fc4913/core/java/android/database/CursorWindow.java#L103
+         */
+
+        //Check if the response document from the server is less than 1.8MB. getBytes uses UTF-8 on Android.
+        if (jsonResponse.getBytes().length > MAX_RESPONSE_LEN) {
+            return;
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/datasets/StatsTable.java]: We probably want to write to `AppLog` here.

Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/datasets/StatsTable.java]: Right, better to add logging here.

**Comment by nbradbury** [comment]
:shipit:
