### PR TITLE
Issue/4404 reader layout differences

### LINKED ISSUE #4404: Reader: Stream and card layout differences with Calypso
I came across differences between Android and Calypso Reader. Basically, I noticed this mainly because I feel like the timestamp is in the wrong place - it doesn't seem like it pertains to the post itself, rather the entire site:

screenshot 2016-07-19 16 53 49

**For Followed Sites:**

- Card:
screenshot-2016-07-19-16 14 16

- I also noticed that if it's a non-wpcom site, their URL is not shown:
screenshot 2016-07-19 16 27 55

**For main Discover stream:**

- In Calypso, we have a single site header at the very top of the main Discover stream to avoid site header repetition:

screenshot 2016-07-19 16 32 33

Card:
screenshot-2016-07-19-16 42 54

**For Full-post view:**

screenshot-2016-07-19-16 51 46

Let me know if I should break this up into several smaller issues.

/cc @nbradbury

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #4404 - addresses the following issues:
* In the reader list, show gravatar, author & timestamp below the post title (and remove the timestamp from the post header)
* In the reader list,  show the full domain in the post header, and make sure it shows for non-wpcom sites
* In the reader list, show the blog name in the dateline when there's no author name (to match Calypso)
* In the reader detail, move the timestamp to the right of the author name
* In the reader detail, show the blavatar in the header and the gravatar in the dateline

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.java [hunk 1]
```diff
@@ -878,36 +880,38 @@ public void onClick(View v) {
...
-            if (mPost.hasAuthorName()) {
-                txtAuthor.setText(mPost.getAuthorName());
-                txtAuthor.setVisibility(View.VISIBLE);
+            if (mPost.hasPostAvatar()) {
+                int avatarSz = getResources().getDimensionPixelSize(R.dimen.avatar_sz_tiny);
+                imgAvatar.setVisibility(View.VISIBLE);
+                imgAvatar.setImageUrl(mPost.getPostAvatarForDisplay(avatarSz), WPNetworkImageView.ImageType.AVATAR);
             } else {
-                txtAuthor.setVisibility(View.GONE);
+                imgAvatar.setVisibility(View.GONE);
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.java]: When the avatar is missing, should we just show a default avatar resource? I think we handle this case on the server-side and return a default avatar url and it _never_ reaches to the _else_ statement, but I am not sure. If it ever does, it might be better to have that default avatar as a resource file. What do you think?

File: WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.java [hunk 2]
```diff
@@ -878,36 +880,38 @@ public void onClick(View v) {
...
             }
 
-            String dateLine;
-            if (mPost.hasBlogUrl()) {
-                dateLine = UrlUtils.getHost(mPost.getBlogUrl()) + " \u2022 " + DateTimeUtils.javaDateToTimeSpan(mPost.getDatePublished());
+            String timestamp = DateTimeUtils.javaDateToTimeSpan(mPost.getDatePublished());
+            if (mPost.hasAuthorName()) {
+                txtDateline.setText(mPost.getAuthorName() + ReaderConstants.UNICODE_BULLET_WITH_SPACE + timestamp);
+            } else if (mPost.hasBlogName()) {
+                txtDateline.setText(mPost.getBlogName() +  ReaderConstants.UNICODE_BULLET_WITH_SPACE + timestamp);
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.java]: This is a very small nitpick probably shouldn't even be mentioned, but there is an extra space after the `+` sign :(

File: WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderPostAdapter.java [hunk 3]
```diff
@@ -313,34 +315,40 @@ private void renderPost(int position, ReaderPostViewHolder holder) {
...
 
-        // dateline includes author name if different than blog name
-        String dateLine;
-        if (post.hasAuthorName() && !post.getAuthorName().equalsIgnoreCase(post.getBlogName())) {
-            dateLine = post.getAuthorName() + " \u2022 " + DateTimeUtils.javaDateToTimeSpan(post.getDatePublished());
+        String timestamp = DateTimeUtils.javaDateToTimeSpan(post.getDatePublished());
+        if (post.hasAuthorName()) {
+            holder.txtDateline.setText(post.getAuthorName() + ReaderConstants.UNICODE_BULLET_WITH_SPACE + timestamp);
+        } else if (post.hasBlogName()) {
+            holder.txtDateline.setText(post.getBlogName() +  ReaderConstants.UNICODE_BULLET_WITH_SPACE + timestamp);
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderPostAdapter.java]: Same extra space nitpick as in the previous comment :(

File: WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderPostAdapter.java [hunk 4]
```diff
@@ -313,34 +315,40 @@ private void renderPost(int position, ReaderPostViewHolder holder) {
...
-            dateLine = DateTimeUtils.javaDateToTimeSpan(post.getDatePublished());
+            holder.txtDateline.setText(timestamp);
+        }
+
+        if (post.hasPostAvatar()) {
+            holder.imgAvatar.setVisibility(View.VISIBLE);
+            holder.imgAvatar.setImageUrl(
+                    post.getPostAvatarForDisplay(mAvatarSzTiny), WPNetworkImageView.ImageType.AVATAR);
+        } else {
+            holder.imgAvatar.setVisibility(View.GONE);
```
Comment (oguzkocer) [inline WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderPostAdapter.java]: My previous [default avatar comment](https://github.com/wordpress-mobile/WordPress-Android/pull/4417/files#r72795199) applies to this as well.

**Comment by oguzkocer** [comment]
@nbradbury I am done with my pass. I've tested the changes both on an emulator and on Samsung S6 and it looks good. I also tried manipulating the code to see some edge cases like having a long name, missing avatar etc and didn't find any issues.

I've left a couple very small comments but they're non-blockers for me.

**Comment by nbradbury** [comment]
@oguzkocer Thanks for the review! Agreed about showing the default avatar - I've corrected that and addressed the extra spaces.

**Comment by oguzkocer** [comment]
Looks good :shipit: I'll merge once Travis does it's thing.

**Comment by jancavan** [comment]
Nice work @nbradbury 👏
