### PR TITLE
Fix #3594 webview crash on app start

### LINKED ISSUE #3594: Crash report 4.9: NameNotFoundException: com.google.android.webview
Makes me sad...

```
Fatal Exception: java.lang.RuntimeException: Unable to create application org.wordpress.android.WordPress: android.util.AndroidRuntimeException: android.content.pm.PackageManager$NameNotFoundException: com.google.android.webview
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4529)
       at android.app.ActivityThread.access$1500(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5249)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
Caused by android.util.AndroidRuntimeException: android.content.pm.PackageManager$NameNotFoundException: com.google.android.webview
       at android.webkit.WebViewFactory.getFactoryClass(WebViewFactory.java:161)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:101)
       at android.webkit.WebView.getFactory(WebView.java:2185)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2180)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2239)
       at android.view.View.(View.java)
       at android.view.View.(View.java)
       at android.view.ViewGroup.(ViewGroup.java)
       at android.widget.AbsoluteLayout.(AbsoluteLayout.java)
       at android.webkit.WebView.(WebView.java)
       at android.webkit.WebView.(WebView.java)
       at android.webkit.WebView.(WebView.java)
       at android.webkit.WebView.(WebView.java)
       at android.webkit.WebView.(WebView.java)
       at org.wordpress.android.WordPress.getDefaultUserAgent(WordPress.java:577)
       at org.wordpress.android.WordPress.getUserAgent(WordPress.java:595)
       at org.wordpress.android.WordPress.onCreate(WordPress.java:189)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4526)
       at android.app.ActivityThread.access$1500(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5249)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
```

Someone tried to find the cause of it: http://stackoverflow.com/a/29809338/58332

### PR DESCRIPTION
**Pull request by maxme**
Fix #3594 webview crash on app start by catching a runtime exception.

Rare crash, but it makes the app crash on start :/

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/WordPress.java [hunk 1]
```diff
@@ -574,7 +575,14 @@ public static String getLoginUrl(Blog blog) {
     public static String getDefaultUserAgent() {
         if (mDefaultUserAgent == null) {
             // TODO: use WebSettings.getDefaultUserAgent() after upgrade to API level 17+
-            mDefaultUserAgent = new WebView(getContext()).getSettings().getUserAgentString();
+            try {
+                // Catch AndroidRuntimeException that could be raised by the WebView() constructor.
+                // See https://github.com/wordpress-mobile/WordPress-Android/issues/3594
+                mDefaultUserAgent = new WebView(getContext()).getSettings().getUserAgentString();
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/WordPress.java]: That SO poster says they only saw this on 5.0 devices, so would it be worthwhile using `WebSettings.getDefaultUserAgent()` to avoid the crash when we detect API 17+?

Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/WordPress.java]: Apparently [it's not specific to 5.0+ devices](https://stackoverflow.com/questions/29575313/namenotfoundexception-webview/29809338#comment48094186_29809338), but we could use `WebSettings.getDefaultUserAgent()` in the catch block, but I don't know if it's going to raise the same kind of **weird** exception. Fill a new issue for 5.0?

Comment (maxme) [inline WordPress/src/main/java/org/wordpress/android/WordPress.java]: Or maybe [it's 5.0 specific](https://stackoverflow.com/questions/29575313/namenotfoundexception-webview/29809338#comment48110351_29809338)...

**Comment by nbradbury** [comment]
:shipit:
