### PR TITLE
Issue/6704 media items multiple enqueueing

### LINKED ISSUE #6704: Async - media uploads get enqueued multiple times
### Expected behavior
Every time the user inserts media items (other than 1 only item) using the media picker in the Editor, the `UploadService` should get called once, with a full list of items to be uploaded.

### Actual behavior
Every time the user inserts media items (other than 1 only item) using the media picker in the Editor, the `UploadService` gets called as many items as items are there in the list, with incremental amounts each time. 
For example, if you insert 1 item, all is good.
Insert 2 items instead, the insertion code gets called once with a list of size=1, then again for a list of size=2 as the second item gets added, adding the first element of the list effectively twice.
Same would happen if it’d been 3 items: first item gets added 3 times, second one twice, last item just once.

In reality, we're uploading media items just once if they're already enqueued, [thanks to this check](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/uploads/MediaUploadHandler.java#L241). However, imagine a situation where a long pending list is due. If we selected many items and repeated the first items again in the last part of the queue, giving these items enough time to upload and end up off the queue before reaching the same items again enqueued in the tail of the list, then these would be uploaded multiple times.

### Steps to reproduce the behavior
1. Place a breakpoint on this line https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java#L163
2. start a new draft
3. tap on the media picker icon
4. select more than 1 media item to include (in particular, select 2 items for the description in step 5 to match)
5. observe the `unpackIntent` method gets called twice, first time with a `mediaList` containing 1 item (size=1) and second time with a `mediaList` containing 2 items (size=2), resulting in 3 items being enqueued to upload instead of just 2 as per the user's intention.

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #6704 

Removes the `mPendingUploads` artifact as it was being kept for visual purposes previous to the `UploadStore` introduction in https://github.com/wordpress-mobile/WordPress-Android/pull/6613

To test:

1. Place a breakpoint on this line https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java#L163
2. start a new draft
3. tap on the media picker icon
4. select two items using long press
5. observe the `unpackIntent` method gets called twice, first time with a `mediaList` containing 1 item (size=1) and second time with a `mediaList` containing 1 item (size=1)

cc @nbradbury @aforcier

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java [hunk 1]
```diff
@@ -2299,26 +2278,22 @@ public void onMediaChanged(OnMediaChanged event) {
...
-        if (mPendingUploads != null && !mPendingUploads.isEmpty()) {
-            final ArrayList<MediaModel> mediaList = new ArrayList<>();
-            for (MediaModel media : mPendingUploads) {
-                if (MediaUploadState.QUEUED.toString().equals(media.getUploadState())) {
-                    mediaList.add(media);
-                }
-            }
+    private void startUploadService(MediaModel media) {
+        final ArrayList<MediaModel> mediaList = new ArrayList<>();
+        if (MediaUploadState.QUEUED.toString().equals(media.getUploadState())) {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: I think this method can be simplified by doing a `return` if the media is already queued. So:

```
private void startUploadService(MediaModel media) {
    if (MediaUploadState.QUEUED.toString().equals(media.getUploadState())) {
        return;
    }

    final ArrayList<MediaModel> mediaList = new ArrayList<>();
    mediaList.add(media);

    // before starting the service, we need to update the posts' contents so we are sure the service
    // can retrieve it from there on
    savePostAsync(new AfterSavePostListener() {
        @Override
        public void onPostSave() {
            UploadService.uploadMedia(EditPostActivity.this, mediaList);
        }
    });
}
```

Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: Just for info for the casual reader of this PR, the actual meaning of the code in there is that the media item needs to have the `QUEUED` state in order to be passed to the `UploadService`. I could yet use the simplifiation by adding a negation operator at the start of that if, like this:
```
if (!MediaUploadState.QUEUED.toString().equals(media.getUploadState())) {
        return;
    }
```
would that make sense @nbradbury ?

Comment (nbradbury) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: Oh, right - I completely reversed that. Yes, that makes sense, and perhaps add a comment explaining it.

Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: addressed in f911bed

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java [hunk 2]
```diff
@@ -2279,22 +2279,21 @@ public void onMediaChanged(OnMediaChanged event) {
      * Starts the upload service to upload selected media.
      */
     private void startUploadService(MediaModel media) {
-        final ArrayList<MediaModel> mediaList = new ArrayList<>();
-        if (MediaUploadState.QUEUED.toString().equals(media.getUploadState())) {
-            mediaList.add(media);
+        // make sure we only pass items with the QUEUED state to thee UploadService
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: Minor nit but I have to point it out: should be `the` not `thee`.

Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: oops sorry afa25cb

**Comment by nbradbury** [comment]
Looks good, and it's nice to see code removed from `EditPostActivity`! :shipit:
