### PR TITLE
Aztec: match `undo` and `discard local changes` options

### LINKED ISSUE #8010: Aztec / Discard changes functionality: don't show discard local changes if no changes to undo
### Expected behavior
Aztec's `undo` functionality and the new WPAndroid `Discard local changes` functionality should be in sync - if there's nothing to be undone, then `Discard local changes` should not be shown as an option (unless the opened Post was already marked with `isLocallyChanged`).

### Actual behavior
`Discard local changes` is shown in the menu as an option even if there's nothing to `undo`, regardless of what the `isLocallyChanged` flag was at the time of opening the Post in the Editor.

### Steps to reproduce the behavior

1. Open an existing post
2. observe the overflow menu (correctly) does not have the "Discard local changes" option
3. enter a new character
4. observe the overflow menu (correctly) now shows the "Discard local changes" option
5. do not tap on that new option, but tap on Undo.
6. observe the action is undone and the content is exactly as what we had earlier
7. tap on the overflow menu icon again
8. observe the "Discard local changes" option is shown, but it shouldn't (there are in theory no local changes to be discarded).

This is because we're relying on the `isLocallyChanged` flag to reflect current state, but it's not being changed when there's nothing else to undo.

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #8010 

From the point of view of the Editor, there are basically 2 moments where a Post can have a "Local changes" status:

a. either the Post already has that status when it's opened in the Editor, or
b. the Editor sets the `isLocallyChanged` flag on the `Post` object as a result of the user making changes to the title or content (or for the case, any of the Post's configuration settings).

This PR takes these two situations into account by making the `Discard local changes` appear either when there's some local history available (noting that the "change history" for now starts only when the Post is opened in the Editor), or when the `isLocallyChanged` flag was already set at the time this Post was opened in the Editor.

#### CASE A: post already had local changes.
1. Open a Post that has `Local changes` flag in the Posts list (to make this happen, you can start a new draft, enter some text, turn airplane mode ON, and tap BACK - remember to turn airplane mode OFF then).
2. check the overflow menu (tap the three dots icon at the top-right corner of the screen) shows the `Discard Local Changes` option

#### CASE B: post doesn't already have local changes.
1. Open an existing Post
2. check the menu does _not_ show the `Discard Local Changes` option
3. enter some text (a character is fine), effectively modifying the original content
4. check the menu now does show the `Discard Local Changes` option
5. tap on the `Undo` option - if you entered more text in step 3 just make sure there's nothing left to be undone by tapping `undo` until it's greyed out.
6. once the `undo` option is not tappable anymore, obseve the  `Discard Local Changes` option is not shown anymore.

cc @SylvesterWilmott following up from https://github.com/wordpress-mobile/WordPress-Android/pull/8005#issuecomment-403838005

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java [hunk 1]
```diff
@@ -505,6 +506,7 @@ public void run() {
     private void initializePostObject() {
         if (mPost != null) {
             mOriginalPost = mPost.clone();
+            mOriginalPostHadLocalChangesOnOpen = mOriginalPost.isLocallyChanged();
```
Comment (theck13) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: What about naming `mOriginalPostHadLocalChangesOnOpen` something like `mOriginalPostWasLocallyChanged` since its only assignment is `mOriginalPost.isLocallyChanged()`?

Comment (mzorz) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: Thanks for the suggestion @theck13 ! I think the current name, while a bit lengthier than the suggested one, better describes the specific situation where it's going to be used - that is, the value it's carrying is only meaningful `OnOpen`. We could either leave it as is or maybe rename it to `mOriginalPostWasLocallyChangedOnOpen` if you want? wdyt?

Comment (theck13) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java]: It's not a big deal so we can leave it as is.
