### PR TITLE
Persist selected app language across app sessions

### LINKED ISSUE #4932: App Settings: Interface Language setting does not persist after closing app completely
### Expected behavior

I expect the language setting under Me > App Settings > Interface Language to persist until I change the setting (or perhaps until I log out).

### Actual behavior

When the app goes to the background, the language setting persists. However, if I swipe to close the app completely, when I reopen the app the interface language is reset to my device language.

### Steps to reproduce the behavior

1. Go to Me > App Settings > Interface Language
2. Select a language other than your device language
3. Tap OK
4. Completely close the app
5. Reopen the app

Result: The interface language is now your device language, instead of the language you selected as the app's interface language.

##### Reported in 150629-h on Samsung Galaxy A7, Android 6.0.1, WPAndroid 6.2

### PR DESCRIPTION
**Pull request by tonyr59h**
Fixes #4932 

To test:
* Go to Me -> App Settings and change your language
* Force close the app
* Restart the app and verify the language change persisted
* Change your language to device default
* Force close the app
* Restart the app and verify the language change persisted

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java [hunk 1]
```diff
@@ -145,12 +145,7 @@ private void changeLanguage(String languageCode) {
         conf.locale = newLocale;
         res.updateConfiguration(conf, res.getDisplayMetrics());
 
-        if (LanguageUtils.getCurrentDeviceLanguage(WordPress.getContext()).equals(newLocale)) {
-            // remove custom locale key when original device locale is selected
-            mSettings.edit().remove(LANGUAGE_PREF_KEY).apply();
-        } else {
-            mSettings.edit().putString(LANGUAGE_PREF_KEY, newLocale.toString()).apply();
-        }
+        mSettings.edit().putString(LANGUAGE_PREF_KEY, newLocale.toString()).apply();
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java]: Do we really want to set the app locale even when it's the same as the device? That seems like it would result in unnecessary work for the app since `WPActivityUtils.applyLocale()` will always apply the locale [here](https://github.com/wordpress-mobile/WordPress-Android/blob/issue/4932-persist-selected-locale/WordPress/src/main/java/org/wordpress/android/util/WPActivityUtils.java#L98). This could lead to more issues since having a custom locale for the app has been the source of quite a few problems.

Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java]: Note: I can see that `WPActivityUtils.applyLocale()` is supposed to skip applying the locale when it's the same as the device's, but that doesn't seem to always work. I changed both the app and device locale to French, but there was a difference between the two still (see screenshot of debug code below).



locale

Comment (tonyr59h) [inline WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java]: My concern with not storing it is that the selected App Language might get lost if the user updates their Device Language.

For example:
Both set to "en_US" == not stored -> Change device language to anything else -> App is no longer "en_US"

Actually, that flow might make more sense...

Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java]: > Actually, that flow might make more sense...

I agree, it makes sense to me that if the app is using the device language, the app language should change if the user updates the device language.

File: WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java [hunk 2]
```diff
@@ -134,23 +134,25 @@ private void changeLanguage(String languageCode) {
...
         Resources res = getResources();
         Configuration conf = res.getConfiguration();
-        Locale currentLocale = conf.locale != null ? conf.locale : LanguageUtils.getCurrentDeviceLanguage(WordPress.getContext());
+        Locale currentLocale = conf.locale != null ?
+                conf.locale : LanguageUtils.getCurrentDeviceLanguage(WordPress.getContext());
 
-        if (currentLocale.toString().equals(languageCode)) return;
-
-        updateLanguagePreference(languageCode);
+        if (currentLocale.getLanguage().equals(new Locale(languageCode).getLanguage())) {
```
Comment (tonyr59h) [inline WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java]: This is how [the documentation](https://docs.oracle.com/javase/7/docs/api/java/util/Locale.html#getLanguage()) for `getLanguage` recommends comparing languages.

File: WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java [hunk 3]
```diff
@@ -134,23 +134,25 @@ private void changeLanguage(String languageCode) {
...
+            return;
+        }
 
-        // update configuration
         Locale newLocale = WPPrefUtils.languageLocale(languageCode);
-        conf.locale = newLocale;
-        res.updateConfiguration(conf, res.getDisplayMetrics());
-
-        if (LanguageUtils.getCurrentDeviceLanguage(WordPress.getContext()).equals(newLocale)) {
+        if (currentLocale.getLanguage().equals(newLocale.getLanguage())) {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java]: This comparison doesn't work because `currentLocale` isn't the current device language unless `conf` is null above (which I think it would rarely be).

Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java]: Looking into this further, I think the comparison needs to be with `Locale.getDefault()` rather than the device locale.

Comment (tonyr59h) [inline WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java]: Yeah, good call on `Locale.getDefault()` here. `getCurrentDeviceLanguage` is a pretty inaccurate name, should probably be something like `getCurrentConfigLanguage`.

I also found/fixed an issue with the comparisons not including country codes (via `getLanguage`).

**Comment by tonyr59h** [comment]
Ready for another go!

File: WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java [hunk 4]
```diff
@@ -136,13 +136,13 @@ private void changeLanguage(String languageCode) {
...
+        Locale newLocale = WPPrefUtils.languageLocale(languageCode);
 
-        if (currentLocale.getLanguage().equals(new Locale(languageCode).getLanguage())) {
+        if (currentLocale.toString().equals(newLocale.getDisplayLanguage())) {
             return;
         }
 
-        Locale newLocale = WPPrefUtils.languageLocale(languageCode);
-        if (currentLocale.getLanguage().equals(newLocale.getLanguage())) {
+        if (Locale.getDefault().toString().equals(newLocale.toString())) {
```
Comment (nbradbury) [inline WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java]: Commit b07a41b dropped `toString()` from the locale equality comparison as recommended by the [docs](https://docs.oracle.com/javase/7/docs/api/java/util/Locale.html#getLanguage()), but here `toString()` has been added back to the comparison. Was this intentional?

Comment (tonyr59h) [inline WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java]: Yeah, that was intentional. As I was testing I switched between `en_US` and `en_GB` but I noticed that this comparison returned true. Turns out `getLanguage` doesn't include the country code so regional variants always compare to true.

**Comment by nbradbury** [comment]
:shipit:
