### PR TITLE
Fix IllegalArgumentException when starting Camera and no space on device

### LINKED ISSUE #5455: Crash report: IllegalArgumentException in WordPressMediaUtils
```
Fatal Exception: java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/sdcard1/DCIM/Camera/wp-1490017032625.jpg
       at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:711)
       at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:400)
       at org.wordpress.android.ui.media.WordPressMediaUtils.getLaunchCameraIntent(WordPressMediaUtils.java:160)
       at org.wordpress.android.ui.media.WordPressMediaUtils.preparelaunchCamera(WordPressMediaUtils.java:150)
       at org.wordpress.android.ui.media.WordPressMediaUtils.launchCamera(WordPressMediaUtils.java:137)
       at org.wordpress.android.ui.media.MediaAddFragment.launchCamera(MediaAddFragment.java:235)
       at org.wordpress.android.ui.media.MediaBrowserActivity$3.onItemClick(MediaBrowserActivity.java:216)
       at android.widget.AdapterView.performItemClick(AdapterView.java:310)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1194)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3239)
       at android.widget.AbsListView$3.run(AbsListView.java:4192)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5660)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
```

### PR DESCRIPTION
**Pull request by daniloercoli**
Fixes #5455 by checking file planned to store the new recording/new picture.

To test:
- Start a new post 
- Took a picture
- Record a video

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/media/WordPressMediaUtils.java [hunk 1]
```diff
@@ -135,32 +135,46 @@ private static Intent preparelaunchCamera(Context context, String applicationId,
...
-                applicationId + ".provider", new File(mediaCapturePath)));
-
-        if (callback != null) {
-            callback.onMediaCapturePathReady(mediaCapturePath);
-        }
 
         // make sure the directory we plan to store the recording in exists
         File directory = new File(mediaCapturePath).getParentFile();
-        if (!directory.exists() && !directory.mkdirs()) {
+        if (directory == null | (!directory.exists() && !directory.mkdirs())) {
```
Comment (tonyr59h) [inline WordPress/src/main/java/org/wordpress/android/ui/media/WordPressMediaUtils.java]: This should be `||`?

Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/ui/media/WordPressMediaUtils.java]: :man_facepalming:

**Comment by tonyr59h** [comment]
Looks good :shipit:
