### PR TITLE
Fix order of processing OnPostChanged event

### LINKED ISSUE #10546: Stuck uploading draft label on a post list item
Test Offline-SelfHosted-11

When I click “Retry” the media does get uploaded, but then the message changes to “Uploading draft” and never goes away (at least not after waiting for more than 5 minutes). I checked wp-admin and the draft was not uploaded. 

### Steps to reproduce the behavior

1. Airplane mode on, Draft tab selected
2. Add an image to an existing draft from the post list
3. Tap back
4. “Couldn’t upload media” label is visible
5. Turn off airplane mode
6. Nothing should be auto-uploaded
7. Click on “Retry”
8. Media file should be uploaded, but the draft shouldn’t be uploaded
9. Notice the "Uploading post" label is displayed (it's caused by a race condition so the issue doesn't occur during each test)

##### Tested on [device], Android [version], WPAndroid [version]
Samsung Galaxy S9 (Android 9)

### PR DESCRIPTION
**Pull request by malinajirka**
Fixes #10546 

This PR fixes a race condition which sometimes resulted in an invalid "Uploading post" UI state.

The issue was caused by the order in which the OnPostChanged event was being processed. More detailed explanation with examples can be found [here](https://github.com/wordpress-mobile/WordPress-Android/issues/10546#issuecomment-536997849).

This PR sets a priority to `PostListEventListener.onPostChanged` observer. We also need to change its `threadMode` to Main as the priority is tied to the threadMode (in other words if you have an observer with threadMode Main and another observer with threadMode background, the priorities are ignored). I used a coroutine to make sure the body of the method is processed on a background thread as before. 

To test - use a self-hosted site
1. Airplane mode on, Draft tab selected
2. Add an image to an existing draft from the post list
3. Tap back
4. “Couldn’t upload media” label is visible
5. Turn off airplane mode
6. Nothing should be auto-uploaded
7. Click on “Retry”
8. Media file should be uploaded, but the draft shouldn’t be uploaded
9. Make sure the "Uploading post" label either doesn't appear at all or appears just for a bit -> "Local changes" label should be visible
- perform these steps several times as the issue was caused by a race condition so it occurred just once in a while (cca 1 out of 3 attempts).

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: WordPress/src/main/java/org/wordpress/android/ui/posts/PostListEventListener.kt [hunk 1]
```diff
@@ -83,63 +95,73 @@ class PostListEventListener(
...
 
+    /**
+     * Has lower priority than the PostUploadHandler and UploadService, which ensures that they already processed this
+     * OnPostChanged event. This means we can safely rely on their internal state being up to date.
+     */
     @Suppress("unused")
-    @Subscribe(threadMode = BACKGROUND)
+    @Subscribe(threadMode = MAIN, priority = 5)
     fun onPostChanged(event: OnPostChanged) {
-        when (event.causeOfChange) {
```
Comment (malinajirka) [inline WordPress/src/main/java/org/wordpress/android/ui/posts/PostListEventListener.kt]: I just wrapped the body of the method with `launch`. I'm not sure why GitHub's diff looks so complicated.

Comment (oguzkocer) [reply WordPress/src/main/java/org/wordpress/android/ui/posts/PostListEventListener.kt]: You can use the ` Hide whitespace changes` setting at the top of the page (under Settings icon) to make it easier to see the changes.

**Comment by malinajirka** [comment]
>but I am not sure if it is the best solution.

💯 

>I feel the use of priorities in general is a bad smell

💯 💯 (Btw I feel the same way about most of our usages of EventBus 🤷‍♂)

>I think it should be possible to leverage the LIST_ITEMS_CHANGED action in the UploadStore for this, but I don't think this is the right time to dig into that.

Tbh I feel like adding List_items_changed event all over the place isn't exactly the best solution either. I think the proper solution for this particular scenario would be creating a brand new event which would be invoked when the UploadService processes the  `OnPostChanged`. But as you said `there are some hard to refactor pieces we need to work with`.


Thank you for the review!!!
