### PR TITLE
Issue/4659 notifications service

### LINKED ISSUE #4602: Notifications: "Like" button shouldn't open the app
### Expected behavior
When I click the Like button in a notification I expect to remain in whatever app I'm currently using

### Actual behavior
I'm taken out of my current activity and placed into the WordPress app's notification view.  I'd much rather just get a toast message indicating success/failure rather than having the whole app open up and interrupt whatever else I'm doing.  This can be especially jarring when I interact with the notification from my Android Wear watch, since then the next time I unlock my phone it's in a different app from where I left it.

I'm labelling the issue with _[Type] Bug_, but if others feel strongly that this is the desired behavior it can be re-labelled an _Enhancement_ and worked on later

### Steps to reproduce the behavior
Receive a notification of a comment, and click Like

### LINKED ISSUE #4659: Notifications: service for background processing - master issue
After a first approach to implementing quick actions (#4523) and voice reply (#4032)  on Notifications it follows it would be expected for these actions to be self-contained and have as less user interaction as possible after user has made a decision and acted upon a notification (#4602).
For this, a service that actually takes care of "liking" ,  "approving", or "replying" would have to be done, so the user doesn't need to follow these actions on-screen.
Furthermore, having this kind of service would also allow us to solve #4657 as well, improving overall UX for Notifications.

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #4659 

This service implements processing of Like/Approve/Voice reply quick actions.

To test:
1. log in to WPAndroid and log in on another device / a browser with some other account
2. make a comment to a comment/post of yours
3. you'd receive a notification with actions REPLY/APPROVE if your blog is set for comments to be moderated, or REPLY/LIKE if your blog is set for comments to be automatically published
4. If you click APPROVE/LIKE the magic should happen in the background. You'll see a "updating" infinite progress bar notification so you're aware your action is being taken care of.
5. If it goes well, a 3-second notification with a successful message is shown, and the original notification is dismissed.
6. If anything goes wrong (i.e. no internet connection available to actually fulfill your request), a permanent message is shown, and the original notification is kept so you can try again.

While this is the basis for something bigger (#4659), this particularly fixes #4602, and means an enhancement of quick actions (#4523) and voice reply (#4032).
I'll continue to work on #4657 after this one is merged.

cc @daniloercoli @hoverduck

### CODE REVIEW

**Comment by daniloercoli** [comment]
Hey @kwonye, which designer is going to review this PR?

**Comment by kwonye** [comment]
> Hey @kwonye, which designer is going to review this PR?

@daniloercoli let's have @drw158 give it the 👍 before we :shipit:

File: WordPress/src/main/java/org/wordpress/android/push/GCMMessageService.java [hunk 1]
```diff
@@ -339,23 +340,17 @@ private void addCommentApproveActionForCommentNotification(NotificationCompat.Bu
...
         commentApproveIntent.addCategory(KEY_CATEGORY_COMMENT_MODERATE);
-        commentApproveIntent.putExtra(NotificationsListFragment.NOTE_INSTANT_APPROVE_EXTRA, true);
+        commentApproveIntent.putExtra(NotificationsProcessingService.ARG_ACTION_TYPE, NotificationsProcessingService.ARG_ACTION_APPROVE);
         if (noteId != null) {
-            commentApproveIntent.putExtra(NotificationsListFragment.NOTE_ID_EXTRA, noteId);
+            commentApproveIntent.putExtra(NotificationsProcessingService.ARG_NOTE_ID, noteId);
         }
-        PendingIntent commentApprovePendingIntent = PendingIntent.getActivity(this, 0, commentApproveIntent,
-                PendingIntent.FLAG_CANCEL_CURRENT);
+        PendingIntent commentApprovePendingIntent =  PendingIntent.getService(this, 0, commentApproveIntent, PendingIntent.FLAG_UPDATE_CURRENT);
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/push/GCMMessageService.java]: It has been a long time since I wrote a Android Service, so my memory could be a little rusty on the topic. I've a couple of questions about starting a service with the `FLAG_UPDATE_CURRENT`.

Are we sure that `FLAG_UPDATE_CURRENT` does't give problems in case of multiple distinct notifications on the status bar?

Similar to the question above, but when the user taps Like twice in a row. EX: The user taps Like on the 1st comment, the service is started its networking, and in the meanwhile a new PN for a new comment arrives on the device. The user taps "like" on this 2nd notification... 

I think, if we want to handle multiple moderation/liking cases, we should set the the `requestCode` when getting the intent, so we can 2 or more intents at the same time. `int uniqueCodeID = new Random().nextInt(9999)` or `int uniqueCodeID = noteId` and then we can use `FLAG_UPDATE_CURRENT`. Request code could also be used later to show UI updates to the end users.

**Comment by kwonye** [comment]
UI-wise could we have something like this? (I clicked the archive quick action) 

https://cloudup.com/cNdibwu9JJK

File: WordPress/src/main/java/org/wordpress/android/push/GCMMessageService.java (hunk 1 above)
Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/push/GCMMessageService.java]: ok fixed this in this commit https://github.com/wordpress-mobile/WordPress-Android/pull/4667/commits/3c7a7a434aae136476abc8b4ae56dcba14be00ec

+ changed the UPDATE for the CANCEL flag
+ added a thread per each call to the service so we can make sure these run in parallel
However, at this very point in time there is very little possibility to have 2 quick actions to be executed at the same time, because if we have 2 pending notifications these are grouped together (so no quick actions are shown at all), and in the case 1 unique notification is shown, showing the REPLY and the LIKE/APPROVE actions at the same time, for instance, the only time when this could potentially happen is the case that a user would hit REPLY, write the reply in the direct reply field, and then LIKE rapidly right after hitting SEND. Anyway, if it happens, it’s handled by this threading mechanism now.
I've tested this by adding a `sleep` call in line 155 in `NotificationsProcessingService.java`, here https://github.com/wordpress-mobile/WordPress-Android/blob/issue/4659-notifications-service/WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java#L154 (it's of course a blank line now)
+ I also evaluated  using `IntentService` instead of `Service`, but I preferred to handle actions in parallel using threads as to keep this available for the future (IntentService would queue intents and that might not be what we really want as a UX behavior.)

Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/push/GCMMessageService.java]: just in case you want to see what an implementation using `IntentService` would look and behave like, here's the branch were I did my tests (it injects a 5 second delay in each operation so we can see how it is like having to wait for each triggered action to get to completion - it's not worth it fwiw).
Branch here: https://github.com/wordpress-mobile/WordPress-Android/tree/issue/4659-notifications-service-intentservice

File: WordPress/src/main/java/org/wordpress/android/push/InstanceIDService.java [hunk 2]
```diff
@@ -1,9 +1,11 @@
-package org.wordpress.android;
+package org.wordpress.android.push;
 
 import android.content.Intent;
 
 import com.google.android.gms.iid.InstanceIDListenerService;
 
+import org.wordpress.android.push.GCMRegistrationIntentService;
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/push/InstanceIDService.java]: This is not required.

File: WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java [hunk 3]
```diff
@@ -0,0 +1,402 @@
...
+            NotificationCompat.Builder builder = getBuilder().setContentText(message).setTicker(message);
+            builder.setProgress(0, 0, intermediateMessage);
+
+            NotificationManagerCompat notificationManager = NotificationManagerCompat.from(mContext);
+            notificationManager.notify(ACTIONS_RESULT_NOTIFICATION_ID, builder.build());
+        }
+
+        private NotificationCompat.Builder getBuilder() {
+            String title = getString(R.string.app_name);
+            NotificationCompat.Builder builder = new NotificationCompat.Builder(mContext)
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java]: Local variable 'builder' is redundant.

File: WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java [hunk 4]
```diff
@@ -0,0 +1,402 @@
+package org.wordpress.android.push;
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java]: Would you mind to run Code Inspector on this file, and fix some of the suggestions?

File: WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java [hunk 5]
```diff
@@ -0,0 +1,402 @@
...
+public class NotificationsProcessingService extends Service {
+
+    public static final String ARG_ACTION_TYPE = "action_type";
+    public static final String ARG_ACTION_LIKE = "action_like";
+    public static final String ARG_ACTION_REPLY = "action_reply";
+    public static final String ARG_ACTION_APPROVE = "action_approve";
+    public static final String ARG_ACTION_REPLY_TEXT = "action_reply_text";
+    public static final String ARG_NOTE_ID = "note_id";
+
+    public static void startServiceForLike(Context context, String noteId) {
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java]: Can't find where this method is called.

File: WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java [hunk 6]
```diff
@@ -0,0 +1,402 @@
...
+        Intent intent = new Intent(context, NotificationsProcessingService.class);
+        intent.putExtra(ARG_ACTION_TYPE, ARG_ACTION_LIKE);
+        intent.putExtra(ARG_NOTE_ID, noteId);
+        context.startService(intent);
+    }
+
+    public static void startServiceForApprove(Context context, String noteId) {
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java]: This method doesn't seem to be used.

File: WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java [hunk 7]
```diff
@@ -0,0 +1,402 @@
...
+        Intent intent = new Intent(context, NotificationsProcessingService.class);
+        intent.putExtra(ARG_ACTION_TYPE, ARG_ACTION_APPROVE);
+        intent.putExtra(ARG_NOTE_ID, noteId);
+        context.startService(intent);
+    }
+
+    public static void startServiceForReply(Context context, String noteId, String replyToComment) {
```
Comment (daniloercoli) [inline WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java]: Same of above. Is it used?

Comment (mzorz) [inline WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java]: I should have added more comments there - yes these 3 methods are not used as of now, but I decided to leave them on purpose in case someone wants to run the service, as an interface for a potential user, so they don't need to build the intent with the right parameters by hand. They can just invoke any of these 3 params for having the service handle any of the 3 implemented actions (Reply/Like/Approve)

**Comment by daniloercoli** [comment]
This PR works fine for me! 👍 

A note for @drw158 - I would prefer something minimal on the UX front. Something more "Like and forget". The user taps the Like button, the original comment notification is removed from the notifications center, and no uploading indicator at all. Optimistic.
We will give feedback to the user in case of errors only. (This are my .2 cents, given by the experience I've used Whatzzapp).

**Comment by mzorz** [comment]
Generally speaking I prefer having feedback than not, so in this regard I like the indeterminate progress notification better, as this informs me that my action-intent is being processed and I should expect some output as a result from that. But anyway it's more of a personal taste rather than actually rooting this on any UX study :). Looking forward to hearing about Dave's view on this.

**Comment by mzorz** [comment]
Heads up @daniloercoli and @drw158 sorry for pinging again: the latest, more complete stuff in terms of Android versions and use case coverage is here https://github.com/wordpress-mobile/WordPress-Android/pull/4673#issuecomment-255863914
cc @kwonye

**Comment by daniloercoli** [comment]
:shipit:
