### PR TITLE
Fix bars turning green issue when switching from a graph with empty data 

### LINKED ISSUE #20413: The traffic chart bars are turning green
### Expected behavior
After changing metric types on the Traffic chart, the graph should remain accurate.

### Actual behavior
After changing metric types on the Traffic chart, the graph is turning green.

https://github.com/wordpress-mobile/jetpack-issue-repo/assets/7199140/5b919f29-8896-457e-ab5a-8ddb92ee5f8f

### Steps to reproduce the behavior
1. Log in.
2. Select a site with high stats data.
3. Open Site → Stats.
4. Change metrics type to Likes or Visitors.
5. Change the metrics type Views again.

### PR DESCRIPTION
**Pull request by aditi-bhatia**
Fixes #20413

This PR fixes an issue where bars for all graphs would turn a `gradient green` after navigating to a graph with empty data. Only categories with no data should display the `gradient green` bars and all other categories with data should have `blue` bars.

-----

## To Test:

1. While on the Stats Traffic tab, click a category with empty data. You can use the `mobile.blog` site for testing which currently has `0 comments` in the month view.
2. You should see a green gradient bar for any category with empty data. 
3. Navigate to `views` or any other category with data. The bars should change to `blue` and not remain `gradient green`.

Video of bug occurring after clicking `likes` or `comments` (empty data) and then navigating back to `views` or `visitors`: 

https://github.com/wordpress-mobile/WordPress-Android/assets/7199140/1d41751e-0de2-4628-a3bf-e4005b5ca3e0

-----

## Regression Notes

1. Potential unintended areas of impact

    - TODO

5. What I did to test those areas of impact (or what existing automated tests I relied on)

    - TODO

6. What automated tests I added (or what prevented me from doing so)

    - TODO

-----

## PR Submission Checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

-----

## Testing Checklist (strike-out the not-applying and unnecessary ones):

- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] Talkback.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] Large and small screen sizes. (Tablet and smaller phones)
- [ ] Multi-tasking: Split screen and Pop-up view. (Android 10 or higher)

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/traffic/TrafficBarChartViewHolder.kt [hunk 1]
```diff
@@ -178,6 +178,15 @@ class TrafficBarChartViewHolder(parent: ViewGroup) : BlockListItemViewHolder(
...
         dataSet.color = ContextCompat.getColor(context, R.color.blue_50)
+        dataSet.setGradientColor(
+            ContextCompat.getColor(
+                context,
+                R.color.blue_50
+            ), ContextCompat.getColor(
+                context,
+                R.color.blue_50
+            )
+        )
```
Comment (irfano) [inline WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/traffic/TrafficBarChartViewHolder.kt]: This appears to be a bug from the chart library. Although we're updating `dataSet` of the `BarChart`, `BarChart`s `BarChartRenderer` is still using gradient colors from the previous chart.
I see a minor side effect of setting gradient colors again here. It causes the chart to render gradient color as a single color, an unnecessary process from the performance perspective.
May I suggest a simpler alternative solution? By setting the shader to null, we can prevent `BarChartRenderer`s from drawing gradient. Wdyt?


```suggestion
        chart.renderer.paintRender.shader = null
        dataSet.color = ContextCompat.getColor(context, R.color.blue_50)
```

**Review by irfano — CHANGES_REQUESTED** [review]

File: WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/traffic/TrafficBarChartViewHolder.kt (hunk 1 above)
Comment (aditi-bhatia) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/traffic/TrafficBarChartViewHolder.kt]: Hi @irfano thanks for the suggestion! Yes, I agree that it's an issue with the library itself. I was concerned about the unnecessary process as well but noticed that `BarChartViewHolder` uses a similar workaround (lines 233-241 and 256-264): 

```        dataSet.setGradientColor(
            ContextCompat.getColor(
                context,
                R.color.stats_bar_chart_top
            ), ContextCompat.getColor(
                context,
                R.color.stats_bar_chart_top
            )
        )
```
I can go ahead and update the usage in `TrafficBarChartViewHolder`, but do you think it's a good idea to update these other occurrences as well?

Comment (irfano) [reply WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/traffic/TrafficBarChartViewHolder.kt]: Yes, I think we can update it on both places. I tested my suggestion and didn't notice any issues.

**Comment by aditi-bhatia** [comment]
Hi @irfano, I pushed the changes we discussed above so it's ready if you'd like to take another look. Thanks!

**Review by irfano — APPROVED** [review]
LGTM! 👍🏻
